# LSTM Autoencoder

## Load data

Set directory

In [2]:
import sys
import os

# Find the project root (Speciale_Kode)
current_dir = os.getcwd()
project_root = current_dir

# Looks for "Speciale_Kode" folder:
while os.path.basename(project_root) != "Speciale_Kode":
    project_root = os.path.dirname(project_root)

# Add to Python path
if project_root not in sys.path:
    sys.path.append(project_root)

Load data

In [3]:
import pandas as pd
from pathlib import Path
from Modules.read_data import read_data

PRICE_ZONE = "DK1"  # "DK1" or "DK2"
TRAIN_WINDOW = 2 * 8760
VAL_START = "2024-01-01 00:00:00"
VAL_WINDOW = 8784
PREDICT_PERIOD = 4 * 168
STRIDE = 13 * 168                           # Stride is measured from the start of the previous fold.
POST_VALIDATION_EXCLUDE_HOURS = 168         # Exclude first 168h after each validation window from remainder_2024_for_train
INCLUDE_REMAINING_2024_DURING_TRAINING = True
# DKPrice is handled internally by the encoder; it is NOT added as a feature column here.
INCLUDE_PRICE_HISTORY_AS_INPUT = False      # True -> incldues DKPrice as input.
INCLUDE_PRICE_LAG1_AS_INPUT = True        # True -> adds DKPrice_lag1 as an input feature regardless of INCLUDE_LAGS
INCLUDE_LAGS = False                        # Include lag features (Price_lag1, Price_lag24, etc.) in training input
USE_FORECASTED_HISTORY = True               # Use model-predicted prices to compute lag features during prediction

(
    DK1_train,
    DK1_test,
    DK2_train,
    DK2_test,
    DK1_train_weather,
    DK1_test_weather,
    DK2_train_weather,
    DK2_test_weather
) = read_data("combined_data_cleaned_v5.csv")

if PRICE_ZONE == "DK1":
    dataset_train = DK1_train.copy()
    dataset_test = DK1_test.copy()
elif PRICE_ZONE == "DK2":
    dataset_train = DK2_train.copy()
    dataset_test = DK2_test.copy()
else:
    raise ValueError("PRICE_ZONE must be 'DK1' or 'DK2'.")

# read_data already returns all of 2024 in dataset_train and all of 2025 in dataset_test.
# Build the custom 2024 rolling validation split entirely from dataset_train.
dataset_train = dataset_train.sort_values("Time").reset_index(drop=True)
dataset_test = dataset_test.sort_values("Time").reset_index(drop=True)

val_start_ts = pd.Timestamp(VAL_START)
year_2024_start = pd.Timestamp("2024-01-01 00:00:00")
year_2025_start = pd.Timestamp("2025-01-01 00:00:00")

# Keep legacy full timeline variable before redefining dataset_train below.
df = pd.concat([dataset_train, dataset_test], ignore_index=True).sort_values("Time").reset_index(drop=True)

# Fixed history block: TRAIN_WINDOW ending at VAL_START.
history = dataset_train.loc[dataset_train["Time"] < val_start_ts].copy().iloc[-TRAIN_WINDOW:]
if len(history) < TRAIN_WINDOW:
    raise ValueError(
        f"Not enough history for TRAIN_WINDOW={TRAIN_WINDOW}. Got {len(history)} rows before {VAL_START}."
    )

data_2024 = dataset_train.loc[
    (dataset_train["Time"] >= year_2024_start) & (dataset_train["Time"] < year_2025_start)
].copy()

validation_idx = []
validation_windows = []
window_start = val_start_ts

# Validation windows in 2024: next fold starts STRIDE hours after the current fold start.
# Only full windows are allowed; trailing partial windows are skipped.
while (window_start + pd.Timedelta(hours=PREDICT_PERIOD)) <= year_2025_start:
    window_end = window_start + pd.Timedelta(hours=PREDICT_PERIOD)
    if window_end <= window_start:
        break

    mask = (data_2024["Time"] >= window_start) & (data_2024["Time"] < window_end)
    if mask.any():
        validation_idx.extend(data_2024.index[mask].tolist())
        validation_windows.append((window_start, window_end))

    window_start = window_start + pd.Timedelta(hours=STRIDE)

validation_idx = sorted(set(validation_idx))

# Exclude first POST_VALIDATION_EXCLUDE_HOURS after each validation window from train remainder.
post_validation_exclusion_idx = []
for _, window_end in validation_windows:
    exclusion_end = min(window_end + pd.Timedelta(hours=POST_VALIDATION_EXCLUDE_HOURS), year_2025_start)
    if exclusion_end <= window_end:
        continue

    exclusion_mask = (data_2024["Time"] >= window_end) & (data_2024["Time"] < exclusion_end)
    if exclusion_mask.any():
        post_validation_exclusion_idx.extend(data_2024.index[exclusion_mask].tolist())

post_validation_exclusion_idx = sorted(set(post_validation_exclusion_idx))
excluded_from_remainder_idx = sorted(set(validation_idx).union(post_validation_exclusion_idx))

dataset_validation = data_2024.loc[validation_idx].copy().sort_values("Time").reset_index(drop=True)
remainder_2024_for_train = data_2024.drop(index=excluded_from_remainder_idx).copy().sort_values("Time").reset_index(drop=True)

# Load cell is the only place that decides whether 2024 remainder is included in training.
if INCLUDE_REMAINING_2024_DURING_TRAINING:
    dataset_train = (
        pd.concat([history, remainder_2024_for_train], ignore_index=True)
        .sort_values("Time")
        .drop_duplicates(subset=["Time"], keep="last")
        .reset_index(drop=True)
    )
else:
    dataset_train = history.copy().sort_values("Time").reset_index(drop=True)

# Full context dataset: pre-2024 history + all of 2024.
# Used by get_predictions for lag computation regardless of training flags.
dataset_context = (
    pd.concat([history, data_2024], ignore_index=True)
    .sort_values("Time")
    .drop_duplicates(subset=["Time"], keep="last")
    .reset_index(drop=True)
)

# Preserve full target-bearing datasets for training/evaluation and create input views for later cells.
dataset_train_full = dataset_train.copy()
dataset_validation_full = dataset_validation.copy()
dataset_train_input = dataset_train_full.copy()
dataset_validation_input = dataset_validation_full.copy()

if not INCLUDE_PRICE_HISTORY_AS_INPUT:
    dataset_train_input = dataset_train_input.drop(columns=["DKPrice"])
    dataset_validation_input = dataset_validation_input.drop(columns=["DKPrice"])

lag_columns = [c for c in dataset_train_input.columns if '_lag' in c]
if not INCLUDE_LAGS:
    dataset_train_input = dataset_train_input.drop(columns=lag_columns, errors='ignore')
    dataset_validation_input = dataset_validation_input.drop(
        columns=[c for c in dataset_validation_input.columns if '_lag' in c], errors='ignore'
    )

if INCLUDE_PRICE_LAG1_AS_INPUT:
    dataset_train_input["DKPrice_lag1"] = dataset_train_full["Price_lag1"].values
    dataset_validation_input["DKPrice_lag1"] = dataset_validation_full["Price_lag1"].values

# Keep 2025 as test set.
dataset_test = dataset_test.copy().reset_index(drop=True)

target_time = val_start_ts
prices = history["DKPrice"].astype(float).values.reshape(-1, 1)

def _load_feature_predictions_for_zone(zone):
    prediction_path = Path(project_root) / "Data" / f"feature_predictions_{zone}_2024-2025.csv"
    if not prediction_path.exists():
        print("No precomputed forecasts found.")
        return None

    predictions = pd.read_csv(prediction_path, sep=";", decimal=".", parse_dates=["Time"], dayfirst=True)
    predictions = predictions.loc[:, ~predictions.columns.duplicated()].copy()
    if "DKZone" in predictions.columns:
        predictions = predictions.loc[predictions["DKZone"] == zone].copy()
        print(f"Loaded {len(predictions)} forecasts for zone {zone}.")
        print(f"Forecast features: {len(predictions.columns)} {predictions.columns.tolist()}")
    return predictions

print(f"Using zone: {PRICE_ZONE}")
print(f"Train source shape (all of 2024): {DK1_train.shape if PRICE_ZONE == 'DK1' else DK2_train.shape}")
print(f"Test source shape (all of 2025): {DK1_test.shape if PRICE_ZONE == 'DK1' else DK2_test.shape}")
print(f"Include remainder_2024_for_train in training: {INCLUDE_REMAINING_2024_DURING_TRAINING}")
print(f"Include DKPrice in training input dataset: {INCLUDE_PRICE_HISTORY_AS_INPUT}")
print(f"Include lag features in training input: {INCLUDE_LAGS}")
print(f"Include DKPrice_lag1 as input: {INCLUDE_PRICE_LAG1_AS_INPUT}")
print(f"Use forecasted prices for lag computation during prediction: {USE_FORECASTED_HISTORY}")
print(f"Train shape (prepared training dataset): {dataset_train.shape}")
print(f"Training input shape: {dataset_train_input.shape}")
print(f"2024 remainder rows included in training: {len(remainder_2024_for_train) if INCLUDE_REMAINING_2024_DURING_TRAINING else 0}")
print(f"Validation shape (rolling 2024 windows): {dataset_validation.shape}")
print(f"Validation input shape: {dataset_validation_input.shape}")
print(f"Context shape (history + all 2024): {dataset_context.shape}")
print(f"Test shape (2025): {dataset_test.shape}")
print(f"Validation windows created: {len(validation_windows)}")
print(f"Post-validation exclusion hours: {POST_VALIDATION_EXCLUDE_HOURS}")
print(f"Rows excluded from remainder after validation windows: {len(post_validation_exclusion_idx)}")
if validation_windows:
    print("All validation windows:")
    for idx, (window_start, window_end) in enumerate(validation_windows, start=1):
        print(f"  {idx:02d}. {window_start} -> {window_end}")
print(f"Training dataset columns: {dataset_train.columns.tolist()}")
print(f"Training input columns: {dataset_train_input.columns.tolist()}")

feature_predictions = _load_feature_predictions_for_zone(PRICE_ZONE)    
if feature_predictions is not None:
    print("\nPrecomputed forecasts loaded.")

use_precomputed_feature_values = feature_predictions is not None

Notebook_dir: c:\Users\n_and\OneDrive\Delt skrivebord\Data Science\Speciale\Energinet\Delte scripts\Speciale_Kode\Modules
Python_dir: c:\Users\n_and\OneDrive\Delt skrivebord\Data Science\Speciale\Energinet\Delte scripts\Speciale_Kode
Data_folder: c:\Users\n_and\OneDrive\Delt skrivebord\Data Science\Speciale\Energinet\Delte scripts\Speciale_Kode\Data
Training data shape (DK1): (78888, 38)
Test data shape (DK1): (8760, 38)
Test set fraction (DK1): 9.99%
Training data shape (DK2): (78888, 38)
Test data shape (DK2): (8760, 38)
Test set fraction (DK2): 9.99%
Using zone: DK1
Train source shape (all of 2024): (78888, 38)
Test source shape (all of 2025): (8760, 38)
Include remainder_2024_for_train in training: True
Include DKPrice in training input dataset: False
Include lag features in training input: False
Include DKPrice_lag1 as input: True
Use forecasted prices for lag computation during prediction: True
Train shape (prepared training dataset): (22944, 38)
Training input shape: (22944, 34)
2024 remainder rows included in training: 5424
Validation shape (rolling 2024 windows): (2688, 38)
Validation input shape: (2688, 34)
Context shape (history + all 2024): (26304, 38)
Test shape (2025): (8760, 38)
Validation windows created: 4
Post-validation exclusion hours: 168
Rows excluded from remainder after validation windows: 672
All validation windows:
  01. 2024-01-01 00:00:00 -> 2024-01-29 00:00:00
  02. 2024-04-01 00:00:00 -> 2024-04-29 00:00:00
  03. 2024-07-01 00:00:00 -> 2024-07-29 00:00:00
  04. 2024-09-30 00:00:00 -> 2024-10-28 00:00:00
Training dataset columns: ['DKPrice', 'Time', 'OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'GrossCon_lag1', 'GrossCon_lag24', 'Price_lag1', 'Price_lag24']
Training input columns: ['Time', 'OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
Loaded 17544 forecasts for zone DK1.
Forecast features: 34 ['Time', 'DKZone', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'WindSpeed', 'Radiation', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'Biogas', 'Biomass', 'DEPrice', 'ExchangeGermany', 'ExchangeGreatBelt', 'ExchangeNetherlands', 'ExchangeNorway', 'ExchangeSweden', 'FossilGas', 'FossilHardCoal', 'FossilOil', 'GrossCon', 'HydroPower', 'NLPrice', 'NO2Price', 'OffshoreWindPower', 'OnshoreWindPower', 'SE3Price', 'SE4Price', 'SolarPower', 'TotalProduction', 'Waste']

Precomputed forecasts loaded.

Load Random Forest forecasting models

In [4]:
from Modules.Load_RF_forecast_models import load_rf_models

rf_models = None
if not use_precomputed_feature_values:
    # load_rf_models currently supports only the optional timeout argument.
    rf_models = load_rf_models(user="Nikolaj")      # set user to "Nikolaj" or "Christine"

Test CUDA

In [4]:
import torch

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("CUDA DIAGNOSTICS")
print("\nBasic Info:")
print(f"CUDA available: {torch.cuda.is_available()}")
print(f"Device: {device}")

if torch.cuda.is_available():
    print(f"\nGPU Info:")
    print(f"GPU Name: {torch.cuda.get_device_name(0)}")
    print(f"CUDA Version: {torch.version.cuda}")
    print(f"cuDNN Version: {torch.backends.cudnn.version()}")
    print(f"Device Count: {torch.cuda.device_count()}")

    test_tensor = torch.randn(100, 100).to(device)
    print(f"Tensor on CUDA: {test_tensor.is_cuda}")

else:
    print("\n  Running on CPU - no CUDA available")

CUDA DIAGNOSTICS

Basic Info:
CUDA available: True
Device: cuda

GPU Info:
GPU Name: NVIDIA GeForce RTX 5060 Ti
CUDA Version: 12.8
cuDNN Version: 91002
Device Count: 1
Tensor on CUDA: True

### Helper functions

In [5]:
import numpy as np
import torch
import torch.nn as nn
from sklearn.base import BaseEstimator, RegressorMixin
from torch.utils.data import DataLoader, Dataset


def set_seed(seed: int) -> None:
    torch.manual_seed(seed)
    np.random.seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)


def smape_mean(y_true: np.ndarray, y_pred: np.ndarray) -> float:
    denom = np.abs(y_true) + np.abs(y_pred)
    vals = np.where(denom == 0, 0.0, 200.0 * np.abs(y_pred - y_true) / denom)
    return float(np.mean(vals))


# ---------------------------------------------------------------------------
# Seq2Seq Dataset
# ---------------------------------------------------------------------------

class Seq2SeqDataset(Dataset):
    """
    Builds encoder/decoder/target triplets on-the-fly for seq2seq training.

    For each valid index i in [seq_len, n_samples - horizon):
      encoder_input  = concat(X[i-seq_len:i], y[i-seq_len:i].reshape(-1,1))
                       shape (seq_len, n_features + 1)  – scaled features + unscaled DKPrice
      decoder_input  = X[i : i+horizon]
                       shape (horizon, n_features)       – scaled future features
      target         = y[i : i+horizon]
                       shape (horizon,)                  – future DKPrice values
    """

    def __init__(self, X_np: np.ndarray, y_np: np.ndarray, seq_len: int, horizon: int):
        self.X = X_np
        self.y = y_np
        self.seq_len = seq_len
        self.horizon = horizon
        self.n_valid = max(0, len(X_np) - seq_len - horizon + 1)

    def __len__(self) -> int:
        return self.n_valid

    def __getitem__(self, idx: int):
        i = idx + self.seq_len
        enc_x = self.X[i - self.seq_len : i]                          # (seq_len, n_features)
        enc_price = self.y[i - self.seq_len : i].reshape(-1, 1)       # (seq_len, 1)
        encoder_input = np.concatenate([enc_x, enc_price], axis=1)    # (seq_len, n_features+1)
        decoder_input = self.X[i : i + self.horizon]                  # (horizon, n_features)
        target = self.y[i : i + self.horizon]                         # (horizon,)
        return (
            torch.tensor(encoder_input, dtype=torch.float32),
            torch.tensor(decoder_input, dtype=torch.float32),
            torch.tensor(target, dtype=torch.float32),
        )


# ---------------------------------------------------------------------------
# LSTM Autoencoder module
# ---------------------------------------------------------------------------

class LSTMAutoencoder(nn.Module):
    """
    Seq2seq LSTM Autoencoder for multi-step price forecasting.

    Architecture (based on Option 1 in the design document):
      1. Feature encoder  – a small dense MLP applied per timestep that
                            compresses (n_features + 1) inputs to latent_dim.
      2. Encoder LSTM     – processes the latent sequence and produces a
                            compressed hidden state.
      3. Decoder LSTM     – initialised with the encoder's final hidden state
                            and fed future feature forecasts; outputs
                            decoder_horizon price predictions.

    Parameters
    ----------
    encoder_input_size : int
        Number of encoder input features per timestep (n_features + 1 for DKPrice).
    decoder_input_size : int
        Number of decoder input features per timestep (n_features, no DKPrice).
    latent_dim : int
        Output dimension of the per-timestep feature encoder.
    encoder_hidden_size : int
        Hidden size of the encoder LSTM.
    decoder_hidden_size : int
        Hidden size of the decoder LSTM.
    layers : int
        Number of LSTM layers (shared between encoder and decoder).
    dense_layers : int
        Depth of the per-timestep feature encoder MLP (>=1).
    dropout : float
        Dropout applied between LSTM layers (only active when layers > 1).
    """

    def __init__(
        self,
        encoder_input_size: int,
        decoder_input_size: int,
        latent_dim: int = 16,
        encoder_hidden_size: int = 64,
        decoder_hidden_size: int = 64,
        layers: int = 1,
        dense_layers: int = 1,
        dropout: float = 0.0,
    ):
        super().__init__()

        # --- Feature encoder (dense MLP applied per timestep) ---
        enc_layers = []
        in_size = encoder_input_size
        for _ in range(dense_layers - 1):
            enc_layers.append(nn.Linear(in_size, latent_dim))
            enc_layers.append(nn.ReLU())
            if dropout > 0.0:
                enc_layers.append(nn.Dropout(dropout))
            in_size = latent_dim
        enc_layers.append(nn.Linear(in_size, latent_dim))
        self.feature_encoder = nn.Sequential(*enc_layers)

        lstm_dropout = dropout if layers > 1 else 0.0

        # --- Encoder LSTM ---
        self.encoder_lstm = nn.LSTM(
            input_size=latent_dim,
            hidden_size=encoder_hidden_size,
            num_layers=layers,
            dropout=lstm_dropout,
            batch_first=True,
        )

        # --- Optional hidden-state adapter ---
        self.needs_adapter = (encoder_hidden_size != decoder_hidden_size)
        if self.needs_adapter:
            self.hidden_adapter = nn.Linear(encoder_hidden_size, decoder_hidden_size)

        # --- Decoder LSTM ---
        self.decoder_lstm = nn.LSTM(
            input_size=decoder_input_size,
            hidden_size=decoder_hidden_size,
            num_layers=layers,
            dropout=lstm_dropout,
            batch_first=True,
        )

        # --- Output projection ---
        self.fc = nn.Linear(decoder_hidden_size, 1)

    def forward(self, encoder_x: torch.Tensor, decoder_x: torch.Tensor) -> torch.Tensor:
        """
        Parameters
        ----------
        encoder_x : Tensor of shape (batch, seq_len, encoder_input_size)
        decoder_x : Tensor of shape (batch, horizon, decoder_input_size)

        Returns
        -------
        Tensor of shape (batch, horizon)
        """
        # Feature encoding applied identically to every timestep
        latent = self.feature_encoder(encoder_x)          # (batch, seq_len, latent_dim)

        # Encoder LSTM – only final hidden state is used
        _, (h_enc, c_enc) = self.encoder_lstm(latent)     # (layers, batch, enc_hidden)

        # Adapt hidden state dimensions if encoder/decoder sizes differ
        if self.needs_adapter:
            h_dec = self.hidden_adapter(h_enc)
            c_dec = self.hidden_adapter(c_enc)
        else:
            h_dec, c_dec = h_enc, c_enc

        # Decoder LSTM initialized with encoder's final state
        out, _ = self.decoder_lstm(decoder_x, (h_dec, c_dec))  # (batch, horizon, dec_hidden)

        return self.fc(out).squeeze(-1)                    # (batch, horizon)


# ---------------------------------------------------------------------------
# Scikit-learn compatible regressor
# ---------------------------------------------------------------------------

class TorchLSTMAERegressor(BaseEstimator, RegressorMixin):
    """
    Scikit-learn style regressor wrapping LSTMAutoencoder.

    fit(X, y)
        X : (n_samples, n_features) – pre-scaled feature matrix (DKPrice excluded).
        y : (n_samples,)            – raw DKPrice target values.
        Internally builds Seq2SeqDataset and trains the seq2seq model.

    predict_ae(encoder_x, decoder_x)
        Used by week_predictions2_AE.get_predictions() for block inference.
        encoder_x : (1, seq_len, n_features+1) – scaled features + unscaled DKPrice
        decoder_x : (1, horizon, n_features)   – scaled future features
        Returns   : (horizon,) predicted prices.

    predict(X)
        2D fallback interface for SHAP / sklearn compatibility.
        Each row of X is broadcast to a constant 168-step decoder sequence;
        a zero encoder input is used as neutral baseline.
        Returns the mean prediction across the horizon.
    """

    def __init__(
        self,
        latent_dim: int = 16,
        encoder_hidden_size: int = 64,
        decoder_hidden_size: int = 64,
        layers: int = 1,
        dense_layers: int = 1,
        learning_rate: float = 1e-3,
        epochs: int = 40,
        batch_size: int = 32,
        sequence_length: int = 168,
        decoder_horizon: int = 168,
        dropout: float = 0.0,
        random_state: int = 42,
        log_epoch_metrics: bool = False,
        log_prefix: str = "",
        warm_start: bool = False,
    ):
        self.latent_dim = latent_dim
        self.encoder_hidden_size = encoder_hidden_size
        self.decoder_hidden_size = decoder_hidden_size
        self.layers = layers
        self.dense_layers = dense_layers
        self.learning_rate = learning_rate
        self.epochs = epochs
        self.batch_size = batch_size
        self.sequence_length = sequence_length
        self.decoder_horizon = decoder_horizon
        self.dropout = dropout
        self.random_state = random_state
        self.log_epoch_metrics = log_epoch_metrics
        self.log_prefix = log_prefix
        self.warm_start = warm_start

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------

    def _initialize_model_state(self, encoder_input_size: int, decoder_input_size: int):
        self.device_ = torch.device("cuda" if torch.cuda.is_available() else "cpu")
        self.pin_memory_ = self.device_.type == "cuda"
        self.encoder_input_size_ = int(encoder_input_size)
        self.decoder_input_size_ = int(decoder_input_size)
        self.model_ = LSTMAutoencoder(
            encoder_input_size=self.encoder_input_size_,
            decoder_input_size=self.decoder_input_size_,
            latent_dim=int(self.latent_dim),
            encoder_hidden_size=int(self.encoder_hidden_size),
            decoder_hidden_size=int(self.decoder_hidden_size),
            layers=int(self.layers),
            dense_layers=int(self.dense_layers),
            dropout=float(self.dropout),
        ).to(self.device_)

        # Load pretrained feature encoder weights from Stage 1 (if set via
        # set_pretrained_encoder()).  Encoder params are frozen when freeze=True,
        # so the optimizer below excludes them automatically.
        _sd = getattr(self, "_pretrained_encoder_state_dict_", None)
        if _sd is not None:
            self.model_.feature_encoder.load_state_dict(_sd)
            if getattr(self, "_freeze_encoder_", True):
                for p in self.model_.feature_encoder.parameters():
                    p.requires_grad = False

        self.loss_fn_ = nn.MSELoss()
        # Only pass parameters that require gradients so frozen encoder layers
        # are not updated even if the optimizer sees them.
        self.optimizer_ = torch.optim.Adam(
            filter(lambda p: p.requires_grad, self.model_.parameters()),
            lr=float(self.learning_rate),
        )
        self.epoch_losses_ = []
        self.epoch_smapes_ = []
        self.epoch_maes_ = []
        self.epoch_rmses_ = []
        self._epochs_trained_ = 0

    # ------------------------------------------------------------------
    # set_pretrained_encoder
    # ------------------------------------------------------------------

    def set_pretrained_encoder(
        self, state_dict: dict, freeze: bool = True
    ) -> "TorchLSTMAERegressor":
        """
        Store pretrained feature encoder weights to be loaded at the next model
        initialisation (i.e. the first fit() call, or when warm_start=False).

        Call this before the first fit() / run_cross_validation() call so the
        weights are in place when _initialize_model_state() creates model_.

        Parameters
        ----------
        state_dict : OrderedDict returned by FeatureAutoencoder.encoder.state_dict()
                     (i.e. ``result["best_encoder_state_dict"]`` from Stage 1).
        freeze     : if True the feature_encoder parameters are frozen so only
                     the encoder/decoder LSTM and output layers are updated
                     during Stage 2 training.
        """
        import copy as _copy
        self._pretrained_encoder_state_dict_ = _copy.deepcopy(state_dict)
        self._freeze_encoder_ = freeze
        return self

    # ------------------------------------------------------------------
    # fit
    # ------------------------------------------------------------------

    def fit(self, X, y):
        set_seed(self.random_state)

        X_np = np.asarray(X, dtype=np.float32)
        y_np = np.asarray(y, dtype=np.float32).reshape(-1)

        if X_np.ndim != 2:
            raise ValueError(f"Expected 2-D X, got shape {X_np.shape}.")

        n_decoder_features = X_np.shape[1]
        n_encoder_features = n_decoder_features + 1   # features + DKPrice
        seq_len = int(self.sequence_length)
        horizon = int(self.decoder_horizon)

        # Build or reuse the dataset (reused across warm-start epochs for speed)
        needs_rebuild = (
            not hasattr(self, "_train_dataset_")
            or getattr(self, "_train_X_shape_", None) != X_np.shape
            or getattr(self, "_train_y_len_", None) != len(y_np)
        )
        if needs_rebuild:
            self._train_dataset_ = Seq2SeqDataset(X_np, y_np, seq_len, horizon)
            self._train_X_shape_ = X_np.shape
            self._train_y_len_ = len(y_np)

        if len(self._train_dataset_) == 0:
            raise ValueError(
                f"Training set too small to build any seq2seq sample "
                f"(need > seq_len+horizon={seq_len+horizon} rows, got {len(X_np)})."
            )

        # Initialise or reuse the model
        needs_reinit = (
            (not bool(self.warm_start))
            or (not hasattr(self, "model_"))
            or (not hasattr(self, "encoder_input_size_"))
            or (int(self.encoder_input_size_) != n_encoder_features)
            or (int(self.decoder_input_size_) != n_decoder_features)
        )
        if needs_reinit:
            self._initialize_model_state(
                encoder_input_size=n_encoder_features,
                decoder_input_size=n_decoder_features,
            )
        elif not hasattr(self, "device_"):
            self.device_ = next(self.model_.parameters()).device
            self.pin_memory_ = self.device_.type == "cuda"

        loader = DataLoader(
            self._train_dataset_,
            batch_size=int(self.batch_size),
            shuffle=True,
            pin_memory=self.pin_memory_,
        )

        self.model_.train()
        for _ in range(int(self.epochs)):
            batch_losses = []
            epoch_preds = []
            epoch_targets = []

            for enc_batch, dec_batch, tgt_batch in loader:
                enc_batch = enc_batch.to(self.device_, non_blocking=self.pin_memory_)
                dec_batch = dec_batch.to(self.device_, non_blocking=self.pin_memory_)
                tgt_batch = tgt_batch.to(self.device_, non_blocking=self.pin_memory_)

                self.optimizer_.zero_grad()
                preds = self.model_(enc_batch, dec_batch)   # (batch, horizon)
                loss = self.loss_fn_(preds, tgt_batch)
                loss.backward()
                self.optimizer_.step()

                batch_losses.append(float(loss.item()))
                epoch_preds.append(preds.detach().cpu().numpy().reshape(-1))
                epoch_targets.append(tgt_batch.detach().cpu().numpy().reshape(-1))

            epoch_loss = float(np.mean(batch_losses)) if batch_losses else float("nan")
            self.epoch_losses_.append(epoch_loss)

            if epoch_preds and epoch_targets:
                y_pred_epoch = np.concatenate(epoch_preds)
                y_true_epoch = np.concatenate(epoch_targets)
                epoch_smape = smape_mean(y_true_epoch, y_pred_epoch)
                epoch_mae = float(np.mean(np.abs(y_true_epoch - y_pred_epoch)))
                epoch_rmse = float(np.sqrt(np.mean((y_true_epoch - y_pred_epoch) ** 2)))
            else:
                epoch_smape = epoch_mae = epoch_rmse = float("nan")

            self.epoch_smapes_.append(float(epoch_smape))
            self.epoch_maes_.append(float(epoch_mae))
            self.epoch_rmses_.append(float(epoch_rmse))
            self._epochs_trained_ += 1

            if bool(self.log_epoch_metrics):
                try:
                    import wandb
                    if wandb.run is not None:
                        pfx = self.log_prefix
                        wandb.log({
                            f"{pfx}train_MSE_loss" if pfx else "train_MSE_loss": epoch_loss,
                            f"{pfx}train_smape"    if pfx else "train_smape":    float(epoch_smape),
                            f"{pfx}train_mae"      if pfx else "train_mae":      float(epoch_mae),
                            f"{pfx}train_rmse"     if pfx else "train_rmse":     float(epoch_rmse),
                            f"{pfx}epoch"          if pfx else "epoch":          int(self._epochs_trained_),
                        })
                except Exception:
                    pass

        return self

    # ------------------------------------------------------------------
    # predict_ae  (primary inference path used by week_predictions2_AE)
    # ------------------------------------------------------------------

    def predict_ae(self, encoder_x: np.ndarray, decoder_x: np.ndarray) -> np.ndarray:
        """
        Predict one 168-hour block in a single forward pass.

        Parameters
        ----------
        encoder_x : ndarray of shape (1, seq_len, n_features+1)
            Scaled historical features concatenated with unscaled DKPrice.
        decoder_x : ndarray of shape (1, horizon, n_features)
            Scaled future feature forecasts.

        Returns
        -------
        ndarray of shape (horizon,)
        """
        self.model_.eval()
        enc_t = torch.tensor(encoder_x, dtype=torch.float32).to(self.device_)
        dec_t = torch.tensor(decoder_x, dtype=torch.float32).to(self.device_)
        with torch.no_grad():
            out = self.model_(enc_t, dec_t)    # (1, horizon)
        return out.squeeze(0).detach().cpu().numpy()

    # ------------------------------------------------------------------
    # predict  (2-D fallback for SHAP / sklearn compatibility)
    # ------------------------------------------------------------------

    def predict(self, X) -> np.ndarray:
        """
        2-D input interface for SHAP / sklearn compatibility.

        Each row of X is broadcast to a constant `decoder_horizon`-step decoder
        sequence.  A zero encoder input is used as a neutral baseline.
        Returns the mean prediction across the horizon for each sample.
        """
        X_np = np.asarray(X, dtype=np.float32)
        if X_np.ndim != 2:
            raise ValueError(
                f"predict() expects 2-D X; got shape {X_np.shape}. "
                "For block inference use predict_ae(encoder_x, decoder_x)."
            )

        n_samples, n_features = X_np.shape
        horizon = int(self.decoder_horizon)
        seq_len = int(self.sequence_length)

        # Neutral encoder (all zeros)
        enc_np = np.zeros((1, seq_len, n_features + 1), dtype=np.float32)
        enc_t = torch.tensor(enc_np, dtype=torch.float32).to(self.device_)

        self.model_.eval()
        preds = []
        with torch.no_grad():
            for i in range(n_samples):
                # Replicate single feature row across the full decoder horizon
                dec_np = np.tile(X_np[i : i + 1], (horizon, 1))[np.newaxis, :]  # (1, horizon, n)
                dec_t = torch.tensor(dec_np, dtype=torch.float32).to(self.device_)
                out = self.model_(enc_t, dec_t)   # (1, horizon)
                preds.append(float(out.mean().item()))

        return np.array(preds, dtype=np.float32)

## Hyperparameter search

### Step 1: Feature Encoder Search

Tune the per-timestep feature encoder MLP as a standalone autoencoder.  
Loss/evaluation metric: **SMAPE on reconstruction**.  
Optimal `latent_dim` and `dense_layers` are then carried forward into the full LSTM AE search.

In [6]:
import copy
import torch
import torch.nn as nn
import numpy as np
from torch.utils.data import DataLoader, TensorDataset


# ---------------------------------------------------------------------------
# Differentiable SMAPE loss
# ---------------------------------------------------------------------------

class SMAPELoss(nn.Module):
    """SMAPE loss: 200 * |y_pred - y_true| / (|y_true| + |y_pred| + eps)."""

    def __init__(self, eps: float = 1e-8):
        super().__init__()
        self.eps = eps

    def forward(self, y_pred: torch.Tensor, y_true: torch.Tensor) -> torch.Tensor:
        denom = torch.abs(y_true) + torch.abs(y_pred) + self.eps
        return torch.mean(200.0 * torch.abs(y_pred - y_true) / denom)


# ---------------------------------------------------------------------------
# Feature Autoencoder – mirrors the architecture of LSTMAutoencoder.feature_encoder
# ---------------------------------------------------------------------------

class FeatureAutoencoder(nn.Module):
    """
    Standalone autoencoder for tuning the per-timestep feature encoder MLP.

    Encoder architecture is identical to LSTMAutoencoder.feature_encoder:
      dense_layers=1 → single Linear(input_size → latent_dim)
      dense_layers=k → k-1 × [Linear → ReLU → (Dropout)] + final Linear → latent_dim

    Decoder mirrors the encoder (symmetric MLP from latent_dim back to input_size).

    Parameters
    ----------
    input_size  : number of features per timestep (n_features + 1 for DKPrice, same
                  as encoder_input_size in LSTMAutoencoder)
    latent_dim  : output dimension of the encoder (hyperparameter to tune)
    dense_layers: depth of the encoder/decoder MLP (≥1)
    dropout     : dropout rate applied between hidden layers (only if dense_layers > 1)
    """

    def __init__(
        self,
        input_size: int,
        latent_dim: int,
        dense_layers: int,
        dropout: float = 0.0,
    ):
        super().__init__()

        # ---- Encoder (same as LSTMAutoencoder.feature_encoder) ----
        enc = []
        in_sz = input_size
        for _ in range(dense_layers - 1):
            enc.append(nn.Linear(in_sz, latent_dim))
            enc.append(nn.ReLU())
            if dropout > 0.0:
                enc.append(nn.Dropout(dropout))
            in_sz = latent_dim
        enc.append(nn.Linear(in_sz, latent_dim))
        self.encoder = nn.Sequential(*enc)

        # ---- Decoder (symmetric) ----
        dec = []
        in_sz = latent_dim
        for _ in range(dense_layers - 1):
            dec.append(nn.Linear(in_sz, latent_dim))
            dec.append(nn.ReLU())
            if dropout > 0.0:
                dec.append(nn.Dropout(dropout))
            in_sz = latent_dim
        dec.append(nn.Linear(in_sz, input_size))
        self.decoder = nn.Sequential(*dec)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        return self.decoder(self.encoder(x))

    def encode(self, x: torch.Tensor) -> torch.Tensor:
        return self.encoder(x)


# ---------------------------------------------------------------------------
# Training helper
# ---------------------------------------------------------------------------

def train_feature_autoencoder(
    X_train: np.ndarray,
    X_val: np.ndarray,
    latent_dim: int,
    dense_layers: int,
    learning_rate: float,
    max_epochs: int,
    patience: int,
    batch_size: int,
    dropout: float = 0.0,
    random_state: int = 42,
    log_wandb: bool = False,
) -> dict:
    """
    Train a FeatureAutoencoder with SMAPE reconstruction loss.

    Parameters
    ----------
    X_train / X_val : float32 arrays of shape (n_samples, input_size).
                      Should be the scaled feature matrix concatenated with
                      raw DKPrice, matching the encoder input in Seq2SeqDataset.
    log_wandb       : whether to call wandb.log() per epoch.

    Returns
    -------
    dict with keys: best_val_smape, best_epoch, epochs_trained, epoch_history,
                    best_encoder_state_dict (state_dict of the encoder at best epoch,
                    ready to be loaded into LSTMAutoencoder.feature_encoder).
    """
    set_seed(random_state)
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    pin_memory = device.type == "cuda"

    input_size = X_train.shape[1]
    model = FeatureAutoencoder(
        input_size=input_size,
        latent_dim=latent_dim,
        dense_layers=dense_layers,
        dropout=dropout,
    ).to(device)

    criterion = SMAPELoss()
    optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate)

    train_t = torch.tensor(X_train, dtype=torch.float32)
    val_t = torch.tensor(X_val, dtype=torch.float32)

    loader = DataLoader(
        TensorDataset(train_t),
        batch_size=batch_size,
        shuffle=True,
        pin_memory=pin_memory,
    )

    best_val_smape = float("inf")
    best_epoch = 0
    patience_counter = 0
    epoch_history = []
    epoch = 0
    best_encoder_state_dict = None   # saved at the epoch with lowest val SMAPE

    for epoch in range(1, max_epochs + 1):
        model.train()
        batch_losses = []
        for (x_batch,) in loader:
            x_batch = x_batch.to(device, non_blocking=pin_memory)
            optimizer.zero_grad()
            recon = model(x_batch)
            loss = criterion(recon, x_batch)
            loss.backward()
            optimizer.step()
            batch_losses.append(float(loss.item()))

        train_smape = float(np.mean(batch_losses)) if batch_losses else float("nan")

        model.eval()
        with torch.no_grad():
            val_recon = model(val_t.to(device))
            val_smape = float(criterion(val_recon, val_t.to(device)).item())

        epoch_history.append({"epoch": epoch, "train_smape": train_smape, "val_smape": val_smape})

        if log_wandb:
            try:
                import wandb as _wandb
                _wandb.log({"epoch": epoch, "train_smape": train_smape, "val_smape": val_smape})
            except Exception:
                pass

        if val_smape < best_val_smape:
            best_val_smape = val_smape
            best_epoch = epoch
            patience_counter = 0
            # Snapshot the encoder weights at this best epoch
            best_encoder_state_dict = copy.deepcopy(model.encoder.state_dict())
        else:
            patience_counter += 1

        if patience_counter >= patience:
            break

    return {
        "best_val_smape": best_val_smape,
        "best_epoch": best_epoch,
        "epochs_trained": epoch,
        "epoch_history": epoch_history,
        "best_encoder_state_dict": best_encoder_state_dict,
    }

Feature encoder search grid

In [7]:
import numpy as np
from sklearn.preprocessing import StandardScaler

# ---------------------------------------------------------------------------
# Hyperparameter grid for the feature encoder autoencoder search
# ---------------------------------------------------------------------------

fe_param_grid = {
    "latent_dim":    [16, 24, 33, 38, 48],
    "dense_layers":  [1, 2, 3],
    "learning_rate": [0.001, 0.0005],
    "batch_size":    [32, 64],
    "dropout":       [0.0, 0.2],   # expand to [0.0, 0.1] if dense_layers > 1 is explored with dropout
    "max_epochs":    [60],
    "patience":      [10],
}

fe_total_combinations = int(np.prod([len(v) for v in fe_param_grid.values()]))

# When dense_layers == 1, dropout has no effect; those combinations are redundant.
_other_keys = [k for k in fe_param_grid if k not in ("dense_layers", "dropout")]
_n_other = int(np.prod([len(fe_param_grid[k]) for k in _other_keys]))
_n_redundant = _n_other * 1 * len([d for d in fe_param_grid["dropout"] if d != 0.0])
fe_effective_combinations = fe_total_combinations - _n_redundant
print(f"Feature encoder total combinations: {fe_total_combinations}")
print(f"Combinations after skipping dropout>0 with 1 layer: {fe_effective_combinations}")

# ---------------------------------------------------------------------------
# Prepare input data: scaled features + raw DKPrice
# (Matches the encoder input built in Seq2SeqDataset)
# ---------------------------------------------------------------------------

fe_feature_cols = [c for c in dataset_train_input.columns if c not in ["Time", "DKPrice"]]
print(f"Feature columns ({len(fe_feature_cols)}): {fe_feature_cols}")

fe_X_features = dataset_train_input[fe_feature_cols].astype(np.float32).values
fe_y_price    = dataset_train_full["DKPrice"].astype(np.float32).values.reshape(-1, 1)

# Fit scaler only on the feature part (DKPrice is kept raw, matching Seq2SeqDataset behaviour)
fe_scaler = StandardScaler()
fe_X_scaled = fe_scaler.fit_transform(fe_X_features).astype(np.float32)

# Final input matrix: [scaled_features | raw_DKPrice]
fe_X = np.concatenate([fe_X_scaled, fe_y_price], axis=1)

# Chronological 90/10 split (no shuffling – temporal data)
fe_split_idx = int(len(fe_X) * 0.9)
fe_X_train = fe_X[:fe_split_idx]
fe_X_val   = fe_X[fe_split_idx:]

print(f"Train samples: {len(fe_X_train)},  val samples: {len(fe_X_val)}")
print(f"Feature AE input size: {fe_X.shape[1]}  (= {len(fe_feature_cols)} features + 1 DKPrice)")

Feature encoder total combinations: 120
Combinations after skipping dropout>0 with 1 layer: 100
Feature columns (32): ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity']
Train samples: 20649,  val samples: 2295
Feature AE input size: 33  (= 32 features + 1 DKPrice)

Run feature encoder search

In [8]:
import itertools
import wandb
import pandas as pd
from pathlib import Path
from time import time

FE_WANDB_PROJECT    = f"FeatureEncoder_AE_search_exclPriceLag1_exclPrice{PRICE_ZONE}"
FE_WANDB_RUN_BASE   = f"{PRICE_ZONE}_"
FE_START_COMBINATION = 1   # resume from a specific combination number if needed

fe_param_names  = list(fe_param_grid.keys())
fe_param_values = list(fe_param_grid.values())
_dense_idx   = fe_param_names.index("dense_layers")
_dropout_idx = fe_param_names.index("dropout")
fe_combinations = [
    combo for combo in itertools.product(*fe_param_values)
    if not (combo[_dense_idx] == 1 and combo[_dropout_idx] != 0.0)
]
fe_num_combinations = len(fe_combinations)
print(f"Running {fe_num_combinations} feature encoder combinations (skipped dropout>0 with dense_layers==1)")

fe_results  = []
fe_start_ts = time()

# Global best across all Stage 1 combinations – exposed to Stage 2.
best_stage1_val_smape         = float("inf")
best_stage1_encoder_state_dict = None   # encoder weights at best reconstruction SMAPE
best_stage1_params            = None    # hyperparameters of the best combination

for comb_no, combination in enumerate(fe_combinations, start=1):
    params = dict(zip(fe_param_names, combination))

    if comb_no < FE_START_COMBINATION:
        continue

    elapsed_min  = (time() - fe_start_ts) / 60
    est_total    = elapsed_min / comb_no * fe_num_combinations if comb_no > 1 else float("nan")
    print(
        f"\nFE combination {comb_no}/{fe_num_combinations}: {params}  "
        f"[{elapsed_min:.1f} min elapsed, ~{est_total:.1f} min total]"
    )

    run_name = (FE_WANDB_RUN_BASE +
        f"latentdim{params['latent_dim']}_dense{params['dense_layers']}"
        f"_lr{params['learning_rate']}_batchsize{params['batch_size']}"
        f"_dropout{params['dropout']}_comb{comb_no:03d}"
    )

    run = wandb.init(
        project=FE_WANDB_PROJECT,
        name=run_name,
        config={
            "price_zone":       PRICE_ZONE,
            "fe_input_size":    int(fe_X.shape[1]),
            "train_samples":    int(len(fe_X_train)),
            "val_samples":      int(len(fe_X_val)),
            "combination":      int(comb_no),
            "num_combinations": int(fe_num_combinations),
            **params,
        },
        tags=["feature-encoder", "autoencoder", "hyperparameter-search", "smape"],
        reinit=True,
        settings=wandb.Settings(start_method="thread"),
    )

    try:
        result = train_feature_autoencoder(
            X_train=fe_X_train,
            X_val=fe_X_val,
            latent_dim=int(params["latent_dim"]),
            dense_layers=int(params["dense_layers"]),
            learning_rate=float(params["learning_rate"]),
            max_epochs=int(params["max_epochs"]),
            patience=int(params["patience"]),
            batch_size=int(params["batch_size"]),
            dropout=float(params["dropout"]),
            log_wandb=True,
        )

        row = {
            **params,
            "combination":      int(comb_no),
            "fe_input_size":    int(fe_X.shape[1]),
            "price_zone":       PRICE_ZONE,
            "best_val_smape":   float(result["best_val_smape"]),
            "best_epoch":       int(result["best_epoch"]),
            "epochs_trained":   int(result["epochs_trained"]),
        }
        fe_results.append(row)

        run.summary.update({
            "best_val_smape": float(result["best_val_smape"]),
            "best_epoch":     int(result["best_epoch"]),
            "epochs_trained": int(result["epochs_trained"]),
        })

        print(
            f"  -> best val SMAPE: {result['best_val_smape']:.4f}  "
            f"(epoch {result['best_epoch']}/{result['epochs_trained']})"
        )

        # Track the globally best encoder weights across all Stage 1 combinations
        if result["best_val_smape"] < best_stage1_val_smape:
            best_stage1_val_smape          = float(result["best_val_smape"])
            best_stage1_encoder_state_dict = result["best_encoder_state_dict"]
            best_stage1_params             = dict(params)
            print(f"  *** New global best: val SMAPE={best_stage1_val_smape:.4f} ***")

    finally:
        wandb.finish()

# ---- Save & display results ----
fe_results_df = pd.DataFrame(fe_results).sort_values("best_val_smape").reset_index(drop=True)

output_folder = Path(project_root) / "Deep learners" / "LSTM Autoencoder"
output_folder.mkdir(parents=True, exist_ok=True)

fe_base_name = f"{PRICE_ZONE}_feature_encoder_search_results"
fe_out_path  = output_folder / f"{fe_base_name}.csv"
_counter = 1
while fe_out_path.exists():
    fe_out_path = output_folder / f"{fe_base_name}_{_counter}.csv"
    _counter += 1

# fe_results_df.to_csv(fe_out_path, index=False, decimal=",")
# print(f"\nFeature encoder search results saved to: {fe_out_path}")

print("\nTop 10 configurations by val SMAPE:")
display(fe_results_df.head(10))

# ---- Summary of what Stage 2 will receive ----
print(
    f"\n=== Stage 1 complete – best encoder weights ready for Stage 2 ===\n"
    f"  latent_dim           : {best_stage1_params['latent_dim']}\n"
    f"  dense_layers         : {best_stage1_params['dense_layers']}\n"
    f"  best_val_smape (recon): {best_stage1_val_smape:.4f}\n"
    f"\n  best_stage1_encoder_state_dict is available for Stage 2.\n"
    f"  These weights will be loaded into LSTMAutoencoder.feature_encoder\n"
    f"  and frozen during Stage 2 LSTM tuning.")

wandb: WARNING `start_method` is deprecated and will be removed in a future version of wandb. This setting is currently non-functional and safely ignored.

Running 100 feature encoder combinations (skipped dropout>0 with dense_layers==1)

FE combination 1/100: {'latent_dim': 16, 'dense_layers': 1, 'learning_rate': 0.001, 'batch_size': 32, 'dropout': 0.0, 'max_epochs': 60, 'patience': 10}  [0.0 min elapsed, ~nan min total]

wandb: Currently logged in as: nande24 (Energinet_speciale) to https://api.wandb.ai. Use `wandb login --relogin` to force relogin
wandb: WARNING Using a boolean value for 'reinit' is deprecated. Use 'return_previous' or 'finish_previous' instead.

  -> best val SMAPE: 45.5865  (epoch 41/51)
  *** New global best: val SMAPE=45.5865 ***

FE combination 2/100: {'latent_dim': 16, 'dense_layers': 1, 'learning_rate': 0.001, 'batch_size': 64, 'dropout': 0.0, 'max_epochs': 60, 'patience': 10}  [0.8 min elapsed, ~38.6 min total]

  -> best val SMAPE: 52.2417  (epoch 45/55)

FE combination 3/100: {'latent_dim': 16, 'dense_layers': 1, 'learning_rate': 0.0005, 'batch_size': 32, 'dropout': 0.0, 'max_epochs': 60, 'patience': 10}  [1.2 min elapsed, ~38.4 min total]

  -> best val SMAPE: 53.1092  (epoch 59/60)

FE combination 4/100: {'latent_dim': 16, 'dense_layers': 1, 'learning_rate': 0.0005, 'batch_size': 64, 'dropout': 0.0, 'max_epochs': 60, 'patience': 10}  [1.9 min elapsed, ~47.4 min total]

  -> best val SMAPE: 66.1809  (epoch 60/60)

FE combination 5/100: {'latent_dim': 16, 'dense_layers': 2, 'learning_rate': 0.001, 'batch_size': 32, 'dropout': 0.0, 'max_epochs': 60, 'patience': 10}  [2.3 min elapsed, ~46.3 min total]

  -> best val SMAPE: 67.6154  (epoch 22/32)

FE combination 6/100: {'latent_dim': 16, 'dense_layers': 2, 'learning_rate': 0.001, 'batch_size': 32, 'dropout': 0.2, 'max_epochs': 60, 'patience': 10}  [2.8 min elapsed, ~47.4 min total]

  -> best val SMAPE: 84.3307  (epoch 58/60)

FE combination 7/100: {'latent_dim': 16, 'dense_layers': 2, 'learning_rate': 0.001, 'batch_size': 64, 'dropout': 0.0, 'max_epochs': 60, 'patience': 10}  [3.9 min elapsed, ~55.5 min total]

  -> best val SMAPE: 70.7768  (epoch 47/57)

FE combination 8/100: {'latent_dim': 16, 'dense_layers': 2, 'learning_rate': 0.001, 'batch_size': 64, 'dropout': 0.2, 'max_epochs': 60, 'patience': 10}  [4.4 min elapsed, ~54.6 min total]

  -> best val SMAPE: 86.5166  (epoch 48/58)

FE combination 9/100: {'latent_dim': 16, 'dense_layers': 2, 'learning_rate': 0.0005, 'batch_size': 32, 'dropout': 0.0, 'max_epochs': 60, 'patience': 10}  [4.9 min elapsed, ~54.2 min total]

  -> best val SMAPE: 77.2964  (epoch 18/28)

FE combination 10/100: {'latent_dim': 16, 'dense_layers': 2, 'learning_rate': 0.0005, 'batch_size': 32, 'dropout': 0.2, 'max_epochs': 60, 'patience': 10}  [5.3 min elapsed, ~53.4 min total]

  -> best val SMAPE: 87.7714  (epoch 44/54)

FE combination 11/100: {'latent_dim': 16, 'dense_layers': 2, 'learning_rate': 0.0005, 'batch_size': 64, 'dropout': 0.0, 'max_epochs': 60, 'patience': 10}  [6.2 min elapsed, ~56.6 min total]

  -> best val SMAPE: 67.3799  (epoch 60/60)

FE combination 12/100: {'latent_dim': 16, 'dense_layers': 2, 'learning_rate': 0.0005, 'batch_size': 64, 'dropout': 0.2, 'max_epochs': 60, 'patience': 10}  [6.7 min elapsed, ~56.1 min total]

  -> best val SMAPE: 86.0468  (epoch 21/31)

FE combination 13/100: {'latent_dim': 16, 'dense_layers': 3, 'learning_rate': 0.001, 'batch_size': 32, 'dropout': 0.0, 'max_epochs': 60, 'patience': 10}  [7.0 min elapsed, ~54.1 min total]

  -> best val SMAPE: 74.9504  (epoch 57/60)

FE combination 14/100: {'latent_dim': 16, 'dense_layers': 3, 'learning_rate': 0.001, 'batch_size': 32, 'dropout': 0.2, 'max_epochs': 60, 'patience': 10}  [8.2 min elapsed, ~58.8 min total]

  -> best val SMAPE: 97.2979  (epoch 51/60)

FE combination 15/100: {'latent_dim': 16, 'dense_layers': 3, 'learning_rate': 0.001, 'batch_size': 64, 'dropout': 0.0, 'max_epochs': 60, 'patience': 10}  [9.5 min elapsed, ~63.3 min total]

  -> best val SMAPE: 75.7590  (epoch 57/60)

FE combination 16/100: {'latent_dim': 16, 'dense_layers': 3, 'learning_rate': 0.001, 'batch_size': 64, 'dropout': 0.2, 'max_epochs': 60, 'patience': 10}  [10.1 min elapsed, ~63.1 min total]

  -> best val SMAPE: 104.3624  (epoch 23/33)

FE combination 17/100: {'latent_dim': 16, 'dense_layers': 3, 'learning_rate': 0.0005, 'batch_size': 32, 'dropout': 0.0, 'max_epochs': 60, 'patience': 10}  [10.5 min elapsed, ~61.7 min total]

  -> best val SMAPE: 79.1800  (epoch 33/43)

FE combination 18/100: {'latent_dim': 16, 'dense_layers': 3, 'learning_rate': 0.0005, 'batch_size': 32, 'dropout': 0.2, 'max_epochs': 60, 'patience': 10}  [11.3 min elapsed, ~62.9 min total]

  -> best val SMAPE: 104.9125  (epoch 18/28)

FE combination 19/100: {'latent_dim': 16, 'dense_layers': 3, 'learning_rate': 0.0005, 'batch_size': 64, 'dropout': 0.0, 'max_epochs': 60, 'patience': 10}  [11.9 min elapsed, ~62.7 min total]

  -> best val SMAPE: 77.5012  (epoch 42/52)

FE combination 20/100: {'latent_dim': 16, 'dense_layers': 3, 'learning_rate': 0.0005, 'batch_size': 64, 'dropout': 0.2, 'max_epochs': 60, 'patience': 10}  [12.5 min elapsed, ~62.3 min total]

  -> best val SMAPE: 104.6026  (epoch 48/58)

FE combination 21/100: {'latent_dim': 24, 'dense_layers': 1, 'learning_rate': 0.001, 'batch_size': 32, 'dropout': 0.0, 'max_epochs': 60, 'patience': 10}  [13.1 min elapsed, ~62.4 min total]

  -> best val SMAPE: 32.4996  (epoch 35/45)
  *** New global best: val SMAPE=32.4996 ***

FE combination 22/100: {'latent_dim': 24, 'dense_layers': 1, 'learning_rate': 0.001, 'batch_size': 64, 'dropout': 0.0, 'max_epochs': 60, 'patience': 10}  [13.6 min elapsed, ~62.0 min total]

  -> best val SMAPE: 46.3923  (epoch 25/35)

FE combination 23/100: {'latent_dim': 24, 'dense_layers': 1, 'learning_rate': 0.0005, 'batch_size': 32, 'dropout': 0.0, 'max_epochs': 60, 'patience': 10}  [13.9 min elapsed, ~60.4 min total]

  -> best val SMAPE: 60.5856  (epoch 26/36)

FE combination 24/100: {'latent_dim': 24, 'dense_layers': 1, 'learning_rate': 0.0005, 'batch_size': 64, 'dropout': 0.0, 'max_epochs': 60, 'patience': 10}  [14.3 min elapsed, ~59.7 min total]

  -> best val SMAPE: 78.3594  (epoch 11/21)

FE combination 25/100: {'latent_dim': 24, 'dense_layers': 2, 'learning_rate': 0.001, 'batch_size': 32, 'dropout': 0.0, 'max_epochs': 60, 'patience': 10}  [14.5 min elapsed, ~58.0 min total]

  -> best val SMAPE: 59.9191  (epoch 56/60)

FE combination 26/100: {'latent_dim': 24, 'dense_layers': 2, 'learning_rate': 0.001, 'batch_size': 32, 'dropout': 0.2, 'max_epochs': 60, 'patience': 10}  [15.4 min elapsed, ~59.3 min total]

  -> best val SMAPE: 78.1646  (epoch 56/60)

FE combination 27/100: {'latent_dim': 24, 'dense_layers': 2, 'learning_rate': 0.001, 'batch_size': 64, 'dropout': 0.0, 'max_epochs': 60, 'patience': 10}  [16.4 min elapsed, ~60.7 min total]

  -> best val SMAPE: 65.3927  (epoch 60/60)

FE combination 28/100: {'latent_dim': 24, 'dense_layers': 2, 'learning_rate': 0.001, 'batch_size': 64, 'dropout': 0.2, 'max_epochs': 60, 'patience': 10}  [16.9 min elapsed, ~60.3 min total]

  -> best val SMAPE: 83.8335  (epoch 38/48)

FE combination 29/100: {'latent_dim': 24, 'dense_layers': 2, 'learning_rate': 0.0005, 'batch_size': 32, 'dropout': 0.0, 'max_epochs': 60, 'patience': 10}  [17.3 min elapsed, ~59.7 min total]

  -> best val SMAPE: 65.5731  (epoch 57/60)

FE combination 30/100: {'latent_dim': 24, 'dense_layers': 2, 'learning_rate': 0.0005, 'batch_size': 32, 'dropout': 0.2, 'max_epochs': 60, 'patience': 10}  [18.2 min elapsed, ~60.8 min total]

  -> best val SMAPE: 80.7533  (epoch 49/59)

FE combination 31/100: {'latent_dim': 24, 'dense_layers': 2, 'learning_rate': 0.0005, 'batch_size': 64, 'dropout': 0.0, 'max_epochs': 60, 'patience': 10}  [19.2 min elapsed, ~62.0 min total]

  -> best val SMAPE: 64.5415  (epoch 52/60)

FE combination 32/100: {'latent_dim': 24, 'dense_layers': 2, 'learning_rate': 0.0005, 'batch_size': 64, 'dropout': 0.2, 'max_epochs': 60, 'patience': 10}  [19.7 min elapsed, ~61.6 min total]

  -> best val SMAPE: 91.2566  (epoch 21/31)

FE combination 33/100: {'latent_dim': 24, 'dense_layers': 3, 'learning_rate': 0.001, 'batch_size': 32, 'dropout': 0.0, 'max_epochs': 60, 'patience': 10}  [20.0 min elapsed, ~60.6 min total]

  -> best val SMAPE: 73.7353  (epoch 21/31)

FE combination 34/100: {'latent_dim': 24, 'dense_layers': 3, 'learning_rate': 0.001, 'batch_size': 32, 'dropout': 0.2, 'max_epochs': 60, 'patience': 10}  [20.6 min elapsed, ~60.6 min total]

  -> best val SMAPE: 95.5147  (epoch 40/50)

FE combination 35/100: {'latent_dim': 24, 'dense_layers': 3, 'learning_rate': 0.001, 'batch_size': 64, 'dropout': 0.0, 'max_epochs': 60, 'patience': 10}  [21.6 min elapsed, ~61.8 min total]

  -> best val SMAPE: 65.0855  (epoch 38/48)

FE combination 36/100: {'latent_dim': 24, 'dense_layers': 3, 'learning_rate': 0.001, 'batch_size': 64, 'dropout': 0.2, 'max_epochs': 60, 'patience': 10}  [22.1 min elapsed, ~61.5 min total]

  -> best val SMAPE: 96.8737  (epoch 60/60)

FE combination 37/100: {'latent_dim': 24, 'dense_layers': 3, 'learning_rate': 0.0005, 'batch_size': 32, 'dropout': 0.0, 'max_epochs': 60, 'patience': 10}  [22.8 min elapsed, ~61.6 min total]

  -> best val SMAPE: 71.4432  (epoch 28/38)

FE combination 38/100: {'latent_dim': 24, 'dense_layers': 3, 'learning_rate': 0.0005, 'batch_size': 32, 'dropout': 0.2, 'max_epochs': 60, 'patience': 10}  [23.5 min elapsed, ~61.9 min total]

  -> best val SMAPE: 90.2425  (epoch 60/60)

FE combination 39/100: {'latent_dim': 24, 'dense_layers': 3, 'learning_rate': 0.0005, 'batch_size': 64, 'dropout': 0.0, 'max_epochs': 60, 'patience': 10}  [24.8 min elapsed, ~63.5 min total]

  -> best val SMAPE: 66.4119  (epoch 59/60)

FE combination 40/100: {'latent_dim': 24, 'dense_layers': 3, 'learning_rate': 0.0005, 'batch_size': 64, 'dropout': 0.2, 'max_epochs': 60, 'patience': 10}  [25.4 min elapsed, ~63.4 min total]

  -> best val SMAPE: 97.2552  (epoch 58/60)

FE combination 41/100: {'latent_dim': 33, 'dense_layers': 1, 'learning_rate': 0.001, 'batch_size': 32, 'dropout': 0.0, 'max_epochs': 60, 'patience': 10}  [26.0 min elapsed, ~63.5 min total]

  -> best val SMAPE: 25.0502  (epoch 45/55)
  *** New global best: val SMAPE=25.0502 ***

FE combination 42/100: {'latent_dim': 33, 'dense_layers': 1, 'learning_rate': 0.001, 'batch_size': 64, 'dropout': 0.0, 'max_epochs': 60, 'patience': 10}  [26.7 min elapsed, ~63.5 min total]

  -> best val SMAPE: 37.7415  (epoch 24/34)

FE combination 43/100: {'latent_dim': 33, 'dense_layers': 1, 'learning_rate': 0.0005, 'batch_size': 32, 'dropout': 0.0, 'max_epochs': 60, 'patience': 10}  [26.9 min elapsed, ~62.6 min total]

  -> best val SMAPE: 69.1673  (epoch 18/28)

FE combination 44/100: {'latent_dim': 33, 'dense_layers': 1, 'learning_rate': 0.0005, 'batch_size': 64, 'dropout': 0.0, 'max_epochs': 60, 'patience': 10}  [27.3 min elapsed, ~62.0 min total]

  -> best val SMAPE: 70.4036  (epoch 22/32)

FE combination 45/100: {'latent_dim': 33, 'dense_layers': 2, 'learning_rate': 0.001, 'batch_size': 32, 'dropout': 0.0, 'max_epochs': 60, 'patience': 10}  [27.5 min elapsed, ~61.1 min total]

  -> best val SMAPE: 50.5748  (epoch 39/49)

FE combination 46/100: {'latent_dim': 33, 'dense_layers': 2, 'learning_rate': 0.001, 'batch_size': 32, 'dropout': 0.2, 'max_epochs': 60, 'patience': 10}  [28.2 min elapsed, ~61.4 min total]

  -> best val SMAPE: 78.8472  (epoch 39/49)

FE combination 47/100: {'latent_dim': 33, 'dense_layers': 2, 'learning_rate': 0.001, 'batch_size': 64, 'dropout': 0.0, 'max_epochs': 60, 'patience': 10}  [29.1 min elapsed, ~61.8 min total]

  -> best val SMAPE: 60.1244  (epoch 37/47)

FE combination 48/100: {'latent_dim': 33, 'dense_layers': 2, 'learning_rate': 0.001, 'batch_size': 64, 'dropout': 0.2, 'max_epochs': 60, 'patience': 10}  [29.5 min elapsed, ~61.4 min total]

  -> best val SMAPE: 77.3071  (epoch 47/57)

FE combination 49/100: {'latent_dim': 33, 'dense_layers': 2, 'learning_rate': 0.0005, 'batch_size': 32, 'dropout': 0.0, 'max_epochs': 60, 'patience': 10}  [30.0 min elapsed, ~61.2 min total]

  -> best val SMAPE: 49.0343  (epoch 55/60)

FE combination 50/100: {'latent_dim': 33, 'dense_layers': 2, 'learning_rate': 0.0005, 'batch_size': 32, 'dropout': 0.2, 'max_epochs': 60, 'patience': 10}  [30.9 min elapsed, ~61.8 min total]

  -> best val SMAPE: 83.7744  (epoch 41/51)

FE combination 51/100: {'latent_dim': 33, 'dense_layers': 2, 'learning_rate': 0.0005, 'batch_size': 64, 'dropout': 0.0, 'max_epochs': 60, 'patience': 10}  [31.7 min elapsed, ~62.2 min total]

  -> best val SMAPE: 75.5674  (epoch 18/28)

FE combination 52/100: {'latent_dim': 33, 'dense_layers': 2, 'learning_rate': 0.0005, 'batch_size': 64, 'dropout': 0.2, 'max_epochs': 60, 'patience': 10}  [32.0 min elapsed, ~61.6 min total]

  -> best val SMAPE: 84.2177  (epoch 56/60)

FE combination 53/100: {'latent_dim': 33, 'dense_layers': 3, 'learning_rate': 0.001, 'batch_size': 32, 'dropout': 0.0, 'max_epochs': 60, 'patience': 10}  [32.5 min elapsed, ~61.4 min total]

  -> best val SMAPE: 72.3268  (epoch 57/60)

FE combination 54/100: {'latent_dim': 33, 'dense_layers': 3, 'learning_rate': 0.001, 'batch_size': 32, 'dropout': 0.2, 'max_epochs': 60, 'patience': 10}  [33.7 min elapsed, ~62.3 min total]

  -> best val SMAPE: 86.2783  (epoch 35/45)

FE combination 55/100: {'latent_dim': 33, 'dense_layers': 3, 'learning_rate': 0.001, 'batch_size': 64, 'dropout': 0.0, 'max_epochs': 60, 'patience': 10}  [34.6 min elapsed, ~62.9 min total]

  -> best val SMAPE: 72.4082  (epoch 27/37)

FE combination 56/100: {'latent_dim': 33, 'dense_layers': 3, 'learning_rate': 0.001, 'batch_size': 64, 'dropout': 0.2, 'max_epochs': 60, 'patience': 10}  [35.1 min elapsed, ~62.7 min total]

  -> best val SMAPE: 89.6706  (epoch 43/53)

FE combination 57/100: {'latent_dim': 33, 'dense_layers': 3, 'learning_rate': 0.0005, 'batch_size': 32, 'dropout': 0.0, 'max_epochs': 60, 'patience': 10}  [35.8 min elapsed, ~62.9 min total]

  -> best val SMAPE: 70.8237  (epoch 23/33)

FE combination 58/100: {'latent_dim': 33, 'dense_layers': 3, 'learning_rate': 0.0005, 'batch_size': 32, 'dropout': 0.2, 'max_epochs': 60, 'patience': 10}  [36.5 min elapsed, ~63.0 min total]

  -> best val SMAPE: 87.5553  (epoch 31/41)

FE combination 59/100: {'latent_dim': 33, 'dense_layers': 3, 'learning_rate': 0.0005, 'batch_size': 64, 'dropout': 0.0, 'max_epochs': 60, 'patience': 10}  [37.4 min elapsed, ~63.4 min total]

  -> best val SMAPE: 74.9997  (epoch 25/35)

FE combination 60/100: {'latent_dim': 33, 'dense_layers': 3, 'learning_rate': 0.0005, 'batch_size': 64, 'dropout': 0.2, 'max_epochs': 60, 'patience': 10}  [38.0 min elapsed, ~63.4 min total]

  -> best val SMAPE: 93.2142  (epoch 57/60)

FE combination 61/100: {'latent_dim': 38, 'dense_layers': 1, 'learning_rate': 0.001, 'batch_size': 32, 'dropout': 0.0, 'max_epochs': 60, 'patience': 10}  [38.7 min elapsed, ~63.4 min total]

  -> best val SMAPE: 32.2062  (epoch 22/32)

FE combination 62/100: {'latent_dim': 38, 'dense_layers': 1, 'learning_rate': 0.001, 'batch_size': 64, 'dropout': 0.0, 'max_epochs': 60, 'patience': 10}  [39.1 min elapsed, ~63.0 min total]

  -> best val SMAPE: 48.4781  (epoch 23/33)

FE combination 63/100: {'latent_dim': 38, 'dense_layers': 1, 'learning_rate': 0.0005, 'batch_size': 32, 'dropout': 0.0, 'max_epochs': 60, 'patience': 10}  [39.3 min elapsed, ~62.4 min total]

  -> best val SMAPE: 47.0012  (epoch 39/49)

FE combination 64/100: {'latent_dim': 38, 'dense_layers': 1, 'learning_rate': 0.0005, 'batch_size': 64, 'dropout': 0.0, 'max_epochs': 60, 'patience': 10}  [39.9 min elapsed, ~62.4 min total]

  -> best val SMAPE: 66.9216  (epoch 46/56)

FE combination 65/100: {'latent_dim': 38, 'dense_layers': 2, 'learning_rate': 0.001, 'batch_size': 32, 'dropout': 0.0, 'max_epochs': 60, 'patience': 10}  [40.3 min elapsed, ~62.0 min total]

  -> best val SMAPE: 48.0679  (epoch 54/60)

FE combination 66/100: {'latent_dim': 38, 'dense_layers': 2, 'learning_rate': 0.001, 'batch_size': 32, 'dropout': 0.2, 'max_epochs': 60, 'patience': 10}  [41.2 min elapsed, ~62.4 min total]

  -> best val SMAPE: 82.1717  (epoch 22/32)

FE combination 67/100: {'latent_dim': 38, 'dense_layers': 2, 'learning_rate': 0.001, 'batch_size': 64, 'dropout': 0.0, 'max_epochs': 60, 'patience': 10}  [41.8 min elapsed, ~62.3 min total]

  -> best val SMAPE: 47.3822  (epoch 56/60)

FE combination 68/100: {'latent_dim': 38, 'dense_layers': 2, 'learning_rate': 0.001, 'batch_size': 64, 'dropout': 0.2, 'max_epochs': 60, 'patience': 10}  [42.3 min elapsed, ~62.2 min total]

  -> best val SMAPE: 78.9507  (epoch 57/60)

FE combination 69/100: {'latent_dim': 38, 'dense_layers': 2, 'learning_rate': 0.0005, 'batch_size': 32, 'dropout': 0.0, 'max_epochs': 60, 'patience': 10}  [42.8 min elapsed, ~62.0 min total]

  -> best val SMAPE: 45.5616  (epoch 57/60)

FE combination 70/100: {'latent_dim': 38, 'dense_layers': 2, 'learning_rate': 0.0005, 'batch_size': 32, 'dropout': 0.2, 'max_epochs': 60, 'patience': 10}  [43.7 min elapsed, ~62.5 min total]

  -> best val SMAPE: 76.7050  (epoch 47/57)

FE combination 71/100: {'latent_dim': 38, 'dense_layers': 2, 'learning_rate': 0.0005, 'batch_size': 64, 'dropout': 0.0, 'max_epochs': 60, 'patience': 10}  [44.7 min elapsed, ~62.9 min total]

  -> best val SMAPE: 48.8216  (epoch 60/60)

FE combination 72/100: {'latent_dim': 38, 'dense_layers': 2, 'learning_rate': 0.0005, 'batch_size': 64, 'dropout': 0.2, 'max_epochs': 60, 'patience': 10}  [45.2 min elapsed, ~62.7 min total]

  -> best val SMAPE: 79.6111  (epoch 58/60)

FE combination 73/100: {'latent_dim': 38, 'dense_layers': 3, 'learning_rate': 0.001, 'batch_size': 32, 'dropout': 0.0, 'max_epochs': 60, 'patience': 10}  [45.7 min elapsed, ~62.6 min total]

  -> best val SMAPE: 74.9327  (epoch 57/60)

FE combination 74/100: {'latent_dim': 38, 'dense_layers': 3, 'learning_rate': 0.001, 'batch_size': 32, 'dropout': 0.2, 'max_epochs': 60, 'patience': 10}  [46.8 min elapsed, ~63.3 min total]

  -> best val SMAPE: 93.5533  (epoch 31/41)

FE combination 75/100: {'latent_dim': 38, 'dense_layers': 3, 'learning_rate': 0.001, 'batch_size': 64, 'dropout': 0.0, 'max_epochs': 60, 'patience': 10}  [47.7 min elapsed, ~63.6 min total]

  -> best val SMAPE: 66.9670  (epoch 50/60)

FE combination 76/100: {'latent_dim': 38, 'dense_layers': 3, 'learning_rate': 0.001, 'batch_size': 64, 'dropout': 0.2, 'max_epochs': 60, 'patience': 10}  [48.3 min elapsed, ~63.6 min total]

  -> best val SMAPE: 96.3010  (epoch 54/60)

FE combination 77/100: {'latent_dim': 38, 'dense_layers': 3, 'learning_rate': 0.0005, 'batch_size': 32, 'dropout': 0.0, 'max_epochs': 60, 'patience': 10}  [49.0 min elapsed, ~63.6 min total]

  -> best val SMAPE: 73.0390  (epoch 59/60)

FE combination 78/100: {'latent_dim': 38, 'dense_layers': 3, 'learning_rate': 0.0005, 'batch_size': 32, 'dropout': 0.2, 'max_epochs': 60, 'patience': 10}  [50.1 min elapsed, ~64.2 min total]

  -> best val SMAPE: 92.2493  (epoch 33/43)

FE combination 79/100: {'latent_dim': 38, 'dense_layers': 3, 'learning_rate': 0.0005, 'batch_size': 64, 'dropout': 0.0, 'max_epochs': 60, 'patience': 10}  [51.0 min elapsed, ~64.6 min total]

  -> best val SMAPE: 72.9298  (epoch 31/41)

FE combination 80/100: {'latent_dim': 38, 'dense_layers': 3, 'learning_rate': 0.0005, 'batch_size': 64, 'dropout': 0.2, 'max_epochs': 60, 'patience': 10}  [51.4 min elapsed, ~64.3 min total]

  -> best val SMAPE: 87.3177  (epoch 58/60)

FE combination 81/100: {'latent_dim': 48, 'dense_layers': 1, 'learning_rate': 0.001, 'batch_size': 32, 'dropout': 0.0, 'max_epochs': 60, 'patience': 10}  [52.1 min elapsed, ~64.3 min total]

  -> best val SMAPE: 42.3902  (epoch 15/25)

FE combination 82/100: {'latent_dim': 48, 'dense_layers': 1, 'learning_rate': 0.001, 'batch_size': 64, 'dropout': 0.0, 'max_epochs': 60, 'patience': 10}  [52.4 min elapsed, ~63.9 min total]

  -> best val SMAPE: 23.7420  (epoch 53/60)
  *** New global best: val SMAPE=23.7420 ***

FE combination 83/100: {'latent_dim': 48, 'dense_layers': 1, 'learning_rate': 0.0005, 'batch_size': 32, 'dropout': 0.0, 'max_epochs': 60, 'patience': 10}  [52.8 min elapsed, ~63.6 min total]

  -> best val SMAPE: 42.8040  (epoch 52/60)

FE combination 84/100: {'latent_dim': 48, 'dense_layers': 1, 'learning_rate': 0.0005, 'batch_size': 64, 'dropout': 0.0, 'max_epochs': 60, 'patience': 10}  [53.5 min elapsed, ~63.7 min total]

  -> best val SMAPE: 68.1115  (epoch 27/37)

FE combination 85/100: {'latent_dim': 48, 'dense_layers': 2, 'learning_rate': 0.001, 'batch_size': 32, 'dropout': 0.0, 'max_epochs': 60, 'patience': 10}  [53.8 min elapsed, ~63.3 min total]

  -> best val SMAPE: 64.0120  (epoch 25/35)

FE combination 86/100: {'latent_dim': 48, 'dense_layers': 2, 'learning_rate': 0.001, 'batch_size': 32, 'dropout': 0.2, 'max_epochs': 60, 'patience': 10}  [54.3 min elapsed, ~63.2 min total]

  -> best val SMAPE: 77.8824  (epoch 60/60)

FE combination 87/100: {'latent_dim': 48, 'dense_layers': 2, 'learning_rate': 0.001, 'batch_size': 64, 'dropout': 0.0, 'max_epochs': 60, 'patience': 10}  [55.3 min elapsed, ~63.6 min total]

  -> best val SMAPE: 51.0698  (epoch 54/60)

FE combination 88/100: {'latent_dim': 48, 'dense_layers': 2, 'learning_rate': 0.001, 'batch_size': 64, 'dropout': 0.2, 'max_epochs': 60, 'patience': 10}  [55.8 min elapsed, ~63.5 min total]

  -> best val SMAPE: 76.8012  (epoch 56/60)

FE combination 89/100: {'latent_dim': 48, 'dense_layers': 2, 'learning_rate': 0.0005, 'batch_size': 32, 'dropout': 0.0, 'max_epochs': 60, 'patience': 10}  [56.4 min elapsed, ~63.4 min total]

  -> best val SMAPE: 52.4385  (epoch 40/50)

FE combination 90/100: {'latent_dim': 48, 'dense_layers': 2, 'learning_rate': 0.0005, 'batch_size': 32, 'dropout': 0.2, 'max_epochs': 60, 'patience': 10}  [57.2 min elapsed, ~63.5 min total]

  -> best val SMAPE: 77.9190  (epoch 36/46)

FE combination 91/100: {'latent_dim': 48, 'dense_layers': 2, 'learning_rate': 0.0005, 'batch_size': 64, 'dropout': 0.0, 'max_epochs': 60, 'patience': 10}  [57.9 min elapsed, ~63.7 min total]

  -> best val SMAPE: 47.0113  (epoch 57/60)

FE combination 92/100: {'latent_dim': 48, 'dense_layers': 2, 'learning_rate': 0.0005, 'batch_size': 64, 'dropout': 0.2, 'max_epochs': 60, 'patience': 10}  [58.4 min elapsed, ~63.5 min total]

  -> best val SMAPE: 81.7926  (epoch 28/38)

FE combination 93/100: {'latent_dim': 48, 'dense_layers': 3, 'learning_rate': 0.001, 'batch_size': 32, 'dropout': 0.0, 'max_epochs': 60, 'patience': 10}  [58.8 min elapsed, ~63.2 min total]

  -> best val SMAPE: 68.7604  (epoch 59/60)

FE combination 94/100: {'latent_dim': 48, 'dense_layers': 3, 'learning_rate': 0.001, 'batch_size': 32, 'dropout': 0.2, 'max_epochs': 60, 'patience': 10}  [59.9 min elapsed, ~63.8 min total]

  -> best val SMAPE: 85.7393  (epoch 56/60)

FE combination 95/100: {'latent_dim': 48, 'dense_layers': 3, 'learning_rate': 0.001, 'batch_size': 64, 'dropout': 0.0, 'max_epochs': 60, 'patience': 10}  [61.2 min elapsed, ~64.4 min total]

  -> best val SMAPE: 69.9174  (epoch 35/45)

FE combination 96/100: {'latent_dim': 48, 'dense_layers': 3, 'learning_rate': 0.001, 'batch_size': 64, 'dropout': 0.2, 'max_epochs': 60, 'patience': 10}  [61.6 min elapsed, ~64.2 min total]

  -> best val SMAPE: 84.9581  (epoch 36/46)

FE combination 97/100: {'latent_dim': 48, 'dense_layers': 3, 'learning_rate': 0.0005, 'batch_size': 32, 'dropout': 0.0, 'max_epochs': 60, 'patience': 10}  [62.2 min elapsed, ~64.1 min total]

  -> best val SMAPE: 67.0274  (epoch 58/60)

FE combination 98/100: {'latent_dim': 48, 'dense_layers': 3, 'learning_rate': 0.0005, 'batch_size': 32, 'dropout': 0.2, 'max_epochs': 60, 'patience': 10}  [63.3 min elapsed, ~64.6 min total]

  -> best val SMAPE: 85.9335  (epoch 30/40)

FE combination 99/100: {'latent_dim': 48, 'dense_layers': 3, 'learning_rate': 0.0005, 'batch_size': 64, 'dropout': 0.0, 'max_epochs': 60, 'patience': 10}  [64.1 min elapsed, ~64.8 min total]

  -> best val SMAPE: 72.5411  (epoch 33/43)

FE combination 100/100: {'latent_dim': 48, 'dense_layers': 3, 'learning_rate': 0.0005, 'batch_size': 64, 'dropout': 0.2, 'max_epochs': 60, 'patience': 10}  [64.6 min elapsed, ~64.6 min total]

  -> best val SMAPE: 86.0543  (epoch 60/60)

Top 10 configurations by val SMAPE:

,latent_dim,dense_layers,learning_rate,batch_size,dropout,max_epochs,patience,combination,fe_input_size,price_zone,best_val_smape,best_epoch,epochs_trained
0,48,1,0.0010,64,0.0,60,10,82,33,DK1,23.741976,53,60
1,33,1,0.0010,32,0.0,60,10,41,33,DK1,25.050196,45,55
2,38,1,0.0010,32,0.0,60,10,61,33,DK1,32.206215,22,32
3,24,1,0.0010,32,0.0,60,10,21,33,DK1,32.499565,35,45
4,33,1,0.0010,64,0.0,60,10,42,33,DK1,37.741501,24,34
5,48,1,0.0010,32,0.0,60,10,81,33,DK1,42.390179,15,25
6,48,1,0.0005,32,0.0,60,10,83,33,DK1,42.804047,52,60
7,38,2,0.0005,32,0.0,60,10,69,33,DK1,45.561584,57,60
8,16,1,0.0010,32,0.0,60,10,1,33,DK1,45.586540,41,51
9,24,1,0.0010,64,0.0,60,10,22,33,DK1,46.392319,25,35

=== Stage 1 complete – best encoder weights ready for Stage 2 ===
  latent_dim           : 48
  dense_layers         : 1
  best_val_smape (recon): 23.7420

  best_stage1_encoder_state_dict is available for Stage 2.
  These weights will be loaded into LSTMAutoencoder.feature_encoder
  and frozen during Stage 2 LSTM tuning.

### Step 2: Full LSTM AE Search

Search grid

In [11]:
import numpy as np
import itertools

# ---------------------------------------------------------------------------
# Step 2 search grid – split by component, combined at the end.
# latent_dim and dense_layers are NOT swept here; they are fixed to the
# best values found in Stage 1 (best_stage1_params).
# ---------------------------------------------------------------------------

# 1. Encoder LSTM
enc_lstm_grid = {
    "encoder_hidden_size": [16, 32, 48],
    "layers":              [1, 2],
}

# 2. Decoder LSTM
dec_lstm_grid = {
    "decoder_hidden_size": [16, 32, 48],
}

# 3. Shared / training hyperparameters
training_grid = {
    "learning_rate":   [0.001],
    "max_epochs":      [60],
    "patience":        [10],
    "batch_size":      [32, 64],
    "sequence_length": [24, 168],
    "dropout":         [0.0, 0.2],
}

# Combine LSTM + training sub-grids into one flat grid
param_grid = {**enc_lstm_grid, **dec_lstm_grid, **training_grid}

total_combinations = int(np.prod([len(v) for v in param_grid.values()]))

# Exclude layers==1 with dropout>0 (dropout has no effect on a single-layer LSTM)
excluded = sum(
    1
    for combo in itertools.product(*param_grid.values())
    if dict(zip(param_grid.keys(), combo))["layers"] == 1
    and dict(zip(param_grid.keys(), combo))["dropout"] > 0.0
)
effective_combinations = total_combinations - excluded

print(f"Stage 1 encoder shape (fixed for Stage 2):")
if "best_stage1_params" in globals() and best_stage1_params is not None:
    print(f"  latent_dim   = {best_stage1_params['latent_dim']}")
    print(f"  dense_layers = {best_stage1_params['dense_layers']}")
else:
    print("  (run Stage 1 first to set best_stage1_params)")

print(f"\nSub-grid sizes:")
print(f"  Encoder LSTM     : {int(np.prod([len(v) for v in enc_lstm_grid.values()]))} combinations  {enc_lstm_grid}")
print(f"  Decoder LSTM     : {int(np.prod([len(v) for v in dec_lstm_grid.values()]))} combinations  {dec_lstm_grid}")
print(f"  Training / shared: {int(np.prod([len(v) for v in training_grid.values()]))} combinations  {training_grid}")
print(f"\nTotal combinations (before exclusions): {total_combinations}")
print(f"Excluded (layers=1 & dropout>0):        {excluded}")
print(f"Effective combinations:                 {effective_combinations}")

Stage 1 encoder shape (fixed for Stage 2):
  latent_dim   = 48
  dense_layers = 1

Sub-grid sizes:
  Encoder LSTM     : 6 combinations  {'encoder_hidden_size': [16, 32, 48], 'layers': [1, 2]}
  Decoder LSTM     : 3 combinations  {'decoder_hidden_size': [16, 32, 48]}
  Training / shared: 8 combinations  {'learning_rate': [0.001], 'max_epochs': [60], 'patience': [10], 'batch_size': [32, 64], 'sequence_length': [24, 168], 'dropout': [0.0, 0.2]}

Total combinations (before exclusions): 144
Excluded (layers=1 & dropout>0):        36
Effective combinations:                 108

Hyperparameter search

In [12]:

from Modules.Validation3_AE import run_cross_validation
import itertools
import numpy as np
from pathlib import Path
from time import time

import pandas as pd
import wandb

# ---------------------------------------------------------------------------
# Verify that Stage 1 produced a pretrained encoder state dict
# ---------------------------------------------------------------------------
if "best_stage1_encoder_state_dict" not in globals() or best_stage1_encoder_state_dict is None:
    raise RuntimeError(
        "best_stage1_encoder_state_dict is not set. Run the Stage 1 feature encoder "
        "search cell first so that pretrained encoder weights are available."
    )

print(
    f"Using pretrained encoder from Stage 1:\n"
    f"  latent_dim   = {best_stage1_params['latent_dim']}\n"
    f"  dense_layers = {best_stage1_params['dense_layers']}\n"
    f"  best recon SMAPE = {best_stage1_val_smape:.4f}\n"
)

PREDICT_PERIOD = 1 * 168
split_setup = 2
start_combination = 1

WANDB_PROJECT = "LSTM_AE_param_search_exclPrice_exclPriceLag1_DK1"

# param_grid is defined in the grid cell above (split into fe_grid, enc_lstm_grid,
# dec_lstm_grid and training_grid, then merged into one flat param_grid dict).
# Stage 2 fixes latent_dim and dense_layers to the Stage 1 best values; only
# LSTM / training hyperparameters are swept here.
num_combinations = int(np.prod([len(v) for v in param_grid.values()]))
print(f"Total combinations: {num_combinations}")

param_names = list(param_grid.keys())
param_values = list(param_grid.values())
all_combinations = list(itertools.product(*param_values))

# Feature columns: all columns except Time and DKPrice.
# DKPrice is handled inside the encoder; it is NOT a feature column.
cv_feature_columns = [c for c in dataset_train_input.columns if c not in ["Time", "DKPrice"]]
print(f"CV feature columns ({len(cv_feature_columns)}): {cv_feature_columns}")

start_time = time()
results = []
for comb_number, combination in enumerate(all_combinations, start=1):
    params = dict(zip(param_names, combination))
    if comb_number < start_combination:
        continue
    if int(params["layers"]) == 1 and float(params["dropout"]) > 0.0:
        continue

    WANDB_RUN_BASENAME = f"LSTM_AE_" + \
                    f"esize{params['encoder_hidden_size']}" + \
                    f"_elayers{params['layers']}" + \
                    f"_dsize{params['decoder_hidden_size']}" + \
                    f"_bs{params['batch_size']}" + \
                    f"_seqlen{params['sequence_length']}" + \
                    f"_lr{params['learning_rate']}" + \
                    f"_drop{params['dropout']}"

    print(f"\nCombination {comb_number}/{num_combinations}: {params}")
    print(
        f"Time: {(time() - start_time)/60:.2f} minutes - estimated total time: "
        f"{(time() - start_time)/comb_number*num_combinations/60:.2f} minutes"
    )
    run_name = (f"{WANDB_RUN_BASENAME}_comb{comb_number:03d}")

    run = wandb.init(
        project=WANDB_PROJECT,
        name=run_name,
        config={
            "price_zone": PRICE_ZONE,
            "train_window": TRAIN_WINDOW,
            "val_window": VAL_WINDOW,
            "val_start": VAL_START,
            "predict_period": PREDICT_PERIOD,
            "stride": STRIDE,
            "split_setup": split_setup,
            "combination": int(comb_number),
            "num_combinations": int(num_combinations),
            "include_remaining_2024_in_prepared_train_data": bool(INCLUDE_REMAINING_2024_DURING_TRAINING),
            # pretrained encoder provenance
            "stage1_latent_dim":   int(best_stage1_params["latent_dim"]),
            "stage1_dense_layers": int(best_stage1_params["dense_layers"]),
            "stage1_recon_smape":  float(best_stage1_val_smape),
            "encoder_frozen":      True,
            # sub-grid membership for easy W&B grouping
            "fe_latent_dim":        int(best_stage1_params["latent_dim"]),
            "fe_dense_layers":      int(best_stage1_params["dense_layers"]),
            "enc_hidden_size":      int(params["encoder_hidden_size"]),
            "enc_layers":           int(params["layers"]),
            "dec_hidden_size":      int(params["decoder_hidden_size"]),
            **params,
        },
        tags=["lstm-ae", "hyperparameter-search", "cross-validation", "early-stopping",
              "pretrained-encoder", "frozen-encoder"],
        reinit=True,
        settings=wandb.Settings(start_method="thread"),
    )

    try:
        max_epochs = int(params["max_epochs"])
        patience = int(params["patience"])

        model = TorchLSTMAERegressor(
            # Use the latent_dim / dense_layers that match the pretrained encoder shape.
            # The grid may vary these, but the actual weights come from Stage 1.
            latent_dim=int(best_stage1_params["latent_dim"]),
            dense_layers=int(best_stage1_params["dense_layers"]),
            encoder_hidden_size=int(params["encoder_hidden_size"]),
            decoder_hidden_size=int(params["decoder_hidden_size"]),
            layers=int(params["layers"]),
            learning_rate=float(params["learning_rate"]),
            epochs=1,
            batch_size=int(params["batch_size"]),
            sequence_length=int(params["sequence_length"]),
            dropout=float(params["dropout"]),
            random_state=42,
            warm_start=True,
        )

        # Load the pretrained encoder weights from Stage 1 and freeze them.
        # _initialize_model_state() (called on the first fit()) will inject
        # these weights into LSTMAutoencoder.feature_encoder and exclude those
        # parameters from the optimizer.
        model.set_pretrained_encoder(best_stage1_encoder_state_dict, freeze=True)

        best_val_smape = float("inf")
        best_epoch = 0
        patience_counter = 0
        best_combination_results = None

        print(f"INCLUDE_REMAINING_2024_DURING_TRAINING: {INCLUDE_REMAINING_2024_DURING_TRAINING}")
        print(f"Number of input features (decoder): {len(cv_feature_columns)}")
        print(f"All input columns: {cv_feature_columns}")

        for epoch in range(1, max_epochs + 1):
            print(f"  Epoch {epoch}/{max_epochs}")
            combination_results = run_cross_validation(
                model=model,
                dataset_train=dataset_train,
                dataset_validation=dataset_validation,
                dataset_context=dataset_context,
                feature_columns=cv_feature_columns,
                include_remaining_2024=INCLUDE_REMAINING_2024_DURING_TRAINING,
                dk_zone=PRICE_ZONE,
                split_setup=split_setup,
                train_window=TRAIN_WINDOW,
                val_window=VAL_WINDOW,
                val_start=VAL_START,
                predict_period=PREDICT_PERIOD,
                stride=STRIDE,
                use_scaler=True,
                print_fold_results=False,
                plot=False,
                rf_models=rf_models,
                use_precomputed_feature_values=use_precomputed_feature_values,
                precomputed_feature_predictions=feature_predictions,
                use_forecasted_history=USE_FORECASTED_HISTORY,
            )

            val_smape = float(combination_results["overall_avg_weekly_smape"])

            if val_smape < best_val_smape:
                best_val_smape = val_smape
                best_epoch = epoch
                best_combination_results = combination_results
                patience_counter = 0
            else:
                patience_counter += 1

            wandb.log({
                "combination": int(comb_number),
                "epoch": int(epoch),
                "train_window": int(TRAIN_WINDOW),
                "val_window": int(VAL_WINDOW),
                "predict_period": int(PREDICT_PERIOD),
                # sub-grid params logged explicitly for W&B grouping/filtering
                "fe_latent_dim": int(best_stage1_params["latent_dim"]),
                "fe_dense_layers": int(best_stage1_params["dense_layers"]),
                "enc_hidden_size":        int(params["encoder_hidden_size"]),
                "enc_layers":             int(params["layers"]),
                "dec_hidden_size":        int(params["decoder_hidden_size"]),
                "learning_rate":          float(params["learning_rate"]),
                "batch_size":             int(params["batch_size"]),
                "sequence_length":        int(params["sequence_length"]),
                "max_epochs":             int(params["max_epochs"]),
                "patience":               int(params["patience"]),
                "val_SMAPE":              float(val_smape),
                "best_val_SMAPE":         float(best_val_smape),
                "patience_counter":       int(patience_counter),
            })

            if patience_counter >= patience:
                print("  Early stopping triggered.")
                break

        print(f"\n  best_val_SMAPE={best_val_smape:.3f}")

        if best_combination_results is None:
            raise RuntimeError("No validation results were produced for this combination.")

        row = {
            # sub-grid columns first for easy reading in the CSV
            "fe_latent_dim":          int(best_stage1_params["latent_dim"]),
            "fe_dense_layers":        int(best_stage1_params["dense_layers"]),
            "enc_hidden_size":        int(params["encoder_hidden_size"]),
            "enc_layers":             int(params["layers"]),
            "dec_hidden_size":        int(params["decoder_hidden_size"]),
            **params,
            "best_epoch": int(best_epoch),
            "epochs_trained": int(epoch),
            "price_zone": PRICE_ZONE,
            "train_window": str(TRAIN_WINDOW // 8760) + " years",
            "val_start": VAL_START.split(" ")[0],
            "avg_smape": best_val_smape,
            "avg_weekly_rmse": best_combination_results["overall_avg_weekly_rmse"],
            "avg_weekly_mae": best_combination_results["overall_avg_weekly_mae"],
            "avg_weekly_smape": best_combination_results["overall_avg_weekly_smape"],
            "avg_daily_rmse": best_combination_results["overall_avg_daily_rmse"],
            "avg_daily_mae": best_combination_results["overall_avg_daily_mae"],
            "avg_daily_smape": best_combination_results["overall_avg_daily_smape"],
            "avg_smape_day_1": best_combination_results["avg_smape_day_1"],
            "avg_smape_day_2": best_combination_results["avg_smape_day_2"],
            "avg_smape_day_3": best_combination_results["avg_smape_day_3"],
            "avg_smape_day_4": best_combination_results["avg_smape_day_4"],
            "avg_smape_day_5": best_combination_results["avg_smape_day_5"],
            "avg_smape_day_6": best_combination_results["avg_smape_day_6"],
            "avg_smape_day_7": best_combination_results["avg_smape_day_7"],
        }
        results.append(row)

        run.summary.update({
            "best_epoch": int(best_epoch),
            "best_val_smape": float(best_val_smape),
            "epochs_trained": int(epoch),
        })
    finally:
        wandb.finish()

results_df = pd.DataFrame(results).sort_values("avg_smape")

project_root_path = Path(project_root)
output_folder = project_root_path / "Deep learners" / "LSTM Autoencoder"
output_folder.mkdir(parents=True, exist_ok=True)

base_filename = f"{PRICE_ZONE}_lstm_ae_search_results"
filename = output_folder / f"{base_filename}.csv"
counter = 1
while filename.exists():
    filename = output_folder / f"{base_filename}_{counter}.csv"
    counter += 1

results_df.to_csv(filename, index=False, decimal=",")
print(f"\nResults saved to: {filename}")
display(results_df.head(10))

Using pretrained encoder from Stage 1:
  latent_dim   = 48
  dense_layers = 1
  best recon SMAPE = 23.7420

Total combinations: 144
CV feature columns (32): ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity']

Combination 1/144: {'encoder_hidden_size': 16, 'layers': 1, 'decoder_hidden_size': 16, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 10, 'batch_size': 32, 'sequence_length': 24, 'dropout': 0.0}
Time: 0.00 minutes - estimated total time: 0.00 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 32
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity']
  Epoch 1/60
Model trained in 2.25s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 179.872
  Epoch 2/60
Model trained in 2.18s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 169.774
  Epoch 3/60
Model trained in 2.12s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 161.420
  Epoch 4/60
Model trained in 2.25s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 154.222
  Epoch 5/60
Model trained in 2.26s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 148.133
  Epoch 6/60
Model trained in 2.36s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 142.403
  Epoch 7/60
Model trained in 2.29s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 136.897
  Epoch 8/60
Model trained in 2.35s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 131.900
  Epoch 9/60
Model trained in 2.45s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 126.940
  Epoch 10/60
Model trained in 2.29s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 122.227
  Epoch 11/60
Model trained in 2.21s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 117.594
  Epoch 12/60
Model trained in 2.15s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 113.894
  Epoch 13/60
Model trained in 2.25s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 110.170
  Epoch 14/60
Model trained in 2.26s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 106.950
  Epoch 15/60
Model trained in 2.19s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 103.648
  Epoch 16/60
Model trained in 2.25s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 100.553
  Epoch 17/60
Model trained in 2.14s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 97.267
  Epoch 18/60
Model trained in 2.23s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 95.034
  Epoch 19/60
Model trained in 2.21s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.713
  Epoch 20/60
Model trained in 2.30s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.935
  Epoch 21/60
Model trained in 2.22s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.182
  Epoch 22/60
Model trained in 2.17s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.824
  Epoch 23/60
Model trained in 2.14s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.435
  Epoch 24/60
Model trained in 2.27s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.497
  Epoch 25/60
Model trained in 2.21s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.552
  Epoch 26/60
Model trained in 2.24s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.519
  Epoch 27/60
Model trained in 2.21s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.653
  Epoch 28/60
Model trained in 2.23s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.562
  Epoch 29/60
Model trained in 2.30s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.886
  Epoch 30/60
Model trained in 2.25s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.787
  Epoch 31/60
Model trained in 2.21s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.523
  Epoch 32/60
Model trained in 2.23s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.199
  Epoch 33/60
Model trained in 2.20s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.020
  Epoch 34/60
Model trained in 2.28s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.927
  Epoch 35/60
Model trained in 2.23s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.664
  Epoch 36/60
Model trained in 2.20s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.015
  Epoch 37/60
Model trained in 2.21s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.439
  Epoch 38/60
Model trained in 2.25s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.326
  Epoch 39/60
Model trained in 2.23s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.726
  Epoch 40/60
Model trained in 2.24s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.769
  Epoch 41/60
Model trained in 2.22s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.950
  Epoch 42/60
Model trained in 2.19s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.820
  Epoch 43/60
Model trained in 2.18s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.305
  Epoch 44/60
Model trained in 2.19s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.701
  Early stopping triggered.

  best_val_SMAPE=77.927

Combination 3/144: {'encoder_hidden_size': 16, 'layers': 1, 'decoder_hidden_size': 16, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 10, 'batch_size': 32, 'sequence_length': 168, 'dropout': 0.0}
Time: 2.04 minutes - estimated total time: 97.97 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 32
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity']
  Epoch 1/60
Model trained in 2.44s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 179.881
  Epoch 2/60
Model trained in 2.32s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 169.853
  Epoch 3/60
Model trained in 2.24s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 161.517
  Epoch 4/60
Model trained in 2.26s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 154.364
  Epoch 5/60
Model trained in 2.39s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 148.422
  Epoch 6/60
Model trained in 2.45s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 142.534
  Epoch 7/60
Model trained in 2.52s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 137.286
  Epoch 8/60
Model trained in 2.37s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 133.962
  Epoch 9/60
Model trained in 2.47s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 127.492
  Epoch 10/60
Model trained in 2.37s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 123.175
  Epoch 11/60
Model trained in 2.32s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 118.959
  Epoch 12/60
Model trained in 2.46s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 115.005
  Epoch 13/60
Model trained in 2.39s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 111.015
  Epoch 14/60
Model trained in 2.25s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 107.364
  Epoch 15/60
Model trained in 2.23s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 103.878
  Epoch 16/60
Model trained in 2.23s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 100.054
  Epoch 17/60
Model trained in 2.32s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 96.489
  Epoch 18/60
Model trained in 2.25s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.971
  Epoch 19/60
Model trained in 2.28s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.863
  Epoch 20/60
Model trained in 2.26s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.381
  Epoch 21/60
Model trained in 2.32s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.995
  Epoch 22/60
Model trained in 2.29s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.109
  Epoch 23/60
Model trained in 2.32s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.868
  Epoch 24/60
Model trained in 2.27s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.273
  Epoch 25/60
Model trained in 2.26s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.643
  Epoch 26/60
Model trained in 2.26s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.858
  Epoch 27/60
Model trained in 2.27s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.097
  Epoch 28/60
Model trained in 2.25s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.594
  Epoch 29/60
Model trained in 2.25s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 72.943
  Epoch 30/60
Model trained in 2.42s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 72.385
  Epoch 31/60
Model trained in 2.31s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 71.141
  Epoch 32/60
Model trained in 2.30s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 69.300
  Epoch 33/60
Model trained in 2.33s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 67.462
  Epoch 34/60
Model trained in 2.27s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 69.351
  Epoch 35/60
Model trained in 2.26s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 69.224
  Epoch 36/60
Model trained in 2.33s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 69.243
  Epoch 37/60
Model trained in 2.32s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 72.089
  Epoch 38/60
Model trained in 2.24s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 70.659
  Epoch 39/60
Model trained in 2.24s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.568
  Epoch 40/60
Model trained in 2.27s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 72.431
  Epoch 41/60
Model trained in 2.29s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.310
  Epoch 42/60
Model trained in 2.28s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.358
  Epoch 43/60
Model trained in 2.24s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.100
  Early stopping triggered.

  best_val_SMAPE=67.462

Combination 5/144: {'encoder_hidden_size': 16, 'layers': 1, 'decoder_hidden_size': 16, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 10, 'batch_size': 64, 'sequence_length': 24, 'dropout': 0.0}
Time: 4.05 minutes - estimated total time: 116.69 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 32
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity']
  Epoch 1/60
Model trained in 1.43s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 186.764
  Epoch 2/60
Model trained in 1.42s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 179.748
  Epoch 3/60
Model trained in 1.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 174.388
  Epoch 4/60
Model trained in 1.48s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 169.637
  Epoch 5/60
Model trained in 1.53s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 165.265
  Epoch 6/60
Model trained in 1.39s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 161.280
  Epoch 7/60
Model trained in 1.58s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 157.567
  Epoch 8/60
Model trained in 1.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 154.503
  Epoch 9/60
Model trained in 1.39s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 151.023
  Epoch 10/60
Model trained in 1.46s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 147.993
  Epoch 11/60
Model trained in 1.46s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 145.156
  Epoch 12/60
Model trained in 1.57s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 142.344
  Epoch 13/60
Model trained in 1.45s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 139.640
  Epoch 14/60
Model trained in 1.41s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 137.195
  Epoch 15/60
Model trained in 1.42s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 134.437
  Epoch 16/60
Model trained in 1.52s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 132.369
  Epoch 17/60
Model trained in 1.39s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 129.962
  Epoch 18/60
Model trained in 1.34s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 127.662
  Epoch 19/60
Model trained in 1.35s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 126.093
  Epoch 20/60
Model trained in 1.34s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 123.056
  Epoch 21/60
Model trained in 1.41s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 120.872
  Epoch 22/60
Model trained in 1.35s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 118.678
  Epoch 23/60
Model trained in 1.34s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 117.194
  Epoch 24/60
Model trained in 1.34s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 115.040
  Epoch 25/60
Model trained in 1.37s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 113.217
  Epoch 26/60
Model trained in 1.34s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 111.154
  Epoch 27/60
Model trained in 1.40s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 109.962
  Epoch 28/60
Model trained in 1.41s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 108.745
  Epoch 29/60
Model trained in 1.38s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 107.740
  Epoch 30/60
Model trained in 1.38s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 105.859
  Epoch 31/60
Model trained in 1.39s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 104.195
  Epoch 32/60
Model trained in 1.38s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 102.458
  Epoch 33/60
Model trained in 1.36s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 100.781
  Epoch 34/60
Model trained in 1.40s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 99.587
  Epoch 35/60
Model trained in 1.38s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 97.533
  Epoch 36/60
Model trained in 1.35s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 96.457
  Epoch 37/60
Model trained in 1.37s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.783
  Epoch 38/60
Model trained in 1.36s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.558
  Epoch 39/60
Model trained in 1.41s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.278
  Epoch 40/60
Model trained in 1.33s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.589
  Epoch 41/60
Model trained in 1.36s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.722
  Epoch 42/60
Model trained in 1.34s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.879
  Epoch 43/60
Model trained in 1.38s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.945
  Epoch 44/60
Model trained in 1.43s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.277
  Epoch 45/60
Model trained in 1.39s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.365
  Epoch 46/60
Model trained in 1.35s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.734
  Epoch 47/60
Model trained in 1.36s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.264
  Epoch 48/60
Model trained in 1.37s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.576
  Epoch 49/60
Model trained in 1.35s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.361
  Epoch 50/60
Model trained in 1.54s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.154
  Epoch 51/60
Model trained in 1.32s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.448
  Epoch 52/60
Model trained in 1.35s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.500
  Epoch 53/60
Model trained in 1.36s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.736
  Epoch 54/60
Model trained in 1.34s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.974
  Epoch 55/60
Model trained in 1.38s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.241
  Epoch 56/60
Model trained in 1.44s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 72.810
  Epoch 57/60
Model trained in 1.38s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 72.314
  Epoch 58/60
Model trained in 1.37s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 72.000
  Epoch 59/60
Model trained in 1.36s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 71.694
  Epoch 60/60
Model trained in 1.37s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 72.000

  best_val_SMAPE=71.694

Combination 7/144: {'encoder_hidden_size': 16, 'layers': 1, 'decoder_hidden_size': 16, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 10, 'batch_size': 64, 'sequence_length': 168, 'dropout': 0.0}
Time: 5.93 minutes - estimated total time: 121.91 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 32
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity']
  Epoch 1/60
Model trained in 1.57s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 186.758
  Epoch 2/60
Model trained in 1.47s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 179.799
  Epoch 3/60
Model trained in 1.48s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 174.470
  Epoch 4/60
Model trained in 1.55s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 169.744
  Epoch 5/60
Model trained in 1.54s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 165.386
  Epoch 6/60
Model trained in 1.47s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 161.370
  Epoch 7/60
Model trained in 1.49s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 157.674
  Epoch 8/60
Model trained in 1.46s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 154.209
  Epoch 9/60
Model trained in 1.47s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 151.056
  Epoch 10/60
Model trained in 1.43s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 148.012
  Epoch 11/60
Model trained in 1.57s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 145.040
  Epoch 12/60
Model trained in 1.46s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 142.177
  Epoch 13/60
Model trained in 1.47s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 139.606
  Epoch 14/60
Model trained in 1.43s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 136.716
  Epoch 15/60
Model trained in 1.45s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 134.093
  Epoch 16/60
Model trained in 1.46s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 131.428
  Epoch 17/60
Model trained in 1.45s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 129.055
  Epoch 18/60
Model trained in 1.44s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 126.330
  Epoch 19/60
Model trained in 1.46s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 124.268
  Epoch 20/60
Model trained in 1.42s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 121.861
  Epoch 21/60
Model trained in 1.49s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 119.580
  Epoch 22/60
Model trained in 1.50s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 117.512
  Epoch 23/60
Model trained in 1.45s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 115.532
  Epoch 24/60
Model trained in 1.44s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 113.907
  Epoch 25/60
Model trained in 1.43s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 112.936
  Epoch 26/60
Model trained in 1.44s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 111.929
  Epoch 27/60
Model trained in 1.47s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 110.978
  Epoch 28/60
Model trained in 1.43s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 110.113
  Epoch 29/60
Model trained in 1.45s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 109.127
  Epoch 30/60
Model trained in 1.43s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 107.568
  Epoch 31/60
Model trained in 1.49s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 105.974
  Epoch 32/60
Model trained in 1.53s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 104.354
  Epoch 33/60
Model trained in 1.48s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 102.678
  Epoch 34/60
Model trained in 1.43s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 100.968
  Epoch 35/60
Model trained in 1.47s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 99.270
  Epoch 36/60
Model trained in 1.44s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 97.359
  Epoch 37/60
Model trained in 1.52s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 96.294
  Epoch 38/60
Model trained in 1.44s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 94.691
  Epoch 39/60
Model trained in 1.44s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.157
  Epoch 40/60
Model trained in 1.41s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.683
  Epoch 41/60
Model trained in 1.45s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.483
  Epoch 42/60
Model trained in 1.63s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.678
  Epoch 43/60
Model trained in 1.46s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.015
  Epoch 44/60
Model trained in 1.44s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.275
  Epoch 45/60
Model trained in 1.45s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.492
  Epoch 46/60
Model trained in 1.43s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.105
  Epoch 47/60
Model trained in 1.48s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.279
  Epoch 48/60
Model trained in 1.51s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.409
  Epoch 49/60
Model trained in 1.46s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.862
  Epoch 50/60
Model trained in 1.47s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.191
  Epoch 51/60
Model trained in 1.47s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.478
  Epoch 52/60
Model trained in 1.43s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.390
  Epoch 53/60
Model trained in 1.53s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.136
  Epoch 54/60
Model trained in 1.46s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.107
  Epoch 55/60
Model trained in 1.48s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.324
  Epoch 56/60
Model trained in 1.46s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.582
  Epoch 57/60
Model trained in 1.47s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.583
  Epoch 58/60
Model trained in 1.49s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.533
  Epoch 59/60
Model trained in 1.44s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.151
  Epoch 60/60
Model trained in 1.45s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.262

  best_val_SMAPE=78.262

Combination 9/144: {'encoder_hidden_size': 16, 'layers': 1, 'decoder_hidden_size': 32, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 10, 'batch_size': 32, 'sequence_length': 24, 'dropout': 0.0}
Time: 7.86 minutes - estimated total time: 125.80 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 32
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity']
  Epoch 1/60
Model trained in 2.40s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 168.693
  Epoch 2/60
Model trained in 2.51s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 153.471
  Epoch 3/60
Model trained in 2.42s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 141.692
  Epoch 4/60
Model trained in 2.44s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 131.957
  Epoch 5/60
Model trained in 2.45s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 122.804
  Epoch 6/60
Model trained in 2.44s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 114.662
  Epoch 7/60
Model trained in 2.37s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 107.433
  Epoch 8/60
Model trained in 2.41s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 100.862
  Epoch 9/60
Model trained in 2.48s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 95.136
  Epoch 10/60
Model trained in 2.38s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.605
  Epoch 11/60
Model trained in 2.38s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.948
  Epoch 12/60
Model trained in 2.40s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.612
  Epoch 13/60
Model trained in 2.38s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.791
  Epoch 14/60
Model trained in 2.41s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.867
  Epoch 15/60
Model trained in 2.37s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.588
  Epoch 16/60
Model trained in 2.53s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.108
  Epoch 17/60
Model trained in 2.37s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.566
  Epoch 18/60
Model trained in 2.39s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 72.638
  Epoch 19/60
Model trained in 2.40s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.002
  Epoch 20/60
Model trained in 2.39s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 71.929
  Epoch 21/60
Model trained in 2.37s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 72.792
  Epoch 22/60
Model trained in 2.39s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 72.376
  Epoch 23/60
Model trained in 2.42s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 72.133
  Epoch 24/60
Model trained in 2.39s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 72.252
  Epoch 25/60
Model trained in 2.38s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 71.625
  Epoch 26/60
Model trained in 2.38s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.066
  Epoch 27/60
Model trained in 2.42s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 72.922
  Epoch 28/60
Model trained in 2.41s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.524
  Epoch 29/60
Model trained in 2.35s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 71.240
  Epoch 30/60
Model trained in 2.41s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 71.057
  Epoch 31/60
Model trained in 2.36s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 70.791
  Epoch 32/60
Model trained in 2.40s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 69.931
  Epoch 33/60
Model trained in 2.38s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 70.457
  Epoch 34/60
Model trained in 2.42s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 69.553
  Epoch 35/60
Model trained in 2.44s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 69.291
  Epoch 36/60
Model trained in 2.39s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 69.886
  Epoch 37/60
Model trained in 2.41s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 69.977
  Epoch 38/60
Model trained in 2.43s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 70.683
  Epoch 39/60
Model trained in 2.38s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 69.565
  Epoch 40/60
Model trained in 2.40s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 69.404
  Epoch 41/60
Model trained in 2.39s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 67.863
  Epoch 42/60
Model trained in 2.39s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 68.738
  Epoch 43/60
Model trained in 2.37s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 68.680
  Epoch 44/60
Model trained in 2.43s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 70.869
  Epoch 45/60
Model trained in 2.38s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 68.918
  Epoch 46/60
Model trained in 2.38s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 67.771
  Epoch 47/60
Model trained in 2.35s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 66.903
  Epoch 48/60
Model trained in 2.45s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 67.318
  Epoch 49/60
Model trained in 2.39s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 66.528
  Epoch 50/60
Model trained in 2.38s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 66.102
  Epoch 51/60
Model trained in 2.41s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 66.183
  Epoch 52/60
Model trained in 2.37s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 65.909
  Epoch 53/60
Model trained in 2.35s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 66.096
  Epoch 54/60
Model trained in 2.36s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 65.866
  Epoch 55/60
Model trained in 2.43s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 65.866
  Epoch 56/60
Model trained in 2.38s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 65.796
  Epoch 57/60
Model trained in 2.38s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 66.276
  Epoch 58/60
Model trained in 2.41s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 66.960
  Epoch 59/60
Model trained in 2.34s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 67.936
  Epoch 60/60
Model trained in 2.38s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 68.905

  best_val_SMAPE=65.796

Combination 11/144: {'encoder_hidden_size': 16, 'layers': 1, 'decoder_hidden_size': 32, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 10, 'batch_size': 32, 'sequence_length': 168, 'dropout': 0.0}
Time: 10.73 minutes - estimated total time: 140.53 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 32
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity']
  Epoch 1/60
Model trained in 2.54s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 168.765
  Epoch 2/60
Model trained in 2.47s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 153.605
  Epoch 3/60
Model trained in 2.55s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 141.870
  Epoch 4/60
Model trained in 2.46s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 131.833
  Epoch 5/60
Model trained in 2.47s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 123.579
  Epoch 6/60
Model trained in 2.51s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 115.561
  Epoch 7/60
Model trained in 2.48s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 108.132
  Epoch 8/60
Model trained in 2.50s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 101.820
  Epoch 9/60
Model trained in 2.47s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 96.602
  Epoch 10/60
Model trained in 2.50s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.358
  Epoch 11/60
Model trained in 2.57s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.648
  Epoch 12/60
Model trained in 2.52s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.839
  Epoch 13/60
Model trained in 2.47s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.166
  Epoch 14/60
Model trained in 2.48s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.786
  Epoch 15/60
Model trained in 2.46s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.218
  Epoch 16/60
Model trained in 2.47s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.881
  Epoch 17/60
Model trained in 2.47s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.468
  Epoch 18/60
Model trained in 2.57s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.170
  Epoch 19/60
Model trained in 2.46s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.960
  Epoch 20/60
Model trained in 2.47s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.478
  Epoch 21/60
Model trained in 2.46s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.869
  Epoch 22/60
Model trained in 2.49s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.795
  Epoch 23/60
Model trained in 2.44s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.539
  Epoch 24/60
Model trained in 2.48s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.436
  Epoch 25/60
Model trained in 2.52s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.777
  Epoch 26/60
Model trained in 2.46s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.931
  Epoch 27/60
Model trained in 2.46s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.548
  Epoch 28/60
Model trained in 2.51s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.618
  Epoch 29/60
Model trained in 2.45s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.132
  Epoch 30/60
Model trained in 2.46s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.119
  Epoch 31/60
Model trained in 2.45s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.172
  Epoch 32/60
Model trained in 2.52s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.406
  Epoch 33/60
Model trained in 2.44s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.288
  Epoch 34/60
Model trained in 2.48s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.361
  Early stopping triggered.

  best_val_SMAPE=73.436

Combination 13/144: {'encoder_hidden_size': 16, 'layers': 1, 'decoder_hidden_size': 32, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 10, 'batch_size': 64, 'sequence_length': 24, 'dropout': 0.0}
Time: 12.43 minutes - estimated total time: 137.65 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 32
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity']
  Epoch 1/60
Model trained in 1.56s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 178.446
  Epoch 2/60
Model trained in 1.50s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 168.624
  Epoch 3/60
Model trained in 1.53s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 160.421
  Epoch 4/60
Model trained in 1.56s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 153.335
  Epoch 5/60
Model trained in 1.55s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 147.180
  Epoch 6/60
Model trained in 1.56s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 141.594
  Epoch 7/60
Model trained in 1.51s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 136.362
  Epoch 8/60
Model trained in 1.52s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 131.589
  Epoch 9/60
Model trained in 1.51s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 127.192
  Epoch 10/60
Model trained in 1.49s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 122.924
  Epoch 11/60
Model trained in 1.56s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 118.787
  Epoch 12/60
Model trained in 1.48s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 116.087
  Epoch 13/60
Model trained in 1.50s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 111.813
  Epoch 14/60
Model trained in 1.50s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 108.547
  Epoch 15/60
Model trained in 1.48s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 104.852
  Epoch 16/60
Model trained in 1.53s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 101.462
  Epoch 17/60
Model trained in 1.46s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 98.641
  Epoch 18/60
Model trained in 1.48s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 98.630
  Epoch 19/60
Model trained in 1.45s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 96.318
  Epoch 20/60
Model trained in 1.50s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 95.198
  Epoch 21/60
Model trained in 1.53s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.235
  Epoch 22/60
Model trained in 1.47s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.816
  Epoch 23/60
Model trained in 1.45s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.956
  Epoch 24/60
Model trained in 1.48s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.797
  Epoch 25/60
Model trained in 1.47s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.201
  Epoch 26/60
Model trained in 1.48s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.237
  Epoch 27/60
Model trained in 1.52s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.768
  Epoch 28/60
Model trained in 1.49s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.889
  Epoch 29/60
Model trained in 1.47s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.961
  Epoch 30/60
Model trained in 1.48s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.910
  Epoch 31/60
Model trained in 1.47s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.061
  Epoch 32/60
Model trained in 1.51s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 71.869
  Epoch 33/60
Model trained in 1.46s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 70.724
  Epoch 34/60
Model trained in 1.47s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 69.661
  Epoch 35/60
Model trained in 1.46s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 69.036
  Epoch 36/60
Model trained in 1.50s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 69.976
  Epoch 37/60
Model trained in 1.54s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 69.248
  Epoch 38/60
Model trained in 1.49s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 69.988
  Epoch 39/60
Model trained in 1.47s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 70.526
  Epoch 40/60
Model trained in 1.48s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 72.553
  Epoch 41/60
Model trained in 1.47s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.181
  Epoch 42/60
Model trained in 1.50s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.460
  Epoch 43/60
Model trained in 1.46s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.280
  Epoch 44/60
Model trained in 1.48s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.584
  Epoch 45/60
Model trained in 1.48s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.984
  Early stopping triggered.

  best_val_SMAPE=69.036

Combination 15/144: {'encoder_hidden_size': 16, 'layers': 1, 'decoder_hidden_size': 32, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 10, 'batch_size': 64, 'sequence_length': 168, 'dropout': 0.0}
Time: 13.91 minutes - estimated total time: 133.53 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 32
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity']
  Epoch 1/60
Model trained in 1.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 178.469
  Epoch 2/60
Model trained in 1.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 168.704
  Epoch 3/60
Model trained in 1.61s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 160.535
  Epoch 4/60
Model trained in 1.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 153.510
  Epoch 5/60
Model trained in 1.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 147.375
  Epoch 6/60
Model trained in 1.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 141.724
  Epoch 7/60
Model trained in 1.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 136.583
  Epoch 8/60
Model trained in 1.62s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 131.960
  Epoch 9/60
Model trained in 1.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 127.816
  Epoch 10/60
Model trained in 1.62s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 123.470
  Epoch 11/60
Model trained in 1.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 120.304
  Epoch 12/60
Model trained in 1.57s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 116.385
  Epoch 13/60
Model trained in 1.57s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 112.586
  Epoch 14/60
Model trained in 1.59s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 108.451
  Epoch 15/60
Model trained in 1.60s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 105.075
  Epoch 16/60
Model trained in 1.60s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 102.177
  Epoch 17/60
Model trained in 1.60s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 99.314
  Epoch 18/60
Model trained in 1.62s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 96.023
  Epoch 19/60
Model trained in 1.57s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.267
  Epoch 20/60
Model trained in 1.57s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.567
  Epoch 21/60
Model trained in 1.65s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.572
  Epoch 22/60
Model trained in 1.57s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.652
  Epoch 23/60
Model trained in 1.58s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.791
  Epoch 24/60
Model trained in 1.57s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.534
  Epoch 25/60
Model trained in 1.54s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.621
  Epoch 26/60
Model trained in 1.59s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.809
  Epoch 27/60
Model trained in 1.60s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.099
  Epoch 28/60
Model trained in 1.58s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.721
  Epoch 29/60
Model trained in 1.60s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.856
  Epoch 30/60
Model trained in 1.58s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.974
  Epoch 31/60
Model trained in 1.68s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.655
  Epoch 32/60
Model trained in 1.56s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.372
  Epoch 33/60
Model trained in 1.58s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.134
  Epoch 34/60
Model trained in 1.56s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 72.919
  Epoch 35/60
Model trained in 1.60s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 72.465
  Epoch 36/60
Model trained in 1.59s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 72.147
  Epoch 37/60
Model trained in 1.58s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 72.454
  Epoch 38/60
Model trained in 1.57s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 72.367
  Epoch 39/60
Model trained in 1.58s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 71.792
  Epoch 40/60
Model trained in 1.58s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 72.477
  Epoch 41/60
Model trained in 1.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 72.439
  Epoch 42/60
Model trained in 1.57s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 72.815
  Epoch 43/60
Model trained in 1.57s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.835
  Epoch 44/60
Model trained in 1.56s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.978
  Epoch 45/60
Model trained in 1.59s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.799
  Epoch 46/60
Model trained in 1.58s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.165
  Epoch 47/60
Model trained in 1.57s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.250
  Epoch 48/60
Model trained in 1.59s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.926
  Epoch 49/60
Model trained in 1.57s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.815
  Early stopping triggered.

  best_val_SMAPE=71.792

Combination 17/144: {'encoder_hidden_size': 16, 'layers': 1, 'decoder_hidden_size': 48, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 10, 'batch_size': 32, 'sequence_length': 24, 'dropout': 0.0}
Time: 15.62 minutes - estimated total time: 132.30 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 32
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity']
  Epoch 1/60
Model trained in 2.42s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 160.409
  Epoch 2/60
Model trained in 2.36s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 141.380
  Epoch 3/60
Model trained in 2.44s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 127.389
  Epoch 4/60
Model trained in 2.39s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 115.242
  Epoch 5/60
Model trained in 2.49s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 105.089
  Epoch 6/60
Model trained in 2.42s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 96.114
  Epoch 7/60
Model trained in 2.45s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.216
  Epoch 8/60
Model trained in 2.42s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.938
  Epoch 9/60
Model trained in 2.38s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.932
  Epoch 10/60
Model trained in 2.37s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.896
  Epoch 11/60
Model trained in 2.44s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.366
  Epoch 12/60
Model trained in 2.37s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 68.497
  Epoch 13/60
Model trained in 2.37s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 70.746
  Epoch 14/60
Model trained in 2.42s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.270
  Epoch 15/60
Model trained in 2.35s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 71.528
  Epoch 16/60
Model trained in 2.37s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.224
  Epoch 17/60
Model trained in 2.32s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.250
  Epoch 18/60
Model trained in 2.37s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 72.429
  Epoch 19/60
Model trained in 2.33s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.815
  Epoch 20/60
Model trained in 2.36s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.485
  Epoch 21/60
Model trained in 2.37s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.502
  Epoch 22/60
Model trained in 2.37s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.315
  Early stopping triggered.

  best_val_SMAPE=68.497

Combination 19/144: {'encoder_hidden_size': 16, 'layers': 1, 'decoder_hidden_size': 48, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 10, 'batch_size': 32, 'sequence_length': 168, 'dropout': 0.0}
Time: 16.70 minutes - estimated total time: 126.58 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 32
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity']
  Epoch 1/60
Model trained in 2.52s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 160.601
  Epoch 2/60
Model trained in 2.48s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 141.575
  Epoch 3/60
Model trained in 2.52s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 128.087
  Epoch 4/60
Model trained in 2.50s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 115.203
  Epoch 5/60
Model trained in 2.52s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 104.263
  Epoch 6/60
Model trained in 2.47s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 96.689
  Epoch 7/60
Model trained in 2.46s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.448
  Epoch 8/60
Model trained in 2.49s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.607
  Epoch 9/60
Model trained in 2.59s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.001
  Epoch 10/60
Model trained in 2.48s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.155
  Epoch 11/60
Model trained in 2.47s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.739
  Epoch 12/60
Model trained in 2.51s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.222
  Epoch 13/60
Model trained in 2.57s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.497
  Epoch 14/60
Model trained in 2.48s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.551
  Epoch 15/60
Model trained in 2.49s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.448
  Epoch 16/60
Model trained in 2.52s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.911
  Epoch 17/60
Model trained in 2.50s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.699
  Epoch 18/60
Model trained in 2.47s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.823
  Epoch 19/60
Model trained in 2.56s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.930
  Epoch 20/60
Model trained in 2.48s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.300
  Epoch 21/60
Model trained in 2.47s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.710
  Epoch 22/60
Model trained in 2.46s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.499
  Epoch 23/60
Model trained in 2.46s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.738
  Early stopping triggered.

  best_val_SMAPE=78.497

Combination 21/144: {'encoder_hidden_size': 16, 'layers': 1, 'decoder_hidden_size': 48, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 10, 'batch_size': 64, 'sequence_length': 24, 'dropout': 0.0}
Time: 17.87 minutes - estimated total time: 122.52 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 32
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity']
  Epoch 1/60
Model trained in 1.58s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 173.270
  Epoch 2/60
Model trained in 1.49s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 160.372
  Epoch 3/60
Model trained in 1.61s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 150.058
  Epoch 4/60
Model trained in 1.50s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 141.242
  Epoch 5/60
Model trained in 1.50s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 133.533
  Epoch 6/60
Model trained in 1.53s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 127.063
  Epoch 7/60
Model trained in 1.52s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 121.629
  Epoch 8/60
Model trained in 1.54s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 114.605
  Epoch 9/60
Model trained in 1.48s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 109.021
  Epoch 10/60
Model trained in 1.46s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 104.509
  Epoch 11/60
Model trained in 1.57s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 99.973
  Epoch 12/60
Model trained in 1.51s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 96.216
  Epoch 13/60
Model trained in 1.58s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.345
  Epoch 14/60
Model trained in 1.48s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.252
  Epoch 15/60
Model trained in 1.49s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.859
  Epoch 16/60
Model trained in 1.51s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.922
  Epoch 17/60
Model trained in 1.54s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.551
  Epoch 18/60
Model trained in 1.53s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.532
  Epoch 19/60
Model trained in 1.54s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.636
  Epoch 20/60
Model trained in 1.48s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.025
  Epoch 21/60
Model trained in 1.55s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 71.320
  Epoch 22/60
Model trained in 1.52s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 69.703
  Epoch 23/60
Model trained in 1.53s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 69.121
  Epoch 24/60
Model trained in 1.50s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 68.918
  Epoch 25/60
Model trained in 1.47s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 68.202
  Epoch 26/60
Model trained in 1.47s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 67.853
  Epoch 27/60
Model trained in 1.48s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 67.143
  Epoch 28/60
Model trained in 1.49s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 67.302
  Epoch 29/60
Model trained in 1.51s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 67.655
  Epoch 30/60
Model trained in 1.46s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 67.825
  Epoch 31/60
Model trained in 1.50s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 67.868
  Epoch 32/60
Model trained in 1.52s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 68.158
  Epoch 33/60
Model trained in 1.51s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 70.110
  Epoch 34/60
Model trained in 1.61s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 70.457
  Epoch 35/60
Model trained in 1.49s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.059
  Epoch 36/60
Model trained in 1.48s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 70.228
  Epoch 37/60
Model trained in 1.49s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 70.145
  Early stopping triggered.

  best_val_SMAPE=67.143

Combination 23/144: {'encoder_hidden_size': 16, 'layers': 1, 'decoder_hidden_size': 48, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 10, 'batch_size': 64, 'sequence_length': 168, 'dropout': 0.0}
Time: 19.10 minutes - estimated total time: 119.60 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 32
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity']
  Epoch 1/60
Model trained in 1.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 173.572
  Epoch 2/60
Model trained in 1.61s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 160.552
  Epoch 3/60
Model trained in 1.62s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 150.224
  Epoch 4/60
Model trained in 1.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 141.421
  Epoch 5/60
Model trained in 1.65s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 134.030
  Epoch 6/60
Model trained in 1.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 127.428
  Epoch 7/60
Model trained in 1.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 121.635
  Epoch 8/60
Model trained in 1.60s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 115.397
  Epoch 9/60
Model trained in 1.58s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 109.798
  Epoch 10/60
Model trained in 1.62s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 105.366
  Epoch 11/60
Model trained in 1.59s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 100.292
  Epoch 12/60
Model trained in 1.62s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 96.177
  Epoch 13/60
Model trained in 1.63s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.920
  Epoch 14/60
Model trained in 1.63s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.934
  Epoch 15/60
Model trained in 1.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.735
  Epoch 16/60
Model trained in 1.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.171
  Epoch 17/60
Model trained in 1.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.972
  Epoch 18/60
Model trained in 1.62s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.391
  Epoch 19/60
Model trained in 1.59s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.246
  Epoch 20/60
Model trained in 1.67s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.704
  Epoch 21/60
Model trained in 1.63s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 71.794
  Epoch 22/60
Model trained in 1.57s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 71.064
  Epoch 23/60
Model trained in 1.58s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 69.835
  Epoch 24/60
Model trained in 1.61s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 69.900
  Epoch 25/60
Model trained in 1.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 68.166
  Epoch 26/60
Model trained in 1.62s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 67.928
  Epoch 27/60
Model trained in 1.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 68.211
  Epoch 28/60
Model trained in 1.62s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 68.465
  Epoch 29/60
Model trained in 1.63s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 70.812
  Epoch 30/60
Model trained in 1.61s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 70.627
  Epoch 31/60
Model trained in 1.60s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 71.383
  Epoch 32/60
Model trained in 1.57s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 70.967
  Epoch 33/60
Model trained in 1.58s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 69.736
  Epoch 34/60
Model trained in 1.59s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 71.726
  Epoch 35/60
Model trained in 1.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 71.736
  Epoch 36/60
Model trained in 1.59s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 69.950
  Early stopping triggered.

  best_val_SMAPE=67.928

Combination 25/144: {'encoder_hidden_size': 16, 'layers': 2, 'decoder_hidden_size': 16, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 10, 'batch_size': 32, 'sequence_length': 24, 'dropout': 0.0}
Time: 20.39 minutes - estimated total time: 117.44 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 32
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity']
  Epoch 1/60
Model trained in 2.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 180.257
  Epoch 2/60
Model trained in 2.60s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 170.167
  Epoch 3/60
Model trained in 2.65s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 161.679
  Epoch 4/60
Model trained in 2.59s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 154.285
  Epoch 5/60
Model trained in 2.68s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 147.530
  Epoch 6/60
Model trained in 2.56s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 141.742
  Epoch 7/60
Model trained in 2.59s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 136.517
  Epoch 8/60
Model trained in 2.62s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 131.136
  Epoch 9/60
Model trained in 2.63s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 126.158
  Epoch 10/60
Model trained in 2.61s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 121.631
  Epoch 11/60
Model trained in 2.60s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 117.378
  Epoch 12/60
Model trained in 2.61s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 112.937
  Epoch 13/60
Model trained in 2.61s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 109.445
  Epoch 14/60
Model trained in 2.53s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 105.394
  Epoch 15/60
Model trained in 2.65s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 101.722
  Epoch 16/60
Model trained in 2.58s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 98.174
  Epoch 17/60
Model trained in 2.59s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 94.854
  Epoch 18/60
Model trained in 2.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.618
  Epoch 19/60
Model trained in 2.63s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.169
  Epoch 20/60
Model trained in 2.56s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.987
  Epoch 21/60
Model trained in 2.52s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.898
  Epoch 22/60
Model trained in 2.52s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.200
  Epoch 23/60
Model trained in 2.56s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.211
  Epoch 24/60
Model trained in 2.55s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.480
  Epoch 25/60
Model trained in 2.63s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.164
  Epoch 26/60
Model trained in 2.55s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.287
  Epoch 27/60
Model trained in 2.54s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.045
  Epoch 28/60
Model trained in 2.61s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.921
  Epoch 29/60
Model trained in 2.60s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.558
  Epoch 30/60
Model trained in 2.56s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.235
  Epoch 31/60
Model trained in 2.57s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.169
  Epoch 32/60
Model trained in 2.54s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.452
  Epoch 33/60
Model trained in 2.57s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 72.553
  Epoch 34/60
Model trained in 2.58s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 72.589
  Epoch 35/60
Model trained in 2.63s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 71.237
  Epoch 36/60
Model trained in 2.59s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 71.094
  Epoch 37/60
Model trained in 2.56s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 71.186
  Epoch 38/60
Model trained in 2.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 72.403
  Epoch 39/60
Model trained in 2.61s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.138
  Epoch 40/60
Model trained in 2.57s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.767
  Epoch 41/60
Model trained in 2.60s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 72.436
  Epoch 42/60
Model trained in 2.59s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.445
  Epoch 43/60
Model trained in 2.58s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.981
  Epoch 44/60
Model trained in 2.59s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.050
  Epoch 45/60
Model trained in 2.67s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.197
  Epoch 46/60
Model trained in 2.57s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.276
  Early stopping triggered.

  best_val_SMAPE=71.094

Combination 26/144: {'encoder_hidden_size': 16, 'layers': 2, 'decoder_hidden_size': 16, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 10, 'batch_size': 32, 'sequence_length': 24, 'dropout': 0.2}
Time: 22.76 minutes - estimated total time: 126.07 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 32
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity']
  Epoch 1/60
Model trained in 2.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 180.175
  Epoch 2/60
Model trained in 2.63s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 170.138
  Epoch 3/60
Model trained in 2.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 161.662
  Epoch 4/60
Model trained in 2.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 154.274
  Epoch 5/60
Model trained in 2.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 147.748
  Epoch 6/60
Model trained in 2.65s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 141.599
  Epoch 7/60
Model trained in 2.62s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 135.991
  Epoch 8/60
Model trained in 2.67s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 130.854
  Epoch 9/60
Model trained in 2.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 125.798
  Epoch 10/60
Model trained in 2.61s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 125.593
  Epoch 11/60
Model trained in 2.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 120.660
  Epoch 12/60
Model trained in 2.59s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 116.210
  Epoch 13/60
Model trained in 2.59s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 112.183
  Epoch 14/60
Model trained in 2.62s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 104.901
  Epoch 15/60
Model trained in 2.60s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 101.312
  Epoch 16/60
Model trained in 2.60s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 98.298
  Epoch 17/60
Model trained in 2.61s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 101.930
  Epoch 18/60
Model trained in 2.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.046
  Epoch 19/60
Model trained in 2.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 95.135
  Epoch 20/60
Model trained in 2.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.476
  Epoch 21/60
Model trained in 2.67s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.211
  Epoch 22/60
Model trained in 2.56s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.586
  Epoch 23/60
Model trained in 2.60s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.703
  Epoch 24/60
Model trained in 2.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.375
  Epoch 25/60
Model trained in 2.61s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.668
  Epoch 26/60
Model trained in 2.61s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.431
  Epoch 27/60
Model trained in 2.61s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.848
  Epoch 28/60
Model trained in 2.63s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.373
  Epoch 29/60
Model trained in 2.59s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.718
  Epoch 30/60
Model trained in 2.60s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.411
  Epoch 31/60
Model trained in 2.60s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.622
  Epoch 32/60
Model trained in 2.61s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.124
  Epoch 33/60
Model trained in 2.61s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.733
  Epoch 34/60
Model trained in 2.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.068
  Epoch 35/60
Model trained in 2.68s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.497
  Epoch 36/60
Model trained in 2.63s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.231
  Epoch 37/60
Model trained in 2.63s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.494
  Epoch 38/60
Model trained in 2.62s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.748
  Epoch 39/60
Model trained in 2.61s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.690
  Epoch 40/60
Model trained in 2.63s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.928
  Epoch 41/60
Model trained in 2.60s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.724
  Epoch 42/60
Model trained in 2.61s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.548
  Epoch 43/60
Model trained in 2.61s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.725
  Epoch 44/60
Model trained in 2.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.572
  Epoch 45/60
Model trained in 2.59s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.626
  Epoch 46/60
Model trained in 2.61s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.469
  Epoch 47/60
Model trained in 2.62s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.908
  Epoch 48/60
Model trained in 2.62s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.696
  Early stopping triggered.

  best_val_SMAPE=73.748

Combination 27/144: {'encoder_hidden_size': 16, 'layers': 2, 'decoder_hidden_size': 16, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 10, 'batch_size': 32, 'sequence_length': 168, 'dropout': 0.0}
Time: 25.25 minutes - estimated total time: 134.69 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 32
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity']
  Epoch 1/60
Model trained in 2.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 180.268
  Epoch 2/60
Model trained in 2.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 170.286
  Epoch 3/60
Model trained in 2.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 161.846
  Epoch 4/60
Model trained in 2.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 154.480
  Epoch 5/60
Model trained in 2.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 147.953
  Epoch 6/60
Model trained in 2.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 141.857
  Epoch 7/60
Model trained in 2.68s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 136.543
  Epoch 8/60
Model trained in 2.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 131.102
  Epoch 9/60
Model trained in 2.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 126.095
  Epoch 10/60
Model trained in 2.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 121.455
  Epoch 11/60
Model trained in 2.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 117.151
  Epoch 12/60
Model trained in 2.67s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 112.875
  Epoch 13/60
Model trained in 2.68s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 109.396
  Epoch 14/60
Model trained in 2.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 106.034
  Epoch 15/60
Model trained in 2.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 102.849
  Epoch 16/60
Model trained in 2.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 99.158
  Epoch 17/60
Model trained in 2.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 96.077
  Epoch 18/60
Model trained in 2.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 94.347
  Epoch 19/60
Model trained in 2.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.535
  Epoch 20/60
Model trained in 2.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.439
  Epoch 21/60
Model trained in 2.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.639
  Epoch 22/60
Model trained in 2.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.948
  Epoch 23/60
Model trained in 2.68s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.363
  Epoch 24/60
Model trained in 2.67s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.802
  Epoch 25/60
Model trained in 2.67s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.419
  Epoch 26/60
Model trained in 2.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.078
  Epoch 27/60
Model trained in 2.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.791
  Epoch 28/60
Model trained in 2.68s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.492
  Epoch 29/60
Model trained in 2.68s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.401
  Epoch 30/60
Model trained in 2.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.219
  Epoch 31/60
Model trained in 2.65s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.376
  Epoch 32/60
Model trained in 2.68s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.710
  Epoch 33/60
Model trained in 2.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.561
  Epoch 34/60
Model trained in 2.67s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.049
  Epoch 35/60
Model trained in 2.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.205
  Epoch 36/60
Model trained in 2.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.387
  Epoch 37/60
Model trained in 2.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.386
  Epoch 38/60
Model trained in 2.68s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.749
  Epoch 39/60
Model trained in 2.67s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.386
  Epoch 40/60
Model trained in 2.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.679
  Epoch 41/60
Model trained in 2.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.056
  Epoch 42/60
Model trained in 2.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.361
  Epoch 43/60
Model trained in 2.68s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.425
  Epoch 44/60
Model trained in 2.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.548
  Early stopping triggered.

  best_val_SMAPE=76.049

Combination 28/144: {'encoder_hidden_size': 16, 'layers': 2, 'decoder_hidden_size': 16, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 10, 'batch_size': 32, 'sequence_length': 168, 'dropout': 0.2}
Time: 27.59 minutes - estimated total time: 141.89 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 32
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity']
  Epoch 1/60
Model trained in 2.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 180.259
  Epoch 2/60
Model trained in 2.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 170.278
  Epoch 3/60
Model trained in 2.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 161.839
  Epoch 4/60
Model trained in 2.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 154.462
  Epoch 5/60
Model trained in 2.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 148.012
  Epoch 6/60
Model trained in 2.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 142.001
  Epoch 7/60
Model trained in 2.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 136.462
  Epoch 8/60
Model trained in 2.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 131.248
  Epoch 9/60
Model trained in 2.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 127.054
  Epoch 10/60
Model trained in 2.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 123.105
  Epoch 11/60
Model trained in 2.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 118.769
  Epoch 12/60
Model trained in 2.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 115.139
  Epoch 13/60
Model trained in 2.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 112.894
  Epoch 14/60
Model trained in 2.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 109.069
  Epoch 15/60
Model trained in 2.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 104.490
  Epoch 16/60
Model trained in 2.68s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 101.465
  Epoch 17/60
Model trained in 2.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 99.474
  Epoch 18/60
Model trained in 2.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 97.452
  Epoch 19/60
Model trained in 2.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 95.466
  Epoch 20/60
Model trained in 2.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.590
  Epoch 21/60
Model trained in 2.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.869
  Epoch 22/60
Model trained in 2.67s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.605
  Epoch 23/60
Model trained in 2.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.048
  Epoch 24/60
Model trained in 2.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.896
  Epoch 25/60
Model trained in 2.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.950
  Epoch 26/60
Model trained in 2.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.113
  Epoch 27/60
Model trained in 2.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.519
  Epoch 28/60
Model trained in 2.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.508
  Epoch 29/60
Model trained in 2.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.547
  Epoch 30/60
Model trained in 2.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.264
  Epoch 31/60
Model trained in 2.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.954
  Epoch 32/60
Model trained in 2.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.363
  Epoch 33/60
Model trained in 2.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.842
  Epoch 34/60
Model trained in 2.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.003
  Epoch 35/60
Model trained in 2.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.339
  Epoch 36/60
Model trained in 2.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.987
  Early stopping triggered.

  best_val_SMAPE=81.113

Combination 29/144: {'encoder_hidden_size': 16, 'layers': 2, 'decoder_hidden_size': 16, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 10, 'batch_size': 64, 'sequence_length': 24, 'dropout': 0.0}
Time: 29.53 minutes - estimated total time: 146.66 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 32
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity']
  Epoch 1/60
Model trained in 1.65s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 186.904
  Epoch 2/60
Model trained in 1.61s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 180.120
  Epoch 3/60
Model trained in 1.62s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 174.824
  Epoch 4/60
Model trained in 1.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 170.077
  Epoch 5/60
Model trained in 1.60s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 165.671
  Epoch 6/60
Model trained in 1.58s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 161.573
  Epoch 7/60
Model trained in 1.59s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 157.764
  Epoch 8/60
Model trained in 1.59s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 154.164
  Epoch 9/60
Model trained in 1.63s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 150.785
  Epoch 10/60
Model trained in 1.57s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 147.564
  Epoch 11/60
Model trained in 1.59s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 144.461
  Epoch 12/60
Model trained in 1.63s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 141.496
  Epoch 13/60
Model trained in 1.61s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 138.643
  Epoch 14/60
Model trained in 1.61s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 135.890
  Epoch 15/60
Model trained in 1.58s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 133.880
  Epoch 16/60
Model trained in 1.58s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 132.905
  Epoch 17/60
Model trained in 1.58s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 136.738
  Epoch 18/60
Model trained in 1.62s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 125.039
  Epoch 19/60
Model trained in 1.57s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 124.389
  Epoch 20/60
Model trained in 1.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 122.062
  Epoch 21/60
Model trained in 1.59s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 120.596
  Epoch 22/60
Model trained in 1.61s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 119.111
  Epoch 23/60
Model trained in 1.58s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 125.459
  Epoch 24/60
Model trained in 1.54s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 127.734
  Epoch 25/60
Model trained in 1.55s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 126.189
  Epoch 26/60
Model trained in 1.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 116.122
  Epoch 27/60
Model trained in 1.58s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 112.020
  Epoch 28/60
Model trained in 1.58s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 108.365
  Epoch 29/60
Model trained in 1.59s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 106.507
  Epoch 30/60
Model trained in 1.59s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 105.017
  Epoch 31/60
Model trained in 1.56s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 103.782
  Epoch 32/60
Model trained in 1.57s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 101.884
  Epoch 33/60
Model trained in 1.59s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 101.614
  Epoch 34/60
Model trained in 1.59s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 105.799
  Epoch 35/60
Model trained in 1.60s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 100.536
  Epoch 36/60
Model trained in 1.63s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 99.515
  Epoch 37/60
Model trained in 1.56s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 97.926
  Epoch 38/60
Model trained in 1.57s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 99.588
  Epoch 39/60
Model trained in 1.57s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 100.052
  Epoch 40/60
Model trained in 1.58s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 96.531
  Epoch 41/60
Model trained in 1.59s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 96.836
  Epoch 42/60
Model trained in 1.57s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 95.673
  Epoch 43/60
Model trained in 1.62s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 95.121
  Epoch 44/60
Model trained in 1.57s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 94.641
  Epoch 45/60
Model trained in 1.62s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.052
  Epoch 46/60
Model trained in 1.59s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.572
  Epoch 47/60
Model trained in 1.59s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.280
  Epoch 48/60
Model trained in 1.61s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.542
  Epoch 49/60
Model trained in 1.60s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.825
  Epoch 50/60
Model trained in 1.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.590
  Epoch 51/60
Model trained in 1.62s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.225
  Epoch 52/60
Model trained in 1.62s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.344
  Epoch 53/60
Model trained in 1.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.657
  Epoch 54/60
Model trained in 1.57s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.795
  Epoch 55/60
Model trained in 1.56s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.609
  Epoch 56/60
Model trained in 1.60s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.126
  Epoch 57/60
Model trained in 1.56s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.914
  Epoch 58/60
Model trained in 1.62s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.187
  Epoch 59/60
Model trained in 1.62s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.629
  Epoch 60/60
Model trained in 1.57s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.113

  best_val_SMAPE=79.113

Combination 30/144: {'encoder_hidden_size': 16, 'layers': 2, 'decoder_hidden_size': 16, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 10, 'batch_size': 64, 'sequence_length': 24, 'dropout': 0.2}
Time: 31.61 minutes - estimated total time: 151.72 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 32
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity']
  Epoch 1/60
Model trained in 1.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 186.885
  Epoch 2/60
Model trained in 1.65s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 180.108
  Epoch 3/60
Model trained in 1.61s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 174.815
  Epoch 4/60
Model trained in 1.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 170.069
  Epoch 5/60
Model trained in 1.67s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 165.663
  Epoch 6/60
Model trained in 1.68s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 161.566
  Epoch 7/60
Model trained in 1.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 157.758
  Epoch 8/60
Model trained in 1.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 154.158
  Epoch 9/60
Model trained in 1.62s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 150.761
  Epoch 10/60
Model trained in 1.60s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 147.555
  Epoch 11/60
Model trained in 1.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 144.440
  Epoch 12/60
Model trained in 1.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 141.479
  Epoch 13/60
Model trained in 1.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 138.727
  Epoch 14/60
Model trained in 1.60s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 136.225
  Epoch 15/60
Model trained in 1.58s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 133.594
  Epoch 16/60
Model trained in 1.62s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 130.795
  Epoch 17/60
Model trained in 1.60s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 128.176
  Epoch 18/60
Model trained in 1.59s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 125.793
  Epoch 19/60
Model trained in 1.61s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 123.210
  Epoch 20/60
Model trained in 1.62s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 120.832
  Epoch 21/60
Model trained in 1.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 118.571
  Epoch 22/60
Model trained in 1.61s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 116.051
  Epoch 23/60
Model trained in 1.61s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 122.554
  Epoch 24/60
Model trained in 1.60s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 123.008
  Epoch 25/60
Model trained in 1.61s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 116.104
  Epoch 26/60
Model trained in 1.63s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 116.744
  Epoch 27/60
Model trained in 1.58s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 109.392
  Epoch 28/60
Model trained in 1.58s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 105.729
  Epoch 29/60
Model trained in 1.59s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 104.369
  Epoch 30/60
Model trained in 1.61s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 102.865
  Epoch 31/60
Model trained in 1.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 101.542
  Epoch 32/60
Model trained in 1.58s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 100.302
  Epoch 33/60
Model trained in 1.60s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 99.076
  Epoch 34/60
Model trained in 1.60s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 97.084
  Epoch 35/60
Model trained in 1.60s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 95.442
  Epoch 36/60
Model trained in 1.62s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 94.175
  Epoch 37/60
Model trained in 1.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 94.423
  Epoch 38/60
Model trained in 1.62s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.366
  Epoch 39/60
Model trained in 1.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.103
  Epoch 40/60
Model trained in 1.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.431
  Epoch 41/60
Model trained in 1.65s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.423
  Epoch 42/60
Model trained in 1.57s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 95.807
  Epoch 43/60
Model trained in 1.60s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 96.563
  Epoch 44/60
Model trained in 1.61s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 98.668
  Epoch 45/60
Model trained in 1.61s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 98.866
  Epoch 46/60
Model trained in 1.59s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 100.685
  Epoch 47/60
Model trained in 1.59s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 99.370
  Epoch 48/60
Model trained in 1.63s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 95.417
  Early stopping triggered.

  best_val_SMAPE=91.366

Combination 31/144: {'encoder_hidden_size': 16, 'layers': 2, 'decoder_hidden_size': 16, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 10, 'batch_size': 64, 'sequence_length': 168, 'dropout': 0.0}
Time: 33.30 minutes - estimated total time: 154.68 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 32
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity']
  Epoch 1/60
Model trained in 1.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 186.934
  Epoch 2/60
Model trained in 1.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 180.166
  Epoch 3/60
Model trained in 1.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 174.895
  Epoch 4/60
Model trained in 1.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 170.167
  Epoch 5/60
Model trained in 1.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 165.778
  Epoch 6/60
Model trained in 1.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 161.697
  Epoch 7/60
Model trained in 1.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 157.897
  Epoch 8/60
Model trained in 1.68s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 154.310
  Epoch 9/60
Model trained in 1.68s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 150.938
  Epoch 10/60
Model trained in 1.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 147.703
  Epoch 11/60
Model trained in 1.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 144.525
  Epoch 12/60
Model trained in 1.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 141.623
  Epoch 13/60
Model trained in 1.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 138.771
  Epoch 14/60
Model trained in 1.65s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 136.044
  Epoch 15/60
Model trained in 1.68s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 133.370
  Epoch 16/60
Model trained in 1.67s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 130.746
  Epoch 17/60
Model trained in 1.67s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 128.244
  Epoch 18/60
Model trained in 1.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 125.951
  Epoch 19/60
Model trained in 1.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 123.683
  Epoch 20/60
Model trained in 1.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 121.465
  Epoch 21/60
Model trained in 1.68s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 119.137
  Epoch 22/60
Model trained in 1.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 117.173
  Epoch 23/60
Model trained in 1.68s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 115.443
  Epoch 24/60
Model trained in 1.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 113.789
  Epoch 25/60
Model trained in 1.65s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 111.824
  Epoch 26/60
Model trained in 1.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 109.544
  Epoch 27/60
Model trained in 1.67s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 107.818
  Epoch 28/60
Model trained in 1.67s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 105.919
  Epoch 29/60
Model trained in 1.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 104.411
  Epoch 30/60
Model trained in 1.68s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 102.957
  Epoch 31/60
Model trained in 1.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 101.781
  Epoch 32/60
Model trained in 1.67s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 100.648
  Epoch 33/60
Model trained in 1.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 99.457
  Epoch 34/60
Model trained in 1.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 99.061
  Epoch 35/60
Model trained in 1.67s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 97.827
  Epoch 36/60
Model trained in 1.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 96.597
  Epoch 37/60
Model trained in 1.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 95.314
  Epoch 38/60
Model trained in 1.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 94.017
  Epoch 39/60
Model trained in 1.68s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.323
  Epoch 40/60
Model trained in 1.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.504
  Epoch 41/60
Model trained in 1.67s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.167
  Epoch 42/60
Model trained in 1.67s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.554
  Epoch 43/60
Model trained in 1.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.357
  Epoch 44/60
Model trained in 1.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.477
  Epoch 45/60
Model trained in 1.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.682
  Epoch 46/60
Model trained in 1.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.139
  Epoch 47/60
Model trained in 1.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.162
  Epoch 48/60
Model trained in 1.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.080
  Epoch 49/60
Model trained in 1.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.512
  Epoch 50/60
Model trained in 1.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.906
  Epoch 51/60
Model trained in 1.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.572
  Epoch 52/60
Model trained in 1.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.697
  Epoch 53/60
Model trained in 1.68s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.658
  Epoch 54/60
Model trained in 1.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.848
  Epoch 55/60
Model trained in 1.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.701
  Epoch 56/60
Model trained in 1.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.651
  Epoch 57/60
Model trained in 1.67s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.840
  Epoch 58/60
Model trained in 1.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.521
  Epoch 59/60
Model trained in 1.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.366
  Epoch 60/60
Model trained in 1.67s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.138

  best_val_SMAPE=81.658

Combination 32/144: {'encoder_hidden_size': 16, 'layers': 2, 'decoder_hidden_size': 16, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 10, 'batch_size': 64, 'sequence_length': 168, 'dropout': 0.2}
Time: 35.47 minutes - estimated total time: 159.63 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 32
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity']
  Epoch 1/60
Model trained in 1.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 186.923
  Epoch 2/60
Model trained in 1.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 180.157
  Epoch 3/60
Model trained in 1.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 174.886
  Epoch 4/60
Model trained in 1.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 170.158
  Epoch 5/60
Model trained in 1.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 165.770
  Epoch 6/60
Model trained in 1.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 161.689
  Epoch 7/60
Model trained in 1.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 157.890
  Epoch 8/60
Model trained in 1.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 154.303
  Epoch 9/60
Model trained in 1.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 150.935
  Epoch 10/60
Model trained in 1.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 147.719
  Epoch 11/60
Model trained in 1.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 144.715
  Epoch 12/60
Model trained in 1.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 141.765
  Epoch 13/60
Model trained in 1.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 138.841
  Epoch 14/60
Model trained in 1.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 136.138
  Epoch 15/60
Model trained in 1.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 133.374
  Epoch 16/60
Model trained in 1.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 131.182
  Epoch 17/60
Model trained in 1.68s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 128.884
  Epoch 18/60
Model trained in 1.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 126.431
  Epoch 19/60
Model trained in 1.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 124.390
  Epoch 20/60
Model trained in 1.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 122.253
  Epoch 21/60
Model trained in 1.68s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 119.719
  Epoch 22/60
Model trained in 1.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 117.762
  Epoch 23/60
Model trained in 1.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 115.961
  Epoch 24/60
Model trained in 1.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 113.811
  Epoch 25/60
Model trained in 1.68s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 111.963
  Epoch 26/60
Model trained in 1.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 110.067
  Epoch 27/60
Model trained in 1.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 108.182
  Epoch 28/60
Model trained in 1.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 106.626
  Epoch 29/60
Model trained in 1.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 104.670
  Epoch 30/60
Model trained in 1.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 103.009
  Epoch 31/60
Model trained in 1.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 101.395
  Epoch 32/60
Model trained in 1.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 99.898
  Epoch 33/60
Model trained in 1.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 98.244
  Epoch 34/60
Model trained in 1.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 96.689
  Epoch 35/60
Model trained in 1.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 95.620
  Epoch 36/60
Model trained in 1.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 94.228
  Epoch 37/60
Model trained in 1.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.448
  Epoch 38/60
Model trained in 1.68s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.131
  Epoch 39/60
Model trained in 1.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.200
  Epoch 40/60
Model trained in 1.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.098
  Epoch 41/60
Model trained in 1.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.757
  Epoch 42/60
Model trained in 1.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.049
  Epoch 43/60
Model trained in 1.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.100
  Epoch 44/60
Model trained in 1.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.100
  Epoch 45/60
Model trained in 1.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.436
  Epoch 46/60
Model trained in 1.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.786
  Epoch 47/60
Model trained in 1.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.568
  Epoch 48/60
Model trained in 1.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.583
  Epoch 49/60
Model trained in 1.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.659
  Epoch 50/60
Model trained in 1.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.354
  Epoch 51/60
Model trained in 1.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.134
  Epoch 52/60
Model trained in 1.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.132
  Epoch 53/60
Model trained in 1.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.055
  Epoch 54/60
Model trained in 1.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.647
  Epoch 55/60
Model trained in 1.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.298
  Epoch 56/60
Model trained in 1.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.341
  Epoch 57/60
Model trained in 1.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.711
  Epoch 58/60
Model trained in 1.68s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.399
  Epoch 59/60
Model trained in 1.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.885
  Epoch 60/60
Model trained in 1.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.183

  best_val_SMAPE=79.183

Combination 33/144: {'encoder_hidden_size': 16, 'layers': 2, 'decoder_hidden_size': 32, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 10, 'batch_size': 32, 'sequence_length': 24, 'dropout': 0.0}
Time: 37.67 minutes - estimated total time: 164.38 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 32
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity']
  Epoch 1/60
Model trained in 2.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 169.532
  Epoch 2/60
Model trained in 2.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 154.134
  Epoch 3/60
Model trained in 2.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 141.887
  Epoch 4/60
Model trained in 2.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 131.338
  Epoch 5/60
Model trained in 2.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 121.698
  Epoch 6/60
Model trained in 2.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 113.128
  Epoch 7/60
Model trained in 2.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 106.473
  Epoch 8/60
Model trained in 2.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 99.633
  Epoch 9/60
Model trained in 2.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.529
  Epoch 10/60
Model trained in 2.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.993
  Epoch 11/60
Model trained in 2.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.960
  Epoch 12/60
Model trained in 2.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.143
  Epoch 13/60
Model trained in 2.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.339
  Epoch 14/60
Model trained in 2.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.543
  Epoch 15/60
Model trained in 2.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.942
  Epoch 16/60
Model trained in 2.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.250
  Epoch 17/60
Model trained in 2.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.360
  Epoch 18/60
Model trained in 2.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.537
  Epoch 19/60
Model trained in 2.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.998
  Epoch 20/60
Model trained in 2.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.734
  Epoch 21/60
Model trained in 2.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.718
  Epoch 22/60
Model trained in 2.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.049
  Epoch 23/60
Model trained in 2.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.039
  Epoch 24/60
Model trained in 2.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.813
  Epoch 25/60
Model trained in 2.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.748
  Epoch 26/60
Model trained in 2.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 71.972
  Epoch 27/60
Model trained in 2.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 70.819
  Epoch 28/60
Model trained in 2.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 71.426
  Epoch 29/60
Model trained in 2.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 70.812
  Epoch 30/60
Model trained in 2.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 70.897
  Epoch 31/60
Model trained in 2.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 70.609
  Epoch 32/60
Model trained in 2.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 69.866
  Epoch 33/60
Model trained in 2.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 70.144
  Epoch 34/60
Model trained in 2.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 70.134
  Epoch 35/60
Model trained in 2.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 68.949
  Epoch 36/60
Model trained in 2.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 67.016
  Epoch 37/60
Model trained in 2.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 67.076
  Epoch 38/60
Model trained in 2.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 67.079
  Epoch 39/60
Model trained in 2.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 67.086
  Epoch 40/60
Model trained in 2.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 68.176
  Epoch 41/60
Model trained in 2.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 67.807
  Epoch 42/60
Model trained in 2.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 68.227
  Epoch 43/60
Model trained in 2.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 69.402
  Epoch 44/60
Model trained in 2.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 70.034
  Epoch 45/60
Model trained in 2.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 70.988
  Epoch 46/60
Model trained in 2.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 71.029
  Early stopping triggered.

  best_val_SMAPE=67.016

Combination 34/144: {'encoder_hidden_size': 16, 'layers': 2, 'decoder_hidden_size': 32, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 10, 'batch_size': 32, 'sequence_length': 24, 'dropout': 0.2}
Time: 40.24 minutes - estimated total time: 170.43 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 32
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity']
  Epoch 1/60
Model trained in 2.95s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 169.525
  Epoch 2/60
Model trained in 2.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 154.128
  Epoch 3/60
Model trained in 2.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 141.881
  Epoch 4/60
Model trained in 2.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 131.333
  Epoch 5/60
Model trained in 2.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 121.748
  Epoch 6/60
Model trained in 2.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 113.934
  Epoch 7/60
Model trained in 2.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 106.763
  Epoch 8/60
Model trained in 2.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 100.295
  Epoch 9/60
Model trained in 2.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 95.209
  Epoch 10/60
Model trained in 2.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.190
  Epoch 11/60
Model trained in 2.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.222
  Epoch 12/60
Model trained in 2.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.242
  Epoch 13/60
Model trained in 2.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.293
  Epoch 14/60
Model trained in 2.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.526
  Epoch 15/60
Model trained in 2.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.319
  Epoch 16/60
Model trained in 3.02s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.139
  Epoch 17/60
Model trained in 2.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.585
  Epoch 18/60
Model trained in 2.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.536
  Epoch 19/60
Model trained in 2.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.167
  Epoch 20/60
Model trained in 2.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.631
  Epoch 21/60
Model trained in 2.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.320
  Epoch 22/60
Model trained in 2.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.705
  Epoch 23/60
Model trained in 2.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.784
  Epoch 24/60
Model trained in 2.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.277
  Epoch 25/60
Model trained in 2.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.531
  Epoch 26/60
Model trained in 2.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.149
  Early stopping triggered.

  best_val_SMAPE=78.139

Combination 35/144: {'encoder_hidden_size': 16, 'layers': 2, 'decoder_hidden_size': 32, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 10, 'batch_size': 32, 'sequence_length': 168, 'dropout': 0.0}
Time: 41.72 minutes - estimated total time: 171.67 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 32
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity']
  Epoch 1/60
Model trained in 2.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 169.606
  Epoch 2/60
Model trained in 2.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 154.288
  Epoch 3/60
Model trained in 2.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 142.090
  Epoch 4/60
Model trained in 2.98s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 131.588
  Epoch 5/60
Model trained in 3.01s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 122.017
  Epoch 6/60
Model trained in 2.97s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 113.606
  Epoch 7/60
Model trained in 2.99s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 106.302
  Epoch 8/60
Model trained in 2.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 100.117
  Epoch 9/60
Model trained in 2.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 94.775
  Epoch 10/60
Model trained in 2.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.418
  Epoch 11/60
Model trained in 2.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.716
  Epoch 12/60
Model trained in 2.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.141
  Epoch 13/60
Model trained in 2.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.912
  Epoch 14/60
Model trained in 2.98s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.736
  Epoch 15/60
Model trained in 2.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.204
  Epoch 16/60
Model trained in 2.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.729
  Epoch 17/60
Model trained in 2.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.759
  Epoch 18/60
Model trained in 2.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.145
  Epoch 19/60
Model trained in 2.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 72.430
  Epoch 20/60
Model trained in 2.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.091
  Epoch 21/60
Model trained in 2.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.074
  Epoch 22/60
Model trained in 2.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.469
  Epoch 23/60
Model trained in 2.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.940
  Epoch 24/60
Model trained in 2.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 72.589
  Epoch 25/60
Model trained in 2.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.194
  Epoch 26/60
Model trained in 2.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 72.768
  Epoch 27/60
Model trained in 2.97s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 70.934
  Epoch 28/60
Model trained in 2.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 69.419
  Epoch 29/60
Model trained in 2.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 69.713
  Epoch 30/60
Model trained in 2.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 69.131
  Epoch 31/60
Model trained in 2.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 71.838
  Epoch 32/60
Model trained in 2.98s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 72.378
  Epoch 33/60
Model trained in 2.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 71.734
  Epoch 34/60
Model trained in 2.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 71.570
  Epoch 35/60
Model trained in 2.95s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 71.063
  Epoch 36/60
Model trained in 2.95s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 70.496
  Epoch 37/60
Model trained in 2.95s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 69.334
  Epoch 38/60
Model trained in 2.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 69.195
  Epoch 39/60
Model trained in 2.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 69.790
  Epoch 40/60
Model trained in 2.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 69.745
  Early stopping triggered.

  best_val_SMAPE=69.131

Combination 36/144: {'encoder_hidden_size': 16, 'layers': 2, 'decoder_hidden_size': 32, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 10, 'batch_size': 32, 'sequence_length': 168, 'dropout': 0.2}
Time: 44.00 minutes - estimated total time: 176.01 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 32
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity']
  Epoch 1/60
Model trained in 2.99s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 169.598
  Epoch 2/60
Model trained in 2.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 154.282
  Epoch 3/60
Model trained in 3.15s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 142.084
  Epoch 4/60
Model trained in 3.02s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 131.582
  Epoch 5/60
Model trained in 3.01s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 121.956
  Epoch 6/60
Model trained in 2.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 113.933
  Epoch 7/60
Model trained in 2.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 106.347
  Epoch 8/60
Model trained in 2.97s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 99.637
  Epoch 9/60
Model trained in 2.99s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.203
  Epoch 10/60
Model trained in 2.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.016
  Epoch 11/60
Model trained in 2.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.120
  Epoch 12/60
Model trained in 2.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.166
  Epoch 13/60
Model trained in 2.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.785
  Epoch 14/60
Model trained in 2.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.549
  Epoch 15/60
Model trained in 2.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 72.993
  Epoch 16/60
Model trained in 2.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 72.083
  Epoch 17/60
Model trained in 2.99s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 70.817
  Epoch 18/60
Model trained in 3.01s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 70.032
  Epoch 19/60
Model trained in 2.98s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 69.006
  Epoch 20/60
Model trained in 3.01s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 68.878
  Epoch 21/60
Model trained in 2.95s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 68.789
  Epoch 22/60
Model trained in 2.98s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 69.025
  Epoch 23/60
Model trained in 2.95s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 68.065
  Epoch 24/60
Model trained in 2.99s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 67.294
  Epoch 25/60
Model trained in 2.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 66.903
  Epoch 26/60
Model trained in 2.98s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 66.541
  Epoch 27/60
Model trained in 2.99s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 67.175
  Epoch 28/60
Model trained in 2.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 67.416
  Epoch 29/60
Model trained in 2.95s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 67.913
  Epoch 30/60
Model trained in 2.95s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 68.429
  Epoch 31/60
Model trained in 3.01s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 69.017
  Epoch 32/60
Model trained in 3.01s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 68.928
  Epoch 33/60
Model trained in 2.97s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 69.119
  Epoch 34/60
Model trained in 2.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 69.237
  Epoch 35/60
Model trained in 2.99s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 69.404
  Epoch 36/60
Model trained in 2.99s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 69.181
  Early stopping triggered.

  best_val_SMAPE=66.541

Combination 37/144: {'encoder_hidden_size': 16, 'layers': 2, 'decoder_hidden_size': 32, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 10, 'batch_size': 64, 'sequence_length': 24, 'dropout': 0.0}
Time: 46.09 minutes - estimated total time: 179.36 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 32
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity']
  Epoch 1/60
Model trained in 1.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 179.127
  Epoch 2/60
Model trained in 1.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 169.400
  Epoch 3/60
Model trained in 1.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 161.152
  Epoch 4/60
Model trained in 1.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 153.984
  Epoch 5/60
Model trained in 1.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 147.589
  Epoch 6/60
Model trained in 1.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 141.710
  Epoch 7/60
Model trained in 1.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 136.285
  Epoch 8/60
Model trained in 1.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 131.162
  Epoch 9/60
Model trained in 1.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 127.154
  Epoch 10/60
Model trained in 1.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 122.242
  Epoch 11/60
Model trained in 1.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 117.823
  Epoch 12/60
Model trained in 1.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 114.383
  Epoch 13/60
Model trained in 1.68s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 110.631
  Epoch 14/60
Model trained in 1.68s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 106.698
  Epoch 15/60
Model trained in 1.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 102.978
  Epoch 16/60
Model trained in 1.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 100.151
  Epoch 17/60
Model trained in 1.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 96.245
  Epoch 18/60
Model trained in 1.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.423
  Epoch 19/60
Model trained in 1.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.507
  Epoch 20/60
Model trained in 1.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.061
  Epoch 21/60
Model trained in 1.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.435
  Epoch 22/60
Model trained in 1.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.021
  Epoch 23/60
Model trained in 1.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.913
  Epoch 24/60
Model trained in 1.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.112
  Epoch 25/60
Model trained in 1.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.486
  Epoch 26/60
Model trained in 1.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.228
  Epoch 27/60
Model trained in 1.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.819
  Epoch 28/60
Model trained in 1.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.957
  Epoch 29/60
Model trained in 1.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.261
  Epoch 30/60
Model trained in 1.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.635
  Epoch 31/60
Model trained in 1.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.673
  Epoch 32/60
Model trained in 1.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.887
  Epoch 33/60
Model trained in 1.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.496
  Epoch 34/60
Model trained in 1.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.080
  Epoch 35/60
Model trained in 1.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.890
  Epoch 36/60
Model trained in 1.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.449
  Epoch 37/60
Model trained in 1.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.924
  Epoch 38/60
Model trained in 1.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.152
  Epoch 39/60
Model trained in 1.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.428
  Epoch 40/60
Model trained in 1.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.911
  Epoch 41/60
Model trained in 1.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.312
  Epoch 42/60
Model trained in 1.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.032
  Epoch 43/60
Model trained in 1.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.079
  Epoch 44/60
Model trained in 1.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.272
  Epoch 45/60
Model trained in 1.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.583
  Epoch 46/60
Model trained in 1.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.547
  Epoch 47/60
Model trained in 1.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.643
  Epoch 48/60
Model trained in 1.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.781
  Epoch 49/60
Model trained in 1.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.455
  Epoch 50/60
Model trained in 1.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.951
  Epoch 51/60
Model trained in 1.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.521
  Early stopping triggered.

  best_val_SMAPE=74.312

Combination 38/144: {'encoder_hidden_size': 16, 'layers': 2, 'decoder_hidden_size': 32, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 10, 'batch_size': 64, 'sequence_length': 24, 'dropout': 0.2}
Time: 47.96 minutes - estimated total time: 181.75 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 32
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity']
  Epoch 1/60
Model trained in 1.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 179.120
  Epoch 2/60
Model trained in 1.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 169.393
  Epoch 3/60
Model trained in 1.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 161.146
  Epoch 4/60
Model trained in 1.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 153.977
  Epoch 5/60
Model trained in 1.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 147.583
  Epoch 6/60
Model trained in 1.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 141.705
  Epoch 7/60
Model trained in 1.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 136.280
  Epoch 8/60
Model trained in 1.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 131.147
  Epoch 9/60
Model trained in 1.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 126.235
  Epoch 10/60
Model trained in 1.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 121.541
  Epoch 11/60
Model trained in 1.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 116.676
  Epoch 12/60
Model trained in 1.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 113.490
  Epoch 13/60
Model trained in 1.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 109.251
  Epoch 14/60
Model trained in 1.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 105.836
  Epoch 15/60
Model trained in 1.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 102.564
  Epoch 16/60
Model trained in 1.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 99.013
  Epoch 17/60
Model trained in 1.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 96.049
  Epoch 18/60
Model trained in 1.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.606
  Epoch 19/60
Model trained in 1.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.799
  Epoch 20/60
Model trained in 1.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.974
  Epoch 21/60
Model trained in 1.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.793
  Epoch 22/60
Model trained in 1.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.397
  Epoch 23/60
Model trained in 1.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.775
  Epoch 24/60
Model trained in 1.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.873
  Epoch 25/60
Model trained in 1.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.945
  Epoch 26/60
Model trained in 1.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.110
  Epoch 27/60
Model trained in 1.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.071
  Epoch 28/60
Model trained in 1.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.894
  Epoch 29/60
Model trained in 1.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.141
  Epoch 30/60
Model trained in 1.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.335
  Epoch 31/60
Model trained in 1.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.598
  Epoch 32/60
Model trained in 1.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.643
  Epoch 33/60
Model trained in 1.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.813
  Epoch 34/60
Model trained in 1.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.053
  Epoch 35/60
Model trained in 1.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.873
  Epoch 36/60
Model trained in 1.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.646
  Epoch 37/60
Model trained in 1.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.440
  Epoch 38/60
Model trained in 1.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.745
  Epoch 39/60
Model trained in 1.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.509
  Epoch 40/60
Model trained in 1.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.040
  Epoch 41/60
Model trained in 1.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.712
  Early stopping triggered.

  best_val_SMAPE=74.598

Combination 39/144: {'encoder_hidden_size': 16, 'layers': 2, 'decoder_hidden_size': 32, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 10, 'batch_size': 64, 'sequence_length': 168, 'dropout': 0.0}
Time: 49.49 minutes - estimated total time: 182.75 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 32
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity']
  Epoch 1/60
Model trained in 2.04s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 179.131
  Epoch 2/60
Model trained in 1.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 169.457
  Epoch 3/60
Model trained in 1.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 161.243
  Epoch 4/60
Model trained in 1.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 154.098
  Epoch 5/60
Model trained in 1.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 147.726
  Epoch 6/60
Model trained in 1.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 141.868
  Epoch 7/60
Model trained in 1.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 136.460
  Epoch 8/60
Model trained in 1.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 131.339
  Epoch 9/60
Model trained in 1.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 126.457
  Epoch 10/60
Model trained in 1.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 122.006
  Epoch 11/60
Model trained in 1.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 117.639
  Epoch 12/60
Model trained in 1.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 122.227
  Epoch 13/60
Model trained in 1.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 109.229
  Epoch 14/60
Model trained in 1.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 105.771
  Epoch 15/60
Model trained in 1.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 102.121
  Epoch 16/60
Model trained in 1.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 99.944
  Epoch 17/60
Model trained in 1.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 96.890
  Epoch 18/60
Model trained in 1.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.609
  Epoch 19/60
Model trained in 1.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.471
  Epoch 20/60
Model trained in 1.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.597
  Epoch 21/60
Model trained in 1.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.875
  Epoch 22/60
Model trained in 1.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.354
  Epoch 23/60
Model trained in 1.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.366
  Epoch 24/60
Model trained in 1.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.516
  Epoch 25/60
Model trained in 1.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.619
  Epoch 26/60
Model trained in 1.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.675
  Epoch 27/60
Model trained in 1.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.219
  Epoch 28/60
Model trained in 1.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.610
  Epoch 29/60
Model trained in 1.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.067
  Epoch 30/60
Model trained in 1.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 72.298
  Epoch 31/60
Model trained in 1.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 71.598
  Epoch 32/60
Model trained in 1.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 71.967
  Epoch 33/60
Model trained in 1.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 72.059
  Epoch 34/60
Model trained in 1.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 71.353
  Epoch 35/60
Model trained in 1.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 72.409
  Epoch 36/60
Model trained in 1.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 72.861
  Epoch 37/60
Model trained in 1.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.024
  Epoch 38/60
Model trained in 1.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.777
  Epoch 39/60
Model trained in 1.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.373
  Epoch 40/60
Model trained in 1.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.674
  Epoch 41/60
Model trained in 1.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.403
  Epoch 42/60
Model trained in 1.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.439
  Epoch 43/60
Model trained in 1.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.241
  Epoch 44/60
Model trained in 1.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.249
  Early stopping triggered.

  best_val_SMAPE=71.353

Combination 40/144: {'encoder_hidden_size': 16, 'layers': 2, 'decoder_hidden_size': 32, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 10, 'batch_size': 64, 'sequence_length': 168, 'dropout': 0.2}
Time: 51.21 minutes - estimated total time: 184.37 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 32
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity']
  Epoch 1/60
Model trained in 2.08s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 179.124
  Epoch 2/60
Model trained in 1.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 169.449
  Epoch 3/60
Model trained in 1.95s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 161.236
  Epoch 4/60
Model trained in 1.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 154.092
  Epoch 5/60
Model trained in 1.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 147.720
  Epoch 6/60
Model trained in 1.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 141.862
  Epoch 7/60
Model trained in 1.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 136.455
  Epoch 8/60
Model trained in 1.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 131.324
  Epoch 9/60
Model trained in 1.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 126.402
  Epoch 10/60
Model trained in 1.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 121.663
  Epoch 11/60
Model trained in 1.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 117.368
  Epoch 12/60
Model trained in 1.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 113.208
  Epoch 13/60
Model trained in 1.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 109.555
  Epoch 14/60
Model trained in 1.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 106.405
  Epoch 15/60
Model trained in 1.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 103.079
  Epoch 16/60
Model trained in 1.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 99.747
  Epoch 17/60
Model trained in 1.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 96.755
  Epoch 18/60
Model trained in 1.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.845
  Epoch 19/60
Model trained in 1.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.249
  Epoch 20/60
Model trained in 1.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.749
  Epoch 21/60
Model trained in 1.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.954
  Epoch 22/60
Model trained in 1.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.314
  Epoch 23/60
Model trained in 1.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.083
  Epoch 24/60
Model trained in 1.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.487
  Epoch 25/60
Model trained in 1.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.479
  Epoch 26/60
Model trained in 1.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.404
  Epoch 27/60
Model trained in 1.95s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.817
  Epoch 28/60
Model trained in 1.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.758
  Epoch 29/60
Model trained in 1.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.296
  Epoch 30/60
Model trained in 1.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.415
  Epoch 31/60
Model trained in 1.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.262
  Epoch 32/60
Model trained in 1.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.061
  Epoch 33/60
Model trained in 1.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.286
  Epoch 34/60
Model trained in 1.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.099
  Epoch 35/60
Model trained in 1.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.459
  Epoch 36/60
Model trained in 1.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.120
  Epoch 37/60
Model trained in 1.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.386
  Epoch 38/60
Model trained in 1.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.700
  Epoch 39/60
Model trained in 1.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.800
  Epoch 40/60
Model trained in 1.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.804
  Epoch 41/60
Model trained in 1.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.149
  Epoch 42/60
Model trained in 1.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.992
  Epoch 43/60
Model trained in 1.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.481
  Epoch 44/60
Model trained in 1.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.546
  Epoch 45/60
Model trained in 1.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.623
  Epoch 46/60
Model trained in 1.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.913
  Epoch 47/60
Model trained in 1.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.332
  Epoch 48/60
Model trained in 1.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.686
  Epoch 49/60
Model trained in 1.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.568
  Epoch 50/60
Model trained in 1.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.475
  Epoch 51/60
Model trained in 1.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.557
  Epoch 52/60
Model trained in 1.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.798
  Epoch 53/60
Model trained in 1.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.071
  Epoch 54/60
Model trained in 1.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.413
  Epoch 55/60
Model trained in 1.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.026
  Epoch 56/60
Model trained in 1.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.085
  Epoch 57/60
Model trained in 1.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.261
  Epoch 58/60
Model trained in 1.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.655
  Epoch 59/60
Model trained in 1.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.021
  Epoch 60/60
Model trained in 1.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.689

  best_val_SMAPE=74.557

Combination 41/144: {'encoder_hidden_size': 16, 'layers': 2, 'decoder_hidden_size': 48, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 10, 'batch_size': 32, 'sequence_length': 24, 'dropout': 0.0}
Time: 53.53 minutes - estimated total time: 188.01 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 32
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity']
  Epoch 1/60
Model trained in 2.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 161.118
  Epoch 2/60
Model trained in 2.97s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 141.897
  Epoch 3/60
Model trained in 2.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 126.617
  Epoch 4/60
Model trained in 2.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 114.948
  Epoch 5/60
Model trained in 2.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 104.622
  Epoch 6/60
Model trained in 2.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 97.446
  Epoch 7/60
Model trained in 2.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.067
  Epoch 8/60
Model trained in 2.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.858
  Epoch 9/60
Model trained in 2.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.379
  Epoch 10/60
Model trained in 2.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.164
  Epoch 11/60
Model trained in 2.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.919
  Epoch 12/60
Model trained in 2.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.759
  Epoch 13/60
Model trained in 2.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.001
  Epoch 14/60
Model trained in 2.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.963
  Epoch 15/60
Model trained in 2.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.618
  Epoch 16/60
Model trained in 2.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.823
  Epoch 17/60
Model trained in 2.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.428
  Epoch 18/60
Model trained in 2.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.422
  Epoch 19/60
Model trained in 2.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.949
  Epoch 20/60
Model trained in 2.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.617
  Epoch 21/60
Model trained in 2.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.619
  Epoch 22/60
Model trained in 2.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.066
  Epoch 23/60
Model trained in 2.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 72.832
  Epoch 24/60
Model trained in 2.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.238
  Epoch 25/60
Model trained in 2.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.092
  Epoch 26/60
Model trained in 2.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.064
  Epoch 27/60
Model trained in 2.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.670
  Epoch 28/60
Model trained in 2.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.217
  Epoch 29/60
Model trained in 2.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.820
  Epoch 30/60
Model trained in 2.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.930
  Epoch 31/60
Model trained in 2.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.336
  Epoch 32/60
Model trained in 2.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.303
  Epoch 33/60
Model trained in 2.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.451
  Early stopping triggered.

  best_val_SMAPE=72.832

Combination 42/144: {'encoder_hidden_size': 16, 'layers': 2, 'decoder_hidden_size': 48, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 10, 'batch_size': 32, 'sequence_length': 24, 'dropout': 0.2}
Time: 55.39 minutes - estimated total time: 189.89 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 32
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity']
  Epoch 1/60
Model trained in 2.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 161.108
  Epoch 2/60
Model trained in 2.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 141.890
  Epoch 3/60
Model trained in 3.06s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 126.611
  Epoch 4/60
Model trained in 2.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 116.194
  Epoch 5/60
Model trained in 2.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 106.995
  Epoch 6/60
Model trained in 2.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 98.118
  Epoch 7/60
Model trained in 2.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 94.478
  Epoch 8/60
Model trained in 2.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.119
  Epoch 9/60
Model trained in 2.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.057
  Epoch 10/60
Model trained in 2.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.777
  Epoch 11/60
Model trained in 2.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.730
  Epoch 12/60
Model trained in 2.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.527
  Epoch 13/60
Model trained in 2.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.038
  Epoch 14/60
Model trained in 2.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.648
  Epoch 15/60
Model trained in 2.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.657
  Epoch 16/60
Model trained in 3.03s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.700
  Epoch 17/60
Model trained in 2.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.830
  Epoch 18/60
Model trained in 2.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.552
  Epoch 19/60
Model trained in 2.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.855
  Epoch 20/60
Model trained in 2.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.028
  Epoch 21/60
Model trained in 2.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.377
  Epoch 22/60
Model trained in 2.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.159
  Early stopping triggered.

  best_val_SMAPE=75.527

Combination 43/144: {'encoder_hidden_size': 16, 'layers': 2, 'decoder_hidden_size': 48, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 10, 'batch_size': 32, 'sequence_length': 168, 'dropout': 0.0}
Time: 56.65 minutes - estimated total time: 189.71 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 32
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity']
  Epoch 1/60
Model trained in 2.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 161.252
  Epoch 2/60
Model trained in 2.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 142.122
  Epoch 3/60
Model trained in 2.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 127.655
  Epoch 4/60
Model trained in 2.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 116.413
  Epoch 5/60
Model trained in 2.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 106.011
  Epoch 6/60
Model trained in 2.99s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 97.001
  Epoch 7/60
Model trained in 2.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.733
  Epoch 8/60
Model trained in 2.98s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.819
  Epoch 9/60
Model trained in 2.95s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.344
  Epoch 10/60
Model trained in 2.95s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.517
  Epoch 11/60
Model trained in 2.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.777
  Epoch 12/60
Model trained in 2.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.148
  Epoch 13/60
Model trained in 2.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.077
  Epoch 14/60
Model trained in 2.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.901
  Epoch 15/60
Model trained in 2.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.495
  Epoch 16/60
Model trained in 2.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.560
  Epoch 17/60
Model trained in 2.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.360
  Epoch 18/60
Model trained in 2.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.272
  Epoch 19/60
Model trained in 2.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 72.796
  Epoch 20/60
Model trained in 2.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 72.780
  Epoch 21/60
Model trained in 2.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.662
  Epoch 22/60
Model trained in 2.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 72.989
  Epoch 23/60
Model trained in 2.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.339
  Epoch 24/60
Model trained in 2.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 72.614
  Epoch 25/60
Model trained in 2.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 72.066
  Epoch 26/60
Model trained in 2.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 72.167
  Epoch 27/60
Model trained in 2.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 72.985
  Epoch 28/60
Model trained in 2.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.242
  Epoch 29/60
Model trained in 2.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.407
  Epoch 30/60
Model trained in 2.95s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.262
  Epoch 31/60
Model trained in 2.97s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.551
  Epoch 32/60
Model trained in 2.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.900
  Epoch 33/60
Model trained in 2.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.349
  Epoch 34/60
Model trained in 2.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.588
  Epoch 35/60
Model trained in 2.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.791
  Early stopping triggered.

  best_val_SMAPE=72.066

Combination 44/144: {'encoder_hidden_size': 16, 'layers': 2, 'decoder_hidden_size': 48, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 10, 'batch_size': 32, 'sequence_length': 168, 'dropout': 0.2}
Time: 58.65 minutes - estimated total time: 191.94 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 32
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity']
  Epoch 1/60
Model trained in 3.09s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 161.244
  Epoch 2/60
Model trained in 2.95s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 142.115
  Epoch 3/60
Model trained in 3.01s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 126.891
  Epoch 4/60
Model trained in 2.97s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 114.583
  Epoch 5/60
Model trained in 2.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 105.756
  Epoch 6/60
Model trained in 2.97s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 98.698
  Epoch 7/60
Model trained in 2.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.604
  Epoch 8/60
Model trained in 2.99s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.148
  Epoch 9/60
Model trained in 3.02s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.977
  Epoch 10/60
Model trained in 3.01s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.447
  Epoch 11/60
Model trained in 3.02s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.862
  Epoch 12/60
Model trained in 2.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.855
  Epoch 13/60
Model trained in 2.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.305
  Epoch 14/60
Model trained in 2.95s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.642
  Epoch 15/60
Model trained in 2.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.637
  Epoch 16/60
Model trained in 2.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.179
  Epoch 17/60
Model trained in 2.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.840
  Epoch 18/60
Model trained in 2.98s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.308
  Epoch 19/60
Model trained in 2.95s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.537
  Epoch 20/60
Model trained in 2.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.460
  Epoch 21/60
Model trained in 2.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.827
  Epoch 22/60
Model trained in 2.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.755
  Epoch 23/60
Model trained in 2.99s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.299
  Epoch 24/60
Model trained in 2.97s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.965
  Epoch 25/60
Model trained in 2.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.813
  Epoch 26/60
Model trained in 2.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.229
  Epoch 27/60
Model trained in 2.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.417
  Epoch 28/60
Model trained in 3.16s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.360
  Epoch 29/60
Model trained in 3.04s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 72.782
  Epoch 30/60
Model trained in 2.95s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 72.431
  Epoch 31/60
Model trained in 3.00s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 71.800
  Epoch 32/60
Model trained in 3.01s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 70.900
  Epoch 33/60
Model trained in 2.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 71.196
  Epoch 34/60
Model trained in 2.97s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 70.888
  Epoch 35/60
Model trained in 2.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 71.555
  Epoch 36/60
Model trained in 2.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.029
  Epoch 37/60
Model trained in 2.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.464
  Epoch 38/60
Model trained in 2.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.279
  Epoch 39/60
Model trained in 2.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.615
  Epoch 40/60
Model trained in 2.97s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.404
  Epoch 41/60
Model trained in 2.95s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.442
  Epoch 42/60
Model trained in 2.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.128
  Epoch 43/60
Model trained in 2.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.085
  Epoch 44/60
Model trained in 2.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.116
  Early stopping triggered.

  best_val_SMAPE=70.888

Combination 45/144: {'encoder_hidden_size': 16, 'layers': 2, 'decoder_hidden_size': 48, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 10, 'batch_size': 64, 'sequence_length': 24, 'dropout': 0.0}
Time: 61.18 minutes - estimated total time: 195.79 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 32
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity']
  Epoch 1/60
Model trained in 1.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 173.827
  Epoch 2/60
Model trained in 1.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 161.061
  Epoch 3/60
Model trained in 1.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 150.704
  Epoch 4/60
Model trained in 1.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 141.787
  Epoch 5/60
Model trained in 1.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 133.847
  Epoch 6/60
Model trained in 1.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 126.448
  Epoch 7/60
Model trained in 1.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 119.574
  Epoch 8/60
Model trained in 1.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 115.272
  Epoch 9/60
Model trained in 1.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 112.194
  Epoch 10/60
Model trained in 1.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 111.883
  Epoch 11/60
Model trained in 1.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 108.619
  Epoch 12/60
Model trained in 1.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 106.157
  Epoch 13/60
Model trained in 1.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 102.074
  Epoch 14/60
Model trained in 1.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 99.337
  Epoch 15/60
Model trained in 1.67s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 98.732
  Epoch 16/60
Model trained in 1.67s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 100.609
  Epoch 17/60
Model trained in 1.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 101.234
  Epoch 18/60
Model trained in 1.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 99.125
  Epoch 19/60
Model trained in 1.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.094
  Epoch 20/60
Model trained in 1.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.874
  Epoch 21/60
Model trained in 1.68s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.790
  Epoch 22/60
Model trained in 1.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.526
  Epoch 23/60
Model trained in 1.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.636
  Epoch 24/60
Model trained in 1.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.894
  Epoch 25/60
Model trained in 1.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.713
  Epoch 26/60
Model trained in 1.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.107
  Epoch 27/60
Model trained in 1.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.353
  Epoch 28/60
Model trained in 1.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.177
  Epoch 29/60
Model trained in 1.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.347
  Epoch 30/60
Model trained in 1.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.810
  Epoch 31/60
Model trained in 1.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.279
  Epoch 32/60
Model trained in 1.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.505
  Epoch 33/60
Model trained in 1.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.147
  Epoch 34/60
Model trained in 1.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 97.177
  Epoch 35/60
Model trained in 1.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 95.673
  Epoch 36/60
Model trained in 1.68s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 95.815
  Epoch 37/60
Model trained in 1.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 95.426
  Epoch 38/60
Model trained in 1.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 97.739
  Epoch 39/60
Model trained in 1.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.498
  Early stopping triggered.

  best_val_SMAPE=86.347

Combination 46/144: {'encoder_hidden_size': 16, 'layers': 2, 'decoder_hidden_size': 48, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 10, 'batch_size': 64, 'sequence_length': 24, 'dropout': 0.2}
Time: 62.62 minutes - estimated total time: 196.02 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 32
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity']
  Epoch 1/60
Model trained in 1.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 173.816
  Epoch 2/60
Model trained in 1.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 161.050
  Epoch 3/60
Model trained in 1.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 150.694
  Epoch 4/60
Model trained in 1.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 141.778
  Epoch 5/60
Model trained in 1.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 133.839
  Epoch 6/60
Model trained in 1.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 126.461
  Epoch 7/60
Model trained in 1.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 119.950
  Epoch 8/60
Model trained in 1.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 114.914
  Epoch 9/60
Model trained in 1.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 109.758
  Epoch 10/60
Model trained in 1.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 105.087
  Epoch 11/60
Model trained in 1.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 100.512
  Epoch 12/60
Model trained in 1.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 95.323
  Epoch 13/60
Model trained in 1.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.217
  Epoch 14/60
Model trained in 1.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.659
  Epoch 15/60
Model trained in 1.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.598
  Epoch 16/60
Model trained in 1.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.488
  Epoch 17/60
Model trained in 1.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.082
  Epoch 18/60
Model trained in 1.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.557
  Epoch 19/60
Model trained in 1.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.493
  Epoch 20/60
Model trained in 1.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.856
  Epoch 21/60
Model trained in 1.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.998
  Epoch 22/60
Model trained in 1.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.427
  Epoch 23/60
Model trained in 1.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.153
  Epoch 24/60
Model trained in 1.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.209
  Epoch 25/60
Model trained in 1.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.400
  Epoch 26/60
Model trained in 1.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.710
  Epoch 27/60
Model trained in 1.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.691
  Epoch 28/60
Model trained in 1.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.157
  Epoch 29/60
Model trained in 1.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.005
  Epoch 30/60
Model trained in 1.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.380
  Epoch 31/60
Model trained in 1.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.407
  Epoch 32/60
Model trained in 1.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.278
  Epoch 33/60
Model trained in 1.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.524
  Epoch 34/60
Model trained in 1.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.830
  Epoch 35/60
Model trained in 1.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.524
  Epoch 36/60
Model trained in 1.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.989
  Epoch 37/60
Model trained in 1.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.644
  Epoch 38/60
Model trained in 1.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.885
  Epoch 39/60
Model trained in 1.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.605
  Epoch 40/60
Model trained in 1.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.810
  Epoch 41/60
Model trained in 1.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.764
  Epoch 42/60
Model trained in 1.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.616
  Early stopping triggered.

  best_val_SMAPE=73.278

Combination 47/144: {'encoder_hidden_size': 16, 'layers': 2, 'decoder_hidden_size': 48, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 10, 'batch_size': 64, 'sequence_length': 168, 'dropout': 0.0}
Time: 64.18 minutes - estimated total time: 196.64 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 32
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity']
  Epoch 1/60
Model trained in 1.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 173.852
  Epoch 2/60
Model trained in 1.95s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 161.162
  Epoch 3/60
Model trained in 1.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 150.840
  Epoch 4/60
Model trained in 1.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 141.954
  Epoch 5/60
Model trained in 1.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 134.042
  Epoch 6/60
Model trained in 1.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 126.682
  Epoch 7/60
Model trained in 1.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 120.018
  Epoch 8/60
Model trained in 1.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 115.658
  Epoch 9/60
Model trained in 1.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 109.954
  Epoch 10/60
Model trained in 1.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 105.398
  Epoch 11/60
Model trained in 1.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 100.757
  Epoch 12/60
Model trained in 1.95s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 96.387
  Epoch 13/60
Model trained in 1.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.995
  Epoch 14/60
Model trained in 1.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.783
  Epoch 15/60
Model trained in 1.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.831
  Epoch 16/60
Model trained in 1.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.248
  Epoch 17/60
Model trained in 1.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.385
  Epoch 18/60
Model trained in 1.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.160
  Epoch 19/60
Model trained in 1.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.645
  Epoch 20/60
Model trained in 1.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.434
  Epoch 21/60
Model trained in 1.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.902
  Epoch 22/60
Model trained in 1.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.231
  Epoch 23/60
Model trained in 1.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.018
  Epoch 24/60
Model trained in 1.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.565
  Epoch 25/60
Model trained in 1.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.923
  Epoch 26/60
Model trained in 1.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.928
  Epoch 27/60
Model trained in 1.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.115
  Epoch 28/60
Model trained in 1.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.203
  Epoch 29/60
Model trained in 1.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.449
  Epoch 30/60
Model trained in 1.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.061
  Epoch 31/60
Model trained in 1.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.903
  Early stopping triggered.

  best_val_SMAPE=75.902

Combination 48/144: {'encoder_hidden_size': 16, 'layers': 2, 'decoder_hidden_size': 48, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 10, 'batch_size': 64, 'sequence_length': 168, 'dropout': 0.2}
Time: 65.40 minutes - estimated total time: 196.21 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 32
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity']
  Epoch 1/60
Model trained in 1.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 173.844
  Epoch 2/60
Model trained in 1.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 161.155
  Epoch 3/60
Model trained in 1.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 150.833
  Epoch 4/60
Model trained in 1.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 141.948
  Epoch 5/60
Model trained in 1.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 134.039
  Epoch 6/60
Model trained in 1.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 126.665
  Epoch 7/60
Model trained in 1.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 120.228
  Epoch 8/60
Model trained in 1.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 115.544
  Epoch 9/60
Model trained in 1.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 115.146
  Epoch 10/60
Model trained in 1.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 110.111
  Epoch 11/60
Model trained in 1.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 108.152
  Epoch 12/60
Model trained in 1.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 110.517
  Epoch 13/60
Model trained in 1.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 108.406
  Epoch 14/60
Model trained in 1.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 103.692
  Epoch 15/60
Model trained in 1.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 100.145
  Epoch 16/60
Model trained in 1.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 97.397
  Epoch 17/60
Model trained in 1.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 99.259
  Epoch 18/60
Model trained in 1.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 99.087
  Epoch 19/60
Model trained in 1.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 96.489
  Epoch 20/60
Model trained in 1.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.648
  Epoch 21/60
Model trained in 1.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.468
  Epoch 22/60
Model trained in 2.06s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.061
  Epoch 23/60
Model trained in 1.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.075
  Epoch 24/60
Model trained in 1.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.546
  Epoch 25/60
Model trained in 1.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.396
  Epoch 26/60
Model trained in 1.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.769
  Epoch 27/60
Model trained in 1.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.621
  Epoch 28/60
Model trained in 1.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.996
  Epoch 29/60
Model trained in 1.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.349
  Epoch 30/60
Model trained in 1.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.223
  Epoch 31/60
Model trained in 1.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.704
  Epoch 32/60
Model trained in 1.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.412
  Epoch 33/60
Model trained in 1.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.360
  Epoch 34/60
Model trained in 1.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.634
  Epoch 35/60
Model trained in 1.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.207
  Epoch 36/60
Model trained in 1.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.127
  Epoch 37/60
Model trained in 1.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.287
  Epoch 38/60
Model trained in 1.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.172
  Epoch 39/60
Model trained in 1.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.039
  Epoch 40/60
Model trained in 1.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.427
  Epoch 41/60
Model trained in 1.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.304
  Epoch 42/60
Model trained in 1.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.735
  Epoch 43/60
Model trained in 1.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.145
  Epoch 44/60
Model trained in 1.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.022
  Epoch 45/60
Model trained in 1.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.555
  Epoch 46/60
Model trained in 1.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.496
  Epoch 47/60
Model trained in 1.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.039
  Epoch 48/60
Model trained in 1.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.544
  Epoch 49/60
Model trained in 1.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.795
  Epoch 50/60
Model trained in 1.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.440
  Epoch 51/60
Model trained in 1.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.090
  Epoch 52/60
Model trained in 1.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.837
  Epoch 53/60
Model trained in 1.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.119
  Early stopping triggered.

  best_val_SMAPE=77.145

Combination 49/144: {'encoder_hidden_size': 32, 'layers': 1, 'decoder_hidden_size': 16, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 10, 'batch_size': 32, 'sequence_length': 24, 'dropout': 0.0}
Time: 67.47 minutes - estimated total time: 198.29 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 32
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity']
  Epoch 1/60
Model trained in 2.44s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 179.344
  Epoch 2/60
Model trained in 2.44s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 169.440
  Epoch 3/60
Model trained in 2.46s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 161.169
  Epoch 4/60
Model trained in 2.49s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 153.701
  Epoch 5/60
Model trained in 2.60s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 147.194
  Epoch 6/60
Model trained in 2.47s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 141.265
  Epoch 7/60
Model trained in 2.43s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 135.837
  Epoch 8/60
Model trained in 2.44s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 130.827
  Epoch 9/60
Model trained in 2.41s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 126.157
  Epoch 10/60
Model trained in 2.41s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 121.802
  Epoch 11/60
Model trained in 2.46s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 117.495
  Epoch 12/60
Model trained in 2.42s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 113.409
  Epoch 13/60
Model trained in 2.46s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 109.599
  Epoch 14/60
Model trained in 2.46s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 107.027
  Epoch 15/60
Model trained in 2.45s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 104.514
  Epoch 16/60
Model trained in 2.43s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 101.700
  Epoch 17/60
Model trained in 2.42s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 100.820
  Epoch 18/60
Model trained in 2.43s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 104.193
  Epoch 19/60
Model trained in 2.44s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 103.072
  Epoch 20/60
Model trained in 2.41s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 102.570
  Epoch 21/60
Model trained in 2.44s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 100.055
  Epoch 22/60
Model trained in 2.45s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 94.068
  Epoch 23/60
Model trained in 2.41s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.256
  Epoch 24/60
Model trained in 2.47s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.325
  Epoch 25/60
Model trained in 2.50s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.549
  Epoch 26/60
Model trained in 2.46s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.440
  Epoch 27/60
Model trained in 2.43s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.940
  Epoch 28/60
Model trained in 2.43s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.325
  Epoch 29/60
Model trained in 2.42s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.365
  Epoch 30/60
Model trained in 2.41s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.613
  Epoch 31/60
Model trained in 2.42s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.020
  Epoch 32/60
Model trained in 2.44s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.223
  Epoch 33/60
Model trained in 2.46s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.797
  Epoch 34/60
Model trained in 2.42s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.727
  Epoch 35/60
Model trained in 2.43s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.886
  Epoch 36/60
Model trained in 2.45s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.594
  Epoch 37/60
Model trained in 2.50s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.186
  Epoch 38/60
Model trained in 2.46s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.061
  Epoch 39/60
Model trained in 2.46s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.388
  Epoch 40/60
Model trained in 2.42s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.252
  Epoch 41/60
Model trained in 2.45s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.869
  Early stopping triggered.

  best_val_SMAPE=73.020

Combination 51/144: {'encoder_hidden_size': 32, 'layers': 1, 'decoder_hidden_size': 16, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 10, 'batch_size': 32, 'sequence_length': 168, 'dropout': 0.0}
Time: 69.49 minutes - estimated total time: 196.20 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 32
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity']
  Epoch 1/60
Model trained in 2.56s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 179.446
  Epoch 2/60
Model trained in 2.54s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 169.919
  Epoch 3/60
Model trained in 2.56s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 161.193
  Epoch 4/60
Model trained in 2.53s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 153.967
  Epoch 5/60
Model trained in 2.56s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 147.486
  Epoch 6/60
Model trained in 2.55s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 141.551
  Epoch 7/60
Model trained in 2.51s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 136.122
  Epoch 8/60
Model trained in 2.49s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 130.970
  Epoch 9/60
Model trained in 2.52s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 126.420
  Epoch 10/60
Model trained in 2.52s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 122.071
  Epoch 11/60
Model trained in 2.49s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 118.055
  Epoch 12/60
Model trained in 2.51s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 114.236
  Epoch 13/60
Model trained in 2.51s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 110.381
  Epoch 14/60
Model trained in 2.51s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 106.848
  Epoch 15/60
Model trained in 2.50s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 103.279
  Epoch 16/60
Model trained in 2.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 100.983
  Epoch 17/60
Model trained in 2.52s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 98.260
  Epoch 18/60
Model trained in 2.52s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 95.581
  Epoch 19/60
Model trained in 2.48s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.719
  Epoch 20/60
Model trained in 2.49s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.797
  Epoch 21/60
Model trained in 2.48s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.063
  Epoch 22/60
Model trained in 2.48s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.729
  Epoch 23/60
Model trained in 2.52s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.368
  Epoch 24/60
Model trained in 2.50s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.396
  Epoch 25/60
Model trained in 2.48s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.332
  Epoch 26/60
Model trained in 2.51s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.830
  Epoch 27/60
Model trained in 2.51s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.111
  Epoch 28/60
Model trained in 2.47s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.118
  Epoch 29/60
Model trained in 2.48s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.011
  Epoch 30/60
Model trained in 2.50s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.635
  Epoch 31/60
Model trained in 2.51s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.754
  Epoch 32/60
Model trained in 2.54s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.818
  Epoch 33/60
Model trained in 2.51s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.864
  Epoch 34/60
Model trained in 2.52s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.837
  Epoch 35/60
Model trained in 2.52s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.031
  Epoch 36/60
Model trained in 2.63s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.092
  Epoch 37/60
Model trained in 2.55s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.892
  Epoch 38/60
Model trained in 2.48s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.461
  Epoch 39/60
Model trained in 2.49s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.457
  Epoch 40/60
Model trained in 2.53s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.852
  Epoch 41/60
Model trained in 2.49s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.135
  Early stopping triggered.

  best_val_SMAPE=74.754

Combination 53/144: {'encoder_hidden_size': 32, 'layers': 1, 'decoder_hidden_size': 16, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 10, 'batch_size': 64, 'sequence_length': 24, 'dropout': 0.0}
Time: 71.54 minutes - estimated total time: 194.37 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 32
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity']
  Epoch 1/60
Model trained in 1.57s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 186.246
  Epoch 2/60
Model trained in 1.54s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 179.285
  Epoch 3/60
Model trained in 1.54s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 174.016
  Epoch 4/60
Model trained in 1.53s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 169.787
  Epoch 5/60
Model trained in 1.57s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 165.198
  Epoch 6/60
Model trained in 1.53s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 161.012
  Epoch 7/60
Model trained in 1.54s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 157.143
  Epoch 8/60
Model trained in 1.57s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 153.578
  Epoch 9/60
Model trained in 1.51s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 150.235
  Epoch 10/60
Model trained in 1.54s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 147.001
  Epoch 11/60
Model trained in 1.50s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 144.003
  Epoch 12/60
Model trained in 1.52s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 141.071
  Epoch 13/60
Model trained in 1.53s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 138.300
  Epoch 14/60
Model trained in 1.52s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 135.656
  Epoch 15/60
Model trained in 1.49s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 133.189
  Epoch 16/60
Model trained in 1.51s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 130.706
  Epoch 17/60
Model trained in 1.51s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 128.344
  Epoch 18/60
Model trained in 1.49s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 125.982
  Epoch 19/60
Model trained in 1.50s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 123.791
  Epoch 20/60
Model trained in 1.52s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 121.814
  Epoch 21/60
Model trained in 1.51s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 119.812
  Epoch 22/60
Model trained in 1.50s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 117.802
  Epoch 23/60
Model trained in 1.51s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 115.766
  Epoch 24/60
Model trained in 1.53s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 113.676
  Epoch 25/60
Model trained in 1.49s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 111.686
  Epoch 26/60
Model trained in 1.50s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 109.565
  Epoch 27/60
Model trained in 1.50s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 108.583
  Epoch 28/60
Model trained in 1.51s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 107.046
  Epoch 29/60
Model trained in 1.50s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 105.497
  Epoch 30/60
Model trained in 1.50s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 103.873
  Epoch 31/60
Model trained in 1.52s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 102.296
  Epoch 32/60
Model trained in 1.48s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 100.695
  Epoch 33/60
Model trained in 1.50s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 99.252
  Epoch 34/60
Model trained in 1.49s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 97.772
  Epoch 35/60
Model trained in 1.52s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 96.258
  Epoch 36/60
Model trained in 1.48s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 94.560
  Epoch 37/60
Model trained in 1.51s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.657
  Epoch 38/60
Model trained in 1.49s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.524
  Epoch 39/60
Model trained in 1.49s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.214
  Epoch 40/60
Model trained in 1.51s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.939
  Epoch 41/60
Model trained in 1.53s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.294
  Epoch 42/60
Model trained in 1.53s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.406
  Epoch 43/60
Model trained in 1.50s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.190
  Epoch 44/60
Model trained in 1.52s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.126
  Epoch 45/60
Model trained in 1.53s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.591
  Epoch 46/60
Model trained in 1.52s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.322
  Epoch 47/60
Model trained in 1.52s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.944
  Epoch 48/60
Model trained in 1.51s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.555
  Epoch 49/60
Model trained in 1.50s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.974
  Epoch 50/60
Model trained in 1.51s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.029
  Epoch 51/60
Model trained in 1.51s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.932
  Epoch 52/60
Model trained in 1.51s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.524
  Epoch 53/60
Model trained in 1.53s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.054
  Epoch 54/60
Model trained in 1.51s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.956
  Epoch 55/60
Model trained in 1.52s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.665
  Epoch 56/60
Model trained in 1.51s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.514
  Epoch 57/60
Model trained in 1.51s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.026
  Epoch 58/60
Model trained in 1.48s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.636
  Epoch 59/60
Model trained in 1.54s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.995
  Epoch 60/60
Model trained in 1.53s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.621

  best_val_SMAPE=79.956

Combination 55/144: {'encoder_hidden_size': 32, 'layers': 1, 'decoder_hidden_size': 16, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 10, 'batch_size': 64, 'sequence_length': 168, 'dropout': 0.0}
Time: 73.52 minutes - estimated total time: 192.49 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 32
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity']
  Epoch 1/60
Model trained in 1.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 186.283
  Epoch 2/60
Model trained in 1.65s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 179.315
  Epoch 3/60
Model trained in 1.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 174.034
  Epoch 4/60
Model trained in 1.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 170.012
  Epoch 5/60
Model trained in 1.67s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 165.192
  Epoch 6/60
Model trained in 1.68s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 161.005
  Epoch 7/60
Model trained in 1.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 157.254
  Epoch 8/60
Model trained in 1.65s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 153.711
  Epoch 9/60
Model trained in 1.63s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 150.404
  Epoch 10/60
Model trained in 1.65s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 147.223
  Epoch 11/60
Model trained in 1.63s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 144.218
  Epoch 12/60
Model trained in 1.65s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 141.329
  Epoch 13/60
Model trained in 1.59s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 138.550
  Epoch 14/60
Model trained in 1.65s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 135.802
  Epoch 15/60
Model trained in 1.58s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 133.187
  Epoch 16/60
Model trained in 1.56s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 130.697
  Epoch 17/60
Model trained in 1.60s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 128.358
  Epoch 18/60
Model trained in 1.60s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 126.122
  Epoch 19/60
Model trained in 1.54s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 124.016
  Epoch 20/60
Model trained in 1.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 121.867
  Epoch 21/60
Model trained in 1.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 119.861
  Epoch 22/60
Model trained in 1.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 117.925
  Epoch 23/60
Model trained in 1.59s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 115.822
  Epoch 24/60
Model trained in 1.59s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 113.983
  Epoch 25/60
Model trained in 1.60s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 112.045
  Epoch 26/60
Model trained in 1.63s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 110.186
  Epoch 27/60
Model trained in 1.65s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 108.701
  Epoch 28/60
Model trained in 1.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 106.941
  Epoch 29/60
Model trained in 1.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 105.572
  Epoch 30/60
Model trained in 1.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 104.428
  Epoch 31/60
Model trained in 1.63s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 103.280
  Epoch 32/60
Model trained in 1.63s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 102.034
  Epoch 33/60
Model trained in 1.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 100.552
  Epoch 34/60
Model trained in 1.58s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 99.082
  Epoch 35/60
Model trained in 1.60s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 97.114
  Epoch 36/60
Model trained in 1.62s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 95.190
  Epoch 37/60
Model trained in 1.61s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.505
  Epoch 38/60
Model trained in 1.62s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.269
  Epoch 39/60
Model trained in 1.61s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.191
  Epoch 40/60
Model trained in 1.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.017
  Epoch 41/60
Model trained in 1.67s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.437
  Epoch 42/60
Model trained in 1.61s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.564
  Epoch 43/60
Model trained in 1.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.876
  Epoch 44/60
Model trained in 1.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.873
  Epoch 45/60
Model trained in 1.61s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.849
  Epoch 46/60
Model trained in 1.61s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.630
  Epoch 47/60
Model trained in 1.59s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.088
  Epoch 48/60
Model trained in 1.63s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.316
  Epoch 49/60
Model trained in 1.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.214
  Epoch 50/60
Model trained in 1.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.384
  Epoch 51/60
Model trained in 1.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.325
  Epoch 52/60
Model trained in 1.65s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.148
  Epoch 53/60
Model trained in 1.63s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.377
  Epoch 54/60
Model trained in 1.63s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.331
  Epoch 55/60
Model trained in 1.63s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.121
  Epoch 56/60
Model trained in 1.61s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.702
  Epoch 57/60
Model trained in 1.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.434
  Epoch 58/60
Model trained in 1.63s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.878
  Epoch 59/60
Model trained in 1.57s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.445
  Epoch 60/60
Model trained in 1.59s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.786

  best_val_SMAPE=74.786

Combination 57/144: {'encoder_hidden_size': 32, 'layers': 1, 'decoder_hidden_size': 32, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 10, 'batch_size': 32, 'sequence_length': 24, 'dropout': 0.0}
Time: 75.63 minutes - estimated total time: 191.06 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 32
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity']
  Epoch 1/60
Model trained in 2.17s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 169.054
  Epoch 2/60
Model trained in 2.16s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 153.778
  Epoch 3/60
Model trained in 2.16s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 142.270
  Epoch 4/60
Model trained in 2.15s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 132.876
  Epoch 5/60
Model trained in 2.20s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 123.698
  Epoch 6/60
Model trained in 2.18s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 115.569
  Epoch 7/60
Model trained in 2.17s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 108.599
  Epoch 8/60
Model trained in 2.15s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 101.949
  Epoch 9/60
Model trained in 2.14s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 95.914
  Epoch 10/60
Model trained in 2.15s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.338
  Epoch 11/60
Model trained in 2.17s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.882
  Epoch 12/60
Model trained in 2.14s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.720
  Epoch 13/60
Model trained in 2.16s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.309
  Epoch 14/60
Model trained in 2.15s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.269
  Epoch 15/60
Model trained in 2.22s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.738
  Epoch 16/60
Model trained in 2.17s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.520
  Epoch 17/60
Model trained in 2.17s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.160
  Epoch 18/60
Model trained in 2.16s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.872
  Epoch 19/60
Model trained in 2.18s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.310
  Epoch 20/60
Model trained in 2.18s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.704
  Epoch 21/60
Model trained in 2.17s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.621
  Epoch 22/60
Model trained in 2.13s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.956
  Epoch 23/60
Model trained in 2.14s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.792
  Epoch 24/60
Model trained in 2.14s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.067
  Epoch 25/60
Model trained in 2.12s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.789
  Epoch 26/60
Model trained in 2.14s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.638
  Epoch 27/60
Model trained in 2.14s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.505
  Epoch 28/60
Model trained in 2.14s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.552
  Epoch 29/60
Model trained in 2.15s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.838
  Epoch 30/60
Model trained in 2.18s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.262
  Epoch 31/60
Model trained in 2.32s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.181
  Epoch 32/60
Model trained in 2.18s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.190
  Epoch 33/60
Model trained in 2.17s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.865
  Epoch 34/60
Model trained in 2.13s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 94.382
  Early stopping triggered.

  best_val_SMAPE=74.067

Combination 59/144: {'encoder_hidden_size': 32, 'layers': 1, 'decoder_hidden_size': 32, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 10, 'batch_size': 32, 'sequence_length': 168, 'dropout': 0.0}
Time: 77.14 minutes - estimated total time: 188.27 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 32
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity']
  Epoch 1/60
Model trained in 2.27s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 169.338
  Epoch 2/60
Model trained in 2.25s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 154.130
  Epoch 3/60
Model trained in 2.32s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 142.333
  Epoch 4/60
Model trained in 2.25s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 132.955
  Epoch 5/60
Model trained in 2.27s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 123.906
  Epoch 6/60
Model trained in 2.23s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 116.417
  Epoch 7/60
Model trained in 2.26s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 109.079
  Epoch 8/60
Model trained in 2.21s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 103.082
  Epoch 9/60
Model trained in 2.23s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 97.045
  Epoch 10/60
Model trained in 2.27s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.874
  Epoch 11/60
Model trained in 2.25s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.052
  Epoch 12/60
Model trained in 2.21s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.097
  Epoch 13/60
Model trained in 2.19s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.871
  Epoch 14/60
Model trained in 2.18s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.331
  Epoch 15/60
Model trained in 2.18s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.039
  Epoch 16/60
Model trained in 2.21s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.534
  Epoch 17/60
Model trained in 2.19s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.149
  Epoch 18/60
Model trained in 2.22s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.949
  Epoch 19/60
Model trained in 2.17s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.859
  Epoch 20/60
Model trained in 2.17s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.522
  Epoch 21/60
Model trained in 2.21s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.295
  Epoch 22/60
Model trained in 2.24s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.561
  Epoch 23/60
Model trained in 2.22s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.239
  Epoch 24/60
Model trained in 2.18s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.503
  Epoch 25/60
Model trained in 2.21s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.000
  Epoch 26/60
Model trained in 2.21s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.406
  Epoch 27/60
Model trained in 2.21s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.261
  Epoch 28/60
Model trained in 2.23s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.844
  Epoch 29/60
Model trained in 2.20s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.479
  Epoch 30/60
Model trained in 2.21s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.155
  Epoch 31/60
Model trained in 2.23s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 95.511
  Epoch 32/60
Model trained in 2.20s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 96.147
  Epoch 33/60
Model trained in 2.22s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 96.968
  Epoch 34/60
Model trained in 2.33s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 98.747
  Epoch 35/60
Model trained in 2.25s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 100.279
  Early stopping triggered.

  best_val_SMAPE=73.000

Combination 61/144: {'encoder_hidden_size': 32, 'layers': 1, 'decoder_hidden_size': 32, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 10, 'batch_size': 64, 'sequence_length': 24, 'dropout': 0.0}
Time: 78.73 minutes - estimated total time: 185.85 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 32
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity']
  Epoch 1/60
Model trained in 1.42s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 178.949
  Epoch 2/60
Model trained in 1.42s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 169.083
  Epoch 3/60
Model trained in 1.40s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 160.879
  Epoch 4/60
Model trained in 1.37s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 153.894
  Epoch 5/60
Model trained in 1.43s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 147.783
  Epoch 6/60
Model trained in 1.43s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 142.344
  Epoch 7/60
Model trained in 1.42s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 137.282
  Epoch 8/60
Model trained in 1.42s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 132.328
  Epoch 9/60
Model trained in 1.44s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 127.930
  Epoch 10/60
Model trained in 1.41s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 123.720
  Epoch 11/60
Model trained in 1.40s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 119.375
  Epoch 12/60
Model trained in 1.36s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 115.728
  Epoch 13/60
Model trained in 1.41s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 112.158
  Epoch 14/60
Model trained in 1.41s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 108.919
  Epoch 15/60
Model trained in 1.42s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 105.777
  Epoch 16/60
Model trained in 1.40s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 101.592
  Epoch 17/60
Model trained in 1.39s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 100.148
  Epoch 18/60
Model trained in 1.39s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 98.742
  Epoch 19/60
Model trained in 1.40s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 97.498
  Epoch 20/60
Model trained in 1.48s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 95.923
  Epoch 21/60
Model trained in 1.43s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 94.602
  Epoch 22/60
Model trained in 1.40s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.206
  Epoch 23/60
Model trained in 1.39s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.320
  Epoch 24/60
Model trained in 1.40s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.950
  Epoch 25/60
Model trained in 1.48s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.638
  Epoch 26/60
Model trained in 1.41s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.520
  Epoch 27/60
Model trained in 1.39s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.481
  Epoch 28/60
Model trained in 1.39s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.622
  Epoch 29/60
Model trained in 1.40s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.671
  Epoch 30/60
Model trained in 1.44s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.129
  Epoch 31/60
Model trained in 1.40s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.303
  Epoch 32/60
Model trained in 1.37s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.941
  Epoch 33/60
Model trained in 1.39s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.698
  Epoch 34/60
Model trained in 1.39s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.223
  Epoch 35/60
Model trained in 1.39s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.632
  Epoch 36/60
Model trained in 1.40s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.337
  Epoch 37/60
Model trained in 1.38s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.793
  Epoch 38/60
Model trained in 1.36s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.018
  Epoch 39/60
Model trained in 1.39s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.799
  Epoch 40/60
Model trained in 1.40s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.488
  Epoch 41/60
Model trained in 1.37s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.386
  Epoch 42/60
Model trained in 1.38s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.250
  Epoch 43/60
Model trained in 1.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.468
  Epoch 44/60
Model trained in 1.41s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.284
  Epoch 45/60
Model trained in 1.41s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.854
  Epoch 46/60
Model trained in 1.42s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.184
  Epoch 47/60
Model trained in 1.43s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.517
  Epoch 48/60
Model trained in 1.46s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.790
  Epoch 49/60
Model trained in 1.45s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 72.826
  Epoch 50/60
Model trained in 1.42s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 71.433
  Epoch 51/60
Model trained in 1.41s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 72.993
  Epoch 52/60
Model trained in 1.44s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 71.689
  Epoch 53/60
Model trained in 1.46s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 72.856
  Epoch 54/60
Model trained in 1.45s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.439
  Epoch 55/60
Model trained in 1.43s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.094
  Epoch 56/60
Model trained in 1.42s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.877
  Epoch 57/60
Model trained in 1.47s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.609
  Epoch 58/60
Model trained in 1.45s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.694
  Epoch 59/60
Model trained in 1.40s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.827
  Epoch 60/60
Model trained in 1.44s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.574
  Early stopping triggered.

  best_val_SMAPE=71.433

Combination 63/144: {'encoder_hidden_size': 32, 'layers': 1, 'decoder_hidden_size': 32, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 10, 'batch_size': 64, 'sequence_length': 168, 'dropout': 0.0}
Time: 80.62 minutes - estimated total time: 184.27 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 32
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity']
  Epoch 1/60
Model trained in 1.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 179.099
  Epoch 2/60
Model trained in 1.56s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 169.254
  Epoch 3/60
Model trained in 1.50s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 161.155
  Epoch 4/60
Model trained in 1.54s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 154.098
  Epoch 5/60
Model trained in 1.51s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 148.211
  Epoch 6/60
Model trained in 1.57s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 142.352
  Epoch 7/60
Model trained in 1.57s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 137.423
  Epoch 8/60
Model trained in 1.50s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 132.488
  Epoch 9/60
Model trained in 1.52s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 127.778
  Epoch 10/60
Model trained in 1.50s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 123.265
  Epoch 11/60
Model trained in 1.52s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 119.070
  Epoch 12/60
Model trained in 1.59s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 115.293
  Epoch 13/60
Model trained in 1.60s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 111.753
  Epoch 14/60
Model trained in 1.53s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 108.109
  Epoch 15/60
Model trained in 1.50s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 105.300
  Epoch 16/60
Model trained in 1.48s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 102.585
  Epoch 17/60
Model trained in 1.51s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 100.647
  Epoch 18/60
Model trained in 1.53s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 98.510
  Epoch 19/60
Model trained in 1.55s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 96.257
  Epoch 20/60
Model trained in 1.62s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 96.112
  Epoch 21/60
Model trained in 1.52s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 94.108
  Epoch 22/60
Model trained in 1.53s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.181
  Epoch 23/60
Model trained in 1.52s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.187
  Epoch 24/60
Model trained in 1.51s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.434
  Epoch 25/60
Model trained in 1.48s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.104
  Epoch 26/60
Model trained in 1.51s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.429
  Epoch 27/60
Model trained in 1.48s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.853
  Epoch 28/60
Model trained in 1.47s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.299
  Epoch 29/60
Model trained in 1.47s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.379
  Epoch 30/60
Model trained in 1.50s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.002
  Epoch 31/60
Model trained in 1.53s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.855
  Epoch 32/60
Model trained in 1.52s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.713
  Epoch 33/60
Model trained in 1.47s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.177
  Epoch 34/60
Model trained in 1.47s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.210
  Epoch 35/60
Model trained in 1.49s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.986
  Epoch 36/60
Model trained in 1.50s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.019
  Epoch 37/60
Model trained in 1.54s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.603
  Epoch 38/60
Model trained in 1.54s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.374
  Epoch 39/60
Model trained in 1.50s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.732
  Epoch 40/60
Model trained in 1.53s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.408
  Epoch 41/60
Model trained in 1.52s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.892
  Epoch 42/60
Model trained in 1.51s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.941
  Epoch 43/60
Model trained in 1.52s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.575
  Epoch 44/60
Model trained in 1.56s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.212
  Epoch 45/60
Model trained in 1.56s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.463
  Epoch 46/60
Model trained in 1.56s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.519
  Epoch 47/60
Model trained in 1.57s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.975
  Epoch 48/60
Model trained in 1.58s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.441
  Epoch 49/60
Model trained in 1.62s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.830
  Epoch 50/60
Model trained in 1.53s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 72.668
  Epoch 51/60
Model trained in 1.51s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 72.440
  Epoch 52/60
Model trained in 1.49s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 71.711
  Epoch 53/60
Model trained in 1.55s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 70.744
  Epoch 54/60
Model trained in 1.55s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 70.834
  Epoch 55/60
Model trained in 1.54s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 71.669
  Epoch 56/60
Model trained in 1.53s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 72.399
  Epoch 57/60
Model trained in 1.48s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.064
  Epoch 58/60
Model trained in 1.51s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 72.791
  Epoch 59/60
Model trained in 1.51s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.257
  Epoch 60/60
Model trained in 1.54s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.734

  best_val_SMAPE=70.744

Combination 65/144: {'encoder_hidden_size': 32, 'layers': 1, 'decoder_hidden_size': 48, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 10, 'batch_size': 32, 'sequence_length': 24, 'dropout': 0.0}
Time: 82.61 minutes - estimated total time: 183.02 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 32
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity']
  Epoch 1/60
Model trained in 2.53s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 160.010
  Epoch 2/60
Model trained in 2.52s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 141.696
  Epoch 3/60
Model trained in 2.52s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 127.720
  Epoch 4/60
Model trained in 2.50s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 115.397
  Epoch 5/60
Model trained in 2.50s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 105.145
  Epoch 6/60
Model trained in 2.43s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 97.208
  Epoch 7/60
Model trained in 2.37s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.165
  Epoch 8/60
Model trained in 2.42s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.402
  Epoch 9/60
Model trained in 2.45s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.602
  Epoch 10/60
Model trained in 2.44s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 71.380
  Epoch 11/60
Model trained in 2.49s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 67.499
  Epoch 12/60
Model trained in 2.48s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 67.340
  Epoch 13/60
Model trained in 2.49s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 64.966
  Epoch 14/60
Model trained in 2.46s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 66.331
  Epoch 15/60
Model trained in 2.45s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 68.508
  Epoch 16/60
Model trained in 2.42s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 72.571
  Epoch 17/60
Model trained in 2.39s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.233
  Epoch 18/60
Model trained in 2.40s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.521
  Epoch 19/60
Model trained in 2.45s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 68.973
  Epoch 20/60
Model trained in 2.48s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 69.781
  Epoch 21/60
Model trained in 2.40s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.002
  Epoch 22/60
Model trained in 2.53s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.817
  Epoch 23/60
Model trained in 2.47s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.655
  Early stopping triggered.

  best_val_SMAPE=64.966

Combination 67/144: {'encoder_hidden_size': 32, 'layers': 1, 'decoder_hidden_size': 48, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 10, 'batch_size': 32, 'sequence_length': 168, 'dropout': 0.0}
Time: 83.76 minutes - estimated total time: 180.03 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 32
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity']
  Epoch 1/60
Model trained in 2.61s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 160.402
  Epoch 2/60
Model trained in 2.58s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 142.155
  Epoch 3/60
Model trained in 2.61s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 127.699
  Epoch 4/60
Model trained in 2.53s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 115.727
  Epoch 5/60
Model trained in 2.58s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 106.597
  Epoch 6/60
Model trained in 2.61s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 97.289
  Epoch 7/60
Model trained in 2.56s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.345
  Epoch 8/60
Model trained in 2.54s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.721
  Epoch 9/60
Model trained in 2.50s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.914
  Epoch 10/60
Model trained in 2.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.476
  Epoch 11/60
Model trained in 2.65s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 72.378
  Epoch 12/60
Model trained in 2.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 70.458
  Epoch 13/60
Model trained in 2.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 68.575
  Epoch 14/60
Model trained in 2.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 66.141
  Epoch 15/60
Model trained in 2.61s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 65.247
  Epoch 16/60
Model trained in 2.52s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 65.131
  Epoch 17/60
Model trained in 2.49s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 66.829
  Epoch 18/60
Model trained in 2.48s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 69.297
  Epoch 19/60
Model trained in 2.53s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 70.777
  Epoch 20/60
Model trained in 2.54s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 69.947
  Epoch 21/60
Model trained in 2.55s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 72.411
  Epoch 22/60
Model trained in 2.58s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.290
  Epoch 23/60
Model trained in 2.58s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.866
  Epoch 24/60
Model trained in 2.57s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.697
  Epoch 25/60
Model trained in 2.51s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.172
  Epoch 26/60
Model trained in 2.50s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.808
  Early stopping triggered.

  best_val_SMAPE=65.131

Combination 69/144: {'encoder_hidden_size': 32, 'layers': 1, 'decoder_hidden_size': 48, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 10, 'batch_size': 64, 'sequence_length': 24, 'dropout': 0.0}
Time: 85.11 minutes - estimated total time: 177.61 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 32
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity']
  Epoch 1/60
Model trained in 1.54s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 172.621
  Epoch 2/60
Model trained in 1.54s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 159.926
  Epoch 3/60
Model trained in 1.56s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 149.868
  Epoch 4/60
Model trained in 1.59s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 141.426
  Epoch 5/60
Model trained in 1.59s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 133.921
  Epoch 6/60
Model trained in 1.55s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 127.312
  Epoch 7/60
Model trained in 1.55s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 120.754
  Epoch 8/60
Model trained in 1.59s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 115.003
  Epoch 9/60
Model trained in 1.58s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 109.567
  Epoch 10/60
Model trained in 1.59s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 104.850
  Epoch 11/60
Model trained in 1.61s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 100.309
  Epoch 12/60
Model trained in 1.60s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 95.662
  Epoch 13/60
Model trained in 1.60s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.815
  Epoch 14/60
Model trained in 1.58s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.691
  Epoch 15/60
Model trained in 1.58s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.035
  Epoch 16/60
Model trained in 1.57s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.857
  Epoch 17/60
Model trained in 1.59s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.973
  Epoch 18/60
Model trained in 1.57s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.145
  Epoch 19/60
Model trained in 1.54s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.331
  Epoch 20/60
Model trained in 1.59s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.561
  Epoch 21/60
Model trained in 1.55s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.313
  Epoch 22/60
Model trained in 1.55s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.218
  Epoch 23/60
Model trained in 1.56s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.175
  Epoch 24/60
Model trained in 1.56s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.609
  Epoch 25/60
Model trained in 1.53s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.782
  Epoch 26/60
Model trained in 1.55s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.934
  Epoch 27/60
Model trained in 1.57s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.451
  Epoch 28/60
Model trained in 1.55s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.340
  Epoch 29/60
Model trained in 1.57s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.510
  Epoch 30/60
Model trained in 1.55s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.172
  Epoch 31/60
Model trained in 1.55s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.758
  Epoch 32/60
Model trained in 1.56s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.841
  Epoch 33/60
Model trained in 1.54s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.072
  Epoch 34/60
Model trained in 1.57s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.307
  Epoch 35/60
Model trained in 1.62s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.507
  Epoch 36/60
Model trained in 1.58s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.043
  Epoch 37/60
Model trained in 1.57s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.784
  Epoch 38/60
Model trained in 1.56s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.272
  Early stopping triggered.

  best_val_SMAPE=78.340

Combination 71/144: {'encoder_hidden_size': 32, 'layers': 1, 'decoder_hidden_size': 48, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 10, 'batch_size': 64, 'sequence_length': 168, 'dropout': 0.0}
Time: 86.43 minutes - estimated total time: 175.29 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 32
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity']
  Epoch 1/60
Model trained in 1.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 172.843
  Epoch 2/60
Model trained in 1.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 160.134
  Epoch 3/60
Model trained in 1.65s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 150.112
  Epoch 4/60
Model trained in 1.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 141.843
  Epoch 5/60
Model trained in 1.62s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 134.470
  Epoch 6/60
Model trained in 1.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 127.779
  Epoch 7/60
Model trained in 1.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 121.265
  Epoch 8/60
Model trained in 1.68s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 115.189
  Epoch 9/60
Model trained in 1.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 110.641
  Epoch 10/60
Model trained in 1.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 104.895
  Epoch 11/60
Model trained in 1.67s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 100.640
  Epoch 12/60
Model trained in 1.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 96.761
  Epoch 13/60
Model trained in 1.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.575
  Epoch 14/60
Model trained in 1.67s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.754
  Epoch 15/60
Model trained in 1.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.623
  Epoch 16/60
Model trained in 1.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.338
  Epoch 17/60
Model trained in 1.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.023
  Epoch 18/60
Model trained in 1.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.991
  Epoch 19/60
Model trained in 1.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.561
  Epoch 20/60
Model trained in 1.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.966
  Epoch 21/60
Model trained in 1.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.969
  Epoch 22/60
Model trained in 1.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.098
  Epoch 23/60
Model trained in 1.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.253
  Epoch 24/60
Model trained in 1.68s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 72.054
  Epoch 25/60
Model trained in 1.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 72.229
  Epoch 26/60
Model trained in 1.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 72.395
  Epoch 27/60
Model trained in 1.68s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 71.446
  Epoch 28/60
Model trained in 1.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.083
  Epoch 29/60
Model trained in 1.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.445
  Epoch 30/60
Model trained in 1.68s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.712
  Epoch 31/60
Model trained in 1.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.787
  Epoch 32/60
Model trained in 1.65s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.801
  Epoch 33/60
Model trained in 1.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.564
  Epoch 34/60
Model trained in 1.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.251
  Epoch 35/60
Model trained in 1.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.313
  Epoch 36/60
Model trained in 1.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.859
  Epoch 37/60
Model trained in 1.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.064
  Early stopping triggered.

  best_val_SMAPE=71.446

Combination 73/144: {'encoder_hidden_size': 32, 'layers': 2, 'decoder_hidden_size': 16, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 10, 'batch_size': 32, 'sequence_length': 24, 'dropout': 0.0}
Time: 87.79 minutes - estimated total time: 173.18 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 32
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity']
  Epoch 1/60
Model trained in 3.01s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 179.776
  Epoch 2/60
Model trained in 2.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 169.846
  Epoch 3/60
Model trained in 2.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 161.421
  Epoch 4/60
Model trained in 2.98s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 153.700
  Epoch 5/60
Model trained in 2.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 146.945
  Epoch 6/60
Model trained in 2.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 140.614
  Epoch 7/60
Model trained in 2.99s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 135.793
  Epoch 8/60
Model trained in 2.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 130.817
  Epoch 9/60
Model trained in 2.99s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 125.277
  Epoch 10/60
Model trained in 2.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 120.907
  Epoch 11/60
Model trained in 2.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 116.241
  Epoch 12/60
Model trained in 2.98s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 112.451
  Epoch 13/60
Model trained in 2.97s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 108.290
  Epoch 14/60
Model trained in 2.98s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 104.673
  Epoch 15/60
Model trained in 2.98s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 100.945
  Epoch 16/60
Model trained in 3.08s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 97.253
  Epoch 17/60
Model trained in 2.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 94.131
  Epoch 18/60
Model trained in 2.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.081
  Epoch 19/60
Model trained in 2.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.978
  Epoch 20/60
Model trained in 2.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.177
  Epoch 21/60
Model trained in 2.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.757
  Epoch 22/60
Model trained in 2.97s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.742
  Epoch 23/60
Model trained in 2.95s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.466
  Epoch 24/60
Model trained in 2.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.992
  Epoch 25/60
Model trained in 2.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.734
  Epoch 26/60
Model trained in 3.01s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.463
  Epoch 27/60
Model trained in 2.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.910
  Epoch 28/60
Model trained in 2.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.425
  Epoch 29/60
Model trained in 2.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.920
  Epoch 30/60
Model trained in 2.97s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.319
  Epoch 31/60
Model trained in 3.00s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.973
  Epoch 32/60
Model trained in 2.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.770
  Epoch 33/60
Model trained in 2.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.904
  Early stopping triggered.

  best_val_SMAPE=80.466

Combination 74/144: {'encoder_hidden_size': 32, 'layers': 2, 'decoder_hidden_size': 16, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 10, 'batch_size': 32, 'sequence_length': 24, 'dropout': 0.2}
Time: 89.69 minutes - estimated total time: 174.53 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 32
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity']
  Epoch 1/60
Model trained in 2.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 179.766
  Epoch 2/60
Model trained in 2.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 169.837
  Epoch 3/60
Model trained in 3.08s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 161.414
  Epoch 4/60
Model trained in 3.01s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 153.735
  Epoch 5/60
Model trained in 3.01s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 147.472
  Epoch 6/60
Model trained in 3.00s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 141.793
  Epoch 7/60
Model trained in 2.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 136.951
  Epoch 8/60
Model trained in 2.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 131.422
  Epoch 9/60
Model trained in 2.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 125.945
  Epoch 10/60
Model trained in 3.05s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 121.574
  Epoch 11/60
Model trained in 3.01s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 118.235
  Epoch 12/60
Model trained in 2.98s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 113.417
  Epoch 13/60
Model trained in 2.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 109.642
  Epoch 14/60
Model trained in 2.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 105.869
  Epoch 15/60
Model trained in 2.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 103.003
  Epoch 16/60
Model trained in 2.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 103.677
  Epoch 17/60
Model trained in 2.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 101.394
  Epoch 18/60
Model trained in 2.98s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 96.945
  Epoch 19/60
Model trained in 2.95s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 94.827
  Epoch 20/60
Model trained in 2.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.430
  Epoch 21/60
Model trained in 2.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.605
  Epoch 22/60
Model trained in 2.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.181
  Epoch 23/60
Model trained in 2.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.786
  Epoch 24/60
Model trained in 2.95s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.844
  Epoch 25/60
Model trained in 2.97s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.444
  Epoch 26/60
Model trained in 2.98s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.158
  Epoch 27/60
Model trained in 3.02s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.483
  Epoch 28/60
Model trained in 2.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.347
  Epoch 29/60
Model trained in 2.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.258
  Epoch 30/60
Model trained in 2.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.548
  Epoch 31/60
Model trained in 2.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.341
  Epoch 32/60
Model trained in 3.02s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.222
  Epoch 33/60
Model trained in 2.99s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.415
  Epoch 34/60
Model trained in 2.98s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.777
  Epoch 35/60
Model trained in 3.02s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.206
  Epoch 36/60
Model trained in 2.98s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.524
  Epoch 37/60
Model trained in 2.95s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.394
  Epoch 38/60
Model trained in 2.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.492
  Epoch 39/60
Model trained in 2.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.187
  Epoch 40/60
Model trained in 2.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.703
  Epoch 41/60
Model trained in 2.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.103
  Epoch 42/60
Model trained in 2.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.342
  Epoch 43/60
Model trained in 2.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.719
  Epoch 44/60
Model trained in 2.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.535
  Early stopping triggered.

  best_val_SMAPE=76.777

Combination 75/144: {'encoder_hidden_size': 32, 'layers': 2, 'decoder_hidden_size': 16, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 10, 'batch_size': 32, 'sequence_length': 168, 'dropout': 0.0}
Time: 92.21 minutes - estimated total time: 177.04 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 32
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity']
  Epoch 1/60
Model trained in 3.01s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 179.898
  Epoch 2/60
Model trained in 3.07s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 169.982
  Epoch 3/60
Model trained in 3.09s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 161.575
  Epoch 4/60
Model trained in 3.10s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 154.302
  Epoch 5/60
Model trained in 3.07s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 147.621
  Epoch 6/60
Model trained in 3.11s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 143.102
  Epoch 7/60
Model trained in 3.09s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 138.285
  Epoch 8/60
Model trained in 2.98s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 133.621
  Epoch 9/60
Model trained in 2.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 128.536
  Epoch 10/60
Model trained in 3.00s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 123.483
  Epoch 11/60
Model trained in 3.04s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 118.963
  Epoch 12/60
Model trained in 3.03s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 114.514
  Epoch 13/60
Model trained in 3.07s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 112.110
  Epoch 14/60
Model trained in 3.11s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 109.290
  Epoch 15/60
Model trained in 3.06s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 106.404
  Epoch 16/60
Model trained in 3.03s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 103.283
  Epoch 17/60
Model trained in 3.02s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 100.596
  Epoch 18/60
Model trained in 2.99s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 96.863
  Epoch 19/60
Model trained in 3.16s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 94.876
  Epoch 20/60
Model trained in 3.31s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.982
  Epoch 21/60
Model trained in 3.12s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.740
  Epoch 22/60
Model trained in 3.36s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.057
  Epoch 23/60
Model trained in 3.37s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.044
  Epoch 24/60
Model trained in 3.16s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.981
  Epoch 25/60
Model trained in 3.18s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.608
  Epoch 26/60
Model trained in 3.09s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.968
  Epoch 27/60
Model trained in 3.14s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.868
  Epoch 28/60
Model trained in 3.23s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.108
  Epoch 29/60
Model trained in 3.13s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.621
  Epoch 30/60
Model trained in 3.05s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.902
  Epoch 31/60
Model trained in 3.06s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.511
  Epoch 32/60
Model trained in 3.07s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.172
  Epoch 33/60
Model trained in 3.09s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.217
  Epoch 34/60
Model trained in 3.07s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.343
  Epoch 35/60
Model trained in 3.14s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.365
  Epoch 36/60
Model trained in 3.10s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.396
  Epoch 37/60
Model trained in 2.99s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.632
  Epoch 38/60
Model trained in 2.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.383
  Epoch 39/60
Model trained in 3.07s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.715
  Epoch 40/60
Model trained in 3.13s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.991
  Early stopping triggered.

  best_val_SMAPE=77.902

Combination 76/144: {'encoder_hidden_size': 32, 'layers': 2, 'decoder_hidden_size': 16, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 10, 'batch_size': 32, 'sequence_length': 168, 'dropout': 0.2}
Time: 94.60 minutes - estimated total time: 179.25 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 32
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity']
  Epoch 1/60
Model trained in 3.28s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 179.888
  Epoch 2/60
Model trained in 3.12s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 169.973
  Epoch 3/60
Model trained in 3.14s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 161.566
  Epoch 4/60
Model trained in 3.07s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 154.244
  Epoch 5/60
Model trained in 3.05s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 147.686
  Epoch 6/60
Model trained in 2.98s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 142.377
  Epoch 7/60
Model trained in 3.00s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 136.395
  Epoch 8/60
Model trained in 3.16s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 131.532
  Epoch 9/60
Model trained in 3.17s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 126.126
  Epoch 10/60
Model trained in 3.07s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 121.062
  Epoch 11/60
Model trained in 3.04s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 116.577
  Epoch 12/60
Model trained in 3.03s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 112.295
  Epoch 13/60
Model trained in 3.06s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 108.303
  Epoch 14/60
Model trained in 2.98s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 104.580
  Epoch 15/60
Model trained in 3.06s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 101.108
  Epoch 16/60
Model trained in 3.13s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 97.460
  Epoch 17/60
Model trained in 3.11s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 94.771
  Epoch 18/60
Model trained in 3.11s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.087
  Epoch 19/60
Model trained in 3.00s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.745
  Epoch 20/60
Model trained in 2.98s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.130
  Epoch 21/60
Model trained in 3.00s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.709
  Epoch 22/60
Model trained in 2.99s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.594
  Epoch 23/60
Model trained in 3.08s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.039
  Epoch 24/60
Model trained in 3.07s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.141
  Epoch 25/60
Model trained in 3.08s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.808
  Epoch 26/60
Model trained in 3.09s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.642
  Epoch 27/60
Model trained in 3.11s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.051
  Epoch 28/60
Model trained in 3.01s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.302
  Epoch 29/60
Model trained in 3.22s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.173
  Epoch 30/60
Model trained in 3.13s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.554
  Epoch 31/60
Model trained in 3.14s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.404
  Epoch 32/60
Model trained in 3.18s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.977
  Epoch 33/60
Model trained in 3.16s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.958
  Epoch 34/60
Model trained in 3.07s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.641
  Epoch 35/60
Model trained in 3.08s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.099
  Epoch 36/60
Model trained in 3.04s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.593
  Early stopping triggered.

  best_val_SMAPE=77.642

Combination 77/144: {'encoder_hidden_size': 32, 'layers': 2, 'decoder_hidden_size': 16, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 10, 'batch_size': 64, 'sequence_length': 24, 'dropout': 0.0}
Time: 96.75 minutes - estimated total time: 180.94 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 32
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity']
  Epoch 1/60
Model trained in 1.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 186.382
  Epoch 2/60
Model trained in 1.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 179.712
  Epoch 3/60
Model trained in 1.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 174.460
  Epoch 4/60
Model trained in 1.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 169.749
  Epoch 5/60
Model trained in 1.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 165.374
  Epoch 6/60
Model trained in 1.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 161.280
  Epoch 7/60
Model trained in 1.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 157.497
  Epoch 8/60
Model trained in 1.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 153.901
  Epoch 9/60
Model trained in 1.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 150.526
  Epoch 10/60
Model trained in 1.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 147.311
  Epoch 11/60
Model trained in 1.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 144.211
  Epoch 12/60
Model trained in 1.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 141.315
  Epoch 13/60
Model trained in 1.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 138.794
  Epoch 14/60
Model trained in 1.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 136.005
  Epoch 15/60
Model trained in 1.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 133.261
  Epoch 16/60
Model trained in 1.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 130.765
  Epoch 17/60
Model trained in 1.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 128.058
  Epoch 18/60
Model trained in 1.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 126.145
  Epoch 19/60
Model trained in 1.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 124.421
  Epoch 20/60
Model trained in 1.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 122.415
  Epoch 21/60
Model trained in 1.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 120.038
  Epoch 22/60
Model trained in 1.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 118.062
  Epoch 23/60
Model trained in 1.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 116.899
  Epoch 24/60
Model trained in 1.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 115.720
  Epoch 25/60
Model trained in 1.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 113.671
  Epoch 26/60
Model trained in 1.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 111.553
  Epoch 27/60
Model trained in 1.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 109.647
  Epoch 28/60
Model trained in 1.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 108.665
  Epoch 29/60
Model trained in 1.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 106.601
  Epoch 30/60
Model trained in 1.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 106.480
  Epoch 31/60
Model trained in 1.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 105.280
  Epoch 32/60
Model trained in 1.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 104.946
  Epoch 33/60
Model trained in 1.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 105.404
  Epoch 34/60
Model trained in 1.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 105.683
  Epoch 35/60
Model trained in 1.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 105.309
  Epoch 36/60
Model trained in 1.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 104.444
  Epoch 37/60
Model trained in 1.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 102.997
  Epoch 38/60
Model trained in 1.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 102.238
  Epoch 39/60
Model trained in 1.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 101.132
  Epoch 40/60
Model trained in 1.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 101.896
  Epoch 41/60
Model trained in 1.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 101.103
  Epoch 42/60
Model trained in 1.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 101.632
  Epoch 43/60
Model trained in 1.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 101.624
  Epoch 44/60
Model trained in 1.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 100.573
  Epoch 45/60
Model trained in 1.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 99.310
  Epoch 46/60
Model trained in 1.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 96.741
  Epoch 47/60
Model trained in 1.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 95.594
  Epoch 48/60
Model trained in 1.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.833
  Epoch 49/60
Model trained in 1.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.214
  Epoch 50/60
Model trained in 1.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.763
  Epoch 51/60
Model trained in 1.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.357
  Epoch 52/60
Model trained in 1.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.203
  Epoch 53/60
Model trained in 1.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.628
  Epoch 54/60
Model trained in 1.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.735
  Epoch 55/60
Model trained in 1.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.000
  Epoch 56/60
Model trained in 1.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.745
  Epoch 57/60
Model trained in 1.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.256
  Epoch 58/60
Model trained in 1.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.257
  Epoch 59/60
Model trained in 1.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.939
  Epoch 60/60
Model trained in 1.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.781

  best_val_SMAPE=83.781

Combination 78/144: {'encoder_hidden_size': 32, 'layers': 2, 'decoder_hidden_size': 16, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 10, 'batch_size': 64, 'sequence_length': 24, 'dropout': 0.2}
Time: 99.02 minutes - estimated total time: 182.81 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 32
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity']
  Epoch 1/60
Model trained in 1.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 186.371
  Epoch 2/60
Model trained in 1.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 179.702
  Epoch 3/60
Model trained in 1.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 174.450
  Epoch 4/60
Model trained in 1.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 169.739
  Epoch 5/60
Model trained in 1.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 165.358
  Epoch 6/60
Model trained in 2.12s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 161.287
  Epoch 7/60
Model trained in 2.02s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 157.512
  Epoch 8/60
Model trained in 1.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 153.896
  Epoch 9/60
Model trained in 1.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 150.523
  Epoch 10/60
Model trained in 1.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 147.323
  Epoch 11/60
Model trained in 1.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 144.210
  Epoch 12/60
Model trained in 1.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 141.254
  Epoch 13/60
Model trained in 1.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 138.443
  Epoch 14/60
Model trained in 1.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 135.698
  Epoch 15/60
Model trained in 1.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 133.201
  Epoch 16/60
Model trained in 1.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 130.610
  Epoch 17/60
Model trained in 1.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 128.180
  Epoch 18/60
Model trained in 1.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 127.691
  Epoch 19/60
Model trained in 1.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 125.234
  Epoch 20/60
Model trained in 1.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 123.938
  Epoch 21/60
Model trained in 1.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 121.803
  Epoch 22/60
Model trained in 1.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 119.521
  Epoch 23/60
Model trained in 1.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 117.970
  Epoch 24/60
Model trained in 1.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 116.786
  Epoch 25/60
Model trained in 1.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 113.823
  Epoch 26/60
Model trained in 1.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 113.025
  Epoch 27/60
Model trained in 1.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 112.386
  Epoch 28/60
Model trained in 1.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 111.930
  Epoch 29/60
Model trained in 1.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 110.351
  Epoch 30/60
Model trained in 1.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 109.846
  Epoch 31/60
Model trained in 1.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 110.357
  Epoch 32/60
Model trained in 1.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 109.023
  Epoch 33/60
Model trained in 2.01s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 106.923
  Epoch 34/60
Model trained in 1.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 104.096
  Epoch 35/60
Model trained in 1.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 100.773
  Epoch 36/60
Model trained in 1.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 99.766
  Epoch 37/60
Model trained in 1.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 98.760
  Epoch 38/60
Model trained in 1.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 97.294
  Epoch 39/60
Model trained in 1.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 94.517
  Epoch 40/60
Model trained in 1.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.690
  Epoch 41/60
Model trained in 1.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.127
  Epoch 42/60
Model trained in 1.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.937
  Epoch 43/60
Model trained in 1.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.409
  Epoch 44/60
Model trained in 1.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.836
  Epoch 45/60
Model trained in 1.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.259
  Epoch 46/60
Model trained in 1.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.407
  Epoch 47/60
Model trained in 1.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.496
  Epoch 48/60
Model trained in 1.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.302
  Epoch 49/60
Model trained in 1.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.264
  Epoch 50/60
Model trained in 1.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.977
  Epoch 51/60
Model trained in 1.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.404
  Epoch 52/60
Model trained in 1.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.105
  Epoch 53/60
Model trained in 1.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.224
  Epoch 54/60
Model trained in 1.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.726
  Epoch 55/60
Model trained in 1.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.502
  Epoch 56/60
Model trained in 1.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.572
  Epoch 57/60
Model trained in 1.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.694
  Epoch 58/60
Model trained in 1.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.742
  Epoch 59/60
Model trained in 1.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.013
  Epoch 60/60
Model trained in 1.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.011

  best_val_SMAPE=77.013

Combination 79/144: {'encoder_hidden_size': 32, 'layers': 2, 'decoder_hidden_size': 16, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 10, 'batch_size': 64, 'sequence_length': 168, 'dropout': 0.0}
Time: 101.32 minutes - estimated total time: 184.68 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 32
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity']
  Epoch 1/60
Model trained in 2.01s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 186.472
  Epoch 2/60
Model trained in 1.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 179.801
  Epoch 3/60
Model trained in 1.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 174.563
  Epoch 4/60
Model trained in 1.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 169.864
  Epoch 5/60
Model trained in 1.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 165.496
  Epoch 6/60
Model trained in 1.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 161.430
  Epoch 7/60
Model trained in 1.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 158.075
  Epoch 8/60
Model trained in 1.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 154.064
  Epoch 9/60
Model trained in 1.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 150.714
  Epoch 10/60
Model trained in 1.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 147.511
  Epoch 11/60
Model trained in 1.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 144.476
  Epoch 12/60
Model trained in 1.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 141.529
  Epoch 13/60
Model trained in 1.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 139.453
  Epoch 14/60
Model trained in 1.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 136.777
  Epoch 15/60
Model trained in 1.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 134.129
  Epoch 16/60
Model trained in 1.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 130.891
  Epoch 17/60
Model trained in 1.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 128.533
  Epoch 18/60
Model trained in 1.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 126.107
  Epoch 19/60
Model trained in 1.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 123.513
  Epoch 20/60
Model trained in 1.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 121.420
  Epoch 21/60
Model trained in 1.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 118.975
  Epoch 22/60
Model trained in 1.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 116.523
  Epoch 23/60
Model trained in 1.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 114.829
  Epoch 24/60
Model trained in 1.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 112.828
  Epoch 25/60
Model trained in 1.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 110.725
  Epoch 26/60
Model trained in 1.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 108.848
  Epoch 27/60
Model trained in 1.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 106.929
  Epoch 28/60
Model trained in 1.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 105.799
  Epoch 29/60
Model trained in 1.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 104.086
  Epoch 30/60
Model trained in 1.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 102.502
  Epoch 31/60
Model trained in 1.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 101.007
  Epoch 32/60
Model trained in 1.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 98.698
  Epoch 33/60
Model trained in 1.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 97.644
  Epoch 34/60
Model trained in 1.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 95.766
  Epoch 35/60
Model trained in 1.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.606
  Epoch 36/60
Model trained in 1.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.049
  Epoch 37/60
Model trained in 1.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.978
  Epoch 38/60
Model trained in 1.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.684
  Epoch 39/60
Model trained in 1.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.685
  Epoch 40/60
Model trained in 1.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.634
  Epoch 41/60
Model trained in 1.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.808
  Epoch 42/60
Model trained in 1.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.735
  Epoch 43/60
Model trained in 1.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.999
  Epoch 44/60
Model trained in 1.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.884
  Epoch 45/60
Model trained in 1.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.021
  Epoch 46/60
Model trained in 1.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.360
  Epoch 47/60
Model trained in 1.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.235
  Epoch 48/60
Model trained in 1.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.864
  Epoch 49/60
Model trained in 1.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.156
  Epoch 50/60
Model trained in 1.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.896
  Epoch 51/60
Model trained in 1.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.912
  Epoch 52/60
Model trained in 1.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.554
  Epoch 53/60
Model trained in 1.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.621
  Epoch 54/60
Model trained in 1.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.864
  Epoch 55/60
Model trained in 1.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.066
  Epoch 56/60
Model trained in 1.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.111
  Epoch 57/60
Model trained in 1.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.617
  Epoch 58/60
Model trained in 1.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.410
  Epoch 59/60
Model trained in 1.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.386
  Epoch 60/60
Model trained in 1.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.942

  best_val_SMAPE=73.942

Combination 80/144: {'encoder_hidden_size': 32, 'layers': 2, 'decoder_hidden_size': 16, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 10, 'batch_size': 64, 'sequence_length': 168, 'dropout': 0.2}
Time: 103.65 minutes - estimated total time: 186.58 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 32
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity']
  Epoch 1/60
Model trained in 1.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 186.461
  Epoch 2/60
Model trained in 1.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 179.790
  Epoch 3/60
Model trained in 1.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 174.553
  Epoch 4/60
Model trained in 1.98s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 169.855
  Epoch 5/60
Model trained in 1.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 165.486
  Epoch 6/60
Model trained in 1.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 161.421
  Epoch 7/60
Model trained in 1.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 157.670
  Epoch 8/60
Model trained in 1.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 154.198
  Epoch 9/60
Model trained in 1.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 150.731
  Epoch 10/60
Model trained in 1.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 147.678
  Epoch 11/60
Model trained in 1.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 144.616
  Epoch 12/60
Model trained in 1.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 141.800
  Epoch 13/60
Model trained in 1.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 138.845
  Epoch 14/60
Model trained in 1.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 136.299
  Epoch 15/60
Model trained in 1.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 133.732
  Epoch 16/60
Model trained in 2.03s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 131.438
  Epoch 17/60
Model trained in 1.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 129.043
  Epoch 18/60
Model trained in 1.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 126.952
  Epoch 19/60
Model trained in 1.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 124.172
  Epoch 20/60
Model trained in 1.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 121.958
  Epoch 21/60
Model trained in 1.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 119.681
  Epoch 22/60
Model trained in 1.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 116.977
  Epoch 23/60
Model trained in 1.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 114.820
  Epoch 24/60
Model trained in 1.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 112.562
  Epoch 25/60
Model trained in 1.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 111.121
  Epoch 26/60
Model trained in 1.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 108.678
  Epoch 27/60
Model trained in 1.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 107.003
  Epoch 28/60
Model trained in 1.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 105.196
  Epoch 29/60
Model trained in 1.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 103.024
  Epoch 30/60
Model trained in 1.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 101.353
  Epoch 31/60
Model trained in 1.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 100.115
  Epoch 32/60
Model trained in 1.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 98.322
  Epoch 33/60
Model trained in 1.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 96.590
  Epoch 34/60
Model trained in 1.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 95.360
  Epoch 35/60
Model trained in 1.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 94.357
  Epoch 36/60
Model trained in 1.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.033
  Epoch 37/60
Model trained in 1.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.333
  Epoch 38/60
Model trained in 1.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.913
  Epoch 39/60
Model trained in 1.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.452
  Epoch 40/60
Model trained in 1.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.024
  Epoch 41/60
Model trained in 1.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.060
  Epoch 42/60
Model trained in 2.00s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.523
  Epoch 43/60
Model trained in 1.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.160
  Epoch 44/60
Model trained in 1.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.141
  Epoch 45/60
Model trained in 1.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.016
  Epoch 46/60
Model trained in 1.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.297
  Epoch 47/60
Model trained in 1.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.012
  Epoch 48/60
Model trained in 1.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.980
  Epoch 49/60
Model trained in 1.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.319
  Epoch 50/60
Model trained in 1.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.954
  Epoch 51/60
Model trained in 1.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.354
  Epoch 52/60
Model trained in 1.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.957
  Epoch 53/60
Model trained in 1.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.798
  Epoch 54/60
Model trained in 1.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.889
  Early stopping triggered.

  best_val_SMAPE=86.141

Combination 81/144: {'encoder_hidden_size': 32, 'layers': 2, 'decoder_hidden_size': 32, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 10, 'batch_size': 32, 'sequence_length': 24, 'dropout': 0.0}
Time: 105.77 minutes - estimated total time: 188.04 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 32
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity']
  Epoch 1/60
Model trained in 2.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 169.192
  Epoch 2/60
Model trained in 2.67s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 153.890
  Epoch 3/60
Model trained in 2.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 141.685
  Epoch 4/60
Model trained in 2.59s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 131.161
  Epoch 5/60
Model trained in 2.60s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 121.557
  Epoch 6/60
Model trained in 2.61s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 114.370
  Epoch 7/60
Model trained in 2.63s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 107.515
  Epoch 8/60
Model trained in 2.59s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 100.814
  Epoch 9/60
Model trained in 2.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 95.517
  Epoch 10/60
Model trained in 2.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.552
  Epoch 11/60
Model trained in 2.67s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.002
  Epoch 12/60
Model trained in 2.67s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.736
  Epoch 13/60
Model trained in 2.55s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.363
  Epoch 14/60
Model trained in 2.52s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.160
  Epoch 15/60
Model trained in 2.59s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.899
  Epoch 16/60
Model trained in 2.55s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.341
  Epoch 17/60
Model trained in 2.60s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.284
  Epoch 18/60
Model trained in 2.60s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.479
  Epoch 19/60
Model trained in 2.60s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.704
  Epoch 20/60
Model trained in 2.62s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.700
  Epoch 21/60
Model trained in 2.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.573
  Epoch 22/60
Model trained in 2.60s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.099
  Epoch 23/60
Model trained in 2.53s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.703
  Epoch 24/60
Model trained in 2.54s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.291
  Epoch 25/60
Model trained in 2.62s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.172
  Epoch 26/60
Model trained in 2.62s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.677
  Epoch 27/60
Model trained in 2.63s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.506
  Early stopping triggered.

  best_val_SMAPE=75.284

Combination 82/144: {'encoder_hidden_size': 32, 'layers': 2, 'decoder_hidden_size': 32, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 10, 'batch_size': 32, 'sequence_length': 24, 'dropout': 0.2}
Time: 107.19 minutes - estimated total time: 188.23 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 32
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity']
  Epoch 1/60
Model trained in 2.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 169.184
  Epoch 2/60
Model trained in 2.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 153.883
  Epoch 3/60
Model trained in 2.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 141.678
  Epoch 4/60
Model trained in 2.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 131.464
  Epoch 5/60
Model trained in 2.59s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 122.744
  Epoch 6/60
Model trained in 2.58s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 115.015
  Epoch 7/60
Model trained in 2.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 106.117
  Epoch 8/60
Model trained in 2.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 99.554
  Epoch 9/60
Model trained in 2.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 95.108
  Epoch 10/60
Model trained in 2.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.995
  Epoch 11/60
Model trained in 2.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.264
  Epoch 12/60
Model trained in 2.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.780
  Epoch 13/60
Model trained in 2.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.208
  Epoch 14/60
Model trained in 2.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.371
  Epoch 15/60
Model trained in 2.57s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.661
  Epoch 16/60
Model trained in 2.63s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.002
  Epoch 17/60
Model trained in 2.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.844
  Epoch 18/60
Model trained in 2.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.720
  Epoch 19/60
Model trained in 2.65s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.974
  Epoch 20/60
Model trained in 2.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.065
  Epoch 21/60
Model trained in 2.59s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.366
  Epoch 22/60
Model trained in 2.63s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.480
  Epoch 23/60
Model trained in 2.61s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.650
  Epoch 24/60
Model trained in 2.58s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.073
  Epoch 25/60
Model trained in 2.65s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.308
  Epoch 26/60
Model trained in 2.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.449
  Epoch 27/60
Model trained in 2.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.586
  Epoch 28/60
Model trained in 2.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.073
  Epoch 29/60
Model trained in 2.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.044
  Epoch 30/60
Model trained in 2.59s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.976
  Epoch 31/60
Model trained in 2.65s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.381
  Epoch 32/60
Model trained in 2.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.232
  Epoch 33/60
Model trained in 2.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.195
  Epoch 34/60
Model trained in 2.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.390
  Epoch 35/60
Model trained in 2.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.194
  Epoch 36/60
Model trained in 2.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 72.609
  Epoch 37/60
Model trained in 2.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 72.468
  Epoch 38/60
Model trained in 2.65s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 72.134
  Epoch 39/60
Model trained in 2.61s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 72.557
  Epoch 40/60
Model trained in 2.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 71.987
  Epoch 41/60
Model trained in 2.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 72.051
  Epoch 42/60
Model trained in 2.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 71.923
  Epoch 43/60
Model trained in 2.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 72.283
  Epoch 44/60
Model trained in 2.65s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.177
  Epoch 45/60
Model trained in 2.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.500
  Epoch 46/60
Model trained in 2.67s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 72.889
  Epoch 47/60
Model trained in 2.68s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 72.617
  Epoch 48/60
Model trained in 2.60s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 72.578
  Epoch 49/60
Model trained in 2.59s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.050
  Epoch 50/60
Model trained in 2.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.387
  Epoch 51/60
Model trained in 2.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.293
  Epoch 52/60
Model trained in 2.67s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.242
  Early stopping triggered.

  best_val_SMAPE=71.923

Combination 83/144: {'encoder_hidden_size': 32, 'layers': 2, 'decoder_hidden_size': 32, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 10, 'batch_size': 32, 'sequence_length': 168, 'dropout': 0.0}
Time: 109.92 minutes - estimated total time: 190.70 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 32
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity']
  Epoch 1/60
Model trained in 2.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 169.336
  Epoch 2/60
Model trained in 2.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 154.087
  Epoch 3/60
Model trained in 2.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 141.925
  Epoch 4/60
Model trained in 2.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 131.440
  Epoch 5/60
Model trained in 2.67s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 121.763
  Epoch 6/60
Model trained in 2.62s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 113.268
  Epoch 7/60
Model trained in 2.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 105.615
  Epoch 8/60
Model trained in 2.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 99.030
  Epoch 9/60
Model trained in 2.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.090
  Epoch 10/60
Model trained in 2.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.801
  Epoch 11/60
Model trained in 2.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.089
  Epoch 12/60
Model trained in 2.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.021
  Epoch 13/60
Model trained in 2.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.413
  Epoch 14/60
Model trained in 2.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.098
  Epoch 15/60
Model trained in 2.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.106
  Epoch 16/60
Model trained in 2.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.289
  Epoch 17/60
Model trained in 2.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.562
  Epoch 18/60
Model trained in 2.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.787
  Epoch 19/60
Model trained in 2.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.856
  Epoch 20/60
Model trained in 2.61s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.308
  Epoch 21/60
Model trained in 2.68s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.908
  Epoch 22/60
Model trained in 2.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.645
  Epoch 23/60
Model trained in 2.68s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.083
  Epoch 24/60
Model trained in 2.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.060
  Epoch 25/60
Model trained in 2.68s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.136
  Epoch 26/60
Model trained in 2.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.523
  Epoch 27/60
Model trained in 2.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 72.851
  Epoch 28/60
Model trained in 2.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.339
  Epoch 29/60
Model trained in 2.59s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.343
  Epoch 30/60
Model trained in 2.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.375
  Epoch 31/60
Model trained in 2.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.732
  Epoch 32/60
Model trained in 2.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.591
  Epoch 33/60
Model trained in 2.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.028
  Epoch 34/60
Model trained in 2.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 72.458
  Epoch 35/60
Model trained in 2.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 72.686
  Epoch 36/60
Model trained in 2.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.483
  Epoch 37/60
Model trained in 2.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.077
  Epoch 38/60
Model trained in 2.65s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.309
  Epoch 39/60
Model trained in 2.65s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.413
  Epoch 40/60
Model trained in 2.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.332
  Epoch 41/60
Model trained in 2.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.186
  Epoch 42/60
Model trained in 2.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.512
  Epoch 43/60
Model trained in 2.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.650
  Epoch 44/60
Model trained in 2.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.388
  Early stopping triggered.

  best_val_SMAPE=72.458

Combination 84/144: {'encoder_hidden_size': 32, 'layers': 2, 'decoder_hidden_size': 32, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 10, 'batch_size': 32, 'sequence_length': 168, 'dropout': 0.2}
Time: 112.26 minutes - estimated total time: 192.45 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 32
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity']
  Epoch 1/60
Model trained in 2.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 169.328
  Epoch 2/60
Model trained in 2.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 154.079
  Epoch 3/60
Model trained in 2.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 141.920
  Epoch 4/60
Model trained in 2.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 131.437
  Epoch 5/60
Model trained in 2.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 122.457
  Epoch 6/60
Model trained in 2.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 114.935
  Epoch 7/60
Model trained in 2.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 107.351
  Epoch 8/60
Model trained in 2.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 101.004
  Epoch 9/60
Model trained in 2.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 95.536
  Epoch 10/60
Model trained in 2.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.468
  Epoch 11/60
Model trained in 2.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.305
  Epoch 12/60
Model trained in 2.67s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.131
  Epoch 13/60
Model trained in 2.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.609
  Epoch 14/60
Model trained in 2.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.031
  Epoch 15/60
Model trained in 2.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.712
  Epoch 16/60
Model trained in 2.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.198
  Epoch 17/60
Model trained in 2.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.035
  Epoch 18/60

C:\Users\n_and\AppData\Local\Temp\ipykernel_9672\2069282406.py:17: RuntimeWarning: invalid value encountered in divide
  vals = np.where(denom == 0, 0.0, 200.0 * np.abs(y_pred - y_true) / denom)

Model trained in 2.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.530
  Epoch 19/60
Model trained in 2.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.197
  Epoch 20/60
Model trained in 2.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.618
  Epoch 21/60
Model trained in 2.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.209
  Epoch 22/60
Model trained in 2.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.526
  Epoch 23/60
Model trained in 2.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.826
  Epoch 24/60
Model trained in 2.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.242
  Epoch 25/60
Model trained in 2.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.264
  Epoch 26/60
Model trained in 2.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.955
  Early stopping triggered.

  best_val_SMAPE=79.198

Combination 85/144: {'encoder_hidden_size': 32, 'layers': 2, 'decoder_hidden_size': 32, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 10, 'batch_size': 64, 'sequence_length': 24, 'dropout': 0.0}
Time: 113.68 minutes - estimated total time: 192.58 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 32
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity']
  Epoch 1/60
Model trained in 1.59s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 178.867
  Epoch 2/60
Model trained in 1.63s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 169.188
  Epoch 3/60
Model trained in 1.62s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 160.966
  Epoch 4/60
Model trained in 1.62s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 153.823
  Epoch 5/60
Model trained in 1.62s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 147.442
  Epoch 6/60
Model trained in 1.63s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 141.573
  Epoch 7/60
Model trained in 1.63s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 136.159
  Epoch 8/60
Model trained in 1.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 130.941
  Epoch 9/60
Model trained in 1.67s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 125.542
  Epoch 10/60
Model trained in 1.65s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 120.256
  Epoch 11/60
Model trained in 1.67s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 115.397
  Epoch 12/60
Model trained in 1.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 111.427
  Epoch 13/60
Model trained in 1.61s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 107.576
  Epoch 14/60
Model trained in 1.65s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 103.975
  Epoch 15/60
Model trained in 1.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 100.507
  Epoch 16/60
Model trained in 1.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 97.599
  Epoch 17/60
Model trained in 1.68s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 94.105
  Epoch 18/60
Model trained in 1.68s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.752
  Epoch 19/60
Model trained in 1.57s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.343
  Epoch 20/60
Model trained in 1.57s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.753
  Epoch 21/60
Model trained in 1.61s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.407
  Epoch 22/60
Model trained in 1.62s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.084
  Epoch 23/60
Model trained in 1.61s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.650
  Epoch 24/60
Model trained in 1.58s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.710
  Epoch 25/60
Model trained in 1.57s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.165
  Epoch 26/60
Model trained in 1.59s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.181
  Epoch 27/60
Model trained in 1.61s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.360
  Epoch 28/60
Model trained in 1.62s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.272
  Epoch 29/60
Model trained in 1.65s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.565
  Epoch 30/60
Model trained in 1.63s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.798
  Epoch 31/60
Model trained in 1.61s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.280
  Epoch 32/60
Model trained in 1.65s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.798
  Epoch 33/60
Model trained in 1.65s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.218
  Epoch 34/60
Model trained in 1.63s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.470
  Epoch 35/60
Model trained in 1.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.109
  Epoch 36/60
Model trained in 1.62s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.260
  Epoch 37/60
Model trained in 1.57s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.641
  Epoch 38/60
Model trained in 1.59s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.928
  Epoch 39/60
Model trained in 1.56s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.109
  Epoch 40/60
Model trained in 1.60s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.118
  Epoch 41/60
Model trained in 1.59s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.061
  Epoch 42/60
Model trained in 1.61s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.204
  Epoch 43/60
Model trained in 1.61s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.316
  Epoch 44/60
Model trained in 1.61s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.420
  Early stopping triggered.

  best_val_SMAPE=77.470

Combination 86/144: {'encoder_hidden_size': 32, 'layers': 2, 'decoder_hidden_size': 32, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 10, 'batch_size': 64, 'sequence_length': 24, 'dropout': 0.2}
Time: 115.22 minutes - estimated total time: 192.92 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 32
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity']
  Epoch 1/60
Model trained in 1.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 178.860
  Epoch 2/60
Model trained in 1.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 169.180
  Epoch 3/60
Model trained in 1.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 160.958
  Epoch 4/60
Model trained in 1.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 153.816
  Epoch 5/60
Model trained in 1.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 147.437
  Epoch 6/60
Model trained in 1.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 141.569
  Epoch 7/60
Model trained in 1.65s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 136.153
  Epoch 8/60
Model trained in 1.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 131.519
  Epoch 9/60
Model trained in 1.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 128.082
  Epoch 10/60
Model trained in 1.68s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 124.007
  Epoch 11/60
Model trained in 1.63s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 119.486
  Epoch 12/60
Model trained in 1.62s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 115.495
  Epoch 13/60
Model trained in 1.65s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 111.505
  Epoch 14/60
Model trained in 1.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 107.970
  Epoch 15/60
Model trained in 1.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 105.241
  Epoch 16/60
Model trained in 1.65s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 102.119
  Epoch 17/60
Model trained in 1.67s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 99.106
  Epoch 18/60
Model trained in 1.61s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 97.134
  Epoch 19/60
Model trained in 1.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.949
  Epoch 20/60
Model trained in 1.65s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.782
  Epoch 21/60
Model trained in 1.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.496
  Epoch 22/60
Model trained in 1.67s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.568
  Epoch 23/60
Model trained in 1.61s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.143
  Epoch 24/60
Model trained in 1.58s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.846
  Epoch 25/60
Model trained in 1.57s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.580
  Epoch 26/60
Model trained in 1.59s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.065
  Epoch 27/60
Model trained in 1.62s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.246
  Epoch 28/60
Model trained in 1.62s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.727
  Epoch 29/60
Model trained in 1.60s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.633
  Epoch 30/60
Model trained in 1.58s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.465
  Epoch 31/60
Model trained in 1.67s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.374
  Epoch 32/60
Model trained in 1.67s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.167
  Epoch 33/60
Model trained in 1.63s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.829
  Epoch 34/60
Model trained in 1.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.165
  Epoch 35/60
Model trained in 1.65s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.374
  Epoch 36/60
Model trained in 1.65s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.415
  Epoch 37/60
Model trained in 1.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.586
  Epoch 38/60
Model trained in 1.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.926
  Epoch 39/60
Model trained in 1.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.324
  Epoch 40/60
Model trained in 1.62s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.705
  Epoch 41/60
Model trained in 1.61s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.605
  Epoch 42/60
Model trained in 1.60s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.287
  Epoch 43/60
Model trained in 1.59s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.104
  Epoch 44/60
Model trained in 1.60s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.990
  Epoch 45/60
Model trained in 1.58s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.366
  Epoch 46/60
Model trained in 1.60s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.749
  Epoch 47/60
Model trained in 1.59s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.814
  Epoch 48/60
Model trained in 1.63s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.009
  Early stopping triggered.

  best_val_SMAPE=75.926

Combination 87/144: {'encoder_hidden_size': 32, 'layers': 2, 'decoder_hidden_size': 32, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 10, 'batch_size': 64, 'sequence_length': 168, 'dropout': 0.0}
Time: 116.92 minutes - estimated total time: 193.53 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 32
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity']
  Epoch 1/60
Model trained in 1.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 178.911
  Epoch 2/60
Model trained in 1.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 169.258
  Epoch 3/60
Model trained in 1.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 161.072
  Epoch 4/60
Model trained in 1.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 153.951
  Epoch 5/60
Model trained in 1.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 147.593
  Epoch 6/60
Model trained in 1.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 141.745
  Epoch 7/60
Model trained in 1.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 136.344
  Epoch 8/60
Model trained in 1.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 131.217
  Epoch 9/60
Model trained in 1.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 126.306
  Epoch 10/60
Model trained in 1.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 121.613
  Epoch 11/60
Model trained in 1.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 118.055
  Epoch 12/60
Model trained in 1.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 116.901
  Epoch 13/60
Model trained in 1.68s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 116.037
  Epoch 14/60
Model trained in 1.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 111.468
  Epoch 15/60
Model trained in 1.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 109.119
  Epoch 16/60
Model trained in 1.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 108.431
  Epoch 17/60
Model trained in 1.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 103.619
  Epoch 18/60
Model trained in 1.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 100.636
  Epoch 19/60
Model trained in 1.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 97.782
  Epoch 20/60
Model trained in 1.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 96.183
  Epoch 21/60
Model trained in 1.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.771
  Epoch 22/60
Model trained in 1.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.761
  Epoch 23/60
Model trained in 1.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.005
  Epoch 24/60
Model trained in 1.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.097
  Epoch 25/60
Model trained in 1.68s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.399
  Epoch 26/60
Model trained in 1.67s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.225
  Epoch 27/60
Model trained in 1.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.863
  Epoch 28/60
Model trained in 1.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.347
  Epoch 29/60
Model trained in 1.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.716
  Epoch 30/60
Model trained in 1.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.779
  Epoch 31/60
Model trained in 1.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.506
  Epoch 32/60
Model trained in 1.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.203
  Epoch 33/60
Model trained in 1.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.729
  Epoch 34/60
Model trained in 1.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.945
  Epoch 35/60
Model trained in 1.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 95.324
  Epoch 36/60
Model trained in 1.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 96.162
  Epoch 37/60
Model trained in 1.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.471
  Early stopping triggered.

  best_val_SMAPE=84.863

Combination 88/144: {'encoder_hidden_size': 32, 'layers': 2, 'decoder_hidden_size': 32, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 10, 'batch_size': 64, 'sequence_length': 168, 'dropout': 0.2}
Time: 118.31 minutes - estimated total time: 193.59 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 32
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity']
  Epoch 1/60
Model trained in 1.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 178.904
  Epoch 2/60
Model trained in 1.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 169.251
  Epoch 3/60
Model trained in 1.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 161.064
  Epoch 4/60
Model trained in 1.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 153.945
  Epoch 5/60
Model trained in 1.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 147.587
  Epoch 6/60
Model trained in 1.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 141.740
  Epoch 7/60
Model trained in 1.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 136.314
  Epoch 8/60
Model trained in 1.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 131.211
  Epoch 9/60
Model trained in 1.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 126.284
  Epoch 10/60
Model trained in 1.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 122.240
  Epoch 11/60
Model trained in 1.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 119.058
  Epoch 12/60
Model trained in 1.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 116.201
  Epoch 13/60
Model trained in 1.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 110.420
  Epoch 14/60
Model trained in 1.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 106.604
  Epoch 15/60
Model trained in 1.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 102.890
  Epoch 16/60
Model trained in 1.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 99.400
  Epoch 17/60
Model trained in 1.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 97.390
  Epoch 18/60
Model trained in 1.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 95.367
  Epoch 19/60
Model trained in 1.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 94.374
  Epoch 20/60
Model trained in 1.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.320
  Epoch 21/60
Model trained in 1.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.388
  Epoch 22/60
Model trained in 1.68s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.003
  Epoch 23/60
Model trained in 1.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.165
  Epoch 24/60
Model trained in 1.67s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.680
  Epoch 25/60
Model trained in 1.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.966
  Epoch 26/60
Model trained in 1.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.603
  Epoch 27/60
Model trained in 1.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.275
  Epoch 28/60
Model trained in 1.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.394
  Epoch 29/60
Model trained in 1.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.580
  Epoch 30/60
Model trained in 1.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.008
  Epoch 31/60
Model trained in 1.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.830
  Epoch 32/60
Model trained in 1.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.120
  Epoch 33/60
Model trained in 1.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.967
  Epoch 34/60
Model trained in 1.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.408
  Epoch 35/60
Model trained in 1.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.750
  Epoch 36/60
Model trained in 1.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.420
  Epoch 37/60
Model trained in 1.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.371
  Early stopping triggered.

  best_val_SMAPE=84.275

Combination 89/144: {'encoder_hidden_size': 32, 'layers': 2, 'decoder_hidden_size': 48, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 10, 'batch_size': 32, 'sequence_length': 24, 'dropout': 0.0}
Time: 119.69 minutes - estimated total time: 193.66 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 32
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity']
  Epoch 1/60
Model trained in 2.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 160.852
  Epoch 2/60
Model trained in 2.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 141.699
  Epoch 3/60
Model trained in 2.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 126.472
  Epoch 4/60
Model trained in 2.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 113.355
  Epoch 5/60
Model trained in 2.97s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 106.886
  Epoch 6/60
Model trained in 2.97s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 102.137
  Epoch 7/60
Model trained in 3.01s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 94.190
  Epoch 8/60
Model trained in 2.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.739
  Epoch 9/60
Model trained in 2.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.630
  Epoch 10/60
Model trained in 2.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.078
  Epoch 11/60
Model trained in 3.04s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 98.701
  Epoch 12/60
Model trained in 2.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 105.327
  Epoch 13/60
Model trained in 2.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 103.133
  Epoch 14/60
Model trained in 2.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 102.894
  Epoch 15/60
Model trained in 2.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 94.410
  Epoch 16/60
Model trained in 2.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 95.999
  Epoch 17/60
Model trained in 2.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 94.592
  Epoch 18/60
Model trained in 2.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.628
  Epoch 19/60
Model trained in 2.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.940
  Epoch 20/60
Model trained in 2.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 94.260
  Epoch 21/60
Model trained in 2.97s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 95.153
  Epoch 22/60
Model trained in 2.95s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 95.390
  Epoch 23/60
Model trained in 2.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 97.627
  Epoch 24/60
Model trained in 2.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 99.262
  Epoch 25/60
Model trained in 2.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 101.378
  Epoch 26/60
Model trained in 2.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 98.806
  Epoch 27/60
Model trained in 2.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 100.239
  Epoch 28/60
Model trained in 2.99s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 97.177
  Early stopping triggered.

  best_val_SMAPE=91.628

Combination 90/144: {'encoder_hidden_size': 32, 'layers': 2, 'decoder_hidden_size': 48, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 10, 'batch_size': 32, 'sequence_length': 24, 'dropout': 0.2}
Time: 121.29 minutes - estimated total time: 194.07 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 32
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity']
  Epoch 1/60
Model trained in 3.01s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 160.843
  Epoch 2/60
Model trained in 2.97s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 141.692
  Epoch 3/60
Model trained in 2.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 126.432
  Epoch 4/60
Model trained in 2.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 115.741
  Epoch 5/60
Model trained in 2.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 109.440
  Epoch 6/60
Model trained in 2.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 102.551
  Epoch 7/60
Model trained in 2.95s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 94.513
  Epoch 8/60
Model trained in 2.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.226
  Epoch 9/60
Model trained in 2.98s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.339
  Epoch 10/60
Model trained in 2.95s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.662
  Epoch 11/60
Model trained in 2.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.129
  Epoch 12/60
Model trained in 2.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.802
  Epoch 13/60
Model trained in 2.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.030
  Epoch 14/60
Model trained in 2.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.218
  Epoch 15/60
Model trained in 2.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.422
  Epoch 16/60
Model trained in 2.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.179
  Epoch 17/60
Model trained in 2.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.658
  Epoch 18/60
Model trained in 2.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.560
  Epoch 19/60
Model trained in 2.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.686
  Epoch 20/60
Model trained in 2.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.663
  Epoch 21/60
Model trained in 2.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.221
  Epoch 22/60
Model trained in 2.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.536
  Epoch 23/60
Model trained in 2.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.628
  Early stopping triggered.

  best_val_SMAPE=81.030

Combination 91/144: {'encoder_hidden_size': 32, 'layers': 2, 'decoder_hidden_size': 48, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 10, 'batch_size': 32, 'sequence_length': 168, 'dropout': 0.0}
Time: 122.61 minutes - estimated total time: 194.02 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 32
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity']
  Epoch 1/60
Model trained in 3.04s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 160.907
  Epoch 2/60
Model trained in 2.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 141.872
  Epoch 3/60
Model trained in 2.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 126.685
  Epoch 4/60
Model trained in 2.97s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 114.890
  Epoch 5/60
Model trained in 3.01s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 104.525
  Epoch 6/60
Model trained in 3.00s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 97.368
  Epoch 7/60
Model trained in 2.98s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.355
  Epoch 8/60
Model trained in 2.99s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.350
  Epoch 9/60
Model trained in 3.03s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.596
  Epoch 10/60
Model trained in 2.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 94.047
  Epoch 11/60
Model trained in 2.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.934
  Epoch 12/60
Model trained in 2.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.635
  Epoch 13/60
Model trained in 3.00s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.160
  Epoch 14/60
Model trained in 3.10s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 94.197
  Epoch 15/60
Model trained in 2.97s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 95.867
  Epoch 16/60
Model trained in 2.95s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 94.881
  Epoch 17/60
Model trained in 2.97s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.422
  Epoch 18/60
Model trained in 3.02s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.986
  Epoch 19/60
Model trained in 3.07s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.348
  Epoch 20/60
Model trained in 2.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.561
  Epoch 21/60
Model trained in 2.95s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.581
  Epoch 22/60
Model trained in 3.01s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.986
  Epoch 23/60
Model trained in 3.03s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.417
  Epoch 24/60
Model trained in 2.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.658
  Epoch 25/60
Model trained in 2.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.877
  Epoch 26/60
Model trained in 2.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.845
  Epoch 27/60
Model trained in 2.95s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.829
  Epoch 28/60
Model trained in 2.97s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.360
  Epoch 29/60
Model trained in 2.99s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.827
  Epoch 30/60
Model trained in 3.10s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.323
  Epoch 31/60
Model trained in 3.08s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.330
  Epoch 32/60
Model trained in 3.06s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.909
  Epoch 33/60
Model trained in 2.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.492
  Epoch 34/60
Model trained in 3.02s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.109
  Epoch 35/60
Model trained in 2.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.204
  Epoch 36/60
Model trained in 3.02s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.057
  Epoch 37/60
Model trained in 3.00s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.131
  Epoch 38/60
Model trained in 3.00s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.918
  Epoch 39/60
Model trained in 3.02s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.696
  Epoch 40/60
Model trained in 2.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.399
  Epoch 41/60
Model trained in 2.95s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.855
  Epoch 42/60
Model trained in 2.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.984
  Epoch 43/60
Model trained in 2.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.283
  Epoch 44/60
Model trained in 3.04s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.878
  Epoch 45/60
Model trained in 3.00s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.364
  Epoch 46/60
Model trained in 3.00s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.200
  Epoch 47/60
Model trained in 2.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.256
  Epoch 48/60
Model trained in 2.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.503
  Early stopping triggered.

  best_val_SMAPE=73.918

Combination 92/144: {'encoder_hidden_size': 32, 'layers': 2, 'decoder_hidden_size': 48, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 10, 'batch_size': 32, 'sequence_length': 168, 'dropout': 0.2}
Time: 125.37 minutes - estimated total time: 196.24 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 32
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity']
  Epoch 1/60
Model trained in 3.03s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 160.900
  Epoch 2/60
Model trained in 3.03s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 141.866
  Epoch 3/60
Model trained in 3.08s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 126.679
  Epoch 4/60
Model trained in 3.01s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 114.117
  Epoch 5/60
Model trained in 3.02s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 107.102
  Epoch 6/60
Model trained in 3.00s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 99.625
  Epoch 7/60
Model trained in 2.95s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 96.880
  Epoch 8/60
Model trained in 2.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.188
  Epoch 9/60
Model trained in 2.97s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.457
  Epoch 10/60
Model trained in 3.08s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.310
  Epoch 11/60
Model trained in 3.07s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.164
  Epoch 12/60
Model trained in 3.01s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.174
  Epoch 13/60
Model trained in 2.98s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.021
  Epoch 14/60
Model trained in 2.95s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.199
  Epoch 15/60
Model trained in 2.97s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.741
  Epoch 16/60
Model trained in 3.02s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.054
  Epoch 17/60
Model trained in 2.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.335
  Epoch 18/60
Model trained in 3.00s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.450
  Epoch 19/60
Model trained in 3.03s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.142
  Epoch 20/60
Model trained in 3.00s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.811
  Epoch 21/60
Model trained in 2.95s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.277
  Epoch 22/60
Model trained in 2.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.793
  Early stopping triggered.

  best_val_SMAPE=80.174

Combination 93/144: {'encoder_hidden_size': 32, 'layers': 2, 'decoder_hidden_size': 48, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 10, 'batch_size': 64, 'sequence_length': 24, 'dropout': 0.0}
Time: 126.67 minutes - estimated total time: 196.13 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 32
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity']
  Epoch 1/60
Model trained in 1.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 173.511
  Epoch 2/60
Model trained in 1.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 160.782
  Epoch 3/60
Model trained in 1.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 150.469
  Epoch 4/60
Model trained in 1.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 141.574
  Epoch 5/60
Model trained in 1.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 133.648
  Epoch 6/60
Model trained in 1.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 126.250
  Epoch 7/60
Model trained in 1.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 119.401
  Epoch 8/60
Model trained in 1.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 113.231
  Epoch 9/60
Model trained in 1.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 109.283
  Epoch 10/60
Model trained in 1.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 104.810
  Epoch 11/60
Model trained in 1.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 99.929
  Epoch 12/60
Model trained in 1.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 96.305
  Epoch 13/60
Model trained in 1.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.045
  Epoch 14/60
Model trained in 1.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.112
  Epoch 15/60
Model trained in 1.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.838
  Epoch 16/60
Model trained in 1.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.264
  Epoch 17/60
Model trained in 1.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.353
  Epoch 18/60
Model trained in 1.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.615
  Epoch 19/60
Model trained in 1.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.090
  Epoch 20/60
Model trained in 1.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.692
  Epoch 21/60
Model trained in 1.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.446
  Epoch 22/60
Model trained in 1.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.945
  Epoch 23/60
Model trained in 1.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.948
  Epoch 24/60
Model trained in 1.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.507
  Epoch 25/60
Model trained in 1.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.431
  Epoch 26/60
Model trained in 1.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.891
  Epoch 27/60
Model trained in 1.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.974
  Epoch 28/60
Model trained in 1.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.527
  Epoch 29/60
Model trained in 1.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.163
  Epoch 30/60
Model trained in 1.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.876
  Epoch 31/60
Model trained in 1.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.082
  Epoch 32/60
Model trained in 1.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.487
  Early stopping triggered.

  best_val_SMAPE=76.945

Combination 94/144: {'encoder_hidden_size': 32, 'layers': 2, 'decoder_hidden_size': 48, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 10, 'batch_size': 64, 'sequence_length': 24, 'dropout': 0.2}
Time: 127.88 minutes - estimated total time: 195.89 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 32
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity']
  Epoch 1/60
Model trained in 1.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 173.501
  Epoch 2/60
Model trained in 1.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 160.771
  Epoch 3/60
Model trained in 1.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 150.460
  Epoch 4/60
Model trained in 1.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 141.566
  Epoch 5/60
Model trained in 1.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 133.647
  Epoch 6/60
Model trained in 1.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 126.273
  Epoch 7/60
Model trained in 1.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 119.410
  Epoch 8/60
Model trained in 1.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 113.711
  Epoch 9/60
Model trained in 1.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 108.465
  Epoch 10/60
Model trained in 1.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 103.900
  Epoch 11/60
Model trained in 1.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 102.441
  Epoch 12/60
Model trained in 1.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 98.714
  Epoch 13/60
Model trained in 1.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 95.665
  Epoch 14/60
Model trained in 1.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.614
  Epoch 15/60
Model trained in 1.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.775
  Epoch 16/60
Model trained in 1.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.170
  Epoch 17/60
Model trained in 1.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.994
  Epoch 18/60
Model trained in 1.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.711
  Epoch 19/60
Model trained in 1.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.838
  Epoch 20/60
Model trained in 1.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.418
  Epoch 21/60
Model trained in 1.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.462
  Epoch 22/60
Model trained in 1.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.042
  Epoch 23/60
Model trained in 1.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.722
  Epoch 24/60
Model trained in 1.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.838
  Epoch 25/60
Model trained in 1.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.445
  Epoch 26/60
Model trained in 1.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.215
  Epoch 27/60
Model trained in 1.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.682
  Epoch 28/60
Model trained in 1.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.594
  Epoch 29/60
Model trained in 1.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.554
  Epoch 30/60
Model trained in 1.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.805
  Epoch 31/60
Model trained in 1.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.359
  Epoch 32/60
Model trained in 1.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.643
  Epoch 33/60
Model trained in 1.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.250
  Epoch 34/60
Model trained in 1.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.565
  Epoch 35/60
Model trained in 1.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.975
  Epoch 36/60
Model trained in 1.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.353
  Early stopping triggered.

  best_val_SMAPE=82.215

Combination 95/144: {'encoder_hidden_size': 32, 'layers': 2, 'decoder_hidden_size': 48, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 10, 'batch_size': 64, 'sequence_length': 168, 'dropout': 0.0}
Time: 129.24 minutes - estimated total time: 195.90 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 32
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity']
  Epoch 1/60
Model trained in 2.07s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 173.552
  Epoch 2/60
Model trained in 1.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 160.885
  Epoch 3/60
Model trained in 1.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 150.608
  Epoch 4/60
Model trained in 1.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 141.745
  Epoch 5/60
Model trained in 1.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 133.848
  Epoch 6/60
Model trained in 1.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 126.489
  Epoch 7/60
Model trained in 1.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 119.700
  Epoch 8/60
Model trained in 1.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 114.686
  Epoch 9/60
Model trained in 1.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 112.237
  Epoch 10/60
Model trained in 1.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 110.535
  Epoch 11/60
Model trained in 1.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 105.321
  Epoch 12/60
Model trained in 1.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 102.401
  Epoch 13/60
Model trained in 1.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 99.236
  Epoch 14/60
Model trained in 1.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 96.610
  Epoch 15/60
Model trained in 1.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 94.136
  Epoch 16/60
Model trained in 1.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.858
  Epoch 17/60
Model trained in 1.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.404
  Epoch 18/60
Model trained in 1.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.165
  Epoch 19/60
Model trained in 1.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.090
  Epoch 20/60
Model trained in 1.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.664
  Epoch 21/60
Model trained in 1.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.129
  Epoch 22/60
Model trained in 1.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.612
  Epoch 23/60
Model trained in 1.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.621
  Epoch 24/60
Model trained in 1.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.313
  Epoch 25/60
Model trained in 1.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.785
  Epoch 26/60
Model trained in 1.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 97.286
  Epoch 27/60
Model trained in 1.98s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.575
  Epoch 28/60
Model trained in 1.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 94.929
  Epoch 29/60
Model trained in 1.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.643
  Epoch 30/60
Model trained in 1.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.375
  Epoch 31/60
Model trained in 1.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.161
  Epoch 32/60
Model trained in 1.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.035
  Early stopping triggered.

  best_val_SMAPE=88.612

Combination 96/144: {'encoder_hidden_size': 32, 'layers': 2, 'decoder_hidden_size': 48, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 10, 'batch_size': 64, 'sequence_length': 168, 'dropout': 0.2}
Time: 130.51 minutes - estimated total time: 195.77 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 32
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity']
  Epoch 1/60
Model trained in 1.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 173.543
  Epoch 2/60
Model trained in 1.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 160.878
  Epoch 3/60
Model trained in 1.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 150.602
  Epoch 4/60
Model trained in 1.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 141.740
  Epoch 5/60
Model trained in 1.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 133.844
  Epoch 6/60
Model trained in 1.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 126.482
  Epoch 7/60
Model trained in 1.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 119.772
  Epoch 8/60
Model trained in 1.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 114.451
  Epoch 9/60
Model trained in 1.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 108.851
  Epoch 10/60
Model trained in 1.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 104.168
  Epoch 11/60
Model trained in 1.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 100.903
  Epoch 12/60
Model trained in 1.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 96.152
  Epoch 13/60
Model trained in 1.95s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.954
  Epoch 14/60
Model trained in 1.95s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.606
  Epoch 15/60
Model trained in 1.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.638
  Epoch 16/60
Model trained in 1.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.909
  Epoch 17/60
Model trained in 1.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.886
  Epoch 18/60
Model trained in 1.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.280
  Epoch 19/60
Model trained in 1.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.513
  Epoch 20/60
Model trained in 2.08s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.239
  Epoch 21/60
Model trained in 1.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.026
  Epoch 22/60
Model trained in 1.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.680
  Epoch 23/60
Model trained in 1.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.286
  Epoch 24/60
Model trained in 1.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.068
  Epoch 25/60
Model trained in 1.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.122
  Epoch 26/60
Model trained in 1.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.900
  Epoch 27/60
Model trained in 1.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.789
  Epoch 28/60
Model trained in 1.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 72.449
  Epoch 29/60
Model trained in 1.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 71.813
  Epoch 30/60
Model trained in 1.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 71.265
  Epoch 31/60
Model trained in 1.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 70.214
  Epoch 32/60
Model trained in 1.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 70.554
  Epoch 33/60
Model trained in 1.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 70.705
  Epoch 34/60
Model trained in 1.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 71.006
  Epoch 35/60
Model trained in 1.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 71.022
  Epoch 36/60
Model trained in 1.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 71.790
  Epoch 37/60
Model trained in 1.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 71.536
  Epoch 38/60
Model trained in 1.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 72.681
  Epoch 39/60
Model trained in 1.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.513
  Epoch 40/60
Model trained in 1.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.883
  Epoch 41/60
Model trained in 1.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.570
  Early stopping triggered.

  best_val_SMAPE=70.214

Combination 97/144: {'encoder_hidden_size': 48, 'layers': 1, 'decoder_hidden_size': 16, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 10, 'batch_size': 32, 'sequence_length': 24, 'dropout': 0.0}
Time: 132.13 minutes - estimated total time: 196.15 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 32
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity']
  Epoch 1/60
Model trained in 2.55s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 178.958
  Epoch 2/60
Model trained in 2.52s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 169.075
  Epoch 3/60
Model trained in 2.45s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 160.696
  Epoch 4/60
Model trained in 2.43s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 153.574
  Epoch 5/60
Model trained in 2.48s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 148.639
  Epoch 6/60
Model trained in 2.47s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 142.208
  Epoch 7/60
Model trained in 2.49s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 136.025
  Epoch 8/60
Model trained in 2.45s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 131.146
  Epoch 9/60
Model trained in 2.46s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 127.000
  Epoch 10/60
Model trained in 2.52s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 123.942
  Epoch 11/60
Model trained in 2.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 120.055
  Epoch 12/60
Model trained in 2.50s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 115.958
  Epoch 13/60
Model trained in 2.43s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 109.953
  Epoch 14/60
Model trained in 2.43s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 106.516
  Epoch 15/60
Model trained in 2.47s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 103.710
  Epoch 16/60
Model trained in 2.49s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 99.688
  Epoch 17/60
Model trained in 2.41s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 96.882
  Epoch 18/60
Model trained in 2.42s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 94.597
  Epoch 19/60
Model trained in 2.47s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.498
  Epoch 20/60
Model trained in 2.47s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.572
  Epoch 21/60
Model trained in 2.47s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.078
  Epoch 22/60
Model trained in 2.47s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.814
  Epoch 23/60
Model trained in 2.47s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.726
  Epoch 24/60
Model trained in 2.43s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.461
  Epoch 25/60
Model trained in 2.45s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.321
  Epoch 26/60
Model trained in 2.40s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.406
  Epoch 27/60
Model trained in 2.39s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.144
  Epoch 28/60
Model trained in 2.38s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.544
  Epoch 29/60
Model trained in 2.47s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.607
  Epoch 30/60
Model trained in 2.47s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.634
  Epoch 31/60
Model trained in 2.42s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.382
  Epoch 32/60
Model trained in 2.55s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.097
  Epoch 33/60
Model trained in 2.45s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.562
  Epoch 34/60
Model trained in 2.45s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.230
  Epoch 35/60
Model trained in 2.50s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.173
  Epoch 36/60
Model trained in 2.42s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.216
  Epoch 37/60
Model trained in 2.46s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.808
  Epoch 38/60
Model trained in 2.43s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.982
  Epoch 39/60
Model trained in 2.49s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.674
  Epoch 40/60
Model trained in 2.48s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.403
  Epoch 41/60
Model trained in 2.44s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.612
  Epoch 42/60
Model trained in 2.46s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.900
  Early stopping triggered.

  best_val_SMAPE=74.097

Combination 99/144: {'encoder_hidden_size': 48, 'layers': 1, 'decoder_hidden_size': 16, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 10, 'batch_size': 32, 'sequence_length': 168, 'dropout': 0.0}
Time: 134.19 minutes - estimated total time: 195.19 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 32
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity']
  Epoch 1/60
Model trained in 2.59s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 179.066
  Epoch 2/60
Model trained in 2.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 169.282
  Epoch 3/60
Model trained in 2.55s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 160.872
  Epoch 4/60
Model trained in 2.46s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 153.667
  Epoch 5/60
Model trained in 2.53s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 147.366
  Epoch 6/60
Model trained in 2.52s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 141.615
  Epoch 7/60
Model trained in 2.53s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 136.398
  Epoch 8/60
Model trained in 2.59s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 131.708
  Epoch 9/60
Model trained in 2.60s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 127.274
  Epoch 10/60
Model trained in 2.63s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 123.007
  Epoch 11/60
Model trained in 2.56s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 118.656
  Epoch 12/60
Model trained in 2.53s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 115.211
  Epoch 13/60
Model trained in 2.47s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 111.804
  Epoch 14/60
Model trained in 2.45s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 108.541
  Epoch 15/60
Model trained in 2.56s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 105.679
  Epoch 16/60
Model trained in 2.53s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 103.130
  Epoch 17/60
Model trained in 2.48s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 100.392
  Epoch 18/60
Model trained in 2.51s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 97.432
  Epoch 19/60
Model trained in 2.55s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 95.067
  Epoch 20/60
Model trained in 2.58s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.460
  Epoch 21/60
Model trained in 2.56s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.673
  Epoch 22/60
Model trained in 2.61s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.781
  Epoch 23/60
Model trained in 2.52s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.595
  Epoch 24/60
Model trained in 2.50s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.853
  Epoch 25/60
Model trained in 2.52s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.165
  Epoch 26/60
Model trained in 2.49s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.615
  Epoch 27/60
Model trained in 2.46s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.294
  Epoch 28/60
Model trained in 2.54s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.940
  Epoch 29/60
Model trained in 2.62s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.724
  Epoch 30/60
Model trained in 2.63s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.766
  Epoch 31/60
Model trained in 2.58s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.209
  Epoch 32/60
Model trained in 2.58s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.479
  Epoch 33/60
Model trained in 2.51s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.238
  Epoch 34/60
Model trained in 2.52s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.838
  Epoch 35/60
Model trained in 2.56s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.575
  Epoch 36/60
Model trained in 2.48s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.848
  Epoch 37/60
Model trained in 2.52s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.892
  Epoch 38/60
Model trained in 2.56s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.826
  Epoch 39/60
Model trained in 2.57s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.506
  Epoch 40/60
Model trained in 2.52s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 72.277
  Epoch 41/60
Model trained in 2.57s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 70.990
  Epoch 42/60
Model trained in 2.67s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 71.261
  Epoch 43/60
Model trained in 2.56s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 71.274
  Epoch 44/60
Model trained in 2.54s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 71.523
  Epoch 45/60
Model trained in 2.48s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 72.484
  Epoch 46/60
Model trained in 2.46s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.980
  Epoch 47/60
Model trained in 2.53s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.426
  Epoch 48/60
Model trained in 2.49s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.040
  Epoch 49/60
Model trained in 2.51s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.028
  Epoch 50/60
Model trained in 2.56s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.105
  Epoch 51/60
Model trained in 2.57s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 72.661
  Early stopping triggered.

  best_val_SMAPE=70.990

Combination 101/144: {'encoder_hidden_size': 48, 'layers': 1, 'decoder_hidden_size': 16, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 10, 'batch_size': 64, 'sequence_length': 24, 'dropout': 0.0}
Time: 136.76 minutes - estimated total time: 194.98 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 32
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity']
  Epoch 1/60
Model trained in 1.58s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 185.694
  Epoch 2/60
Model trained in 1.57s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 178.928
  Epoch 3/60
Model trained in 1.52s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 173.736
  Epoch 4/60
Model trained in 1.54s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 168.995
  Epoch 5/60
Model trained in 1.55s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 164.612
  Epoch 6/60
Model trained in 1.53s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 160.584
  Epoch 7/60
Model trained in 1.56s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 156.885
  Epoch 8/60
Model trained in 1.58s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 153.424
  Epoch 9/60
Model trained in 1.57s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 150.210
  Epoch 10/60
Model trained in 1.53s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 147.181
  Epoch 11/60
Model trained in 1.55s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 144.167
  Epoch 12/60
Model trained in 1.53s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 141.338
  Epoch 13/60
Model trained in 1.56s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 138.534
  Epoch 14/60
Model trained in 1.53s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 135.927
  Epoch 15/60
Model trained in 1.51s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 133.419
  Epoch 16/60
Model trained in 1.54s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 131.031
  Epoch 17/60
Model trained in 1.52s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 128.599
  Epoch 18/60
Model trained in 1.55s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 126.302
  Epoch 19/60
Model trained in 1.52s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 124.250
  Epoch 20/60
Model trained in 1.53s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 122.036
  Epoch 21/60
Model trained in 1.51s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 119.913
  Epoch 22/60
Model trained in 1.51s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 117.610
  Epoch 23/60
Model trained in 1.52s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 115.939
  Epoch 24/60
Model trained in 1.52s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 114.154
  Epoch 25/60
Model trained in 1.52s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 112.374
  Epoch 26/60
Model trained in 1.56s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 110.815
  Epoch 27/60
Model trained in 1.58s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 109.017
  Epoch 28/60
Model trained in 1.51s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 107.020
  Epoch 29/60
Model trained in 1.50s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 105.686
  Epoch 30/60
Model trained in 1.45s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 104.203
  Epoch 31/60
Model trained in 1.48s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 102.954
  Epoch 32/60
Model trained in 1.48s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 101.474
  Epoch 33/60
Model trained in 1.49s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 99.365
  Epoch 34/60
Model trained in 1.52s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 97.843
  Epoch 35/60
Model trained in 1.50s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 96.316
  Epoch 36/60
Model trained in 1.53s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 96.605
  Epoch 37/60
Model trained in 1.53s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 95.359
  Epoch 38/60
Model trained in 1.54s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 94.222
  Epoch 39/60
Model trained in 1.51s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.881
  Epoch 40/60
Model trained in 1.52s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.120
  Epoch 41/60
Model trained in 1.51s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.525
  Epoch 42/60
Model trained in 1.52s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.373
  Epoch 43/60
Model trained in 1.53s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.097
  Epoch 44/60
Model trained in 1.57s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.802
  Epoch 45/60
Model trained in 1.56s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.990
  Epoch 46/60
Model trained in 1.51s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.635
  Epoch 47/60
Model trained in 1.50s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.721
  Epoch 48/60
Model trained in 1.49s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.824
  Epoch 49/60
Model trained in 1.47s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.140
  Epoch 50/60
Model trained in 1.46s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.514
  Epoch 51/60
Model trained in 1.52s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.214
  Epoch 52/60
Model trained in 1.55s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.489
  Epoch 53/60
Model trained in 1.57s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.908
  Epoch 54/60
Model trained in 1.55s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.585
  Epoch 55/60
Model trained in 1.51s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.591
  Epoch 56/60
Model trained in 1.53s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.309
  Epoch 57/60
Model trained in 1.53s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.430
  Epoch 58/60
Model trained in 1.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.753
  Epoch 59/60
Model trained in 1.62s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.285
  Epoch 60/60
Model trained in 1.58s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.451

  best_val_SMAPE=75.451

Combination 103/144: {'encoder_hidden_size': 48, 'layers': 1, 'decoder_hidden_size': 16, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 10, 'batch_size': 64, 'sequence_length': 168, 'dropout': 0.0}
Time: 138.76 minutes - estimated total time: 193.99 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 32
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity']
  Epoch 1/60
Model trained in 1.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 185.757
  Epoch 2/60
Model trained in 1.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 179.032
  Epoch 3/60
Model trained in 1.63s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 173.880
  Epoch 4/60
Model trained in 1.61s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 169.136
  Epoch 5/60
Model trained in 1.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 164.773
  Epoch 6/60
Model trained in 1.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 160.755
  Epoch 7/60
Model trained in 1.61s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 157.049
  Epoch 8/60
Model trained in 1.60s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 153.578
  Epoch 9/60
Model trained in 1.63s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 150.347
  Epoch 10/60
Model trained in 1.61s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 147.278
  Epoch 11/60
Model trained in 1.63s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 144.259
  Epoch 12/60
Model trained in 1.62s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 141.455
  Epoch 13/60
Model trained in 1.60s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 138.848
  Epoch 14/60
Model trained in 1.58s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 136.243
  Epoch 15/60
Model trained in 1.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 133.721
  Epoch 16/60
Model trained in 1.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 131.372
  Epoch 17/60
Model trained in 1.63s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 128.843
  Epoch 18/60
Model trained in 1.58s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 126.669
  Epoch 19/60
Model trained in 1.58s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 124.274
  Epoch 20/60
Model trained in 1.57s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 121.986
  Epoch 21/60
Model trained in 1.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 119.839
  Epoch 22/60
Model trained in 1.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 118.155
  Epoch 23/60
Model trained in 1.67s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 115.823
  Epoch 24/60
Model trained in 1.63s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 114.200
  Epoch 25/60
Model trained in 1.61s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 112.848
  Epoch 26/60
Model trained in 1.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 110.602
  Epoch 27/60
Model trained in 1.61s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 108.860
  Epoch 28/60
Model trained in 1.58s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 107.130
  Epoch 29/60
Model trained in 1.62s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 105.542
  Epoch 30/60
Model trained in 1.59s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 103.902
  Epoch 31/60
Model trained in 1.56s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 102.616
  Epoch 32/60
Model trained in 1.60s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 100.729
  Epoch 33/60
Model trained in 1.63s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 98.776
  Epoch 34/60
Model trained in 1.62s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 97.343
  Epoch 35/60
Model trained in 1.58s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 95.555
  Epoch 36/60
Model trained in 1.63s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 94.101
  Epoch 37/60
Model trained in 1.65s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.772
  Epoch 38/60
Model trained in 1.65s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.317
  Epoch 39/60
Model trained in 1.68s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.841
  Epoch 40/60
Model trained in 1.68s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.649
  Epoch 41/60
Model trained in 1.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.296
  Epoch 42/60
Model trained in 1.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.869
  Epoch 43/60
Model trained in 1.62s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.891
  Epoch 44/60
Model trained in 1.63s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.947
  Epoch 45/60
Model trained in 1.67s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.066
  Epoch 46/60
Model trained in 1.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.496
  Epoch 47/60
Model trained in 1.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.686
  Epoch 48/60
Model trained in 1.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.850
  Epoch 49/60
Model trained in 1.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.242
  Epoch 50/60
Model trained in 1.60s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.875
  Epoch 51/60
Model trained in 1.63s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.918
  Epoch 52/60
Model trained in 1.63s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.122
  Epoch 53/60
Model trained in 1.65s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.622
  Epoch 54/60
Model trained in 1.58s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.024
  Epoch 55/60
Model trained in 1.60s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.718
  Epoch 56/60
Model trained in 1.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.399
  Epoch 57/60
Model trained in 1.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.469
  Epoch 58/60
Model trained in 1.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.736
  Epoch 59/60
Model trained in 1.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.940
  Epoch 60/60
Model trained in 1.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.625

  best_val_SMAPE=73.625

Combination 105/144: {'encoder_hidden_size': 48, 'layers': 1, 'decoder_hidden_size': 32, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 10, 'batch_size': 32, 'sequence_length': 24, 'dropout': 0.0}
Time: 140.88 minutes - estimated total time: 193.20 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 32
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity']
  Epoch 1/60
Model trained in 2.52s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 169.026
  Epoch 2/60
Model trained in 2.52s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 153.632
  Epoch 3/60
Model trained in 2.47s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 141.738
  Epoch 4/60
Model trained in 2.46s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 131.982
  Epoch 5/60
Model trained in 2.43s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 122.913
  Epoch 6/60
Model trained in 2.42s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 115.103
  Epoch 7/60
Model trained in 2.44s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 108.054
  Epoch 8/60
Model trained in 2.52s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 100.754
  Epoch 9/60
Model trained in 2.58s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 94.968
  Epoch 10/60
Model trained in 2.45s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.221
  Epoch 11/60
Model trained in 2.43s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.206
  Epoch 12/60
Model trained in 2.44s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.415
  Epoch 13/60
Model trained in 2.46s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.988
  Epoch 14/60
Model trained in 2.38s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.465
  Epoch 15/60
Model trained in 2.38s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.506
  Epoch 16/60
Model trained in 2.39s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.059
  Epoch 17/60
Model trained in 2.44s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 72.929
  Epoch 18/60
Model trained in 2.40s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 72.390
  Epoch 19/60
Model trained in 2.45s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.435
  Epoch 20/60
Model trained in 2.43s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 72.867
  Epoch 21/60
Model trained in 2.47s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 70.862
  Epoch 22/60
Model trained in 2.47s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 68.660
  Epoch 23/60
Model trained in 2.45s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 68.608
  Epoch 24/60
Model trained in 2.44s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 68.348
  Epoch 25/60
Model trained in 2.39s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 68.736
  Epoch 26/60
Model trained in 2.48s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 69.823
  Epoch 27/60
Model trained in 2.50s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 71.897
  Epoch 28/60
Model trained in 2.48s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.280
  Epoch 29/60
Model trained in 2.40s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.717
  Epoch 30/60
Model trained in 2.46s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.995
  Epoch 31/60
Model trained in 2.44s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.592
  Epoch 32/60
Model trained in 2.46s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.450
  Epoch 33/60
Model trained in 2.45s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.796
  Epoch 34/60
Model trained in 2.44s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.924
  Early stopping triggered.

  best_val_SMAPE=68.348

Combination 107/144: {'encoder_hidden_size': 48, 'layers': 1, 'decoder_hidden_size': 32, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 10, 'batch_size': 32, 'sequence_length': 168, 'dropout': 0.0}
Time: 142.55 minutes - estimated total time: 191.85 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 32
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity']
  Epoch 1/60
Model trained in 2.57s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 169.028
  Epoch 2/60
Model trained in 2.59s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 153.761
  Epoch 3/60
Model trained in 2.59s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 142.046
  Epoch 4/60
Model trained in 2.51s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 132.183
  Epoch 5/60
Model trained in 2.51s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 123.008
  Epoch 6/60
Model trained in 2.56s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 114.720
  Epoch 7/60
Model trained in 2.59s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 108.067
  Epoch 8/60
Model trained in 2.61s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 101.560
  Epoch 9/60
Model trained in 2.60s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 96.106
  Epoch 10/60
Model trained in 2.56s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.213
  Epoch 11/60
Model trained in 2.54s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.574
  Epoch 12/60
Model trained in 2.51s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.069
  Epoch 13/60
Model trained in 2.47s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.848
  Epoch 14/60
Model trained in 2.46s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.268
  Epoch 15/60
Model trained in 2.46s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.036
  Epoch 16/60
Model trained in 2.48s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.209
  Epoch 17/60
Model trained in 2.55s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.560
  Epoch 18/60
Model trained in 2.53s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.438
  Epoch 19/60
Model trained in 2.53s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.432
  Epoch 20/60
Model trained in 2.58s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.470
  Epoch 21/60
Model trained in 2.57s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.523
  Epoch 22/60
Model trained in 2.55s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.171
  Epoch 23/60
Model trained in 2.61s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.268
  Epoch 24/60
Model trained in 2.52s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.451
  Epoch 25/60
Model trained in 2.53s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.921
  Epoch 26/60
Model trained in 2.49s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.832
  Epoch 27/60
Model trained in 2.51s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.595
  Epoch 28/60
Model trained in 2.55s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.960
  Early stopping triggered.

  best_val_SMAPE=75.438

Combination 109/144: {'encoder_hidden_size': 48, 'layers': 1, 'decoder_hidden_size': 32, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 10, 'batch_size': 64, 'sequence_length': 24, 'dropout': 0.0}
Time: 143.98 minutes - estimated total time: 190.21 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 32
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity']
  Epoch 1/60
Model trained in 1.58s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 178.827
  Epoch 2/60
Model trained in 1.58s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 168.905
  Epoch 3/60
Model trained in 1.58s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 160.627
  Epoch 4/60
Model trained in 1.58s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 153.506
  Epoch 5/60
Model trained in 1.60s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 147.175
  Epoch 6/60
Model trained in 1.60s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 141.968
  Epoch 7/60
Model trained in 1.57s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 136.803
  Epoch 8/60
Model trained in 1.55s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 131.970
  Epoch 9/60
Model trained in 1.67s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 127.136
  Epoch 10/60
Model trained in 1.59s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 122.885
  Epoch 11/60
Model trained in 1.55s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 118.766
  Epoch 12/60
Model trained in 1.51s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 114.644
  Epoch 13/60
Model trained in 1.55s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 111.220
  Epoch 14/60
Model trained in 1.53s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 107.635
  Epoch 15/60
Model trained in 1.54s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 105.638
  Epoch 16/60
Model trained in 1.51s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 100.957
  Epoch 17/60
Model trained in 1.53s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 97.999
  Epoch 18/60
Model trained in 1.56s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 95.362
  Epoch 19/60
Model trained in 1.56s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.326
  Epoch 20/60
Model trained in 1.52s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.406
  Epoch 21/60
Model trained in 1.53s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.059
  Epoch 22/60
Model trained in 1.50s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.943
  Epoch 23/60
Model trained in 1.50s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.800
  Epoch 24/60
Model trained in 1.51s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.507
  Epoch 25/60
Model trained in 1.53s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.599
  Epoch 26/60
Model trained in 1.58s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.153
  Epoch 27/60
Model trained in 1.57s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.004
  Epoch 28/60
Model trained in 1.53s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.723
  Epoch 29/60
Model trained in 1.45s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.183
  Epoch 30/60
Model trained in 1.47s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.241
  Epoch 31/60
Model trained in 1.49s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.295
  Epoch 32/60
Model trained in 1.49s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.878
  Epoch 33/60
Model trained in 1.50s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.488
  Epoch 34/60
Model trained in 1.50s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.628
  Epoch 35/60
Model trained in 1.52s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.499
  Epoch 36/60
Model trained in 1.48s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.364
  Epoch 37/60
Model trained in 1.46s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.223
  Epoch 38/60
Model trained in 1.49s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.848
  Epoch 39/60
Model trained in 1.53s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.834
  Epoch 40/60
Model trained in 1.62s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.314
  Epoch 41/60
Model trained in 1.58s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 72.007
  Epoch 42/60
Model trained in 1.53s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.111
  Epoch 43/60
Model trained in 1.56s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.666
  Epoch 44/60
Model trained in 1.53s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 72.206
  Epoch 45/60
Model trained in 1.58s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 71.338
  Epoch 46/60
Model trained in 1.54s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 72.518
  Epoch 47/60
Model trained in 1.53s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 72.822
  Epoch 48/60
Model trained in 1.50s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 72.993
  Epoch 49/60
Model trained in 1.49s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.555
  Epoch 50/60
Model trained in 1.50s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.141
  Epoch 51/60
Model trained in 1.53s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.860
  Epoch 52/60
Model trained in 1.57s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.233
  Epoch 53/60
Model trained in 1.58s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.170
  Epoch 54/60
Model trained in 1.55s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.280
  Epoch 55/60
Model trained in 1.54s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.665
  Early stopping triggered.

  best_val_SMAPE=71.338

Combination 111/144: {'encoder_hidden_size': 48, 'layers': 1, 'decoder_hidden_size': 32, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 10, 'batch_size': 64, 'sequence_length': 168, 'dropout': 0.0}
Time: 145.83 minutes - estimated total time: 189.18 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 32
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity']
  Epoch 1/60
Model trained in 1.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 178.767
  Epoch 2/60
Model trained in 1.65s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 168.909
  Epoch 3/60
Model trained in 1.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 160.695
  Epoch 4/60
Model trained in 1.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 153.605
  Epoch 5/60
Model trained in 1.68s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 147.560
  Epoch 6/60
Model trained in 1.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 141.924
  Epoch 7/60
Model trained in 1.67s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 136.814
  Epoch 8/60
Model trained in 1.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 131.967
  Epoch 9/60
Model trained in 1.63s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 127.456
  Epoch 10/60
Model trained in 1.62s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 123.097
  Epoch 11/60
Model trained in 1.62s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 118.866
  Epoch 12/60
Model trained in 1.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 115.016
  Epoch 13/60
Model trained in 1.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 111.362
  Epoch 14/60
Model trained in 1.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 107.543
  Epoch 15/60
Model trained in 1.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 104.036
  Epoch 16/60
Model trained in 1.60s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 100.786
  Epoch 17/60
Model trained in 1.57s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 97.813
  Epoch 18/60
Model trained in 1.57s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 94.844
  Epoch 19/60
Model trained in 1.58s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.007
  Epoch 20/60
Model trained in 1.62s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.104
  Epoch 21/60
Model trained in 1.61s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.243
  Epoch 22/60
Model trained in 1.59s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.794
  Epoch 23/60
Model trained in 1.58s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.987
  Epoch 24/60
Model trained in 1.57s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.763
  Epoch 25/60
Model trained in 1.62s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.010
  Epoch 26/60
Model trained in 1.63s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.032
  Epoch 27/60
Model trained in 1.63s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.973
  Epoch 28/60
Model trained in 1.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.451
  Epoch 29/60
Model trained in 1.61s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.314
  Epoch 30/60
Model trained in 1.60s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.450
  Epoch 31/60
Model trained in 1.62s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.311
  Epoch 32/60
Model trained in 1.62s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 71.049
  Epoch 33/60
Model trained in 1.61s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 70.202
  Epoch 34/60
Model trained in 1.61s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 69.492
  Epoch 35/60
Model trained in 1.59s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 69.099
  Epoch 36/60
Model trained in 1.57s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 69.418
  Epoch 37/60
Model trained in 1.59s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 70.152
  Epoch 38/60
Model trained in 1.60s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 69.793
  Epoch 39/60
Model trained in 1.59s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 69.393
  Epoch 40/60
Model trained in 1.59s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 69.755
  Epoch 41/60
Model trained in 1.58s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 71.694
  Epoch 42/60
Model trained in 1.58s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 70.816
  Epoch 43/60
Model trained in 1.61s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 70.428
  Epoch 44/60
Model trained in 1.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 70.937
  Epoch 45/60
Model trained in 1.61s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 71.029
  Early stopping triggered.

  best_val_SMAPE=69.099

Combination 113/144: {'encoder_hidden_size': 48, 'layers': 1, 'decoder_hidden_size': 48, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 10, 'batch_size': 32, 'sequence_length': 24, 'dropout': 0.0}
Time: 147.41 minutes - estimated total time: 187.85 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 32
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity']
  Epoch 1/60
Model trained in 2.23s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 160.688
  Epoch 2/60
Model trained in 2.19s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 141.615
  Epoch 3/60
Model trained in 2.18s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 128.556
  Epoch 4/60
Model trained in 2.23s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 115.692
  Epoch 5/60
Model trained in 2.28s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 105.839
  Epoch 6/60
Model trained in 2.19s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 96.033
  Epoch 7/60
Model trained in 2.15s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.871
  Epoch 8/60
Model trained in 2.14s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.053
  Epoch 9/60
Model trained in 2.19s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.477
  Epoch 10/60
Model trained in 2.21s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.754
  Epoch 11/60
Model trained in 2.17s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 72.515
  Epoch 12/60
Model trained in 2.12s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 68.946
  Epoch 13/60
Model trained in 2.19s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 68.521
  Epoch 14/60
Model trained in 2.20s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 68.493
  Epoch 15/60
Model trained in 2.16s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 69.051
  Epoch 16/60
Model trained in 2.16s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 71.037
  Epoch 17/60
Model trained in 2.21s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.256
  Epoch 18/60
Model trained in 2.21s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 97.537
  Epoch 19/60
Model trained in 2.22s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.828
  Epoch 20/60
Model trained in 2.18s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 96.038
  Epoch 21/60
Model trained in 2.16s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 96.678
  Epoch 22/60
Model trained in 2.12s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.205
  Epoch 23/60
Model trained in 2.10s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.471
  Epoch 24/60
Model trained in 2.17s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.399
  Early stopping triggered.

  best_val_SMAPE=68.493

Combination 115/144: {'encoder_hidden_size': 48, 'layers': 1, 'decoder_hidden_size': 48, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 10, 'batch_size': 32, 'sequence_length': 168, 'dropout': 0.0}
Time: 148.50 minutes - estimated total time: 185.94 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 32
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity']
  Epoch 1/60
Model trained in 2.30s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 160.772
  Epoch 2/60
Model trained in 2.30s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 141.702
  Epoch 3/60
Model trained in 2.35s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 127.379
  Epoch 4/60
Model trained in 2.37s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 116.598
  Epoch 5/60
Model trained in 2.33s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 105.513
  Epoch 6/60
Model trained in 2.31s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 96.785
  Epoch 7/60
Model trained in 2.28s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.582
  Epoch 8/60
Model trained in 2.22s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.662
  Epoch 9/60
Model trained in 2.22s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.135
  Epoch 10/60
Model trained in 2.24s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.609
  Epoch 11/60
Model trained in 2.21s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.422
  Epoch 12/60
Model trained in 2.19s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.780
  Epoch 13/60
Model trained in 2.22s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 96.153
  Epoch 14/60
Model trained in 2.26s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 108.537
  Epoch 15/60
Model trained in 2.34s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 105.751
  Epoch 16/60
Model trained in 2.32s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 102.509
  Epoch 17/60
Model trained in 2.35s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 102.620
  Epoch 18/60
Model trained in 2.40s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 100.060
  Epoch 19/60
Model trained in 2.35s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 106.518
  Epoch 20/60
Model trained in 2.32s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 108.326
  Epoch 21/60
Model trained in 2.29s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 109.304
  Early stopping triggered.

  best_val_SMAPE=79.422

Combination 117/144: {'encoder_hidden_size': 48, 'layers': 1, 'decoder_hidden_size': 48, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 10, 'batch_size': 64, 'sequence_length': 24, 'dropout': 0.0}
Time: 149.49 minutes - estimated total time: 183.99 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 32
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity']
  Epoch 1/60
Model trained in 1.40s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 173.470
  Epoch 2/60
Model trained in 1.38s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 160.576
  Epoch 3/60
Model trained in 1.38s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 150.266
  Epoch 4/60
Model trained in 1.43s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 141.473
  Epoch 5/60
Model trained in 1.43s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 133.913
  Epoch 6/60
Model trained in 1.44s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 127.541
  Epoch 7/60
Model trained in 1.45s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 121.201
  Epoch 8/60
Model trained in 1.38s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 115.587
  Epoch 9/60
Model trained in 1.39s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 109.763
  Epoch 10/60
Model trained in 1.39s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 104.698
  Epoch 11/60
Model trained in 1.39s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 100.270
  Epoch 12/60
Model trained in 1.42s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 97.261
  Epoch 13/60
Model trained in 1.40s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.638
  Epoch 14/60
Model trained in 1.38s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.890
  Epoch 15/60
Model trained in 1.38s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.302
  Epoch 16/60
Model trained in 1.40s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.885
  Epoch 17/60
Model trained in 1.40s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.312
  Epoch 18/60
Model trained in 1.39s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.909
  Epoch 19/60
Model trained in 1.59s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.246
  Epoch 20/60
Model trained in 1.38s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.957
  Epoch 21/60
Model trained in 1.41s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.020
  Epoch 22/60
Model trained in 1.42s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 70.682
  Epoch 23/60
Model trained in 1.42s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 71.853
  Epoch 24/60
Model trained in 1.42s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 71.383
  Epoch 25/60
Model trained in 1.44s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 71.578
  Epoch 26/60
Model trained in 1.50s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 72.591
  Epoch 27/60
Model trained in 1.44s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 71.825
  Epoch 28/60
Model trained in 1.38s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 71.549
  Epoch 29/60
Model trained in 1.39s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 71.710
  Epoch 30/60
Model trained in 1.41s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 72.121
  Epoch 31/60
Model trained in 1.40s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 71.931
  Epoch 32/60
Model trained in 1.40s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 72.458
  Early stopping triggered.

  best_val_SMAPE=70.682

Combination 119/144: {'encoder_hidden_size': 48, 'layers': 1, 'decoder_hidden_size': 48, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 10, 'batch_size': 64, 'sequence_length': 168, 'dropout': 0.0}
Time: 150.51 minutes - estimated total time: 182.13 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 32
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity']
  Epoch 1/60
Model trained in 1.53s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 173.552
  Epoch 2/60
Model trained in 1.47s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 160.715
  Epoch 3/60
Model trained in 1.48s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 150.401
  Epoch 4/60
Model trained in 1.54s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 141.594
  Epoch 5/60
Model trained in 1.54s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 133.838
  Epoch 6/60
Model trained in 1.55s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 126.708
  Epoch 7/60
Model trained in 1.52s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 121.351
  Epoch 8/60
Model trained in 1.55s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 115.358
  Epoch 9/60
Model trained in 1.53s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 109.654
  Epoch 10/60
Model trained in 1.55s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 104.805
  Epoch 11/60
Model trained in 1.57s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 99.960
  Epoch 12/60
Model trained in 1.49s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 96.193
  Epoch 13/60
Model trained in 1.51s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.910
  Epoch 14/60
Model trained in 1.47s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.088
  Epoch 15/60
Model trained in 1.50s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.819
  Epoch 16/60
Model trained in 1.53s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.463
  Epoch 17/60
Model trained in 1.52s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.560
  Epoch 18/60
Model trained in 1.47s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.544
  Epoch 19/60
Model trained in 1.50s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.705
  Epoch 20/60
Model trained in 1.47s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.137
  Epoch 21/60
Model trained in 1.48s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.856
  Epoch 22/60
Model trained in 1.52s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.811
  Epoch 23/60
Model trained in 1.54s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.920
  Epoch 24/60
Model trained in 1.61s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.459
  Epoch 25/60
Model trained in 1.50s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 72.519
  Epoch 26/60
Model trained in 1.46s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 71.844
  Epoch 27/60
Model trained in 1.48s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 71.850
  Epoch 28/60
Model trained in 1.53s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 72.227
  Epoch 29/60
Model trained in 1.50s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 72.555
  Epoch 30/60
Model trained in 1.48s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 72.134
  Epoch 31/60
Model trained in 1.46s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 71.677
  Epoch 32/60
Model trained in 1.47s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 71.524
  Epoch 33/60
Model trained in 1.46s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 71.247
  Epoch 34/60
Model trained in 1.48s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 71.607
  Epoch 35/60
Model trained in 1.50s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 71.558
  Epoch 36/60
Model trained in 1.49s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 72.112
  Epoch 37/60
Model trained in 1.49s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 71.293
  Epoch 38/60
Model trained in 1.48s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 70.324
  Epoch 39/60
Model trained in 1.52s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 70.446
  Epoch 40/60
Model trained in 1.51s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 69.450
  Epoch 41/60
Model trained in 1.46s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 68.737
  Epoch 42/60
Model trained in 1.49s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 69.328
  Epoch 43/60
Model trained in 1.49s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 70.294
  Epoch 44/60
Model trained in 1.43s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 69.542
  Epoch 45/60
Model trained in 1.44s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.293
  Epoch 46/60
Model trained in 1.43s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 72.341
  Epoch 47/60
Model trained in 1.48s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 69.888
  Epoch 48/60
Model trained in 1.45s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 70.418
  Epoch 49/60
Model trained in 1.46s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 70.901
  Epoch 50/60
Model trained in 1.44s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 70.264
  Epoch 51/60
Model trained in 1.45s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 72.497
  Early stopping triggered.

  best_val_SMAPE=68.737

Combination 121/144: {'encoder_hidden_size': 48, 'layers': 2, 'decoder_hidden_size': 16, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 10, 'batch_size': 32, 'sequence_length': 24, 'dropout': 0.0}
Time: 152.19 minutes - estimated total time: 181.12 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 32
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity']
  Epoch 1/60
Model trained in 3.01s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 179.702
  Epoch 2/60
Model trained in 2.98s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 169.738
  Epoch 3/60
Model trained in 3.00s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 161.297
  Epoch 4/60
Model trained in 2.95s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 153.952
  Epoch 5/60
Model trained in 2.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 147.971
  Epoch 6/60
Model trained in 2.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 141.717
  Epoch 7/60
Model trained in 2.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 136.493
  Epoch 8/60
Model trained in 2.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 130.875
  Epoch 9/60
Model trained in 2.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 125.547
  Epoch 10/60
Model trained in 2.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 121.135
  Epoch 11/60
Model trained in 2.98s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 116.538
  Epoch 12/60
Model trained in 2.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 112.017
  Epoch 13/60
Model trained in 2.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 107.886
  Epoch 14/60
Model trained in 2.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 103.945
  Epoch 15/60
Model trained in 2.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 100.015
  Epoch 16/60
Model trained in 2.95s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 97.284
  Epoch 17/60
Model trained in 2.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 94.774
  Epoch 18/60
Model trained in 2.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.418
  Epoch 19/60
Model trained in 2.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.376
  Epoch 20/60
Model trained in 2.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.403
  Epoch 21/60
Model trained in 2.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.929
  Epoch 22/60
Model trained in 2.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.264
  Epoch 23/60
Model trained in 2.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.256
  Epoch 24/60
Model trained in 2.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.313
  Epoch 25/60
Model trained in 2.95s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.209
  Epoch 26/60
Model trained in 2.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.265
  Epoch 27/60
Model trained in 2.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.653
  Epoch 28/60
Model trained in 2.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.264
  Epoch 29/60
Model trained in 2.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.904
  Epoch 30/60
Model trained in 2.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.706
  Epoch 31/60
Model trained in 2.98s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.006
  Epoch 32/60
Model trained in 2.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.260
  Epoch 33/60
Model trained in 2.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.656
  Epoch 34/60
Model trained in 3.02s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.956
  Epoch 35/60
Model trained in 2.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.459
  Epoch 36/60
Model trained in 2.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.464
  Epoch 37/60
Model trained in 2.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.085
  Epoch 38/60
Model trained in 3.04s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.174
  Epoch 39/60
Model trained in 2.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.297
  Epoch 40/60
Model trained in 2.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.825
  Epoch 41/60
Model trained in 2.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.546
  Epoch 42/60
Model trained in 2.95s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.720
  Epoch 43/60
Model trained in 2.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.833
  Epoch 44/60
Model trained in 2.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.161
  Epoch 45/60
Model trained in 2.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.194
  Epoch 46/60
Model trained in 2.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.794
  Epoch 47/60
Model trained in 2.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.111
  Epoch 48/60
Model trained in 2.97s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.325
  Epoch 49/60
Model trained in 2.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.186
  Epoch 50/60
Model trained in 2.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.127
  Epoch 51/60
Model trained in 2.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.531
  Epoch 52/60
Model trained in 2.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.362
  Early stopping triggered.

  best_val_SMAPE=73.720

Combination 122/144: {'encoder_hidden_size': 48, 'layers': 2, 'decoder_hidden_size': 16, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 10, 'batch_size': 32, 'sequence_length': 24, 'dropout': 0.2}
Time: 155.13 minutes - estimated total time: 183.10 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 32
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity']
  Epoch 1/60
Model trained in 3.02s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 179.695
  Epoch 2/60
Model trained in 2.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 169.729
  Epoch 3/60
Model trained in 2.98s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 161.288
  Epoch 4/60
Model trained in 2.99s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 153.944
  Epoch 5/60
Model trained in 2.95s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 147.392
  Epoch 6/60
Model trained in 2.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 141.365
  Epoch 7/60
Model trained in 2.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 135.858
  Epoch 8/60
Model trained in 2.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 128.745
  Epoch 9/60
Model trained in 3.02s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 125.840
  Epoch 10/60
Model trained in 3.07s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 120.757
  Epoch 11/60
Model trained in 2.97s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 116.291
  Epoch 12/60
Model trained in 2.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 111.947
  Epoch 13/60
Model trained in 2.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 107.952
  Epoch 14/60
Model trained in 2.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 104.184
  Epoch 15/60
Model trained in 2.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 101.405
  Epoch 16/60
Model trained in 2.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 98.643
  Epoch 17/60
Model trained in 2.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 95.040
  Epoch 18/60
Model trained in 2.95s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.482
  Epoch 19/60
Model trained in 2.97s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.865
  Epoch 20/60
Model trained in 2.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.184
  Epoch 21/60
Model trained in 3.01s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.697
  Epoch 22/60
Model trained in 2.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.528
  Epoch 23/60
Model trained in 2.95s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.370
  Epoch 24/60
Model trained in 2.98s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.555
  Epoch 25/60
Model trained in 2.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.400
  Epoch 26/60
Model trained in 2.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.393
  Epoch 27/60
Model trained in 2.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.060
  Epoch 28/60
Model trained in 2.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.555
  Epoch 29/60
Model trained in 2.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.636
  Epoch 30/60
Model trained in 2.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.402
  Epoch 31/60
Model trained in 2.95s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.223
  Epoch 32/60
Model trained in 3.03s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.900
  Epoch 33/60
Model trained in 2.98s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.492
  Epoch 34/60
Model trained in 2.97s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.187
  Epoch 35/60
Model trained in 2.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.401
  Epoch 36/60
Model trained in 2.97s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.734
  Epoch 37/60
Model trained in 2.99s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.645
  Epoch 38/60
Model trained in 2.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.711
  Epoch 39/60
Model trained in 2.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.098
  Epoch 40/60
Model trained in 2.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.665
  Epoch 41/60
Model trained in 2.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 99.678
  Epoch 42/60
Model trained in 2.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.816
  Epoch 43/60
Model trained in 2.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 102.897
  Epoch 44/60
Model trained in 2.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 102.715
  Early stopping triggered.

  best_val_SMAPE=80.187

Combination 123/144: {'encoder_hidden_size': 48, 'layers': 2, 'decoder_hidden_size': 16, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 10, 'batch_size': 32, 'sequence_length': 168, 'dropout': 0.0}
Time: 157.64 minutes - estimated total time: 184.56 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 32
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity']
  Epoch 1/60
Model trained in 3.01s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 179.813
  Epoch 2/60
Model trained in 2.99s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 169.891
  Epoch 3/60
Model trained in 3.06s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 161.485
  Epoch 4/60
Model trained in 3.04s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 154.161
  Epoch 5/60
Model trained in 2.98s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 147.631
  Epoch 6/60
Model trained in 2.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 141.623
  Epoch 7/60
Model trained in 2.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 136.073
  Epoch 8/60
Model trained in 2.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 130.790
  Epoch 9/60
Model trained in 2.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 126.164
  Epoch 10/60
Model trained in 3.03s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 121.626
  Epoch 11/60
Model trained in 2.99s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 117.059
  Epoch 12/60
Model trained in 3.05s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 112.899
  Epoch 13/60
Model trained in 2.97s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 109.352
  Epoch 14/60
Model trained in 3.00s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 105.947
  Epoch 15/60
Model trained in 2.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 102.627
  Epoch 16/60
Model trained in 2.97s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 98.933
  Epoch 17/60
Model trained in 3.00s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 95.222
  Epoch 18/60
Model trained in 3.13s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.701
  Epoch 19/60
Model trained in 3.01s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.157
  Epoch 20/60
Model trained in 2.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.447
  Epoch 21/60
Model trained in 2.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.486
  Epoch 22/60
Model trained in 2.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.609
  Epoch 23/60
Model trained in 2.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.815
  Epoch 24/60
Model trained in 2.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.852
  Epoch 25/60
Model trained in 2.98s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.191
  Epoch 26/60
Model trained in 3.01s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.970
  Epoch 27/60
Model trained in 2.98s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.910
  Epoch 28/60
Model trained in 2.99s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.609
  Epoch 29/60
Model trained in 2.99s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.155
  Epoch 30/60
Model trained in 2.99s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 72.414
  Epoch 31/60
Model trained in 2.97s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 72.486
  Epoch 32/60
Model trained in 3.03s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 72.508
  Epoch 33/60
Model trained in 3.00s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.874
  Epoch 34/60
Model trained in 3.01s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.786
  Epoch 35/60
Model trained in 2.99s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 70.952
  Epoch 36/60
Model trained in 2.97s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 71.002
  Epoch 37/60
Model trained in 2.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 69.464
  Epoch 38/60
Model trained in 2.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 69.374
  Epoch 39/60
Model trained in 2.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 69.941
  Epoch 40/60
Model trained in 3.02s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 71.097
  Epoch 41/60
Model trained in 3.02s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 71.133
  Epoch 42/60
Model trained in 3.03s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.431
  Epoch 43/60
Model trained in 2.95s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.271
  Epoch 44/60
Model trained in 3.05s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.917
  Epoch 45/60
Model trained in 2.98s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.945
  Epoch 46/60
Model trained in 2.99s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.206
  Epoch 47/60
Model trained in 3.11s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.573
  Epoch 48/60
Model trained in 2.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.415
  Early stopping triggered.

  best_val_SMAPE=69.374

Combination 124/144: {'encoder_hidden_size': 48, 'layers': 2, 'decoder_hidden_size': 16, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 10, 'batch_size': 32, 'sequence_length': 168, 'dropout': 0.2}
Time: 160.41 minutes - estimated total time: 186.28 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 32
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity']
  Epoch 1/60
Model trained in 3.25s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 179.808
  Epoch 2/60
Model trained in 3.07s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 169.887
  Epoch 3/60
Model trained in 3.03s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 161.481
  Epoch 4/60
Model trained in 2.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 154.158
  Epoch 5/60
Model trained in 2.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 147.628
  Epoch 6/60
Model trained in 3.01s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 141.621
  Epoch 7/60
Model trained in 3.13s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 136.070
  Epoch 8/60
Model trained in 3.09s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 130.787
  Epoch 9/60
Model trained in 3.03s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 125.728
  Epoch 10/60
Model trained in 3.02s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 122.405
  Epoch 11/60
Model trained in 3.07s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 119.533
  Epoch 12/60
Model trained in 2.97s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 117.226
  Epoch 13/60
Model trained in 2.95s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 113.675
  Epoch 14/60
Model trained in 3.04s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 110.019
  Epoch 15/60
Model trained in 3.10s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 108.053
  Epoch 16/60
Model trained in 3.10s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 105.732
  Epoch 17/60
Model trained in 2.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 102.544
  Epoch 18/60
Model trained in 2.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 99.202
  Epoch 19/60
Model trained in 2.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 96.136
  Epoch 20/60
Model trained in 3.01s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.732
  Epoch 21/60
Model trained in 2.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.213
  Epoch 22/60
Model trained in 2.99s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.652
  Epoch 23/60
Model trained in 3.04s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.218
  Epoch 24/60
Model trained in 3.09s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.596
  Epoch 25/60
Model trained in 2.95s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.705
  Epoch 26/60
Model trained in 2.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.041
  Epoch 27/60
Model trained in 2.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.635
  Epoch 28/60
Model trained in 3.03s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.268
  Epoch 29/60
Model trained in 3.04s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.118
  Epoch 30/60
Model trained in 3.03s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.643
  Epoch 31/60
Model trained in 3.05s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.915
  Epoch 32/60
Model trained in 3.02s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.341
  Epoch 33/60
Model trained in 3.02s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.627
  Epoch 34/60
Model trained in 2.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.088
  Epoch 35/60
Model trained in 2.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.061
  Epoch 36/60
Model trained in 3.05s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.870
  Epoch 37/60
Model trained in 3.15s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.495
  Epoch 38/60
Model trained in 3.10s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.998
  Epoch 39/60
Model trained in 3.01s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.674
  Epoch 40/60
Model trained in 2.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.164
  Early stopping triggered.

  best_val_SMAPE=80.643

Combination 125/144: {'encoder_hidden_size': 48, 'layers': 2, 'decoder_hidden_size': 16, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 10, 'batch_size': 64, 'sequence_length': 24, 'dropout': 0.0}
Time: 162.75 minutes - estimated total time: 187.48 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 32
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity']
  Epoch 1/60
Model trained in 1.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 186.452
  Epoch 2/60
Model trained in 1.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 179.673
  Epoch 3/60
Model trained in 1.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 174.390
  Epoch 4/60
Model trained in 1.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 169.668
  Epoch 5/60
Model trained in 1.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 165.281
  Epoch 6/60
Model trained in 1.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 161.197
  Epoch 7/60
Model trained in 1.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 157.417
  Epoch 8/60
Model trained in 1.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 153.833
  Epoch 9/60
Model trained in 1.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 150.471
  Epoch 10/60
Model trained in 1.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 147.261
  Epoch 11/60
Model trained in 1.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 143.698
  Epoch 12/60
Model trained in 1.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 141.456
  Epoch 13/60
Model trained in 1.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 138.497
  Epoch 14/60
Model trained in 1.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 135.911
  Epoch 15/60
Model trained in 1.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 133.105
  Epoch 16/60
Model trained in 1.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 130.284
  Epoch 17/60
Model trained in 1.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 127.740
  Epoch 18/60
Model trained in 1.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 125.242
  Epoch 19/60
Model trained in 1.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 122.396
  Epoch 20/60
Model trained in 1.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 120.141
  Epoch 21/60
Model trained in 1.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 117.892
  Epoch 22/60
Model trained in 1.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 116.320
  Epoch 23/60
Model trained in 1.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 114.666
  Epoch 24/60
Model trained in 1.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 112.571
  Epoch 25/60
Model trained in 1.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 110.151
  Epoch 26/60
Model trained in 1.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 107.950
  Epoch 27/60
Model trained in 1.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 106.191
  Epoch 28/60
Model trained in 1.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 104.067
  Epoch 29/60
Model trained in 1.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 102.535
  Epoch 30/60
Model trained in 1.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 100.837
  Epoch 31/60
Model trained in 1.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 99.546
  Epoch 32/60
Model trained in 1.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 97.925
  Epoch 33/60
Model trained in 1.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 96.215
  Epoch 34/60
Model trained in 1.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 94.399
  Epoch 35/60
Model trained in 1.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.603
  Epoch 36/60
Model trained in 1.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.172
  Epoch 37/60
Model trained in 1.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.936
  Epoch 38/60
Model trained in 1.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.720
  Epoch 39/60
Model trained in 1.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.604
  Epoch 40/60
Model trained in 1.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.345
  Epoch 41/60
Model trained in 1.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.127
  Epoch 42/60
Model trained in 1.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.311
  Epoch 43/60
Model trained in 1.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.014
  Epoch 44/60
Model trained in 1.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.864
  Epoch 45/60
Model trained in 1.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.356
  Epoch 46/60
Model trained in 1.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.585
  Epoch 47/60
Model trained in 1.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.439
  Epoch 48/60
Model trained in 1.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.730
  Epoch 49/60
Model trained in 1.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.972
  Epoch 50/60
Model trained in 1.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.204
  Epoch 51/60
Model trained in 1.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.780
  Epoch 52/60
Model trained in 1.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.348
  Epoch 53/60
Model trained in 1.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.834
  Epoch 54/60
Model trained in 1.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.916
  Epoch 55/60
Model trained in 1.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.372
  Epoch 56/60
Model trained in 1.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.249
  Epoch 57/60
Model trained in 1.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.579
  Epoch 58/60
Model trained in 1.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.275
  Epoch 59/60
Model trained in 1.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.398
  Epoch 60/60
Model trained in 1.68s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.936

  best_val_SMAPE=73.579

Combination 126/144: {'encoder_hidden_size': 48, 'layers': 2, 'decoder_hidden_size': 16, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 10, 'batch_size': 64, 'sequence_length': 24, 'dropout': 0.2}
Time: 164.99 minutes - estimated total time: 188.56 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 32
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity']
  Epoch 1/60
Model trained in 1.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 186.441
  Epoch 2/60
Model trained in 1.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 179.662
  Epoch 3/60
Model trained in 1.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 174.379
  Epoch 4/60
Model trained in 1.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 169.657
  Epoch 5/60
Model trained in 1.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 165.270
  Epoch 6/60
Model trained in 1.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 161.186
  Epoch 7/60
Model trained in 1.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 157.407
  Epoch 8/60
Model trained in 1.95s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 153.823
  Epoch 9/60
Model trained in 1.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 150.474
  Epoch 10/60
Model trained in 1.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 147.280
  Epoch 11/60
Model trained in 1.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 144.376
  Epoch 12/60
Model trained in 1.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 141.676
  Epoch 13/60
Model trained in 1.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 138.509
  Epoch 14/60
Model trained in 1.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 135.764
  Epoch 15/60
Model trained in 1.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 132.982
  Epoch 16/60
Model trained in 1.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 130.342
  Epoch 17/60
Model trained in 1.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 127.793
  Epoch 18/60
Model trained in 1.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 125.453
  Epoch 19/60
Model trained in 1.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 123.407
  Epoch 20/60
Model trained in 1.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 121.321
  Epoch 21/60
Model trained in 1.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 119.002
  Epoch 22/60
Model trained in 1.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 116.772
  Epoch 23/60
Model trained in 1.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 114.997
  Epoch 24/60
Model trained in 1.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 113.146
  Epoch 25/60
Model trained in 1.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 110.856
  Epoch 26/60
Model trained in 1.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 108.754
  Epoch 27/60
Model trained in 1.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 107.128
  Epoch 28/60
Model trained in 1.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 103.813
  Epoch 29/60
Model trained in 1.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 104.174
  Epoch 30/60
Model trained in 1.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 102.708
  Epoch 31/60
Model trained in 1.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 100.708
  Epoch 32/60
Model trained in 1.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 100.068
  Epoch 33/60
Model trained in 1.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 98.678
  Epoch 34/60
Model trained in 1.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 97.166
  Epoch 35/60
Model trained in 1.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 96.570
  Epoch 36/60
Model trained in 1.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 96.094
  Epoch 37/60
Model trained in 1.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.752
  Epoch 38/60
Model trained in 1.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.264
  Epoch 39/60
Model trained in 1.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.032
  Epoch 40/60
Model trained in 1.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.905
  Epoch 41/60
Model trained in 1.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.943
  Epoch 42/60
Model trained in 1.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.759
  Epoch 43/60
Model trained in 1.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.649
  Epoch 44/60
Model trained in 1.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.896
  Epoch 45/60
Model trained in 1.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.764
  Epoch 46/60
Model trained in 1.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.238
  Epoch 47/60
Model trained in 1.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.115
  Epoch 48/60
Model trained in 1.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.444
  Epoch 49/60
Model trained in 1.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.875
  Epoch 50/60
Model trained in 1.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.331
  Epoch 51/60
Model trained in 1.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.212
  Epoch 52/60
Model trained in 1.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.052
  Epoch 53/60
Model trained in 1.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.408
  Epoch 54/60
Model trained in 1.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.229
  Epoch 55/60
Model trained in 1.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.440
  Epoch 56/60
Model trained in 1.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.885
  Epoch 57/60
Model trained in 1.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.403
  Epoch 58/60
Model trained in 1.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.264
  Epoch 59/60
Model trained in 1.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.736
  Epoch 60/60
Model trained in 1.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.925

  best_val_SMAPE=76.925

Combination 127/144: {'encoder_hidden_size': 48, 'layers': 2, 'decoder_hidden_size': 16, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 10, 'batch_size': 64, 'sequence_length': 168, 'dropout': 0.0}
Time: 167.25 minutes - estimated total time: 189.63 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 32
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity']
  Epoch 1/60
Model trained in 1.95s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 186.516
  Epoch 2/60
Model trained in 1.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 179.771
  Epoch 3/60
Model trained in 1.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 174.513
  Epoch 4/60
Model trained in 1.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 169.808
  Epoch 5/60
Model trained in 1.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 165.436
  Epoch 6/60
Model trained in 1.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 161.367
  Epoch 7/60
Model trained in 1.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 157.594
  Epoch 8/60
Model trained in 1.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 154.020
  Epoch 9/60
Model trained in 1.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 150.666
  Epoch 10/60
Model trained in 1.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 147.466
  Epoch 11/60
Model trained in 1.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 144.382
  Epoch 12/60
Model trained in 1.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 141.438
  Epoch 13/60
Model trained in 1.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 138.616
  Epoch 14/60
Model trained in 1.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 135.711
  Epoch 15/60
Model trained in 1.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 133.149
  Epoch 16/60
Model trained in 1.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 130.475
  Epoch 17/60
Model trained in 1.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 128.095
  Epoch 18/60
Model trained in 1.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 125.720
  Epoch 19/60
Model trained in 1.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 123.589
  Epoch 20/60
Model trained in 1.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 122.153
  Epoch 21/60
Model trained in 1.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 119.695
  Epoch 22/60
Model trained in 1.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 117.673
  Epoch 23/60
Model trained in 1.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 115.717
  Epoch 24/60
Model trained in 1.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 113.487
  Epoch 25/60
Model trained in 1.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 111.732
  Epoch 26/60
Model trained in 1.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 109.271
  Epoch 27/60
Model trained in 1.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 107.246
  Epoch 28/60
Model trained in 1.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 104.714
  Epoch 29/60
Model trained in 1.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 104.493
  Epoch 30/60
Model trained in 1.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 102.660
  Epoch 31/60
Model trained in 1.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 101.148
  Epoch 32/60
Model trained in 1.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 98.803
  Epoch 33/60
Model trained in 1.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 97.733
  Epoch 34/60
Model trained in 1.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 96.362
  Epoch 35/60
Model trained in 1.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 95.081
  Epoch 36/60
Model trained in 1.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.466
  Epoch 37/60
Model trained in 2.01s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.447
  Epoch 38/60
Model trained in 1.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.585
  Epoch 39/60
Model trained in 1.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.326
  Epoch 40/60
Model trained in 1.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.733
  Epoch 41/60
Model trained in 1.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.731
  Epoch 42/60
Model trained in 1.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.667
  Epoch 43/60
Model trained in 1.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.529
  Epoch 44/60
Model trained in 1.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.184
  Epoch 45/60
Model trained in 1.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.152
  Epoch 46/60
Model trained in 1.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.428
  Epoch 47/60
Model trained in 1.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.800
  Epoch 48/60
Model trained in 1.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.455
  Epoch 49/60
Model trained in 1.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.152
  Epoch 50/60
Model trained in 1.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.609
  Epoch 51/60
Model trained in 1.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.988
  Epoch 52/60
Model trained in 1.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.303
  Epoch 53/60
Model trained in 1.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.193
  Epoch 54/60
Model trained in 2.02s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.336
  Epoch 55/60
Model trained in 1.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.812
  Epoch 56/60
Model trained in 1.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.273
  Epoch 57/60
Model trained in 1.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.018
  Epoch 58/60
Model trained in 1.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.303
  Epoch 59/60
Model trained in 1.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.000
  Epoch 60/60
Model trained in 1.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.321

  best_val_SMAPE=74.321

Combination 128/144: {'encoder_hidden_size': 48, 'layers': 2, 'decoder_hidden_size': 16, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 10, 'batch_size': 64, 'sequence_length': 168, 'dropout': 0.2}
Time: 169.58 minutes - estimated total time: 190.77 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 32
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity']
  Epoch 1/60
Model trained in 1.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 186.505
  Epoch 2/60
Model trained in 1.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 179.763
  Epoch 3/60
Model trained in 1.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 174.506
  Epoch 4/60
Model trained in 1.95s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 169.801
  Epoch 5/60
Model trained in 1.95s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 165.429
  Epoch 6/60
Model trained in 1.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 161.361
  Epoch 7/60
Model trained in 1.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 157.588
  Epoch 8/60
Model trained in 1.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 154.014
  Epoch 9/60
Model trained in 1.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 150.661
  Epoch 10/60
Model trained in 1.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 147.461
  Epoch 11/60
Model trained in 1.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 144.377
  Epoch 12/60
Model trained in 1.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 141.433
  Epoch 13/60
Model trained in 1.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 138.597
  Epoch 14/60
Model trained in 1.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 135.919
  Epoch 15/60
Model trained in 1.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 133.165
  Epoch 16/60
Model trained in 1.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 130.514
  Epoch 17/60
Model trained in 1.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 127.953
  Epoch 18/60
Model trained in 1.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 125.518
  Epoch 19/60
Model trained in 1.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 123.123
  Epoch 20/60
Model trained in 1.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 120.837
  Epoch 21/60
Model trained in 1.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 118.580
  Epoch 22/60
Model trained in 1.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 116.315
  Epoch 23/60
Model trained in 1.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 114.161
  Epoch 24/60
Model trained in 1.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 112.103
  Epoch 25/60
Model trained in 1.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 110.119
  Epoch 26/60
Model trained in 1.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 108.234
  Epoch 27/60
Model trained in 1.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 106.353
  Epoch 28/60
Model trained in 1.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 104.648
  Epoch 29/60
Model trained in 1.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 102.764
  Epoch 30/60
Model trained in 1.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 100.853
  Epoch 31/60
Model trained in 1.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 98.836
  Epoch 32/60
Model trained in 1.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 97.227
  Epoch 33/60
Model trained in 1.95s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 95.641
  Epoch 34/60
Model trained in 1.95s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 94.055
  Epoch 35/60
Model trained in 1.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.349
  Epoch 36/60
Model trained in 1.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.825
  Epoch 37/60
Model trained in 1.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.224
  Epoch 38/60
Model trained in 1.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.708
  Epoch 39/60
Model trained in 1.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.251
  Epoch 40/60
Model trained in 1.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.790
  Epoch 41/60
Model trained in 1.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.485
  Epoch 42/60
Model trained in 1.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.165
  Epoch 43/60
Model trained in 1.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.677
  Epoch 44/60
Model trained in 2.02s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.232
  Epoch 45/60
Model trained in 2.06s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.958
  Epoch 46/60
Model trained in 1.98s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.108
  Epoch 47/60
Model trained in 1.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.898
  Epoch 48/60
Model trained in 1.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.848
  Epoch 49/60
Model trained in 1.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.616
  Epoch 50/60
Model trained in 1.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 72.688
  Epoch 51/60
Model trained in 1.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 71.516
  Epoch 52/60
Model trained in 1.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 70.752
  Epoch 53/60
Model trained in 1.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 70.200
  Epoch 54/60
Model trained in 1.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 69.886
  Epoch 55/60
Model trained in 1.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 68.721
  Epoch 56/60
Model trained in 1.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 68.235
  Epoch 57/60
Model trained in 1.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 67.841
  Epoch 58/60
Model trained in 1.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 67.178
  Epoch 59/60
Model trained in 1.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 66.904
  Epoch 60/60
Model trained in 1.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 67.282

  best_val_SMAPE=66.904

Combination 129/144: {'encoder_hidden_size': 48, 'layers': 2, 'decoder_hidden_size': 32, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 10, 'batch_size': 32, 'sequence_length': 24, 'dropout': 0.0}
Time: 171.94 minutes - estimated total time: 191.93 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 32
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity']
  Epoch 1/60
Model trained in 2.98s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 169.244
  Epoch 2/60
Model trained in 2.99s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 153.924
  Epoch 3/60
Model trained in 2.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 141.715
  Epoch 4/60
Model trained in 2.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 130.963
  Epoch 5/60
Model trained in 2.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 122.183
  Epoch 6/60
Model trained in 2.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 114.043
  Epoch 7/60
Model trained in 2.95s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 106.404
  Epoch 8/60
Model trained in 2.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 99.707
  Epoch 9/60
Model trained in 2.99s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.810
  Epoch 10/60
Model trained in 2.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.548
  Epoch 11/60
Model trained in 2.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.919
  Epoch 12/60
Model trained in 2.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.248
  Epoch 13/60
Model trained in 2.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.484
  Epoch 14/60
Model trained in 2.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.199
  Epoch 15/60
Model trained in 2.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.831
  Epoch 16/60
Model trained in 2.97s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.772
  Epoch 17/60
Model trained in 2.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.884
  Epoch 18/60
Model trained in 2.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.824
  Epoch 19/60
Model trained in 2.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.097
  Epoch 20/60
Model trained in 2.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.236
  Epoch 21/60
Model trained in 2.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.643
  Epoch 22/60
Model trained in 2.97s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.304
  Epoch 23/60
Model trained in 3.02s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.072
  Epoch 24/60
Model trained in 2.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.549
  Epoch 25/60
Model trained in 2.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.295
  Early stopping triggered.

  best_val_SMAPE=74.831

Combination 130/144: {'encoder_hidden_size': 48, 'layers': 2, 'decoder_hidden_size': 32, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 10, 'batch_size': 32, 'sequence_length': 24, 'dropout': 0.2}
Time: 173.38 minutes - estimated total time: 192.05 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 32
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity']
  Epoch 1/60
Model trained in 2.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 169.235
  Epoch 2/60
Model trained in 2.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 153.916
  Epoch 3/60
Model trained in 2.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 141.705
  Epoch 4/60
Model trained in 3.04s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 131.299
  Epoch 5/60
Model trained in 3.14s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 122.188
  Epoch 6/60
Model trained in 2.99s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 113.654
  Epoch 7/60
Model trained in 2.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 106.895
  Epoch 8/60
Model trained in 2.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 100.606
  Epoch 9/60
Model trained in 2.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 95.169
  Epoch 10/60
Model trained in 2.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.880
  Epoch 11/60
Model trained in 2.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.340
  Epoch 12/60
Model trained in 2.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.042
  Epoch 13/60
Model trained in 2.97s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.942
  Epoch 14/60
Model trained in 3.04s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.090
  Epoch 15/60
Model trained in 2.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.816
  Epoch 16/60
Model trained in 2.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.413
  Epoch 17/60
Model trained in 2.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.664
  Epoch 18/60
Model trained in 2.97s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.923
  Epoch 19/60
Model trained in 3.02s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.067
  Epoch 20/60
Model trained in 2.98s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.044
  Epoch 21/60
Model trained in 3.00s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.234
  Epoch 22/60
Model trained in 2.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.385
  Epoch 23/60
Model trained in 2.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 95.331
  Epoch 24/60
Model trained in 3.02s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.129
  Epoch 25/60
Model trained in 2.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.224
  Epoch 26/60
Model trained in 2.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.487
  Early stopping triggered.

  best_val_SMAPE=79.413

Combination 131/144: {'encoder_hidden_size': 48, 'layers': 2, 'decoder_hidden_size': 32, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 10, 'batch_size': 32, 'sequence_length': 168, 'dropout': 0.0}
Time: 174.88 minutes - estimated total time: 192.24 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 32
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity']
  Epoch 1/60
Model trained in 3.09s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 169.287
  Epoch 2/60
Model trained in 3.01s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 154.063
  Epoch 3/60
Model trained in 3.01s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 141.909
  Epoch 4/60
Model trained in 3.01s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 131.428
  Epoch 5/60
Model trained in 3.02s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 122.672
  Epoch 6/60
Model trained in 3.07s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 115.256
  Epoch 7/60
Model trained in 2.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 109.544
  Epoch 8/60
Model trained in 2.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 106.049
  Epoch 9/60
Model trained in 3.00s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 105.461
  Epoch 10/60
Model trained in 3.05s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 99.756
  Epoch 11/60
Model trained in 2.97s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 98.656
  Epoch 12/60
Model trained in 2.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 98.149
  Epoch 13/60
Model trained in 2.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 94.368
  Epoch 14/60
Model trained in 2.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.597
  Epoch 15/60
Model trained in 2.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.849
  Epoch 16/60
Model trained in 3.13s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.946
  Epoch 17/60
Model trained in 2.97s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.033
  Epoch 18/60
Model trained in 3.01s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.910
  Epoch 19/60
Model trained in 2.98s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.296
  Epoch 20/60
Model trained in 2.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.925
  Epoch 21/60
Model trained in 2.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.579
  Epoch 22/60
Model trained in 2.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.801
  Epoch 23/60
Model trained in 2.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.545
  Epoch 24/60
Model trained in 2.95s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.763
  Epoch 25/60
Model trained in 3.04s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.426
  Epoch 26/60
Model trained in 3.01s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.449
  Epoch 27/60
Model trained in 2.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.563
  Epoch 28/60
Model trained in 2.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.105
  Epoch 29/60
Model trained in 2.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.622
  Epoch 30/60
Model trained in 2.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.084
  Epoch 31/60
Model trained in 3.04s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.719
  Epoch 32/60
Model trained in 3.06s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.845
  Epoch 33/60
Model trained in 3.01s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.526
  Epoch 34/60
Model trained in 3.04s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.450
  Epoch 35/60
Model trained in 2.97s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.885
  Epoch 36/60
Model trained in 3.00s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.629
  Epoch 37/60
Model trained in 2.97s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.462
  Epoch 38/60
Model trained in 2.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 72.958
  Epoch 39/60
Model trained in 3.03s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 72.254
  Epoch 40/60
Model trained in 2.97s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 72.331
  Epoch 41/60
Model trained in 2.98s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 71.926
  Epoch 42/60
Model trained in 2.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 72.063
  Epoch 43/60
Model trained in 2.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 71.820
  Epoch 44/60
Model trained in 2.95s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 72.585
  Epoch 45/60
Model trained in 2.98s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 72.792
  Epoch 46/60
Model trained in 2.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 72.054
  Epoch 47/60
Model trained in 2.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.812
  Epoch 48/60
Model trained in 2.97s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.363
  Epoch 49/60
Model trained in 2.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.122
  Epoch 50/60
Model trained in 2.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.115
  Epoch 51/60
Model trained in 2.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.350
  Epoch 52/60
Model trained in 2.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.180
  Epoch 53/60
Model trained in 2.97s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.305
  Early stopping triggered.

  best_val_SMAPE=71.820

Combination 132/144: {'encoder_hidden_size': 48, 'layers': 2, 'decoder_hidden_size': 32, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 10, 'batch_size': 32, 'sequence_length': 168, 'dropout': 0.2}
Time: 177.92 minutes - estimated total time: 194.10 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 32
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity']
  Epoch 1/60
Model trained in 3.10s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 169.279
  Epoch 2/60
Model trained in 3.02s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 154.055
  Epoch 3/60
Model trained in 3.06s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 141.902
  Epoch 4/60
Model trained in 3.17s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 131.422
  Epoch 5/60
Model trained in 3.09s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 121.857
  Epoch 6/60
Model trained in 2.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 115.484
  Epoch 7/60
Model trained in 2.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 107.701
  Epoch 8/60
Model trained in 3.06s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 103.085
  Epoch 9/60
Model trained in 3.10s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 99.483
  Epoch 10/60
Model trained in 3.04s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 96.682
  Epoch 11/60
Model trained in 2.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 94.116
  Epoch 12/60
Model trained in 2.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.310
  Epoch 13/60
Model trained in 2.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.388
  Epoch 14/60
Model trained in 3.14s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.236
  Epoch 15/60
Model trained in 2.97s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.043
  Epoch 16/60
Model trained in 2.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.199
  Epoch 17/60
Model trained in 2.99s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.577
  Epoch 18/60
Model trained in 3.06s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.790
  Epoch 19/60
Model trained in 2.97s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.005
  Epoch 20/60
Model trained in 2.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.254
  Epoch 21/60
Model trained in 2.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.881
  Epoch 22/60
Model trained in 2.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.672
  Epoch 23/60
Model trained in 3.15s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.932
  Epoch 24/60
Model trained in 2.97s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.374
  Epoch 25/60
Model trained in 3.01s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.589
  Epoch 26/60
Model trained in 3.00s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.323
  Epoch 27/60
Model trained in 2.97s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.635
  Epoch 28/60
Model trained in 2.95s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.773
  Epoch 29/60
Model trained in 2.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.369
  Epoch 30/60
Model trained in 3.05s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.056
  Epoch 31/60
Model trained in 3.12s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.158
  Epoch 32/60
Model trained in 3.17s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.022
  Epoch 33/60
Model trained in 3.06s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.420
  Epoch 34/60
Model trained in 2.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.993
  Epoch 35/60
Model trained in 3.03s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.375
  Epoch 36/60
Model trained in 2.98s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.694
  Epoch 37/60
Model trained in 2.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.747
  Epoch 38/60
Model trained in 2.97s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 72.521
  Epoch 39/60
Model trained in 2.99s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 72.565
  Epoch 40/60
Model trained in 3.06s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 72.125
  Epoch 41/60
Model trained in 3.08s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 72.337
  Epoch 42/60
Model trained in 2.98s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 72.213
  Epoch 43/60
Model trained in 2.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 71.991
  Epoch 44/60
Model trained in 3.02s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 71.689
  Epoch 45/60
Model trained in 3.08s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 70.415
  Epoch 46/60
Model trained in 3.00s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 70.781
  Epoch 47/60
Model trained in 2.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 70.609
  Epoch 48/60
Model trained in 3.01s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 70.482
  Epoch 49/60
Model trained in 2.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 70.763
  Epoch 50/60
Model trained in 2.97s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 71.207
  Epoch 51/60
Model trained in 3.08s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 71.601
  Epoch 52/60
Model trained in 2.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 72.126
  Epoch 53/60
Model trained in 3.02s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 71.363
  Epoch 54/60
Model trained in 3.05s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 71.343
  Epoch 55/60
Model trained in 3.04s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 70.229
  Epoch 56/60
Model trained in 2.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 70.833
  Epoch 57/60
Model trained in 2.97s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 70.816
  Epoch 58/60
Model trained in 3.03s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 69.862
  Epoch 59/60
Model trained in 2.95s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 68.949
  Epoch 60/60
Model trained in 3.09s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 68.276

  best_val_SMAPE=68.276

Combination 133/144: {'encoder_hidden_size': 48, 'layers': 2, 'decoder_hidden_size': 32, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 10, 'batch_size': 64, 'sequence_length': 24, 'dropout': 0.0}
Time: 181.40 minutes - estimated total time: 196.40 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 32
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity']
  Epoch 1/60
Model trained in 1.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 178.800
  Epoch 2/60
Model trained in 1.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 169.125
  Epoch 3/60
Model trained in 1.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 160.908
  Epoch 4/60
Model trained in 1.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 153.772
  Epoch 5/60
Model trained in 1.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 147.396
  Epoch 6/60
Model trained in 1.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 141.532
  Epoch 7/60
Model trained in 1.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 136.549
  Epoch 8/60
Model trained in 1.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 131.631
  Epoch 9/60
Model trained in 1.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 127.099
  Epoch 10/60
Model trained in 1.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 122.761
  Epoch 11/60
Model trained in 1.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 118.933
  Epoch 12/60
Model trained in 1.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 116.564
  Epoch 13/60
Model trained in 1.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 112.160
  Epoch 14/60
Model trained in 1.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 108.475
  Epoch 15/60
Model trained in 1.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 105.242
  Epoch 16/60
Model trained in 1.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 102.353
  Epoch 17/60
Model trained in 1.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 99.119
  Epoch 18/60
Model trained in 1.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 97.118
  Epoch 19/60
Model trained in 1.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 94.170
  Epoch 20/60
Model trained in 1.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.851
  Epoch 21/60
Model trained in 1.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.156
  Epoch 22/60
Model trained in 1.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.147
  Epoch 23/60
Model trained in 1.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.160
  Epoch 24/60
Model trained in 1.68s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.768
  Epoch 25/60
Model trained in 1.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.789
  Epoch 26/60
Model trained in 1.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.472
  Epoch 27/60
Model trained in 1.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.250
  Epoch 28/60
Model trained in 1.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.684
  Epoch 29/60
Model trained in 1.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.101
  Epoch 30/60
Model trained in 1.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.893
  Epoch 31/60
Model trained in 1.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.339
  Epoch 32/60
Model trained in 1.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.555
  Epoch 33/60
Model trained in 1.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.156
  Epoch 34/60
Model trained in 1.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.519
  Epoch 35/60
Model trained in 1.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.064
  Epoch 36/60
Model trained in 1.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.052
  Epoch 37/60
Model trained in 1.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.522
  Epoch 38/60
Model trained in 1.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.145
  Epoch 39/60
Model trained in 1.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.044
  Epoch 40/60
Model trained in 1.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.118
  Epoch 41/60
Model trained in 1.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.438
  Epoch 42/60
Model trained in 1.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.354
  Epoch 43/60
Model trained in 1.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.544
  Epoch 44/60
Model trained in 1.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.004
  Epoch 45/60
Model trained in 1.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.710
  Epoch 46/60
Model trained in 1.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.710
  Epoch 47/60
Model trained in 1.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.851
  Epoch 48/60
Model trained in 1.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.836
  Epoch 49/60
Model trained in 1.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.391
  Epoch 50/60
Model trained in 1.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.353
  Early stopping triggered.

  best_val_SMAPE=73.118

Combination 134/144: {'encoder_hidden_size': 48, 'layers': 2, 'decoder_hidden_size': 32, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 10, 'batch_size': 64, 'sequence_length': 24, 'dropout': 0.2}
Time: 183.26 minutes - estimated total time: 196.94 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 32
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity']
  Epoch 1/60
Model trained in 1.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 178.792
  Epoch 2/60
Model trained in 1.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 169.116
  Epoch 3/60
Model trained in 1.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 160.900
  Epoch 4/60
Model trained in 1.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 153.764
  Epoch 5/60
Model trained in 1.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 147.389
  Epoch 6/60
Model trained in 1.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 141.525
  Epoch 7/60
Model trained in 1.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 136.111
  Epoch 8/60
Model trained in 1.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 130.962
  Epoch 9/60
Model trained in 1.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 126.035
  Epoch 10/60
Model trained in 1.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 122.352
  Epoch 11/60
Model trained in 1.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 117.875
  Epoch 12/60
Model trained in 1.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 113.708
  Epoch 13/60
Model trained in 1.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 109.512
  Epoch 14/60
Model trained in 1.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 105.578
  Epoch 15/60
Model trained in 1.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 102.441
  Epoch 16/60
Model trained in 1.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 99.467
  Epoch 17/60
Model trained in 1.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 96.199
  Epoch 18/60
Model trained in 1.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.533
  Epoch 19/60
Model trained in 1.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.738
  Epoch 20/60
Model trained in 1.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.484
  Epoch 21/60
Model trained in 1.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.295
  Epoch 22/60
Model trained in 1.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.365
  Epoch 23/60
Model trained in 1.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.170
  Epoch 24/60
Model trained in 1.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.691
  Epoch 25/60
Model trained in 1.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.516
  Epoch 26/60
Model trained in 1.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.637
  Epoch 27/60
Model trained in 1.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.143
  Epoch 28/60
Model trained in 1.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.079
  Epoch 29/60
Model trained in 1.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.801
  Epoch 30/60
Model trained in 1.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 72.699
  Epoch 31/60
Model trained in 1.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 71.421
  Epoch 32/60
Model trained in 1.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 71.360
  Epoch 33/60
Model trained in 1.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 71.266
  Epoch 34/60
Model trained in 1.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 72.790
  Epoch 35/60
Model trained in 1.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.317
  Epoch 36/60
Model trained in 1.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.886
  Epoch 37/60
Model trained in 1.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.436
  Epoch 38/60
Model trained in 1.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.561
  Epoch 39/60
Model trained in 1.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 72.419
  Epoch 40/60
Model trained in 1.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.342
  Epoch 41/60
Model trained in 1.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.014
  Epoch 42/60
Model trained in 1.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.021
  Epoch 43/60
Model trained in 1.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.414
  Early stopping triggered.

  best_val_SMAPE=71.266

Combination 135/144: {'encoder_hidden_size': 48, 'layers': 2, 'decoder_hidden_size': 32, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 10, 'batch_size': 64, 'sequence_length': 168, 'dropout': 0.0}
Time: 184.88 minutes - estimated total time: 197.21 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 32
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity']
  Epoch 1/60
Model trained in 1.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 178.843
  Epoch 2/60
Model trained in 1.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 169.224
  Epoch 3/60
Model trained in 1.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 161.047
  Epoch 4/60
Model trained in 1.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 153.933
  Epoch 5/60
Model trained in 1.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 147.579
  Epoch 6/60
Model trained in 1.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 141.733
  Epoch 7/60
Model trained in 1.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 136.336
  Epoch 8/60
Model trained in 1.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 131.209
  Epoch 9/60
Model trained in 1.95s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 126.295
  Epoch 10/60
Model trained in 1.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 121.812
  Epoch 11/60
Model trained in 1.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 117.564
  Epoch 12/60
Model trained in 1.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 113.568
  Epoch 13/60
Model trained in 1.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 109.744
  Epoch 14/60
Model trained in 1.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 106.632
  Epoch 15/60
Model trained in 1.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 103.475
  Epoch 16/60
Model trained in 1.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 100.281
  Epoch 17/60
Model trained in 1.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 97.258
  Epoch 18/60
Model trained in 1.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 96.028
  Epoch 19/60
Model trained in 1.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 95.183
  Epoch 20/60
Model trained in 1.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.725
  Epoch 21/60
Model trained in 1.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.260
  Epoch 22/60
Model trained in 1.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.106
  Epoch 23/60
Model trained in 1.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.993
  Epoch 24/60
Model trained in 1.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.498
  Epoch 25/60
Model trained in 1.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.021
  Epoch 26/60
Model trained in 1.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.782
  Epoch 27/60
Model trained in 1.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.910
  Epoch 28/60
Model trained in 1.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.719
  Epoch 29/60
Model trained in 1.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.287
  Epoch 30/60
Model trained in 1.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.237
  Epoch 31/60
Model trained in 1.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.425
  Epoch 32/60
Model trained in 1.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.279
  Epoch 33/60
Model trained in 1.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.479
  Epoch 34/60
Model trained in 1.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.386
  Epoch 35/60
Model trained in 1.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.062
  Epoch 36/60
Model trained in 1.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.586
  Epoch 37/60
Model trained in 1.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.059
  Epoch 38/60
Model trained in 1.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.940
  Epoch 39/60
Model trained in 1.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.161
  Epoch 40/60
Model trained in 1.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.019
  Epoch 41/60
Model trained in 1.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.597
  Epoch 42/60
Model trained in 1.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.906
  Early stopping triggered.

  best_val_SMAPE=76.279

Combination 136/144: {'encoder_hidden_size': 48, 'layers': 2, 'decoder_hidden_size': 32, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 10, 'batch_size': 64, 'sequence_length': 168, 'dropout': 0.2}
Time: 186.52 minutes - estimated total time: 197.49 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 32
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity']
  Epoch 1/60
Model trained in 1.97s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 178.836
  Epoch 2/60
Model trained in 1.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 169.217
  Epoch 3/60
Model trained in 1.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 161.040
  Epoch 4/60
Model trained in 1.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 153.927
  Epoch 5/60
Model trained in 1.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 147.573
  Epoch 6/60
Model trained in 1.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 141.728
  Epoch 7/60
Model trained in 1.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 136.331
  Epoch 8/60
Model trained in 1.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 132.606
  Epoch 9/60
Model trained in 1.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 126.980
  Epoch 10/60
Model trained in 2.08s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 123.012
  Epoch 11/60
Model trained in 1.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 117.932
  Epoch 12/60
Model trained in 1.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 114.501
  Epoch 13/60
Model trained in 1.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 111.282
  Epoch 14/60
Model trained in 1.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 107.676
  Epoch 15/60
Model trained in 1.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 105.523
  Epoch 16/60
Model trained in 1.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 102.261
  Epoch 17/60
Model trained in 1.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 98.996
  Epoch 18/60
Model trained in 1.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 96.988
  Epoch 19/60
Model trained in 1.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 96.343
  Epoch 20/60
Model trained in 1.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.597
  Epoch 21/60
Model trained in 1.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.928
  Epoch 22/60
Model trained in 1.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.280
  Epoch 23/60
Model trained in 1.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.352
  Epoch 24/60
Model trained in 1.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.565
  Epoch 25/60
Model trained in 1.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.058
  Epoch 26/60
Model trained in 1.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.779
  Epoch 27/60
Model trained in 1.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.877
  Epoch 28/60
Model trained in 1.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.310
  Epoch 29/60
Model trained in 1.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.909
  Epoch 30/60
Model trained in 1.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.848
  Epoch 31/60
Model trained in 1.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.334
  Epoch 32/60
Model trained in 1.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.404
  Epoch 33/60
Model trained in 1.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.014
  Epoch 34/60
Model trained in 1.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.985
  Epoch 35/60
Model trained in 1.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.519
  Epoch 36/60
Model trained in 1.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.287
  Epoch 37/60
Model trained in 1.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.887
  Epoch 38/60
Model trained in 1.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.782
  Epoch 39/60
Model trained in 1.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.653
  Early stopping triggered.

  best_val_SMAPE=80.909

Combination 137/144: {'encoder_hidden_size': 48, 'layers': 2, 'decoder_hidden_size': 48, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 10, 'batch_size': 32, 'sequence_length': 24, 'dropout': 0.0}
Time: 188.06 minutes - estimated total time: 197.67 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 32
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity']
  Epoch 1/60
Model trained in 2.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 161.026
  Epoch 2/60
Model trained in 2.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 141.846
  Epoch 3/60
Model trained in 2.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 126.571
  Epoch 4/60
Model trained in 2.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 113.495
  Epoch 5/60
Model trained in 2.62s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 103.926
  Epoch 6/60
Model trained in 2.63s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 96.286
  Epoch 7/60
Model trained in 2.57s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.001
  Epoch 8/60
Model trained in 2.59s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.082
  Epoch 9/60
Model trained in 2.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.668
  Epoch 10/60
Model trained in 2.67s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.819
  Epoch 11/60
Model trained in 2.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.357
  Epoch 12/60
Model trained in 2.65s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.222
  Epoch 13/60
Model trained in 2.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.135
  Epoch 14/60
Model trained in 2.63s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.747
  Epoch 15/60
Model trained in 2.65s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.852
  Epoch 16/60
Model trained in 2.55s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.584
  Epoch 17/60
Model trained in 2.55s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.640
  Epoch 18/60
Model trained in 2.63s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.671
  Epoch 19/60
Model trained in 2.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.589
  Epoch 20/60
Model trained in 2.65s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.969
  Epoch 21/60
Model trained in 2.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.020
  Epoch 22/60
Model trained in 2.59s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.030
  Epoch 23/60
Model trained in 2.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.300
  Epoch 24/60
Model trained in 2.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.959
  Epoch 25/60
Model trained in 2.56s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.592
  Epoch 26/60
Model trained in 2.59s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 72.179
  Epoch 27/60
Model trained in 2.65s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 72.281
  Epoch 28/60
Model trained in 2.63s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 70.998
  Epoch 29/60
Model trained in 2.68s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 70.294
  Epoch 30/60
Model trained in 2.61s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 69.794
  Epoch 31/60
Model trained in 2.58s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 70.356
  Epoch 32/60
Model trained in 2.57s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 70.338
  Epoch 33/60
Model trained in 2.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 70.773
  Epoch 34/60
Model trained in 2.68s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 71.914
  Epoch 35/60
Model trained in 2.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 72.178
  Epoch 36/60
Model trained in 2.68s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 72.003
  Epoch 37/60
Model trained in 2.67s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 72.136
  Epoch 38/60
Model trained in 2.63s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 71.494
  Epoch 39/60
Model trained in 2.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 71.793
  Epoch 40/60
Model trained in 2.51s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 72.548
  Early stopping triggered.

  best_val_SMAPE=69.794

Combination 138/144: {'encoder_hidden_size': 48, 'layers': 2, 'decoder_hidden_size': 48, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 10, 'batch_size': 32, 'sequence_length': 24, 'dropout': 0.2}
Time: 190.15 minutes - estimated total time: 198.41 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 32
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity']
  Epoch 1/60
Model trained in 2.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 161.017
  Epoch 2/60
Model trained in 2.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 141.838
  Epoch 3/60
Model trained in 2.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 126.572
  Epoch 4/60
Model trained in 2.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 113.550
  Epoch 5/60
Model trained in 2.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 103.008
  Epoch 6/60
Model trained in 2.68s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 96.350
  Epoch 7/60
Model trained in 2.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.376
  Epoch 8/60
Model trained in 2.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.451
  Epoch 9/60
Model trained in 2.59s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.588
  Epoch 10/60
Model trained in 2.59s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.272
  Epoch 11/60
Model trained in 2.60s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.798
  Epoch 12/60
Model trained in 2.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.969
  Epoch 13/60
Model trained in 2.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.229
  Epoch 14/60
Model trained in 2.68s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.634
  Epoch 15/60
Model trained in 2.65s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.859
  Epoch 16/60
Model trained in 2.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.912
  Epoch 17/60
Model trained in 2.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.445
  Epoch 18/60
Model trained in 2.63s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 98.315
  Epoch 19/60
Model trained in 2.56s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.525
  Epoch 20/60
Model trained in 2.60s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.266
  Epoch 21/60
Model trained in 2.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.573
  Early stopping triggered.

  best_val_SMAPE=80.798

Combination 139/144: {'encoder_hidden_size': 48, 'layers': 2, 'decoder_hidden_size': 48, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 10, 'batch_size': 32, 'sequence_length': 168, 'dropout': 0.0}
Time: 191.27 minutes - estimated total time: 198.15 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 32
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity']
  Epoch 1/60
Model trained in 2.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 161.245
  Epoch 2/60
Model trained in 2.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 142.094
  Epoch 3/60
Model trained in 2.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 126.872
  Epoch 4/60
Model trained in 2.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 142.287
  Epoch 5/60
Model trained in 2.67s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 103.704
  Epoch 6/60
Model trained in 2.68s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 95.221
  Epoch 7/60
Model trained in 2.59s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.247
  Epoch 8/60
Model trained in 2.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.601
  Epoch 9/60
Model trained in 2.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.722
  Epoch 10/60
Model trained in 2.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.746
  Epoch 11/60
Model trained in 2.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.416
  Epoch 12/60
Model trained in 2.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.873
  Epoch 13/60
Model trained in 2.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.649
  Epoch 14/60
Model trained in 2.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.333
  Epoch 15/60
Model trained in 2.67s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.257
  Epoch 16/60
Model trained in 2.63s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.860
  Epoch 17/60
Model trained in 2.67s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.092
  Epoch 18/60
Model trained in 2.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.440
  Epoch 19/60
Model trained in 2.67s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.168
  Epoch 20/60
Model trained in 2.68s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.679
  Epoch 21/60
Model trained in 2.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.867
  Epoch 22/60
Model trained in 2.62s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.383
  Epoch 23/60
Model trained in 2.68s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.757
  Epoch 24/60
Model trained in 2.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.601
  Epoch 25/60
Model trained in 2.63s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.499
  Epoch 26/60
Model trained in 2.68s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.486
  Epoch 27/60
Model trained in 2.68s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.892
  Early stopping triggered.

  best_val_SMAPE=85.092

Combination 140/144: {'encoder_hidden_size': 48, 'layers': 2, 'decoder_hidden_size': 48, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 10, 'batch_size': 32, 'sequence_length': 168, 'dropout': 0.2}
Time: 192.72 minutes - estimated total time: 198.23 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 32
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity']
  Epoch 1/60
Model trained in 2.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 161.236
  Epoch 2/60
Model trained in 2.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 142.087
  Epoch 3/60
Model trained in 2.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 126.867
  Epoch 4/60
Model trained in 2.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 115.612
  Epoch 5/60
Model trained in 2.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 104.686
  Epoch 6/60
Model trained in 2.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 97.227
  Epoch 7/60
Model trained in 2.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 94.474
  Epoch 8/60
Model trained in 2.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.704
  Epoch 9/60
Model trained in 2.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.638
  Epoch 10/60
Model trained in 2.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.679
  Epoch 11/60
Model trained in 2.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.784
  Epoch 12/60
Model trained in 2.63s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.292
  Epoch 13/60
Model trained in 2.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.126
  Epoch 14/60
Model trained in 2.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.145
  Epoch 15/60
Model trained in 2.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.622
  Epoch 16/60
Model trained in 2.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.455
  Epoch 17/60
Model trained in 2.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.996
  Epoch 18/60
Model trained in 2.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.181
  Epoch 19/60
Model trained in 2.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.059
  Epoch 20/60
Model trained in 2.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.357
  Epoch 21/60
Model trained in 2.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.731
  Epoch 22/60
Model trained in 2.59s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.929
  Epoch 23/60
Model trained in 2.62s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.301
  Epoch 24/60
Model trained in 2.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.944
  Epoch 25/60
Model trained in 2.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.016
  Epoch 26/60
Model trained in 2.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.853
  Epoch 27/60
Model trained in 2.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.158
  Epoch 28/60
Model trained in 2.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.050
  Epoch 29/60
Model trained in 2.68s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.302
  Epoch 30/60
Model trained in 2.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.755
  Epoch 31/60
Model trained in 2.65s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.348
  Epoch 32/60
Model trained in 2.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.028
  Epoch 33/60
Model trained in 2.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.013
  Epoch 34/60
Model trained in 2.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.204
  Epoch 35/60
Model trained in 2.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.807
  Epoch 36/60
Model trained in 2.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.437
  Epoch 37/60
Model trained in 2.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.375
  Early stopping triggered.

  best_val_SMAPE=73.158

Combination 141/144: {'encoder_hidden_size': 48, 'layers': 2, 'decoder_hidden_size': 48, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 10, 'batch_size': 64, 'sequence_length': 24, 'dropout': 0.0}
Time: 194.71 minutes - estimated total time: 198.85 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 32
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity']
  Epoch 1/60
Model trained in 1.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 173.739
  Epoch 2/60
Model trained in 1.61s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 161.002
  Epoch 3/60
Model trained in 1.61s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 150.660
  Epoch 4/60
Model trained in 1.68s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 141.751
  Epoch 5/60
Model trained in 1.57s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 133.825
  Epoch 6/60
Model trained in 1.59s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 126.429
  Epoch 7/60
Model trained in 1.63s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 119.382
  Epoch 8/60
Model trained in 1.61s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 115.584
  Epoch 9/60
Model trained in 1.58s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 111.772
  Epoch 10/60
Model trained in 1.58s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 108.009
  Epoch 11/60
Model trained in 1.62s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 103.617
  Epoch 12/60
Model trained in 1.63s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 101.358
  Epoch 13/60
Model trained in 1.67s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 100.400
  Epoch 14/60
Model trained in 1.62s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 102.665
  Epoch 15/60
Model trained in 1.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 101.664
  Epoch 16/60
Model trained in 1.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 100.639
  Epoch 17/60
Model trained in 1.57s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 104.016
  Epoch 18/60
Model trained in 1.54s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 103.829
  Epoch 19/60
Model trained in 1.60s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 99.051
  Epoch 20/60
Model trained in 1.61s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 99.031
  Epoch 21/60
Model trained in 1.59s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 98.690
  Epoch 22/60
Model trained in 1.57s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 100.578
  Epoch 23/60
Model trained in 1.59s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 98.210
  Epoch 24/60
Model trained in 1.56s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 98.767
  Epoch 25/60
Model trained in 1.57s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 94.661
  Epoch 26/60
Model trained in 1.60s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 96.454
  Epoch 27/60
Model trained in 1.62s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 96.951
  Epoch 28/60
Model trained in 1.63s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 96.305
  Epoch 29/60
Model trained in 1.61s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.934
  Epoch 30/60
Model trained in 1.60s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.014
  Epoch 31/60
Model trained in 1.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.804
  Epoch 32/60
Model trained in 1.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.426
  Epoch 33/60
Model trained in 1.60s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.153
  Epoch 34/60
Model trained in 1.56s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.695
  Epoch 35/60
Model trained in 1.53s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.890
  Epoch 36/60
Model trained in 1.54s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.656
  Epoch 37/60
Model trained in 1.54s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.920
  Epoch 38/60
Model trained in 1.59s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.498
  Epoch 39/60
Model trained in 1.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.797
  Epoch 40/60
Model trained in 1.59s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.011
  Epoch 41/60
Model trained in 1.60s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.642
  Epoch 42/60
Model trained in 1.56s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.476
  Epoch 43/60
Model trained in 1.62s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.343
  Epoch 44/60
Model trained in 1.62s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.329
  Epoch 45/60
Model trained in 1.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 71.938
  Epoch 46/60
Model trained in 1.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 72.013
  Epoch 47/60
Model trained in 1.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 71.819
  Epoch 48/60
Model trained in 1.63s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 71.726
  Epoch 49/60
Model trained in 1.62s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 71.611
  Epoch 50/60
Model trained in 1.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 71.934
  Epoch 51/60
Model trained in 1.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 71.708
  Epoch 52/60
Model trained in 1.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 72.458
  Epoch 53/60
Model trained in 1.61s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 72.667
  Epoch 54/60
Model trained in 1.56s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.273
  Epoch 55/60
Model trained in 1.58s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.197
  Epoch 56/60
Model trained in 1.55s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.590
  Epoch 57/60
Model trained in 1.62s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.311
  Epoch 58/60
Model trained in 1.63s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.482
  Epoch 59/60
Model trained in 1.62s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.290
  Early stopping triggered.

  best_val_SMAPE=71.611

Combination 142/144: {'encoder_hidden_size': 48, 'layers': 2, 'decoder_hidden_size': 48, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 10, 'batch_size': 64, 'sequence_length': 24, 'dropout': 0.2}
Time: 196.76 minutes - estimated total time: 199.53 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 32
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity']
  Epoch 1/60
Model trained in 1.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 173.732
  Epoch 2/60
Model trained in 1.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 160.994
  Epoch 3/60
Model trained in 1.68s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 150.654
  Epoch 4/60
Model trained in 1.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 141.744
  Epoch 5/60
Model trained in 1.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 133.811
  Epoch 6/60
Model trained in 1.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 126.410
  Epoch 7/60
Model trained in 1.63s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 119.688
  Epoch 8/60
Model trained in 1.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 114.093
  Epoch 9/60
Model trained in 1.61s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 108.979
  Epoch 10/60
Model trained in 1.59s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 103.544
  Epoch 11/60
Model trained in 1.63s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 99.084
  Epoch 12/60
Model trained in 1.61s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 95.183
  Epoch 13/60
Model trained in 1.63s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.122
  Epoch 14/60
Model trained in 1.55s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.751
  Epoch 15/60
Model trained in 1.52s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.956
  Epoch 16/60
Model trained in 1.58s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.077
  Epoch 17/60
Model trained in 1.63s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.901
  Epoch 18/60
Model trained in 1.67s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.655
  Epoch 19/60
Model trained in 1.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.556
  Epoch 20/60
Model trained in 1.63s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 72.192
  Epoch 21/60
Model trained in 1.61s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 70.489
  Epoch 22/60
Model trained in 1.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 69.873
  Epoch 23/60
Model trained in 1.65s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 69.259
  Epoch 24/60
Model trained in 1.61s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 69.604
  Epoch 25/60
Model trained in 1.61s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 69.916
  Epoch 26/60
Model trained in 1.60s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 70.196
  Epoch 27/60
Model trained in 1.61s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 70.488
  Epoch 28/60
Model trained in 1.60s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 70.539
  Epoch 29/60
Model trained in 1.59s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 70.497
  Epoch 30/60
Model trained in 1.62s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 70.988
  Epoch 31/60
Model trained in 1.58s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 71.005
  Epoch 32/60
Model trained in 1.60s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 70.921
  Epoch 33/60
Model trained in 1.57s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 70.873
  Early stopping triggered.

  best_val_SMAPE=69.259

Combination 143/144: {'encoder_hidden_size': 48, 'layers': 2, 'decoder_hidden_size': 48, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 10, 'batch_size': 64, 'sequence_length': 168, 'dropout': 0.0}
Time: 197.93 minutes - estimated total time: 199.31 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 32
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity']
  Epoch 1/60
Model trained in 1.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 173.812
  Epoch 2/60
Model trained in 1.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 161.103
  Epoch 3/60
Model trained in 1.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 150.788
  Epoch 4/60
Model trained in 1.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 141.907
  Epoch 5/60
Model trained in 1.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 134.000
  Epoch 6/60
Model trained in 1.97s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 126.699
  Epoch 7/60
Model trained in 1.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 120.107
  Epoch 8/60
Model trained in 1.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 113.937
  Epoch 9/60
Model trained in 1.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 108.270
  Epoch 10/60
Model trained in 1.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 103.837
  Epoch 11/60
Model trained in 1.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 99.656
  Epoch 12/60
Model trained in 1.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 96.003
  Epoch 13/60
Model trained in 1.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.710
  Epoch 14/60
Model trained in 1.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.041
  Epoch 15/60
Model trained in 1.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.940
  Epoch 16/60
Model trained in 1.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.085
  Epoch 17/60
Model trained in 1.68s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.396
  Epoch 18/60
Model trained in 1.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.474
  Epoch 19/60
Model trained in 1.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.636
  Epoch 20/60
Model trained in 1.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.039
  Epoch 21/60
Model trained in 1.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.187
  Epoch 22/60
Model trained in 1.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.174
  Epoch 23/60
Model trained in 1.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.603
  Epoch 24/60
Model trained in 1.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.103
  Epoch 25/60
Model trained in 1.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.139
  Epoch 26/60
Model trained in 1.67s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.631
  Epoch 27/60
Model trained in 1.68s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.031
  Epoch 28/60
Model trained in 1.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.077
  Epoch 29/60
Model trained in 1.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.735
  Epoch 30/60
Model trained in 1.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.351
  Epoch 31/60
Model trained in 1.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.785
  Epoch 32/60
Model trained in 1.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.795
  Epoch 33/60
Model trained in 1.67s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.864
  Early stopping triggered.

  best_val_SMAPE=77.603

Combination 144/144: {'encoder_hidden_size': 48, 'layers': 2, 'decoder_hidden_size': 48, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 10, 'batch_size': 64, 'sequence_length': 168, 'dropout': 0.2}
Time: 199.16 minutes - estimated total time: 199.16 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 32
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity']
  Epoch 1/60
Model trained in 1.98s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 173.804
  Epoch 2/60
Model trained in 1.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 161.095
  Epoch 3/60
Model trained in 1.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 150.781
  Epoch 4/60
Model trained in 1.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 141.900
  Epoch 5/60
Model trained in 1.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 134.005
  Epoch 6/60
Model trained in 1.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 126.641
  Epoch 7/60
Model trained in 1.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 119.810
  Epoch 8/60
Model trained in 1.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 114.790
  Epoch 9/60
Model trained in 1.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 111.567
  Epoch 10/60
Model trained in 1.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 106.785
  Epoch 11/60
Model trained in 1.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 102.609
  Epoch 12/60
Model trained in 1.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 99.219
  Epoch 13/60
Model trained in 1.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 96.057
  Epoch 14/60
Model trained in 1.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.027
  Epoch 15/60
Model trained in 1.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.881
  Epoch 16/60
Model trained in 1.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.746
  Epoch 17/60
Model trained in 1.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.693
  Epoch 18/60
Model trained in 1.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.377
  Epoch 19/60
Model trained in 1.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.459
  Epoch 20/60
Model trained in 1.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.036
  Epoch 21/60
Model trained in 1.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.542
  Epoch 22/60
Model trained in 1.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.822
  Epoch 23/60
Model trained in 1.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.113
  Epoch 24/60
Model trained in 1.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.955
  Epoch 25/60
Model trained in 1.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.782
  Epoch 26/60
Model trained in 1.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.448
  Epoch 27/60
Model trained in 1.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.609
  Epoch 28/60
Model trained in 1.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.939
  Epoch 29/60
Model trained in 1.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.821
  Epoch 30/60
Model trained in 1.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.851
  Early stopping triggered.

  best_val_SMAPE=82.036

Results saved to: c:\Users\n_and\OneDrive\Delt skrivebord\Data Science\Speciale\Energinet\Delte scripts\Speciale_Kode\Deep learners\LSTM Autoencoder\DK1_lstm_ae_search_results_2.csv

,fe_latent_dim,fe_dense_layers,enc_hidden_size,enc_layers,dec_hidden_size,encoder_hidden_size,layers,decoder_hidden_size,learning_rate,max_epochs,...,avg_daily_rmse,avg_daily_mae,avg_daily_smape,avg_smape_day_1,avg_smape_day_2,avg_smape_day_3,avg_smape_day_4,avg_smape_day_5,avg_smape_day_6,avg_smape_day_7
44,48,1,32,1,48,32,1,48,0.001,60,...,235.706736,203.647877,64.966176,58.773976,41.805386,46.737987,57.492625,66.027041,83.719662,100.206553
45,48,1,32,1,48,32,1,48,0.001,60,...,229.954432,196.254736,65.131135,64.200804,42.458226,38.830595,54.601942,66.167897,86.010769,103.647708
4,48,1,16,1,32,16,1,32,0.001,60,...,232.648581,204.880818,65.796253,60.830447,41.708680,36.926446,57.400812,69.341050,85.720694,108.645641
23,48,1,16,2,32,16,2,32,0.001,60,...,227.850522,199.247940,66.541318,61.313756,44.000359,38.808087,56.705003,71.003377,87.331083,106.627564
91,48,1,48,2,16,48,2,16,0.001,60,...,240.523340,207.304739,66.904494,60.186715,44.403284,55.375297,64.452800,65.666230,84.209903,94.037232
20,48,1,16,2,32,16,2,32,0.001,60,...,238.849481,208.165635,67.015614,61.212212,46.963017,39.640465,55.621166,72.732356,81.802412,111.137670
10,48,1,16,1,48,16,1,48,0.001,60,...,240.159701,208.170218,67.142702,67.237162,44.022243,43.280125,58.402689,65.656897,85.938457,105.461338
1,48,1,16,1,16,16,1,16,0.001,60,...,240.389645,206.697420,67.461661,57.553599,45.667028,49.081439,61.699088,67.949042,82.698480,107.582954
11,48,1,16,1,48,16,1,48,0.001,60,...,239.433466,206.881508,67.927568,64.487616,45.300430,43.162961,58.943477,69.109259,88.258781,106.230453
95,48,1,48,2,32,48,2,32,0.001,60,...,246.501370,217.882322,68.275797,70.018507,51.446428,39.376910,55.117551,66.270401,85.745081,109.955705

## Train final model

In [ ]:

import copy
import numpy as np
import pandas as pd
from pathlib import Path
import wandb
import tempfile
import joblib
from sklearn.preprocessing import StandardScaler
from Modules.Validation3_AE import run_cross_validation

# =====================================================================================
# Stage 3 – Train final LSTM Autoencoder
#
# Parameters are taken from the best Stage 2 row (results_df).
# The pretrained feature encoder from Stage 1 is loaded UNFROZEN so all weights
# can fine-tune together end-to-end.
# =====================================================================================

# ---------------------------------------------------------------------------
# Validate prerequisites
# ---------------------------------------------------------------------------
required_globals = [
    "dataset_train", "dataset_train_input", "dataset_validation",
    "dataset_context", "INCLUDE_REMAINING_2024_DURING_TRAINING",
    "INCLUDE_LAGS", "USE_FORECASTED_HISTORY",
    "results_df",                          # Stage 2 search results
    "best_stage1_encoder_state_dict",      # pretrained encoder weights from Stage 1
    "best_stage1_params",                  # Stage 1 best latent_dim / dense_layers
]
missing_globals = [name for name in required_globals if name not in globals()]
if missing_globals:
    raise ValueError(
        f"Missing prerequisites – run Stage 1 and Stage 2 first. "
        f"Missing: {missing_globals}"
    )

if dataset_train.empty:
    raise ValueError("Prepared dataset_train is empty; cannot train final model.")
if dataset_validation.empty:
    raise ValueError("dataset_validation is empty; cannot run final training with early stopping.")
if best_stage1_encoder_state_dict is None:
    raise ValueError("best_stage1_encoder_state_dict is None. Re-run Stage 1.")

# ---------------------------------------------------------------------------
# Derive parameters from the best Stage 2 row
# ---------------------------------------------------------------------------
best_stage2_row = results_df.iloc[0]

params = {
    # Feature encoder shape – fixed from Stage 1
    "latent_dim":            int(best_stage1_params["latent_dim"]),
    "dense_layers":          int(best_stage1_params["dense_layers"]),
    # LSTM / training – from Stage 2 best
    "encoder_hidden_size":   int(best_stage2_row["encoder_hidden_size"]),
    "decoder_hidden_size":   int(best_stage2_row["decoder_hidden_size"]),
    "layers":                int(best_stage2_row["layers"]),
    "learning_rate":         float(best_stage2_row["learning_rate"]),
    "batch_size":            int(best_stage2_row["batch_size"]),
    "sequence_length":       int(best_stage2_row["sequence_length"]),
    "dropout":               float(best_stage2_row["dropout"]),
}

print("=== Stage 3 parameters (derived from Stage 1 + Stage 2 best) ===")
for k, v in params.items():
    print(f"  {k}: {v}")
print(f"  (Stage 2 best avg_smape: {float(best_stage2_row['avg_smape']):.4f})")

# ---------------------------------------------------------------------------
# Config
# ---------------------------------------------------------------------------
PREDICT_PERIOD = 4 * 168
MAX_EPOCHS = 80
PATIENCE = 30
MIN_DELTA = 0.0
WANDB_PROJECT = "LSTM_AE_final"
WANDB_RUN_NAME = (
    f"{PRICE_ZONE}_LSTM_AE_{TRAIN_WINDOW//8760}y_"
    f"2024{'incl' if INCLUDE_REMAINING_2024_DURING_TRAINING else 'excl'}"
    f"_DKPriceLag1{'_incl' if INCLUDE_PRICE_LAG1_AS_INPUT else '_excl'}"
    f"_lags{'_incl' if INCLUDE_LAGS else '_excl'}"
    f"_{PREDICT_PERIOD//168}val"
)
save_model_to_wandb = True
save_model_to_disk = False

feature_columns = [c for c in dataset_train_input.columns if c not in ["Time", "DKPrice"]]
if not feature_columns:
    raise ValueError("No feature columns found in dataset_train_input.")

output_root = Path(project_root) / "Deep learners" / "LSTM Autoencoder"
output_root.mkdir(parents=True, exist_ok=True)

# ---------------------------------------------------------------------------
# W&B run
# ---------------------------------------------------------------------------
run = wandb.init(
    project=WANDB_PROJECT,
    name=WANDB_RUN_NAME,
    config={
        "price_zone": PRICE_ZONE,
        "train_window": int(TRAIN_WINDOW),
        "training_rows": int(len(dataset_train)),
        "validation_rows": int(len(dataset_validation)),
        "train_start_time": str(dataset_train["Time"].min()),
        "train_end_time": str(dataset_train["Time"].max()),
        "val_start": VAL_START,
        "val_window": int(VAL_WINDOW),
        "predict_period": int(PREDICT_PERIOD),
        "stride": int(STRIDE),
        "include_remaining_2024_in_prepared_train_data": bool(INCLUDE_REMAINING_2024_DURING_TRAINING),
        "include_lags": bool(INCLUDE_LAGS),
        "use_forecasted_history": bool(USE_FORECASTED_HISTORY),
        "max_epochs": MAX_EPOCHS,
        "patience": PATIENCE,
        "min_delta": MIN_DELTA,
        "save_model_to_wandb": bool(save_model_to_wandb),
        "decoder_horizon": 168,
        "stage1_recon_smape": float(best_stage1_val_smape),
        "stage2_best_val_smape": float(best_stage2_row["avg_smape"]),
        "encoder_pretrained": True,
        "encoder_frozen": False,
        **params,
    },
    tags=["lstm-ae", "final-model", "early-stopping", "pretrained-encoder", "unfrozen-encoder"],
    reinit=True,
    settings=wandb.Settings(start_method="thread"),
)

print(f"\nTraining rows: {len(dataset_train)}")
print(f"Training window: {dataset_train['Time'].min()} -> {dataset_train['Time'].max()}")
print(f"Validation rows: {len(dataset_validation)}")
print(f"Include remainder_2024_for_train: {INCLUDE_REMAINING_2024_DURING_TRAINING}")
print(f"Include lag features: {INCLUDE_LAGS}")
print(f"Use forecasted history: {USE_FORECASTED_HISTORY}")
print(f"Feature columns (decoder, {len(feature_columns)}): {feature_columns}")

# ---------------------------------------------------------------------------
# Build model – load pretrained encoder UNFROZEN (freeze=False) so all weights
# fine-tune end-to-end during Stage 3.
# ---------------------------------------------------------------------------
model = TorchLSTMAERegressor(
    latent_dim=params["latent_dim"],
    encoder_hidden_size=params["encoder_hidden_size"],
    decoder_hidden_size=params["decoder_hidden_size"],
    layers=params["layers"],
    dense_layers=params["dense_layers"],
    learning_rate=params["learning_rate"],
    epochs=1,
    batch_size=params["batch_size"],
    sequence_length=params["sequence_length"],
    dropout=params["dropout"],
    random_state=42,
    log_epoch_metrics=True,
    log_prefix="final_",
    warm_start=True,
)

# Load pretrained encoder weights but keep them trainable (freeze=False)
model.set_pretrained_encoder(best_stage1_encoder_state_dict, freeze=False)

# ---------------------------------------------------------------------------
# Training loop with early stopping
# ---------------------------------------------------------------------------
best_val_smape = float("inf")
best_epoch = 0
patience_counter = 0
best_model = None
epoch_history = []

for epoch in range(1, MAX_EPOCHS + 1):
    print(f"\nEpoch {epoch}/{MAX_EPOCHS}")

    epoch_results = run_cross_validation(
        model=model,
        dataset_train=dataset_train,
        dataset_validation=dataset_validation,
        dataset_context=dataset_context,
        feature_columns=feature_columns,
        include_remaining_2024=INCLUDE_REMAINING_2024_DURING_TRAINING,
        dk_zone=PRICE_ZONE,
        split_setup=2,
        train_window=TRAIN_WINDOW,
        val_window=VAL_WINDOW,
        val_start=VAL_START,
        predict_period=PREDICT_PERIOD,
        stride=STRIDE,
        use_scaler=True,
        print_fold_results=False,
        plot=False,
        rf_models=rf_models,
        use_precomputed_feature_values=use_precomputed_feature_values,
        precomputed_feature_predictions=feature_predictions,
        use_forecasted_history=USE_FORECASTED_HISTORY,
    )

    train_mse = float(model.epoch_losses_[-1]) if hasattr(model, "epoch_losses_") else float("nan")
    train_smape = float(model.epoch_smapes_[-1]) if hasattr(model, "epoch_smapes_") else float("nan")
    val_smape = float(epoch_results["overall_avg_weekly_smape"])

    improved = val_smape < (best_val_smape - MIN_DELTA)
    if improved:
        best_val_smape = val_smape
        best_epoch = epoch
        patience_counter = 0
        best_model = copy.deepcopy(model)
        print(f"  Validation SMAPE improved: {val_smape:.4f} (best so far)")
    else:
        patience_counter += 1
        print(f"  Validation SMAPE: {val_smape:.4f} (patience {patience_counter}/{PATIENCE})")

    epoch_row = {
        "epoch": epoch,
        "train_MSE": train_mse,
        "train_SMAPE": train_smape,
        "val_SMAPE": val_smape,
        "best_val_SMAPE": best_val_smape,
        "patience_counter": int(patience_counter),
    }
    epoch_history.append(epoch_row)
    wandb.log(epoch_row)

    if patience_counter >= PATIENCE:
        print(f"\nEarly stopping triggered at epoch {epoch}. Best epoch: {best_epoch}.")
        break

if best_epoch == 0:
    raise RuntimeError("No valid epoch found during final training with early stopping.")

print(f"\n=== Stage 3 Training Complete ===")
print(f"Best epoch: {best_epoch}")
print(f"Best validation SMAPE: {best_val_smape:.4f}")

final_model = best_model

epoch_metrics_df = pd.DataFrame(epoch_history)
wandb.log({"final_epoch_metrics": wandb.Table(dataframe=epoch_metrics_df)})
wandb.log({
    "best_epoch": int(best_epoch),
    "best_val_smape": float(best_val_smape),
})
run.summary.update({
    "best_epoch": int(best_epoch),
    "best_val_smape": float(best_val_smape),
    "epochs_trained": int(epoch),
})

if save_model_to_wandb:
    model_artifact = wandb.Artifact(name=f"{WANDB_RUN_NAME}_model", type="model")
    with tempfile.TemporaryDirectory() as tmpdir:
        model_path = Path(tmpdir) / f"{WANDB_RUN_NAME}_model.joblib"
        joblib.dump(final_model, model_path, compress=3)
        model_artifact.add_file(str(model_path), name="model.joblib")
        run.log_artifact(model_artifact)
    print("Model stored in W&B artifact.")
else:
    print("Model not saved to W&B. Set save_model_to_wandb = True to upload it.")

print(f"Trained final LSTM AE on the prepared {PRICE_ZONE} train set (best epoch: {best_epoch}).")

wandb.finish()

=== Stage 3 parameters (derived from Stage 1 + Stage 2 best) ===
  latent_dim: 48
  dense_layers: 1
  encoder_hidden_size: 16
  decoder_hidden_size: 32
  layers: 2
  learning_rate: 0.001
  batch_size: 64
  sequence_length: 24
  dropout: 0.2
  (Stage 2 best avg_smape: 70.9189)

Training rows: 22944
Training window: 2022-01-01 00:00:00 -> 2024-12-31 23:00:00
Validation rows: 2688
Include remainder_2024_for_train: True
Include lag features: False
Use forecasted history: True
Feature columns (decoder, 33): ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']

Epoch 1/80
Model trained in 1.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 182.245
  Validation SMAPE improved: 182.2450 (best so far)

Epoch 2/80

Model trained in 1.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 173.020
  Validation SMAPE improved: 173.0198 (best so far)

Epoch 3/80
Model trained in 1.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 164.970
  Validation SMAPE improved: 164.9697 (best so far)

Epoch 4/80
Model trained in 1.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 157.841
  Validation SMAPE improved: 157.8415 (best so far)

Epoch 5/80
Model trained in 1.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 151.295
  Validation SMAPE improved: 151.2952 (best so far)

Epoch 6/80
Model trained in 1.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 145.199
  Validation SMAPE improved: 145.1988 (best so far)

Epoch 7/80
Model trained in 1.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 139.537
  Validation SMAPE improved: 139.5370 (best so far)

Epoch 8/80
Model trained in 1.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 134.251
  Validation SMAPE improved: 134.2507 (best so far)

Epoch 9/80
Model trained in 1.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 129.363
  Validation SMAPE improved: 129.3631 (best so far)

Epoch 10/80
Model trained in 1.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 126.158
  Validation SMAPE improved: 126.1583 (best so far)

Epoch 11/80
Model trained in 1.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 123.346
  Validation SMAPE improved: 123.3461 (best so far)

Epoch 12/80
Model trained in 1.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 118.970
  Validation SMAPE improved: 118.9696 (best so far)

Epoch 13/80
Model trained in 1.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 115.104
  Validation SMAPE improved: 115.1043 (best so far)

Epoch 14/80
Model trained in 1.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 111.122
  Validation SMAPE improved: 111.1222 (best so far)

Epoch 15/80
Model trained in 1.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 108.563
  Validation SMAPE improved: 108.5631 (best so far)

Epoch 16/80
Model trained in 1.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 105.498
  Validation SMAPE improved: 105.4983 (best so far)

Epoch 17/80
Model trained in 1.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 102.015
  Validation SMAPE improved: 102.0151 (best so far)

Epoch 18/80
Model trained in 1.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 99.799
  Validation SMAPE improved: 99.7994 (best so far)

Epoch 19/80
Model trained in 1.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 98.007
  Validation SMAPE improved: 98.0075 (best so far)

Epoch 20/80
Model trained in 1.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 96.137
  Validation SMAPE improved: 96.1374 (best so far)

Epoch 21/80
Model trained in 1.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 95.159
  Validation SMAPE improved: 95.1591 (best so far)

Epoch 22/80
Model trained in 1.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.452
  Validation SMAPE improved: 93.4522 (best so far)

Epoch 23/80
Model trained in 1.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.184
  Validation SMAPE improved: 93.1842 (best so far)

Epoch 24/80
Model trained in 1.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.408
  Validation SMAPE improved: 90.4079 (best so far)

Epoch 25/80
Model trained in 1.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.302
  Validation SMAPE improved: 87.3015 (best so far)

Epoch 26/80
Model trained in 1.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.485
  Validation SMAPE improved: 84.4848 (best so far)

Epoch 27/80
Model trained in 1.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.002
  Validation SMAPE: 86.0021 (patience 1/30)

Epoch 28/80
Model trained in 1.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.970
  Validation SMAPE: 87.9700 (patience 2/30)

Epoch 29/80
Model trained in 1.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.828
  Validation SMAPE: 89.8279 (patience 3/30)

Epoch 30/80
Model trained in 1.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.473
  Validation SMAPE: 89.4732 (patience 4/30)

Epoch 31/80
Model trained in 1.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.784
  Validation SMAPE: 91.7844 (patience 5/30)

Epoch 32/80
Model trained in 1.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.665
  Validation SMAPE: 93.6650 (patience 6/30)

Epoch 33/80
Model trained in 1.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.883
  Validation SMAPE: 92.8827 (patience 7/30)

Epoch 34/80
Model trained in 1.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.483
  Validation SMAPE: 92.4833 (patience 8/30)

Epoch 35/80
Model trained in 1.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.924
  Validation SMAPE: 92.9245 (patience 9/30)

Epoch 36/80
Model trained in 1.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.832
  Validation SMAPE: 93.8325 (patience 10/30)

Epoch 37/80
Model trained in 1.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 95.612
  Validation SMAPE: 95.6123 (patience 11/30)

Epoch 38/80
Model trained in 1.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 96.737
  Validation SMAPE: 96.7367 (patience 12/30)

Epoch 39/80
Model trained in 1.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 96.836
  Validation SMAPE: 96.8358 (patience 13/30)

Epoch 40/80
Model trained in 1.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 94.993
  Validation SMAPE: 94.9927 (patience 14/30)

Epoch 41/80
Model trained in 1.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 94.521
  Validation SMAPE: 94.5211 (patience 15/30)

Epoch 42/80
Model trained in 1.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 94.120
  Validation SMAPE: 94.1195 (patience 16/30)

Epoch 43/80
Model trained in 1.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.588
  Validation SMAPE: 91.5875 (patience 17/30)

Epoch 44/80
Model trained in 1.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.431
  Validation SMAPE: 91.4310 (patience 18/30)

Epoch 45/80
Model trained in 1.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.189
  Validation SMAPE: 92.1886 (patience 19/30)

Epoch 46/80
Model trained in 1.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.624
  Validation SMAPE: 90.6242 (patience 20/30)

Epoch 47/80
Model trained in 1.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.014
  Validation SMAPE: 91.0136 (patience 21/30)

Epoch 48/80
Model trained in 1.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.713
  Validation SMAPE: 89.7127 (patience 22/30)

Epoch 49/80
Model trained in 1.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.121
  Validation SMAPE: 88.1210 (patience 23/30)

Epoch 50/80
Model trained in 1.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.488
  Validation SMAPE: 87.4882 (patience 24/30)

Epoch 51/80
Model trained in 1.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.922
  Validation SMAPE: 85.9215 (patience 25/30)

Epoch 52/80
Model trained in 1.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.811
  Validation SMAPE: 85.8114 (patience 26/30)

Epoch 53/80
Model trained in 1.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.441
  Validation SMAPE: 85.4407 (patience 27/30)

Epoch 54/80
Model trained in 1.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.634
  Validation SMAPE: 85.6338 (patience 28/30)

Epoch 55/80
Model trained in 1.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.542
  Validation SMAPE: 85.5420 (patience 29/30)

Epoch 56/80
Model trained in 1.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.957
  Validation SMAPE: 85.9569 (patience 30/30)

Early stopping triggered at epoch 56. Best epoch: 26.

=== Stage 3 Training Complete ===
Best epoch: 26
Best validation SMAPE: 84.4848
Model stored in W&B artifact.
Trained final LSTM AE on the prepared DK1 train set (best epoch: 26).

Test Final Model

In [ ]:
# Fit scaler on the same training tail used during training.
train_for_scaler = history_source.sort_values("Time").copy()
train_for_scaler = train_for_scaler.tail(TRAIN_WINDOW).reset_index(drop=True)
# DKPrice_lag1 is stored as Price_lag1 in raw source DataFrames; rename to match feature_columns.
if "DKPrice_lag1" not in train_for_scaler.columns and "Price_lag1" in train_for_scaler.columns:
    train_for_scaler["DKPrice_lag1"] = train_for_scaler["Price_lag1"]
X_scaler = train_for_scaler[feature_columns].astype(np.float32)
scaler = StandardScaler()
scaler.fit(X_scaler)

wandb: WARNING `start_method` is deprecated and will be removed in a future version of wandb. This setting is currently non-functional and safely ignored.
wandb: Currently logged in as: nande24 (Energinet_speciale) to https://api.wandb.ai. Use `wandb login --relogin` to force relogin
wandb: WARNING Using a boolean value for 'reinit' is deprecated. Use 'return_previous' or 'finish_previous' instead.

wandb:   1 of 1 files downloaded.

Loaded model artifact: DK1_LSTM_AE_2y_2024incl_DKPriceLag1_incl_lags_excl_4val_model:latest
Test window: 2025-01-01 00:00:00 -> 2025-12-31 23:00:00 (8760 rows)
Feature columns (decoder, 33): ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']

KeyError: "['DKPrice_lag1'] not in index"

Shap analysis

In [ ]:

import gc
from pathlib import Path

import joblib
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import psutil
import shap
import wandb

# ==========================
# SHAP configuration (LSTM AE)
# Note: predict() uses a constant-feature decoder with zero encoder baseline.
# SHAP values reflect sensitivity of the mean predicted price to each decoder
# feature value held constant across the 168-hour horizon.
# ==========================
quick_mode = False
eval_size = 300            # evaluation sample size
bg_size = 150              # background sample size for KernelExplainer
chunk_size = 25            # lower if memory/runtime is high
nsamples = 100             # SHAP Monte Carlo samples per explained point
include_beeswarm = True
include_waterfall = True

PRICE_ZONE = globals().get("PRICE_ZONE", "DK1")
WANDB_PROJECT = globals().get("WANDB_PROJECT", "LSTM_AE")
WANDB_RUN_NAME = WANDB_RUN_NAME  # Must match the final training run name from Stage 3
WANDB_RUN_NAME = "DK1_LSTM_AE_2y_2024incl_DKPriceLag1_excl_lags_excl_4val"
WANDB_ARTIFACT_NAME = f"{WANDB_RUN_NAME}_model"
WANDB_SHAP_RUN_NAME = f"{PRICE_ZONE}_lstm_ae_shap"


# Use dataset_train_input (feature columns only, no DKPrice) as the SHAP background/eval set.
if "dataset_train_input" not in globals() or dataset_train_input is None:
    raise ValueError("Missing dataset_train_input. Run the data loading cell first.")

feature_columns = [c for c in dataset_train_input.columns if c not in ["Time", "DKPrice"]]
if not feature_columns:
    raise ValueError("No feature columns found in dataset_train_input after removing ['Time', 'DKPrice'].")

X_train_shap = dataset_train_input.loc[:, feature_columns].copy()
if len(X_train_shap) == 0:
    raise ValueError("No rows found in dataset_train_input for SHAP analysis.")

X_train_shap = X_train_shap.astype(np.float32, copy=False)

# Start a dedicated W&B run for SHAP and load latest model artifact
wandb_run = wandb.init(
    project=WANDB_PROJECT,
    name=WANDB_SHAP_RUN_NAME,
    job_type="shap-analysis",
    config={
        "price_zone": PRICE_ZONE,
        "train_hours": int(TRAIN_WINDOW),
        "artifact_name": WANDB_ARTIFACT_NAME,
        "eval_size_requested": int(eval_size),
        "bg_size_requested": int(bg_size),
        "nsamples": int(nsamples),
    },
    reinit=True,
    settings=wandb.Settings(start_method="thread"),
)

model_artifact = wandb_run.use_artifact(f"{WANDB_ARTIFACT_NAME}:latest")
artifact_dir = Path(model_artifact.download())
model_path = artifact_dir / "model.joblib"
if not model_path.exists():
    raise ValueError(f"Could not find model.joblib in downloaded artifact: {artifact_dir}")

model = joblib.load(model_path)
print(f"Loaded LSTM AE model artifact: {WANDB_ARTIFACT_NAME}:latest")

mem = psutil.virtual_memory()
print(f"Available RAM before SHAP: {mem.available / (1024**3):.2f} GB")
print(f"Training set size for SHAP: {len(X_train_shap)} samples")
print(f"Number of features: {len(feature_columns)}")

if quick_mode:
    bg_size = min(30, len(X_train_shap))
    eval_size = min(60, len(X_train_shap))
    chunk_size = 10
    nsamples = 50
else:
    bg_size = min(bg_size, len(X_train_shap))
    eval_size = min(eval_size, len(X_train_shap))
    chunk_size = max(1, min(chunk_size, eval_size))

X_bg = shap.sample(X_train_shap, bg_size, random_state=42)
X_eval = shap.sample(X_train_shap, eval_size, random_state=42)

print(f"\nBackground sample size (X_bg): {len(X_bg)}")
print(f"Evaluation sample size (X_eval): {len(X_eval)}")
print(f"Chunk size: {chunk_size}")
print(f"Kernel SHAP nsamples: {nsamples}")

def predict_fn(x):
    x_df = pd.DataFrame(x, columns=feature_columns)
    preds = model.predict(x_df)
    return np.asarray(preds).reshape(-1)

explainer = shap.KernelExplainer(predict_fn, X_bg.values)

# Compute SHAP values in chunks and print progress
shap_chunks = []
n_chunks = (len(X_eval) + chunk_size - 1) // chunk_size
for idx, start in enumerate(range(0, len(X_eval), chunk_size), start=1):
    stop = min(start + chunk_size, len(X_eval))
    print(f"Computing SHAP chunk {idx}/{n_chunks} (rows {start}:{stop})...", flush=True)
    X_chunk = X_eval.iloc[start:stop]
    shap_chunk = explainer.shap_values(X_chunk.values, nsamples=nsamples)
    shap_chunks.append(np.asarray(shap_chunk))

shap_values = np.vstack(shap_chunks)
gc.collect()

print("\nSHAP analysis complete.")

# Global importance bar plot
plt.figure(figsize=(12, 6))
shap.summary_plot(shap_values, X_eval, plot_type="bar", show=False)
plt.tight_layout()
wandb_run.log({"shap_bar": wandb.Image(plt.gcf())})
plt.show()
plt.close()

# Beeswarm plot
if include_beeswarm:
    plt.figure(figsize=(12, 8))
    shap.summary_plot(shap_values, X_eval, show=False)
    plt.tight_layout()
    wandb_run.log({"shap_beeswarm": wandb.Image(plt.gcf())})
    plt.show()
    plt.close()

# Waterfall plot for first sample
if include_waterfall:
    i = 0
    base_value = float(np.mean(predict_fn(X_bg.values)))
    explanation = shap.Explanation(
        values=shap_values[i],
        base_values=base_value,
        data=X_eval.iloc[i].values,
        feature_names=X_eval.columns.tolist(),
    )
    plt.figure(figsize=(10, 4))
    shap.plots.waterfall(explanation, show=False)
    plt.tight_layout()
    wandb_run.log({"shap_waterfall": wandb.Image(plt.gcf())})
    plt.show()
    plt.close()

# Log mean absolute SHAP as a table
mean_abs_shap = np.abs(shap_values).mean(axis=0)
importance_df = pd.DataFrame({
    "feature": feature_columns,
    "mean_abs_shap": mean_abs_shap,
}).sort_values("mean_abs_shap", ascending=False)

wandb_run.log({"shap_importance_table": wandb.Table(dataframe=importance_df)})
wandb_run.summary.update({
    "shap_eval_size": int(len(X_eval)),
    "shap_bg_size": int(len(X_bg)),
    "top_feature": str(importance_df.iloc[0]["feature"]),
    "top_feature_mean_abs_shap": float(importance_df.iloc[0]["mean_abs_shap"]),
})

mem_after = psutil.virtual_memory()
print(f"Available RAM after SHAP cleanup: {mem_after.available / (1024**3):.2f} GB")

# Cleanup large objects explicitly
del X_bg, X_eval, X_train_shap, shap_chunks, shap_values
gc.collect()

wandb.finish()

wandb:   1 of 1 files downloaded.
c:\Users\n_and\OneDrive\Delt skrivebord\Data Science\Speciale\Energinet\py_3.10_blackwell\lib\site-packages\torch\nn\modules\rnn.py:1141: UserWarning: RNN module weights are not part of single contiguous chunk of memory. This means they need to be compacted at every call, possibly greatly increasing memory usage. To compact weights again call flatten_parameters(). (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\cudnn\RNN.cpp:1480.)
  result = _VF.lstm(
Using 150 background data samples could cause slower run times. Consider using shap.sample(data, K) or shap.kmeans(data, K) to summarize the background as K samples.

Loaded LSTM AE model artifact: DK1_LSTM_AE_2y_2024incl_DKPriceLag1_excl_lags_excl_4val_model:latest
Available RAM before SHAP: 18.54 GB
Training set size for SHAP: 22944 samples
Number of features: 32

Background sample size (X_bg): 150
Evaluation sample size (X_eval): 300
Chunk size: 25
Kernel SHAP nsamples: 100
Computing SHAP chunk 1/12 (rows 0:25)...

100%|██████████| 25/25 [05:52<00:00, 14.10s/it]

Computing SHAP chunk 2/12 (rows 25:50)...

100%|██████████| 25/25 [05:55<00:00, 14.22s/it]

Computing SHAP chunk 3/12 (rows 50:75)...

100%|██████████| 25/25 [05:57<00:00, 14.32s/it]

Computing SHAP chunk 4/12 (rows 75:100)...

100%|██████████| 25/25 [05:52<00:00, 14.12s/it]

Computing SHAP chunk 5/12 (rows 100:125)...

100%|██████████| 25/25 [05:55<00:00, 14.22s/it]

Computing SHAP chunk 6/12 (rows 125:150)...

100%|██████████| 25/25 [05:50<00:00, 14.03s/it]

Computing SHAP chunk 7/12 (rows 150:175)...

 56%|█████▌    | 14/25 [03:24<02:40, 14.63s/it]

KeyboardInterrupt: