# LSTM Autoencoder

## Load data

Set directory

In [1]:
import sys
import os

# Find the project root (Speciale_Kode)
current_dir = os.getcwd()
project_root = current_dir

# Looks for "Speciale_Kode" folder:
while os.path.basename(project_root) != "Speciale_Kode":
    project_root = os.path.dirname(project_root)

# Add to Python path
if project_root not in sys.path:
    sys.path.append(project_root)

Load data

In [2]:
import pandas as pd
from pathlib import Path
from Modules.read_data import read_data

PRICE_ZONE = "DK1"  # "DK1" or "DK2"
TRAIN_WINDOW = 2 * 8760
VAL_START = "2024-01-01 00:00:00"
VAL_WINDOW = 8784
PREDICT_PERIOD = 4 * 168
STRIDE = 13 * 168                           # Stride is measured from the start of the previous fold.
POST_VALIDATION_EXCLUDE_HOURS = 168         # Exclude first 168h after each validation window from remainder_2024_for_train
INCLUDE_REMAINING_2024_DURING_TRAINING = True
# DKPrice is handled internally by the encoder; it is NOT added as a feature column here.
INCLUDE_PRICE_HISTORY_AS_INPUT = False      # True -> incldues DKPrice as input.
INCLUDE_PRICE_LAG1_AS_INPUT = True        # True -> adds DKPrice_lag1 as an input feature regardless of INCLUDE_LAGS
INCLUDE_LAGS = False                        # Include lag features (Price_lag1, Price_lag24, etc.) in training input
USE_FORECASTED_HISTORY = True               # Use model-predicted prices to compute lag features during prediction

(
    DK1_train,
    DK1_test,
    DK2_train,
    DK2_test,
    DK1_train_weather,
    DK1_test_weather,
    DK2_train_weather,
    DK2_test_weather
) = read_data("combined_data_cleaned_v5.csv")

if PRICE_ZONE == "DK1":
    dataset_train = DK1_train.copy()
    dataset_test = DK1_test.copy()
elif PRICE_ZONE == "DK2":
    dataset_train = DK2_train.copy()
    dataset_test = DK2_test.copy()
else:
    raise ValueError("PRICE_ZONE must be 'DK1' or 'DK2'.")

# read_data already returns all of 2024 in dataset_train and all of 2025 in dataset_test.
# Build the custom 2024 rolling validation split entirely from dataset_train.
dataset_train = dataset_train.sort_values("Time").reset_index(drop=True)
dataset_test = dataset_test.sort_values("Time").reset_index(drop=True)

val_start_ts = pd.Timestamp(VAL_START)
year_2024_start = pd.Timestamp("2024-01-01 00:00:00")
year_2025_start = pd.Timestamp("2025-01-01 00:00:00")

# Keep legacy full timeline variable before redefining dataset_train below.
df = pd.concat([dataset_train, dataset_test], ignore_index=True).sort_values("Time").reset_index(drop=True)

# Fixed history block: TRAIN_WINDOW ending at VAL_START.
history = dataset_train.loc[dataset_train["Time"] < val_start_ts].copy().iloc[-TRAIN_WINDOW:]
if len(history) < TRAIN_WINDOW:
    raise ValueError(
        f"Not enough history for TRAIN_WINDOW={TRAIN_WINDOW}. Got {len(history)} rows before {VAL_START}."
    )

data_2024 = dataset_train.loc[
    (dataset_train["Time"] >= year_2024_start) & (dataset_train["Time"] < year_2025_start)
].copy()

validation_idx = []
validation_windows = []
window_start = val_start_ts

# Validation windows in 2024: next fold starts STRIDE hours after the current fold start.
# Only full windows are allowed; trailing partial windows are skipped.
while (window_start + pd.Timedelta(hours=PREDICT_PERIOD)) <= year_2025_start:
    window_end = window_start + pd.Timedelta(hours=PREDICT_PERIOD)
    if window_end <= window_start:
        break

    mask = (data_2024["Time"] >= window_start) & (data_2024["Time"] < window_end)
    if mask.any():
        validation_idx.extend(data_2024.index[mask].tolist())
        validation_windows.append((window_start, window_end))

    window_start = window_start + pd.Timedelta(hours=STRIDE)

validation_idx = sorted(set(validation_idx))

# Exclude first POST_VALIDATION_EXCLUDE_HOURS after each validation window from train remainder.
post_validation_exclusion_idx = []
for _, window_end in validation_windows:
    exclusion_end = min(window_end + pd.Timedelta(hours=POST_VALIDATION_EXCLUDE_HOURS), year_2025_start)
    if exclusion_end <= window_end:
        continue

    exclusion_mask = (data_2024["Time"] >= window_end) & (data_2024["Time"] < exclusion_end)
    if exclusion_mask.any():
        post_validation_exclusion_idx.extend(data_2024.index[exclusion_mask].tolist())

post_validation_exclusion_idx = sorted(set(post_validation_exclusion_idx))
excluded_from_remainder_idx = sorted(set(validation_idx).union(post_validation_exclusion_idx))

dataset_validation = data_2024.loc[validation_idx].copy().sort_values("Time").reset_index(drop=True)
remainder_2024_for_train = data_2024.drop(index=excluded_from_remainder_idx).copy().sort_values("Time").reset_index(drop=True)

# Load cell is the only place that decides whether 2024 remainder is included in training.
if INCLUDE_REMAINING_2024_DURING_TRAINING:
    dataset_train = (
        pd.concat([history, remainder_2024_for_train], ignore_index=True)
        .sort_values("Time")
        .drop_duplicates(subset=["Time"], keep="last")
        .reset_index(drop=True)
    )
else:
    dataset_train = history.copy().sort_values("Time").reset_index(drop=True)

# Full context dataset: pre-2024 history + all of 2024.
# Used by get_predictions for lag computation regardless of training flags.
dataset_context = (
    pd.concat([history, data_2024], ignore_index=True)
    .sort_values("Time")
    .drop_duplicates(subset=["Time"], keep="last")
    .reset_index(drop=True)
)

# Preserve full target-bearing datasets for training/evaluation and create input views for later cells.
dataset_train_full = dataset_train.copy()
dataset_validation_full = dataset_validation.copy()
dataset_train_input = dataset_train_full.copy()
dataset_validation_input = dataset_validation_full.copy()

if not INCLUDE_PRICE_HISTORY_AS_INPUT:
    dataset_train_input = dataset_train_input.drop(columns=["DKPrice"])
    dataset_validation_input = dataset_validation_input.drop(columns=["DKPrice"])

lag_columns = [c for c in dataset_train_input.columns if '_lag' in c]
if not INCLUDE_LAGS:
    dataset_train_input = dataset_train_input.drop(columns=lag_columns, errors='ignore')
    dataset_validation_input = dataset_validation_input.drop(
        columns=[c for c in dataset_validation_input.columns if '_lag' in c], errors='ignore'
    )

if INCLUDE_PRICE_LAG1_AS_INPUT:
    dataset_train_input["DKPrice_lag1"] = dataset_train_full["Price_lag1"].values
    dataset_validation_input["DKPrice_lag1"] = dataset_validation_full["Price_lag1"].values

# Keep 2025 as test set.
dataset_test = dataset_test.copy().reset_index(drop=True)

target_time = val_start_ts
prices = history["DKPrice"].astype(float).values.reshape(-1, 1)

def _load_feature_predictions_for_zone(zone):
    prediction_path = Path(project_root) / "Data" / f"feature_predictions_{zone}_2024-2025.csv"
    if not prediction_path.exists():
        print("No precomputed forecasts found.")
        return None

    predictions = pd.read_csv(prediction_path, sep=";", decimal=".", parse_dates=["Time"], dayfirst=True)
    predictions = predictions.loc[:, ~predictions.columns.duplicated()].copy()
    if "DKZone" in predictions.columns:
        predictions = predictions.loc[predictions["DKZone"] == zone].copy()
        print(f"Loaded {len(predictions)} forecasts for zone {zone}.")
        print(f"Forecast features: {len(predictions.columns)} {predictions.columns.tolist()}")
    return predictions

print(f"Using zone: {PRICE_ZONE}")
print(f"Train source shape (all of 2024): {DK1_train.shape if PRICE_ZONE == 'DK1' else DK2_train.shape}")
print(f"Test source shape (all of 2025): {DK1_test.shape if PRICE_ZONE == 'DK1' else DK2_test.shape}")
print(f"Include remainder_2024_for_train in training: {INCLUDE_REMAINING_2024_DURING_TRAINING}")
print(f"Include DKPrice in training input dataset: {INCLUDE_PRICE_HISTORY_AS_INPUT}")
print(f"Include lag features in training input: {INCLUDE_LAGS}")
print(f"Include DKPrice_lag1 as input: {INCLUDE_PRICE_LAG1_AS_INPUT}")
print(f"Use forecasted prices for lag computation during prediction: {USE_FORECASTED_HISTORY}")
print(f"Train shape (prepared training dataset): {dataset_train.shape}")
print(f"Training input shape: {dataset_train_input.shape}")
print(f"2024 remainder rows included in training: {len(remainder_2024_for_train) if INCLUDE_REMAINING_2024_DURING_TRAINING else 0}")
print(f"Validation shape (rolling 2024 windows): {dataset_validation.shape}")
print(f"Validation input shape: {dataset_validation_input.shape}")
print(f"Context shape (history + all 2024): {dataset_context.shape}")
print(f"Test shape (2025): {dataset_test.shape}")
print(f"Validation windows created: {len(validation_windows)}")
print(f"Post-validation exclusion hours: {POST_VALIDATION_EXCLUDE_HOURS}")
print(f"Rows excluded from remainder after validation windows: {len(post_validation_exclusion_idx)}")
if validation_windows:
    print("All validation windows:")
    for idx, (window_start, window_end) in enumerate(validation_windows, start=1):
        print(f"  {idx:02d}. {window_start} -> {window_end}")
print(f"Training dataset columns: {dataset_train.columns.tolist()}")
print(f"Training input columns: {dataset_train_input.columns.tolist()}")

feature_predictions = _load_feature_predictions_for_zone(PRICE_ZONE)    
if feature_predictions is not None:
    print("\nPrecomputed forecasts loaded.")

use_precomputed_feature_values = feature_predictions is not None

Notebook_dir: c:\Users\n_and\OneDrive\Delt skrivebord\Data Science\Speciale\Energinet\Delte scripts\Speciale_Kode\Modules
Python_dir: c:\Users\n_and\OneDrive\Delt skrivebord\Data Science\Speciale\Energinet\Delte scripts\Speciale_Kode
Data_folder: c:\Users\n_and\OneDrive\Delt skrivebord\Data Science\Speciale\Energinet\Delte scripts\Speciale_Kode\Data
Training data shape (DK1): (78888, 38)
Test data shape (DK1): (8760, 38)
Test set fraction (DK1): 9.99%
Training data shape (DK2): (78888, 38)
Test data shape (DK2): (8760, 38)
Test set fraction (DK2): 9.99%
Using zone: DK1
Train source shape (all of 2024): (78888, 38)
Test source shape (all of 2025): (8760, 38)
Include remainder_2024_for_train in training: True
Include DKPrice in training input dataset: False
Include lag features in training input: False
Include DKPrice_lag1 as input: True
Use forecasted prices for lag computation during prediction: True
Train shape (prepared training dataset): (22944, 38)
Training input shape: (22944, 34)
2024 remainder rows included in training: 5424
Validation shape (rolling 2024 windows): (2688, 38)
Validation input shape: (2688, 34)
Context shape (history + all 2024): (26304, 38)
Test shape (2025): (8760, 38)
Validation windows created: 4
Post-validation exclusion hours: 168
Rows excluded from remainder after validation windows: 672
All validation windows:
  01. 2024-01-01 00:00:00 -> 2024-01-29 00:00:00
  02. 2024-04-01 00:00:00 -> 2024-04-29 00:00:00
  03. 2024-07-01 00:00:00 -> 2024-07-29 00:00:00
  04. 2024-09-30 00:00:00 -> 2024-10-28 00:00:00
Training dataset columns: ['DKPrice', 'Time', 'OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'GrossCon_lag1', 'GrossCon_lag24', 'Price_lag1', 'Price_lag24']
Training input columns: ['Time', 'OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
Loaded 17544 forecasts for zone DK1.
Forecast features: 34 ['Time', 'DKZone', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'WindSpeed', 'Radiation', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'Biogas', 'Biomass', 'DEPrice', 'ExchangeGermany', 'ExchangeGreatBelt', 'ExchangeNetherlands', 'ExchangeNorway', 'ExchangeSweden', 'FossilGas', 'FossilHardCoal', 'FossilOil', 'GrossCon', 'HydroPower', 'NLPrice', 'NO2Price', 'OffshoreWindPower', 'OnshoreWindPower', 'SE3Price', 'SE4Price', 'SolarPower', 'TotalProduction', 'Waste']

Precomputed forecasts loaded.

Load Random Forest forecasting models

In [3]:
from Modules.Load_RF_forecast_models import load_rf_models

rf_models = None
if not use_precomputed_feature_values:
    # load_rf_models currently supports only the optional timeout argument.
    rf_models = load_rf_models(user="Nikolaj")      # set user to "Nikolaj" or "Christine"

Test CUDA

In [4]:
import torch

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("CUDA DIAGNOSTICS")
print("\nBasic Info:")
print(f"CUDA available: {torch.cuda.is_available()}")
print(f"Device: {device}")

if torch.cuda.is_available():
    print(f"\nGPU Info:")
    print(f"GPU Name: {torch.cuda.get_device_name(0)}")
    print(f"CUDA Version: {torch.version.cuda}")
    print(f"cuDNN Version: {torch.backends.cudnn.version()}")
    print(f"Device Count: {torch.cuda.device_count()}")

    test_tensor = torch.randn(100, 100).to(device)
    print(f"Tensor on CUDA: {test_tensor.is_cuda}")

else:
    print("\n  Running on CPU - no CUDA available")

CUDA DIAGNOSTICS

Basic Info:
CUDA available: True
Device: cuda

GPU Info:
GPU Name: NVIDIA GeForce RTX 5060 Ti
CUDA Version: 12.8
cuDNN Version: 91002
Device Count: 1
Tensor on CUDA: True

### Helper functions

In [4]:
import numpy as np
import torch
import torch.nn as nn
from sklearn.base import BaseEstimator, RegressorMixin
from torch.utils.data import DataLoader, Dataset


def set_seed(seed: int) -> None:
    torch.manual_seed(seed)
    np.random.seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)


def smape_mean(y_true: np.ndarray, y_pred: np.ndarray) -> float:
    denom = np.abs(y_true) + np.abs(y_pred)
    vals = np.where(denom == 0, 0.0, 200.0 * np.abs(y_pred - y_true) / denom)
    return float(np.mean(vals))


# ---------------------------------------------------------------------------
# Seq2Seq Dataset
# ---------------------------------------------------------------------------

class Seq2SeqDataset(Dataset):
    """
    Builds encoder/decoder/target triplets on-the-fly for seq2seq training.

    For each valid index i in [seq_len, n_samples - horizon):
      encoder_input  = concat(X[i-seq_len:i], y[i-seq_len:i].reshape(-1,1))
                       shape (seq_len, n_features + 1)  – scaled features + unscaled DKPrice
      decoder_input  = X[i : i+horizon]
                       shape (horizon, n_features)       – scaled future features
      target         = y[i : i+horizon]
                       shape (horizon,)                  – future DKPrice values
    """

    def __init__(self, X_np: np.ndarray, y_np: np.ndarray, seq_len: int, horizon: int):
        self.X = X_np
        self.y = y_np
        self.seq_len = seq_len
        self.horizon = horizon
        self.n_valid = max(0, len(X_np) - seq_len - horizon + 1)

    def __len__(self) -> int:
        return self.n_valid

    def __getitem__(self, idx: int):
        i = idx + self.seq_len
        enc_x = self.X[i - self.seq_len : i]                          # (seq_len, n_features)
        enc_price = self.y[i - self.seq_len : i].reshape(-1, 1)       # (seq_len, 1)
        encoder_input = np.concatenate([enc_x, enc_price], axis=1)    # (seq_len, n_features+1)
        decoder_input = self.X[i : i + self.horizon]                  # (horizon, n_features)
        target = self.y[i : i + self.horizon]                         # (horizon,)
        return (
            torch.tensor(encoder_input, dtype=torch.float32),
            torch.tensor(decoder_input, dtype=torch.float32),
            torch.tensor(target, dtype=torch.float32),
        )


# ---------------------------------------------------------------------------
# LSTM Autoencoder module
# ---------------------------------------------------------------------------

class LSTMAutoencoder(nn.Module):
    """
    Seq2seq LSTM Autoencoder for multi-step price forecasting.

    Architecture (based on Option 1 in the design document):
      1. Feature encoder  – a small dense MLP applied per timestep that
                            compresses (n_features + 1) inputs to latent_dim.
      2. Encoder LSTM     – processes the latent sequence and produces a
                            compressed hidden state.
      3. Decoder LSTM     – initialised with the encoder's final hidden state
                            and fed future feature forecasts; outputs
                            decoder_horizon price predictions.

    Parameters
    ----------
    encoder_input_size : int
        Number of encoder input features per timestep (n_features + 1 for DKPrice).
    decoder_input_size : int
        Number of decoder input features per timestep (n_features, no DKPrice).
    latent_dim : int
        Output dimension of the per-timestep feature encoder.
    encoder_hidden_size : int
        Hidden size of the encoder LSTM.
    decoder_hidden_size : int
        Hidden size of the decoder LSTM.
    layers : int
        Number of LSTM layers (shared between encoder and decoder).
    dense_layers : int
        Depth of the per-timestep feature encoder MLP (>=1).
    dropout : float
        Shared fallback dropout. Used for dense feature encoder dropout and as
        fallback for encoder/decoder LSTM dropout when specific values are not set.
    encoder_dropout : float or None
        Encoder LSTM dropout (active when encoder_layers > 1). If None, uses dropout.
    decoder_dropout : float or None
        Decoder LSTM dropout (active when decoder_layers > 1). If None, uses dropout.
    """

    def __init__(
        self,
        encoder_input_size: int,
        decoder_input_size: int,
        latent_dim: int = 16,
        encoder_hidden_size: int = 64,
        decoder_hidden_size: int = 64,
        layers: int = 1,
        encoder_layers=None,
        decoder_layers=None,
        dense_layers: int = 1,
        dropout: float = 0.0,
        encoder_dropout=None,
        decoder_dropout=None,
    ):
        super().__init__()
        if encoder_layers is None:
            encoder_layers = layers
        if decoder_layers is None:
            decoder_layers = layers
        self.encoder_num_layers = encoder_layers
        self.decoder_num_layers = decoder_layers
        encoder_layers = int(encoder_layers)
        decoder_layers = int(decoder_layers)

        if encoder_dropout is None:
            encoder_dropout = dropout
        if decoder_dropout is None:
            decoder_dropout = dropout
        encoder_dropout = float(encoder_dropout)
        decoder_dropout = float(decoder_dropout)

        # --- Feature encoder (dense MLP applied per timestep) ---
        enc_layers = []
        input_size = encoder_input_size

        insz_latentdim_diff = input_size - latent_dim
        change_per_layer = round(insz_latentdim_diff / dense_layers)

        in_sizes = [input_size]

        for _ in range(dense_layers - 1):
            next_in_sz = in_sizes[-1] - change_per_layer
            if next_in_sz < latent_dim:
                next_in_sz = latent_dim
            in_sizes.append(next_in_sz)

        in_sizes.append(latent_dim)
        
        for sz in range(len(in_sizes) - 1):
            in_sz = in_sizes[sz]
            out_sz = in_sizes[sz + 1]

            enc_layers.append(nn.Linear(in_sz, out_sz))

            if sz < len(in_sizes) - 2:
                enc_layers.append(nn.ReLU())
                if dropout > 0.0:
                    enc_layers.append(nn.Dropout(dropout))

        self.feature_encoder = nn.Sequential(*enc_layers)

        enc_lstm_dropout = encoder_dropout if encoder_layers > 1 else 0.0
        dec_lstm_dropout = decoder_dropout if decoder_layers > 1 else 0.0

        # --- Encoder LSTM ---
        self.encoder_lstm = nn.LSTM(
            input_size=latent_dim,
            hidden_size=encoder_hidden_size,
            num_layers=encoder_layers,
            dropout=enc_lstm_dropout,
            batch_first=True,
        )

        # --- Optional hidden-state adapter ---
        self.needs_adapter = (encoder_hidden_size != decoder_hidden_size)
        if self.needs_adapter:
            self.hidden_adapter = nn.Linear(encoder_hidden_size, decoder_hidden_size)

        # --- Decoder LSTM ---
        self.decoder_lstm = nn.LSTM(
            input_size=decoder_input_size,
            hidden_size=decoder_hidden_size,
            num_layers=decoder_layers,
            dropout=dec_lstm_dropout,
            batch_first=True,
        )

        # --- Output projection ---
        self.fc = nn.Linear(decoder_hidden_size, 1)

    def _match_decoder_layers(self, h: torch.Tensor, c: torch.Tensor):
        """Match encoder state depth to decoder num_layers."""
        enc_layers = h.size(0)
        dec_layers = self.decoder_num_layers
        if enc_layers == dec_layers:
            return h, c

        if dec_layers < enc_layers:
            # Keep the top-most encoder layers for decoder initialization.
            return h[-dec_layers:], c[-dec_layers:]

        # dec_layers > enc_layers: pad with copies of the top encoder layer.
        pad = dec_layers - enc_layers
        h_pad = h[-1:].repeat(pad, 1, 1)
        c_pad = c[-1:].repeat(pad, 1, 1)
        return torch.cat([h, h_pad], dim=0), torch.cat([c, c_pad], dim=0)

    def forward(self, encoder_x: torch.Tensor, decoder_x: torch.Tensor) -> torch.Tensor:
        """
        Parameters
        ----------
        encoder_x : Tensor of shape (batch, seq_len, encoder_input_size)
        decoder_x : Tensor of shape (batch, horizon, decoder_input_size)

        Returns
        -------
        Tensor of shape (batch, horizon)
        """
        # Feature encoding applied identically to every timestep
        latent = self.feature_encoder(encoder_x)          # (batch, seq_len, latent_dim)

        # Encoder LSTM – only final hidden state is used
        _, (h_enc, c_enc) = self.encoder_lstm(latent)     # (layers, batch, enc_hidden)

        # Adapt hidden state dimensions if encoder/decoder sizes differ
        if self.needs_adapter:
            h_dec = self.hidden_adapter(h_enc)
            c_dec = self.hidden_adapter(c_enc)
        else:
            h_dec, c_dec = h_enc, c_enc

        # Match layer depth when encoder_layers != decoder_layers.
        h_dec, c_dec = self._match_decoder_layers(h_dec, c_dec)

        # Decoder LSTM initialized with encoder's final state
        out, _ = self.decoder_lstm(decoder_x, (h_dec, c_dec))  # (batch, horizon, dec_hidden)

        return self.fc(out).squeeze(-1)                    # (batch, horizon)


# ---------------------------------------------------------------------------
# Scikit-learn compatible regressor
# ---------------------------------------------------------------------------

class TorchLSTMAERegressor(BaseEstimator, RegressorMixin):
    """
    Scikit-learn style regressor wrapping LSTMAutoencoder.

    fit(X, y)
        X : (n_samples, n_features) – pre-scaled feature matrix (DKPrice excluded).
        y : (n_samples,)            – raw DKPrice target values.
        Internally builds Seq2SeqDataset and trains the seq2seq model.

    predict_ae(encoder_x, decoder_x)
        Used by week_predictions2_AE.get_predictions() for block inference.
        encoder_x : (1, seq_len, n_features+1) – scaled features + unscaled DKPrice
        decoder_x : (1, horizon, n_features)   – scaled future features
        Returns   : (horizon,) predicted prices.

    predict(X)
        2D fallback interface for SHAP / sklearn compatibility.
        Each row of X is broadcast to a constant 168-step decoder sequence;
        a zero encoder input is used as neutral baseline.
        Returns the mean prediction across the horizon.
    """

    def __init__(
        self,
        latent_dim: int = 16,
        encoder_hidden_size: int = 64,
        decoder_hidden_size: int = 64,
        layers: int = 1,
        encoder_layers=None,
        decoder_layers=None,
        dense_layers: int = 1,
        learning_rate: float = 1e-3,
        epochs: int = 40,
        batch_size: int = 32,
        sequence_length: int = 168,
        decoder_horizon: int = 168,
        dropout: float = 0.0,
        encoder_dropout=None,
        decoder_dropout=None,
        random_state: int = 42,
        log_epoch_metrics: bool = False,
        log_prefix: str = "",
        warm_start: bool = False,
    ):
        self.latent_dim = latent_dim
        self.encoder_hidden_size = encoder_hidden_size
        self.decoder_hidden_size = decoder_hidden_size
        self.layers = layers
        self.encoder_layers = int(encoder_layers) if encoder_layers is not None else int(layers)
        self.decoder_layers = int(decoder_layers) if decoder_layers is not None else int(layers)
        self.dense_layers = dense_layers
        self.learning_rate = learning_rate
        self.epochs = epochs
        self.batch_size = batch_size
        self.sequence_length = sequence_length
        self.decoder_horizon = decoder_horizon
        self.dropout = dropout
        self.encoder_dropout = float(encoder_dropout) if encoder_dropout is not None else float(dropout)
        self.decoder_dropout = float(decoder_dropout) if decoder_dropout is not None else float(dropout)
        self.random_state = random_state
        self.log_epoch_metrics = log_epoch_metrics
        self.log_prefix = log_prefix
        self.warm_start = warm_start

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------

    def _initialize_model_state(self, encoder_input_size: int, decoder_input_size: int):
        self.device_ = torch.device("cuda" if torch.cuda.is_available() else "cpu")
        self.pin_memory_ = self.device_.type == "cuda"
        self.encoder_input_size_ = int(encoder_input_size)
        self.decoder_input_size_ = int(decoder_input_size)
        self.model_ = LSTMAutoencoder(
            encoder_input_size=self.encoder_input_size_,
            decoder_input_size=self.decoder_input_size_,
            latent_dim=int(self.latent_dim),
            encoder_hidden_size=int(self.encoder_hidden_size),
            decoder_hidden_size=int(self.decoder_hidden_size),
            layers=int(self.layers),
            encoder_layers=int(self.encoder_layers),
            decoder_layers=int(self.decoder_layers),
            dense_layers=int(self.dense_layers),
            dropout=float(self.dropout),
            encoder_dropout=float(self.encoder_dropout),
            decoder_dropout=float(self.decoder_dropout),
        ).to(self.device_)

        # Load pretrained feature encoder weights from Stage 1 (if set via
        # set_pretrained_encoder()).  Encoder params are frozen when freeze=True,
        # so the optimizer below excludes them automatically.
        _sd = getattr(self, "_pretrained_encoder_state_dict_", None)
        if _sd is not None:
            self.model_.feature_encoder.load_state_dict(_sd)
            if getattr(self, "_freeze_encoder_", True):
                for p in self.model_.feature_encoder.parameters():
                    p.requires_grad = False

        self.loss_fn_ = nn.MSELoss()
        # Only pass parameters that require gradients so frozen encoder layers
        # are not updated even if the optimizer sees them.
        self.optimizer_ = torch.optim.Adam(
            filter(lambda p: p.requires_grad, self.model_.parameters()),
            lr=float(self.learning_rate),
        )
        self.epoch_losses_ = []
        self.epoch_smapes_ = []
        self.epoch_maes_ = []
        self.epoch_rmses_ = []
        self._epochs_trained_ = 0

    # ------------------------------------------------------------------
    # set_pretrained_encoder
    # ------------------------------------------------------------------

    def set_pretrained_encoder(
        self, state_dict: dict, freeze: bool = True
    ) -> "TorchLSTMAERegressor":
        """
        Store pretrained feature encoder weights to be loaded at the next model
        initialisation (i.e. the first fit() call, or when warm_start=False).

        Call this before the first fit() / run_cross_validation() call so the
        weights are in place when _initialize_model_state() creates model_.

        Parameters
        ----------
        state_dict : OrderedDict returned by FeatureAutoencoder.encoder.state_dict()
                     (i.e. ``result["best_encoder_state_dict"]`` from Stage 1).
        freeze     : if True the feature_encoder parameters are frozen so only
                     the encoder/decoder LSTM and output layers are updated
                     during Stage 2 training.
        """
        import copy as _copy
        self._pretrained_encoder_state_dict_ = _copy.deepcopy(state_dict)
        self._freeze_encoder_ = freeze
        return self

    # ------------------------------------------------------------------
    # fit
    # ------------------------------------------------------------------

    def fit(self, X, y):
        set_seed(self.random_state)

        X_np = np.asarray(X, dtype=np.float32)
        y_np = np.asarray(y, dtype=np.float32).reshape(-1)

        if X_np.ndim != 2:
            raise ValueError(f"Expected 2-D X, got shape {X_np.shape}.")

        n_decoder_features = X_np.shape[1]
        n_encoder_features = n_decoder_features + 1   # features + DKPrice
        seq_len = int(self.sequence_length)
        horizon = int(self.decoder_horizon)

        # Build or reuse the dataset (reused across warm-start epochs for speed)
        needs_rebuild = (
            not hasattr(self, "_train_dataset_")
            or getattr(self, "_train_X_shape_", None) != X_np.shape
            or getattr(self, "_train_y_len_", None) != len(y_np)
        )
        if needs_rebuild:
            self._train_dataset_ = Seq2SeqDataset(X_np, y_np, seq_len, horizon)
            self._train_X_shape_ = X_np.shape
            self._train_y_len_ = len(y_np)

        if len(self._train_dataset_) == 0:
            raise ValueError(
                f"Training set too small to build any seq2seq sample "
                f"(need > seq_len+horizon={seq_len+horizon} rows, got {len(X_np)})."
            )

        # Initialise or reuse the model
        needs_reinit = (
            (not bool(self.warm_start))
            or (not hasattr(self, "model_"))
            or (not hasattr(self, "encoder_input_size_"))
            or (int(self.encoder_input_size_) != n_encoder_features)
            or (int(self.decoder_input_size_) != n_decoder_features)
        )
        if needs_reinit:
            self._initialize_model_state(
                encoder_input_size=n_encoder_features,
                decoder_input_size=n_decoder_features,
            )
        elif not hasattr(self, "device_"):
            self.device_ = next(self.model_.parameters()).device
            self.pin_memory_ = self.device_.type == "cuda"

        loader = DataLoader(
            self._train_dataset_,
            batch_size=int(self.batch_size),
            shuffle=True,
            pin_memory=self.pin_memory_,
        )

        self.model_.train()
        for _ in range(int(self.epochs)):
            batch_losses = []
            epoch_preds = []
            epoch_targets = []

            for enc_batch, dec_batch, tgt_batch in loader:
                enc_batch = enc_batch.to(self.device_, non_blocking=self.pin_memory_)
                dec_batch = dec_batch.to(self.device_, non_blocking=self.pin_memory_)
                tgt_batch = tgt_batch.to(self.device_, non_blocking=self.pin_memory_)

                self.optimizer_.zero_grad()
                preds = self.model_(enc_batch, dec_batch)   # (batch, horizon)
                loss = self.loss_fn_(preds, tgt_batch)
                loss.backward()
                self.optimizer_.step()

                batch_losses.append(float(loss.item()))
                epoch_preds.append(preds.detach().cpu().numpy().reshape(-1))
                epoch_targets.append(tgt_batch.detach().cpu().numpy().reshape(-1))

            epoch_loss = float(np.mean(batch_losses)) if batch_losses else float("nan")
            self.epoch_losses_.append(epoch_loss)

            if epoch_preds and epoch_targets:
                y_pred_epoch = np.concatenate(epoch_preds)
                y_true_epoch = np.concatenate(epoch_targets)
                epoch_smape = smape_mean(y_true_epoch, y_pred_epoch)
                epoch_mae = float(np.mean(np.abs(y_true_epoch - y_pred_epoch)))
                epoch_rmse = float(np.sqrt(np.mean((y_true_epoch - y_pred_epoch) ** 2)))
            else:
                epoch_smape = epoch_mae = epoch_rmse = float("nan")

            self.epoch_smapes_.append(float(epoch_smape))
            self.epoch_maes_.append(float(epoch_mae))
            self.epoch_rmses_.append(float(epoch_rmse))
            self._epochs_trained_ += 1

            if bool(self.log_epoch_metrics):
                try:
                    import wandb
                    if wandb.run is not None:
                        pfx = self.log_prefix
                        wandb.log({
                            f"{pfx}train_MSE_loss" if pfx else "train_MSE_loss": epoch_loss,
                            f"{pfx}train_smape"    if pfx else "train_smape":    float(epoch_smape),
                            f"{pfx}train_mae"      if pfx else "train_mae":      float(epoch_mae),
                            f"{pfx}train_rmse"     if pfx else "train_rmse":     float(epoch_rmse),
                            f"{pfx}epoch"          if pfx else "epoch":          int(self._epochs_trained_),
                        })
                except Exception:
                    pass

        return self

    # ------------------------------------------------------------------
    # predict_ae  (primary inference path used by week_predictions2_AE)
    # ------------------------------------------------------------------

    def predict_ae(self, encoder_x: np.ndarray, decoder_x: np.ndarray) -> np.ndarray:
        """
        Predict one 168-hour block in a single forward pass.

        Parameters
        ----------
        encoder_x : ndarray of shape (1, seq_len, n_features+1)
            Scaled historical features concatenated with unscaled DKPrice.
        decoder_x : ndarray of shape (1, horizon, n_features)
            Scaled future feature forecasts.

        Returns
        -------
        ndarray of shape (horizon,)
        """
        self.model_.eval()
        enc_t = torch.tensor(encoder_x, dtype=torch.float32).to(self.device_)
        dec_t = torch.tensor(decoder_x, dtype=torch.float32).to(self.device_)
        with torch.no_grad():
            out = self.model_(enc_t, dec_t)    # (1, horizon)
        return out.squeeze(0).detach().cpu().numpy()

    # ------------------------------------------------------------------
    # predict  (2-D fallback for SHAP / sklearn compatibility)
    # ------------------------------------------------------------------

    def predict(self, X) -> np.ndarray:
        """
        2-D input interface for SHAP / sklearn compatibility.

        Each row of X is broadcast to a constant `decoder_horizon`-step decoder
        sequence.  A zero encoder input is used as a neutral baseline.
        Returns the mean prediction across the horizon for each sample.
        """
        X_np = np.asarray(X, dtype=np.float32)
        if X_np.ndim != 2:
            raise ValueError(
                f"predict() expects 2-D X; got shape {X_np.shape}. "
                "For block inference use predict_ae(encoder_x, decoder_x)."
            )

        n_samples, n_features = X_np.shape
        horizon = int(self.decoder_horizon)
        seq_len = int(self.sequence_length)

        # Neutral encoder (all zeros)
        enc_np = np.zeros((1, seq_len, n_features + 1), dtype=np.float32)
        enc_t = torch.tensor(enc_np, dtype=torch.float32).to(self.device_)

        self.model_.eval()
        preds = []
        with torch.no_grad():
            for i in range(n_samples):
                # Replicate single feature row across the full decoder horizon
                dec_np = np.tile(X_np[i : i + 1], (horizon, 1))[np.newaxis, :]  # (1, horizon, n)
                dec_t = torch.tensor(dec_np, dtype=torch.float32).to(self.device_)
                out = self.model_(enc_t, dec_t)   # (1, horizon)
                preds.append(float(out.mean().item()))

        return np.array(preds, dtype=np.float32)

## Hyperparameter search

### Step 1: Feature Encoder Search

Tune the per-timestep feature encoder MLP as a standalone autoencoder.  
Loss/evaluation metric: **SMAPE on reconstruction**.  
Optimal `latent_dim` and `dense_layers` are then carried forward into the full LSTM AE search.

In [5]:
import copy
import torch
import torch.nn as nn
import numpy as np
from torch.utils.data import DataLoader, TensorDataset


# ---------------------------------------------------------------------------
# Differentiable SMAPE loss
# ---------------------------------------------------------------------------

class SMAPELoss(nn.Module):
    """SMAPE loss: 200 * |y_pred - y_true| / (|y_true| + |y_pred| + eps)."""

    def __init__(self, eps: float = 1e-8):
        super().__init__()
        self.eps = eps

    def forward(self, y_pred: torch.Tensor, y_true: torch.Tensor) -> torch.Tensor:
        denom = torch.abs(y_true) + torch.abs(y_pred) + self.eps
        return torch.mean(200.0 * torch.abs(y_pred - y_true) / denom)


# ---------------------------------------------------------------------------
# Feature Autoencoder – mirrors the architecture of LSTMAutoencoder.feature_encoder
# ---------------------------------------------------------------------------

class FeatureAutoencoder(nn.Module):
    """
    Standalone autoencoder for tuning the per-timestep feature encoder MLP.

    Encoder architecture is identical to LSTMAutoencoder.feature_encoder:
      dense_layers=1 → single Linear(input_size → latent_dim)
      dense_layers=k → k-1 × [Linear → ReLU → (Dropout)] + final Linear → latent_dim

    Decoder mirrors the encoder (symmetric MLP from latent_dim back to input_size).

    Parameters
    ----------
    input_size  : number of features per timestep (n_features + 1 for DKPrice, same
                  as encoder_input_size in LSTMAutoencoder)
    latent_dim  : output dimension of the encoder (hyperparameter to tune)
    dense_layers: depth of the encoder/decoder MLP (≥1)
    dropout     : dropout rate applied between hidden layers (only if dense_layers > 1)
    """

    def __init__(
        self,
        input_size: int,
        latent_dim: int,
        dense_layers: int,
        dropout: float = 0.0,
    ):
        super().__init__()

        # ---- Encoder (same as LSTMAutoencoder.feature_encoder) ----
        enc = []

        insz_latentdim_diff = input_size - latent_dim
        change_per_layer = round(insz_latentdim_diff / dense_layers)

        in_sizes = [input_size]

        for _ in range(dense_layers - 1):
            next_in_sz = in_sizes[-1] - change_per_layer
            if next_in_sz < latent_dim:
                next_in_sz = latent_dim
            in_sizes.append(next_in_sz)

        in_sizes.append(latent_dim)
        
        for sz in range(len(in_sizes) - 1):
            in_sz = in_sizes[sz]
            out_sz = in_sizes[sz + 1]

            enc.append(nn.Linear(in_sz, out_sz))

            if sz < len(in_sizes) - 2:
                enc.append(nn.ReLU())
                if dropout > 0.0:
                    enc.append(nn.Dropout(dropout))

        self.encoder = nn.Sequential(*enc)

        # ---- Decoder (symmetric to encoder) ----
        dec = []

        decoder_sizes = list(reversed(in_sizes))

        for sz in range(len(decoder_sizes) - 1):
            in_sz = decoder_sizes[sz]
            out_sz = decoder_sizes[sz + 1]

            dec.append(nn.Linear(in_sz, out_sz))

            if sz < len(decoder_sizes) - 2:
                dec.append(nn.ReLU())
                if dropout > 0.0:
                    dec.append(nn.Dropout(dropout))

        self.decoder = nn.Sequential(*dec)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        return self.decoder(self.encoder(x))

    def encode(self, x: torch.Tensor) -> torch.Tensor:
        return self.encoder(x)


# ---------------------------------------------------------------------------
# Training helper
# ---------------------------------------------------------------------------

def train_feature_autoencoder(
    X_train: np.ndarray,
    X_val: np.ndarray,
    latent_dim: int,
    dense_layers: int,
    learning_rate: float,
    max_epochs: int,
    patience: int,
    batch_size: int,
    dropout: float = 0.0,
    random_state: int = 42,
    log_wandb: bool = False,
) -> dict:
    """
    Train a FeatureAutoencoder with SMAPE reconstruction loss.

    Parameters
    ----------
    X_train / X_val : float32 arrays of shape (n_samples, input_size).
                      Should be the scaled feature matrix concatenated with
                      raw DKPrice, matching the encoder input in Seq2SeqDataset.
    log_wandb       : whether to call wandb.log() per epoch.

    Returns
    -------
    dict with keys: best_val_smape, best_epoch, epochs_trained, epoch_history,
                    best_encoder_state_dict (state_dict of the encoder at best epoch,
                    ready to be loaded into LSTMAutoencoder.feature_encoder).
    """
    set_seed(random_state)
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    pin_memory = device.type == "cuda"

    input_size = X_train.shape[1]
    model = FeatureAutoencoder(
        input_size=input_size,
        latent_dim=latent_dim,
        dense_layers=dense_layers,
        dropout=dropout,
    ).to(device)

    criterion = SMAPELoss()
    optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate)

    train_t = torch.tensor(X_train, dtype=torch.float32)
    val_t = torch.tensor(X_val, dtype=torch.float32)

    loader = DataLoader(
        TensorDataset(train_t),
        batch_size=batch_size,
        shuffle=True,
        pin_memory=pin_memory,
    )

    best_val_smape = float("inf")
    best_epoch = 0
    patience_counter = 0
    epoch_history = []
    epoch = 0
    best_encoder_state_dict = None   # saved at the epoch with lowest val SMAPE

    for epoch in range(1, max_epochs + 1):
        model.train()
        batch_losses = []
        for (x_batch,) in loader:
            x_batch = x_batch.to(device, non_blocking=pin_memory)
            optimizer.zero_grad()
            recon = model(x_batch)
            loss = criterion(recon, x_batch)
            loss.backward()
            optimizer.step()
            batch_losses.append(float(loss.item()))

        train_smape = float(np.mean(batch_losses)) if batch_losses else float("nan")

        model.eval()
        with torch.no_grad():
            val_recon = model(val_t.to(device))
            val_smape = float(criterion(val_recon, val_t.to(device)).item())

        epoch_history.append({"epoch": epoch, "train_smape": train_smape, "val_smape": val_smape})

        if log_wandb:
            try:
                import wandb as _wandb
                _wandb.log({"epoch": epoch, "train_smape": train_smape, "val_smape": val_smape})
            except Exception:
                pass

        if val_smape < best_val_smape:
            best_val_smape = val_smape
            best_epoch = epoch
            patience_counter = 0
            # Snapshot the encoder weights at this best epoch
            best_encoder_state_dict = copy.deepcopy(model.encoder.state_dict())
        else:
            patience_counter += 1

        if patience_counter >= patience:
            break

    return {
        "best_val_smape": best_val_smape,
        "best_epoch": best_epoch,
        "epochs_trained": epoch,
        "epoch_history": epoch_history,
        "best_encoder_state_dict": best_encoder_state_dict,
    }

Feature encoder search grid

In [26]:
import numpy as np
from sklearn.preprocessing import StandardScaler

# ---------------------------------------------------------------------------
# Hyperparameter grid for the feature encoder autoencoder search
# ---------------------------------------------------------------------------

fe_param_grid = {
    "latent_dim":    [33],
    "dense_layers":  [1],
    "learning_rate": [0.001],
    "batch_size":    [64],
    "dropout":       [0.0],   # expand to [0.0, 0.1] if dense_layers > 1 is explored with dropout
    "max_epochs":    [150],
    "patience":      [30],
}

fe_total_combinations = int(np.prod([len(v) for v in fe_param_grid.values()]))

# When dense_layers == 1, dropout has no effect; those combinations are redundant.
_other_keys = [k for k in fe_param_grid if k not in ("dense_layers", "dropout")]
_n_other = int(np.prod([len(fe_param_grid[k]) for k in _other_keys]))
_n_redundant = _n_other * 1 * len([d for d in fe_param_grid["dropout"] if d != 0.0])
fe_effective_combinations = fe_total_combinations - _n_redundant
print(f"Feature encoder total combinations: {fe_total_combinations}")
print(f"Combinations after skipping dropout>0 with 1 layer: {fe_effective_combinations}")

# ---------------------------------------------------------------------------
# Prepare input data: scaled features + raw DKPrice
# (Matches the encoder input built in Seq2SeqDataset)
# ---------------------------------------------------------------------------

fe_feature_cols = [c for c in dataset_train_input.columns if c not in ["Time", "DKPrice"]]
print(f"Feature columns ({len(fe_feature_cols)}): {fe_feature_cols}")

fe_X_features = dataset_train_input[fe_feature_cols].astype(np.float32).values
fe_y_price    = dataset_train_full["DKPrice"].astype(np.float32).values.reshape(-1, 1)

# Fit scaler only on the feature part (DKPrice is kept raw, matching Seq2SeqDataset behaviour)
fe_scaler = StandardScaler()
fe_X_scaled = fe_scaler.fit_transform(fe_X_features).astype(np.float32)

# Final input matrix: [scaled_features | raw_DKPrice]
fe_X = np.concatenate([fe_X_scaled, fe_y_price], axis=1)

# Chronological 90/10 split (no shuffling – temporal data)
fe_split_idx = int(len(fe_X) * 0.9)
fe_X_train = fe_X[:fe_split_idx]
fe_X_val   = fe_X[fe_split_idx:]

print(f"Train samples: {len(fe_X_train)},  val samples: {len(fe_X_val)}")
print(f"Feature AE input size: {fe_X.shape[1]}  (= {len(fe_feature_cols)} features + 1 DKPrice)")

Feature encoder total combinations: 1
Combinations after skipping dropout>0 with 1 layer: 1
Feature columns (33): ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
Train samples: 20649,  val samples: 2295
Feature AE input size: 34  (= 33 features + 1 DKPrice)

Run feature encoder search

In [27]:
import itertools
import torch
import wandb
import pandas as pd
from pathlib import Path
from time import time

FE_WANDB_PROJECT    = f"FeatureEncoder_AE_search_inclLag1_{PRICE_ZONE}_v2_Niko"
FE_WANDB_RUN_BASE   = f"{PRICE_ZONE}_"
FE_START_COMBINATION = 1   # resume from a specific combination number if needed

output_folder = Path(project_root) / "Deep learners" / "LSTM Autoencoder"
output_folder.mkdir(parents=True, exist_ok=True)

# Path where Stage 1 best checkpoint is persisted to disk
_stage1_ckpt_path = output_folder / f"{PRICE_ZONE}_best_stage1_checkpoint.pt"

fe_param_names  = list(fe_param_grid.keys())
fe_param_values = list(fe_param_grid.values())
_dense_idx   = fe_param_names.index("dense_layers")
_dropout_idx = fe_param_names.index("dropout")
fe_combinations = [
    combo for combo in itertools.product(*fe_param_values)
    if not (combo[_dense_idx] == 1 and combo[_dropout_idx] != 0.0)
]
fe_num_combinations = len(fe_combinations)
print(f"Running {fe_num_combinations} feature encoder combinations (skipped dropout>0 with dense_layers==1)")

fe_results  = []
fe_start_ts = time()

# Global best across all Stage 1 combinations – exposed to Stage 2.
best_stage1_val_smape         = float("inf")
best_stage1_encoder_state_dict = None   # encoder weights at best reconstruction SMAPE
best_stage1_params            = None    # hyperparameters of the best combination

for comb_no, combination in enumerate(fe_combinations, start=1):
    params = dict(zip(fe_param_names, combination))

    if comb_no < FE_START_COMBINATION:
        continue

    elapsed_min  = (time() - fe_start_ts) / 60
    est_total    = elapsed_min / comb_no * fe_num_combinations if comb_no > 1 else float("nan")
    print(
        f"\nFE combination {comb_no}/{fe_num_combinations}: {params}  "
        f"[{elapsed_min:.1f} min elapsed, ~{est_total:.1f} min total]"
    )

    run_name = (FE_WANDB_RUN_BASE +
        f"latentdim{params['latent_dim']}_layers{params['dense_layers']}"
        f"_lr{params['learning_rate']}_batchsize{params['batch_size']}"
        f"_dropout{params['dropout']}_comb{comb_no:03d}"
    )

    run = wandb.init(
        project=FE_WANDB_PROJECT,
        name=run_name,
        config={
            "price_zone":       PRICE_ZONE,
            "fe_input_size":    int(fe_X.shape[1]),
            "train_samples":    int(len(fe_X_train)),
            "val_samples":      int(len(fe_X_val)),
            "combination":      int(comb_no),
            "num_combinations": int(fe_num_combinations),
            **params,
        },
        tags=["feature-encoder", "autoencoder", "hyperparameter-search", "smape"],
        reinit=True,
        settings=wandb.Settings(start_method="thread"),
    )

    try:
        result = train_feature_autoencoder(
            X_train=fe_X_train,
            X_val=fe_X_val,
            latent_dim=int(params["latent_dim"]),
            dense_layers=int(params["dense_layers"]),
            learning_rate=float(params["learning_rate"]),
            max_epochs=int(params["max_epochs"]),
            patience=int(params["patience"]),
            batch_size=int(params["batch_size"]),
            dropout=float(params["dropout"]),
            log_wandb=True,
        )

        row = {
            **params,
            "combination":      int(comb_no),
            "fe_input_size":    int(fe_X.shape[1]),
            "price_zone":       PRICE_ZONE,
            "best_val_smape":   float(result["best_val_smape"]),
            "best_epoch":       int(result["best_epoch"]),
            "epochs_trained":   int(result["epochs_trained"]),
        }
        fe_results.append(row)

        run.summary.update({
            "best_val_smape": float(result["best_val_smape"]),
            "best_epoch":     int(result["best_epoch"]),
            "epochs_trained": int(result["epochs_trained"]),
        })

        print(
            f"  -> best val SMAPE: {result['best_val_smape']:.4f}  "
            f"(epoch {result['best_epoch']}/{result['epochs_trained']})"
        )

        # Track the globally best encoder weights across all Stage 1 combinations
        if result["best_val_smape"] < best_stage1_val_smape:
            best_stage1_val_smape          = float(result["best_val_smape"])
            best_stage1_encoder_state_dict = result["best_encoder_state_dict"]
            best_stage1_params             = dict(params)
            print(f"  *** New global best: val SMAPE={best_stage1_val_smape:.4f} ***")

    finally:
        wandb.finish()

# Persist checkpoint to disk immediately so progress survives a restart
torch.save(
    {
        "encoder_state_dict": best_stage1_encoder_state_dict,
        "params":             best_stage1_params,
        "val_smape":          best_stage1_val_smape,
    },
    _stage1_ckpt_path,
)
print(f"  Checkpoint saved → {_stage1_ckpt_path}")

# ---- Save & display results ----
fe_results_df = pd.DataFrame(fe_results).sort_values("best_val_smape").reset_index(drop=True)

fe_base_name = f"{PRICE_ZONE}_feature_encoder_search_results"
fe_out_path  = output_folder / f"{fe_base_name}.csv"
_counter = 1
while fe_out_path.exists():
    fe_out_path = output_folder / f"{fe_base_name}_{_counter}.csv"
    _counter += 1

# fe_results_df.to_csv(fe_out_path, index=False, decimal=",")
# print(f"\nFeature encoder search results saved to: {fe_out_path}")

print("\nTop 10 configurations by val SMAPE:")
display(fe_results_df.head(10))

# ---- Summary of what Stage 2 will receive ----
print(
    f"\n=== Stage 1 complete – best encoder weights ready for Stage 2 ===\n"
    f"  latent_dim           : {best_stage1_params['latent_dim']}\n"
    f"  dense_layers         : {best_stage1_params['dense_layers']}\n"
    f"  best_val_smape (recon): {best_stage1_val_smape:.4f}\n"
    f"\n  best_stage1_encoder_state_dict is available for Stage 2.\n"
    f"  These weights will be loaded into LSTMAutoencoder.feature_encoder\n"
    f"  and frozen during Stage 2 LSTM tuning.\n"
    f"  Checkpoint on disk : {_stage1_ckpt_path}"
)

Running 1 feature encoder combinations (skipped dropout>0 with dense_layers==1)

FE combination 1/1: {'latent_dim': 33, 'dense_layers': 1, 'learning_rate': 0.001, 'batch_size': 64, 'dropout': 0.0, 'max_epochs': 150, 'patience': 30}  [0.0 min elapsed, ~nan min total]

  -> best val SMAPE: 16.8601  (epoch 97/127)
  *** New global best: val SMAPE=16.8601 ***

  Checkpoint saved → c:\Users\n_and\OneDrive\Delt skrivebord\Data Science\Speciale\Energinet\Delte scripts\Speciale_Kode\Deep learners\LSTM Autoencoder\DK1_best_stage1_checkpoint.pt

Top 10 configurations by val SMAPE:

,latent_dim,dense_layers,learning_rate,batch_size,dropout,max_epochs,patience,combination,fe_input_size,price_zone,best_val_smape,best_epoch,epochs_trained
0,33,1,0.001,64,0.0,150,30,1,34,DK1,16.860125,97,127

=== Stage 1 complete – best encoder weights ready for Stage 2 ===
  latent_dim           : 33
  dense_layers         : 1
  best_val_smape (recon): 16.8601

  best_stage1_encoder_state_dict is available for Stage 2.
  These weights will be loaded into LSTMAutoencoder.feature_encoder
  and frozen during Stage 2 LSTM tuning.
  Checkpoint on disk : c:\Users\n_and\OneDrive\Delt skrivebord\Data Science\Speciale\Energinet\Delte scripts\Speciale_Kode\Deep learners\LSTM Autoencoder\DK1_best_stage1_checkpoint.pt

### Step 2: Full LSTM AE Search

Search grid

In [6]:
import numpy as np
import itertools
import torch
from pathlib import Path

# ---------------------------------------------------------------------------
# Load Stage 1 checkpoint from disk if not already in memory
# (allows resuming Stage 2 after a kernel restart)
# ---------------------------------------------------------------------------
_stage1_ckpt_path = Path(project_root) / "Deep learners" / "LSTM Autoencoder" / f"{PRICE_ZONE}_best_stage1_checkpoint.pt"

if not ("best_stage1_encoder_state_dict" in globals() and best_stage1_encoder_state_dict is not None):
    if _stage1_ckpt_path.exists():
        _ckpt = torch.load(_stage1_ckpt_path, map_location="cpu")
        best_stage1_encoder_state_dict = _ckpt["encoder_state_dict"]
        best_stage1_params             = _ckpt["params"]
        best_stage1_val_smape          = _ckpt["val_smape"]
        print(f"Loaded Stage 1 checkpoint from disk: {_stage1_ckpt_path}")
        print(f"  best_stage1_params   : {best_stage1_params}")
        print(f"  best_stage1_val_smape: {best_stage1_val_smape:.4f}")
    else:
        print(f"WARNING: No Stage 1 checkpoint found at {_stage1_ckpt_path}. Run Stage 1 first.")
else:
    print(f"Stage 1 results already in memory (val SMAPE={best_stage1_val_smape:.4f}). Skipping disk load.")

# ---------------------------------------------------------------------------
# Step 2 search grid – split by component, combined at the end.
# latent_dim and dense_layers are NOT swept here; they are fixed to the
# best values found in Stage 1 (best_stage1_params).
# ---------------------------------------------------------------------------

# 1. Encoder LSTM
enc_lstm_grid = {
    "encoder_hidden_size": [28, 33, 48],
    "encoder_layers":      [1, 2],
    "encoder_dropout":     [0.0, 0.2],
}

# 2. Decoder LSTM
dec_lstm_grid = {
    "decoder_hidden_size": [28, 33, 48],
    "decoder_layers":      [1, 2],
    "decoder_dropout":     [0.0, 0.2],
}

# 3. Shared / training hyperparameters
training_grid = {
    "learning_rate":   [0.001, 0.0005],
    "max_epochs":      [60],
    "patience":        [20],
    "batch_size":      [32, 64],
    "sequence_length": [24, 168],
}

# Combine LSTM + training sub-grids into one flat grid
param_grid = {**enc_lstm_grid, **dec_lstm_grid, **training_grid}

total_combinations = int(np.prod([len(v) for v in param_grid.values()]))

# Exclude ineffective single-layer dropout combinations
excluded = sum(
    1
    for combo in itertools.product(*param_grid.values())
    if (
        dict(zip(param_grid.keys(), combo))["encoder_layers"] == 1
        and dict(zip(param_grid.keys(), combo))["encoder_dropout"] > 0.0
    )
    or (
        dict(zip(param_grid.keys(), combo))["decoder_layers"] == 1
        and dict(zip(param_grid.keys(), combo))["decoder_dropout"] > 0.0
    )
)
effective_combinations = total_combinations - excluded

print(f"Stage 1 encoder shape (fixed for Stage 2):")
if "best_stage1_params" in globals() and best_stage1_params is not None:
    print(f"  latent_dim   = {best_stage1_params['latent_dim']}")
    print(f"  dense_layers = {best_stage1_params['dense_layers']}")
else:
    print("  (run Stage 1 first to set best_stage1_params)")

print(f"\nSub-grid sizes:")
print(f"  Encoder LSTM     : {int(np.prod([len(v) for v in enc_lstm_grid.values()]))} combinations  {enc_lstm_grid}")
print(f"  Decoder LSTM     : {int(np.prod([len(v) for v in dec_lstm_grid.values()]))} combinations  {dec_lstm_grid}")
print(f"  Training / shared: {int(np.prod([len(v) for v in training_grid.values()]))} combinations  {training_grid}")
print(f"\nTotal combinations (before exclusions): {total_combinations}")
print(f"Excluded (single-layer branch with dropout>0): {excluded}")
print(f"Effective combinations:                 {effective_combinations}")

Loaded Stage 1 checkpoint from disk: c:\Users\n_and\OneDrive\Delt skrivebord\Data Science\Speciale\Energinet\Delte scripts\Speciale_Kode\Deep learners\LSTM Autoencoder\DK1_best_stage1_checkpoint.pt
  best_stage1_params   : {'latent_dim': 33, 'dense_layers': 1, 'learning_rate': 0.001, 'batch_size': 64, 'dropout': 0.0, 'max_epochs': 150, 'patience': 30}
  best_stage1_val_smape: 16.8601
Stage 1 encoder shape (fixed for Stage 2):
  latent_dim   = 33
  dense_layers = 1

Sub-grid sizes:
  Encoder LSTM     : 12 combinations  {'encoder_hidden_size': [28, 33, 48], 'encoder_layers': [1, 2], 'encoder_dropout': [0.0, 0.2]}
  Decoder LSTM     : 12 combinations  {'decoder_hidden_size': [28, 33, 48], 'decoder_layers': [1, 2], 'decoder_dropout': [0.0, 0.2]}
  Training / shared: 8 combinations  {'learning_rate': [0.001, 0.0005], 'max_epochs': [60], 'patience': [20], 'batch_size': [32, 64], 'sequence_length': [24, 168]}

Total combinations (before exclusions): 1152
Excluded (single-layer branch with dropout>0): 504
Effective combinations:                 648

Hyperparameter search

In [7]:

from Modules.Validation3_AE import run_cross_validation
import itertools
import numpy as np
from pathlib import Path
from time import time

import pandas as pd
import wandb

# ---------------------------------------------------------------------------
# Verify that Stage 1 produced a pretrained encoder state dict
# ---------------------------------------------------------------------------
if "best_stage1_encoder_state_dict" not in globals() or best_stage1_encoder_state_dict is None:
    best_stage1_params = {
        "latent_dim":    None,
        "dense_layers":  None
    }
    raise RuntimeError(
        "best_stage1_encoder_state_dict is not set. Run the Stage 1 feature encoder "
        "search cell first so that pretrained encoder weights are available."
    )

print(
    f"Using pretrained encoder from Stage 1:\n"
    f"  latent_dim   = {best_stage1_params['latent_dim']}\n"
    f"  dense_layers = {best_stage1_params['dense_layers']}\n"
    f"  best recon SMAPE = {best_stage1_val_smape:.4f}\n"
)

PREDICT_PERIOD = 1 * 168
split_setup = 2
start_combination = 742

WANDB_PROJECT = "LSTM_AE_param_Lag1Incl_v3_Niko"

# param_grid is defined in the grid cell above (split into fe_grid, enc_lstm_grid,
# dec_lstm_grid and training_grid, then merged into one flat param_grid dict).
# Stage 2 fixes latent_dim and dense_layers to the Stage 1 best values; only
# LSTM / training hyperparameters are swept here.
num_combinations = int(np.prod([len(v) for v in param_grid.values()]))
print(f"Total combinations: {num_combinations}")

param_names = list(param_grid.keys())
param_values = list(param_grid.values())
all_combinations = list(itertools.product(*param_values))

# Feature columns: all columns except Time and DKPrice.
# DKPrice is handled inside the encoder; it is NOT a feature column.
cv_feature_columns = [c for c in dataset_train_input.columns if c not in ["Time", "DKPrice"]]
print(f"CV feature columns ({len(cv_feature_columns)}): {cv_feature_columns}")

start_time = time()
results = []
for comb_number, combination in enumerate(all_combinations, start=1):
    params = dict(zip(param_names, combination))
    if comb_number < start_combination:
        continue
    if int(params["encoder_layers"]) == 1 and float(params["encoder_dropout"]) > 0.0:
        continue
    if int(params["decoder_layers"]) == 1 and float(params["decoder_dropout"]) > 0.0:
        continue

    WANDB_RUN_BASENAME = f"LSTM_AE_" + \
                    f"esize{params['encoder_hidden_size']}" + \
                    f"_elayers{params['encoder_layers']}" + \
                    f"_dsize{params['decoder_hidden_size']}" + \
                    f"_dlayers{params['decoder_layers']}" + \
                    f"_bs{params['batch_size']}" + \
                    f"_seqlen{params['sequence_length']}" + \
                    f"_lr{params['learning_rate']}" + \
                    f"_edrop{params['encoder_dropout']}" + \
                    f"_ddrop{params['decoder_dropout']}"

    print(f"\nCombination {comb_number}/{num_combinations}: {params}")
    print(
        f"Time: {(time() - start_time)/60:.2f} minutes - estimated total time: "
        f"{(time() - start_time)/comb_number*num_combinations/60:.2f} minutes"
    )
    run_name = (f"{WANDB_RUN_BASENAME}_comb{comb_number:03d}")

    run = wandb.init(
        project=WANDB_PROJECT,
        name=run_name,
        config={
            "price_zone": PRICE_ZONE,
            "train_window": TRAIN_WINDOW,
            "val_window": VAL_WINDOW,
            "val_start": VAL_START,
            "predict_period": PREDICT_PERIOD,
            "stride": STRIDE,
            "split_setup": split_setup,
            "combination": int(comb_number),
            "num_combinations": int(num_combinations),
            "include_remaining_2024_in_prepared_train_data": bool(INCLUDE_REMAINING_2024_DURING_TRAINING),
            # pretrained encoder provenance
            "stage1_latent_dim":   int(best_stage1_params["latent_dim"]),
            "stage1_dense_layers": int(best_stage1_params["dense_layers"]),
            "stage1_recon_smape":  float(best_stage1_val_smape),
            "encoder_frozen":      True,
            # sub-grid membership for easy W&B grouping
            "fe_latent_dim":        int(best_stage1_params["latent_dim"]),
            "fe_dense_layers":      int(best_stage1_params["dense_layers"]),
            "enc_hidden_size":      int(params["encoder_hidden_size"]),
            "enc_layers":           int(params["encoder_layers"]),
            "dec_hidden_size":      int(params["decoder_hidden_size"]),
            "dec_layers":           int(params["decoder_layers"]),
            **params,
        },
        tags=["lstm-ae", "hyperparameter-search", "cross-validation", "early-stopping",
              "pretrained-encoder", "frozen-encoder"],
        reinit=True,
        settings=wandb.Settings(start_method="thread"),
    )

    try:
        max_epochs = int(params["max_epochs"])
        patience = int(params["patience"])

        model = TorchLSTMAERegressor(
            # Use the latent_dim / dense_layers that match the pretrained encoder shape.
            # The grid may vary these, but the actual weights come from Stage 1.
            latent_dim=int(best_stage1_params["latent_dim"]),
            dense_layers=int(best_stage1_params["dense_layers"]),
            encoder_hidden_size=int(params["encoder_hidden_size"]),
            decoder_hidden_size=int(params["decoder_hidden_size"]),
            encoder_layers=int(params["encoder_layers"]),
            decoder_layers=int(params["decoder_layers"]),
            learning_rate=float(params["learning_rate"]),
            epochs=1,
            batch_size=int(params["batch_size"]),
            sequence_length=int(params["sequence_length"]),
            encoder_dropout=float(params["encoder_dropout"]),
            decoder_dropout=float(params["decoder_dropout"]),
            dropout=0.0,
            random_state=42,
            warm_start=True,
        )

        # Load the pretrained encoder weights from Stage 1 and freeze them.
        # _initialize_model_state() (called on the first fit()) will inject
        # these weights into LSTMAutoencoder.feature_encoder and exclude those
        # parameters from the optimizer.
        model.set_pretrained_encoder(best_stage1_encoder_state_dict, freeze=True)

        best_val_smape = float("inf")
        best_epoch = 0
        patience_counter = 0
        best_combination_results = None

        print(f"INCLUDE_REMAINING_2024_DURING_TRAINING: {INCLUDE_REMAINING_2024_DURING_TRAINING}")
        print(f"Number of input features (decoder): {len(cv_feature_columns)}")
        print(f"All input columns: {cv_feature_columns}")

        for epoch in range(1, max_epochs + 1):
            print(f"  Epoch {epoch}/{max_epochs}")
            combination_results = run_cross_validation(
                model=model,
                dataset_train=dataset_train,
                dataset_validation=dataset_validation,
                dataset_context=dataset_context,
                feature_columns=cv_feature_columns,
                include_remaining_2024=INCLUDE_REMAINING_2024_DURING_TRAINING,
                dk_zone=PRICE_ZONE,
                split_setup=split_setup,
                train_window=TRAIN_WINDOW,
                val_window=VAL_WINDOW,
                val_start=VAL_START,
                predict_period=PREDICT_PERIOD,
                stride=STRIDE,
                use_scaler=True,
                print_fold_results=False,
                plot=False,
                rf_models=rf_models,
                use_precomputed_feature_values=use_precomputed_feature_values,
                precomputed_feature_predictions=feature_predictions,
                use_forecasted_history=USE_FORECASTED_HISTORY,
            )

            val_smape = float(combination_results["overall_avg_weekly_smape"])

            if val_smape < best_val_smape:
                best_val_smape = val_smape
                best_epoch = epoch
                best_combination_results = combination_results
                patience_counter = 0
            else:
                patience_counter += 1

            wandb.log({
                "combination": int(comb_number),
                "epoch": int(epoch),
                "train_window": int(TRAIN_WINDOW),
                "val_window": int(VAL_WINDOW),
                "predict_period": int(PREDICT_PERIOD),
                # sub-grid params logged explicitly for W&B grouping/filtering
                "fe_latent_dim": int(best_stage1_params["latent_dim"]),
                "fe_dense_layers": int(best_stage1_params["dense_layers"]),
                "enc_hidden_size":        int(params["encoder_hidden_size"]),
                "enc_layers":             int(params["encoder_layers"]),
                "dec_hidden_size":        int(params["decoder_hidden_size"]),
                "dec_layers":             int(params["decoder_layers"]),
                "learning_rate":          float(params["learning_rate"]),
                "encoder_dropout":        float(params["encoder_dropout"]),
                "decoder_dropout":        float(params["decoder_dropout"]),
                "batch_size":             int(params["batch_size"]),
                "sequence_length":        int(params["sequence_length"]),
                "max_epochs":             int(params["max_epochs"]),
                "patience":               int(params["patience"]),
                "val_SMAPE":              float(val_smape),
                "best_val_SMAPE":         float(best_val_smape),
                "patience_counter":       int(patience_counter),
            })

            if patience_counter >= patience:
                print("  Early stopping triggered.")
                break

        print(f"\n  best_val_SMAPE={best_val_smape:.3f}")

        if best_combination_results is None:
            raise RuntimeError("No validation results were produced for this combination.")

        row = {
            # sub-grid columns first for easy reading in the CSV
            "fe_latent_dim":          int(best_stage1_params["latent_dim"]),
            "fe_dense_layers":        int(best_stage1_params["dense_layers"]),
            "enc_hidden_size":        int(params["encoder_hidden_size"]),
            "enc_layers":             int(params["encoder_layers"]),
            "dec_hidden_size":        int(params["decoder_hidden_size"]),
            "dec_layers":             int(params["decoder_layers"]),
            "encoder_dropout":        float(params["encoder_dropout"]),
            "decoder_dropout":        float(params["decoder_dropout"]),
            **params,
            "best_epoch": int(best_epoch),
            "epochs_trained": int(epoch),
            "price_zone": PRICE_ZONE,
            "train_window": str(TRAIN_WINDOW // 8760) + " years",
            "val_start": VAL_START.split(" ")[0],
            "avg_smape": best_val_smape,
            "avg_weekly_rmse": best_combination_results["overall_avg_weekly_rmse"],
            "avg_weekly_mae": best_combination_results["overall_avg_weekly_mae"],
            "avg_weekly_smape": best_combination_results["overall_avg_weekly_smape"],
            "avg_daily_rmse": best_combination_results["overall_avg_daily_rmse"],
            "avg_daily_mae": best_combination_results["overall_avg_daily_mae"],
            "avg_daily_smape": best_combination_results["overall_avg_daily_smape"],
            "avg_smape_day_1": best_combination_results["avg_smape_day_1"],
            "avg_smape_day_2": best_combination_results["avg_smape_day_2"],
            "avg_smape_day_3": best_combination_results["avg_smape_day_3"],
            "avg_smape_day_4": best_combination_results["avg_smape_day_4"],
            "avg_smape_day_5": best_combination_results["avg_smape_day_5"],
            "avg_smape_day_6": best_combination_results["avg_smape_day_6"],
            "avg_smape_day_7": best_combination_results["avg_smape_day_7"],
        }
        results.append(row)

        run.summary.update({
            "best_epoch": int(best_epoch),
            "best_val_smape": float(best_val_smape),
            "epochs_trained": int(epoch),
        })
    finally:
        wandb.finish()

results_df = pd.DataFrame(results).sort_values("avg_smape")

project_root_path = Path(project_root)
output_folder = project_root_path / "Deep learners" / "LSTM Autoencoder"
output_folder.mkdir(parents=True, exist_ok=True)

base_filename = f"{PRICE_ZONE}_lstm_ae_search_results"
filename = output_folder / f"{base_filename}.csv"
counter = 1
while filename.exists():
    filename = output_folder / f"{base_filename}_{counter}.csv"
    counter += 1

results_df.to_csv(filename, index=False, decimal=",")
print(f"\nResults saved to: {filename}")
display(results_df.head(10))

c:\Users\n_and\OneDrive\Delt skrivebord\Data Science\Speciale\Energinet\py_3.10_blackwell\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
wandb: WARNING `start_method` is deprecated and will be removed in a future version of wandb. This setting is currently non-functional and safely ignored.

Using pretrained encoder from Stage 1:
  latent_dim   = 33
  dense_layers = 1
  best recon SMAPE = 16.8601

Total combinations: 1152
CV feature columns (33): ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']

Combination 742/1152: {'encoder_hidden_size': 33, 'encoder_layers': 2, 'encoder_dropout': 0.2, 'decoder_hidden_size': 48, 'decoder_layers': 1, 'decoder_dropout': 0.0, 'learning_rate': 0.0005, 'max_epochs': 60, 'patience': 20, 'batch_size': 32, 'sequence_length': 168}
Time: 0.00 minutes - estimated total time: 0.00 minutes

wandb: Currently logged in as: nande24 (Energinet_speciale) to https://api.wandb.ai. Use `wandb login --relogin` to force relogin
wandb: WARNING Using a boolean value for 'reinit' is deprecated. Use 'return_previous' or 'finish_previous' instead.

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 5.18s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 173.229
  Epoch 2/60
Model trained in 2.99s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 160.642
  Epoch 3/60
Model trained in 2.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 150.477
  Epoch 4/60
Model trained in 2.97s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 141.822
  Epoch 5/60
Model trained in 2.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 134.042
  Epoch 6/60
Model trained in 2.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 126.999
  Epoch 7/60
Model trained in 2.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 120.519
  Epoch 8/60
Model trained in 2.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 114.573
  Epoch 9/60
Model trained in 2.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 109.120
  Epoch 10/60
Model trained in 2.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 104.270
  Epoch 11/60
Model trained in 2.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 100.043
  Epoch 12/60
Model trained in 2.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 96.287
  Epoch 13/60
Model trained in 2.99s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.597
  Epoch 14/60
Model trained in 2.98s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.040
  Epoch 15/60
Model trained in 2.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.608
  Epoch 16/60
Model trained in 2.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.908
  Epoch 17/60
Model trained in 2.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.616
  Epoch 18/60
Model trained in 2.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.337
  Epoch 19/60
Model trained in 2.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.044
  Epoch 20/60
Model trained in 3.13s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.889
  Epoch 21/60
Model trained in 2.95s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.025
  Epoch 22/60
Model trained in 2.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.661
  Epoch 23/60
Model trained in 3.17s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.970
  Epoch 24/60
Model trained in 2.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.322
  Epoch 25/60
Model trained in 2.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.941
  Epoch 26/60
Model trained in 2.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.808
  Epoch 27/60
Model trained in 2.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.468
  Epoch 28/60
Model trained in 2.65s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.196
  Epoch 29/60
Model trained in 2.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.538
  Epoch 30/60
Model trained in 2.95s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.055
  Epoch 31/60
Model trained in 3.10s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.985
  Epoch 32/60
Model trained in 2.99s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.952
  Epoch 33/60
Model trained in 2.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.470
  Epoch 34/60
Model trained in 3.15s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.452
  Epoch 35/60
Model trained in 2.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.923
  Epoch 36/60
Model trained in 2.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.394
  Epoch 37/60
Model trained in 3.29s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.270
  Epoch 38/60
Model trained in 3.12s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.322
  Epoch 39/60
Model trained in 3.17s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.879
  Epoch 40/60
Model trained in 3.13s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.236
  Epoch 41/60
Model trained in 3.13s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.932
  Epoch 42/60
Model trained in 3.16s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.621
  Epoch 43/60
Model trained in 3.13s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.541
  Epoch 44/60
Model trained in 3.14s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.684
  Epoch 45/60
Model trained in 2.99s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.980
  Epoch 46/60
Model trained in 3.12s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.601
  Epoch 47/60
Model trained in 3.17s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.171
  Early stopping triggered.

  best_val_SMAPE=74.468

Combination 743/1152: {'encoder_hidden_size': 33, 'encoder_layers': 2, 'encoder_dropout': 0.2, 'decoder_hidden_size': 48, 'decoder_layers': 1, 'decoder_dropout': 0.0, 'learning_rate': 0.0005, 'max_epochs': 60, 'patience': 20, 'batch_size': 64, 'sequence_length': 24}
Time: 2.78 minutes - estimated total time: 4.30 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 1.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 181.013
  Epoch 2/60
Model trained in 1.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 172.958
  Epoch 3/60
Model trained in 1.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 166.254
  Epoch 4/60
Model trained in 1.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 160.285
  Epoch 5/60
Model trained in 1.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 154.957
  Epoch 6/60
Model trained in 1.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 150.156
  Epoch 7/60
Model trained in 1.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 145.637
  Epoch 8/60
Model trained in 1.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 141.476
  Epoch 9/60
Model trained in 1.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 137.694
  Epoch 10/60
Model trained in 1.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 134.292
  Epoch 11/60
Model trained in 1.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 130.047
  Epoch 12/60
Model trained in 1.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 126.560
  Epoch 13/60
Model trained in 1.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 123.231
  Epoch 14/60
Model trained in 1.68s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 120.418
  Epoch 15/60
Model trained in 1.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 117.022
  Epoch 16/60
Model trained in 1.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 114.107
  Epoch 17/60
Model trained in 1.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 111.351
  Epoch 18/60
Model trained in 1.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 108.815
  Epoch 19/60
Model trained in 1.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 106.167
  Epoch 20/60
Model trained in 1.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 109.251
  Epoch 21/60
Model trained in 1.67s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 101.053
  Epoch 22/60
Model trained in 1.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 98.974
  Epoch 23/60
Model trained in 1.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 97.235
  Epoch 24/60
Model trained in 1.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 95.498
  Epoch 25/60
Model trained in 1.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.595
  Epoch 26/60
Model trained in 1.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.568
  Epoch 27/60
Model trained in 1.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.484
  Epoch 28/60
Model trained in 1.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.956
  Epoch 29/60
Model trained in 1.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.339
  Epoch 30/60
Model trained in 1.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.161
  Epoch 31/60
Model trained in 1.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.739
  Epoch 32/60
Model trained in 1.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.543
  Epoch 33/60
Model trained in 1.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.353
  Epoch 34/60
Model trained in 1.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.435
  Epoch 35/60
Model trained in 1.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.563
  Epoch 36/60
Model trained in 1.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.556
  Epoch 37/60
Model trained in 1.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.985
  Epoch 38/60
Model trained in 1.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.617
  Epoch 39/60
Model trained in 1.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.536
  Epoch 40/60
Model trained in 1.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.639
  Epoch 41/60
Model trained in 1.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.563
  Epoch 42/60
Model trained in 1.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.333
  Epoch 43/60
Model trained in 1.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.343
  Epoch 44/60
Model trained in 1.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.214
  Epoch 45/60
Model trained in 1.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.870
  Epoch 46/60
Model trained in 2.01s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.946
  Epoch 47/60
Model trained in 1.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.715
  Epoch 48/60
Model trained in 1.95s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.684
  Epoch 49/60
Model trained in 2.14s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.270
  Epoch 50/60
Model trained in 2.05s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.510
  Epoch 51/60
Model trained in 2.65s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.293
  Epoch 52/60
Model trained in 2.23s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.460
  Epoch 53/60
Model trained in 2.09s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.391
  Early stopping triggered.

  best_val_SMAPE=84.353

Combination 744/1152: {'encoder_hidden_size': 33, 'encoder_layers': 2, 'encoder_dropout': 0.2, 'decoder_hidden_size': 48, 'decoder_layers': 1, 'decoder_dropout': 0.0, 'learning_rate': 0.0005, 'max_epochs': 60, 'patience': 20, 'batch_size': 64, 'sequence_length': 168}
Time: 4.84 minutes - estimated total time: 7.49 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 2.19s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 181.078
  Epoch 2/60
Model trained in 2.22s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 173.058
  Epoch 3/60
Model trained in 2.18s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 166.388
  Epoch 4/60
Model trained in 2.32s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 160.441
  Epoch 5/60
Model trained in 2.16s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 155.120
  Epoch 6/60
Model trained in 2.32s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 150.272
  Epoch 7/60
Model trained in 2.17s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 145.835
  Epoch 8/60
Model trained in 2.41s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 141.804
  Epoch 9/60
Model trained in 2.67s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 137.750
  Epoch 10/60
Model trained in 2.45s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 133.916
  Epoch 11/60
Model trained in 2.18s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 130.247
  Epoch 12/60
Model trained in 2.15s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 126.995
  Epoch 13/60
Model trained in 2.14s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 123.715
  Epoch 14/60
Model trained in 2.21s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 120.568
  Epoch 15/60
Model trained in 2.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 117.602
  Epoch 16/60
Model trained in 2.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 115.273
  Epoch 17/60
Model trained in 2.10s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 112.390
  Epoch 18/60
Model trained in 2.06s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 109.781
  Epoch 19/60
Model trained in 2.08s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 107.163
  Epoch 20/60
Model trained in 1.97s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 104.767
  Epoch 21/60
Model trained in 2.05s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 102.431
  Epoch 22/60
Model trained in 2.04s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 100.019
  Epoch 23/60
Model trained in 2.08s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 97.978
  Epoch 24/60
Model trained in 2.10s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 95.824
  Epoch 25/60
Model trained in 2.01s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 94.403
  Epoch 26/60
Model trained in 2.31s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.892
  Epoch 27/60
Model trained in 2.16s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.029
  Epoch 28/60
Model trained in 2.30s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.523
  Epoch 29/60
Model trained in 2.16s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.227
  Epoch 30/60
Model trained in 2.23s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.140
  Epoch 31/60
Model trained in 2.17s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.189
  Epoch 32/60
Model trained in 2.13s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.675
  Epoch 33/60
Model trained in 2.01s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.160
  Epoch 34/60
Model trained in 2.18s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.045
  Epoch 35/60
Model trained in 2.10s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.280
  Epoch 36/60
Model trained in 2.08s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.720
  Epoch 37/60
Model trained in 2.07s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.080
  Epoch 38/60
Model trained in 2.01s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.408
  Epoch 39/60
Model trained in 2.07s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.113
  Epoch 40/60
Model trained in 2.04s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.044
  Epoch 41/60
Model trained in 2.14s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.986
  Epoch 42/60
Model trained in 2.02s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.954
  Epoch 43/60
Model trained in 2.15s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.149
  Epoch 44/60
Model trained in 2.24s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.220
  Epoch 45/60
Model trained in 2.13s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.283
  Epoch 46/60
Model trained in 2.05s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.214
  Epoch 47/60
Model trained in 2.05s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.867
  Epoch 48/60
Model trained in 1.97s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.107
  Epoch 49/60
Model trained in 2.12s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.213
  Epoch 50/60
Model trained in 1.97s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.691
  Epoch 51/60
Model trained in 2.12s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.379
  Epoch 52/60
Model trained in 2.05s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.108
  Epoch 53/60
Model trained in 2.12s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.382
  Epoch 54/60
Model trained in 2.17s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.977
  Epoch 55/60
Model trained in 2.05s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.515
  Epoch 56/60
Model trained in 2.12s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.479
  Epoch 57/60
Model trained in 2.08s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.031
  Epoch 58/60
Model trained in 2.10s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.845
  Epoch 59/60
Model trained in 2.01s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.624
  Epoch 60/60
Model trained in 2.09s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.592

  best_val_SMAPE=78.107

Combination 753/1152: {'encoder_hidden_size': 33, 'encoder_layers': 2, 'encoder_dropout': 0.2, 'decoder_hidden_size': 48, 'decoder_layers': 2, 'decoder_dropout': 0.0, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 20, 'batch_size': 32, 'sequence_length': 24}
Time: 7.51 minutes - estimated total time: 11.49 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 3.18s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 161.123
  Epoch 2/60
Model trained in 3.23s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 141.864
  Epoch 3/60
Model trained in 3.27s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 126.575
  Epoch 4/60
Model trained in 3.40s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 115.972
  Epoch 5/60
Model trained in 3.37s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 104.986
  Epoch 6/60
Model trained in 3.41s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 97.334
  Epoch 7/60
Model trained in 3.25s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.081
  Epoch 8/60
Model trained in 3.29s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.555
  Epoch 9/60
Model trained in 3.23s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.050
  Epoch 10/60
Model trained in 3.36s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.379
  Epoch 11/60
Model trained in 3.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.511
  Epoch 12/60
Model trained in 3.38s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.082
  Epoch 13/60
Model trained in 3.20s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.776
  Epoch 14/60
Model trained in 3.39s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.420
  Epoch 15/60
Model trained in 3.33s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.081
  Epoch 16/60
Model trained in 3.10s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.671
  Epoch 17/60
Model trained in 3.04s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.919
  Epoch 18/60
Model trained in 3.36s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.377
  Epoch 19/60
Model trained in 3.34s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.894
  Epoch 20/60
Model trained in 3.31s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.582
  Epoch 21/60
Model trained in 3.30s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.863
  Epoch 22/60
Model trained in 3.41s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.399
  Epoch 23/60
Model trained in 3.39s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.800
  Epoch 24/60
Model trained in 3.39s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.312
  Epoch 25/60
Model trained in 3.42s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.695
  Epoch 26/60
Model trained in 3.36s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.724
  Epoch 27/60
Model trained in 3.36s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.751
  Epoch 28/60
Model trained in 3.30s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.096
  Epoch 29/60
Model trained in 3.19s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.546
  Epoch 30/60
Model trained in 3.18s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.519
  Epoch 31/60
Model trained in 3.27s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.164
  Epoch 32/60
Model trained in 3.27s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.699
  Epoch 33/60
Model trained in 3.22s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.322
  Epoch 34/60
Model trained in 3.22s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.331
  Epoch 35/60
Model trained in 3.27s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.408
  Epoch 36/60
Model trained in 3.20s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.746
  Early stopping triggered.

  best_val_SMAPE=75.671

Combination 754/1152: {'encoder_hidden_size': 33, 'encoder_layers': 2, 'encoder_dropout': 0.2, 'decoder_hidden_size': 48, 'decoder_layers': 2, 'decoder_dropout': 0.0, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 20, 'batch_size': 32, 'sequence_length': 168}
Time: 9.86 minutes - estimated total time: 15.06 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 3.52s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 161.273
  Epoch 2/60
Model trained in 3.44s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 142.097
  Epoch 3/60
Model trained in 3.44s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 126.865
  Epoch 4/60
Model trained in 3.35s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 115.813
  Epoch 5/60
Model trained in 3.34s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 106.405
  Epoch 6/60
Model trained in 3.15s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 97.488
  Epoch 7/60
Model trained in 3.18s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.491
  Epoch 8/60
Model trained in 3.53s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.479
  Epoch 9/60
Model trained in 3.46s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.637
  Epoch 10/60
Model trained in 3.48s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.048
  Epoch 11/60
Model trained in 3.41s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.682
  Epoch 12/60
Model trained in 3.35s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.230
  Epoch 13/60
Model trained in 3.25s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.933
  Epoch 14/60
Model trained in 3.35s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.756
  Epoch 15/60
Model trained in 3.44s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.327
  Epoch 16/60
Model trained in 3.37s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.217
  Epoch 17/60
Model trained in 3.37s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.237
  Epoch 18/60
Model trained in 3.24s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.623
  Epoch 19/60
Model trained in 3.38s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.683
  Epoch 20/60
Model trained in 3.67s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.121
  Epoch 21/60
Model trained in 3.55s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.136
  Epoch 22/60
Model trained in 3.60s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.424
  Epoch 23/60
Model trained in 3.26s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.734
  Epoch 24/60
Model trained in 3.34s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.137
  Epoch 25/60
Model trained in 3.36s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.240
  Epoch 26/60
Model trained in 3.40s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.144
  Epoch 27/60
Model trained in 3.35s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.772
  Epoch 28/60
Model trained in 3.28s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.581
  Epoch 29/60
Model trained in 3.32s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.690
  Epoch 30/60
Model trained in 3.28s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.041
  Early stopping triggered.

  best_val_SMAPE=78.048

Combination 755/1152: {'encoder_hidden_size': 33, 'encoder_layers': 2, 'encoder_dropout': 0.2, 'decoder_hidden_size': 48, 'decoder_layers': 2, 'decoder_dropout': 0.0, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 20, 'batch_size': 64, 'sequence_length': 24}
Time: 11.83 minutes - estimated total time: 18.06 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 2.07s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 173.863
  Epoch 2/60
Model trained in 2.10s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 160.994
  Epoch 3/60
Model trained in 2.02s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 150.610
  Epoch 4/60
Model trained in 2.01s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 141.682
  Epoch 5/60
Model trained in 2.09s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 133.736
  Epoch 6/60
Model trained in 2.12s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 126.327
  Epoch 7/60
Model trained in 2.05s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 119.422
  Epoch 8/60
Model trained in 2.16s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 113.208
  Epoch 9/60
Model trained in 2.08s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 111.121
  Epoch 10/60
Model trained in 2.07s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 107.814
  Epoch 11/60
Model trained in 2.04s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 103.330
  Epoch 12/60
Model trained in 2.01s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 100.832
  Epoch 13/60
Model trained in 2.03s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 100.758
  Epoch 14/60
Model trained in 2.12s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 98.091
  Epoch 15/60
Model trained in 2.03s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 95.187
  Epoch 16/60
Model trained in 2.16s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.536
  Epoch 17/60
Model trained in 2.08s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.651
  Epoch 18/60
Model trained in 2.07s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.808
  Epoch 19/60
Model trained in 2.20s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.696
  Epoch 20/60
Model trained in 2.14s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.264
  Epoch 21/60
Model trained in 2.01s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.171
  Epoch 22/60
Model trained in 2.08s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.505
  Epoch 23/60
Model trained in 2.07s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.021
  Epoch 24/60
Model trained in 2.13s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.461
  Epoch 25/60
Model trained in 1.98s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.835
  Epoch 26/60
Model trained in 2.05s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.619
  Epoch 27/60
Model trained in 2.03s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.765
  Epoch 28/60
Model trained in 2.17s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.245
  Epoch 29/60
Model trained in 2.10s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.360
  Epoch 30/60
Model trained in 2.07s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.039
  Epoch 31/60
Model trained in 2.13s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.607
  Epoch 32/60
Model trained in 2.11s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.981
  Epoch 33/60
Model trained in 2.11s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.485
  Epoch 34/60
Model trained in 2.11s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.804
  Epoch 35/60
Model trained in 2.15s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.339
  Epoch 36/60
Model trained in 1.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.261
  Epoch 37/60
Model trained in 2.03s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.156
  Epoch 38/60
Model trained in 2.04s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.516
  Epoch 39/60
Model trained in 2.01s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.053
  Epoch 40/60
Model trained in 1.95s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.056
  Epoch 41/60
Model trained in 2.01s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.632
  Epoch 42/60
Model trained in 1.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.601
  Epoch 43/60
Model trained in 2.07s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.354
  Epoch 44/60
Model trained in 2.14s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.581
  Epoch 45/60
Model trained in 2.02s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.837
  Epoch 46/60
Model trained in 1.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.395
  Epoch 47/60
Model trained in 2.15s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.735
  Epoch 48/60
Model trained in 1.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.105
  Epoch 49/60
Model trained in 2.03s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.652
  Epoch 50/60
Model trained in 1.99s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.094
  Epoch 51/60
Model trained in 2.01s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.383
  Epoch 52/60
Model trained in 1.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.007
  Epoch 53/60
Model trained in 2.09s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.645
  Epoch 54/60
Model trained in 1.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.578
  Epoch 55/60
Model trained in 2.00s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.678
  Epoch 56/60
Model trained in 1.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.725
  Epoch 57/60
Model trained in 2.20s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.162
  Epoch 58/60
Model trained in 1.99s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.094
  Epoch 59/60
Model trained in 2.20s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.016
  Epoch 60/60
Model trained in 2.02s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.638

  best_val_SMAPE=75.638

Combination 756/1152: {'encoder_hidden_size': 33, 'encoder_layers': 2, 'encoder_dropout': 0.2, 'decoder_hidden_size': 48, 'decoder_layers': 2, 'decoder_dropout': 0.0, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 20, 'batch_size': 64, 'sequence_length': 168}
Time: 14.43 minutes - estimated total time: 22.00 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 2.22s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 173.988
  Epoch 2/60
Model trained in 2.21s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 161.183
  Epoch 3/60
Model trained in 2.22s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 150.831
  Epoch 4/60
Model trained in 2.14s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 141.936
  Epoch 5/60
Model trained in 2.14s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 134.021
  Epoch 6/60
Model trained in 2.59s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 126.633
  Epoch 7/60
Model trained in 2.25s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 121.944
  Epoch 8/60
Model trained in 2.41s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 116.405
  Epoch 9/60
Model trained in 2.14s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 110.517
  Epoch 10/60
Model trained in 2.19s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 105.562
  Epoch 11/60
Model trained in 2.20s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 100.958
  Epoch 12/60
Model trained in 2.14s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 97.621
  Epoch 13/60
Model trained in 2.19s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.740
  Epoch 14/60
Model trained in 2.34s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.934
  Epoch 15/60
Model trained in 2.19s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.321
  Epoch 16/60
Model trained in 2.26s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.291
  Epoch 17/60
Model trained in 2.23s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.167
  Epoch 18/60
Model trained in 2.25s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.448
  Epoch 19/60
Model trained in 2.14s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.836
  Epoch 20/60
Model trained in 2.26s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.495
  Epoch 21/60
Model trained in 2.08s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.209
  Epoch 22/60
Model trained in 2.29s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.831
  Epoch 23/60
Model trained in 2.20s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.881
  Epoch 24/60
Model trained in 2.28s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.867
  Epoch 25/60
Model trained in 2.25s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.749
  Epoch 26/60
Model trained in 2.30s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.082
  Epoch 27/60
Model trained in 2.31s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.987
  Epoch 28/60
Model trained in 2.55s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.201
  Epoch 29/60
Model trained in 2.41s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.894
  Epoch 30/60
Model trained in 2.31s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.721
  Epoch 31/60
Model trained in 2.30s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.019
  Epoch 32/60
Model trained in 2.35s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.662
  Epoch 33/60
Model trained in 2.30s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.862
  Epoch 34/60
Model trained in 2.32s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.221
  Epoch 35/60
Model trained in 2.23s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.029
  Epoch 36/60
Model trained in 2.25s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.457
  Epoch 37/60
Model trained in 2.15s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.058
  Epoch 38/60
Model trained in 2.19s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.069
  Epoch 39/60
Model trained in 2.16s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.204
  Epoch 40/60
Model trained in 2.17s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.248
  Epoch 41/60
Model trained in 2.18s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.980
  Epoch 42/60
Model trained in 2.14s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.166
  Epoch 43/60
Model trained in 2.18s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.196
  Early stopping triggered.

  best_val_SMAPE=75.881

Combination 757/1152: {'encoder_hidden_size': 33, 'encoder_layers': 2, 'encoder_dropout': 0.2, 'decoder_hidden_size': 48, 'decoder_layers': 2, 'decoder_dropout': 0.0, 'learning_rate': 0.0005, 'max_epochs': 60, 'patience': 20, 'batch_size': 32, 'sequence_length': 24}
Time: 16.44 minutes - estimated total time: 25.02 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 3.20s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 173.937
  Epoch 2/60
Model trained in 3.29s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 161.161
  Epoch 3/60
Model trained in 3.15s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 150.835
  Epoch 4/60
Model trained in 3.20s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 141.932
  Epoch 5/60
Model trained in 3.30s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 133.983
  Epoch 6/60
Model trained in 3.20s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 126.556
  Epoch 7/60
Model trained in 3.12s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 119.635
  Epoch 8/60
Model trained in 3.24s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 113.351
  Epoch 9/60
Model trained in 3.28s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 110.202
  Epoch 10/60
Model trained in 3.12s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 104.803
  Epoch 11/60
Model trained in 3.36s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 100.722
  Epoch 12/60
Model trained in 3.23s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 97.414
  Epoch 13/60
Model trained in 3.20s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.124
  Epoch 14/60
Model trained in 3.18s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.045
  Epoch 15/60
Model trained in 3.29s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.792
  Epoch 16/60
Model trained in 3.21s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.983
  Epoch 17/60
Model trained in 3.12s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.001
  Epoch 18/60
Model trained in 3.36s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.518
  Epoch 19/60
Model trained in 3.35s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.338
  Epoch 20/60
Model trained in 3.17s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.064
  Epoch 21/60
Model trained in 3.26s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.447
  Epoch 22/60
Model trained in 3.26s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.645
  Epoch 23/60
Model trained in 3.41s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.399
  Epoch 24/60
Model trained in 3.27s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.418
  Epoch 25/60
Model trained in 3.31s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.768
  Epoch 26/60
Model trained in 3.24s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.858
  Epoch 27/60
Model trained in 3.13s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.049
  Epoch 28/60
Model trained in 3.19s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.105
  Epoch 29/60
Model trained in 3.27s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.214
  Epoch 30/60
Model trained in 3.13s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.755
  Epoch 31/60
Model trained in 3.21s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.921
  Epoch 32/60
Model trained in 3.28s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.270
  Epoch 33/60
Model trained in 3.22s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.974
  Epoch 34/60
Model trained in 3.10s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.083
  Epoch 35/60
Model trained in 3.26s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.761
  Epoch 36/60
Model trained in 3.19s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.404
  Epoch 37/60
Model trained in 3.17s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.530
  Epoch 38/60
Model trained in 3.33s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.526
  Epoch 39/60
Model trained in 3.28s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.137
  Epoch 40/60
Model trained in 3.09s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.945
  Epoch 41/60
Model trained in 3.24s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.968
  Epoch 42/60
Model trained in 3.26s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.056
  Epoch 43/60
Model trained in 3.21s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.123
  Epoch 44/60
Model trained in 3.20s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.884
  Epoch 45/60
Model trained in 3.22s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.930
  Epoch 46/60
Model trained in 3.25s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.809
  Epoch 47/60
Model trained in 3.30s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.876
  Epoch 48/60
Model trained in 3.35s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.279
  Epoch 49/60
Model trained in 3.24s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.488
  Epoch 50/60
Model trained in 3.29s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.896
  Epoch 51/60
Model trained in 3.28s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.904
  Epoch 52/60
Model trained in 3.25s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.420
  Epoch 53/60
Model trained in 3.26s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.661
  Epoch 54/60
Model trained in 3.22s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.635
  Early stopping triggered.

  best_val_SMAPE=75.083

Combination 758/1152: {'encoder_hidden_size': 33, 'encoder_layers': 2, 'encoder_dropout': 0.2, 'decoder_hidden_size': 48, 'decoder_layers': 2, 'decoder_dropout': 0.0, 'learning_rate': 0.0005, 'max_epochs': 60, 'patience': 20, 'batch_size': 32, 'sequence_length': 168}
Time: 19.82 minutes - estimated total time: 30.11 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 3.36s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 174.216
  Epoch 2/60
Model trained in 3.22s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 161.418
  Epoch 3/60
Model trained in 3.37s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 151.091
  Epoch 4/60
Model trained in 3.38s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 142.202
  Epoch 5/60
Model trained in 3.25s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 134.274
  Epoch 6/60
Model trained in 3.32s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 126.868
  Epoch 7/60
Model trained in 3.38s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 119.960
  Epoch 8/60
Model trained in 3.36s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 113.686
  Epoch 9/60
Model trained in 3.18s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 110.559
  Epoch 10/60
Model trained in 3.42s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 108.140
  Epoch 11/60
Model trained in 3.37s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 104.751
  Epoch 12/60
Model trained in 3.22s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 101.640
  Epoch 13/60
Model trained in 3.35s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 96.884
  Epoch 14/60
Model trained in 3.20s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.754
  Epoch 15/60
Model trained in 3.32s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.321
  Epoch 16/60
Model trained in 3.36s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.205
  Epoch 17/60
Model trained in 3.33s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.414
  Epoch 18/60
Model trained in 3.36s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.650
  Epoch 19/60
Model trained in 3.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.616
  Epoch 20/60
Model trained in 3.37s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.585
  Epoch 21/60
Model trained in 3.35s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.473
  Epoch 22/60
Model trained in 3.48s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.411
  Epoch 23/60
Model trained in 3.37s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.193
  Epoch 24/60
Model trained in 3.26s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.831
  Epoch 25/60
Model trained in 3.40s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.729
  Epoch 26/60
Model trained in 3.37s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.137
  Epoch 27/60
Model trained in 3.32s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.209
  Epoch 28/60
Model trained in 3.30s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.316
  Epoch 29/60
Model trained in 3.39s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.478
  Epoch 30/60
Model trained in 3.32s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.804
  Epoch 31/60
Model trained in 3.29s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.284
  Epoch 32/60
Model trained in 3.35s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.670
  Epoch 33/60
Model trained in 3.35s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.172
  Epoch 34/60
Model trained in 3.34s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.927
  Epoch 35/60
Model trained in 3.44s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.648
  Epoch 36/60
Model trained in 3.43s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.544
  Epoch 37/60
Model trained in 3.25s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.716
  Epoch 38/60
Model trained in 3.30s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.378
  Epoch 39/60
Model trained in 3.46s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.362
  Epoch 40/60
Model trained in 3.32s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.218
  Epoch 41/60
Model trained in 3.17s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.586
  Epoch 42/60
Model trained in 3.48s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.585
  Epoch 43/60
Model trained in 3.35s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.994
  Epoch 44/60
Model trained in 3.24s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.746
  Epoch 45/60
Model trained in 3.35s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.276
  Early stopping triggered.

  best_val_SMAPE=78.729

Combination 759/1152: {'encoder_hidden_size': 33, 'encoder_layers': 2, 'encoder_dropout': 0.2, 'decoder_hidden_size': 48, 'decoder_layers': 2, 'decoder_dropout': 0.0, 'learning_rate': 0.0005, 'max_epochs': 60, 'patience': 20, 'batch_size': 64, 'sequence_length': 24}
Time: 22.72 minutes - estimated total time: 34.48 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 1.97s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 182.086
  Epoch 2/60
Model trained in 1.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 173.822
  Epoch 3/60
Model trained in 1.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 167.054
  Epoch 4/60
Model trained in 1.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 161.034
  Epoch 5/60
Model trained in 2.03s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 155.638
  Epoch 6/60
Model trained in 2.05s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 150.680
  Epoch 7/60
Model trained in 2.20s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 146.077
  Epoch 8/60
Model trained in 1.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 141.743
  Epoch 9/60
Model trained in 2.08s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 137.659
  Epoch 10/60
Model trained in 1.95s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 133.761
  Epoch 11/60
Model trained in 2.01s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 129.966
  Epoch 12/60
Model trained in 2.03s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 126.299
  Epoch 13/60
Model trained in 1.99s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 123.197
  Epoch 14/60
Model trained in 2.10s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 121.971
  Epoch 15/60
Model trained in 2.00s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 120.500
  Epoch 16/60
Model trained in 2.08s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 117.636
  Epoch 17/60
Model trained in 1.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 114.472
  Epoch 18/60
Model trained in 1.98s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 113.029
  Epoch 19/60
Model trained in 2.07s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 110.278
  Epoch 20/60
Model trained in 2.11s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 108.089
  Epoch 21/60
Model trained in 1.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 105.137
  Epoch 22/60
Model trained in 2.05s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 102.609
  Epoch 23/60
Model trained in 1.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 99.931
  Epoch 24/60
Model trained in 1.99s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 97.608
  Epoch 25/60
Model trained in 1.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 95.687
  Epoch 26/60
Model trained in 1.99s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.337
  Epoch 27/60
Model trained in 2.00s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.630
  Epoch 28/60
Model trained in 1.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.966
  Epoch 29/60
Model trained in 1.95s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.168
  Epoch 30/60
Model trained in 1.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.442
  Epoch 31/60
Model trained in 2.12s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.331
  Epoch 32/60
Model trained in 2.15s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.263
  Epoch 33/60
Model trained in 2.23s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.611
  Epoch 34/60
Model trained in 1.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.595
  Epoch 35/60
Model trained in 2.05s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.966
  Epoch 36/60
Model trained in 1.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.717
  Epoch 37/60
Model trained in 2.05s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.462
  Epoch 38/60
Model trained in 2.04s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.276
  Epoch 39/60
Model trained in 2.14s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.052
  Epoch 40/60
Model trained in 2.04s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.529
  Epoch 41/60
Model trained in 1.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.631
  Epoch 42/60
Model trained in 2.13s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.920
  Epoch 43/60
Model trained in 2.05s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.326
  Epoch 44/60
Model trained in 2.14s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.603
  Epoch 45/60
Model trained in 2.07s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.390
  Epoch 46/60
Model trained in 2.24s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.285
  Epoch 47/60
Model trained in 2.13s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.907
  Epoch 48/60
Model trained in 2.20s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.510
  Epoch 49/60
Model trained in 1.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.430
  Epoch 50/60
Model trained in 2.08s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.972
  Epoch 51/60
Model trained in 1.95s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.975
  Epoch 52/60
Model trained in 2.18s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.015
  Epoch 53/60
Model trained in 2.16s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.641
  Epoch 54/60
Model trained in 2.07s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.397
  Epoch 55/60
Model trained in 2.11s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.578
  Epoch 56/60
Model trained in 1.97s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.195
  Epoch 57/60
Model trained in 2.00s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.380
  Epoch 58/60
Model trained in 1.99s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.586
  Epoch 59/60
Model trained in 2.28s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.408
  Epoch 60/60
Model trained in 2.16s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.013

  best_val_SMAPE=74.285

Combination 760/1152: {'encoder_hidden_size': 33, 'encoder_layers': 2, 'encoder_dropout': 0.2, 'decoder_hidden_size': 48, 'decoder_layers': 2, 'decoder_dropout': 0.0, 'learning_rate': 0.0005, 'max_epochs': 60, 'patience': 20, 'batch_size': 64, 'sequence_length': 168}
Time: 25.27 minutes - estimated total time: 38.31 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 2.36s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 182.170
  Epoch 2/60
Model trained in 2.37s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 173.921
  Epoch 3/60
Model trained in 2.30s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 167.191
  Epoch 4/60
Model trained in 2.32s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 161.202
  Epoch 5/60
Model trained in 2.40s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 155.825
  Epoch 6/60
Model trained in 2.16s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 150.882
  Epoch 7/60
Model trained in 2.20s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 146.299
  Epoch 8/60
Model trained in 2.31s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 141.979
  Epoch 9/60
Model trained in 2.41s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 137.909
  Epoch 10/60
Model trained in 2.36s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 134.029
  Epoch 11/60
Model trained in 2.41s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 130.253
  Epoch 12/60
Model trained in 2.07s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 126.599
  Epoch 13/60
Model trained in 2.01s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 124.822
  Epoch 14/60
Model trained in 2.41s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 121.951
  Epoch 15/60
Model trained in 2.19s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 119.058
  Epoch 16/60
Model trained in 2.44s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 116.220
  Epoch 17/60
Model trained in 2.20s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 113.456
  Epoch 18/60
Model trained in 2.39s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 110.803
  Epoch 19/60
Model trained in 2.28s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 108.332
  Epoch 20/60
Model trained in 2.33s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 106.737
  Epoch 21/60
Model trained in 2.49s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 104.434
  Epoch 22/60
Model trained in 2.30s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 102.636
  Epoch 23/60
Model trained in 2.32s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 101.717
  Epoch 24/60
Model trained in 2.21s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 100.629
  Epoch 25/60
Model trained in 2.45s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 98.413
  Epoch 26/60
Model trained in 2.20s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 96.511
  Epoch 27/60
Model trained in 2.41s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 94.791
  Epoch 28/60
Model trained in 2.19s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.949
  Epoch 29/60
Model trained in 2.42s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.165
  Epoch 30/60
Model trained in 2.25s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.948
  Epoch 31/60
Model trained in 2.34s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.885
  Epoch 32/60
Model trained in 2.36s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.282
  Epoch 33/60
Model trained in 2.23s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.262
  Epoch 34/60
Model trained in 2.20s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.792
  Epoch 35/60
Model trained in 2.17s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.833
  Epoch 36/60
Model trained in 2.34s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.992
  Epoch 37/60
Model trained in 2.12s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.541
  Epoch 38/60
Model trained in 2.17s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.698
  Epoch 39/60
Model trained in 2.15s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.046
  Epoch 40/60
Model trained in 2.09s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.876
  Epoch 41/60
Model trained in 2.19s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.437
  Epoch 42/60
Model trained in 2.21s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.782
  Epoch 43/60
Model trained in 2.21s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.866
  Epoch 44/60
Model trained in 2.07s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.551
  Epoch 45/60
Model trained in 2.18s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.579
  Epoch 46/60
Model trained in 2.12s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.259
  Epoch 47/60
Model trained in 2.18s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.669
  Epoch 48/60
Model trained in 2.16s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.177
  Epoch 49/60
Model trained in 2.23s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.228
  Epoch 50/60
Model trained in 2.19s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.334
  Epoch 51/60
Model trained in 2.09s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.761
  Epoch 52/60
Model trained in 2.17s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.015
  Epoch 53/60
Model trained in 2.07s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.440
  Epoch 54/60
Model trained in 2.23s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.944
  Epoch 55/60
Model trained in 2.15s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.152
  Epoch 56/60
Model trained in 2.22s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.798
  Epoch 57/60
Model trained in 2.09s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.957
  Epoch 58/60
Model trained in 2.19s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.780
  Epoch 59/60
Model trained in 2.20s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.340
  Epoch 60/60
Model trained in 2.11s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.639

  best_val_SMAPE=75.340

Combination 761/1152: {'encoder_hidden_size': 33, 'encoder_layers': 2, 'encoder_dropout': 0.2, 'decoder_hidden_size': 48, 'decoder_layers': 2, 'decoder_dropout': 0.2, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 20, 'batch_size': 32, 'sequence_length': 24}
Time: 28.06 minutes - estimated total time: 42.48 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 3.12s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 161.114
  Epoch 2/60
Model trained in 3.17s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 141.859
  Epoch 3/60
Model trained in 3.26s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 126.571
  Epoch 4/60
Model trained in 3.25s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 113.662
  Epoch 5/60
Model trained in 3.30s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 107.456
  Epoch 6/60
Model trained in 3.19s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 99.308
  Epoch 7/60
Model trained in 3.30s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.011
  Epoch 8/60
Model trained in 3.23s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.741
  Epoch 9/60
Model trained in 3.13s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.778
  Epoch 10/60
Model trained in 3.11s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.699
  Epoch 11/60
Model trained in 3.24s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.414
  Epoch 12/60
Model trained in 3.25s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.026
  Epoch 13/60
Model trained in 3.19s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.778
  Epoch 14/60
Model trained in 3.19s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.574
  Epoch 15/60
Model trained in 3.24s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.870
  Epoch 16/60
Model trained in 3.16s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.260
  Epoch 17/60
Model trained in 3.28s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.744
  Epoch 18/60
Model trained in 3.16s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.185
  Epoch 19/60
Model trained in 3.13s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.392
  Epoch 20/60
Model trained in 3.14s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.174
  Epoch 21/60
Model trained in 3.20s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.279
  Epoch 22/60
Model trained in 3.18s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.524
  Epoch 23/60
Model trained in 3.16s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.290
  Epoch 24/60
Model trained in 3.23s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.269
  Epoch 25/60
Model trained in 3.26s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.777
  Epoch 26/60
Model trained in 3.34s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.100
  Epoch 27/60
Model trained in 3.22s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.175
  Epoch 28/60
Model trained in 3.13s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.595
  Epoch 29/60
Model trained in 3.08s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.258
  Epoch 30/60
Model trained in 3.25s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.850
  Epoch 31/60
Model trained in 3.17s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.144
  Epoch 32/60
Model trained in 3.18s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.048
  Epoch 33/60
Model trained in 3.12s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.902
  Early stopping triggered.

  best_val_SMAPE=75.778

Combination 762/1152: {'encoder_hidden_size': 33, 'encoder_layers': 2, 'encoder_dropout': 0.2, 'decoder_hidden_size': 48, 'decoder_layers': 2, 'decoder_dropout': 0.2, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 20, 'batch_size': 32, 'sequence_length': 168}
Time: 30.11 minutes - estimated total time: 45.52 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 3.36s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 161.265
  Epoch 2/60
Model trained in 3.45s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 142.091
  Epoch 3/60
Model trained in 3.34s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 126.864
  Epoch 4/60
Model trained in 3.30s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 115.355
  Epoch 5/60
Model trained in 3.38s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 106.140
  Epoch 6/60
Model trained in 3.38s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 99.307
  Epoch 7/60
Model trained in 3.38s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.940
  Epoch 8/60
Model trained in 3.30s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.880
  Epoch 9/60
Model trained in 3.26s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.957
  Epoch 10/60
Model trained in 3.38s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.029
  Epoch 11/60
Model trained in 3.28s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.946
  Epoch 12/60
Model trained in 3.33s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.998
  Epoch 13/60
Model trained in 3.23s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.693
  Epoch 14/60
Model trained in 3.63s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.011
  Epoch 15/60
Model trained in 3.39s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.900
  Epoch 16/60
Model trained in 3.32s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.495
  Epoch 17/60
Model trained in 3.27s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.563
  Epoch 18/60
Model trained in 3.26s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.145
  Epoch 19/60
Model trained in 3.36s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.744
  Epoch 20/60
Model trained in 3.31s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.043
  Epoch 21/60
Model trained in 3.31s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.141
  Epoch 22/60
Model trained in 3.41s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.398
  Epoch 23/60
Model trained in 3.34s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.169
  Epoch 24/60
Model trained in 3.31s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.312
  Epoch 25/60
Model trained in 3.36s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.291
  Epoch 26/60
Model trained in 3.34s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.287
  Epoch 27/60
Model trained in 3.36s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.910
  Epoch 28/60
Model trained in 3.27s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.091
  Epoch 29/60
Model trained in 3.24s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.965
  Epoch 30/60
Model trained in 3.34s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.775
  Epoch 31/60
Model trained in 3.38s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.328
  Early stopping triggered.

  best_val_SMAPE=79.946

Combination 763/1152: {'encoder_hidden_size': 33, 'encoder_layers': 2, 'encoder_dropout': 0.2, 'decoder_hidden_size': 48, 'decoder_layers': 2, 'decoder_dropout': 0.2, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 20, 'batch_size': 64, 'sequence_length': 24}
Time: 32.12 minutes - estimated total time: 48.49 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 1.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 173.845
  Epoch 2/60
Model trained in 2.02s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 160.984
  Epoch 3/60
Model trained in 1.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 150.603
  Epoch 4/60
Model trained in 2.04s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 141.676
  Epoch 5/60
Model trained in 1.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 133.699
  Epoch 6/60
Model trained in 2.07s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 126.328
  Epoch 7/60
Model trained in 1.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 119.455
  Epoch 8/60
Model trained in 1.97s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 113.400
  Epoch 9/60
Model trained in 1.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 111.128
  Epoch 10/60
Model trained in 2.03s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 107.364
  Epoch 11/60
Model trained in 2.01s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 103.474
  Epoch 12/60
Model trained in 2.02s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 99.029
  Epoch 13/60
Model trained in 2.05s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 94.902
  Epoch 14/60
Model trained in 1.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.805
  Epoch 15/60
Model trained in 2.06s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.769
  Epoch 16/60
Model trained in 1.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.640
  Epoch 17/60
Model trained in 2.06s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.675
  Epoch 18/60
Model trained in 1.97s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.236
  Epoch 19/60
Model trained in 2.02s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.871
  Epoch 20/60
Model trained in 1.95s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.511
  Epoch 21/60
Model trained in 2.18s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.346
  Epoch 22/60
Model trained in 1.99s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.492
  Epoch 23/60
Model trained in 2.02s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.360
  Epoch 24/60
Model trained in 2.00s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.797
  Epoch 25/60
Model trained in 2.02s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.107
  Epoch 26/60
Model trained in 1.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.972
  Epoch 27/60
Model trained in 1.99s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.281
  Epoch 28/60
Model trained in 1.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.913
  Epoch 29/60
Model trained in 2.02s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.609
  Epoch 30/60
Model trained in 2.00s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.366
  Epoch 31/60
Model trained in 1.97s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.420
  Epoch 32/60
Model trained in 2.02s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.342
  Epoch 33/60
Model trained in 1.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.853
  Epoch 34/60
Model trained in 1.98s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.248
  Epoch 35/60
Model trained in 1.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.845
  Epoch 36/60
Model trained in 2.03s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.477
  Epoch 37/60
Model trained in 2.00s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.234
  Epoch 38/60
Model trained in 2.00s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.798
  Epoch 39/60
Model trained in 1.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.778
  Epoch 40/60
Model trained in 2.12s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.941
  Epoch 41/60
Model trained in 2.03s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.161
  Epoch 42/60
Model trained in 2.13s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.913
  Epoch 43/60
Model trained in 2.03s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.261
  Epoch 44/60
Model trained in 2.09s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.114
  Epoch 45/60
Model trained in 2.12s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.554
  Epoch 46/60
Model trained in 2.18s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.015
  Epoch 47/60
Model trained in 2.04s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.204
  Epoch 48/60
Model trained in 2.12s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.923
  Epoch 49/60
Model trained in 2.06s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.832
  Epoch 50/60
Model trained in 2.13s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.848
  Epoch 51/60
Model trained in 2.24s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.270
  Epoch 52/60
Model trained in 2.21s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.271
  Epoch 53/60
Model trained in 2.08s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.013
  Epoch 54/60
Model trained in 2.07s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.301
  Epoch 55/60
Model trained in 2.12s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.625
  Epoch 56/60
Model trained in 2.02s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.240
  Epoch 57/60
Model trained in 2.02s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.989
  Epoch 58/60
Model trained in 1.98s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.699
  Epoch 59/60
Model trained in 2.00s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.614
  Epoch 60/60
Model trained in 2.14s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.741

  best_val_SMAPE=78.013

Combination 764/1152: {'encoder_hidden_size': 33, 'encoder_layers': 2, 'encoder_dropout': 0.2, 'decoder_hidden_size': 48, 'decoder_layers': 2, 'decoder_dropout': 0.2, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 20, 'batch_size': 64, 'sequence_length': 168}
Time: 34.65 minutes - estimated total time: 52.24 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 2.25s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 173.990
  Epoch 2/60
Model trained in 2.40s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 161.179
  Epoch 3/60
Model trained in 2.28s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 150.826
  Epoch 4/60
Model trained in 2.28s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 141.930
  Epoch 5/60
Model trained in 2.18s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 134.016
  Epoch 6/60
Model trained in 2.22s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 126.642
  Epoch 7/60
Model trained in 2.04s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 121.742
  Epoch 8/60
Model trained in 2.22s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 115.984
  Epoch 9/60
Model trained in 2.19s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 111.219
  Epoch 10/60
Model trained in 2.19s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 105.808
  Epoch 11/60
Model trained in 2.29s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 100.880
  Epoch 12/60
Model trained in 2.21s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 97.629
  Epoch 13/60
Model trained in 2.37s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 94.059
  Epoch 14/60
Model trained in 2.13s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.194
  Epoch 15/60
Model trained in 2.16s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.320
  Epoch 16/60
Model trained in 2.05s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.273
  Epoch 17/60
Model trained in 2.30s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.661
  Epoch 18/60
Model trained in 2.22s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.067
  Epoch 19/60
Model trained in 2.21s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.284
  Epoch 20/60
Model trained in 2.11s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.032
  Epoch 21/60
Model trained in 2.30s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.799
  Epoch 22/60
Model trained in 2.26s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.469
  Epoch 23/60
Model trained in 2.19s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.609
  Epoch 24/60
Model trained in 2.39s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.280
  Epoch 25/60
Model trained in 2.33s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.858
  Epoch 26/60
Model trained in 2.28s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.756
  Epoch 27/60
Model trained in 2.12s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.684
  Epoch 28/60
Model trained in 2.21s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.689
  Epoch 29/60
Model trained in 2.12s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.116
  Epoch 30/60
Model trained in 2.23s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.618
  Epoch 31/60
Model trained in 2.16s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.691
  Epoch 32/60
Model trained in 2.17s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.968
  Epoch 33/60
Model trained in 2.33s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.548
  Epoch 34/60
Model trained in 2.30s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.292
  Epoch 35/60
Model trained in 2.34s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.871
  Epoch 36/60
Model trained in 2.20s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.784
  Epoch 37/60
Model trained in 2.20s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 72.814
  Epoch 38/60
Model trained in 2.06s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 72.557
  Epoch 39/60
Model trained in 2.37s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 72.610
  Epoch 40/60
Model trained in 2.25s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.366
  Epoch 41/60
Model trained in 2.32s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.854
  Epoch 42/60
Model trained in 2.32s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.578
  Epoch 43/60
Model trained in 2.22s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 72.991
  Epoch 44/60
Model trained in 2.36s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.332
  Epoch 45/60
Model trained in 2.29s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.647
  Epoch 46/60
Model trained in 2.37s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.751
  Epoch 47/60
Model trained in 2.34s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.776
  Epoch 48/60
Model trained in 2.45s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.162
  Epoch 49/60
Model trained in 2.10s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.239
  Epoch 50/60
Model trained in 2.39s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 72.745
  Epoch 51/60
Model trained in 2.35s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.002
  Epoch 52/60
Model trained in 2.24s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.185
  Epoch 53/60
Model trained in 2.14s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 72.905
  Epoch 54/60
Model trained in 2.07s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 72.837
  Epoch 55/60
Model trained in 2.14s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 72.935
  Epoch 56/60
Model trained in 2.12s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 71.787
  Epoch 57/60
Model trained in 2.18s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 70.895
  Epoch 58/60
Model trained in 2.11s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 70.379
  Epoch 59/60
Model trained in 2.26s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 69.935
  Epoch 60/60
Model trained in 2.33s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 70.088

  best_val_SMAPE=69.935

Combination 765/1152: {'encoder_hidden_size': 33, 'encoder_layers': 2, 'encoder_dropout': 0.2, 'decoder_hidden_size': 48, 'decoder_layers': 2, 'decoder_dropout': 0.2, 'learning_rate': 0.0005, 'max_epochs': 60, 'patience': 20, 'batch_size': 32, 'sequence_length': 24}
Time: 37.42 minutes - estimated total time: 56.34 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 3.46s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 173.886
  Epoch 2/60
Model trained in 3.36s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 161.143
  Epoch 3/60
Model trained in 3.31s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 150.823
  Epoch 4/60
Model trained in 3.31s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 141.922
  Epoch 5/60
Model trained in 3.44s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 133.975
  Epoch 6/60
Model trained in 3.38s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 126.548
  Epoch 7/60
Model trained in 3.38s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 119.627
  Epoch 8/60
Model trained in 3.43s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 113.344
  Epoch 9/60
Model trained in 3.21s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 109.851
  Epoch 10/60
Model trained in 3.26s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 105.512
  Epoch 11/60
Model trained in 3.38s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 103.267
  Epoch 12/60
Model trained in 3.38s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 100.127
  Epoch 13/60
Model trained in 3.43s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 96.287
  Epoch 14/60
Model trained in 3.23s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.202
  Epoch 15/60
Model trained in 3.34s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.805
  Epoch 16/60
Model trained in 3.31s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.460
  Epoch 17/60
Model trained in 3.42s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.018
  Epoch 18/60
Model trained in 3.29s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.952
  Epoch 19/60
Model trained in 3.21s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.263
  Epoch 20/60
Model trained in 3.28s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.672
  Epoch 21/60
Model trained in 3.34s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.923
  Epoch 22/60
Model trained in 3.40s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.172
  Epoch 23/60
Model trained in 3.39s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.250
  Epoch 24/60
Model trained in 3.46s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.973
  Epoch 25/60
Model trained in 3.41s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.526
  Epoch 26/60
Model trained in 3.15s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.365
  Epoch 27/60
Model trained in 3.43s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.966
  Epoch 28/60
Model trained in 3.36s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.661
  Epoch 29/60
Model trained in 3.22s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.203
  Epoch 30/60
Model trained in 3.34s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.965
  Epoch 31/60
Model trained in 3.19s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.698
  Epoch 32/60
Model trained in 3.25s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.250
  Epoch 33/60
Model trained in 3.04s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.354
  Epoch 34/60
Model trained in 3.29s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.019
  Epoch 35/60
Model trained in 3.15s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.145
  Epoch 36/60
Model trained in 3.46s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.575
  Epoch 37/60
Model trained in 2.97s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.919
  Epoch 38/60
Model trained in 3.63s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.780
  Epoch 39/60
Model trained in 3.42s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.683
  Epoch 40/60
Model trained in 3.33s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.745
  Epoch 41/60
Model trained in 3.10s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.270
  Epoch 42/60
Model trained in 3.25s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.922
  Epoch 43/60
Model trained in 2.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.386
  Epoch 44/60
Model trained in 3.41s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.803
  Epoch 45/60
Model trained in 2.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.849
  Epoch 46/60
Model trained in 3.22s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.048
  Epoch 47/60
Model trained in 3.19s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.387
  Epoch 48/60
Model trained in 3.19s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.374
  Epoch 49/60
Model trained in 3.25s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.892
  Epoch 50/60
Model trained in 3.21s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.860
  Epoch 51/60
Model trained in 3.28s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.408
  Epoch 52/60
Model trained in 3.29s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.142
  Epoch 53/60
Model trained in 3.33s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.907
  Epoch 54/60
Model trained in 3.14s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.086
  Epoch 55/60
Model trained in 3.26s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.434
  Epoch 56/60
Model trained in 3.17s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.494
  Epoch 57/60
Model trained in 3.10s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.214
  Epoch 58/60
Model trained in 3.28s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.661
  Epoch 59/60
Model trained in 3.34s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.030
  Epoch 60/60
Model trained in 3.22s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.431

  best_val_SMAPE=78.374

Combination 766/1152: {'encoder_hidden_size': 33, 'encoder_layers': 2, 'encoder_dropout': 0.2, 'decoder_hidden_size': 48, 'decoder_layers': 2, 'decoder_dropout': 0.2, 'learning_rate': 0.0005, 'max_epochs': 60, 'patience': 20, 'batch_size': 32, 'sequence_length': 168}
Time: 41.25 minutes - estimated total time: 62.04 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 3.57s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 174.206
  Epoch 2/60
Model trained in 3.59s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 161.376
  Epoch 3/60
Model trained in 3.60s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 151.065
  Epoch 4/60
Model trained in 3.50s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 142.182
  Epoch 5/60
Model trained in 3.52s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 134.257
  Epoch 6/60
Model trained in 3.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 126.852
  Epoch 7/60
Model trained in 3.55s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 119.946
  Epoch 8/60
Model trained in 3.45s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 113.667
  Epoch 9/60
Model trained in 3.61s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 109.844
  Epoch 10/60
Model trained in 3.42s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 105.009
  Epoch 11/60
Model trained in 3.46s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 101.976
  Epoch 12/60
Model trained in 3.35s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 98.343
  Epoch 13/60
Model trained in 3.47s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 94.193
  Epoch 14/60
Model trained in 3.59s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.495
  Epoch 15/60
Model trained in 3.62s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.172
  Epoch 16/60
Model trained in 3.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.242
  Epoch 17/60
Model trained in 4.08s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.667
  Epoch 18/60
Model trained in 3.06s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.804
  Epoch 19/60
Model trained in 3.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.888
  Epoch 20/60
Model trained in 3.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.765
  Epoch 21/60
Model trained in 3.45s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.425
  Epoch 22/60
Model trained in 3.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.175
  Epoch 23/60
Model trained in 3.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.545
  Epoch 24/60
Model trained in 3.59s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 72.396
  Epoch 25/60
Model trained in 3.41s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.036
  Epoch 26/60
Model trained in 3.60s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.139
  Epoch 27/60
Model trained in 3.48s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.186
  Epoch 28/60
Model trained in 3.37s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.562
  Epoch 29/60
Model trained in 3.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.167
  Epoch 30/60
Model trained in 3.37s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.864
  Epoch 31/60
Model trained in 3.28s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.231
  Epoch 32/60
Model trained in 3.57s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 72.700
  Epoch 33/60
Model trained in 3.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.146
  Epoch 34/60
Model trained in 3.52s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.577
  Epoch 35/60
Model trained in 3.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.090
  Epoch 36/60
Model trained in 3.41s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.466
  Epoch 37/60
Model trained in 3.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.155
  Epoch 38/60
Model trained in 3.61s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.346
  Epoch 39/60
Model trained in 3.28s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.820
  Epoch 40/60
Model trained in 3.56s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.723
  Epoch 41/60
Model trained in 3.42s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.063
  Epoch 42/60
Model trained in 3.35s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.263
  Epoch 43/60
Model trained in 3.46s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.500
  Epoch 44/60
Model trained in 3.42s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.174
  Early stopping triggered.

  best_val_SMAPE=72.396

Combination 767/1152: {'encoder_hidden_size': 33, 'encoder_layers': 2, 'encoder_dropout': 0.2, 'decoder_hidden_size': 48, 'decoder_layers': 2, 'decoder_dropout': 0.2, 'learning_rate': 0.0005, 'max_epochs': 60, 'patience': 20, 'batch_size': 64, 'sequence_length': 24}
Time: 44.29 minutes - estimated total time: 66.52 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 2.15s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 182.065
  Epoch 2/60
Model trained in 2.02s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 173.790
  Epoch 3/60
Model trained in 2.07s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 167.034
  Epoch 4/60
Model trained in 1.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 161.019
  Epoch 5/60
Model trained in 2.03s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 155.625
  Epoch 6/60
Model trained in 2.25s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 150.670
  Epoch 7/60
Model trained in 2.34s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 146.068
  Epoch 8/60
Model trained in 2.40s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 141.735
  Epoch 9/60
Model trained in 2.15s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 137.652
  Epoch 10/60
Model trained in 2.29s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 133.753
  Epoch 11/60
Model trained in 2.16s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 129.959
  Epoch 12/60
Model trained in 2.49s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 126.293
  Epoch 13/60
Model trained in 2.32s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 122.747
  Epoch 14/60
Model trained in 2.44s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 119.348
  Epoch 15/60
Model trained in 2.22s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 116.130
  Epoch 16/60
Model trained in 2.38s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 112.334
  Epoch 17/60
Model trained in 2.26s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 113.781
  Epoch 18/60
Model trained in 2.31s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 112.261
  Epoch 19/60
Model trained in 2.08s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 110.584
  Epoch 20/60
Model trained in 2.22s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 108.396
  Epoch 21/60
Model trained in 2.30s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 106.021
  Epoch 22/60
Model trained in 2.20s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 103.700
  Epoch 23/60
Model trained in 2.39s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 100.990
  Epoch 24/60
Model trained in 2.15s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 99.373
  Epoch 25/60
Model trained in 2.47s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 97.729
  Epoch 26/60
Model trained in 2.14s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 96.216
  Epoch 27/60
Model trained in 2.47s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 94.826
  Epoch 28/60
Model trained in 2.31s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.106
  Epoch 29/60
Model trained in 2.33s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.487
  Epoch 30/60
Model trained in 2.21s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.877
  Epoch 31/60
Model trained in 2.16s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.436
  Epoch 32/60
Model trained in 2.25s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.308
  Epoch 33/60
Model trained in 2.08s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.684
  Epoch 34/60
Model trained in 2.26s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.370
  Epoch 35/60
Model trained in 2.24s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.700
  Epoch 36/60
Model trained in 2.59s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.389
  Epoch 37/60
Model trained in 2.42s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.835
  Epoch 38/60
Model trained in 2.27s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.239
  Epoch 39/60
Model trained in 2.16s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.345
  Epoch 40/60
Model trained in 2.21s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.846
  Epoch 41/60
Model trained in 2.20s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.497
  Epoch 42/60
Model trained in 2.10s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.229
  Epoch 43/60
Model trained in 2.40s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.379
  Epoch 44/60
Model trained in 2.09s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.693
  Epoch 45/60
Model trained in 2.44s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.702
  Epoch 46/60
Model trained in 2.11s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.883
  Epoch 47/60
Model trained in 2.24s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.438
  Epoch 48/60
Model trained in 2.09s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.716
  Epoch 49/60
Model trained in 2.36s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.386
  Epoch 50/60
Model trained in 2.42s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.948
  Epoch 51/60
Model trained in 2.23s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.989
  Epoch 52/60
Model trained in 2.24s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.236
  Epoch 53/60
Model trained in 2.02s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.108
  Epoch 54/60
Model trained in 2.41s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.417
  Epoch 55/60
Model trained in 2.14s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.760
  Epoch 56/60
Model trained in 2.35s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.322
  Epoch 57/60
Model trained in 2.02s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.394
  Epoch 58/60
Model trained in 2.12s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.252
  Epoch 59/60
Model trained in 2.05s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.686
  Epoch 60/60
Model trained in 2.09s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.108

  best_val_SMAPE=80.229

Combination 768/1152: {'encoder_hidden_size': 33, 'encoder_layers': 2, 'encoder_dropout': 0.2, 'decoder_hidden_size': 48, 'decoder_layers': 2, 'decoder_dropout': 0.2, 'learning_rate': 0.0005, 'max_epochs': 60, 'patience': 20, 'batch_size': 64, 'sequence_length': 168}
Time: 47.12 minutes - estimated total time: 70.68 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 2.28s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 182.168
  Epoch 2/60
Model trained in 2.56s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 173.898
  Epoch 3/60
Model trained in 2.32s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 167.177
  Epoch 4/60
Model trained in 2.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 161.190
  Epoch 5/60
Model trained in 2.26s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 155.815
  Epoch 6/60
Model trained in 2.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 150.873
  Epoch 7/60
Model trained in 2.35s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 146.291
  Epoch 8/60
Model trained in 2.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 141.971
  Epoch 9/60
Model trained in 2.38s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 137.902
  Epoch 10/60
Model trained in 2.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 134.036
  Epoch 11/60
Model trained in 2.38s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 131.261
  Epoch 12/60
Model trained in 2.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 128.497
  Epoch 13/60
Model trained in 2.28s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 125.552
  Epoch 14/60
Model trained in 2.23s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 122.273
  Epoch 15/60
Model trained in 2.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 118.979
  Epoch 16/60
Model trained in 2.30s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 115.862
  Epoch 17/60
Model trained in 2.62s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 113.507
  Epoch 18/60
Model trained in 2.30s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 110.899
  Epoch 19/60
Model trained in 2.42s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 108.307
  Epoch 20/60
Model trained in 2.40s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 106.165
  Epoch 21/60
Model trained in 2.37s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 103.699
  Epoch 22/60
Model trained in 2.49s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 101.736
  Epoch 23/60
Model trained in 2.38s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 99.990
  Epoch 24/60
Model trained in 2.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 98.760
  Epoch 25/60
Model trained in 2.38s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 96.382
  Epoch 26/60
Model trained in 2.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 95.331
  Epoch 27/60
Model trained in 2.24s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.523
  Epoch 28/60
Model trained in 2.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.413
  Epoch 29/60
Model trained in 2.29s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.693
  Epoch 30/60
Model trained in 2.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.039
  Epoch 31/60
Model trained in 2.31s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.745
  Epoch 32/60
Model trained in 2.95s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.602
  Epoch 33/60
Model trained in 2.34s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.614
  Epoch 34/60
Model trained in 2.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.400
  Epoch 35/60
Model trained in 2.30s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.668
  Epoch 36/60
Model trained in 2.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.903
  Epoch 37/60
Model trained in 2.39s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.532
  Epoch 38/60
Model trained in 2.65s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.084
  Epoch 39/60
Model trained in 2.39s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.376
  Epoch 40/60
Model trained in 2.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.438
  Epoch 41/60
Model trained in 2.51s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.310
  Epoch 42/60
Model trained in 2.51s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.503
  Epoch 43/60
Model trained in 2.56s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.853
  Epoch 44/60
Model trained in 2.30s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.517
  Epoch 45/60
Model trained in 2.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.337
  Epoch 46/60
Model trained in 2.30s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.774
  Epoch 47/60
Model trained in 2.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.612
  Epoch 48/60
Model trained in 2.35s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.715
  Epoch 49/60
Model trained in 2.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.168
  Epoch 50/60
Model trained in 2.34s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.193
  Epoch 51/60
Model trained in 2.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.165
  Epoch 52/60
Model trained in 2.35s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.153
  Epoch 53/60
Model trained in 2.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.707
  Epoch 54/60
Model trained in 2.23s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.870
  Epoch 55/60
Model trained in 2.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.964
  Epoch 56/60
Model trained in 2.31s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.505
  Epoch 57/60
Model trained in 2.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.433
  Epoch 58/60
Model trained in 2.37s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.789
  Epoch 59/60
Model trained in 2.67s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.686
  Epoch 60/60
Model trained in 2.38s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.081

  best_val_SMAPE=73.153

Combination 769/1152: {'encoder_hidden_size': 48, 'encoder_layers': 1, 'encoder_dropout': 0.0, 'decoder_hidden_size': 28, 'decoder_layers': 1, 'decoder_dropout': 0.0, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 20, 'batch_size': 32, 'sequence_length': 24}
Time: 50.22 minutes - estimated total time: 75.23 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 3.01s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 171.231
  Epoch 2/60
Model trained in 3.15s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 157.087
  Epoch 3/60
Model trained in 2.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 145.874
  Epoch 4/60
Model trained in 3.15s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 136.397
  Epoch 5/60
Model trained in 2.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 127.748
  Epoch 6/60
Model trained in 3.18s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 120.138
  Epoch 7/60
Model trained in 2.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 113.226
  Epoch 8/60
Model trained in 2.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 107.008
  Epoch 9/60
Model trained in 3.16s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 101.448
  Epoch 10/60
Model trained in 2.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 96.606
  Epoch 11/60
Model trained in 3.08s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.119
  Epoch 12/60
Model trained in 2.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.215
  Epoch 13/60
Model trained in 3.01s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.324
  Epoch 14/60
Model trained in 2.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.698
  Epoch 15/60
Model trained in 2.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.591
  Epoch 16/60
Model trained in 2.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.148
  Epoch 17/60
Model trained in 2.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.091
  Epoch 18/60
Model trained in 3.03s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.826
  Epoch 19/60
Model trained in 2.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.163
  Epoch 20/60
Model trained in 2.99s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.837
  Epoch 21/60
Model trained in 2.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.920
  Epoch 22/60
Model trained in 2.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.776
  Epoch 23/60
Model trained in 2.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.318
  Epoch 24/60
Model trained in 2.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.684
  Epoch 25/60
Model trained in 3.04s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 94.250
  Epoch 26/60
Model trained in 2.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 96.517
  Epoch 27/60
Model trained in 3.08s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 99.499
  Epoch 28/60
Model trained in 2.61s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 100.648
  Epoch 29/60
Model trained in 2.95s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 100.705
  Epoch 30/60
Model trained in 2.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 100.844
  Epoch 31/60
Model trained in 2.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 102.245
  Epoch 32/60
Model trained in 3.03s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 100.699
  Epoch 33/60
Model trained in 2.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 100.690
  Epoch 34/60
Model trained in 2.67s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 98.029
  Epoch 35/60
Model trained in 3.02s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 94.987
  Epoch 36/60
Model trained in 2.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 95.710
  Epoch 37/60
Model trained in 2.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.939
  Early stopping triggered.

  best_val_SMAPE=80.091

Combination 770/1152: {'encoder_hidden_size': 48, 'encoder_layers': 1, 'encoder_dropout': 0.0, 'decoder_hidden_size': 28, 'decoder_layers': 1, 'decoder_dropout': 0.0, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 20, 'batch_size': 32, 'sequence_length': 168}
Time: 52.38 minutes - estimated total time: 78.36 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 3.00s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 171.280
  Epoch 2/60
Model trained in 3.31s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 157.198
  Epoch 3/60
Model trained in 2.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 145.969
  Epoch 4/60
Model trained in 3.39s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 136.695
  Epoch 5/60
Model trained in 2.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 128.013
  Epoch 6/60
Model trained in 3.12s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 120.208
  Epoch 7/60
Model trained in 3.24s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 113.400
  Epoch 8/60
Model trained in 2.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 107.275
  Epoch 9/60
Model trained in 3.35s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 101.964
  Epoch 10/60
Model trained in 3.01s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 97.467
  Epoch 11/60
Model trained in 3.24s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.403
  Epoch 12/60
Model trained in 3.02s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.686
  Epoch 13/60
Model trained in 2.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.075
  Epoch 14/60
Model trained in 3.31s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.212
  Epoch 15/60
Model trained in 2.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.168
  Epoch 16/60
Model trained in 3.33s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.100
  Epoch 17/60
Model trained in 2.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.945
  Epoch 18/60
Model trained in 3.14s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.955
  Epoch 19/60
Model trained in 3.20s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.532
  Epoch 20/60
Model trained in 2.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.894
  Epoch 21/60
Model trained in 3.27s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.377
  Epoch 22/60
Model trained in 2.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.571
  Epoch 23/60
Model trained in 3.23s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.803
  Epoch 24/60
Model trained in 2.97s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.786
  Epoch 25/60
Model trained in 3.03s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.372
  Epoch 26/60
Model trained in 3.28s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.282
  Epoch 27/60
Model trained in 2.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.877
  Epoch 28/60
Model trained in 3.35s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.347
  Epoch 29/60
Model trained in 2.98s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.970
  Epoch 30/60
Model trained in 3.14s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.861
  Epoch 31/60
Model trained in 3.07s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.560
  Epoch 32/60
Model trained in 2.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.981
  Epoch 33/60
Model trained in 3.34s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 72.238
  Epoch 34/60
Model trained in 2.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.505
  Epoch 35/60
Model trained in 3.34s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.329
  Epoch 36/60
Model trained in 2.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.438
  Epoch 37/60
Model trained in 2.97s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.175
  Epoch 38/60
Model trained in 3.28s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.724
  Epoch 39/60
Model trained in 2.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 71.694
  Epoch 40/60
Model trained in 3.29s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.162
  Epoch 41/60
Model trained in 2.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.891
  Epoch 42/60
Model trained in 3.13s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.929
  Epoch 43/60
Model trained in 2.99s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.215
  Epoch 44/60
Model trained in 2.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.238
  Epoch 45/60
Model trained in 3.32s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.223
  Epoch 46/60
Model trained in 2.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.129
  Epoch 47/60
Model trained in 3.32s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.186
  Epoch 48/60
Model trained in 2.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.416
  Epoch 49/60
Model trained in 3.06s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.423
  Epoch 50/60
Model trained in 3.09s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.500
  Epoch 51/60
Model trained in 2.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.606
  Epoch 52/60
Model trained in 3.27s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.507
  Epoch 53/60
Model trained in 2.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.715
  Epoch 54/60
Model trained in 3.18s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.266
  Epoch 55/60
Model trained in 2.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.746
  Epoch 56/60
Model trained in 2.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.587
  Epoch 57/60
Model trained in 3.18s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.291
  Epoch 58/60
Model trained in 2.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.247
  Epoch 59/60
Model trained in 3.25s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.429
  Early stopping triggered.

  best_val_SMAPE=71.694

Combination 771/1152: {'encoder_hidden_size': 48, 'encoder_layers': 1, 'encoder_dropout': 0.0, 'decoder_hidden_size': 28, 'decoder_layers': 1, 'decoder_dropout': 0.0, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 20, 'batch_size': 64, 'sequence_length': 24}
Time: 55.95 minutes - estimated total time: 83.60 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 2.09s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 180.083
  Epoch 2/60
Model trained in 1.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 171.044
  Epoch 3/60
Model trained in 1.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 163.488
  Epoch 4/60
Model trained in 1.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 156.874
  Epoch 5/60
Model trained in 1.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 150.978
  Epoch 6/60
Model trained in 2.12s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 145.668
  Epoch 7/60
Model trained in 1.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 140.738
  Epoch 8/60
Model trained in 1.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 136.055
  Epoch 9/60
Model trained in 1.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 131.603
  Epoch 10/60
Model trained in 1.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 127.398
  Epoch 11/60
Model trained in 1.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 123.541
  Epoch 12/60
Model trained in 1.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 119.754
  Epoch 13/60
Model trained in 1.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 116.311
  Epoch 14/60
Model trained in 1.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 113.105
  Epoch 15/60
Model trained in 1.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 110.077
  Epoch 16/60
Model trained in 1.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 107.458
  Epoch 17/60
Model trained in 1.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 104.770
  Epoch 18/60
Model trained in 1.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 103.910
  Epoch 19/60
Model trained in 1.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 99.883
  Epoch 20/60
Model trained in 1.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 97.800
  Epoch 21/60
Model trained in 1.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 95.100
  Epoch 22/60
Model trained in 1.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 101.616
  Epoch 23/60
Model trained in 1.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 99.201
  Epoch 24/60
Model trained in 1.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 99.907
  Epoch 25/60
Model trained in 1.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 95.187
  Epoch 26/60
Model trained in 1.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.829
  Epoch 27/60
Model trained in 1.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.076
  Epoch 28/60
Model trained in 1.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.576
  Epoch 29/60
Model trained in 1.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.057
  Epoch 30/60
Model trained in 1.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.067
  Epoch 31/60
Model trained in 1.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.375
  Epoch 32/60
Model trained in 1.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.732
  Epoch 33/60
Model trained in 1.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.084
  Epoch 34/60
Model trained in 1.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.210
  Epoch 35/60
Model trained in 1.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.295
  Epoch 36/60
Model trained in 1.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.527
  Epoch 37/60
Model trained in 1.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.639
  Epoch 38/60
Model trained in 1.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.409
  Epoch 39/60
Model trained in 1.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.379
  Epoch 40/60
Model trained in 1.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.440
  Epoch 41/60
Model trained in 1.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.788
  Epoch 42/60
Model trained in 1.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.727
  Epoch 43/60
Model trained in 1.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.747
  Epoch 44/60
Model trained in 1.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.477
  Epoch 45/60
Model trained in 1.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.102
  Epoch 46/60
Model trained in 1.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.726
  Epoch 47/60
Model trained in 1.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.505
  Epoch 48/60
Model trained in 1.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.645
  Epoch 49/60
Model trained in 1.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.209
  Epoch 50/60
Model trained in 1.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.398
  Epoch 51/60
Model trained in 1.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.010
  Epoch 52/60
Model trained in 1.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.497
  Epoch 53/60
Model trained in 1.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.603
  Epoch 54/60
Model trained in 1.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.370
  Epoch 55/60
Model trained in 1.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.856
  Epoch 56/60
Model trained in 1.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 94.916
  Epoch 57/60
Model trained in 1.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 94.864
  Epoch 58/60
Model trained in 1.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.778
  Epoch 59/60
Model trained in 1.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.011
  Epoch 60/60
Model trained in 1.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.827
  Early stopping triggered.

  best_val_SMAPE=79.440

Combination 772/1152: {'encoder_hidden_size': 48, 'encoder_layers': 1, 'encoder_dropout': 0.0, 'decoder_hidden_size': 28, 'decoder_layers': 1, 'decoder_dropout': 0.0, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 20, 'batch_size': 64, 'sequence_length': 168}
Time: 58.33 minutes - estimated total time: 87.04 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 2.15s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 180.142
  Epoch 2/60
Model trained in 1.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 171.166
  Epoch 3/60
Model trained in 2.08s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 163.645
  Epoch 4/60
Model trained in 1.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 157.066
  Epoch 5/60
Model trained in 2.09s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 151.177
  Epoch 6/60
Model trained in 1.95s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 145.834
  Epoch 7/60
Model trained in 2.01s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 140.924
  Epoch 8/60
Model trained in 1.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 136.299
  Epoch 9/60
Model trained in 1.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 131.917
  Epoch 10/60
Model trained in 2.13s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 127.556
  Epoch 11/60
Model trained in 1.97s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 123.830
  Epoch 12/60
Model trained in 2.00s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 120.163
  Epoch 13/60
Model trained in 1.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 116.587
  Epoch 14/60
Model trained in 1.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 113.346
  Epoch 15/60
Model trained in 1.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 110.325
  Epoch 16/60
Model trained in 2.08s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 107.487
  Epoch 17/60
Model trained in 1.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 105.009
  Epoch 18/60
Model trained in 2.01s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 102.216
  Epoch 19/60
Model trained in 1.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 99.608
  Epoch 20/60
Model trained in 2.01s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 97.266
  Epoch 21/60
Model trained in 1.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 95.298
  Epoch 22/60
Model trained in 2.06s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.615
  Epoch 23/60
Model trained in 1.95s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.742
  Epoch 24/60
Model trained in 2.07s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.990
  Epoch 25/60
Model trained in 1.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.906
  Epoch 26/60
Model trained in 2.01s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.275
  Epoch 27/60
Model trained in 1.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.110
  Epoch 28/60
Model trained in 2.06s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.059
  Epoch 29/60
Model trained in 1.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.911
  Epoch 30/60
Model trained in 2.04s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.044
  Epoch 31/60
Model trained in 1.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.080
  Epoch 32/60
Model trained in 2.07s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.855
  Epoch 33/60
Model trained in 1.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.314
  Epoch 34/60
Model trained in 2.04s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.708
  Epoch 35/60
Model trained in 1.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.374
  Epoch 36/60
Model trained in 2.11s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.477
  Epoch 37/60
Model trained in 1.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.372
  Epoch 38/60
Model trained in 2.01s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.179
  Epoch 39/60
Model trained in 1.95s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.260
  Epoch 40/60
Model trained in 2.02s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.821
  Epoch 41/60
Model trained in 1.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.186
  Epoch 42/60
Model trained in 1.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.376
  Epoch 43/60
Model trained in 1.98s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.641
  Epoch 44/60
Model trained in 1.95s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.049
  Epoch 45/60
Model trained in 2.06s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.145
  Epoch 46/60
Model trained in 2.01s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.904
  Epoch 47/60
Model trained in 1.98s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.820
  Epoch 48/60
Model trained in 1.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.442
  Epoch 49/60
Model trained in 1.97s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.562
  Epoch 50/60
Model trained in 1.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.411
  Epoch 51/60
Model trained in 1.98s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.801
  Epoch 52/60
Model trained in 1.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.034
  Epoch 53/60
Model trained in 2.10s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.726
  Epoch 54/60
Model trained in 1.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.165
  Epoch 55/60
Model trained in 2.00s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.124
  Epoch 56/60
Model trained in 1.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.279
  Epoch 57/60
Model trained in 2.06s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.868
  Epoch 58/60
Model trained in 1.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.182
  Epoch 59/60
Model trained in 2.06s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.943
  Epoch 60/60
Model trained in 1.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.743
  Early stopping triggered.

  best_val_SMAPE=76.821

Combination 773/1152: {'encoder_hidden_size': 48, 'encoder_layers': 1, 'encoder_dropout': 0.0, 'decoder_hidden_size': 28, 'decoder_layers': 1, 'decoder_dropout': 0.0, 'learning_rate': 0.0005, 'max_epochs': 60, 'patience': 20, 'batch_size': 32, 'sequence_length': 24}
Time: 60.87 minutes - estimated total time: 90.72 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 2.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 180.145
  Epoch 2/60
Model trained in 2.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 171.274
  Epoch 3/60
Model trained in 2.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 163.828
  Epoch 4/60
Model trained in 2.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 157.233
  Epoch 5/60
Model trained in 2.98s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 151.352
  Epoch 6/60
Model trained in 2.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 146.012
  Epoch 7/60
Model trained in 2.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 141.036
  Epoch 8/60
Model trained in 2.65s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 136.830
  Epoch 9/60
Model trained in 2.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 133.573
  Epoch 10/60
Model trained in 2.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 127.805
  Epoch 11/60
Model trained in 2.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 123.945
  Epoch 12/60
Model trained in 2.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 120.255
  Epoch 13/60
Model trained in 2.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 116.705
  Epoch 14/60
Model trained in 2.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 113.406
  Epoch 15/60
Model trained in 2.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 110.299
  Epoch 16/60
Model trained in 2.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 107.350
  Epoch 17/60
Model trained in 2.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 104.580
  Epoch 18/60
Model trained in 2.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 101.863
  Epoch 19/60
Model trained in 2.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 100.151
  Epoch 20/60
Model trained in 2.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 97.018
  Epoch 21/60
Model trained in 2.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 96.275
  Epoch 22/60
Model trained in 2.65s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.403
  Epoch 23/60
Model trained in 2.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.884
  Epoch 24/60
Model trained in 2.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.940
  Epoch 25/60
Model trained in 2.62s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.424
  Epoch 26/60
Model trained in 2.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.680
  Epoch 27/60
Model trained in 2.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.063
  Epoch 28/60
Model trained in 2.63s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.016
  Epoch 29/60
Model trained in 2.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.457
  Epoch 30/60
Model trained in 2.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.465
  Epoch 31/60
Model trained in 2.60s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.948
  Epoch 32/60
Model trained in 2.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.168
  Epoch 33/60
Model trained in 2.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.282
  Epoch 34/60
Model trained in 2.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.474
  Epoch 35/60
Model trained in 2.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.454
  Epoch 36/60
Model trained in 2.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.911
  Epoch 37/60
Model trained in 2.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.056
  Epoch 38/60
Model trained in 2.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.744
  Epoch 39/60
Model trained in 2.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.181
  Epoch 40/60
Model trained in 2.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.858
  Epoch 41/60
Model trained in 2.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.902
  Epoch 42/60
Model trained in 2.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.192
  Epoch 43/60
Model trained in 2.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.594
  Epoch 44/60
Model trained in 2.68s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.356
  Epoch 45/60
Model trained in 2.65s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.936
  Epoch 46/60
Model trained in 2.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.060
  Epoch 47/60
Model trained in 2.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.732
  Epoch 48/60
Model trained in 2.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.536
  Epoch 49/60
Model trained in 2.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.188
  Epoch 50/60
Model trained in 2.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.829
  Epoch 51/60
Model trained in 2.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.678
  Epoch 52/60
Model trained in 2.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.858
  Epoch 53/60
Model trained in 2.60s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.540
  Epoch 54/60
Model trained in 2.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.301
  Early stopping triggered.

  best_val_SMAPE=79.474

Combination 774/1152: {'encoder_hidden_size': 48, 'encoder_layers': 1, 'encoder_dropout': 0.0, 'decoder_hidden_size': 28, 'decoder_layers': 1, 'decoder_dropout': 0.0, 'learning_rate': 0.0005, 'max_epochs': 60, 'patience': 20, 'batch_size': 32, 'sequence_length': 168}
Time: 63.87 minutes - estimated total time: 95.06 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 2.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 180.195
  Epoch 2/60
Model trained in 3.20s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 171.378
  Epoch 3/60
Model trained in 2.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 163.945
  Epoch 4/60
Model trained in 2.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 157.382
  Epoch 5/60
Model trained in 2.95s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 151.502
  Epoch 6/60
Model trained in 2.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 146.174
  Epoch 7/60
Model trained in 2.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 141.257
  Epoch 8/60
Model trained in 2.98s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 136.610
  Epoch 9/60
Model trained in 2.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 132.345
  Epoch 10/60
Model trained in 2.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 128.083
  Epoch 11/60
Model trained in 2.98s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 124.090
  Epoch 12/60
Model trained in 2.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 120.519
  Epoch 13/60
Model trained in 2.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 116.883
  Epoch 14/60
Model trained in 3.00s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 113.663
  Epoch 15/60
Model trained in 2.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 110.528
  Epoch 16/60
Model trained in 2.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 107.633
  Epoch 17/60
Model trained in 3.00s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 105.123
  Epoch 18/60
Model trained in 2.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 102.883
  Epoch 19/60
Model trained in 2.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 100.649
  Epoch 20/60
Model trained in 2.97s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 98.402
  Epoch 21/60
Model trained in 2.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 96.513
  Epoch 22/60
Model trained in 2.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.955
  Epoch 23/60
Model trained in 2.95s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.922
  Epoch 24/60
Model trained in 2.95s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.105
  Epoch 25/60
Model trained in 2.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.201
  Epoch 26/60
Model trained in 2.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.881
  Epoch 27/60
Model trained in 3.08s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.866
  Epoch 28/60
Model trained in 3.04s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.923
  Epoch 29/60
Model trained in 2.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.971
  Epoch 30/60
Model trained in 3.08s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.245
  Epoch 31/60
Model trained in 3.09s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.102
  Epoch 32/60
Model trained in 2.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.673
  Epoch 33/60
Model trained in 3.05s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.672
  Epoch 34/60
Model trained in 3.09s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.501
  Epoch 35/60
Model trained in 2.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.521
  Epoch 36/60
Model trained in 3.13s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.971
  Epoch 37/60
Model trained in 3.25s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.994
  Epoch 38/60
Model trained in 2.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.384
  Epoch 39/60
Model trained in 3.05s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.532
  Epoch 40/60
Model trained in 3.03s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.101
  Epoch 41/60
Model trained in 2.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.094
  Epoch 42/60
Model trained in 3.14s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.150
  Epoch 43/60
Model trained in 2.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.296
  Epoch 44/60
Model trained in 2.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.994
  Epoch 45/60
Model trained in 3.17s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.519
  Epoch 46/60
Model trained in 3.04s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.841
  Epoch 47/60
Model trained in 2.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.491
  Epoch 48/60
Model trained in 3.18s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.143
  Epoch 49/60
Model trained in 3.04s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.749
  Epoch 50/60
Model trained in 2.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.273
  Epoch 51/60
Model trained in 3.09s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.139
  Epoch 52/60
Model trained in 2.98s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.745
  Epoch 53/60
Model trained in 2.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.452
  Epoch 54/60
Model trained in 3.21s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.351
  Epoch 55/60
Model trained in 3.02s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.685
  Epoch 56/60
Model trained in 2.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.757
  Epoch 57/60
Model trained in 3.08s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.502
  Epoch 58/60
Model trained in 3.02s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.456
  Epoch 59/60
Model trained in 2.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.589
  Epoch 60/60
Model trained in 3.11s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.101

  best_val_SMAPE=75.994

Combination 775/1152: {'encoder_hidden_size': 48, 'encoder_layers': 1, 'encoder_dropout': 0.0, 'decoder_hidden_size': 28, 'decoder_layers': 1, 'decoder_dropout': 0.0, 'learning_rate': 0.0005, 'max_epochs': 60, 'patience': 20, 'batch_size': 64, 'sequence_length': 24}
Time: 67.40 minutes - estimated total time: 100.19 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 1.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 186.256
  Epoch 2/60
Model trained in 1.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 180.026
  Epoch 3/60
Model trained in 1.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 175.345
  Epoch 4/60
Model trained in 1.67s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 171.157
  Epoch 5/60
Model trained in 1.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 167.297
  Epoch 6/60
Model trained in 1.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 163.665
  Epoch 7/60
Model trained in 2.00s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 160.235
  Epoch 8/60
Model trained in 1.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 157.059
  Epoch 9/60
Model trained in 1.97s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 154.011
  Epoch 10/60
Model trained in 1.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 151.342
  Epoch 11/60
Model trained in 1.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 148.783
  Epoch 12/60
Model trained in 1.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 145.832
  Epoch 13/60
Model trained in 1.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 143.274
  Epoch 14/60
Model trained in 1.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 141.872
  Epoch 15/60
Model trained in 1.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 139.978
  Epoch 16/60
Model trained in 1.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 136.100
  Epoch 17/60
Model trained in 1.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 133.825
  Epoch 18/60
Model trained in 1.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 131.615
  Epoch 19/60
Model trained in 1.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 134.638
  Epoch 20/60
Model trained in 1.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 132.402
  Epoch 21/60
Model trained in 1.68s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 131.886
  Epoch 22/60
Model trained in 1.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 123.381
  Epoch 23/60
Model trained in 1.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 121.472
  Epoch 24/60
Model trained in 1.68s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 119.622
  Epoch 25/60
Model trained in 1.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 117.857
  Epoch 26/60
Model trained in 1.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 116.120
  Epoch 27/60
Model trained in 1.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 114.430
  Epoch 28/60
Model trained in 1.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 112.821
  Epoch 29/60
Model trained in 1.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 111.409
  Epoch 30/60
Model trained in 1.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 114.408
  Epoch 31/60
Model trained in 1.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 115.270
  Epoch 32/60
Model trained in 1.67s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 115.113
  Epoch 33/60
Model trained in 1.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 114.138
  Epoch 34/60
Model trained in 1.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 113.373
  Epoch 35/60
Model trained in 1.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 113.050
  Epoch 36/60
Model trained in 1.98s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 112.459
  Epoch 37/60
Model trained in 1.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 111.781
  Epoch 38/60
Model trained in 1.97s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 113.444
  Epoch 39/60
Model trained in 1.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 116.539
  Epoch 40/60
Model trained in 1.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 112.214
  Epoch 41/60
Model trained in 1.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 108.957
  Epoch 42/60
Model trained in 1.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 108.403
  Epoch 43/60
Model trained in 1.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 106.495
  Epoch 44/60
Model trained in 1.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 105.384
  Epoch 45/60
Model trained in 1.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 104.289
  Epoch 46/60
Model trained in 1.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.687
  Epoch 47/60
Model trained in 1.99s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 98.904
  Epoch 48/60
Model trained in 1.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 100.833
  Epoch 49/60
Model trained in 1.98s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 100.844
  Epoch 50/60
Model trained in 1.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 99.441
  Epoch 51/60
Model trained in 1.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 99.340
  Epoch 52/60
Model trained in 1.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 99.337
  Epoch 53/60
Model trained in 1.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 99.212
  Epoch 54/60
Model trained in 1.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 98.852
  Epoch 55/60
Model trained in 1.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 99.884
  Epoch 56/60
Model trained in 1.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 97.324
  Epoch 57/60
Model trained in 1.67s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 96.614
  Epoch 58/60
Model trained in 1.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 96.270
  Epoch 59/60
Model trained in 1.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.920
  Epoch 60/60
Model trained in 1.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.807

  best_val_SMAPE=81.807

Combination 776/1152: {'encoder_hidden_size': 48, 'encoder_layers': 1, 'encoder_dropout': 0.0, 'decoder_hidden_size': 28, 'decoder_layers': 1, 'decoder_dropout': 0.0, 'learning_rate': 0.0005, 'max_epochs': 60, 'patience': 20, 'batch_size': 64, 'sequence_length': 168}
Time: 69.80 minutes - estimated total time: 103.62 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 2.24s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 186.310
  Epoch 2/60
Model trained in 1.98s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 180.119
  Epoch 3/60
Model trained in 1.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 175.461
  Epoch 4/60
Model trained in 2.23s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 171.290
  Epoch 5/60
Model trained in 1.97s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 167.448
  Epoch 6/60
Model trained in 2.22s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 163.835
  Epoch 7/60
Model trained in 1.98s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 160.420
  Epoch 8/60
Model trained in 2.04s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 157.251
  Epoch 9/60
Model trained in 1.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 154.232
  Epoch 10/60
Model trained in 2.17s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 151.366
  Epoch 11/60
Model trained in 1.97s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 148.652
  Epoch 12/60
Model trained in 2.05s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 146.023
  Epoch 13/60
Model trained in 2.05s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 143.474
  Epoch 14/60
Model trained in 1.98s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 141.042
  Epoch 15/60
Model trained in 2.03s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 138.662
  Epoch 16/60
Model trained in 1.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 136.365
  Epoch 17/60
Model trained in 2.11s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 134.104
  Epoch 18/60
Model trained in 1.95s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 131.955
  Epoch 19/60
Model trained in 2.27s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 130.950
  Epoch 20/60
Model trained in 1.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 127.784
  Epoch 21/60
Model trained in 2.29s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 125.760
  Epoch 22/60
Model trained in 1.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 123.828
  Epoch 23/60
Model trained in 2.35s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 121.895
  Epoch 24/60
Model trained in 2.05s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 120.209
  Epoch 25/60
Model trained in 2.26s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 118.240
  Epoch 26/60
Model trained in 1.97s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 116.562
  Epoch 27/60
Model trained in 2.28s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 114.914
  Epoch 28/60
Model trained in 1.98s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 113.227
  Epoch 29/60
Model trained in 2.29s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 111.738
  Epoch 30/60
Model trained in 1.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 110.185
  Epoch 31/60
Model trained in 2.25s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 108.750
  Epoch 32/60
Model trained in 1.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 107.341
  Epoch 33/60
Model trained in 2.26s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 106.035
  Epoch 34/60
Model trained in 1.99s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 104.933
  Epoch 35/60
Model trained in 2.36s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 103.729
  Epoch 36/60
Model trained in 1.97s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 102.479
  Epoch 37/60
Model trained in 2.18s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 101.470
  Epoch 38/60
Model trained in 1.95s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 100.394
  Epoch 39/60
Model trained in 2.06s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 99.458
  Epoch 40/60
Model trained in 1.95s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 98.490
  Epoch 41/60
Model trained in 2.09s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 97.940
  Epoch 42/60
Model trained in 1.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 97.062
  Epoch 43/60
Model trained in 1.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 96.221
  Epoch 44/60
Model trained in 2.04s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 95.749
  Epoch 45/60
Model trained in 1.99s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 95.792
  Epoch 46/60
Model trained in 2.02s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 95.323
  Epoch 47/60
Model trained in 1.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 95.825
  Epoch 48/60
Model trained in 2.09s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 94.522
  Epoch 49/60
Model trained in 1.95s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 94.229
  Epoch 50/60
Model trained in 2.32s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.191
  Epoch 51/60
Model trained in 2.02s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.723
  Epoch 52/60
Model trained in 2.22s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.603
  Epoch 53/60
Model trained in 1.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.854
  Epoch 54/60
Model trained in 2.27s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.633
  Epoch 55/60
Model trained in 1.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.095
  Epoch 56/60
Model trained in 2.22s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.525
  Epoch 57/60
Model trained in 1.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.031
  Epoch 58/60
Model trained in 2.23s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.426
  Epoch 59/60
Model trained in 1.97s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.219
  Epoch 60/60
Model trained in 2.25s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.841

  best_val_SMAPE=87.841

Combination 785/1152: {'encoder_hidden_size': 48, 'encoder_layers': 1, 'encoder_dropout': 0.0, 'decoder_hidden_size': 28, 'decoder_layers': 2, 'decoder_dropout': 0.0, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 20, 'batch_size': 32, 'sequence_length': 24}
Time: 72.45 minutes - estimated total time: 106.32 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 3.39s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 172.167
  Epoch 2/60
Model trained in 3.30s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 157.895
  Epoch 3/60
Model trained in 3.12s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 146.443
  Epoch 4/60
Model trained in 3.43s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 136.610
  Epoch 5/60
Model trained in 3.35s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 129.130
  Epoch 6/60
Model trained in 3.13s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 120.372
  Epoch 7/60
Model trained in 3.15s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 112.638
  Epoch 8/60
Model trained in 3.44s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 106.596
  Epoch 9/60
Model trained in 3.29s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 101.521
  Epoch 10/60
Model trained in 3.16s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 95.891
  Epoch 11/60
Model trained in 3.40s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.061
  Epoch 12/60
Model trained in 3.30s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.694
  Epoch 13/60
Model trained in 3.05s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.790
  Epoch 14/60
Model trained in 3.15s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.404
  Epoch 15/60
Model trained in 3.28s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.513
  Epoch 16/60
Model trained in 3.22s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.164
  Epoch 17/60
Model trained in 3.32s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.161
  Epoch 18/60
Model trained in 3.28s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 72.423
  Epoch 19/60
Model trained in 3.39s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 71.830
  Epoch 20/60
Model trained in 3.08s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 72.858
  Epoch 21/60
Model trained in 3.21s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 72.465
  Epoch 22/60
Model trained in 3.42s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.711
  Epoch 23/60
Model trained in 3.25s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.599
  Epoch 24/60
Model trained in 3.14s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.791
  Epoch 25/60
Model trained in 3.48s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.077
  Epoch 26/60
Model trained in 3.35s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.959
  Epoch 27/60
Model trained in 3.12s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.792
  Epoch 28/60
Model trained in 3.26s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.130
  Epoch 29/60
Model trained in 3.46s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 72.471
  Epoch 30/60
Model trained in 3.29s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 70.720
  Epoch 31/60
Model trained in 3.12s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 70.549
  Epoch 32/60
Model trained in 3.42s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 71.081
  Epoch 33/60
Model trained in 3.40s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 70.598
  Epoch 34/60
Model trained in 3.14s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 70.163
  Epoch 35/60
Model trained in 3.17s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 70.038
  Epoch 36/60
Model trained in 3.31s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 70.589
  Epoch 37/60
Model trained in 3.35s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 69.911
  Epoch 38/60
Model trained in 3.18s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 69.602
  Epoch 39/60
Model trained in 3.30s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 70.207
  Epoch 40/60
Model trained in 3.33s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 69.991
  Epoch 41/60
Model trained in 3.16s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 70.679
  Epoch 42/60
Model trained in 3.26s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 70.600
  Epoch 43/60
Model trained in 3.23s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 72.122
  Epoch 44/60
Model trained in 3.36s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 72.421
  Epoch 45/60
Model trained in 3.38s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 72.795
  Epoch 46/60
Model trained in 3.24s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.725
  Epoch 47/60
Model trained in 3.15s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.036
  Epoch 48/60
Model trained in 3.30s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.747
  Epoch 49/60
Model trained in 3.17s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.182
  Epoch 50/60
Model trained in 3.21s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.309
  Epoch 51/60
Model trained in 3.31s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.759
  Epoch 52/60
Model trained in 3.26s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.581
  Epoch 53/60
Model trained in 3.33s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.135
  Epoch 54/60
Model trained in 3.33s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.702
  Epoch 55/60
Model trained in 3.13s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.906
  Epoch 56/60
Model trained in 3.30s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.462
  Epoch 57/60
Model trained in 3.29s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.184
  Epoch 58/60
Model trained in 3.13s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.853
  Early stopping triggered.

  best_val_SMAPE=69.602

Combination 786/1152: {'encoder_hidden_size': 48, 'encoder_layers': 1, 'encoder_dropout': 0.0, 'decoder_hidden_size': 28, 'decoder_layers': 2, 'decoder_dropout': 0.0, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 20, 'batch_size': 32, 'sequence_length': 168}
Time: 76.17 minutes - estimated total time: 111.64 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 3.46s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 172.166
  Epoch 2/60
Model trained in 3.51s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 157.971
  Epoch 3/60
Model trained in 3.46s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 146.571
  Epoch 4/60
Model trained in 3.45s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 136.778
  Epoch 5/60
Model trained in 3.31s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 127.910
  Epoch 6/60
Model trained in 3.56s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 120.240
  Epoch 7/60
Model trained in 3.32s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 116.964
  Epoch 8/60
Model trained in 3.35s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 114.001
  Epoch 9/60
Model trained in 3.53s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 107.172
  Epoch 10/60
Model trained in 3.40s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 102.083
  Epoch 11/60
Model trained in 3.33s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 96.415
  Epoch 12/60
Model trained in 3.67s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.358
  Epoch 13/60
Model trained in 3.47s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.367
  Epoch 14/60
Model trained in 3.40s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.462
  Epoch 15/60
Model trained in 3.48s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.751
  Epoch 16/60
Model trained in 3.27s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.439
  Epoch 17/60
Model trained in 3.28s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.726
  Epoch 18/60
Model trained in 3.44s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.115
  Epoch 19/60
Model trained in 3.25s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.364
  Epoch 20/60
Model trained in 3.31s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.690
  Epoch 21/60
Model trained in 3.55s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.443
  Epoch 22/60
Model trained in 3.31s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.644
  Epoch 23/60
Model trained in 3.43s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.516
  Epoch 24/60
Model trained in 3.56s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.013
  Epoch 25/60
Model trained in 3.36s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.921
  Epoch 26/60
Model trained in 3.37s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.273
  Epoch 27/60
Model trained in 3.53s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.392
  Epoch 28/60
Model trained in 3.33s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.374
  Epoch 29/60
Model trained in 3.37s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.749
  Epoch 30/60
Model trained in 3.57s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.524
  Epoch 31/60
Model trained in 3.31s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.052
  Epoch 32/60
Model trained in 3.51s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.156
  Epoch 33/60
Model trained in 3.57s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.282
  Epoch 34/60
Model trained in 3.37s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.051
  Epoch 35/60
Model trained in 3.42s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.617
  Epoch 36/60
Model trained in 3.56s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.100
  Epoch 37/60
Model trained in 3.36s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.441
  Epoch 38/60
Model trained in 3.40s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.033
  Epoch 39/60
Model trained in 3.56s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.713
  Epoch 40/60
Model trained in 3.57s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.665
  Epoch 41/60
Model trained in 3.23s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.813
  Epoch 42/60
Model trained in 3.51s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.256
  Epoch 43/60
Model trained in 3.29s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.606
  Epoch 44/60
Model trained in 3.24s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.912
  Epoch 45/60
Model trained in 3.47s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.937
  Epoch 46/60
Model trained in 3.30s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.307
  Epoch 47/60
Model trained in 3.31s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.908
  Epoch 48/60
Model trained in 3.49s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.520
  Epoch 49/60
Model trained in 3.27s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.482
  Epoch 50/60
Model trained in 3.34s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.667
  Epoch 51/60
Model trained in 3.49s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.430
  Early stopping triggered.

  best_val_SMAPE=79.052

Combination 787/1152: {'encoder_hidden_size': 48, 'encoder_layers': 1, 'encoder_dropout': 0.0, 'decoder_hidden_size': 28, 'decoder_layers': 2, 'decoder_dropout': 0.0, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 20, 'batch_size': 64, 'sequence_length': 24}
Time: 79.58 minutes - estimated total time: 116.49 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 2.12s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 181.107
  Epoch 2/60
Model trained in 2.02s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 172.065
  Epoch 3/60
Model trained in 2.21s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 164.460
  Epoch 4/60
Model trained in 1.99s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 157.755
  Epoch 5/60
Model trained in 2.15s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 151.745
  Epoch 6/60
Model trained in 2.03s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 146.262
  Epoch 7/60
Model trained in 2.03s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 141.158
  Epoch 8/60
Model trained in 2.08s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 136.397
  Epoch 9/60
Model trained in 1.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 131.852
  Epoch 10/60
Model trained in 1.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 127.474
  Epoch 11/60
Model trained in 2.15s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 124.822
  Epoch 12/60
Model trained in 2.01s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 121.224
  Epoch 13/60
Model trained in 2.15s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 117.420
  Epoch 14/60
Model trained in 1.99s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 114.168
  Epoch 15/60
Model trained in 2.23s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 110.576
  Epoch 16/60
Model trained in 2.02s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 107.512
  Epoch 17/60
Model trained in 1.99s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 105.260
  Epoch 18/60
Model trained in 2.08s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 101.963
  Epoch 19/60
Model trained in 1.99s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 99.264
  Epoch 20/60
Model trained in 2.17s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 96.417
  Epoch 21/60
Model trained in 1.99s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.916
  Epoch 22/60
Model trained in 2.16s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.850
  Epoch 23/60
Model trained in 1.99s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.357
  Epoch 24/60
Model trained in 2.02s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.914
  Epoch 25/60
Model trained in 2.08s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.556
  Epoch 26/60
Model trained in 2.00s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.553
  Epoch 27/60
Model trained in 2.21s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.930
  Epoch 28/60
Model trained in 1.98s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.323
  Epoch 29/60
Model trained in 2.14s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.009
  Epoch 30/60
Model trained in 1.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.671
  Epoch 31/60
Model trained in 2.05s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.922
  Epoch 32/60
Model trained in 1.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.601
  Epoch 33/60
Model trained in 1.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.663
  Epoch 34/60
Model trained in 2.05s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.438
  Epoch 35/60
Model trained in 1.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.896
  Epoch 36/60
Model trained in 2.18s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.128
  Epoch 37/60
Model trained in 1.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.297
  Epoch 38/60
Model trained in 2.09s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.422
  Epoch 39/60
Model trained in 1.95s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.731
  Epoch 40/60
Model trained in 2.15s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.998
  Epoch 41/60
Model trained in 2.13s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.768
  Epoch 42/60
Model trained in 1.98s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.628
  Epoch 43/60
Model trained in 2.16s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.767
  Epoch 44/60
Model trained in 1.99s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.079
  Epoch 45/60
Model trained in 2.19s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.645
  Epoch 46/60
Model trained in 2.04s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.441
  Epoch 47/60
Model trained in 2.09s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.634
  Epoch 48/60
Model trained in 2.08s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.009
  Epoch 49/60
Model trained in 2.01s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.683
  Epoch 50/60
Model trained in 2.08s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.638
  Epoch 51/60
Model trained in 1.97s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.717
  Epoch 52/60
Model trained in 2.17s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.843
  Epoch 53/60
Model trained in 2.01s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.983
  Epoch 54/60
Model trained in 2.15s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.096
  Epoch 55/60
Model trained in 2.08s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.776
  Epoch 56/60
Model trained in 2.13s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.647
  Epoch 57/60
Model trained in 2.10s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.127
  Early stopping triggered.

  best_val_SMAPE=74.297

Combination 788/1152: {'encoder_hidden_size': 48, 'encoder_layers': 1, 'encoder_dropout': 0.0, 'decoder_hidden_size': 28, 'decoder_layers': 2, 'decoder_dropout': 0.0, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 20, 'batch_size': 64, 'sequence_length': 168}
Time: 82.09 minutes - estimated total time: 120.01 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 2.45s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 181.170
  Epoch 2/60
Model trained in 2.17s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 172.161
  Epoch 3/60
Model trained in 2.39s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 164.594
  Epoch 4/60
Model trained in 2.11s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 157.916
  Epoch 5/60
Model trained in 2.50s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 151.932
  Epoch 6/60
Model trained in 2.19s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 146.468
  Epoch 7/60
Model trained in 2.57s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 141.384
  Epoch 8/60
Model trained in 2.20s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 136.748
  Epoch 9/60
Model trained in 2.60s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 132.112
  Epoch 10/60
Model trained in 2.21s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 127.826
  Epoch 11/60
Model trained in 2.41s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 125.371
  Epoch 12/60
Model trained in 2.13s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 121.500
  Epoch 13/60
Model trained in 2.21s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 118.433
  Epoch 14/60
Model trained in 2.25s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 114.848
  Epoch 15/60
Model trained in 2.23s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 110.826
  Epoch 16/60
Model trained in 2.34s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 107.321
  Epoch 17/60
Model trained in 2.07s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 104.562
  Epoch 18/60
Model trained in 2.37s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 101.868
  Epoch 19/60
Model trained in 2.09s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 99.499
  Epoch 20/60
Model trained in 2.52s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 97.120
  Epoch 21/60
Model trained in 2.28s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 94.621
  Epoch 22/60
Model trained in 2.46s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.374
  Epoch 23/60
Model trained in 2.19s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.521
  Epoch 24/60
Model trained in 2.57s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.094
  Epoch 25/60
Model trained in 2.19s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.836
  Epoch 26/60
Model trained in 2.41s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.345
  Epoch 27/60
Model trained in 2.19s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.062
  Epoch 28/60
Model trained in 2.33s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.291
  Epoch 29/60
Model trained in 2.33s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.247
  Epoch 30/60
Model trained in 2.28s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.374
  Epoch 31/60
Model trained in 2.30s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.902
  Epoch 32/60
Model trained in 2.29s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.087
  Epoch 33/60
Model trained in 2.33s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.572
  Epoch 34/60
Model trained in 2.14s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.310
  Epoch 35/60
Model trained in 2.34s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.507
  Epoch 36/60
Model trained in 2.14s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.172
  Epoch 37/60
Model trained in 2.52s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.257
  Epoch 38/60
Model trained in 2.17s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.710
  Epoch 39/60
Model trained in 2.44s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.067
  Epoch 40/60
Model trained in 2.16s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.725
  Epoch 41/60
Model trained in 2.40s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.938
  Epoch 42/60
Model trained in 2.15s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.845
  Epoch 43/60
Model trained in 2.42s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.407
  Epoch 44/60
Model trained in 2.31s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.279
  Epoch 45/60
Model trained in 2.30s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.816
  Epoch 46/60
Model trained in 2.30s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.782
  Epoch 47/60
Model trained in 2.14s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.150
  Epoch 48/60
Model trained in 2.40s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.246
  Epoch 49/60
Model trained in 2.13s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.504
  Epoch 50/60
Model trained in 2.39s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.818
  Epoch 51/60
Model trained in 2.18s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.345
  Epoch 52/60
Model trained in 2.53s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.363
  Epoch 53/60
Model trained in 2.10s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.548
  Epoch 54/60
Model trained in 2.42s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.500
  Epoch 55/60
Model trained in 2.11s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.848
  Epoch 56/60
Model trained in 2.34s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.085
  Epoch 57/60
Model trained in 2.15s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.829
  Epoch 58/60
Model trained in 2.30s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.078
  Epoch 59/60
Model trained in 2.28s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.805
  Epoch 60/60
Model trained in 2.27s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.298

  best_val_SMAPE=77.938

Combination 789/1152: {'encoder_hidden_size': 48, 'encoder_layers': 1, 'encoder_dropout': 0.0, 'decoder_hidden_size': 28, 'decoder_layers': 2, 'decoder_dropout': 0.0, 'learning_rate': 0.0005, 'max_epochs': 60, 'patience': 20, 'batch_size': 32, 'sequence_length': 24}
Time: 84.96 minutes - estimated total time: 124.05 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 3.28s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 181.109
  Epoch 2/60
Model trained in 3.15s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 172.211
  Epoch 3/60
Model trained in 3.37s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 164.682
  Epoch 4/60
Model trained in 3.24s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 158.011
  Epoch 5/60
Model trained in 3.56s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 152.016
  Epoch 6/60
Model trained in 3.15s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 146.541
  Epoch 7/60
Model trained in 3.45s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 141.428
  Epoch 8/60
Model trained in 3.46s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 136.658
  Epoch 9/60
Model trained in 3.21s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 132.068
  Epoch 10/60
Model trained in 3.50s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 128.292
  Epoch 11/60
Model trained in 3.32s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 124.997
  Epoch 12/60
Model trained in 3.19s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 121.940
  Epoch 13/60
Model trained in 3.54s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 118.496
  Epoch 14/60
Model trained in 3.23s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 115.170
  Epoch 15/60
Model trained in 3.26s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 111.682
  Epoch 16/60
Model trained in 3.49s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 108.264
  Epoch 17/60
Model trained in 3.17s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 105.094
  Epoch 18/60
Model trained in 3.40s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 101.785
  Epoch 19/60
Model trained in 3.38s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 99.206
  Epoch 20/60
Model trained in 3.06s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 97.088
  Epoch 21/60
Model trained in 3.52s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 94.953
  Epoch 22/60
Model trained in 3.18s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.283
  Epoch 23/60
Model trained in 3.19s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.734
  Epoch 24/60
Model trained in 3.38s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.862
  Epoch 25/60
Model trained in 3.17s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.350
  Epoch 26/60
Model trained in 3.32s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.196
  Epoch 27/60
Model trained in 3.45s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.072
  Epoch 28/60
Model trained in 3.18s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.823
  Epoch 29/60
Model trained in 3.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.564
  Epoch 30/60
Model trained in 3.36s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.833
  Epoch 31/60
Model trained in 3.20s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.944
  Epoch 32/60
Model trained in 3.48s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.250
  Epoch 33/60
Model trained in 3.21s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.265
  Epoch 34/60
Model trained in 3.35s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.113
  Epoch 35/60
Model trained in 3.47s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.890
  Epoch 36/60
Model trained in 3.08s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.487
  Epoch 37/60
Model trained in 3.48s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.992
  Epoch 38/60
Model trained in 3.54s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.521
  Epoch 39/60
Model trained in 3.16s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.804
  Epoch 40/60
Model trained in 3.50s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.405
  Epoch 41/60
Model trained in 3.29s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.081
  Epoch 42/60
Model trained in 3.15s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.522
  Epoch 43/60
Model trained in 3.41s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.455
  Epoch 44/60
Model trained in 3.05s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.127
  Epoch 45/60
Model trained in 3.28s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.253
  Epoch 46/60
Model trained in 3.33s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.249
  Epoch 47/60
Model trained in 3.03s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.936
  Epoch 48/60
Model trained in 3.38s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.681
  Epoch 49/60
Model trained in 3.17s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.853
  Epoch 50/60
Model trained in 3.13s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.835
  Epoch 51/60
Model trained in 3.42s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.679
  Epoch 52/60
Model trained in 3.20s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.960
  Epoch 53/60
Model trained in 3.30s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.496
  Epoch 54/60
Model trained in 3.33s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.065
  Epoch 55/60
Model trained in 3.05s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.411
  Epoch 56/60
Model trained in 3.45s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.624
  Epoch 57/60
Model trained in 3.30s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.599
  Epoch 58/60
Model trained in 3.24s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.073
  Epoch 59/60
Model trained in 3.48s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.299
  Epoch 60/60
Model trained in 3.43s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.784

  best_val_SMAPE=77.127

Combination 790/1152: {'encoder_hidden_size': 48, 'encoder_layers': 1, 'encoder_dropout': 0.0, 'decoder_hidden_size': 28, 'decoder_layers': 2, 'decoder_dropout': 0.0, 'learning_rate': 0.0005, 'max_epochs': 60, 'patience': 20, 'batch_size': 32, 'sequence_length': 168}
Time: 88.85 minutes - estimated total time: 129.56 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 3.47s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 181.121
  Epoch 2/60
Model trained in 3.37s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 172.268
  Epoch 3/60
Model trained in 3.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 164.776
  Epoch 4/60
Model trained in 3.29s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 158.131
  Epoch 5/60
Model trained in 3.45s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 152.159
  Epoch 6/60
Model trained in 3.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 146.698
  Epoch 7/60
Model trained in 3.34s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 141.597
  Epoch 8/60
Model trained in 3.52s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 136.832
  Epoch 9/60
Model trained in 3.61s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 132.281
  Epoch 10/60
Model trained in 3.29s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 127.877
  Epoch 11/60
Model trained in 3.58s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 123.706
  Epoch 12/60
Model trained in 3.51s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 120.975
  Epoch 13/60
Model trained in 3.24s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 118.118
  Epoch 14/60
Model trained in 3.65s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 115.025
  Epoch 15/60
Model trained in 3.49s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 111.631
  Epoch 16/60
Model trained in 3.17s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 108.868
  Epoch 17/60
Model trained in 3.60s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 106.238
  Epoch 18/60
Model trained in 3.35s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 104.159
  Epoch 19/60
Model trained in 3.19s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 102.568
  Epoch 20/60
Model trained in 3.62s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 100.432
  Epoch 21/60
Model trained in 3.51s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 97.813
  Epoch 22/60
Model trained in 3.51s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 95.868
  Epoch 23/60
Model trained in 3.67s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.312
  Epoch 24/60
Model trained in 3.38s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.069
  Epoch 25/60
Model trained in 3.52s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.492
  Epoch 26/60
Model trained in 3.22s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.642
  Epoch 27/60
Model trained in 3.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.981
  Epoch 28/60
Model trained in 3.55s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.707
  Epoch 29/60
Model trained in 3.37s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.725
  Epoch 30/60
Model trained in 3.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.422
  Epoch 31/60
Model trained in 3.48s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.114
  Epoch 32/60
Model trained in 3.51s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.051
  Epoch 33/60
Model trained in 3.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.063
  Epoch 34/60
Model trained in 3.35s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.530
  Epoch 35/60
Model trained in 3.48s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.071
  Epoch 36/60
Model trained in 3.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.105
  Epoch 37/60
Model trained in 3.22s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.546
  Epoch 38/60
Model trained in 3.50s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.270
  Epoch 39/60
Model trained in 3.65s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.674
  Epoch 40/60
Model trained in 3.46s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.357
  Epoch 41/60
Model trained in 3.49s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.384
  Epoch 42/60
Model trained in 3.59s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.786
  Epoch 43/60
Model trained in 3.20s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.163
  Epoch 44/60
Model trained in 3.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.298
  Epoch 45/60
Model trained in 3.58s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.372
  Epoch 46/60
Model trained in 3.30s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.446
  Epoch 47/60
Model trained in 3.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.753
  Epoch 48/60
Model trained in 3.61s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.710
  Epoch 49/60
Model trained in 3.37s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.439
  Epoch 50/60
Model trained in 3.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.217
  Epoch 51/60
Model trained in 3.38s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.905
  Epoch 52/60
Model trained in 3.50s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.074
  Epoch 53/60
Model trained in 3.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.757
  Epoch 54/60
Model trained in 3.23s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.900
  Epoch 55/60
Model trained in 3.56s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.046
  Epoch 56/60
Model trained in 3.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.344
  Epoch 57/60
Model trained in 3.31s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.225
  Epoch 58/60
Model trained in 3.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.553
  Early stopping triggered.

  best_val_SMAPE=77.270

Combination 791/1152: {'encoder_hidden_size': 48, 'encoder_layers': 1, 'encoder_dropout': 0.0, 'decoder_hidden_size': 28, 'decoder_layers': 2, 'decoder_dropout': 0.0, 'learning_rate': 0.0005, 'max_epochs': 60, 'patience': 20, 'batch_size': 64, 'sequence_length': 24}
Time: 92.79 minutes - estimated total time: 135.13 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 2.16s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 187.017
  Epoch 2/60
Model trained in 1.97s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 181.046
  Epoch 3/60
Model trained in 2.30s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 176.353
  Epoch 4/60
Model trained in 1.95s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 172.126
  Epoch 5/60
Model trained in 2.18s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 168.228
  Epoch 6/60
Model trained in 2.02s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 164.567
  Epoch 7/60
Model trained in 2.11s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 161.106
  Epoch 8/60
Model trained in 2.26s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 157.871
  Epoch 9/60
Model trained in 1.98s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 154.780
  Epoch 10/60
Model trained in 2.28s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 151.853
  Epoch 11/60
Model trained in 1.95s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 149.051
  Epoch 12/60
Model trained in 2.10s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 146.347
  Epoch 13/60
Model trained in 2.01s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 143.725
  Epoch 14/60
Model trained in 2.01s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 141.214
  Epoch 15/60
Model trained in 2.17s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 138.773
  Epoch 16/60
Model trained in 1.95s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 136.412
  Epoch 17/60
Model trained in 2.30s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 134.097
  Epoch 18/60
Model trained in 1.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 131.818
  Epoch 19/60
Model trained in 2.08s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 129.574
  Epoch 20/60
Model trained in 2.18s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 127.381
  Epoch 21/60
Model trained in 1.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 125.250
  Epoch 22/60
Model trained in 2.15s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 123.189
  Epoch 23/60
Model trained in 1.95s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 122.664
  Epoch 24/60
Model trained in 2.21s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 121.743
  Epoch 25/60
Model trained in 1.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 120.495
  Epoch 26/60
Model trained in 2.01s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 118.801
  Epoch 27/60
Model trained in 2.08s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 117.065
  Epoch 28/60
Model trained in 1.95s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 115.474
  Epoch 29/60
Model trained in 2.20s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 113.736
  Epoch 30/60
Model trained in 1.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 112.049
  Epoch 31/60
Model trained in 2.22s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 110.641
  Epoch 32/60
Model trained in 1.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 109.041
  Epoch 33/60
Model trained in 2.05s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 107.640
  Epoch 34/60
Model trained in 2.04s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 106.211
  Epoch 35/60
Model trained in 1.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 104.579
  Epoch 36/60
Model trained in 2.24s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 103.478
  Epoch 37/60
Model trained in 2.00s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 102.584
  Epoch 38/60
Model trained in 2.25s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 101.263
  Epoch 39/60
Model trained in 2.05s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 99.902
  Epoch 40/60
Model trained in 2.08s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 98.574
  Epoch 41/60
Model trained in 2.16s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 97.297
  Epoch 42/60
Model trained in 1.95s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 95.965
  Epoch 43/60
Model trained in 2.26s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 94.946
  Epoch 44/60
Model trained in 1.99s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.578
  Epoch 45/60
Model trained in 2.22s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.521
  Epoch 46/60
Model trained in 2.00s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.436
  Epoch 47/60
Model trained in 2.05s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.913
  Epoch 48/60
Model trained in 2.15s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.351
  Epoch 49/60
Model trained in 1.95s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.351
  Epoch 50/60
Model trained in 2.26s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.862
  Epoch 51/60
Model trained in 2.03s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.406
  Epoch 52/60
Model trained in 2.24s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.886
  Epoch 53/60
Model trained in 1.97s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.378
  Epoch 54/60
Model trained in 2.06s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.832
  Epoch 55/60
Model trained in 2.14s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.267
  Epoch 56/60
Model trained in 2.15s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.194
  Epoch 57/60
Model trained in 2.21s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.460
  Epoch 58/60
Model trained in 1.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.374
  Epoch 59/60
Model trained in 2.19s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.558
  Epoch 60/60
Model trained in 1.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.494

  best_val_SMAPE=82.494

Combination 792/1152: {'encoder_hidden_size': 48, 'encoder_layers': 1, 'encoder_dropout': 0.0, 'decoder_hidden_size': 28, 'decoder_layers': 2, 'decoder_dropout': 0.0, 'learning_rate': 0.0005, 'max_epochs': 60, 'patience': 20, 'batch_size': 64, 'sequence_length': 168}
Time: 95.45 minutes - estimated total time: 138.83 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 2.22s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 187.041
  Epoch 2/60
Model trained in 2.31s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 181.105
  Epoch 3/60
Model trained in 2.31s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 176.432
  Epoch 4/60
Model trained in 2.16s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 172.225
  Epoch 5/60
Model trained in 2.45s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 168.348
  Epoch 6/60
Model trained in 2.17s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 164.702
  Epoch 7/60
Model trained in 2.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 161.259
  Epoch 8/60
Model trained in 2.20s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 158.032
  Epoch 9/60
Model trained in 2.60s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 154.962
  Epoch 10/60
Model trained in 2.22s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 152.061
  Epoch 11/60
Model trained in 2.09s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 149.532
  Epoch 12/60
Model trained in 2.30s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 146.556
  Epoch 13/60
Model trained in 2.22s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 143.944
  Epoch 14/60
Model trained in 2.32s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 141.440
  Epoch 15/60
Model trained in 2.14s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 139.015
  Epoch 16/60
Model trained in 2.32s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 136.667
  Epoch 17/60
Model trained in 2.16s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 134.393
  Epoch 18/60
Model trained in 2.49s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 132.091
  Epoch 19/60
Model trained in 2.21s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 129.876
  Epoch 20/60
Model trained in 2.26s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 127.809
  Epoch 21/60
Model trained in 2.17s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 125.743
  Epoch 22/60
Model trained in 2.15s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 123.567
  Epoch 23/60
Model trained in 2.22s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 121.439
  Epoch 24/60
Model trained in 2.18s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 119.585
  Epoch 25/60
Model trained in 2.28s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 119.763
  Epoch 26/60
Model trained in 2.20s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 117.292
  Epoch 27/60
Model trained in 2.32s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 114.974
  Epoch 28/60
Model trained in 2.15s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 112.965
  Epoch 29/60
Model trained in 2.38s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 111.201
  Epoch 30/60
Model trained in 2.28s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 109.334
  Epoch 31/60
Model trained in 2.38s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 107.868
  Epoch 32/60
Model trained in 2.19s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 106.298
  Epoch 33/60
Model trained in 2.26s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 104.677
  Epoch 34/60
Model trained in 2.04s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 103.146
  Epoch 35/60
Model trained in 2.28s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 101.426
  Epoch 36/60
Model trained in 2.07s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 99.899
  Epoch 37/60
Model trained in 2.28s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 98.585
  Epoch 38/60
Model trained in 2.17s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 97.189
  Epoch 39/60
Model trained in 2.43s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 96.085
  Epoch 40/60
Model trained in 2.24s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 94.346
  Epoch 41/60
Model trained in 2.38s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.099
  Epoch 42/60
Model trained in 2.30s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.955
  Epoch 43/60
Model trained in 2.18s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.840
  Epoch 44/60
Model trained in 2.31s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.888
  Epoch 45/60
Model trained in 2.18s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.826
  Epoch 46/60
Model trained in 2.32s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.984
  Epoch 47/60
Model trained in 2.17s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.556
  Epoch 48/60
Model trained in 2.35s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.191
  Epoch 49/60
Model trained in 2.22s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.037
  Epoch 50/60
Model trained in 2.32s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.895
  Epoch 51/60
Model trained in 2.16s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.872
  Epoch 52/60
Model trained in 2.34s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.686
  Epoch 53/60
Model trained in 2.13s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.928
  Epoch 54/60
Model trained in 2.34s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.091
  Epoch 55/60
Model trained in 2.12s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.305
  Epoch 56/60
Model trained in 2.28s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.372
  Epoch 57/60
Model trained in 2.13s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.698
  Epoch 58/60
Model trained in 2.19s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.021
  Epoch 59/60
Model trained in 2.28s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.219
  Epoch 60/60
Model trained in 2.39s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.536

  best_val_SMAPE=75.536

Combination 793/1152: {'encoder_hidden_size': 48, 'encoder_layers': 1, 'encoder_dropout': 0.0, 'decoder_hidden_size': 28, 'decoder_layers': 2, 'decoder_dropout': 0.2, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 20, 'batch_size': 32, 'sequence_length': 24}
Time: 98.29 minutes - estimated total time: 142.79 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 3.22s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 172.156
  Epoch 2/60
Model trained in 3.15s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 157.885
  Epoch 3/60
Model trained in 3.28s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 146.434
  Epoch 4/60
Model trained in 3.34s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 136.604
  Epoch 5/60
Model trained in 3.19s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 127.708
  Epoch 6/60
Model trained in 3.24s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 119.491
  Epoch 7/60
Model trained in 3.33s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 114.143
  Epoch 8/60
Model trained in 3.44s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 109.546
  Epoch 9/60
Model trained in 3.17s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 103.984
  Epoch 10/60
Model trained in 3.21s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 99.032
  Epoch 11/60
Model trained in 3.27s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.376
  Epoch 12/60
Model trained in 3.27s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.858
  Epoch 13/60
Model trained in 3.16s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.627
  Epoch 14/60
Model trained in 3.30s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.703
  Epoch 15/60
Model trained in 3.23s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.843
  Epoch 16/60
Model trained in 3.15s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.041
  Epoch 17/60
Model trained in 3.14s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.829
  Epoch 18/60
Model trained in 3.33s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.993
  Epoch 19/60
Model trained in 3.26s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.026
  Epoch 20/60
Model trained in 3.22s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.102
  Epoch 21/60
Model trained in 3.22s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.365
  Epoch 22/60
Model trained in 3.34s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.810
  Epoch 23/60
Model trained in 3.28s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.065
  Epoch 24/60
Model trained in 3.12s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.821
  Epoch 25/60
Model trained in 3.21s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.374
  Epoch 26/60
Model trained in 3.23s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.412
  Epoch 27/60
Model trained in 3.30s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.620
  Epoch 28/60
Model trained in 3.23s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.887
  Epoch 29/60
Model trained in 3.24s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.845
  Epoch 30/60
Model trained in 3.22s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.275
  Epoch 31/60
Model trained in 3.37s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.775
  Epoch 32/60
Model trained in 3.16s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.570
  Epoch 33/60
Model trained in 3.29s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.923
  Epoch 34/60
Model trained in 3.27s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.718
  Epoch 35/60
Model trained in 3.21s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.693
  Epoch 36/60
Model trained in 3.12s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.720
  Epoch 37/60
Model trained in 3.28s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.223
  Epoch 38/60
Model trained in 3.27s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.316
  Early stopping triggered.

  best_val_SMAPE=76.993

Combination 794/1152: {'encoder_hidden_size': 48, 'encoder_layers': 1, 'encoder_dropout': 0.0, 'decoder_hidden_size': 28, 'decoder_layers': 2, 'decoder_dropout': 0.2, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 20, 'batch_size': 32, 'sequence_length': 168}
Time: 100.73 minutes - estimated total time: 146.15 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 3.68s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 172.155
  Epoch 2/60
Model trained in 3.53s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 157.963
  Epoch 3/60
Model trained in 3.44s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 146.563
  Epoch 4/60
Model trained in 3.39s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 136.773
  Epoch 5/60
Model trained in 3.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 127.902
  Epoch 6/60
Model trained in 3.49s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 119.733
  Epoch 7/60
Model trained in 3.35s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 112.517
  Epoch 8/60
Model trained in 3.52s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 108.640
  Epoch 9/60
Model trained in 3.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 102.713
  Epoch 10/60
Model trained in 3.38s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 99.292
  Epoch 11/60
Model trained in 3.40s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 96.358
  Epoch 12/60
Model trained in 3.34s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.436
  Epoch 13/60
Model trained in 3.45s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.865
  Epoch 14/60
Model trained in 3.50s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.922
  Epoch 15/60
Model trained in 3.34s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.789
  Epoch 16/60
Model trained in 3.23s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.610
  Epoch 17/60
Model trained in 3.53s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.073
  Epoch 18/60
Model trained in 3.38s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.073
  Epoch 19/60
Model trained in 3.35s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.796
  Epoch 20/60
Model trained in 3.23s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.015
  Epoch 21/60
Model trained in 3.40s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.049
  Epoch 22/60
Model trained in 3.54s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.161
  Epoch 23/60
Model trained in 3.46s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.425
  Epoch 24/60
Model trained in 3.33s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.013
  Epoch 25/60
Model trained in 3.46s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.505
  Epoch 26/60
Model trained in 3.48s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.452
  Epoch 27/60
Model trained in 3.45s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.950
  Epoch 28/60
Model trained in 3.33s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.708
  Epoch 29/60
Model trained in 3.37s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.406
  Epoch 30/60
Model trained in 3.36s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.764
  Epoch 31/60
Model trained in 3.35s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.023
  Epoch 32/60
Model trained in 3.50s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.106
  Epoch 33/60
Model trained in 3.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.726
  Epoch 34/60
Model trained in 3.46s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.876
  Epoch 35/60
Model trained in 3.25s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.997
  Epoch 36/60
Model trained in 3.48s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.862
  Epoch 37/60
Model trained in 3.47s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.824
  Epoch 38/60
Model trained in 3.44s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.430
  Epoch 39/60
Model trained in 3.34s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.944
  Epoch 40/60
Model trained in 3.54s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.212
  Epoch 41/60
Model trained in 3.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.864
  Epoch 42/60
Model trained in 3.41s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.741
  Epoch 43/60
Model trained in 3.24s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.007
  Epoch 44/60
Model trained in 3.33s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.436
  Epoch 45/60
Model trained in 3.38s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.645
  Epoch 46/60
Model trained in 3.34s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.318
  Epoch 47/60
Model trained in 3.24s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.320
  Epoch 48/60
Model trained in 3.31s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.862
  Epoch 49/60
Model trained in 3.49s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.609
  Epoch 50/60
Model trained in 3.48s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.933
  Epoch 51/60
Model trained in 3.22s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.647
  Epoch 52/60
Model trained in 3.42s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.823
  Epoch 53/60
Model trained in 3.43s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.739
  Epoch 54/60
Model trained in 3.38s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.660
  Epoch 55/60
Model trained in 3.23s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.266
  Epoch 56/60
Model trained in 3.50s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.173
  Epoch 57/60
Model trained in 3.48s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.069
  Epoch 58/60
Model trained in 3.44s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.970
  Epoch 59/60
Model trained in 3.37s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.906
  Epoch 60/60
Model trained in 3.41s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.322

  best_val_SMAPE=75.069

Combination 795/1152: {'encoder_hidden_size': 48, 'encoder_layers': 1, 'encoder_dropout': 0.0, 'decoder_hidden_size': 28, 'decoder_layers': 2, 'decoder_dropout': 0.2, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 20, 'batch_size': 64, 'sequence_length': 24}
Time: 104.73 minutes - estimated total time: 151.76 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 2.00s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 181.097
  Epoch 2/60
Model trained in 2.12s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 172.056
  Epoch 3/60
Model trained in 1.99s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 164.451
  Epoch 4/60
Model trained in 2.10s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 157.746
  Epoch 5/60
Model trained in 2.05s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 151.737
  Epoch 6/60
Model trained in 2.10s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 146.254
  Epoch 7/60
Model trained in 2.03s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 141.155
  Epoch 8/60
Model trained in 2.07s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 136.391
  Epoch 9/60
Model trained in 2.07s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 131.838
  Epoch 10/60
Model trained in 2.12s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 127.440
  Epoch 11/60
Model trained in 2.19s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 123.233
  Epoch 12/60
Model trained in 2.12s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 120.462
  Epoch 13/60
Model trained in 1.97s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 119.156
  Epoch 14/60
Model trained in 2.09s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 116.689
  Epoch 15/60
Model trained in 2.04s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 115.702
  Epoch 16/60
Model trained in 2.09s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 114.597
  Epoch 17/60
Model trained in 1.99s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 111.383
  Epoch 18/60
Model trained in 2.05s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 108.248
  Epoch 19/60
Model trained in 2.00s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 105.986
  Epoch 20/60
Model trained in 2.01s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 102.725
  Epoch 21/60
Model trained in 1.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 100.033
  Epoch 22/60
Model trained in 2.04s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 98.272
  Epoch 23/60
Model trained in 1.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 96.502
  Epoch 24/60
Model trained in 2.17s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 94.982
  Epoch 25/60
Model trained in 1.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 94.194
  Epoch 26/60
Model trained in 1.98s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.663
  Epoch 27/60
Model trained in 2.00s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.384
  Epoch 28/60
Model trained in 2.01s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.500
  Epoch 29/60
Model trained in 1.95s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.597
  Epoch 30/60
Model trained in 2.08s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.460
  Epoch 31/60
Model trained in 2.03s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.098
  Epoch 32/60
Model trained in 2.10s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.307
  Epoch 33/60
Model trained in 1.97s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.093
  Epoch 34/60
Model trained in 2.08s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.472
  Epoch 35/60
Model trained in 2.02s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.657
  Epoch 36/60
Model trained in 2.18s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.383
  Epoch 37/60
Model trained in 2.10s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.333
  Epoch 38/60
Model trained in 2.09s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.512
  Epoch 39/60
Model trained in 2.03s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.676
  Epoch 40/60
Model trained in 2.07s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.579
  Epoch 41/60
Model trained in 2.06s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.218
  Epoch 42/60
Model trained in 2.12s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.787
  Epoch 43/60
Model trained in 2.05s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.912
  Epoch 44/60
Model trained in 2.10s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 94.844
  Epoch 45/60
Model trained in 2.00s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.710
  Epoch 46/60
Model trained in 2.06s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.303
  Epoch 47/60
Model trained in 2.03s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.312
  Epoch 48/60
Model trained in 2.12s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.395
  Epoch 49/60
Model trained in 2.15s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.988
  Epoch 50/60
Model trained in 2.07s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.364
  Epoch 51/60
Model trained in 2.09s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.529
  Epoch 52/60
Model trained in 2.07s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.371
  Epoch 53/60
Model trained in 1.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.773
  Epoch 54/60
Model trained in 2.10s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.961
  Epoch 55/60
Model trained in 2.05s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.939
  Epoch 56/60
Model trained in 2.07s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.936
  Epoch 57/60
Model trained in 1.98s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.625
  Early stopping triggered.

  best_val_SMAPE=88.333

Combination 796/1152: {'encoder_hidden_size': 48, 'encoder_layers': 1, 'encoder_dropout': 0.0, 'decoder_hidden_size': 28, 'decoder_layers': 2, 'decoder_dropout': 0.2, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 20, 'batch_size': 64, 'sequence_length': 168}
Time: 107.23 minutes - estimated total time: 155.19 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 2.25s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 181.130
  Epoch 2/60
Model trained in 2.38s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 172.133
  Epoch 3/60
Model trained in 2.36s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 164.570
  Epoch 4/60
Model trained in 2.39s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 157.892
  Epoch 5/60
Model trained in 2.24s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 151.910
  Epoch 6/60
Model trained in 2.38s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 146.448
  Epoch 7/60
Model trained in 2.19s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 141.366
  Epoch 8/60
Model trained in 2.32s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 136.622
  Epoch 9/60
Model trained in 2.20s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 132.097
  Epoch 10/60
Model trained in 2.38s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 127.715
  Epoch 11/60
Model trained in 2.24s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 124.916
  Epoch 12/60
Model trained in 2.30s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 121.713
  Epoch 13/60
Model trained in 2.29s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 117.706
  Epoch 14/60
Model trained in 2.20s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 114.384
  Epoch 15/60
Model trained in 2.30s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 112.125
  Epoch 16/60
Model trained in 2.23s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 109.404
  Epoch 17/60
Model trained in 2.28s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 107.208
  Epoch 18/60
Model trained in 2.20s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 104.334
  Epoch 19/60
Model trained in 2.43s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 101.672
  Epoch 20/60
Model trained in 2.25s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 100.216
  Epoch 21/60
Model trained in 2.56s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 97.697
  Epoch 22/60
Model trained in 2.25s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 95.608
  Epoch 23/60
Model trained in 2.36s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.780
  Epoch 24/60
Model trained in 2.16s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.328
  Epoch 25/60
Model trained in 2.35s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.574
  Epoch 26/60
Model trained in 2.18s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.774
  Epoch 27/60
Model trained in 2.36s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.702
  Epoch 28/60
Model trained in 2.21s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.941
  Epoch 29/60
Model trained in 2.25s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.431
  Epoch 30/60
Model trained in 2.25s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.048
  Epoch 31/60
Model trained in 2.22s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.370
  Epoch 32/60
Model trained in 2.33s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.900
  Epoch 33/60
Model trained in 2.40s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.434
  Epoch 34/60
Model trained in 2.34s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.096
  Epoch 35/60
Model trained in 2.14s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.594
  Epoch 36/60
Model trained in 2.35s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.036
  Epoch 37/60
Model trained in 2.26s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.255
  Epoch 38/60
Model trained in 2.42s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.346
  Epoch 39/60
Model trained in 2.17s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.207
  Epoch 40/60
Model trained in 2.15s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.429
  Epoch 41/60
Model trained in 2.43s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.998
  Epoch 42/60
Model trained in 2.27s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.192
  Epoch 43/60
Model trained in 2.32s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.392
  Epoch 44/60
Model trained in 2.21s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.411
  Epoch 45/60
Model trained in 2.26s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.909
  Epoch 46/60
Model trained in 2.32s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.636
  Epoch 47/60
Model trained in 2.25s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.542
  Epoch 48/60
Model trained in 2.37s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.409
  Epoch 49/60
Model trained in 2.15s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.949
  Epoch 50/60
Model trained in 2.38s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.645
  Epoch 51/60
Model trained in 2.21s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.182
  Epoch 52/60
Model trained in 2.47s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.388
  Epoch 53/60
Model trained in 2.22s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.489
  Epoch 54/60
Model trained in 2.39s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.599
  Epoch 55/60
Model trained in 2.21s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.057
  Epoch 56/60
Model trained in 2.45s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.214
  Epoch 57/60
Model trained in 2.21s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.578
  Epoch 58/60
Model trained in 2.45s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.580
  Epoch 59/60
Model trained in 2.16s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.229
  Early stopping triggered.

  best_val_SMAPE=74.207

Combination 797/1152: {'encoder_hidden_size': 48, 'encoder_layers': 1, 'encoder_dropout': 0.0, 'decoder_hidden_size': 28, 'decoder_layers': 2, 'decoder_dropout': 0.2, 'learning_rate': 0.0005, 'max_epochs': 60, 'patience': 20, 'batch_size': 32, 'sequence_length': 24}
Time: 110.07 minutes - estimated total time: 159.10 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 3.39s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 181.099
  Epoch 2/60
Model trained in 3.21s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 172.203
  Epoch 3/60
Model trained in 3.53s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 164.675
  Epoch 4/60
Model trained in 3.38s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 158.004
  Epoch 5/60
Model trained in 3.41s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 152.010
  Epoch 6/60
Model trained in 3.20s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 146.528
  Epoch 7/60
Model trained in 3.21s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 141.412
  Epoch 8/60
Model trained in 3.34s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 136.632
  Epoch 9/60
Model trained in 3.26s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 132.061
  Epoch 10/60
Model trained in 3.12s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 127.638
  Epoch 11/60
Model trained in 3.52s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 123.486
  Epoch 12/60
Model trained in 3.38s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 119.366
  Epoch 13/60
Model trained in 3.20s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 117.073
  Epoch 14/60
Model trained in 3.25s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 114.432
  Epoch 15/60
Model trained in 3.43s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 111.343
  Epoch 16/60
Model trained in 3.30s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 108.234
  Epoch 17/60
Model trained in 3.15s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 105.275
  Epoch 18/60
Model trained in 3.45s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 102.733
  Epoch 19/60
Model trained in 3.50s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 100.250
  Epoch 20/60
Model trained in 3.19s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 98.810
  Epoch 21/60
Model trained in 3.18s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 95.776
  Epoch 22/60
Model trained in 3.40s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.546
  Epoch 23/60
Model trained in 3.40s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.447
  Epoch 24/60
Model trained in 3.07s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.338
  Epoch 25/60
Model trained in 3.26s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.128
  Epoch 26/60
Model trained in 3.40s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.141
  Epoch 27/60
Model trained in 3.24s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.277
  Epoch 28/60
Model trained in 3.24s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.750
  Epoch 29/60
Model trained in 3.38s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.610
  Epoch 30/60
Model trained in 3.41s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.954
  Epoch 31/60
Model trained in 3.16s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.259
  Epoch 32/60
Model trained in 3.22s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.600
  Epoch 33/60
Model trained in 3.43s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.527
  Epoch 34/60
Model trained in 3.34s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.003
  Epoch 35/60
Model trained in 3.20s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.248
  Epoch 36/60
Model trained in 3.55s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.899
  Epoch 37/60
Model trained in 3.33s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.415
  Epoch 38/60
Model trained in 3.18s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.279
  Epoch 39/60
Model trained in 3.17s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.811
  Epoch 40/60
Model trained in 3.43s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.497
  Epoch 41/60
Model trained in 3.33s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.832
  Epoch 42/60
Model trained in 3.19s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.334
  Epoch 43/60
Model trained in 3.28s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.393
  Epoch 44/60
Model trained in 3.58s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.520
  Epoch 45/60
Model trained in 3.28s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.972
  Epoch 46/60
Model trained in 3.17s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.392
  Epoch 47/60
Model trained in 3.41s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.571
  Epoch 48/60
Model trained in 3.40s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.170
  Epoch 49/60
Model trained in 3.23s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.645
  Epoch 50/60
Model trained in 3.21s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.252
  Epoch 51/60
Model trained in 3.49s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.631
  Epoch 52/60
Model trained in 3.52s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.466
  Epoch 53/60
Model trained in 3.21s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.687
  Epoch 54/60
Model trained in 3.31s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.933
  Epoch 55/60
Model trained in 3.30s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.431
  Epoch 56/60
Model trained in 3.13s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.402
  Epoch 57/60
Model trained in 3.12s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.094
  Epoch 58/60
Model trained in 3.44s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.104
  Early stopping triggered.

  best_val_SMAPE=76.279

Combination 798/1152: {'encoder_hidden_size': 48, 'encoder_layers': 1, 'encoder_dropout': 0.0, 'decoder_hidden_size': 28, 'decoder_layers': 2, 'decoder_dropout': 0.2, 'learning_rate': 0.0005, 'max_epochs': 60, 'patience': 20, 'batch_size': 32, 'sequence_length': 168}
Time: 113.84 minutes - estimated total time: 164.34 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 3.31s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 181.108
  Epoch 2/60
Model trained in 3.63s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 172.258
  Epoch 3/60
Model trained in 3.57s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 164.767
  Epoch 4/60
Model trained in 3.50s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 158.122
  Epoch 5/60
Model trained in 3.34s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 152.151
  Epoch 6/60
Model trained in 3.65s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 146.757
  Epoch 7/60
Model trained in 3.62s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 141.589
  Epoch 8/60
Model trained in 3.32s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 136.865
  Epoch 9/60
Model trained in 3.34s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 132.443
  Epoch 10/60
Model trained in 3.58s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 128.071
  Epoch 11/60
Model trained in 3.59s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 123.865
  Epoch 12/60
Model trained in 3.45s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 119.796
  Epoch 13/60
Model trained in 3.29s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 118.254
  Epoch 14/60
Model trained in 3.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 113.930
  Epoch 15/60
Model trained in 3.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 111.466
  Epoch 16/60
Model trained in 3.39s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 109.048
  Epoch 17/60
Model trained in 3.28s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 106.732
  Epoch 18/60
Model trained in 3.54s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 103.501
  Epoch 19/60
Model trained in 3.51s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 101.391
  Epoch 20/60
Model trained in 3.23s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 98.755
  Epoch 21/60
Model trained in 3.52s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 95.878
  Epoch 22/60
Model trained in 3.53s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.256
  Epoch 23/60
Model trained in 3.47s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.170
  Epoch 24/60
Model trained in 3.22s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.578
  Epoch 25/60
Model trained in 3.34s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.457
  Epoch 26/60
Model trained in 3.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.392
  Epoch 27/60
Model trained in 3.57s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.082
  Epoch 28/60
Model trained in 3.27s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.715
  Epoch 29/60
Model trained in 3.63s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.231
  Epoch 30/60
Model trained in 3.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.008
  Epoch 31/60
Model trained in 3.30s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.732
  Epoch 32/60
Model trained in 3.54s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.334
  Epoch 33/60
Model trained in 3.35s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.971
  Epoch 34/60
Model trained in 3.54s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.725
  Epoch 35/60
Model trained in 3.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.245
  Epoch 36/60
Model trained in 3.59s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.433
  Epoch 37/60
Model trained in 3.56s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.003
  Epoch 38/60
Model trained in 3.52s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.788
  Epoch 39/60
Model trained in 3.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.588
  Epoch 40/60
Model trained in 3.54s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.633
  Epoch 41/60
Model trained in 3.29s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.205
  Epoch 42/60
Model trained in 3.59s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.587
  Epoch 43/60
Model trained in 3.50s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.070
  Epoch 44/60
Model trained in 3.42s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.046
  Epoch 45/60
Model trained in 3.25s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.619
  Epoch 46/60
Model trained in 3.46s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.463
  Epoch 47/60
Model trained in 3.63s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.632
  Epoch 48/60
Model trained in 3.33s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.381
  Epoch 49/60
Model trained in 3.23s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.520
  Epoch 50/60
Model trained in 3.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.686
  Epoch 51/60
Model trained in 3.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.457
  Epoch 52/60
Model trained in 3.42s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.465
  Epoch 53/60
Model trained in 3.47s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.958
  Epoch 54/60
Model trained in 3.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.296
  Epoch 55/60
Model trained in 3.97s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.356
  Epoch 56/60
Model trained in 3.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.944
  Epoch 57/60
Model trained in 3.62s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.742
  Epoch 58/60
Model trained in 3.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.937
  Epoch 59/60
Model trained in 3.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.912
  Early stopping triggered.

  best_val_SMAPE=75.588

Combination 799/1152: {'encoder_hidden_size': 48, 'encoder_layers': 1, 'encoder_dropout': 0.0, 'decoder_hidden_size': 28, 'decoder_layers': 2, 'decoder_dropout': 0.2, 'learning_rate': 0.0005, 'max_epochs': 60, 'patience': 20, 'batch_size': 64, 'sequence_length': 24}
Time: 117.87 minutes - estimated total time: 169.94 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 2.31s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 187.008
  Epoch 2/60
Model trained in 2.24s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 181.036
  Epoch 3/60
Model trained in 2.28s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 176.344
  Epoch 4/60
Model trained in 2.14s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 172.118
  Epoch 5/60
Model trained in 2.19s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 168.220
  Epoch 6/60
Model trained in 2.18s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 164.560
  Epoch 7/60
Model trained in 2.48s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 161.098
  Epoch 8/60
Model trained in 2.08s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 157.864
  Epoch 9/60
Model trained in 2.18s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 154.773
  Epoch 10/60
Model trained in 2.00s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 151.846
  Epoch 11/60
Model trained in 2.15s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 149.045
  Epoch 12/60
Model trained in 1.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 146.341
  Epoch 13/60
Model trained in 2.29s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 143.719
  Epoch 14/60
Model trained in 1.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 141.207
  Epoch 15/60
Model trained in 2.27s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 138.776
  Epoch 16/60
Model trained in 1.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 136.414
  Epoch 17/60
Model trained in 2.24s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 134.106
  Epoch 18/60
Model trained in 1.97s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 131.825
  Epoch 19/60
Model trained in 2.30s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 130.704
  Epoch 20/60
Model trained in 2.05s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 127.787
  Epoch 21/60
Model trained in 2.22s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 126.046
  Epoch 22/60
Model trained in 2.02s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 123.886
  Epoch 23/60
Model trained in 2.12s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 122.036
  Epoch 24/60
Model trained in 1.97s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 120.269
  Epoch 25/60
Model trained in 2.13s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 118.092
  Epoch 26/60
Model trained in 2.01s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 115.945
  Epoch 27/60
Model trained in 2.02s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 113.797
  Epoch 28/60
Model trained in 1.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 111.969
  Epoch 29/60
Model trained in 1.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 110.304
  Epoch 30/60
Model trained in 1.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 108.809
  Epoch 31/60
Model trained in 1.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 107.329
  Epoch 32/60
Model trained in 2.01s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 105.945
  Epoch 33/60
Model trained in 1.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 104.365
  Epoch 34/60
Model trained in 2.07s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 103.223
  Epoch 35/60
Model trained in 1.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 102.018
  Epoch 36/60
Model trained in 2.25s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 100.316
  Epoch 37/60
Model trained in 2.05s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 99.087
  Epoch 38/60
Model trained in 2.28s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 98.529
  Epoch 39/60
Model trained in 1.98s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 97.632
  Epoch 40/60
Model trained in 2.28s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 96.543
  Epoch 41/60
Model trained in 2.17s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 95.129
  Epoch 42/60
Model trained in 2.31s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.509
  Epoch 43/60
Model trained in 2.05s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.054
  Epoch 44/60
Model trained in 2.25s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.936
  Epoch 45/60
Model trained in 2.00s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.942
  Epoch 46/60
Model trained in 2.25s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.857
  Epoch 47/60
Model trained in 2.09s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.121
  Epoch 48/60
Model trained in 2.22s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.377
  Epoch 49/60
Model trained in 2.02s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.818
  Epoch 50/60
Model trained in 2.23s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.483
  Epoch 51/60
Model trained in 2.01s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.871
  Epoch 52/60
Model trained in 2.29s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.447
  Epoch 53/60
Model trained in 2.23s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.194
  Epoch 54/60
Model trained in 2.28s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.295
  Epoch 55/60
Model trained in 1.99s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.167
  Epoch 56/60
Model trained in 2.10s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.811
  Epoch 57/60
Model trained in 2.01s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.051
  Epoch 58/60
Model trained in 2.11s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.152
  Epoch 59/60
Model trained in 2.00s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.123
  Epoch 60/60
Model trained in 2.05s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.759

  best_val_SMAPE=80.759

Combination 800/1152: {'encoder_hidden_size': 48, 'encoder_layers': 1, 'encoder_dropout': 0.0, 'decoder_hidden_size': 28, 'decoder_layers': 2, 'decoder_dropout': 0.2, 'learning_rate': 0.0005, 'max_epochs': 60, 'patience': 20, 'batch_size': 64, 'sequence_length': 168}
Time: 120.57 minutes - estimated total time: 173.62 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 2.53s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 187.030
  Epoch 2/60
Model trained in 2.30s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 181.095
  Epoch 3/60
Model trained in 2.49s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 176.423
  Epoch 4/60
Model trained in 2.29s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 172.216
  Epoch 5/60
Model trained in 2.50s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 168.339
  Epoch 6/60
Model trained in 2.23s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 164.694
  Epoch 7/60
Model trained in 2.46s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 161.251
  Epoch 8/60
Model trained in 2.28s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 158.026
  Epoch 9/60
Model trained in 2.49s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 154.950
  Epoch 10/60
Model trained in 2.22s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 152.032
  Epoch 11/60
Model trained in 2.37s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 149.243
  Epoch 12/60
Model trained in 2.30s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 146.549
  Epoch 13/60
Model trained in 2.25s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 143.937
  Epoch 14/60
Model trained in 2.34s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 141.433
  Epoch 15/60
Model trained in 2.22s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 139.005
  Epoch 16/60
Model trained in 2.40s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 136.651
  Epoch 17/60
Model trained in 2.22s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 134.352
  Epoch 18/60
Model trained in 2.53s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 132.091
  Epoch 19/60
Model trained in 2.38s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 129.857
  Epoch 20/60
Model trained in 2.57s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 127.683
  Epoch 21/60
Model trained in 2.27s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 126.304
  Epoch 22/60
Model trained in 2.50s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 123.616
  Epoch 23/60
Model trained in 2.24s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 122.641
  Epoch 24/60
Model trained in 2.49s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 121.832
  Epoch 25/60
Model trained in 2.21s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 120.043
  Epoch 26/60
Model trained in 2.48s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 118.178
  Epoch 27/60
Model trained in 2.17s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 116.967
  Epoch 28/60
Model trained in 2.55s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 116.275
  Epoch 29/60
Model trained in 2.16s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 114.719
  Epoch 30/60
Model trained in 2.47s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 113.524
  Epoch 31/60
Model trained in 2.37s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 112.257
  Epoch 32/60
Model trained in 2.36s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 110.900
  Epoch 33/60
Model trained in 2.21s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 109.437
  Epoch 34/60
Model trained in 2.08s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 108.333
  Epoch 35/60
Model trained in 2.20s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 106.870
  Epoch 36/60
Model trained in 2.14s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 105.401
  Epoch 37/60
Model trained in 2.30s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 103.950
  Epoch 38/60
Model trained in 2.25s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 102.196
  Epoch 39/60
Model trained in 2.43s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 100.532
  Epoch 40/60
Model trained in 2.32s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 99.463
  Epoch 41/60
Model trained in 2.31s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 98.118
  Epoch 42/60
Model trained in 2.22s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 96.845
  Epoch 43/60
Model trained in 2.53s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 95.543
  Epoch 44/60
Model trained in 2.23s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 94.058
  Epoch 45/60
Model trained in 2.27s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.778
  Epoch 46/60
Model trained in 2.26s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.985
  Epoch 47/60
Model trained in 2.20s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.716
  Epoch 48/60
Model trained in 2.30s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.376
  Epoch 49/60
Model trained in 2.28s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.494
  Epoch 50/60
Model trained in 2.32s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.441
  Epoch 51/60
Model trained in 2.25s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.628
  Epoch 52/60
Model trained in 2.33s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.600
  Epoch 53/60
Model trained in 2.26s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.483
  Epoch 54/60
Model trained in 2.36s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.514
  Epoch 55/60
Model trained in 2.42s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.058
  Epoch 56/60
Model trained in 2.32s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.809
  Epoch 57/60
Model trained in 2.24s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.678
  Epoch 58/60
Model trained in 2.31s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.131
  Epoch 59/60
Model trained in 2.24s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.815
  Epoch 60/60
Model trained in 2.36s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.573

  best_val_SMAPE=81.573

Combination 801/1152: {'encoder_hidden_size': 48, 'encoder_layers': 1, 'encoder_dropout': 0.0, 'decoder_hidden_size': 33, 'decoder_layers': 1, 'decoder_dropout': 0.0, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 20, 'batch_size': 32, 'sequence_length': 24}
Time: 123.44 minutes - estimated total time: 177.53 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 2.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 168.606
  Epoch 2/60
Model trained in 2.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 152.946
  Epoch 3/60
Model trained in 2.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 140.795
  Epoch 4/60
Model trained in 2.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 130.338
  Epoch 5/60
Model trained in 2.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 120.938
  Epoch 6/60
Model trained in 2.67s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 112.921
  Epoch 7/60
Model trained in 2.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 105.813
  Epoch 8/60
Model trained in 2.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 100.083
  Epoch 9/60
Model trained in 2.65s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 95.120
  Epoch 10/60
Model trained in 2.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.336
  Epoch 11/60
Model trained in 2.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.720
  Epoch 12/60
Model trained in 2.63s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.868
  Epoch 13/60
Model trained in 2.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.612
  Epoch 14/60
Model trained in 2.61s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.137
  Epoch 15/60
Model trained in 2.65s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.457
  Epoch 16/60
Model trained in 2.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.680
  Epoch 17/60
Model trained in 2.68s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.490
  Epoch 18/60
Model trained in 2.68s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.337
  Epoch 19/60
Model trained in 2.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.800
  Epoch 20/60
Model trained in 2.62s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.462
  Epoch 21/60
Model trained in 2.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.637
  Epoch 22/60
Model trained in 2.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.740
  Epoch 23/60
Model trained in 2.67s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.375
  Epoch 24/60
Model trained in 2.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.112
  Epoch 25/60
Model trained in 2.68s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 100.518
  Epoch 26/60
Model trained in 2.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 102.056
  Epoch 27/60
Model trained in 2.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 98.979
  Epoch 28/60
Model trained in 2.67s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 103.840
  Epoch 29/60
Model trained in 2.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 101.447
  Epoch 30/60
Model trained in 2.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 103.080
  Epoch 31/60
Model trained in 2.68s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 102.064
  Epoch 32/60
Model trained in 2.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 98.232
  Epoch 33/60
Model trained in 2.43s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 94.672
  Epoch 34/60
Model trained in 2.54s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.517
  Epoch 35/60
Model trained in 2.51s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.825
  Epoch 36/60
Model trained in 2.54s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.105
  Early stopping triggered.

  best_val_SMAPE=84.680

Combination 802/1152: {'encoder_hidden_size': 48, 'encoder_layers': 1, 'encoder_dropout': 0.0, 'decoder_hidden_size': 33, 'decoder_layers': 1, 'decoder_dropout': 0.0, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 20, 'batch_size': 32, 'sequence_length': 168}
Time: 125.38 minutes - estimated total time: 180.10 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 2.58s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 168.693
  Epoch 2/60
Model trained in 2.62s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 153.134
  Epoch 3/60
Model trained in 2.62s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 140.965
  Epoch 4/60
Model trained in 2.59s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 130.438
  Epoch 5/60
Model trained in 2.57s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 121.265
  Epoch 6/60
Model trained in 2.68s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 113.062
  Epoch 7/60
Model trained in 2.59s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 105.930
  Epoch 8/60
Model trained in 2.67s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 99.862
  Epoch 9/60
Model trained in 2.58s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 94.617
  Epoch 10/60
Model trained in 2.54s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.188
  Epoch 11/60
Model trained in 2.61s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.199
  Epoch 12/60
Model trained in 2.52s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.748
  Epoch 13/60
Model trained in 2.48s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.281
  Epoch 14/60
Model trained in 2.56s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.383
  Epoch 15/60
Model trained in 2.56s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.499
  Epoch 16/60
Model trained in 2.61s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.440
  Epoch 17/60
Model trained in 2.61s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.769
  Epoch 18/60
Model trained in 2.61s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.006
  Epoch 19/60
Model trained in 2.63s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.482
  Epoch 20/60
Model trained in 2.51s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.161
  Epoch 21/60
Model trained in 2.46s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.791
  Epoch 22/60
Model trained in 2.56s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.545
  Epoch 23/60
Model trained in 2.56s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.859
  Epoch 24/60
Model trained in 2.57s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.817
  Epoch 25/60
Model trained in 2.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.782
  Epoch 26/60
Model trained in 2.50s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.212
  Epoch 27/60
Model trained in 2.59s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.310
  Epoch 28/60
Model trained in 2.61s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.415
  Epoch 29/60
Model trained in 2.58s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.595
  Epoch 30/60
Model trained in 2.62s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.522
  Epoch 31/60
Model trained in 2.60s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.101
  Epoch 32/60
Model trained in 2.60s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.311
  Epoch 33/60
Model trained in 2.53s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.799
  Epoch 34/60
Model trained in 2.57s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.340
  Epoch 35/60
Model trained in 2.52s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.291
  Epoch 36/60
Model trained in 2.62s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.267
  Epoch 37/60
Model trained in 2.62s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.679
  Epoch 38/60
Model trained in 2.45s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.904
  Epoch 39/60
Model trained in 2.57s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.599
  Epoch 40/60
Model trained in 2.61s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.723
  Epoch 41/60
Model trained in 2.59s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.811
  Epoch 42/60
Model trained in 2.60s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.847
  Epoch 43/60
Model trained in 2.61s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.995
  Epoch 44/60
Model trained in 2.54s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.050
  Epoch 45/60
Model trained in 2.52s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.873
  Epoch 46/60
Model trained in 2.51s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.438
  Epoch 47/60
Model trained in 2.59s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.039
  Epoch 48/60
Model trained in 2.58s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.899
  Epoch 49/60
Model trained in 2.51s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.750
  Epoch 50/60
Model trained in 2.56s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.170
  Epoch 51/60
Model trained in 2.48s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.740
  Epoch 52/60
Model trained in 2.43s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.068
  Epoch 53/60
Model trained in 2.51s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.385
  Epoch 54/60
Model trained in 2.49s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.627
  Early stopping triggered.

  best_val_SMAPE=79.340

Combination 803/1152: {'encoder_hidden_size': 48, 'encoder_layers': 1, 'encoder_dropout': 0.0, 'decoder_hidden_size': 33, 'decoder_layers': 1, 'decoder_dropout': 0.0, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 20, 'batch_size': 64, 'sequence_length': 24}
Time: 128.12 minutes - estimated total time: 183.80 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 1.68s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 178.515
  Epoch 2/60
Model trained in 1.68s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 168.424
  Epoch 3/60
Model trained in 1.57s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 159.994
  Epoch 4/60
Model trained in 1.58s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 152.746
  Epoch 5/60
Model trained in 1.46s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 146.413
  Epoch 6/60
Model trained in 1.52s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 140.565
  Epoch 7/60
Model trained in 1.57s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 135.076
  Epoch 8/60
Model trained in 1.57s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 129.964
  Epoch 9/60
Model trained in 1.57s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 125.143
  Epoch 10/60
Model trained in 1.45s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 120.847
  Epoch 11/60
Model trained in 1.50s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 116.545
  Epoch 12/60
Model trained in 1.47s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 112.606
  Epoch 13/60
Model trained in 1.50s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 108.891
  Epoch 14/60
Model trained in 1.55s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 105.577
  Epoch 15/60
Model trained in 1.51s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 102.148
  Epoch 16/60
Model trained in 1.59s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 99.397
  Epoch 17/60
Model trained in 1.46s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 96.668
  Epoch 18/60
Model trained in 1.53s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.904
  Epoch 19/60
Model trained in 1.53s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.833
  Epoch 20/60
Model trained in 1.48s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.801
  Epoch 21/60
Model trained in 1.49s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.601
  Epoch 22/60
Model trained in 1.47s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.509
  Epoch 23/60
Model trained in 1.49s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.324
  Epoch 24/60
Model trained in 1.42s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.830
  Epoch 25/60
Model trained in 1.47s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.961
  Epoch 26/60
Model trained in 1.55s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.662
  Epoch 27/60
Model trained in 1.53s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.487
  Epoch 28/60
Model trained in 1.51s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.654
  Epoch 29/60
Model trained in 1.50s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.171
  Epoch 30/60
Model trained in 1.58s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.656
  Epoch 31/60
Model trained in 1.54s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.485
  Epoch 32/60
Model trained in 1.60s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.928
  Epoch 33/60
Model trained in 1.57s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.284
  Epoch 34/60
Model trained in 1.54s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.535
  Epoch 35/60
Model trained in 1.63s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.737
  Epoch 36/60
Model trained in 1.55s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.489
  Epoch 37/60
Model trained in 1.44s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.415
  Epoch 38/60
Model trained in 1.46s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.077
  Epoch 39/60
Model trained in 1.47s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.541
  Epoch 40/60
Model trained in 1.50s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.778
  Epoch 41/60
Model trained in 1.47s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.855
  Epoch 42/60
Model trained in 1.49s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.261
  Epoch 43/60
Model trained in 1.44s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.867
  Epoch 44/60
Model trained in 1.50s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.006
  Epoch 45/60
Model trained in 1.44s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.298
  Epoch 46/60
Model trained in 1.48s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.063
  Epoch 47/60
Model trained in 1.51s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.819
  Epoch 48/60
Model trained in 1.47s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.110
  Epoch 49/60
Model trained in 1.47s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.617
  Epoch 50/60
Model trained in 1.50s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.704
  Epoch 51/60
Model trained in 1.44s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.558
  Epoch 52/60
Model trained in 1.53s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.455
  Epoch 53/60
Model trained in 1.55s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.345
  Early stopping triggered.

  best_val_SMAPE=76.284

Combination 804/1152: {'encoder_hidden_size': 48, 'encoder_layers': 1, 'encoder_dropout': 0.0, 'decoder_hidden_size': 33, 'decoder_layers': 1, 'decoder_dropout': 0.0, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 20, 'batch_size': 64, 'sequence_length': 168}
Time: 129.88 minutes - estimated total time: 186.09 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 1.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 178.624
  Epoch 2/60
Model trained in 1.65s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 168.584
  Epoch 3/60
Model trained in 1.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 160.196
  Epoch 4/60
Model trained in 1.56s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 153.046
  Epoch 5/60
Model trained in 1.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 146.623
  Epoch 6/60
Model trained in 1.59s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 140.821
  Epoch 7/60
Model trained in 1.63s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 135.389
  Epoch 8/60
Model trained in 1.67s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 130.297
  Epoch 9/60
Model trained in 1.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 125.521
  Epoch 10/60
Model trained in 1.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 121.346
  Epoch 11/60
Model trained in 1.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 117.208
  Epoch 12/60
Model trained in 1.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 113.047
  Epoch 13/60
Model trained in 1.63s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 109.411
  Epoch 14/60
Model trained in 1.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 105.960
  Epoch 15/60
Model trained in 2.15s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 102.672
  Epoch 16/60
Model trained in 1.63s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 99.838
  Epoch 17/60
Model trained in 1.53s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 96.740
  Epoch 18/60
Model trained in 1.58s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 94.066
  Epoch 19/60
Model trained in 1.60s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.755
  Epoch 20/60
Model trained in 1.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.695
  Epoch 21/60
Model trained in 1.67s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.655
  Epoch 22/60
Model trained in 1.65s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.635
  Epoch 23/60
Model trained in 1.58s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.650
  Epoch 24/60
Model trained in 1.68s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.421
  Epoch 25/60
Model trained in 1.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.002
  Epoch 26/60
Model trained in 1.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.454
  Epoch 27/60
Model trained in 1.60s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.702
  Epoch 28/60
Model trained in 1.53s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.440
  Epoch 29/60
Model trained in 1.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.409
  Epoch 30/60
Model trained in 1.58s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.412
  Epoch 31/60
Model trained in 1.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.322
  Epoch 32/60
Model trained in 1.55s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.508
  Epoch 33/60
Model trained in 1.57s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.750
  Epoch 34/60
Model trained in 1.58s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.995
  Epoch 35/60
Model trained in 1.56s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.310
  Epoch 36/60
Model trained in 1.54s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.493
  Epoch 37/60
Model trained in 1.61s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.645
  Epoch 38/60
Model trained in 1.57s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.417
  Epoch 39/60
Model trained in 1.57s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.823
  Epoch 40/60
Model trained in 1.55s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.114
  Epoch 41/60
Model trained in 1.67s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.202
  Epoch 42/60
Model trained in 1.62s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.335
  Epoch 43/60
Model trained in 1.58s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.078
  Epoch 44/60
Model trained in 1.59s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.222
  Epoch 45/60
Model trained in 1.54s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.030
  Epoch 46/60
Model trained in 1.58s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.276
  Epoch 47/60
Model trained in 1.52s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.943
  Epoch 48/60
Model trained in 1.65s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.405
  Epoch 49/60
Model trained in 1.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.316
  Epoch 50/60
Model trained in 1.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.140
  Epoch 51/60
Model trained in 1.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.951
  Early stopping triggered.

  best_val_SMAPE=80.322

Combination 805/1152: {'encoder_hidden_size': 48, 'encoder_layers': 1, 'encoder_dropout': 0.0, 'decoder_hidden_size': 33, 'decoder_layers': 1, 'decoder_dropout': 0.0, 'learning_rate': 0.0005, 'max_epochs': 60, 'patience': 20, 'batch_size': 32, 'sequence_length': 24}
Time: 131.68 minutes - estimated total time: 188.44 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 2.47s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 178.603
  Epoch 2/60
Model trained in 2.63s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 168.650
  Epoch 3/60
Model trained in 2.58s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 160.292
  Epoch 4/60
Model trained in 2.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 153.069
  Epoch 5/60
Model trained in 2.63s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 146.599
  Epoch 6/60
Model trained in 2.59s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 140.654
  Epoch 7/60
Model trained in 2.48s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 135.317
  Epoch 8/60
Model trained in 2.47s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 130.461
  Epoch 9/60
Model trained in 2.53s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 125.754
  Epoch 10/60
Model trained in 2.55s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 121.077
  Epoch 11/60
Model trained in 2.62s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 116.785
  Epoch 12/60
Model trained in 2.50s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 112.897
  Epoch 13/60
Model trained in 2.46s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 109.306
  Epoch 14/60
Model trained in 2.59s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 106.182
  Epoch 15/60
Model trained in 2.37s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 103.483
  Epoch 16/60
Model trained in 2.49s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 100.747
  Epoch 17/60
Model trained in 2.46s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 98.455
  Epoch 18/60
Model trained in 2.40s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 96.404
  Epoch 19/60
Model trained in 2.41s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 94.700
  Epoch 20/60
Model trained in 2.40s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 94.918
  Epoch 21/60
Model trained in 2.40s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.955
  Epoch 22/60
Model trained in 2.37s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.203
  Epoch 23/60
Model trained in 2.43s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.207
  Epoch 24/60
Model trained in 2.48s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.434
  Epoch 25/60
Model trained in 2.34s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.106
  Epoch 26/60
Model trained in 2.48s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.546
  Epoch 27/60
Model trained in 2.54s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.482
  Epoch 28/60
Model trained in 2.43s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.186
  Epoch 29/60
Model trained in 2.41s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.721
  Epoch 30/60
Model trained in 2.49s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.017
  Epoch 31/60
Model trained in 2.42s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.873
  Epoch 32/60
Model trained in 2.47s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.943
  Epoch 33/60
Model trained in 2.40s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.899
  Epoch 34/60
Model trained in 2.41s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.627
  Epoch 35/60
Model trained in 2.60s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.552
  Epoch 36/60
Model trained in 2.52s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.946
  Epoch 37/60
Model trained in 2.56s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.100
  Epoch 38/60
Model trained in 2.60s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.783
  Epoch 39/60
Model trained in 2.49s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.585
  Epoch 40/60
Model trained in 2.36s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.540
  Epoch 41/60
Model trained in 2.41s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.751
  Epoch 42/60
Model trained in 2.54s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.573
  Epoch 43/60
Model trained in 2.65s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.840
  Epoch 44/60
Model trained in 2.44s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.524
  Epoch 45/60
Model trained in 2.46s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.669
  Epoch 46/60
Model trained in 2.47s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.557
  Epoch 47/60
Model trained in 2.67s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.405
  Epoch 48/60
Model trained in 2.48s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.294
  Epoch 49/60
Model trained in 2.52s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.339
  Epoch 50/60
Model trained in 2.48s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.207
  Epoch 51/60
Model trained in 2.57s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.874
  Epoch 52/60
Model trained in 2.62s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.537
  Epoch 53/60
Model trained in 2.58s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.694
  Epoch 54/60
Model trained in 2.61s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.373
  Epoch 55/60
Model trained in 2.54s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.576
  Epoch 56/60
Model trained in 2.51s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.025
  Epoch 57/60
Model trained in 2.62s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.347
  Epoch 58/60
Model trained in 2.58s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.024
  Epoch 59/60
Model trained in 2.55s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.958
  Early stopping triggered.

  best_val_SMAPE=81.585

Combination 806/1152: {'encoder_hidden_size': 48, 'encoder_layers': 1, 'encoder_dropout': 0.0, 'decoder_hidden_size': 33, 'decoder_layers': 1, 'decoder_dropout': 0.0, 'learning_rate': 0.0005, 'max_epochs': 60, 'patience': 20, 'batch_size': 32, 'sequence_length': 168}
Time: 134.62 minutes - estimated total time: 192.40 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 2.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 178.660
  Epoch 2/60
Model trained in 2.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 168.792
  Epoch 3/60
Model trained in 2.68s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 160.498
  Epoch 4/60
Model trained in 2.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 153.326
  Epoch 5/60
Model trained in 2.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 146.970
  Epoch 6/60
Model trained in 2.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 141.222
  Epoch 7/60
Model trained in 2.67s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 135.876
  Epoch 8/60
Model trained in 2.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 130.644
  Epoch 9/60
Model trained in 2.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 125.904
  Epoch 10/60
Model trained in 2.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 121.387
  Epoch 11/60
Model trained in 2.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 117.320
  Epoch 12/60
Model trained in 2.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 113.398
  Epoch 13/60
Model trained in 2.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 109.464
  Epoch 14/60
Model trained in 2.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 106.168
  Epoch 15/60
Model trained in 2.68s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 103.082
  Epoch 16/60
Model trained in 2.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 100.066
  Epoch 17/60
Model trained in 2.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 97.628
  Epoch 18/60
Model trained in 2.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 95.229
  Epoch 19/60
Model trained in 2.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.979
  Epoch 20/60
Model trained in 2.67s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.474
  Epoch 21/60
Model trained in 2.47s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.141
  Epoch 22/60
Model trained in 2.62s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.756
  Epoch 23/60
Model trained in 2.43s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.490
  Epoch 24/60
Model trained in 2.48s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.852
  Epoch 25/60
Model trained in 2.45s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.722
  Epoch 26/60
Model trained in 2.41s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.884
  Epoch 27/60
Model trained in 2.45s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.843
  Epoch 28/60
Model trained in 2.48s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.747
  Epoch 29/60
Model trained in 2.46s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.174
  Epoch 30/60
Model trained in 2.44s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.401
  Epoch 31/60
Model trained in 2.54s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.627
  Epoch 32/60
Model trained in 2.47s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.539
  Epoch 33/60
Model trained in 2.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.665
  Epoch 34/60
Model trained in 2.58s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.877
  Epoch 35/60
Model trained in 2.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.070
  Epoch 36/60
Model trained in 2.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.189
  Epoch 37/60
Model trained in 2.61s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.546
  Epoch 38/60
Model trained in 2.45s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.995
  Epoch 39/60
Model trained in 2.50s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.537
  Epoch 40/60
Model trained in 2.45s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.490
  Epoch 41/60
Model trained in 2.51s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.827
  Epoch 42/60
Model trained in 2.63s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.116
  Epoch 43/60
Model trained in 2.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.010
  Epoch 44/60
Model trained in 2.47s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.515
  Epoch 45/60
Model trained in 2.44s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.485
  Epoch 46/60
Model trained in 2.46s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.355
  Epoch 47/60
Model trained in 2.52s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.886
  Epoch 48/60
Model trained in 2.51s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.732
  Epoch 49/60
Model trained in 2.38s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.915
  Epoch 50/60
Model trained in 2.51s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.219
  Early stopping triggered.

  best_val_SMAPE=80.401

Combination 807/1152: {'encoder_hidden_size': 48, 'encoder_layers': 1, 'encoder_dropout': 0.0, 'decoder_hidden_size': 33, 'decoder_layers': 1, 'decoder_dropout': 0.0, 'learning_rate': 0.0005, 'max_epochs': 60, 'patience': 20, 'batch_size': 64, 'sequence_length': 24}
Time: 137.19 minutes - estimated total time: 195.84 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 1.65s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 185.210
  Epoch 2/60
Model trained in 1.60s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 178.502
  Epoch 3/60
Model trained in 1.65s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 173.250
  Epoch 4/60
Model trained in 1.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 168.564
  Epoch 5/60
Model trained in 1.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 164.234
  Epoch 6/60
Model trained in 1.62s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 160.193
  Epoch 7/60
Model trained in 1.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 156.499
  Epoch 8/60
Model trained in 1.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 153.016
  Epoch 9/60
Model trained in 1.63s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 149.705
  Epoch 10/60
Model trained in 1.62s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 146.593
  Epoch 11/60
Model trained in 1.53s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 143.608
  Epoch 12/60
Model trained in 1.57s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 140.748
  Epoch 13/60
Model trained in 1.56s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 138.019
  Epoch 14/60
Model trained in 1.58s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 135.364
  Epoch 15/60
Model trained in 1.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 132.746
  Epoch 16/60
Model trained in 1.68s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 130.215
  Epoch 17/60
Model trained in 1.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 127.822
  Epoch 18/60
Model trained in 1.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 125.360
  Epoch 19/60
Model trained in 1.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 122.941
  Epoch 20/60
Model trained in 1.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 120.708
  Epoch 21/60
Model trained in 1.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 118.554
  Epoch 22/60
Model trained in 1.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 116.433
  Epoch 23/60
Model trained in 1.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 114.447
  Epoch 24/60
Model trained in 1.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 112.527
  Epoch 25/60
Model trained in 1.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 110.668
  Epoch 26/60
Model trained in 1.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 108.808
  Epoch 27/60
Model trained in 1.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 106.980
  Epoch 28/60
Model trained in 1.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 105.478
  Epoch 29/60
Model trained in 1.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 103.823
  Epoch 30/60
Model trained in 1.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 102.247
  Epoch 31/60
Model trained in 1.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 100.905
  Epoch 32/60
Model trained in 1.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 99.334
  Epoch 33/60
Model trained in 1.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 97.996
  Epoch 34/60
Model trained in 1.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 96.599
  Epoch 35/60
Model trained in 1.67s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 95.299
  Epoch 36/60
Model trained in 1.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 94.076
  Epoch 37/60
Model trained in 1.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.619
  Epoch 38/60
Model trained in 1.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.392
  Epoch 39/60
Model trained in 1.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.882
  Epoch 40/60
Model trained in 1.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.418
  Epoch 41/60
Model trained in 1.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.454
  Epoch 42/60
Model trained in 1.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.805
  Epoch 43/60
Model trained in 1.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.677
  Epoch 44/60
Model trained in 1.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.995
  Epoch 45/60
Model trained in 1.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.988
  Epoch 46/60
Model trained in 1.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.914
  Epoch 47/60
Model trained in 1.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.291
  Epoch 48/60
Model trained in 1.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.283
  Epoch 49/60
Model trained in 1.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.533
  Epoch 50/60
Model trained in 1.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.933
  Epoch 51/60
Model trained in 1.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.263
  Epoch 52/60
Model trained in 1.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.615
  Epoch 53/60
Model trained in 1.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.222
  Epoch 54/60
Model trained in 1.67s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.627
  Epoch 55/60
Model trained in 1.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.441
  Epoch 56/60
Model trained in 1.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.059
  Epoch 57/60
Model trained in 1.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.165
  Epoch 58/60
Model trained in 1.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.906
  Epoch 59/60
Model trained in 1.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.376
  Epoch 60/60
Model trained in 1.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.020

  best_val_SMAPE=77.906

Combination 808/1152: {'encoder_hidden_size': 48, 'encoder_layers': 1, 'encoder_dropout': 0.0, 'decoder_hidden_size': 33, 'decoder_layers': 1, 'decoder_dropout': 0.0, 'learning_rate': 0.0005, 'max_epochs': 60, 'patience': 20, 'batch_size': 64, 'sequence_length': 168}
Time: 139.39 minutes - estimated total time: 198.73 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 1.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 185.299
  Epoch 2/60
Model trained in 1.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 178.608
  Epoch 3/60
Model trained in 1.95s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 173.383
  Epoch 4/60
Model trained in 1.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 168.722
  Epoch 5/60
Model trained in 1.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 164.410
  Epoch 6/60
Model trained in 1.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 160.405
  Epoch 7/60
Model trained in 1.98s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 156.722
  Epoch 8/60
Model trained in 2.01s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 153.217
  Epoch 9/60
Model trained in 1.99s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 149.952
  Epoch 10/60
Model trained in 1.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 146.856
  Epoch 11/60
Model trained in 1.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 143.882
  Epoch 12/60
Model trained in 1.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 140.995
  Epoch 13/60
Model trained in 1.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 138.207
  Epoch 14/60
Model trained in 1.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 135.517
  Epoch 15/60
Model trained in 1.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 132.953
  Epoch 16/60
Model trained in 1.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 130.522
  Epoch 17/60
Model trained in 1.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 127.881
  Epoch 18/60
Model trained in 1.97s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 125.529
  Epoch 19/60
Model trained in 1.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 123.191
  Epoch 20/60
Model trained in 1.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 120.912
  Epoch 21/60
Model trained in 1.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 119.020
  Epoch 22/60
Model trained in 1.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 116.706
  Epoch 23/60
Model trained in 1.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 114.566
  Epoch 24/60
Model trained in 1.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 112.552
  Epoch 25/60
Model trained in 1.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 110.737
  Epoch 26/60
Model trained in 1.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 108.790
  Epoch 27/60
Model trained in 1.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 107.128
  Epoch 28/60
Model trained in 1.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 105.472
  Epoch 29/60
Model trained in 1.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 103.748
  Epoch 30/60
Model trained in 1.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 102.028
  Epoch 31/60
Model trained in 1.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 100.450
  Epoch 32/60
Model trained in 1.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 99.273
  Epoch 33/60
Model trained in 1.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 97.792
  Epoch 34/60
Model trained in 1.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 96.589
  Epoch 35/60
Model trained in 1.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 95.152
  Epoch 36/60
Model trained in 1.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 94.012
  Epoch 37/60
Model trained in 1.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.773
  Epoch 38/60
Model trained in 1.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.653
  Epoch 39/60
Model trained in 1.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.827
  Epoch 40/60
Model trained in 1.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.631
  Epoch 41/60
Model trained in 1.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.576
  Epoch 42/60
Model trained in 1.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.523
  Epoch 43/60
Model trained in 1.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.746
  Epoch 44/60
Model trained in 1.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.957
  Epoch 45/60
Model trained in 1.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.061
  Epoch 46/60
Model trained in 1.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.752
  Epoch 47/60
Model trained in 1.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.863
  Epoch 48/60
Model trained in 1.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.168
  Epoch 49/60
Model trained in 1.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.608
  Epoch 50/60
Model trained in 1.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.042
  Epoch 51/60
Model trained in 1.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.574
  Epoch 52/60
Model trained in 1.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.207
  Epoch 53/60
Model trained in 1.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.686
  Epoch 54/60
Model trained in 1.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.326
  Epoch 55/60
Model trained in 1.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.088
  Epoch 56/60
Model trained in 1.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.417
  Epoch 57/60
Model trained in 1.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.228
  Epoch 58/60
Model trained in 1.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.580
  Epoch 59/60
Model trained in 1.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.571
  Epoch 60/60
Model trained in 1.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.320

  best_val_SMAPE=80.088

Combination 817/1152: {'encoder_hidden_size': 48, 'encoder_layers': 1, 'encoder_dropout': 0.0, 'decoder_hidden_size': 33, 'decoder_layers': 2, 'decoder_dropout': 0.0, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 20, 'batch_size': 32, 'sequence_length': 24}
Time: 141.70 minutes - estimated total time: 199.80 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 3.01s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 169.258
  Epoch 2/60
Model trained in 2.97s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 153.498
  Epoch 3/60
Model trained in 3.01s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 141.019
  Epoch 4/60
Model trained in 2.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 130.259
  Epoch 5/60
Model trained in 2.95s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 120.574
  Epoch 6/60
Model trained in 2.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 114.434
  Epoch 7/60
Model trained in 2.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 107.442
  Epoch 8/60
Model trained in 2.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 102.082
  Epoch 9/60
Model trained in 2.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 95.927
  Epoch 10/60
Model trained in 2.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.518
  Epoch 11/60
Model trained in 2.97s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.369
  Epoch 12/60
Model trained in 2.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.887
  Epoch 13/60
Model trained in 3.12s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.441
  Epoch 14/60
Model trained in 3.11s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.194
  Epoch 15/60
Model trained in 2.98s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.732
  Epoch 16/60
Model trained in 2.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.891
  Epoch 17/60
Model trained in 2.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.282
  Epoch 18/60
Model trained in 2.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.008
  Epoch 19/60
Model trained in 3.03s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.728
  Epoch 20/60
Model trained in 2.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.429
  Epoch 21/60
Model trained in 2.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.113
  Epoch 22/60
Model trained in 2.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.542
  Epoch 23/60
Model trained in 3.01s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.354
  Epoch 24/60
Model trained in 3.08s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.265
  Epoch 25/60
Model trained in 3.10s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.655
  Epoch 26/60
Model trained in 3.04s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.663
  Epoch 27/60
Model trained in 2.97s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.979
  Epoch 28/60
Model trained in 3.07s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.107
  Epoch 29/60
Model trained in 2.98s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.399
  Epoch 30/60
Model trained in 2.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.243
  Epoch 31/60
Model trained in 2.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.156
  Epoch 32/60
Model trained in 2.95s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.460
  Epoch 33/60
Model trained in 3.02s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.240
  Epoch 34/60
Model trained in 2.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.707
  Epoch 35/60
Model trained in 2.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.543
  Early stopping triggered.

  best_val_SMAPE=81.732

Combination 818/1152: {'encoder_hidden_size': 48, 'encoder_layers': 1, 'encoder_dropout': 0.0, 'decoder_hidden_size': 33, 'decoder_layers': 2, 'decoder_dropout': 0.0, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 20, 'batch_size': 32, 'sequence_length': 168}
Time: 143.72 minutes - estimated total time: 202.40 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 3.08s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 169.404
  Epoch 2/60
Model trained in 3.13s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 153.666
  Epoch 3/60
Model trained in 3.12s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 141.223
  Epoch 4/60
Model trained in 3.08s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 130.487
  Epoch 5/60
Model trained in 3.11s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 121.673
  Epoch 6/60
Model trained in 3.14s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 113.093
  Epoch 7/60
Model trained in 3.06s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 105.646
  Epoch 8/60
Model trained in 2.99s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 98.863
  Epoch 9/60
Model trained in 3.12s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.252
  Epoch 10/60
Model trained in 3.24s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.499
  Epoch 11/60
Model trained in 3.03s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.577
  Epoch 12/60
Model trained in 3.00s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.170
  Epoch 13/60
Model trained in 2.99s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.234
  Epoch 14/60
Model trained in 3.10s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.343
  Epoch 15/60
Model trained in 3.12s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.498
  Epoch 16/60
Model trained in 3.16s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.424
  Epoch 17/60
Model trained in 3.11s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.217
  Epoch 18/60
Model trained in 3.17s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.178
  Epoch 19/60
Model trained in 3.21s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.262
  Epoch 20/60
Model trained in 3.04s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.203
  Epoch 21/60
Model trained in 3.05s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.919
  Epoch 22/60
Model trained in 3.10s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.344
  Epoch 23/60
Model trained in 3.08s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.256
  Epoch 24/60
Model trained in 3.00s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.749
  Epoch 25/60
Model trained in 3.00s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.643
  Epoch 26/60
Model trained in 3.17s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.119
  Epoch 27/60
Model trained in 3.12s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.966
  Epoch 28/60
Model trained in 3.24s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.226
  Epoch 29/60
Model trained in 3.09s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.938
  Epoch 30/60
Model trained in 3.21s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.183
  Epoch 31/60
Model trained in 3.11s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.159
  Epoch 32/60
Model trained in 3.27s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.019
  Epoch 33/60
Model trained in 2.98s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.512
  Epoch 34/60
Model trained in 3.10s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.104
  Epoch 35/60
Model trained in 3.05s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.001
  Epoch 36/60
Model trained in 3.02s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.402
  Epoch 37/60
Model trained in 3.20s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.851
  Epoch 38/60
Model trained in 2.95s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.931
  Early stopping triggered.

  best_val_SMAPE=73.178

Combination 819/1152: {'encoder_hidden_size': 48, 'encoder_layers': 1, 'encoder_dropout': 0.0, 'decoder_hidden_size': 33, 'decoder_layers': 2, 'decoder_dropout': 0.0, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 20, 'batch_size': 64, 'sequence_length': 24}
Time: 146.01 minutes - estimated total time: 205.38 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 1.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 179.251
  Epoch 2/60
Model trained in 1.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 169.126
  Epoch 3/60
Model trained in 1.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 160.642
  Epoch 4/60
Model trained in 1.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 153.322
  Epoch 5/60
Model trained in 1.68s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 146.789
  Epoch 6/60
Model trained in 1.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 140.808
  Epoch 7/60
Model trained in 1.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 135.271
  Epoch 8/60
Model trained in 1.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 130.209
  Epoch 9/60
Model trained in 1.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 125.148
  Epoch 10/60
Model trained in 1.68s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 120.374
  Epoch 11/60
Model trained in 1.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 116.875
  Epoch 12/60
Model trained in 1.67s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 113.596
  Epoch 13/60
Model trained in 1.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 109.966
  Epoch 14/60
Model trained in 1.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 106.779
  Epoch 15/60
Model trained in 1.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 103.337
  Epoch 16/60
Model trained in 1.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 100.032
  Epoch 17/60
Model trained in 1.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 96.744
  Epoch 18/60
Model trained in 1.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.780
  Epoch 19/60
Model trained in 1.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.458
  Epoch 20/60
Model trained in 1.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.234
  Epoch 21/60
Model trained in 1.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.282
  Epoch 22/60
Model trained in 1.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.303
  Epoch 23/60
Model trained in 1.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.598
  Epoch 24/60
Model trained in 1.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.885
  Epoch 25/60
Model trained in 1.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.776
  Epoch 26/60
Model trained in 1.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.105
  Epoch 27/60
Model trained in 1.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.393
  Epoch 28/60
Model trained in 1.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.522
  Epoch 29/60
Model trained in 1.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.120
  Epoch 30/60
Model trained in 1.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.914
  Epoch 31/60
Model trained in 1.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.443
  Epoch 32/60
Model trained in 1.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.757
  Epoch 33/60
Model trained in 1.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.303
  Epoch 34/60
Model trained in 1.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.482
  Epoch 35/60
Model trained in 1.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.500
  Epoch 36/60
Model trained in 1.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.754
  Epoch 37/60
Model trained in 1.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.235
  Epoch 38/60
Model trained in 1.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.246
  Epoch 39/60
Model trained in 1.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.390
  Epoch 40/60
Model trained in 1.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.021
  Epoch 41/60
Model trained in 1.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.384
  Epoch 42/60
Model trained in 1.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.373
  Epoch 43/60
Model trained in 1.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.114
  Epoch 44/60
Model trained in 1.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.117
  Epoch 45/60
Model trained in 1.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.646
  Epoch 46/60
Model trained in 1.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.826
  Epoch 47/60
Model trained in 1.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.816
  Epoch 48/60
Model trained in 1.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.736
  Epoch 49/60
Model trained in 1.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.391
  Epoch 50/60
Model trained in 1.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.482
  Epoch 51/60
Model trained in 1.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.555
  Early stopping triggered.

  best_val_SMAPE=76.443

Combination 820/1152: {'encoder_hidden_size': 48, 'encoder_layers': 1, 'encoder_dropout': 0.0, 'decoder_hidden_size': 33, 'decoder_layers': 2, 'decoder_dropout': 0.0, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 20, 'batch_size': 64, 'sequence_length': 168}
Time: 147.96 minutes - estimated total time: 207.86 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 1.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 179.313
  Epoch 2/60
Model trained in 2.03s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 169.224
  Epoch 3/60
Model trained in 2.21s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 160.782
  Epoch 4/60
Model trained in 1.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 153.490
  Epoch 5/60
Model trained in 1.97s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 146.984
  Epoch 6/60
Model trained in 1.98s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 140.985
  Epoch 7/60
Model trained in 1.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 135.468
  Epoch 8/60
Model trained in 1.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 130.316
  Epoch 9/60
Model trained in 1.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 126.939
  Epoch 10/60
Model trained in 1.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 122.910
  Epoch 11/60
Model trained in 1.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 118.890
  Epoch 12/60
Model trained in 2.07s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 114.277
  Epoch 13/60
Model trained in 1.97s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 110.544
  Epoch 14/60
Model trained in 1.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 107.092
  Epoch 15/60
Model trained in 1.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 103.677
  Epoch 16/60
Model trained in 2.14s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 100.477
  Epoch 17/60
Model trained in 1.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 97.770
  Epoch 18/60
Model trained in 1.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 94.842
  Epoch 19/60
Model trained in 1.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.866
  Epoch 20/60
Model trained in 1.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.834
  Epoch 21/60
Model trained in 1.99s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.808
  Epoch 22/60
Model trained in 1.99s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.746
  Epoch 23/60
Model trained in 2.01s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.162
  Epoch 24/60
Model trained in 1.99s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.958
  Epoch 25/60
Model trained in 2.02s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.869
  Epoch 26/60
Model trained in 1.95s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.620
  Epoch 27/60
Model trained in 1.98s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.700
  Epoch 28/60
Model trained in 1.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.996
  Epoch 29/60
Model trained in 1.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.550
  Epoch 30/60
Model trained in 1.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.703
  Epoch 31/60
Model trained in 1.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.734
  Epoch 32/60
Model trained in 1.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.708
  Epoch 33/60
Model trained in 1.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.688
  Epoch 34/60
Model trained in 1.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.722
  Epoch 35/60
Model trained in 1.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.498
  Epoch 36/60
Model trained in 1.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.659
  Epoch 37/60
Model trained in 1.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.275
  Epoch 38/60
Model trained in 1.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.207
  Epoch 39/60
Model trained in 1.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.609
  Epoch 40/60
Model trained in 1.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.424
  Epoch 41/60
Model trained in 1.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.591
  Epoch 42/60
Model trained in 1.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.853
  Epoch 43/60
Model trained in 1.98s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.623
  Epoch 44/60
Model trained in 2.05s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.487
  Epoch 45/60
Model trained in 1.98s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.536
  Epoch 46/60
Model trained in 1.99s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.898
  Epoch 47/60
Model trained in 2.02s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.679
  Epoch 48/60
Model trained in 2.07s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.447
  Epoch 49/60
Model trained in 2.01s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.205
  Epoch 50/60
Model trained in 1.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.079
  Epoch 51/60
Model trained in 1.95s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.743
  Epoch 52/60
Model trained in 1.99s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.751
  Epoch 53/60
Model trained in 1.95s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.789
  Epoch 54/60
Model trained in 1.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.886
  Epoch 55/60
Model trained in 1.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.738
  Epoch 56/60
Model trained in 1.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.191
  Epoch 57/60
Model trained in 1.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.411
  Epoch 58/60
Model trained in 2.05s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.630
  Epoch 59/60
Model trained in 1.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.877
  Epoch 60/60
Model trained in 1.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.056

  best_val_SMAPE=77.447

Combination 821/1152: {'encoder_hidden_size': 48, 'encoder_layers': 1, 'encoder_dropout': 0.0, 'decoder_hidden_size': 33, 'decoder_layers': 2, 'decoder_dropout': 0.0, 'learning_rate': 0.0005, 'max_epochs': 60, 'patience': 20, 'batch_size': 32, 'sequence_length': 24}
Time: 150.38 minutes - estimated total time: 211.01 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 2.97s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 179.166
  Epoch 2/60
Model trained in 2.99s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 169.283
  Epoch 3/60
Model trained in 3.10s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 160.898
  Epoch 4/60
Model trained in 2.97s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 153.613
  Epoch 5/60
Model trained in 3.00s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 147.094
  Epoch 6/60
Model trained in 2.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 141.097
  Epoch 7/60
Model trained in 2.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 135.545
  Epoch 8/60
Model trained in 2.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 130.248
  Epoch 9/60
Model trained in 3.04s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 125.190
  Epoch 10/60
Model trained in 3.01s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 120.363
  Epoch 11/60
Model trained in 2.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 115.870
  Epoch 12/60
Model trained in 3.11s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 111.634
  Epoch 13/60
Model trained in 2.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 108.270
  Epoch 14/60
Model trained in 2.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 104.718
  Epoch 15/60
Model trained in 2.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 100.497
  Epoch 16/60
Model trained in 2.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 96.294
  Epoch 17/60
Model trained in 3.00s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.826
  Epoch 18/60
Model trained in 3.04s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.383
  Epoch 19/60
Model trained in 3.07s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.291
  Epoch 20/60
Model trained in 3.00s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.162
  Epoch 21/60
Model trained in 3.09s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.282
  Epoch 22/60
Model trained in 2.97s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.654
  Epoch 23/60
Model trained in 2.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.986
  Epoch 24/60
Model trained in 2.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.843
  Epoch 25/60
Model trained in 2.99s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.936
  Epoch 26/60
Model trained in 2.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.390
  Epoch 27/60
Model trained in 2.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.855
  Epoch 28/60
Model trained in 2.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.519
  Epoch 29/60
Model trained in 2.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 72.826
  Epoch 30/60
Model trained in 2.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 72.144
  Epoch 31/60
Model trained in 2.99s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 72.628
  Epoch 32/60
Model trained in 2.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 71.904
  Epoch 33/60
Model trained in 3.11s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 72.140
  Epoch 34/60
Model trained in 2.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 72.768
  Epoch 35/60
Model trained in 2.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.579
  Epoch 36/60
Model trained in 2.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.078
  Epoch 37/60
Model trained in 2.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.378
  Epoch 38/60
Model trained in 3.06s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.754
  Epoch 39/60
Model trained in 3.13s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.330
  Epoch 40/60
Model trained in 3.01s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.269
  Epoch 41/60
Model trained in 2.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.146
  Epoch 42/60
Model trained in 2.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.269
  Epoch 43/60
Model trained in 2.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.908
  Epoch 44/60
Model trained in 2.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.361
  Epoch 45/60
Model trained in 2.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.959
  Epoch 46/60
Model trained in 2.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.597
  Epoch 47/60
Model trained in 2.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.825
  Epoch 48/60
Model trained in 2.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.680
  Epoch 49/60
Model trained in 2.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.287
  Epoch 50/60
Model trained in 2.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.848
  Epoch 51/60
Model trained in 2.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.355
  Epoch 52/60
Model trained in 2.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.985
  Early stopping triggered.

  best_val_SMAPE=71.904

Combination 822/1152: {'encoder_hidden_size': 48, 'encoder_layers': 1, 'encoder_dropout': 0.0, 'decoder_hidden_size': 33, 'decoder_layers': 2, 'decoder_dropout': 0.0, 'learning_rate': 0.0005, 'max_epochs': 60, 'patience': 20, 'batch_size': 32, 'sequence_length': 168}
Time: 153.33 minutes - estimated total time: 214.88 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 3.01s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 179.212
  Epoch 2/60
Model trained in 3.09s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 169.372
  Epoch 3/60
Model trained in 3.04s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 161.022
  Epoch 4/60
Model trained in 3.07s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 153.759
  Epoch 5/60
Model trained in 3.05s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 147.264
  Epoch 6/60
Model trained in 2.97s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 141.280
  Epoch 7/60
Model trained in 2.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 135.744
  Epoch 8/60
Model trained in 3.00s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 130.492
  Epoch 9/60
Model trained in 3.12s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 125.488
  Epoch 10/60
Model trained in 2.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 120.901
  Epoch 11/60
Model trained in 3.04s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 116.246
  Epoch 12/60
Model trained in 3.03s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 113.867
  Epoch 13/60
Model trained in 2.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 110.298
  Epoch 14/60
Model trained in 2.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 106.949
  Epoch 15/60
Model trained in 2.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 103.234
  Epoch 16/60
Model trained in 2.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 100.714
  Epoch 17/60
Model trained in 2.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 97.722
  Epoch 18/60
Model trained in 2.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 94.569
  Epoch 19/60
Model trained in 2.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.197
  Epoch 20/60
Model trained in 2.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.658
  Epoch 21/60
Model trained in 2.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.066
  Epoch 22/60
Model trained in 2.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.955
  Epoch 23/60
Model trained in 2.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.348
  Epoch 24/60
Model trained in 2.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.014
  Epoch 25/60
Model trained in 3.03s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.462
  Epoch 26/60
Model trained in 2.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.508
  Epoch 27/60
Model trained in 2.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.585
  Epoch 28/60
Model trained in 2.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.241
  Epoch 29/60
Model trained in 2.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.899
  Epoch 30/60
Model trained in 2.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.073
  Epoch 31/60
Model trained in 3.02s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.347
  Epoch 32/60
Model trained in 2.99s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.818
  Epoch 33/60
Model trained in 3.11s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.286
  Epoch 34/60
Model trained in 3.10s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.567
  Epoch 35/60
Model trained in 2.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.408
  Epoch 36/60
Model trained in 2.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.929
  Epoch 37/60
Model trained in 3.11s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.924
  Epoch 38/60
Model trained in 3.00s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.707
  Epoch 39/60
Model trained in 3.08s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.761
  Epoch 40/60
Model trained in 3.06s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.986
  Epoch 41/60
Model trained in 2.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.482
  Epoch 42/60
Model trained in 2.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.749
  Epoch 43/60
Model trained in 2.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.976
  Epoch 44/60
Model trained in 2.95s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.404
  Epoch 45/60
Model trained in 2.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.972
  Epoch 46/60
Model trained in 2.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.362
  Epoch 47/60
Model trained in 3.07s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.724
  Epoch 48/60
Model trained in 2.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.251
  Epoch 49/60
Model trained in 2.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.759
  Epoch 50/60
Model trained in 2.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.598
  Epoch 51/60
Model trained in 2.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.669
  Epoch 52/60
Model trained in 2.95s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.537
  Epoch 53/60
Model trained in 2.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.614
  Early stopping triggered.

  best_val_SMAPE=74.286

Combination 823/1152: {'encoder_hidden_size': 48, 'encoder_layers': 1, 'encoder_dropout': 0.0, 'decoder_hidden_size': 33, 'decoder_layers': 2, 'decoder_dropout': 0.0, 'learning_rate': 0.0005, 'max_epochs': 60, 'patience': 20, 'batch_size': 64, 'sequence_length': 24}
Time: 156.35 minutes - estimated total time: 218.85 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 1.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 185.678
  Epoch 2/60
Model trained in 1.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 179.084
  Epoch 3/60
Model trained in 1.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 173.858
  Epoch 4/60
Model trained in 1.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 169.176
  Epoch 5/60
Model trained in 1.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 164.821
  Epoch 6/60
Model trained in 1.68s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 160.760
  Epoch 7/60
Model trained in 1.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 157.014
  Epoch 8/60
Model trained in 1.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 153.452
  Epoch 9/60
Model trained in 1.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 150.106
  Epoch 10/60
Model trained in 1.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 146.907
  Epoch 11/60
Model trained in 1.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 143.823
  Epoch 12/60
Model trained in 1.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 140.888
  Epoch 13/60
Model trained in 1.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 138.049
  Epoch 14/60
Model trained in 1.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 135.322
  Epoch 15/60
Model trained in 1.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 132.631
  Epoch 16/60
Model trained in 1.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 129.997
  Epoch 17/60
Model trained in 1.65s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 127.425
  Epoch 18/60
Model trained in 1.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 124.914
  Epoch 19/60
Model trained in 1.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 122.457
  Epoch 20/60
Model trained in 1.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 120.366
  Epoch 21/60
Model trained in 1.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 119.090
  Epoch 22/60
Model trained in 1.67s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 116.269
  Epoch 23/60
Model trained in 1.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 114.535
  Epoch 24/60
Model trained in 1.65s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 112.674
  Epoch 25/60
Model trained in 1.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 111.121
  Epoch 26/60
Model trained in 1.68s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 109.216
  Epoch 27/60
Model trained in 1.68s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 107.259
  Epoch 28/60
Model trained in 1.59s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 105.710
  Epoch 29/60
Model trained in 1.65s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 104.003
  Epoch 30/60
Model trained in 1.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 102.371
  Epoch 31/60
Model trained in 1.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 100.761
  Epoch 32/60
Model trained in 1.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 99.433
  Epoch 33/60
Model trained in 1.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 98.091
  Epoch 34/60
Model trained in 1.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 96.599
  Epoch 35/60
Model trained in 1.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 95.483
  Epoch 36/60
Model trained in 1.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 94.084
  Epoch 37/60
Model trained in 1.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.962
  Epoch 38/60
Model trained in 1.63s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.923
  Epoch 39/60
Model trained in 1.67s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.792
  Epoch 40/60
Model trained in 1.65s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.540
  Epoch 41/60
Model trained in 1.65s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.885
  Epoch 42/60
Model trained in 1.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.930
  Epoch 43/60
Model trained in 1.67s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.605
  Epoch 44/60
Model trained in 1.65s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.874
  Epoch 45/60
Model trained in 1.68s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.715
  Epoch 46/60
Model trained in 1.68s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.981
  Epoch 47/60
Model trained in 1.67s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.074
  Epoch 48/60
Model trained in 1.61s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.599
  Epoch 49/60
Model trained in 1.65s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.508
  Epoch 50/60
Model trained in 1.67s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.430
  Epoch 51/60
Model trained in 1.67s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.600
  Epoch 52/60
Model trained in 1.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.479
  Epoch 53/60
Model trained in 1.65s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.708
  Epoch 54/60
Model trained in 1.61s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.476
  Epoch 55/60
Model trained in 1.68s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.635
  Epoch 56/60
Model trained in 1.65s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.928
  Epoch 57/60
Model trained in 1.63s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.619
  Epoch 58/60
Model trained in 1.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.726
  Epoch 59/60
Model trained in 1.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.624
  Epoch 60/60
Model trained in 1.67s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.646

  best_val_SMAPE=73.619

Combination 824/1152: {'encoder_hidden_size': 48, 'encoder_layers': 1, 'encoder_dropout': 0.0, 'decoder_hidden_size': 33, 'decoder_layers': 2, 'decoder_dropout': 0.0, 'learning_rate': 0.0005, 'max_epochs': 60, 'patience': 20, 'batch_size': 64, 'sequence_length': 168}
Time: 158.50 minutes - estimated total time: 221.60 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 1.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 185.875
  Epoch 2/60
Model trained in 1.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 179.163
  Epoch 3/60
Model trained in 1.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 173.933
  Epoch 4/60
Model trained in 1.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 169.265
  Epoch 5/60
Model trained in 1.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 164.925
  Epoch 6/60
Model trained in 1.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 160.881
  Epoch 7/60
Model trained in 1.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 157.148
  Epoch 8/60
Model trained in 1.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 153.599
  Epoch 9/60
Model trained in 1.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 150.266
  Epoch 10/60
Model trained in 1.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 147.082
  Epoch 11/60
Model trained in 1.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 144.011
  Epoch 12/60
Model trained in 1.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 141.086
  Epoch 13/60
Model trained in 1.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 138.261
  Epoch 14/60
Model trained in 1.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 135.536
  Epoch 15/60
Model trained in 1.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 131.687
  Epoch 16/60
Model trained in 1.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 129.785
  Epoch 17/60
Model trained in 1.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 127.945
  Epoch 18/60
Model trained in 1.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 125.577
  Epoch 19/60
Model trained in 1.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 123.035
  Epoch 20/60
Model trained in 1.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 120.652
  Epoch 21/60
Model trained in 1.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 118.459
  Epoch 22/60
Model trained in 1.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 116.366
  Epoch 23/60
Model trained in 1.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 114.327
  Epoch 24/60
Model trained in 1.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 112.383
  Epoch 25/60
Model trained in 1.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 110.314
  Epoch 26/60
Model trained in 1.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 108.322
  Epoch 27/60
Model trained in 1.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 106.282
  Epoch 28/60
Model trained in 1.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 104.708
  Epoch 29/60
Model trained in 1.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 103.261
  Epoch 30/60
Model trained in 1.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 101.438
  Epoch 31/60
Model trained in 1.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 99.302
  Epoch 32/60
Model trained in 1.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 97.969
  Epoch 33/60
Model trained in 1.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 96.978
  Epoch 34/60
Model trained in 1.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 95.444
  Epoch 35/60
Model trained in 1.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 94.801
  Epoch 36/60
Model trained in 1.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.624
  Epoch 37/60
Model trained in 1.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.498
  Epoch 38/60
Model trained in 1.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.442
  Epoch 39/60
Model trained in 1.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.342
  Epoch 40/60
Model trained in 2.09s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.310
  Epoch 41/60
Model trained in 1.99s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.929
  Epoch 42/60
Model trained in 1.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.304
  Epoch 43/60
Model trained in 1.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.357
  Epoch 44/60
Model trained in 1.97s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.120
  Epoch 45/60
Model trained in 2.08s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.516
  Epoch 46/60
Model trained in 1.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.079
  Epoch 47/60
Model trained in 1.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.817
  Epoch 48/60
Model trained in 1.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.417
  Epoch 49/60
Model trained in 1.99s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.373
  Epoch 50/60
Model trained in 1.99s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.640
  Epoch 51/60
Model trained in 1.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.028
  Epoch 52/60
Model trained in 1.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.394
  Epoch 53/60
Model trained in 1.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.732
  Epoch 54/60
Model trained in 1.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.939
  Epoch 55/60
Model trained in 1.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.706
  Epoch 56/60
Model trained in 1.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.606
  Epoch 57/60
Model trained in 1.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.019
  Epoch 58/60
Model trained in 1.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.433
  Epoch 59/60
Model trained in 2.10s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.259
  Epoch 60/60
Model trained in 2.06s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.979

  best_val_SMAPE=77.433

Combination 825/1152: {'encoder_hidden_size': 48, 'encoder_layers': 1, 'encoder_dropout': 0.0, 'decoder_hidden_size': 33, 'decoder_layers': 2, 'decoder_dropout': 0.2, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 20, 'batch_size': 32, 'sequence_length': 24}
Time: 160.85 minutes - estimated total time: 224.61 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 3.00s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 169.258
  Epoch 2/60
Model trained in 3.06s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 153.494
  Epoch 3/60
Model trained in 2.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 141.015
  Epoch 4/60
Model trained in 3.03s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 131.554
  Epoch 5/60
Model trained in 3.18s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 122.828
  Epoch 6/60
Model trained in 3.02s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 114.268
  Epoch 7/60
Model trained in 2.98s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 108.354
  Epoch 8/60
Model trained in 2.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 103.180
  Epoch 9/60
Model trained in 2.98s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 98.472
  Epoch 10/60
Model trained in 3.14s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 94.427
  Epoch 11/60
Model trained in 3.07s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.716
  Epoch 12/60
Model trained in 3.00s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.840
  Epoch 13/60
Model trained in 2.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.595
  Epoch 14/60
Model trained in 2.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.384
  Epoch 15/60
Model trained in 2.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.694
  Epoch 16/60
Model trained in 2.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.757
  Epoch 17/60
Model trained in 2.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.890
  Epoch 18/60
Model trained in 2.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.013
  Epoch 19/60
Model trained in 2.95s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.716
  Epoch 20/60
Model trained in 2.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.112
  Epoch 21/60
Model trained in 3.16s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.761
  Epoch 22/60
Model trained in 3.07s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.436
  Epoch 23/60
Model trained in 3.07s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.792
  Epoch 24/60
Model trained in 3.08s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.326
  Epoch 25/60
Model trained in 2.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.972
  Epoch 26/60
Model trained in 2.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.814
  Epoch 27/60
Model trained in 2.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.555
  Epoch 28/60
Model trained in 2.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.483
  Epoch 29/60
Model trained in 2.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.095
  Epoch 30/60
Model trained in 3.07s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.863
  Epoch 31/60
Model trained in 2.99s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.606
  Epoch 32/60
Model trained in 3.44s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.083
  Epoch 33/60
Model trained in 3.24s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.833
  Epoch 34/60
Model trained in 2.98s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.178
  Epoch 35/60
Model trained in 3.09s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.104
  Epoch 36/60
Model trained in 2.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.749
  Epoch 37/60
Model trained in 2.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.763
  Epoch 38/60
Model trained in 3.01s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.497
  Epoch 39/60
Model trained in 3.05s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.493
  Epoch 40/60
Model trained in 2.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.942
  Epoch 41/60
Model trained in 2.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.022
  Epoch 42/60
Model trained in 3.15s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.859
  Epoch 43/60
Model trained in 2.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.678
  Epoch 44/60
Model trained in 3.04s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.872
  Epoch 45/60
Model trained in 3.12s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.547
  Epoch 46/60
Model trained in 2.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.280
  Epoch 47/60
Model trained in 2.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.529
  Epoch 48/60
Model trained in 2.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.279
  Epoch 49/60
Model trained in 3.08s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.056
  Epoch 50/60
Model trained in 3.00s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.155
  Epoch 51/60
Model trained in 3.13s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.946
  Epoch 52/60
Model trained in 3.19s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.984
  Epoch 53/60
Model trained in 2.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.116
  Epoch 54/60
Model trained in 2.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.011
  Epoch 55/60
Model trained in 2.57s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.640
  Epoch 56/60
Model trained in 2.63s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.533
  Epoch 57/60
Model trained in 2.56s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.428
  Epoch 58/60
Model trained in 2.63s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.677
  Epoch 59/60
Model trained in 2.62s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.719
  Epoch 60/60
Model trained in 2.67s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.176

  best_val_SMAPE=73.428

Combination 826/1152: {'encoder_hidden_size': 48, 'encoder_layers': 1, 'encoder_dropout': 0.0, 'decoder_hidden_size': 33, 'decoder_layers': 2, 'decoder_dropout': 0.2, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 20, 'batch_size': 32, 'sequence_length': 168}
Time: 164.28 minutes - estimated total time: 229.12 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 2.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 169.395
  Epoch 2/60
Model trained in 3.16s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 153.664
  Epoch 3/60
Model trained in 2.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 141.217
  Epoch 4/60
Model trained in 2.68s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 130.475
  Epoch 5/60
Model trained in 2.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 120.721
  Epoch 6/60
Model trained in 2.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 114.273
  Epoch 7/60
Model trained in 2.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 105.924
  Epoch 8/60
Model trained in 2.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 99.412
  Epoch 9/60
Model trained in 2.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.173
  Epoch 10/60
Model trained in 2.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.088
  Epoch 11/60
Model trained in 2.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.011
  Epoch 12/60
Model trained in 2.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.141
  Epoch 13/60
Model trained in 2.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.565
  Epoch 14/60
Model trained in 2.58s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.628
  Epoch 15/60
Model trained in 2.65s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.245
  Epoch 16/60
Model trained in 2.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.791
  Epoch 17/60
Model trained in 2.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.074
  Epoch 18/60
Model trained in 2.67s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.077
  Epoch 19/60
Model trained in 2.58s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.631
  Epoch 20/60
Model trained in 2.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.178
  Epoch 21/60
Model trained in 2.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.050
  Epoch 22/60
Model trained in 2.62s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.357
  Epoch 23/60
Model trained in 2.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.753
  Epoch 24/60
Model trained in 2.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.212
  Epoch 25/60
Model trained in 2.61s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.278
  Epoch 26/60
Model trained in 2.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.031
  Epoch 27/60
Model trained in 2.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.550
  Epoch 28/60
Model trained in 2.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.567
  Epoch 29/60
Model trained in 2.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.032
  Epoch 30/60
Model trained in 2.68s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.560
  Epoch 31/60
Model trained in 2.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.618
  Epoch 32/60
Model trained in 2.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.241
  Epoch 33/60
Model trained in 2.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.936
  Epoch 34/60
Model trained in 2.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.966
  Epoch 35/60
Model trained in 2.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.782
  Epoch 36/60
Model trained in 2.68s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.593
  Epoch 37/60
Model trained in 2.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.097
  Epoch 38/60
Model trained in 2.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.815
  Epoch 39/60
Model trained in 2.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.438
  Epoch 40/60
Model trained in 2.68s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.037
  Epoch 41/60
Model trained in 2.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.837
  Epoch 42/60
Model trained in 2.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.236
  Epoch 43/60
Model trained in 2.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.160
  Epoch 44/60
Model trained in 2.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.158
  Epoch 45/60
Model trained in 2.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.882
  Epoch 46/60
Model trained in 2.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.880
  Epoch 47/60
Model trained in 2.62s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.811
  Epoch 48/60
Model trained in 2.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.061
  Epoch 49/60
Model trained in 2.63s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.330
  Epoch 50/60
Model trained in 2.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.435
  Epoch 51/60
Model trained in 2.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.493
  Epoch 52/60
Model trained in 2.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.658
  Epoch 53/60
Model trained in 2.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.450
  Epoch 54/60
Model trained in 2.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.213
  Epoch 55/60
Model trained in 2.62s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.030
  Epoch 56/60
Model trained in 2.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.814
  Epoch 57/60
Model trained in 2.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.275
  Early stopping triggered.

  best_val_SMAPE=75.097

Combination 827/1152: {'encoder_hidden_size': 48, 'encoder_layers': 1, 'encoder_dropout': 0.0, 'decoder_hidden_size': 33, 'decoder_layers': 2, 'decoder_dropout': 0.2, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 20, 'batch_size': 64, 'sequence_length': 24}
Time: 167.34 minutes - estimated total time: 233.10 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 1.65s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 179.258
  Epoch 2/60
Model trained in 1.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 169.121
  Epoch 3/60
Model trained in 1.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 160.635
  Epoch 4/60
Model trained in 1.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 153.315
  Epoch 5/60
Model trained in 1.65s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 146.780
  Epoch 6/60
Model trained in 1.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 140.808
  Epoch 7/60
Model trained in 1.59s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 135.396
  Epoch 8/60
Model trained in 1.63s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 130.191
  Epoch 9/60
Model trained in 1.67s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 124.984
  Epoch 10/60
Model trained in 1.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 120.211
  Epoch 11/60
Model trained in 1.58s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 115.872
  Epoch 12/60
Model trained in 1.61s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 114.877
  Epoch 13/60
Model trained in 1.63s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 111.984
  Epoch 14/60
Model trained in 1.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 108.557
  Epoch 15/60
Model trained in 1.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 105.488
  Epoch 16/60
Model trained in 1.57s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 102.218
  Epoch 17/60
Model trained in 1.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 99.004
  Epoch 18/60
Model trained in 1.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 96.365
  Epoch 19/60
Model trained in 1.58s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.534
  Epoch 20/60
Model trained in 1.62s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.994
  Epoch 21/60
Model trained in 1.59s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.576
  Epoch 22/60
Model trained in 1.58s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.807
  Epoch 23/60
Model trained in 1.56s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.690
  Epoch 24/60
Model trained in 1.62s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.215
  Epoch 25/60
Model trained in 1.54s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.209
  Epoch 26/60
Model trained in 1.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.507
  Epoch 27/60
Model trained in 1.59s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.606
  Epoch 28/60
Model trained in 1.57s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.255
  Epoch 29/60
Model trained in 1.53s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.859
  Epoch 30/60
Model trained in 1.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.908
  Epoch 31/60
Model trained in 1.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.031
  Epoch 32/60
Model trained in 1.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.717
  Epoch 33/60
Model trained in 1.57s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.106
  Epoch 34/60
Model trained in 1.60s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.198
  Epoch 35/60
Model trained in 1.56s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.107
  Epoch 36/60
Model trained in 1.54s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.804
  Epoch 37/60
Model trained in 1.62s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.709
  Epoch 38/60
Model trained in 1.58s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.659
  Epoch 39/60
Model trained in 1.57s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.005
  Epoch 40/60
Model trained in 1.55s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.817
  Epoch 41/60
Model trained in 1.56s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.373
  Epoch 42/60
Model trained in 1.60s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.598
  Epoch 43/60
Model trained in 1.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.971
  Epoch 44/60
Model trained in 1.58s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.605
  Epoch 45/60
Model trained in 1.58s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.843
  Epoch 46/60
Model trained in 1.57s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.377
  Epoch 47/60
Model trained in 1.60s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.982
  Epoch 48/60
Model trained in 1.68s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.850
  Epoch 49/60
Model trained in 1.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.016
  Epoch 50/60
Model trained in 1.62s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.735
  Epoch 51/60
Model trained in 1.58s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.199
  Epoch 52/60
Model trained in 1.58s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.038
  Epoch 53/60
Model trained in 1.58s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.742
  Epoch 54/60
Model trained in 1.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.203
  Epoch 55/60
Model trained in 1.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.328
  Epoch 56/60
Model trained in 1.57s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.616
  Epoch 57/60
Model trained in 1.59s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.176
  Epoch 58/60
Model trained in 1.59s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.506
  Epoch 59/60
Model trained in 1.56s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.307
  Epoch 60/60
Model trained in 1.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.991

  best_val_SMAPE=74.991

Combination 828/1152: {'encoder_hidden_size': 48, 'encoder_layers': 1, 'encoder_dropout': 0.0, 'decoder_hidden_size': 33, 'decoder_layers': 2, 'decoder_dropout': 0.2, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 20, 'batch_size': 64, 'sequence_length': 168}
Time: 169.43 minutes - estimated total time: 235.73 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 1.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 179.325
  Epoch 2/60
Model trained in 1.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 169.221
  Epoch 3/60
Model trained in 1.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 160.776
  Epoch 4/60
Model trained in 1.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 153.484
  Epoch 5/60
Model trained in 1.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 146.979
  Epoch 6/60
Model trained in 1.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 141.011
  Epoch 7/60
Model trained in 1.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 135.550
  Epoch 8/60
Model trained in 1.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 130.388
  Epoch 9/60
Model trained in 1.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 126.034
  Epoch 10/60
Model trained in 1.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 121.416
  Epoch 11/60
Model trained in 1.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 116.825
  Epoch 12/60
Model trained in 1.65s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 112.838
  Epoch 13/60
Model trained in 1.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 109.321
  Epoch 14/60
Model trained in 1.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 105.835
  Epoch 15/60
Model trained in 1.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 102.864
  Epoch 16/60
Model trained in 1.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 100.481
  Epoch 17/60
Model trained in 1.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 97.918
  Epoch 18/60
Model trained in 1.68s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 95.082
  Epoch 19/60
Model trained in 1.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.311
  Epoch 20/60
Model trained in 1.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.624
  Epoch 21/60
Model trained in 1.65s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.289
  Epoch 22/60
Model trained in 1.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.459
  Epoch 23/60
Model trained in 1.67s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.761
  Epoch 24/60
Model trained in 1.67s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.981
  Epoch 25/60
Model trained in 1.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.936
  Epoch 26/60
Model trained in 1.68s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.806
  Epoch 27/60
Model trained in 1.61s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.683
  Epoch 28/60
Model trained in 1.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.425
  Epoch 29/60
Model trained in 1.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.941
  Epoch 30/60
Model trained in 1.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.705
  Epoch 31/60
Model trained in 1.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.925
  Epoch 32/60
Model trained in 1.63s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.343
  Epoch 33/60
Model trained in 1.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.653
  Epoch 34/60
Model trained in 1.65s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.845
  Epoch 35/60
Model trained in 1.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.022
  Epoch 36/60
Model trained in 1.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.723
  Epoch 37/60
Model trained in 1.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.286
  Epoch 38/60
Model trained in 1.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.816
  Epoch 39/60
Model trained in 1.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.817
  Epoch 40/60
Model trained in 1.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.638
  Epoch 41/60
Model trained in 1.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.450
  Epoch 42/60
Model trained in 1.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.618
  Epoch 43/60
Model trained in 1.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.447
  Epoch 44/60
Model trained in 1.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.884
  Epoch 45/60
Model trained in 1.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.180
  Epoch 46/60
Model trained in 1.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.781
  Epoch 47/60
Model trained in 1.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.359
  Epoch 48/60
Model trained in 1.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.700
  Epoch 49/60
Model trained in 1.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.109
  Epoch 50/60
Model trained in 1.68s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.294
  Epoch 51/60
Model trained in 1.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.727
  Epoch 52/60
Model trained in 1.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.604
  Epoch 53/60
Model trained in 2.01s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.569
  Epoch 54/60
Model trained in 2.00s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.723
  Epoch 55/60
Model trained in 1.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.824
  Epoch 56/60
Model trained in 2.02s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.063
  Early stopping triggered.

  best_val_SMAPE=74.723

Combination 829/1152: {'encoder_hidden_size': 48, 'encoder_layers': 1, 'encoder_dropout': 0.0, 'decoder_hidden_size': 33, 'decoder_layers': 2, 'decoder_dropout': 0.2, 'learning_rate': 0.0005, 'max_epochs': 60, 'patience': 20, 'batch_size': 32, 'sequence_length': 24}
Time: 171.53 minutes - estimated total time: 238.37 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 2.95s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 179.161
  Epoch 2/60
Model trained in 3.03s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 169.278
  Epoch 3/60
Model trained in 3.11s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 160.893
  Epoch 4/60
Model trained in 2.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 153.608
  Epoch 5/60
Model trained in 3.25s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 147.089
  Epoch 6/60
Model trained in 3.15s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 141.093
  Epoch 7/60
Model trained in 2.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 135.544
  Epoch 8/60
Model trained in 2.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 129.918
  Epoch 9/60
Model trained in 3.08s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 125.514
  Epoch 10/60
Model trained in 3.07s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 120.601
  Epoch 11/60
Model trained in 2.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 116.302
  Epoch 12/60
Model trained in 2.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 112.279
  Epoch 13/60
Model trained in 2.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 108.266
  Epoch 14/60
Model trained in 2.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 104.595
  Epoch 15/60
Model trained in 3.17s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 101.301
  Epoch 16/60
Model trained in 3.17s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 98.039
  Epoch 17/60
Model trained in 3.05s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 94.806
  Epoch 18/60
Model trained in 3.19s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.876
  Epoch 19/60
Model trained in 3.05s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.350
  Epoch 20/60
Model trained in 3.19s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.805
  Epoch 21/60
Model trained in 3.14s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.517
  Epoch 22/60
Model trained in 3.03s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.512
  Epoch 23/60
Model trained in 3.13s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.586
  Epoch 24/60
Model trained in 2.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.153
  Epoch 25/60
Model trained in 2.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.586
  Epoch 26/60
Model trained in 3.02s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.168
  Epoch 27/60
Model trained in 2.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.198
  Epoch 28/60
Model trained in 2.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.603
  Epoch 29/60
Model trained in 2.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 72.377
  Epoch 30/60
Model trained in 3.08s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 72.409
  Epoch 31/60
Model trained in 2.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 71.724
  Epoch 32/60
Model trained in 2.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 72.211
  Epoch 33/60
Model trained in 3.23s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 72.856
  Epoch 34/60
Model trained in 3.02s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 72.459
  Epoch 35/60
Model trained in 3.01s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 72.235
  Epoch 36/60
Model trained in 3.46s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 71.843
  Epoch 37/60
Model trained in 2.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 70.753
  Epoch 38/60
Model trained in 3.09s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 70.579
  Epoch 39/60
Model trained in 2.95s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 70.736
  Epoch 40/60
Model trained in 2.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 70.821
  Epoch 41/60
Model trained in 2.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 70.490
  Epoch 42/60
Model trained in 2.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 70.274
  Epoch 43/60
Model trained in 3.04s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 69.868
  Epoch 44/60
Model trained in 2.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 69.390
  Epoch 45/60
Model trained in 3.02s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 69.096
  Epoch 46/60
Model trained in 3.38s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 68.989
  Epoch 47/60
Model trained in 3.08s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 68.935
  Epoch 48/60
Model trained in 2.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 68.910
  Epoch 49/60
Model trained in 2.95s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 69.494
  Epoch 50/60
Model trained in 2.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 69.076
  Epoch 51/60
Model trained in 3.13s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 69.218
  Epoch 52/60
Model trained in 3.04s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 69.267
  Epoch 53/60
Model trained in 3.11s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 68.838
  Epoch 54/60
Model trained in 2.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 69.653
  Epoch 55/60
Model trained in 2.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 70.392
  Epoch 56/60
Model trained in 2.95s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 70.736
  Epoch 57/60
Model trained in 3.08s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 70.513
  Epoch 58/60
Model trained in 3.05s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 70.319
  Epoch 59/60
Model trained in 2.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 70.325
  Epoch 60/60
Model trained in 3.07s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 69.962

  best_val_SMAPE=68.838

Combination 830/1152: {'encoder_hidden_size': 48, 'encoder_layers': 1, 'encoder_dropout': 0.0, 'decoder_hidden_size': 33, 'decoder_layers': 2, 'decoder_dropout': 0.2, 'learning_rate': 0.0005, 'max_epochs': 60, 'patience': 20, 'batch_size': 32, 'sequence_length': 168}
Time: 175.03 minutes - estimated total time: 242.93 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 2.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 179.206
  Epoch 2/60
Model trained in 2.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 169.365
  Epoch 3/60
Model trained in 3.06s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 161.016
  Epoch 4/60
Model trained in 2.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 153.754
  Epoch 5/60
Model trained in 3.02s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 147.259
  Epoch 6/60
Model trained in 3.25s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 141.279
  Epoch 7/60
Model trained in 3.05s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 135.765
  Epoch 8/60
Model trained in 3.07s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 130.485
  Epoch 9/60
Model trained in 3.09s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 125.519
  Epoch 10/60
Model trained in 2.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 120.785
  Epoch 11/60
Model trained in 2.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 116.206
  Epoch 12/60
Model trained in 2.95s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 112.495
  Epoch 13/60
Model trained in 3.05s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 108.668
  Epoch 14/60
Model trained in 3.15s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 105.285
  Epoch 15/60
Model trained in 3.27s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 102.573
  Epoch 16/60
Model trained in 3.14s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 99.912
  Epoch 17/60
Model trained in 3.04s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 97.631
  Epoch 18/60
Model trained in 2.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 95.137
  Epoch 19/60
Model trained in 2.98s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.789
  Epoch 20/60
Model trained in 2.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.292
  Epoch 21/60
Model trained in 3.16s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.942
  Epoch 22/60
Model trained in 3.23s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.338
  Epoch 23/60
Model trained in 2.99s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.236
  Epoch 24/60
Model trained in 3.23s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.037
  Epoch 25/60
Model trained in 3.18s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.866
  Epoch 26/60
Model trained in 3.27s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.698
  Epoch 27/60
Model trained in 2.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.029
  Epoch 28/60
Model trained in 3.05s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.863
  Epoch 29/60
Model trained in 3.08s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.599
  Epoch 30/60
Model trained in 3.19s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.180
  Epoch 31/60
Model trained in 3.18s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.006
  Epoch 32/60
Model trained in 3.07s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.475
  Epoch 33/60
Model trained in 3.16s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.699
  Epoch 34/60
Model trained in 3.22s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.743
  Epoch 35/60
Model trained in 3.12s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.060
  Epoch 36/60
Model trained in 2.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.777
  Epoch 37/60
Model trained in 3.05s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.557
  Epoch 38/60
Model trained in 2.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.848
  Epoch 39/60
Model trained in 2.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.496
  Epoch 40/60
Model trained in 2.67s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.978
  Epoch 41/60
Model trained in 2.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.940
  Epoch 42/60
Model trained in 2.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.031
  Epoch 43/60
Model trained in 2.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.771
  Epoch 44/60
Model trained in 2.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.965
  Epoch 45/60
Model trained in 2.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.432
  Epoch 46/60
Model trained in 2.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.686
  Epoch 47/60
Model trained in 2.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.792
  Epoch 48/60
Model trained in 3.12s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.491
  Epoch 49/60
Model trained in 3.26s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.285
  Epoch 50/60
Model trained in 3.18s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.135
  Epoch 51/60
Model trained in 2.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.163
  Epoch 52/60
Model trained in 2.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.408
  Epoch 53/60
Model trained in 3.09s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.558
  Epoch 54/60
Model trained in 3.23s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.290
  Epoch 55/60
Model trained in 3.34s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.244
  Epoch 56/60
Model trained in 3.29s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.103
  Epoch 57/60
Model trained in 2.97s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.843
  Epoch 58/60
Model trained in 2.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.848
  Epoch 59/60
Model trained in 2.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.568
  Epoch 60/60
Model trained in 2.97s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.136

  best_val_SMAPE=74.136

Combination 831/1152: {'encoder_hidden_size': 48, 'encoder_layers': 1, 'encoder_dropout': 0.0, 'decoder_hidden_size': 33, 'decoder_layers': 2, 'decoder_dropout': 0.2, 'learning_rate': 0.0005, 'max_epochs': 60, 'patience': 20, 'batch_size': 64, 'sequence_length': 24}
Time: 178.54 minutes - estimated total time: 247.51 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 1.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 185.672
  Epoch 2/60
Model trained in 1.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 179.078
  Epoch 3/60
Model trained in 2.03s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 173.852
  Epoch 4/60
Model trained in 2.06s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 169.170
  Epoch 5/60
Model trained in 1.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 164.816
  Epoch 6/60
Model trained in 2.14s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 160.755
  Epoch 7/60
Model trained in 2.03s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 157.009
  Epoch 8/60
Model trained in 1.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 153.449
  Epoch 9/60
Model trained in 1.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 150.103
  Epoch 10/60
Model trained in 1.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 146.901
  Epoch 11/60
Model trained in 1.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 143.815
  Epoch 12/60
Model trained in 1.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 140.884
  Epoch 13/60
Model trained in 1.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 138.044
  Epoch 14/60
Model trained in 1.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 135.310
  Epoch 15/60
Model trained in 1.62s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 132.625
  Epoch 16/60
Model trained in 1.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 129.989
  Epoch 17/60
Model trained in 1.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 127.421
  Epoch 18/60
Model trained in 1.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 124.926
  Epoch 19/60
Model trained in 1.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 122.472
  Epoch 20/60
Model trained in 1.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 119.884
  Epoch 21/60
Model trained in 1.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 119.119
  Epoch 22/60
Model trained in 1.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 117.159
  Epoch 23/60
Model trained in 1.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 115.007
  Epoch 24/60
Model trained in 1.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 112.931
  Epoch 25/60
Model trained in 1.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 110.974
  Epoch 26/60
Model trained in 1.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 109.199
  Epoch 27/60
Model trained in 1.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 107.644
  Epoch 28/60
Model trained in 1.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 106.130
  Epoch 29/60
Model trained in 1.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 104.547
  Epoch 30/60
Model trained in 1.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 102.815
  Epoch 31/60
Model trained in 1.65s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 101.135
  Epoch 32/60
Model trained in 1.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 99.433
  Epoch 33/60
Model trained in 1.62s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 97.916
  Epoch 34/60
Model trained in 1.67s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 96.400
  Epoch 35/60
Model trained in 1.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 94.892
  Epoch 36/60
Model trained in 1.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.339
  Epoch 37/60
Model trained in 1.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.238
  Epoch 38/60
Model trained in 1.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.086
  Epoch 39/60
Model trained in 1.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.916
  Epoch 40/60
Model trained in 1.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.873
  Epoch 41/60
Model trained in 1.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.716
  Epoch 42/60
Model trained in 1.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.755
  Epoch 43/60
Model trained in 1.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.537
  Epoch 44/60
Model trained in 1.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.734
  Epoch 45/60
Model trained in 1.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.118
  Epoch 46/60
Model trained in 1.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.099
  Epoch 47/60
Model trained in 1.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.259
  Epoch 48/60
Model trained in 1.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.511
  Epoch 49/60
Model trained in 1.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.191
  Epoch 50/60
Model trained in 1.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.818
  Epoch 51/60
Model trained in 1.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.602
  Epoch 52/60
Model trained in 1.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.305
  Epoch 53/60
Model trained in 1.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.271
  Epoch 54/60
Model trained in 1.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.970
  Epoch 55/60
Model trained in 1.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.665
  Epoch 56/60
Model trained in 1.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.415
  Epoch 57/60
Model trained in 1.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.453
  Epoch 58/60
Model trained in 1.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.204
  Epoch 59/60
Model trained in 1.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.785
  Epoch 60/60
Model trained in 1.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.651

  best_val_SMAPE=78.651

Combination 832/1152: {'encoder_hidden_size': 48, 'encoder_layers': 1, 'encoder_dropout': 0.0, 'decoder_hidden_size': 33, 'decoder_layers': 2, 'decoder_dropout': 0.2, 'learning_rate': 0.0005, 'max_epochs': 60, 'patience': 20, 'batch_size': 64, 'sequence_length': 168}
Time: 180.84 minutes - estimated total time: 250.40 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 2.03s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 185.868
  Epoch 2/60
Model trained in 2.02s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 179.153
  Epoch 3/60
Model trained in 1.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 173.925
  Epoch 4/60
Model trained in 1.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 169.258
  Epoch 5/60
Model trained in 1.98s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 164.918
  Epoch 6/60
Model trained in 1.99s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 160.875
  Epoch 7/60
Model trained in 2.06s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 157.142
  Epoch 8/60
Model trained in 1.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 153.593
  Epoch 9/60
Model trained in 1.99s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 150.261
  Epoch 10/60
Model trained in 1.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 147.076
  Epoch 11/60
Model trained in 2.02s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 144.005
  Epoch 12/60
Model trained in 1.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 141.083
  Epoch 13/60
Model trained in 1.97s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 138.258
  Epoch 14/60
Model trained in 1.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 135.546
  Epoch 15/60
Model trained in 1.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 132.872
  Epoch 16/60
Model trained in 1.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 130.262
  Epoch 17/60
Model trained in 1.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 128.507
  Epoch 18/60
Model trained in 1.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 126.403
  Epoch 19/60
Model trained in 1.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 124.071
  Epoch 20/60
Model trained in 1.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 121.766
  Epoch 21/60
Model trained in 1.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 119.198
  Epoch 22/60
Model trained in 1.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 117.101
  Epoch 23/60
Model trained in 1.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 115.136
  Epoch 24/60
Model trained in 1.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 113.221
  Epoch 25/60
Model trained in 1.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 111.604
  Epoch 26/60
Model trained in 1.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 109.758
  Epoch 27/60
Model trained in 1.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 108.014
  Epoch 28/60
Model trained in 1.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 106.178
  Epoch 29/60
Model trained in 2.00s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 104.303
  Epoch 30/60
Model trained in 1.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 102.828
  Epoch 31/60
Model trained in 1.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 101.073
  Epoch 32/60
Model trained in 1.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 99.342
  Epoch 33/60
Model trained in 1.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 98.009
  Epoch 34/60
Model trained in 1.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 96.351
  Epoch 35/60
Model trained in 1.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 94.886
  Epoch 36/60
Model trained in 1.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.849
  Epoch 37/60
Model trained in 1.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.180
  Epoch 38/60
Model trained in 1.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.896
  Epoch 39/60
Model trained in 1.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.740
  Epoch 40/60
Model trained in 1.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.612
  Epoch 41/60
Model trained in 1.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.255
  Epoch 42/60
Model trained in 1.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.053
  Epoch 43/60
Model trained in 1.99s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.096
  Epoch 44/60
Model trained in 1.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.875
  Epoch 45/60
Model trained in 1.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.694
  Epoch 46/60
Model trained in 1.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.146
  Epoch 47/60
Model trained in 1.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.916
  Epoch 48/60
Model trained in 1.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.820
  Epoch 49/60
Model trained in 1.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.007
  Epoch 50/60
Model trained in 1.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.263
  Epoch 51/60
Model trained in 1.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.671
  Epoch 52/60
Model trained in 1.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.909
  Epoch 53/60
Model trained in 1.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.063
  Epoch 54/60
Model trained in 1.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.115
  Epoch 55/60
Model trained in 1.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.175
  Epoch 56/60
Model trained in 1.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 72.754
  Epoch 57/60
Model trained in 1.99s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 72.434
  Epoch 58/60
Model trained in 1.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 72.301
  Epoch 59/60
Model trained in 1.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 71.727
  Epoch 60/60
Model trained in 1.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 71.146

  best_val_SMAPE=71.146

Combination 833/1152: {'encoder_hidden_size': 48, 'encoder_layers': 1, 'encoder_dropout': 0.0, 'decoder_hidden_size': 48, 'decoder_layers': 1, 'decoder_dropout': 0.0, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 20, 'batch_size': 32, 'sequence_length': 24}
Time: 183.20 minutes - estimated total time: 253.36 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 2.24s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 160.491
  Epoch 2/60
Model trained in 2.15s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 141.437
  Epoch 3/60
Model trained in 2.21s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 126.833
  Epoch 4/60
Model trained in 2.09s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 114.615
  Epoch 5/60
Model trained in 2.16s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 104.674
  Epoch 6/60
Model trained in 2.21s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 96.318
  Epoch 7/60
Model trained in 2.15s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.589
  Epoch 8/60
Model trained in 2.15s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.114
  Epoch 9/60
Model trained in 2.12s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.322
  Epoch 10/60
Model trained in 2.23s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.183
  Epoch 11/60
Model trained in 2.24s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.820
  Epoch 12/60
Model trained in 2.12s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.686
  Epoch 13/60
Model trained in 2.25s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.766
  Epoch 14/60
Model trained in 2.17s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.618
  Epoch 15/60
Model trained in 2.14s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.377
  Epoch 16/60
Model trained in 2.16s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 94.089
  Epoch 17/60
Model trained in 2.14s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 96.749
  Epoch 18/60
Model trained in 2.07s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 101.848
  Epoch 19/60
Model trained in 2.10s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 107.078
  Epoch 20/60
Model trained in 1.99s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 100.861
  Epoch 21/60
Model trained in 2.06s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 98.987
  Epoch 22/60
Model trained in 2.14s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 96.900
  Epoch 23/60
Model trained in 1.99s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.894
  Epoch 24/60
Model trained in 1.99s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 95.536
  Epoch 25/60
Model trained in 1.98s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 97.724
  Epoch 26/60
Model trained in 2.04s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 103.271
  Epoch 27/60
Model trained in 2.09s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 101.712
  Epoch 28/60
Model trained in 2.09s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 98.641
  Epoch 29/60
Model trained in 2.16s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 101.649
  Epoch 30/60
Model trained in 2.13s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 104.689
  Epoch 31/60
Model trained in 2.20s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 104.590
  Early stopping triggered.

  best_val_SMAPE=79.820

Combination 834/1152: {'encoder_hidden_size': 48, 'encoder_layers': 1, 'encoder_dropout': 0.0, 'decoder_hidden_size': 48, 'decoder_layers': 1, 'decoder_dropout': 0.0, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 20, 'batch_size': 32, 'sequence_length': 168}
Time: 184.56 minutes - estimated total time: 254.93 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 2.25s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 160.667
  Epoch 2/60
Model trained in 2.35s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 141.636
  Epoch 3/60
Model trained in 2.18s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 127.108
  Epoch 4/60
Model trained in 2.27s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 115.267
  Epoch 5/60
Model trained in 2.25s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 105.050
  Epoch 6/60
Model trained in 2.31s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 96.581
  Epoch 7/60
Model trained in 2.22s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.390
  Epoch 8/60
Model trained in 2.26s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.554
  Epoch 9/60
Model trained in 2.25s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.990
  Epoch 10/60
Model trained in 2.23s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.062
  Epoch 11/60
Model trained in 2.28s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.052
  Epoch 12/60
Model trained in 2.30s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.207
  Epoch 13/60
Model trained in 2.26s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.372
  Epoch 14/60
Model trained in 2.25s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.931
  Epoch 15/60
Model trained in 2.29s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.803
  Epoch 16/60
Model trained in 2.15s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.212
  Epoch 17/60
Model trained in 2.18s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 98.473
  Epoch 18/60
Model trained in 2.27s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 103.464
  Epoch 19/60
Model trained in 2.23s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 107.371
  Epoch 20/60
Model trained in 2.23s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 108.924
  Epoch 21/60
Model trained in 2.19s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 109.772
  Epoch 22/60
Model trained in 2.21s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 109.297
  Epoch 23/60
Model trained in 2.11s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 109.903
  Epoch 24/60
Model trained in 2.12s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 109.258
  Epoch 25/60
Model trained in 2.19s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 108.983
  Epoch 26/60
Model trained in 2.14s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 105.804
  Epoch 27/60
Model trained in 2.16s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 103.839
  Epoch 28/60
Model trained in 2.17s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 102.097
  Epoch 29/60
Model trained in 2.11s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 100.096
  Epoch 30/60
Model trained in 2.21s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 99.184
  Early stopping triggered.

  best_val_SMAPE=78.062

Combination 835/1152: {'encoder_hidden_size': 48, 'encoder_layers': 1, 'encoder_dropout': 0.0, 'decoder_hidden_size': 48, 'decoder_layers': 1, 'decoder_dropout': 0.0, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 20, 'batch_size': 64, 'sequence_length': 24}
Time: 185.94 minutes - estimated total time: 256.53 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 1.51s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 173.077
  Epoch 2/60
Model trained in 1.40s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 160.249
  Epoch 3/60
Model trained in 1.36s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 149.965
  Epoch 4/60
Model trained in 1.33s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 141.281
  Epoch 5/60
Model trained in 1.45s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 133.583
  Epoch 6/60
Model trained in 1.32s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 126.711
  Epoch 7/60
Model trained in 1.40s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 120.095
  Epoch 8/60
Model trained in 1.43s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 114.345
  Epoch 9/60
Model trained in 1.33s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 109.084
  Epoch 10/60
Model trained in 1.33s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 104.518
  Epoch 11/60
Model trained in 1.34s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 100.436
  Epoch 12/60
Model trained in 1.45s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 96.374
  Epoch 13/60
Model trained in 1.37s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.843
  Epoch 14/60
Model trained in 1.42s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.520
  Epoch 15/60
Model trained in 1.34s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.173
  Epoch 16/60
Model trained in 1.38s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.765
  Epoch 17/60
Model trained in 1.39s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.964
  Epoch 18/60
Model trained in 1.43s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.672
  Epoch 19/60
Model trained in 1.43s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.882
  Epoch 20/60
Model trained in 1.48s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.513
  Epoch 21/60
Model trained in 1.35s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.069
  Epoch 22/60
Model trained in 1.38s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.751
  Epoch 23/60
Model trained in 1.49s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.846
  Epoch 24/60
Model trained in 1.40s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.168
  Epoch 25/60
Model trained in 1.42s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.360
  Epoch 26/60
Model trained in 1.39s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.453
  Epoch 27/60
Model trained in 1.51s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.940
  Epoch 28/60
Model trained in 1.46s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.672
  Epoch 29/60
Model trained in 1.47s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.954
  Epoch 30/60
Model trained in 1.43s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.843
  Epoch 31/60
Model trained in 1.50s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.905
  Epoch 32/60
Model trained in 1.42s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.835
  Epoch 33/60
Model trained in 1.41s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.773
  Epoch 34/60
Model trained in 1.50s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.701
  Epoch 35/60
Model trained in 1.53s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.140
  Epoch 36/60
Model trained in 1.58s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.445
  Epoch 37/60
Model trained in 1.55s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.906
  Epoch 38/60
Model trained in 1.48s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.592
  Epoch 39/60
Model trained in 1.43s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.346
  Epoch 40/60
Model trained in 1.37s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.541
  Epoch 41/60
Model trained in 1.38s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.786
  Epoch 42/60
Model trained in 1.28s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.621
  Early stopping triggered.

  best_val_SMAPE=77.751

Combination 836/1152: {'encoder_hidden_size': 48, 'encoder_layers': 1, 'encoder_dropout': 0.0, 'decoder_hidden_size': 48, 'decoder_layers': 1, 'decoder_dropout': 0.0, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 20, 'batch_size': 64, 'sequence_length': 168}
Time: 187.28 minutes - estimated total time: 258.06 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 1.56s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 173.190
  Epoch 2/60
Model trained in 1.58s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 160.425
  Epoch 3/60
Model trained in 1.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 150.178
  Epoch 4/60
Model trained in 1.57s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 141.459
  Epoch 5/60
Model trained in 1.59s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 134.178
  Epoch 6/60
Model trained in 1.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 126.853
  Epoch 7/60
Model trained in 1.65s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 120.342
  Epoch 8/60
Model trained in 1.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 114.670
  Epoch 9/60
Model trained in 1.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 109.695
  Epoch 10/60
Model trained in 1.60s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 104.582
  Epoch 11/60
Model trained in 1.51s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 100.057
  Epoch 12/60
Model trained in 1.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 96.099
  Epoch 13/60
Model trained in 1.56s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.368
  Epoch 14/60
Model trained in 1.61s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.221
  Epoch 15/60
Model trained in 1.52s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.105
  Epoch 16/60
Model trained in 1.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.809
  Epoch 17/60
Model trained in 1.50s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.300
  Epoch 18/60
Model trained in 1.45s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.012
  Epoch 19/60
Model trained in 1.57s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.149
  Epoch 20/60
Model trained in 1.63s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.893
  Epoch 21/60
Model trained in 1.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.351
  Epoch 22/60
Model trained in 1.57s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.667
  Epoch 23/60
Model trained in 1.51s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.365
  Epoch 24/60
Model trained in 1.67s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.958
  Epoch 25/60
Model trained in 1.59s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.450
  Epoch 26/60
Model trained in 1.41s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.512
  Epoch 27/60
Model trained in 1.57s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.123
  Epoch 28/60
Model trained in 1.62s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.437
  Epoch 29/60
Model trained in 1.56s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.070
  Epoch 30/60
Model trained in 1.68s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.811
  Epoch 31/60
Model trained in 1.61s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 94.577
  Epoch 32/60
Model trained in 1.61s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 97.689
  Epoch 33/60
Model trained in 1.57s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 101.336
  Epoch 34/60
Model trained in 1.59s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 99.869
  Epoch 35/60
Model trained in 1.53s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 98.000
  Epoch 36/60
Model trained in 1.61s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 101.345
  Epoch 37/60
Model trained in 1.57s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 102.877
  Epoch 38/60
Model trained in 1.53s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 104.836
  Epoch 39/60
Model trained in 1.57s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 104.017
  Epoch 40/60
Model trained in 1.67s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 100.890
  Epoch 41/60
Model trained in 1.58s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 98.635
  Early stopping triggered.

  best_val_SMAPE=76.351

Combination 837/1152: {'encoder_hidden_size': 48, 'encoder_layers': 1, 'encoder_dropout': 0.0, 'decoder_hidden_size': 48, 'decoder_layers': 1, 'decoder_dropout': 0.0, 'learning_rate': 0.0005, 'max_epochs': 60, 'patience': 20, 'batch_size': 32, 'sequence_length': 24}
Time: 188.71 minutes - estimated total time: 259.73 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 2.23s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 173.147
  Epoch 2/60
Model trained in 2.26s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 160.507
  Epoch 3/60
Model trained in 2.18s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 150.316
  Epoch 4/60
Model trained in 2.28s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 141.587
  Epoch 5/60
Model trained in 2.25s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 133.820
  Epoch 6/60
Model trained in 2.28s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 126.802
  Epoch 7/60
Model trained in 2.22s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 120.270
  Epoch 8/60
Model trained in 2.15s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 114.336
  Epoch 9/60
Model trained in 2.05s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 108.617
  Epoch 10/60
Model trained in 2.21s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 104.236
  Epoch 11/60
Model trained in 2.07s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 99.586
  Epoch 12/60
Model trained in 2.28s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 95.702
  Epoch 13/60
Model trained in 2.38s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.188
  Epoch 14/60
Model trained in 2.23s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.682
  Epoch 15/60
Model trained in 2.22s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.094
  Epoch 16/60
Model trained in 2.31s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.595
  Epoch 17/60
Model trained in 2.23s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.652
  Epoch 18/60
Model trained in 2.25s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.499
  Epoch 19/60
Model trained in 2.23s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.395
  Epoch 20/60
Model trained in 2.35s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.606
  Epoch 21/60
Model trained in 2.15s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.814
  Epoch 22/60
Model trained in 2.28s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.271
  Epoch 23/60
Model trained in 2.24s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.685
  Epoch 24/60
Model trained in 2.17s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.217
  Epoch 25/60
Model trained in 2.32s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.394
  Epoch 26/60
Model trained in 2.20s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.760
  Epoch 27/60
Model trained in 2.30s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.394
  Epoch 28/60
Model trained in 2.30s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.529
  Epoch 29/60
Model trained in 2.28s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.564
  Epoch 30/60
Model trained in 2.23s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.102
  Epoch 31/60
Model trained in 2.17s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 96.408
  Epoch 32/60
Model trained in 2.25s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 95.289
  Epoch 33/60
Model trained in 2.11s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.241
  Epoch 34/60
Model trained in 2.34s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.901
  Epoch 35/60
Model trained in 2.16s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.286
  Epoch 36/60
Model trained in 2.13s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.426
  Epoch 37/60
Model trained in 2.24s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.200
  Epoch 38/60
Model trained in 2.18s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.284
  Epoch 39/60
Model trained in 2.11s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.918
  Epoch 40/60
Model trained in 2.22s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.440
  Epoch 41/60
Model trained in 2.13s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.334
  Early stopping triggered.

  best_val_SMAPE=77.814

Combination 838/1152: {'encoder_hidden_size': 48, 'encoder_layers': 1, 'encoder_dropout': 0.0, 'decoder_hidden_size': 48, 'decoder_layers': 1, 'decoder_dropout': 0.0, 'learning_rate': 0.0005, 'max_epochs': 60, 'patience': 20, 'batch_size': 32, 'sequence_length': 168}
Time: 190.58 minutes - estimated total time: 261.99 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 2.34s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 173.248
  Epoch 2/60
Model trained in 2.29s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 160.661
  Epoch 3/60
Model trained in 2.28s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 150.519
  Epoch 4/60
Model trained in 2.51s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 141.743
  Epoch 5/60
Model trained in 2.29s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 134.208
  Epoch 6/60
Model trained in 2.24s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 127.088
  Epoch 7/60
Model trained in 2.44s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 120.558
  Epoch 8/60
Model trained in 2.34s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 114.330
  Epoch 9/60
Model trained in 2.36s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 109.127
  Epoch 10/60
Model trained in 2.34s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 104.377
  Epoch 11/60
Model trained in 2.35s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 99.491
  Epoch 12/60
Model trained in 2.21s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 95.068
  Epoch 13/60
Model trained in 2.20s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.363
  Epoch 14/60
Model trained in 2.16s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.138
  Epoch 15/60
Model trained in 2.30s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.267
  Epoch 16/60
Model trained in 2.30s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.886
  Epoch 17/60
Model trained in 2.33s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.861
  Epoch 18/60
Model trained in 2.24s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.086
  Epoch 19/60
Model trained in 2.15s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.681
  Epoch 20/60
Model trained in 2.25s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.620
  Epoch 21/60
Model trained in 2.21s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.230
  Epoch 22/60
Model trained in 2.33s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.787
  Epoch 23/60
Model trained in 2.23s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.207
  Epoch 24/60
Model trained in 2.29s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.785
  Epoch 25/60
Model trained in 2.17s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.102
  Epoch 26/60
Model trained in 2.19s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.065
  Epoch 27/60
Model trained in 2.29s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.882
  Epoch 28/60
Model trained in 2.20s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.400
  Epoch 29/60
Model trained in 2.12s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.196
  Epoch 30/60
Model trained in 2.11s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.194
  Epoch 31/60
Model trained in 2.11s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.270
  Epoch 32/60
Model trained in 2.18s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.695
  Epoch 33/60
Model trained in 2.20s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.013
  Epoch 34/60
Model trained in 2.23s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.853
  Epoch 35/60
Model trained in 2.29s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.454
  Epoch 36/60
Model trained in 2.27s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.010
  Epoch 37/60
Model trained in 2.29s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.296
  Epoch 38/60
Model trained in 2.43s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.220
  Epoch 39/60
Model trained in 2.37s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.421
  Epoch 40/60
Model trained in 2.38s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.162
  Epoch 41/60
Model trained in 2.46s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.253
  Epoch 42/60
Model trained in 2.40s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.872
  Early stopping triggered.

  best_val_SMAPE=78.787

Combination 839/1152: {'encoder_hidden_size': 48, 'encoder_layers': 1, 'encoder_dropout': 0.0, 'decoder_hidden_size': 48, 'decoder_layers': 1, 'decoder_dropout': 0.0, 'learning_rate': 0.0005, 'max_epochs': 60, 'patience': 20, 'batch_size': 64, 'sequence_length': 24}
Time: 192.52 minutes - estimated total time: 264.34 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 1.39s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 181.046
  Epoch 2/60
Model trained in 1.49s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 173.009
  Epoch 3/60
Model trained in 1.43s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 166.312
  Epoch 4/60
Model trained in 1.37s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 160.340
  Epoch 5/60
Model trained in 1.36s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 155.011
  Epoch 6/60
Model trained in 1.45s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 150.138
  Epoch 7/60
Model trained in 1.37s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 145.601
  Epoch 8/60
Model trained in 1.53s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 141.425
  Epoch 9/60
Model trained in 1.60s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 137.611
  Epoch 10/60
Model trained in 1.54s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 133.793
  Epoch 11/60
Model trained in 1.48s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 130.149
  Epoch 12/60
Model trained in 1.52s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 126.590
  Epoch 13/60
Model trained in 1.38s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 123.219
  Epoch 14/60
Model trained in 1.46s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 119.997
  Epoch 15/60
Model trained in 1.43s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 116.953
  Epoch 16/60
Model trained in 1.44s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 114.036
  Epoch 17/60
Model trained in 1.50s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 111.780
  Epoch 18/60
Model trained in 1.39s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 108.793
  Epoch 19/60
Model trained in 1.43s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 106.269
  Epoch 20/60
Model trained in 1.33s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 103.857
  Epoch 21/60
Model trained in 1.29s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 101.648
  Epoch 22/60
Model trained in 1.39s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 99.489
  Epoch 23/60
Model trained in 1.31s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 97.660
  Epoch 24/60
Model trained in 1.40s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 95.845
  Epoch 25/60
Model trained in 1.38s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 94.402
  Epoch 26/60
Model trained in 1.36s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.660
  Epoch 27/60
Model trained in 1.34s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.185
  Epoch 28/60
Model trained in 1.36s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.178
  Epoch 29/60
Model trained in 1.49s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.985
  Epoch 30/60
Model trained in 1.35s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.769
  Epoch 31/60
Model trained in 1.34s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.505
  Epoch 32/60
Model trained in 1.30s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.028
  Epoch 33/60
Model trained in 1.36s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.700
  Epoch 34/60
Model trained in 1.31s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.975
  Epoch 35/60
Model trained in 1.34s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.702
  Epoch 36/60
Model trained in 1.31s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.324
  Epoch 37/60
Model trained in 1.32s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.826
  Epoch 38/60
Model trained in 1.37s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.810
  Epoch 39/60
Model trained in 1.38s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.052
  Epoch 40/60
Model trained in 1.35s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.797
  Epoch 41/60
Model trained in 1.33s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.560
  Epoch 42/60
Model trained in 1.32s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.556
  Epoch 43/60
Model trained in 1.34s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.732
  Epoch 44/60
Model trained in 1.30s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.797
  Epoch 45/60
Model trained in 1.33s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.449
  Epoch 46/60
Model trained in 1.34s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.311
  Epoch 47/60
Model trained in 1.38s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.486
  Epoch 48/60
Model trained in 1.47s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.824
  Epoch 49/60
Model trained in 1.41s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.898
  Epoch 50/60
Model trained in 1.41s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.712
  Epoch 51/60
Model trained in 1.45s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.243
  Epoch 52/60
Model trained in 1.44s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.028
  Epoch 53/60
Model trained in 1.45s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.460
  Epoch 54/60
Model trained in 1.42s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.471
  Epoch 55/60
Model trained in 1.44s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 101.880
  Epoch 56/60
Model trained in 1.42s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 101.676
  Epoch 57/60
Model trained in 1.39s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 110.094
  Epoch 58/60
Model trained in 1.43s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 110.171
  Epoch 59/60
Model trained in 1.44s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 109.790
  Epoch 60/60
Model trained in 1.41s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 115.759

  best_val_SMAPE=84.311

Combination 840/1152: {'encoder_hidden_size': 48, 'encoder_layers': 1, 'encoder_dropout': 0.0, 'decoder_hidden_size': 48, 'decoder_layers': 1, 'decoder_dropout': 0.0, 'learning_rate': 0.0005, 'max_epochs': 60, 'patience': 20, 'batch_size': 64, 'sequence_length': 168}
Time: 194.39 minutes - estimated total time: 266.59 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 1.63s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 181.146
  Epoch 2/60
Model trained in 1.59s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 173.148
  Epoch 3/60
Model trained in 1.54s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 166.484
  Epoch 4/60
Model trained in 1.56s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 160.540
  Epoch 5/60
Model trained in 1.58s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 155.220
  Epoch 6/60
Model trained in 1.60s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 150.372
  Epoch 7/60
Model trained in 1.63s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 145.859
  Epoch 8/60
Model trained in 1.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 141.751
  Epoch 9/60
Model trained in 1.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 137.926
  Epoch 10/60
Model trained in 1.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 134.156
  Epoch 11/60
Model trained in 1.56s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 130.412
  Epoch 12/60
Model trained in 1.61s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 126.902
  Epoch 13/60
Model trained in 1.60s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 123.707
  Epoch 14/60
Model trained in 1.59s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 120.444
  Epoch 15/60
Model trained in 1.59s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 117.451
  Epoch 16/60
Model trained in 1.62s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 114.649
  Epoch 17/60
Model trained in 1.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 111.872
  Epoch 18/60
Model trained in 1.67s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 109.437
  Epoch 19/60
Model trained in 1.58s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 107.113
  Epoch 20/60
Model trained in 1.50s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 105.211
  Epoch 21/60
Model trained in 1.52s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 102.589
  Epoch 22/60
Model trained in 1.48s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 100.802
  Epoch 23/60
Model trained in 1.44s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 102.937
  Epoch 24/60
Model trained in 1.59s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 97.923
  Epoch 25/60
Model trained in 1.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 96.427
  Epoch 26/60
Model trained in 1.52s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 95.266
  Epoch 27/60
Model trained in 1.61s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 94.658
  Epoch 28/60
Model trained in 1.55s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 94.231
  Epoch 29/60
Model trained in 1.56s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.971
  Epoch 30/60
Model trained in 1.54s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.263
  Epoch 31/60
Model trained in 1.53s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.259
  Epoch 32/60
Model trained in 1.55s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.107
  Epoch 33/60
Model trained in 1.54s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.812
  Epoch 34/60
Model trained in 1.57s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.395
  Epoch 35/60
Model trained in 1.55s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.649
  Epoch 36/60
Model trained in 1.54s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.793
  Epoch 37/60
Model trained in 1.54s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.612
  Epoch 38/60
Model trained in 1.47s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.759
  Epoch 39/60
Model trained in 1.55s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.270
  Epoch 40/60
Model trained in 1.52s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.745
  Epoch 41/60
Model trained in 1.45s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.457
  Epoch 42/60
Model trained in 1.41s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.755
  Epoch 43/60
Model trained in 1.43s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.256
  Epoch 44/60
Model trained in 1.43s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.105
  Epoch 45/60
Model trained in 1.59s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.060
  Epoch 46/60
Model trained in 1.56s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.584
  Epoch 47/60
Model trained in 1.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.587
  Epoch 48/60
Model trained in 1.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.275
  Epoch 49/60
Model trained in 1.60s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.322
  Epoch 50/60
Model trained in 1.54s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.392
  Epoch 51/60
Model trained in 1.49s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.290
  Epoch 52/60
Model trained in 1.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.222
  Epoch 53/60
Model trained in 1.65s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.810
  Epoch 54/60
Model trained in 1.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.950
  Epoch 55/60
Model trained in 1.53s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.748
  Epoch 56/60
Model trained in 1.49s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 94.142
  Epoch 57/60
Model trained in 1.56s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 95.409
  Epoch 58/60
Model trained in 1.52s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 95.962
  Early stopping triggered.

  best_val_SMAPE=87.759

Combination 849/1152: {'encoder_hidden_size': 48, 'encoder_layers': 1, 'encoder_dropout': 0.0, 'decoder_hidden_size': 48, 'decoder_layers': 2, 'decoder_dropout': 0.0, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 20, 'batch_size': 32, 'sequence_length': 24}
Time: 196.37 minutes - estimated total time: 266.46 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 2.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 161.249
  Epoch 2/60
Model trained in 2.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 141.985
  Epoch 3/60
Model trained in 2.56s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 126.703
  Epoch 4/60
Model trained in 2.68s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 116.743
  Epoch 5/60
Model trained in 2.67s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 106.877
  Epoch 6/60
Model trained in 2.61s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 98.778
  Epoch 7/60
Model trained in 2.53s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.632
  Epoch 8/60
Model trained in 2.58s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.591
  Epoch 9/60
Model trained in 2.51s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.343
  Epoch 10/60
Model trained in 2.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.834
  Epoch 11/60
Model trained in 2.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.251
  Epoch 12/60
Model trained in 2.67s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.494
  Epoch 13/60
Model trained in 2.48s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.024
  Epoch 14/60
Model trained in 2.53s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.297
  Epoch 15/60
Model trained in 2.52s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.951
  Epoch 16/60
Model trained in 2.55s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.776
  Epoch 17/60
Model trained in 2.51s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.671
  Epoch 18/60
Model trained in 2.52s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.646
  Epoch 19/60
Model trained in 2.55s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.458
  Epoch 20/60
Model trained in 2.51s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.104
  Epoch 21/60
Model trained in 2.52s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.514
  Epoch 22/60
Model trained in 2.58s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.278
  Epoch 23/60
Model trained in 2.65s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.845
  Epoch 24/60
Model trained in 2.51s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.745
  Epoch 25/60
Model trained in 2.59s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.924
  Epoch 26/60
Model trained in 2.51s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.471
  Epoch 27/60
Model trained in 2.46s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.958
  Epoch 28/60
Model trained in 2.52s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.080
  Epoch 29/60
Model trained in 2.55s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.574
  Epoch 30/60
Model trained in 2.57s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.111
  Early stopping triggered.

  best_val_SMAPE=81.834

Combination 850/1152: {'encoder_hidden_size': 48, 'encoder_layers': 1, 'encoder_dropout': 0.0, 'decoder_hidden_size': 48, 'decoder_layers': 2, 'decoder_dropout': 0.0, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 20, 'batch_size': 32, 'sequence_length': 168}
Time: 197.92 minutes - estimated total time: 268.23 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 2.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 161.331
  Epoch 2/60
Model trained in 2.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 142.159
  Epoch 3/60
Model trained in 2.67s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 126.929
  Epoch 4/60
Model trained in 2.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 113.828
  Epoch 5/60
Model trained in 2.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 105.816
  Epoch 6/60
Model trained in 2.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 98.731
  Epoch 7/60
Model trained in 2.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.366
  Epoch 8/60
Model trained in 2.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.766
  Epoch 9/60
Model trained in 2.58s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.096
  Epoch 10/60
Model trained in 2.67s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.702
  Epoch 11/60
Model trained in 2.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.030
  Epoch 12/60
Model trained in 2.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.157
  Epoch 13/60
Model trained in 2.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.362
  Epoch 14/60
Model trained in 2.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.953
  Epoch 15/60
Model trained in 2.65s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.965
  Epoch 16/60
Model trained in 2.67s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.376
  Epoch 17/60
Model trained in 2.63s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.385
  Epoch 18/60
Model trained in 2.61s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.075
  Epoch 19/60
Model trained in 2.60s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.012
  Epoch 20/60
Model trained in 2.61s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.080
  Epoch 21/60
Model trained in 2.57s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.694
  Epoch 22/60
Model trained in 2.65s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.322
  Epoch 23/60
Model trained in 2.63s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.167
  Epoch 24/60
Model trained in 2.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.498
  Epoch 25/60
Model trained in 2.53s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.616
  Epoch 26/60
Model trained in 2.65s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.846
  Epoch 27/60
Model trained in 2.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.937
  Epoch 28/60
Model trained in 2.62s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.251
  Epoch 29/60
Model trained in 2.60s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.653
  Epoch 30/60
Model trained in 2.59s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.370
  Epoch 31/60
Model trained in 2.68s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.371
  Epoch 32/60
Model trained in 2.63s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.602
  Epoch 33/60
Model trained in 2.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.089
  Epoch 34/60
Model trained in 2.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.514
  Epoch 35/60
Model trained in 2.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.220
  Epoch 36/60
Model trained in 2.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.185
  Epoch 37/60
Model trained in 2.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.930
  Epoch 38/60
Model trained in 2.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.842
  Early stopping triggered.

  best_val_SMAPE=78.075

Combination 851/1152: {'encoder_hidden_size': 48, 'encoder_layers': 1, 'encoder_dropout': 0.0, 'decoder_hidden_size': 48, 'decoder_layers': 2, 'decoder_dropout': 0.0, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 20, 'batch_size': 64, 'sequence_length': 24}
Time: 199.93 minutes - estimated total time: 270.65 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 1.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 173.718
  Epoch 2/60
Model trained in 1.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 160.951
  Epoch 3/60
Model trained in 1.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 150.603
  Epoch 4/60
Model trained in 1.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 141.686
  Epoch 5/60
Model trained in 1.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 133.748
  Epoch 6/60
Model trained in 1.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 126.352
  Epoch 7/60
Model trained in 1.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 119.553
  Epoch 8/60
Model trained in 1.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 113.251
  Epoch 9/60
Model trained in 1.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 107.730
  Epoch 10/60
Model trained in 1.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 106.210
  Epoch 11/60
Model trained in 1.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 103.582
  Epoch 12/60
Model trained in 1.63s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 99.095
  Epoch 13/60
Model trained in 1.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 95.714
  Epoch 14/60
Model trained in 1.67s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.806
  Epoch 15/60
Model trained in 1.62s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.699
  Epoch 16/60
Model trained in 1.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.189
  Epoch 17/60
Model trained in 1.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.038
  Epoch 18/60
Model trained in 1.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.985
  Epoch 19/60
Model trained in 1.60s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.254
  Epoch 20/60
Model trained in 1.59s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.058
  Epoch 21/60
Model trained in 1.60s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.789
  Epoch 22/60
Model trained in 1.59s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.576
  Epoch 23/60
Model trained in 1.63s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.831
  Epoch 24/60
Model trained in 1.63s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.585
  Epoch 25/60
Model trained in 1.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.774
  Epoch 26/60
Model trained in 1.62s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.363
  Epoch 27/60
Model trained in 1.63s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.919
  Epoch 28/60
Model trained in 1.62s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.879
  Epoch 29/60
Model trained in 1.62s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.237
  Epoch 30/60
Model trained in 1.61s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.244
  Epoch 31/60
Model trained in 1.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.538
  Epoch 32/60
Model trained in 1.60s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.780
  Epoch 33/60
Model trained in 1.62s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.207
  Epoch 34/60
Model trained in 1.59s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.702
  Epoch 35/60
Model trained in 1.65s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.038
  Epoch 36/60
Model trained in 1.62s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.219
  Epoch 37/60
Model trained in 1.61s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.885
  Epoch 38/60
Model trained in 1.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.255
  Epoch 39/60
Model trained in 1.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.241
  Epoch 40/60
Model trained in 1.63s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.453
  Epoch 41/60
Model trained in 1.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.315
  Epoch 42/60
Model trained in 1.63s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.153
  Early stopping triggered.

  best_val_SMAPE=80.576

Combination 852/1152: {'encoder_hidden_size': 48, 'encoder_layers': 1, 'encoder_dropout': 0.0, 'decoder_hidden_size': 48, 'decoder_layers': 2, 'decoder_dropout': 0.0, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 20, 'batch_size': 64, 'sequence_length': 168}
Time: 201.45 minutes - estimated total time: 272.38 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 1.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 173.827
  Epoch 2/60
Model trained in 1.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 161.133
  Epoch 3/60
Model trained in 1.68s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 150.822
  Epoch 4/60
Model trained in 1.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 141.940
  Epoch 5/60
Model trained in 1.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 134.041
  Epoch 6/60
Model trained in 1.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 126.680
  Epoch 7/60
Model trained in 1.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 119.868
  Epoch 8/60
Model trained in 1.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 113.653
  Epoch 9/60
Model trained in 1.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 108.030
  Epoch 10/60
Model trained in 1.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 106.772
  Epoch 11/60
Model trained in 1.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 102.999
  Epoch 12/60
Model trained in 1.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 98.395
  Epoch 13/60
Model trained in 1.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 94.482
  Epoch 14/60
Model trained in 1.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.155
  Epoch 15/60
Model trained in 1.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.719
  Epoch 16/60
Model trained in 1.68s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.432
  Epoch 17/60
Model trained in 1.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.737
  Epoch 18/60
Model trained in 1.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.529
  Epoch 19/60
Model trained in 1.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.484
  Epoch 20/60
Model trained in 1.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.390
  Epoch 21/60
Model trained in 1.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.633
  Epoch 22/60
Model trained in 1.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.338
  Epoch 23/60
Model trained in 1.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.275
  Epoch 24/60
Model trained in 1.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.033
  Epoch 25/60
Model trained in 1.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.929
  Epoch 26/60
Model trained in 1.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.395
  Epoch 27/60
Model trained in 1.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.145
  Epoch 28/60
Model trained in 1.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.405
  Epoch 29/60
Model trained in 1.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.814
  Epoch 30/60
Model trained in 1.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.137
  Epoch 31/60
Model trained in 1.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.382
  Epoch 32/60
Model trained in 1.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.380
  Epoch 33/60
Model trained in 1.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.769
  Epoch 34/60
Model trained in 1.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.305
  Epoch 35/60
Model trained in 1.67s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.807
  Epoch 36/60
Model trained in 1.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.400
  Epoch 37/60
Model trained in 1.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.375
  Epoch 38/60
Model trained in 1.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 72.678
  Epoch 39/60
Model trained in 1.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 72.969
  Epoch 40/60
Model trained in 1.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 72.999
  Epoch 41/60
Model trained in 1.99s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 72.367
  Epoch 42/60
Model trained in 1.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 71.905
  Epoch 43/60
Model trained in 1.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 72.308
  Epoch 44/60
Model trained in 1.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 72.939
  Epoch 45/60
Model trained in 1.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.625
  Epoch 46/60
Model trained in 1.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.174
  Epoch 47/60
Model trained in 1.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.103
  Epoch 48/60
Model trained in 1.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.022
  Epoch 49/60
Model trained in 1.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.994
  Epoch 50/60
Model trained in 1.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.614
  Epoch 51/60
Model trained in 1.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.234
  Epoch 52/60
Model trained in 1.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.486
  Epoch 53/60
Model trained in 1.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.987
  Epoch 54/60
Model trained in 1.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.975
  Epoch 55/60
Model trained in 2.00s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.958
  Epoch 56/60
Model trained in 1.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.703
  Epoch 57/60
Model trained in 1.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.714
  Epoch 58/60
Model trained in 1.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.841
  Epoch 59/60
Model trained in 1.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.923
  Epoch 60/60
Model trained in 1.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.130

  best_val_SMAPE=71.905

Combination 853/1152: {'encoder_hidden_size': 48, 'encoder_layers': 1, 'encoder_dropout': 0.0, 'decoder_hidden_size': 48, 'decoder_layers': 2, 'decoder_dropout': 0.0, 'learning_rate': 0.0005, 'max_epochs': 60, 'patience': 20, 'batch_size': 32, 'sequence_length': 24}
Time: 203.72 minutes - estimated total time: 275.12 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 2.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 173.744
  Epoch 2/60
Model trained in 2.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 161.118
  Epoch 3/60
Model trained in 2.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 150.826
  Epoch 4/60
Model trained in 2.65s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 141.932
  Epoch 5/60
Model trained in 2.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 133.986
  Epoch 6/60
Model trained in 2.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 127.664
  Epoch 7/60
Model trained in 2.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 121.995
  Epoch 8/60
Model trained in 2.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 115.729
  Epoch 9/60
Model trained in 2.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 110.630
  Epoch 10/60
Model trained in 2.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 105.351
  Epoch 11/60
Model trained in 2.68s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 100.273
  Epoch 12/60
Model trained in 2.65s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 96.157
  Epoch 13/60
Model trained in 2.61s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.429
  Epoch 14/60
Model trained in 2.59s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.218
  Epoch 15/60
Model trained in 2.65s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.610
  Epoch 16/60
Model trained in 2.68s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.627
  Epoch 17/60
Model trained in 2.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.268
  Epoch 18/60
Model trained in 2.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.751
  Epoch 19/60
Model trained in 2.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.475
  Epoch 20/60
Model trained in 2.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.710
  Epoch 21/60
Model trained in 2.63s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.580
  Epoch 22/60
Model trained in 2.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.236
  Epoch 23/60
Model trained in 2.60s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.128
  Epoch 24/60
Model trained in 2.65s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.768
  Epoch 25/60
Model trained in 2.65s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.437
  Epoch 26/60
Model trained in 2.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.471
  Epoch 27/60
Model trained in 2.67s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.303
  Epoch 28/60
Model trained in 2.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.672
  Epoch 29/60
Model trained in 2.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.409
  Epoch 30/60
Model trained in 2.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.038
  Epoch 31/60
Model trained in 2.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.004
  Epoch 32/60
Model trained in 2.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.735
  Epoch 33/60
Model trained in 2.65s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.132
  Epoch 34/60
Model trained in 2.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.280
  Epoch 35/60
Model trained in 2.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.161
  Epoch 36/60
Model trained in 2.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.992
  Epoch 37/60
Model trained in 2.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.746
  Epoch 38/60
Model trained in 2.67s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.778
  Epoch 39/60
Model trained in 2.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.387
  Epoch 40/60
Model trained in 2.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.474
  Epoch 41/60
Model trained in 2.63s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.214
  Epoch 42/60
Model trained in 2.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.160
  Epoch 43/60
Model trained in 2.65s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.007
  Epoch 44/60
Model trained in 2.62s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.769
  Epoch 45/60
Model trained in 2.65s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.314
  Early stopping triggered.

  best_val_SMAPE=73.437

Combination 854/1152: {'encoder_hidden_size': 48, 'encoder_layers': 1, 'encoder_dropout': 0.0, 'decoder_hidden_size': 48, 'decoder_layers': 2, 'decoder_dropout': 0.0, 'learning_rate': 0.0005, 'max_epochs': 60, 'patience': 20, 'batch_size': 32, 'sequence_length': 168}
Time: 206.10 minutes - estimated total time: 278.02 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 2.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 173.840
  Epoch 2/60
Model trained in 2.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 161.290
  Epoch 3/60
Model trained in 2.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 151.029
  Epoch 4/60
Model trained in 2.99s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 142.159
  Epoch 5/60
Model trained in 2.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 134.239
  Epoch 6/60
Model trained in 2.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 126.831
  Epoch 7/60
Model trained in 2.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 120.135
  Epoch 8/60
Model trained in 2.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 115.674
  Epoch 9/60
Model trained in 2.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 110.472
  Epoch 10/60
Model trained in 2.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 106.128
  Epoch 11/60
Model trained in 2.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 102.208
  Epoch 12/60
Model trained in 2.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 97.843
  Epoch 13/60
Model trained in 2.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.967
  Epoch 14/60
Model trained in 2.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.019
  Epoch 15/60
Model trained in 2.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.719
  Epoch 16/60
Model trained in 2.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.205
  Epoch 17/60
Model trained in 2.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.816
  Epoch 18/60
Model trained in 2.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.596
  Epoch 19/60
Model trained in 2.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.428
  Epoch 20/60
Model trained in 2.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.567
  Epoch 21/60
Model trained in 2.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.654
  Epoch 22/60
Model trained in 2.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.012
  Epoch 23/60
Model trained in 2.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.594
  Epoch 24/60
Model trained in 2.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.223
  Epoch 25/60
Model trained in 2.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.338
  Epoch 26/60
Model trained in 2.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.981
  Epoch 27/60
Model trained in 2.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.867
  Epoch 28/60
Model trained in 2.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.918
  Epoch 29/60
Model trained in 2.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.118
  Epoch 30/60
Model trained in 2.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.051
  Epoch 31/60
Model trained in 2.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.020
  Epoch 32/60
Model trained in 2.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.229
  Epoch 33/60
Model trained in 2.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.228
  Epoch 34/60
Model trained in 2.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.372
  Epoch 35/60
Model trained in 2.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.199
  Epoch 36/60
Model trained in 2.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.768
  Epoch 37/60
Model trained in 2.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.756
  Epoch 38/60
Model trained in 2.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.022
  Epoch 39/60
Model trained in 2.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.439
  Epoch 40/60
Model trained in 2.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.994
  Epoch 41/60
Model trained in 2.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.198
  Early stopping triggered.

  best_val_SMAPE=77.654

Combination 855/1152: {'encoder_hidden_size': 48, 'encoder_layers': 1, 'encoder_dropout': 0.0, 'decoder_hidden_size': 48, 'decoder_layers': 2, 'decoder_dropout': 0.0, 'learning_rate': 0.0005, 'max_epochs': 60, 'patience': 20, 'batch_size': 64, 'sequence_length': 24}
Time: 208.36 minutes - estimated total time: 280.74 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 1.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 181.499
  Epoch 2/60
Model trained in 1.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 173.600
  Epoch 3/60
Model trained in 1.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 166.929
  Epoch 4/60
Model trained in 1.62s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 160.953
  Epoch 5/60
Model trained in 1.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 155.581
  Epoch 6/60
Model trained in 1.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 150.639
  Epoch 7/60
Model trained in 1.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 146.042
  Epoch 8/60
Model trained in 1.63s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 141.713
  Epoch 9/60
Model trained in 1.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 137.628
  Epoch 10/60
Model trained in 1.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 133.722
  Epoch 11/60
Model trained in 1.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 129.947
  Epoch 12/60
Model trained in 1.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 127.542
  Epoch 13/60
Model trained in 1.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 123.800
  Epoch 14/60
Model trained in 1.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 120.517
  Epoch 15/60
Model trained in 1.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 117.769
  Epoch 16/60
Model trained in 1.60s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 115.129
  Epoch 17/60
Model trained in 1.61s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 112.399
  Epoch 18/60
Model trained in 1.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 109.756
  Epoch 19/60
Model trained in 1.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 107.456
  Epoch 20/60
Model trained in 1.68s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 105.176
  Epoch 21/60
Model trained in 1.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 103.312
  Epoch 22/60
Model trained in 1.65s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 101.180
  Epoch 23/60
Model trained in 1.62s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 99.108
  Epoch 24/60
Model trained in 1.62s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 96.894
  Epoch 25/60
Model trained in 1.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 94.946
  Epoch 26/60
Model trained in 1.67s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.908
  Epoch 27/60
Model trained in 1.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.543
  Epoch 28/60
Model trained in 1.63s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.094
  Epoch 29/60
Model trained in 1.63s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.621
  Epoch 30/60
Model trained in 1.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.039
  Epoch 31/60
Model trained in 1.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.215
  Epoch 32/60
Model trained in 1.68s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.026
  Epoch 33/60
Model trained in 1.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.709
  Epoch 34/60
Model trained in 1.68s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.555
  Epoch 35/60
Model trained in 1.67s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.872
  Epoch 36/60
Model trained in 1.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.188
  Epoch 37/60
Model trained in 1.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.451
  Epoch 38/60
Model trained in 1.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.198
  Epoch 39/60
Model trained in 1.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.823
  Epoch 40/60
Model trained in 1.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.254
  Epoch 41/60
Model trained in 1.62s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.700
  Epoch 42/60
Model trained in 1.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.199
  Epoch 43/60
Model trained in 1.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.714
  Epoch 44/60
Model trained in 1.65s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.620
  Epoch 45/60
Model trained in 1.68s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.984
  Epoch 46/60
Model trained in 1.67s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.311
  Epoch 47/60
Model trained in 1.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.552
  Epoch 48/60
Model trained in 1.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.582
  Epoch 49/60
Model trained in 1.63s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.125
  Epoch 50/60
Model trained in 1.65s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.600
  Epoch 51/60
Model trained in 1.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.080
  Epoch 52/60
Model trained in 1.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.371
  Epoch 53/60
Model trained in 1.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.303
  Epoch 54/60
Model trained in 1.65s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.885
  Epoch 55/60
Model trained in 1.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.684
  Epoch 56/60
Model trained in 1.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.627
  Epoch 57/60
Model trained in 1.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.694
  Epoch 58/60
Model trained in 1.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.481
  Epoch 59/60
Model trained in 1.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.478
  Epoch 60/60
Model trained in 1.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.330

  best_val_SMAPE=76.620

Combination 856/1152: {'encoder_hidden_size': 48, 'encoder_layers': 1, 'encoder_dropout': 0.0, 'decoder_hidden_size': 48, 'decoder_layers': 2, 'decoder_dropout': 0.0, 'learning_rate': 0.0005, 'max_epochs': 60, 'patience': 20, 'batch_size': 64, 'sequence_length': 168}
Time: 210.55 minutes - estimated total time: 283.36 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 1.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 181.579
  Epoch 2/60
Model trained in 1.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 173.719
  Epoch 3/60
Model trained in 1.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 167.088
  Epoch 4/60
Model trained in 1.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 161.142
  Epoch 5/60
Model trained in 1.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 155.787
  Epoch 6/60
Model trained in 1.99s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 150.859
  Epoch 7/60
Model trained in 1.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 146.281
  Epoch 8/60
Model trained in 1.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 141.967
  Epoch 9/60
Model trained in 1.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 137.900
  Epoch 10/60
Model trained in 1.95s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 134.026
  Epoch 11/60
Model trained in 1.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 130.209
  Epoch 12/60
Model trained in 1.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 126.973
  Epoch 13/60
Model trained in 1.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 123.032
  Epoch 14/60
Model trained in 1.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 119.667
  Epoch 15/60
Model trained in 1.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 116.470
  Epoch 16/60
Model trained in 1.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 116.145
  Epoch 17/60
Model trained in 1.95s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 112.277
  Epoch 18/60
Model trained in 1.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 109.116
  Epoch 19/60
Model trained in 1.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 106.430
  Epoch 20/60
Model trained in 1.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 104.309
  Epoch 21/60
Model trained in 1.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 101.683
  Epoch 22/60
Model trained in 1.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 98.980
  Epoch 23/60
Model trained in 1.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 96.174
  Epoch 24/60
Model trained in 1.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.916
  Epoch 25/60
Model trained in 1.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.960
  Epoch 26/60
Model trained in 1.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.680
  Epoch 27/60
Model trained in 1.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.906
  Epoch 28/60
Model trained in 1.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.287
  Epoch 29/60
Model trained in 1.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.188
  Epoch 30/60
Model trained in 1.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.851
  Epoch 31/60
Model trained in 1.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.712
  Epoch 32/60
Model trained in 1.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.917
  Epoch 33/60
Model trained in 1.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.861
  Epoch 34/60
Model trained in 1.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.772
  Epoch 35/60
Model trained in 1.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.848
  Epoch 36/60
Model trained in 1.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.531
  Epoch 37/60
Model trained in 1.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.139
  Epoch 38/60
Model trained in 1.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.584
  Epoch 39/60
Model trained in 1.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.093
  Epoch 40/60
Model trained in 1.65s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.650
  Epoch 41/60
Model trained in 1.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.765
  Epoch 42/60
Model trained in 1.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.564
  Epoch 43/60
Model trained in 1.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.965
  Epoch 44/60
Model trained in 1.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.704
  Epoch 45/60
Model trained in 1.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.765
  Epoch 46/60
Model trained in 1.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.992
  Epoch 47/60
Model trained in 1.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.620
  Epoch 48/60
Model trained in 1.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.420
  Epoch 49/60
Model trained in 1.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.644
  Epoch 50/60
Model trained in 1.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.040
  Epoch 51/60
Model trained in 1.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.747
  Epoch 52/60
Model trained in 1.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.496
  Epoch 53/60
Model trained in 1.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.705
  Epoch 54/60
Model trained in 1.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.479
  Epoch 55/60
Model trained in 1.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.688
  Epoch 56/60
Model trained in 1.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.245
  Epoch 57/60
Model trained in 1.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.792
  Epoch 58/60
Model trained in 1.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.209
  Epoch 59/60
Model trained in 1.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.482
  Epoch 60/60
Model trained in 1.67s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.396

  best_val_SMAPE=75.040

Combination 857/1152: {'encoder_hidden_size': 48, 'encoder_layers': 1, 'encoder_dropout': 0.0, 'decoder_hidden_size': 48, 'decoder_layers': 2, 'decoder_dropout': 0.2, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 20, 'batch_size': 32, 'sequence_length': 24}
Time: 212.87 minutes - estimated total time: 286.15 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 2.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 161.243
  Epoch 2/60
Model trained in 2.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 141.980
  Epoch 3/60
Model trained in 2.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 126.689
  Epoch 4/60
Model trained in 2.98s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 118.209
  Epoch 5/60
Model trained in 2.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 108.235
  Epoch 6/60
Model trained in 2.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 100.774
  Epoch 7/60
Model trained in 2.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 94.647
  Epoch 8/60
Model trained in 2.61s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.064
  Epoch 9/60
Model trained in 2.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.946
  Epoch 10/60
Model trained in 2.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.651
  Epoch 11/60
Model trained in 2.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.610
  Epoch 12/60
Model trained in 2.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.296
  Epoch 13/60
Model trained in 2.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.380
  Epoch 14/60
Model trained in 2.63s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.242
  Epoch 15/60
Model trained in 2.61s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.412
  Epoch 16/60
Model trained in 2.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.808
  Epoch 17/60
Model trained in 2.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.006
  Epoch 18/60
Model trained in 2.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.911
  Epoch 19/60
Model trained in 2.63s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.937
  Epoch 20/60
Model trained in 2.52s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.014
  Epoch 21/60
Model trained in 2.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.878
  Epoch 22/60
Model trained in 2.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.581
  Epoch 23/60
Model trained in 2.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.941
  Epoch 24/60
Model trained in 2.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.625
  Epoch 25/60
Model trained in 2.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.443
  Epoch 26/60
Model trained in 2.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.674
  Epoch 27/60
Model trained in 2.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.862
  Epoch 28/60
Model trained in 2.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.856
  Epoch 29/60
Model trained in 2.68s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.441
  Epoch 30/60
Model trained in 2.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.849
  Epoch 31/60
Model trained in 2.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.901
  Epoch 32/60
Model trained in 2.67s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.198
  Epoch 33/60
Model trained in 2.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.791
  Epoch 34/60
Model trained in 2.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.740
  Epoch 35/60
Model trained in 2.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.760
  Epoch 36/60
Model trained in 2.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.218
  Epoch 37/60
Model trained in 2.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.201
  Epoch 38/60
Model trained in 2.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.883
  Epoch 39/60
Model trained in 2.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.083
  Epoch 40/60
Model trained in 2.61s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.064
  Epoch 41/60
Model trained in 2.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.530
  Epoch 42/60
Model trained in 2.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.750
  Epoch 43/60
Model trained in 2.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.312
  Epoch 44/60
Model trained in 2.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.658
  Epoch 45/60
Model trained in 2.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.553
  Epoch 46/60
Model trained in 2.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.727
  Epoch 47/60
Model trained in 2.51s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.911
  Epoch 48/60
Model trained in 2.53s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.959
  Epoch 49/60
Model trained in 2.56s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.285
  Epoch 50/60
Model trained in 2.52s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.261
  Epoch 51/60
Model trained in 2.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.184
  Epoch 52/60
Model trained in 2.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.742
  Epoch 53/60
Model trained in 2.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.127
  Epoch 54/60
Model trained in 2.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.361
  Epoch 55/60
Model trained in 2.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.361
  Epoch 56/60
Model trained in 2.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.170
  Epoch 57/60
Model trained in 2.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.649
  Epoch 58/60
Model trained in 2.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.954
  Epoch 59/60
Model trained in 2.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.740
  Epoch 60/60
Model trained in 2.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.363

  best_val_SMAPE=74.363

Combination 858/1152: {'encoder_hidden_size': 48, 'encoder_layers': 1, 'encoder_dropout': 0.0, 'decoder_hidden_size': 48, 'decoder_layers': 2, 'decoder_dropout': 0.2, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 20, 'batch_size': 32, 'sequence_length': 168}
Time: 216.10 minutes - estimated total time: 290.15 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 3.00s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 161.324
  Epoch 2/60
Model trained in 2.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 142.153
  Epoch 3/60
Model trained in 2.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 126.932
  Epoch 4/60
Model trained in 2.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 113.829
  Epoch 5/60
Model trained in 2.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 108.431
  Epoch 6/60
Model trained in 2.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 99.916
  Epoch 7/60
Model trained in 2.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.507
  Epoch 8/60
Model trained in 2.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.726
  Epoch 9/60
Model trained in 2.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.926
  Epoch 10/60
Model trained in 2.99s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.797
  Epoch 11/60
Model trained in 2.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.408
  Epoch 12/60
Model trained in 2.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.971
  Epoch 13/60
Model trained in 2.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.415
  Epoch 14/60
Model trained in 2.95s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.969
  Epoch 15/60
Model trained in 2.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.586
  Epoch 16/60
Model trained in 2.61s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.970
  Epoch 17/60
Model trained in 2.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.019
  Epoch 18/60
Model trained in 2.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.820
  Epoch 19/60
Model trained in 2.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.347
  Epoch 20/60
Model trained in 2.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.631
  Epoch 21/60
Model trained in 2.67s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.437
  Epoch 22/60
Model trained in 2.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.324
  Epoch 23/60
Model trained in 2.68s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.198
  Epoch 24/60
Model trained in 2.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.435
  Epoch 25/60
Model trained in 2.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.282
  Epoch 26/60
Model trained in 2.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.221
  Epoch 27/60
Model trained in 2.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.476
  Epoch 28/60
Model trained in 2.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.852
  Epoch 29/60
Model trained in 2.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.445
  Epoch 30/60
Model trained in 2.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.544
  Epoch 31/60
Model trained in 2.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.451
  Epoch 32/60
Model trained in 2.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.920
  Epoch 33/60
Model trained in 2.98s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.369
  Early stopping triggered.

  best_val_SMAPE=73.415

Combination 859/1152: {'encoder_hidden_size': 48, 'encoder_layers': 1, 'encoder_dropout': 0.0, 'decoder_hidden_size': 48, 'decoder_layers': 2, 'decoder_dropout': 0.2, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 20, 'batch_size': 64, 'sequence_length': 24}
Time: 217.93 minutes - estimated total time: 292.27 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 1.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 173.705
  Epoch 2/60
Model trained in 1.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 160.941
  Epoch 3/60
Model trained in 1.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 150.594
  Epoch 4/60
Model trained in 1.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 141.679
  Epoch 5/60
Model trained in 1.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 133.742
  Epoch 6/60
Model trained in 1.67s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 126.344
  Epoch 7/60
Model trained in 1.55s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 119.500
  Epoch 8/60
Model trained in 1.61s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 114.438
  Epoch 9/60
Model trained in 1.62s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 109.913
  Epoch 10/60
Model trained in 1.58s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 105.090
  Epoch 11/60
Model trained in 1.60s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 100.553
  Epoch 12/60
Model trained in 1.54s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 95.825
  Epoch 13/60
Model trained in 1.57s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.002
  Epoch 14/60
Model trained in 1.51s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.791
  Epoch 15/60
Model trained in 1.63s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.868
  Epoch 16/60
Model trained in 1.62s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.142
  Epoch 17/60
Model trained in 1.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.467
  Epoch 18/60
Model trained in 1.57s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.022
  Epoch 19/60
Model trained in 1.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.423
  Epoch 20/60
Model trained in 1.56s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.741
  Epoch 21/60
Model trained in 1.61s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.343
  Epoch 22/60
Model trained in 1.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.534
  Epoch 23/60
Model trained in 1.59s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.387
  Epoch 24/60
Model trained in 1.62s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.200
  Epoch 25/60
Model trained in 1.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.580
  Epoch 26/60
Model trained in 1.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.635
  Epoch 27/60
Model trained in 1.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.255
  Epoch 28/60
Model trained in 1.58s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.880
  Epoch 29/60
Model trained in 1.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.524
  Epoch 30/60
Model trained in 1.61s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.598
  Epoch 31/60
Model trained in 1.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.021
  Epoch 32/60
Model trained in 1.68s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.778
  Epoch 33/60
Model trained in 1.63s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.045
  Epoch 34/60
Model trained in 1.68s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.533
  Epoch 35/60
Model trained in 1.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.414
  Epoch 36/60
Model trained in 1.56s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.669
  Epoch 37/60
Model trained in 1.63s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.452
  Epoch 38/60
Model trained in 1.63s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.137
  Epoch 39/60
Model trained in 1.56s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.226
  Epoch 40/60
Model trained in 1.59s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.233
  Epoch 41/60
Model trained in 1.61s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.704
  Epoch 42/60
Model trained in 1.55s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.655
  Early stopping triggered.

  best_val_SMAPE=77.534

Combination 860/1152: {'encoder_hidden_size': 48, 'encoder_layers': 1, 'encoder_dropout': 0.0, 'decoder_hidden_size': 48, 'decoder_layers': 2, 'decoder_dropout': 0.2, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 20, 'batch_size': 64, 'sequence_length': 168}
Time: 219.43 minutes - estimated total time: 293.94 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 1.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 173.819
  Epoch 2/60
Model trained in 1.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 161.127
  Epoch 3/60
Model trained in 1.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 150.815
  Epoch 4/60
Model trained in 1.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 141.935
  Epoch 5/60
Model trained in 1.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 134.034
  Epoch 6/60
Model trained in 1.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 126.655
  Epoch 7/60
Model trained in 1.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 119.848
  Epoch 8/60
Model trained in 2.09s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 114.804
  Epoch 9/60
Model trained in 1.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 111.405
  Epoch 10/60
Model trained in 1.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 105.876
  Epoch 11/60
Model trained in 1.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 101.432
  Epoch 12/60
Model trained in 1.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 97.339
  Epoch 13/60
Model trained in 1.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.461
  Epoch 14/60
Model trained in 1.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.159
  Epoch 15/60
Model trained in 1.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.129
  Epoch 16/60
Model trained in 1.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.516
  Epoch 17/60
Model trained in 1.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.573
  Epoch 18/60
Model trained in 1.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.781
  Epoch 19/60
Model trained in 1.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.311
  Epoch 20/60
Model trained in 1.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.967
  Epoch 21/60
Model trained in 1.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.901
  Epoch 22/60
Model trained in 1.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.005
  Epoch 23/60
Model trained in 1.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.821
  Epoch 24/60
Model trained in 1.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.527
  Epoch 25/60
Model trained in 1.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.507
  Epoch 26/60
Model trained in 1.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.400
  Epoch 27/60
Model trained in 1.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.316
  Epoch 28/60
Model trained in 1.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.013
  Epoch 29/60
Model trained in 1.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.306
  Epoch 30/60
Model trained in 1.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.743
  Epoch 31/60
Model trained in 1.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.669
  Epoch 32/60
Model trained in 1.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.758
  Epoch 33/60
Model trained in 1.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.483
  Epoch 34/60
Model trained in 1.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.612
  Epoch 35/60
Model trained in 1.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.184
  Epoch 36/60
Model trained in 1.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.227
  Epoch 37/60
Model trained in 1.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.913
  Epoch 38/60
Model trained in 1.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.405
  Epoch 39/60
Model trained in 1.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.954
  Epoch 40/60
Model trained in 1.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.265
  Epoch 41/60
Model trained in 1.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.537
  Early stopping triggered.

  best_val_SMAPE=77.901

Combination 861/1152: {'encoder_hidden_size': 48, 'encoder_layers': 1, 'encoder_dropout': 0.0, 'decoder_hidden_size': 48, 'decoder_layers': 2, 'decoder_dropout': 0.2, 'learning_rate': 0.0005, 'max_epochs': 60, 'patience': 20, 'batch_size': 32, 'sequence_length': 24}
Time: 221.02 minutes - estimated total time: 295.71 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 2.67s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 173.747
  Epoch 2/60
Model trained in 2.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 161.114
  Epoch 3/60
Model trained in 2.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 150.821
  Epoch 4/60
Model trained in 2.62s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 141.927
  Epoch 5/60
Model trained in 2.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 133.984
  Epoch 6/60
Model trained in 2.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 128.121
  Epoch 7/60
Model trained in 2.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 121.354
  Epoch 8/60
Model trained in 2.62s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 115.272
  Epoch 9/60
Model trained in 2.59s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 109.840
  Epoch 10/60
Model trained in 2.67s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 104.861
  Epoch 11/60
Model trained in 2.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 100.453
  Epoch 12/60
Model trained in 2.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 96.753
  Epoch 13/60
Model trained in 2.67s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.961
  Epoch 14/60
Model trained in 2.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.312
  Epoch 15/60
Model trained in 2.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.449
  Epoch 16/60
Model trained in 2.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.458
  Epoch 17/60
Model trained in 2.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.333
  Epoch 18/60
Model trained in 2.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.711
  Epoch 19/60
Model trained in 2.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.630
  Epoch 20/60
Model trained in 2.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.854
  Epoch 21/60
Model trained in 2.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.352
  Epoch 22/60
Model trained in 2.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.162
  Epoch 23/60
Model trained in 2.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.714
  Epoch 24/60
Model trained in 2.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.613
  Epoch 25/60
Model trained in 2.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.947
  Epoch 26/60
Model trained in 2.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.900
  Epoch 27/60
Model trained in 2.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.550
  Epoch 28/60
Model trained in 2.63s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.120
  Epoch 29/60
Model trained in 2.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.994
  Epoch 30/60
Model trained in 2.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.106
  Epoch 31/60
Model trained in 2.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.707
  Epoch 32/60
Model trained in 2.60s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.730
  Epoch 33/60
Model trained in 2.52s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.487
  Epoch 34/60
Model trained in 2.54s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.856
  Epoch 35/60
Model trained in 2.51s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.286
  Epoch 36/60
Model trained in 2.54s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.105
  Epoch 37/60
Model trained in 2.61s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.891
  Epoch 38/60
Model trained in 2.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.565
  Epoch 39/60
Model trained in 2.57s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.656
  Epoch 40/60
Model trained in 2.57s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.318
  Epoch 41/60
Model trained in 2.65s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.075
  Epoch 42/60
Model trained in 2.63s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.260
  Epoch 43/60
Model trained in 2.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.338
  Epoch 44/60
Model trained in 2.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.938
  Epoch 45/60
Model trained in 2.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.575
  Epoch 46/60
Model trained in 2.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.363
  Epoch 47/60
Model trained in 2.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.307
  Epoch 48/60
Model trained in 2.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.498
  Epoch 49/60
Model trained in 2.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.788
  Epoch 50/60
Model trained in 2.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.792
  Epoch 51/60
Model trained in 2.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.650
  Epoch 52/60
Model trained in 2.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.416
  Epoch 53/60
Model trained in 2.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.086
  Epoch 54/60
Model trained in 2.68s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.453
  Epoch 55/60
Model trained in 2.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.560
  Epoch 56/60
Model trained in 2.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.446
  Epoch 57/60
Model trained in 2.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.099
  Epoch 58/60
Model trained in 2.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.568
  Epoch 59/60
Model trained in 2.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.060
  Epoch 60/60
Model trained in 2.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.571

  best_val_SMAPE=75.571

Combination 862/1152: {'encoder_hidden_size': 48, 'encoder_layers': 1, 'encoder_dropout': 0.0, 'decoder_hidden_size': 48, 'decoder_layers': 2, 'decoder_dropout': 0.2, 'learning_rate': 0.0005, 'max_epochs': 60, 'patience': 20, 'batch_size': 32, 'sequence_length': 168}
Time: 224.22 minutes - estimated total time: 299.65 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 2.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 173.833
  Epoch 2/60
Model trained in 2.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 161.283
  Epoch 3/60
Model trained in 2.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 151.021
  Epoch 4/60
Model trained in 2.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 142.154
  Epoch 5/60
Model trained in 2.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 134.237
  Epoch 6/60
Model trained in 2.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 126.826
  Epoch 7/60
Model trained in 2.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 119.894
  Epoch 8/60
Model trained in 2.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 113.669
  Epoch 9/60
Model trained in 2.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 108.049
  Epoch 10/60
Model trained in 2.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 105.727
  Epoch 11/60
Model trained in 2.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 101.181
  Epoch 12/60
Model trained in 2.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 97.536
  Epoch 13/60
Model trained in 2.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.517
  Epoch 14/60
Model trained in 2.68s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.235
  Epoch 15/60
Model trained in 2.58s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.229
  Epoch 16/60
Model trained in 2.60s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.809
  Epoch 17/60
Model trained in 2.65s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.398
  Epoch 18/60
Model trained in 2.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.600
  Epoch 19/60
Model trained in 2.97s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.355
  Epoch 20/60
Model trained in 2.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.656
  Epoch 21/60
Model trained in 2.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.148
  Epoch 22/60
Model trained in 2.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.041
  Epoch 23/60
Model trained in 2.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.055
  Epoch 24/60
Model trained in 2.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.058
  Epoch 25/60
Model trained in 2.56s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.762
  Epoch 26/60
Model trained in 2.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.464
  Epoch 27/60
Model trained in 2.68s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.218
  Epoch 28/60
Model trained in 2.68s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.790
  Epoch 29/60
Model trained in 2.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.267
  Epoch 30/60
Model trained in 2.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.771
  Epoch 31/60
Model trained in 2.60s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.067
  Epoch 32/60
Model trained in 2.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.539
  Epoch 33/60
Model trained in 2.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.184
  Epoch 34/60
Model trained in 2.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.594
  Epoch 35/60
Model trained in 2.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.575
  Epoch 36/60
Model trained in 2.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.706
  Epoch 37/60
Model trained in 2.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.957
  Epoch 38/60
Model trained in 2.95s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.122
  Epoch 39/60
Model trained in 3.02s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.767
  Epoch 40/60
Model trained in 2.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.432
  Epoch 41/60
Model trained in 2.67s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 72.962
  Epoch 42/60
Model trained in 2.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.384
  Epoch 43/60
Model trained in 2.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.543
  Epoch 44/60
Model trained in 2.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.665
  Epoch 45/60
Model trained in 2.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.793
  Epoch 46/60
Model trained in 2.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.867
  Epoch 47/60
Model trained in 2.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.679
  Epoch 48/60
Model trained in 2.65s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.874
  Epoch 49/60
Model trained in 2.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.947
  Epoch 50/60
Model trained in 2.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.040
  Epoch 51/60
Model trained in 2.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.447
  Epoch 52/60
Model trained in 2.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.273
  Epoch 53/60
Model trained in 2.63s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.311
  Epoch 54/60
Model trained in 2.61s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.416
  Epoch 55/60
Model trained in 2.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.575
  Epoch 56/60
Model trained in 2.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.544
  Epoch 57/60
Model trained in 2.55s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.806
  Epoch 58/60
Model trained in 2.60s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.976
  Epoch 59/60
Model trained in 2.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.172
  Epoch 60/60
Model trained in 2.60s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.726

  best_val_SMAPE=72.962

Combination 863/1152: {'encoder_hidden_size': 48, 'encoder_layers': 1, 'encoder_dropout': 0.0, 'decoder_hidden_size': 48, 'decoder_layers': 2, 'decoder_dropout': 0.2, 'learning_rate': 0.0005, 'max_epochs': 60, 'patience': 20, 'batch_size': 64, 'sequence_length': 24}
Time: 227.46 minutes - estimated total time: 303.64 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 1.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 181.491
  Epoch 2/60
Model trained in 1.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 173.590
  Epoch 3/60
Model trained in 1.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 166.919
  Epoch 4/60
Model trained in 1.63s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 160.942
  Epoch 5/60
Model trained in 1.59s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 155.572
  Epoch 6/60
Model trained in 1.63s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 150.630
  Epoch 7/60
Model trained in 1.62s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 146.033
  Epoch 8/60
Model trained in 1.61s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 141.705
  Epoch 9/60
Model trained in 1.58s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 137.622
  Epoch 10/60
Model trained in 1.56s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 133.712
  Epoch 11/60
Model trained in 1.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 129.941
  Epoch 12/60
Model trained in 1.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 126.276
  Epoch 13/60
Model trained in 1.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 123.948
  Epoch 14/60
Model trained in 1.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 120.774
  Epoch 15/60
Model trained in 1.68s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 117.746
  Epoch 16/60
Model trained in 1.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 114.922
  Epoch 17/60
Model trained in 1.68s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 112.393
  Epoch 18/60
Model trained in 1.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 110.003
  Epoch 19/60
Model trained in 1.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 107.581
  Epoch 20/60
Model trained in 1.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 105.266
  Epoch 21/60
Model trained in 1.68s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 102.682
  Epoch 22/60
Model trained in 1.53s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 100.553
  Epoch 23/60
Model trained in 1.68s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 98.137
  Epoch 24/60
Model trained in 1.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 96.467
  Epoch 25/60
Model trained in 1.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 94.612
  Epoch 26/60
Model trained in 1.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.883
  Epoch 27/60
Model trained in 1.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.704
  Epoch 28/60
Model trained in 1.68s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.303
  Epoch 29/60
Model trained in 1.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.113
  Epoch 30/60
Model trained in 1.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.274
  Epoch 31/60
Model trained in 1.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.645
  Epoch 32/60
Model trained in 1.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.397
  Epoch 33/60
Model trained in 1.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.399
  Epoch 34/60
Model trained in 1.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.169
  Epoch 35/60
Model trained in 1.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.565
  Epoch 36/60
Model trained in 1.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.537
  Epoch 37/60
Model trained in 1.62s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.321
  Epoch 38/60
Model trained in 1.58s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.341
  Epoch 39/60
Model trained in 1.67s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.206
  Epoch 40/60
Model trained in 1.58s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.971
  Epoch 41/60
Model trained in 1.60s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.342
  Epoch 42/60
Model trained in 1.59s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.821
  Epoch 43/60
Model trained in 1.68s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.242
  Epoch 44/60
Model trained in 1.62s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.831
  Epoch 45/60
Model trained in 1.63s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.362
  Epoch 46/60
Model trained in 1.65s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.358
  Epoch 47/60
Model trained in 1.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.440
  Epoch 48/60
Model trained in 1.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.583
  Epoch 49/60
Model trained in 1.65s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.411
  Epoch 50/60
Model trained in 2.00s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.096
  Epoch 51/60
Model trained in 1.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.657
  Epoch 52/60
Model trained in 1.68s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 72.737
  Epoch 53/60
Model trained in 1.61s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 72.504
  Epoch 54/60
Model trained in 1.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 72.937
  Epoch 55/60
Model trained in 1.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.026
  Epoch 56/60
Model trained in 1.58s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.743
  Epoch 57/60
Model trained in 1.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.714
  Epoch 58/60
Model trained in 1.65s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.237
  Epoch 59/60
Model trained in 1.65s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.120
  Epoch 60/60
Model trained in 1.61s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.559

  best_val_SMAPE=72.504

Combination 864/1152: {'encoder_hidden_size': 48, 'encoder_layers': 1, 'encoder_dropout': 0.0, 'decoder_hidden_size': 48, 'decoder_layers': 2, 'decoder_dropout': 0.2, 'learning_rate': 0.0005, 'max_epochs': 60, 'patience': 20, 'batch_size': 64, 'sequence_length': 168}
Time: 229.63 minutes - estimated total time: 306.17 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 1.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 181.572
  Epoch 2/60
Model trained in 1.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 173.712
  Epoch 3/60
Model trained in 1.95s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 167.081
  Epoch 4/60
Model trained in 1.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 161.136
  Epoch 5/60
Model trained in 1.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 155.782
  Epoch 6/60
Model trained in 1.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 150.853
  Epoch 7/60
Model trained in 1.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 146.276
  Epoch 8/60
Model trained in 1.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 141.961
  Epoch 9/60
Model trained in 1.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 137.895
  Epoch 10/60
Model trained in 1.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 134.017
  Epoch 11/60
Model trained in 1.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 130.242
  Epoch 12/60
Model trained in 2.01s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 126.593
  Epoch 13/60
Model trained in 1.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 123.065
  Epoch 14/60
Model trained in 1.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 119.671
  Epoch 15/60
Model trained in 1.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 116.470
  Epoch 16/60
Model trained in 1.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 113.396
  Epoch 17/60
Model trained in 1.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 111.626
  Epoch 18/60
Model trained in 1.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 109.892
  Epoch 19/60
Model trained in 1.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 106.840
  Epoch 20/60
Model trained in 1.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 104.044
  Epoch 21/60
Model trained in 1.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 101.443
  Epoch 22/60
Model trained in 1.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 99.143
  Epoch 23/60
Model trained in 1.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 96.935
  Epoch 24/60
Model trained in 1.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 95.001
  Epoch 25/60
Model trained in 1.61s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.739
  Epoch 26/60
Model trained in 1.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.579
  Epoch 27/60
Model trained in 1.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.755
  Epoch 28/60
Model trained in 1.63s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.808
  Epoch 29/60
Model trained in 1.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.765
  Epoch 30/60
Model trained in 1.62s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.868
  Epoch 31/60
Model trained in 1.62s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.005
  Epoch 32/60
Model trained in 1.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.762
  Epoch 33/60
Model trained in 1.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.138
  Epoch 34/60
Model trained in 1.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.837
  Epoch 35/60
Model trained in 1.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.092
  Epoch 36/60
Model trained in 1.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.013
  Epoch 37/60
Model trained in 1.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.161
  Epoch 38/60
Model trained in 1.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.947
  Epoch 39/60
Model trained in 1.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.987
  Epoch 40/60
Model trained in 1.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.841
  Epoch 41/60
Model trained in 1.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.158
  Epoch 42/60
Model trained in 1.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.481
  Epoch 43/60
Model trained in 1.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 72.946
  Epoch 44/60
Model trained in 1.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.062
  Epoch 45/60
Model trained in 1.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 72.579
  Epoch 46/60
Model trained in 1.68s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 72.137
  Epoch 47/60
Model trained in 1.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 71.571
  Epoch 48/60
Model trained in 2.05s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 71.564
  Epoch 49/60
Model trained in 1.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 71.901
  Epoch 50/60
Model trained in 1.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 71.650
  Epoch 51/60
Model trained in 1.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 71.772
  Epoch 52/60
Model trained in 1.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 71.983
  Epoch 53/60
Model trained in 1.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 72.570
  Epoch 54/60
Model trained in 1.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.116
  Epoch 55/60
Model trained in 1.63s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.345
  Epoch 56/60
Model trained in 1.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.229
  Epoch 57/60
Model trained in 1.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.155
  Epoch 58/60
Model trained in 1.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.002
  Epoch 59/60
Model trained in 1.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.439
  Epoch 60/60
Model trained in 1.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.780

  best_val_SMAPE=71.564

Combination 961/1152: {'encoder_hidden_size': 48, 'encoder_layers': 2, 'encoder_dropout': 0.0, 'decoder_hidden_size': 28, 'decoder_layers': 1, 'decoder_dropout': 0.0, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 20, 'batch_size': 32, 'sequence_length': 24}
Time: 231.90 minutes - estimated total time: 277.98 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 2.97s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 171.518
  Epoch 2/60
Model trained in 2.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 157.333
  Epoch 3/60
Model trained in 2.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 146.049
  Epoch 4/60
Model trained in 3.11s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 136.389
  Epoch 5/60
Model trained in 2.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 128.030
  Epoch 6/60
Model trained in 2.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 120.568
  Epoch 7/60
Model trained in 2.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 113.580
  Epoch 8/60
Model trained in 2.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 107.596
  Epoch 9/60
Model trained in 2.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 101.988
  Epoch 10/60
Model trained in 2.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 97.468
  Epoch 11/60
Model trained in 2.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.173
  Epoch 12/60
Model trained in 2.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.497
  Epoch 13/60
Model trained in 2.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.145
  Epoch 14/60
Model trained in 2.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.114
  Epoch 15/60
Model trained in 2.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.706
  Epoch 16/60
Model trained in 2.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.560
  Epoch 17/60
Model trained in 2.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.892
  Epoch 18/60
Model trained in 2.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.691
  Epoch 19/60
Model trained in 2.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.681
  Epoch 20/60
Model trained in 2.98s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.337
  Epoch 21/60
Model trained in 2.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.093
  Epoch 22/60
Model trained in 2.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.912
  Epoch 23/60
Model trained in 2.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.510
  Epoch 24/60
Model trained in 2.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.875
  Epoch 25/60
Model trained in 2.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.022
  Epoch 26/60
Model trained in 2.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.103
  Epoch 27/60
Model trained in 2.56s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.279
  Epoch 28/60
Model trained in 2.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.636
  Epoch 29/60
Model trained in 2.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.914
  Epoch 30/60
Model trained in 2.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.017
  Epoch 31/60
Model trained in 2.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.506
  Epoch 32/60
Model trained in 2.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.461
  Epoch 33/60
Model trained in 2.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.665
  Epoch 34/60
Model trained in 2.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.415
  Epoch 35/60
Model trained in 2.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.684
  Epoch 36/60
Model trained in 2.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.458
  Epoch 37/60
Model trained in 2.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 94.281
  Early stopping triggered.

  best_val_SMAPE=81.892

Combination 962/1152: {'encoder_hidden_size': 48, 'encoder_layers': 2, 'encoder_dropout': 0.0, 'decoder_hidden_size': 28, 'decoder_layers': 1, 'decoder_dropout': 0.0, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 20, 'batch_size': 32, 'sequence_length': 168}
Time: 233.97 minutes - estimated total time: 280.18 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 2.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 171.750
  Epoch 2/60
Model trained in 2.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 157.574
  Epoch 3/60
Model trained in 2.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 146.208
  Epoch 4/60
Model trained in 2.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 136.676
  Epoch 5/60
Model trained in 2.98s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 128.270
  Epoch 6/60
Model trained in 2.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 120.915
  Epoch 7/60
Model trained in 3.30s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 113.761
  Epoch 8/60
Model trained in 3.20s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 107.496
  Epoch 9/60
Model trained in 3.20s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 102.035
  Epoch 10/60
Model trained in 3.25s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 97.430
  Epoch 11/60
Model trained in 2.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.725
  Epoch 12/60
Model trained in 2.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.793
  Epoch 13/60
Model trained in 2.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.067
  Epoch 14/60
Model trained in 3.03s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.069
  Epoch 15/60
Model trained in 2.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.435
  Epoch 16/60
Model trained in 2.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.307
  Epoch 17/60
Model trained in 2.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.837
  Epoch 18/60
Model trained in 2.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.639
  Epoch 19/60
Model trained in 2.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.770
  Epoch 20/60
Model trained in 2.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.465
  Epoch 21/60
Model trained in 2.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.505
  Epoch 22/60
Model trained in 2.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.130
  Epoch 23/60
Model trained in 2.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.427
  Epoch 24/60
Model trained in 2.97s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.783
  Epoch 25/60
Model trained in 2.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.080
  Epoch 26/60
Model trained in 2.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.764
  Epoch 27/60
Model trained in 3.11s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.623
  Epoch 28/60
Model trained in 2.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.957
  Epoch 29/60
Model trained in 2.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.108
  Epoch 30/60
Model trained in 2.97s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.669
  Epoch 31/60
Model trained in 2.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.668
  Epoch 32/60
Model trained in 3.29s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.128
  Epoch 33/60
Model trained in 2.98s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.285
  Epoch 34/60
Model trained in 2.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.080
  Epoch 35/60
Model trained in 3.23s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.654
  Epoch 36/60
Model trained in 3.10s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.313
  Epoch 37/60
Model trained in 2.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.790
  Epoch 38/60
Model trained in 2.98s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.248
  Epoch 39/60
Model trained in 2.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.714
  Epoch 40/60
Model trained in 2.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.343
  Epoch 41/60
Model trained in 2.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.692
  Epoch 42/60
Model trained in 2.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.448
  Early stopping triggered.

  best_val_SMAPE=78.130

Combination 963/1152: {'encoder_hidden_size': 48, 'encoder_layers': 2, 'encoder_dropout': 0.0, 'decoder_hidden_size': 28, 'decoder_layers': 1, 'decoder_dropout': 0.0, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 20, 'batch_size': 64, 'sequence_length': 24}
Time: 236.37 minutes - estimated total time: 282.76 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 1.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 180.513
  Epoch 2/60
Model trained in 1.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 171.484
  Epoch 3/60
Model trained in 1.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 163.897
  Epoch 4/60
Model trained in 1.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 157.234
  Epoch 5/60
Model trained in 1.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 151.263
  Epoch 6/60
Model trained in 1.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 145.945
  Epoch 7/60
Model trained in 1.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 140.954
  Epoch 8/60
Model trained in 1.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 136.353
  Epoch 9/60
Model trained in 1.61s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 132.183
  Epoch 10/60
Model trained in 1.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 128.106
  Epoch 11/60
Model trained in 1.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 124.174
  Epoch 12/60
Model trained in 1.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 120.660
  Epoch 13/60
Model trained in 1.62s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 117.265
  Epoch 14/60
Model trained in 1.60s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 114.046
  Epoch 15/60
Model trained in 1.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 110.747
  Epoch 16/60
Model trained in 1.68s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 107.533
  Epoch 17/60
Model trained in 1.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 104.666
  Epoch 18/60
Model trained in 1.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 101.888
  Epoch 19/60
Model trained in 1.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 99.816
  Epoch 20/60
Model trained in 1.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 97.120
  Epoch 21/60
Model trained in 1.68s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 94.165
  Epoch 22/60
Model trained in 1.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.126
  Epoch 23/60
Model trained in 1.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.170
  Epoch 24/60
Model trained in 1.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.738
  Epoch 25/60
Model trained in 1.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.352
  Epoch 26/60
Model trained in 1.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.424
  Epoch 27/60
Model trained in 1.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.319
  Epoch 28/60
Model trained in 1.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.529
  Epoch 29/60
Model trained in 1.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.685
  Epoch 30/60
Model trained in 1.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.248
  Epoch 31/60
Model trained in 1.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.099
  Epoch 32/60
Model trained in 1.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.390
  Epoch 33/60
Model trained in 1.65s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.634
  Epoch 34/60
Model trained in 1.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.997
  Epoch 35/60
Model trained in 1.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.842
  Epoch 36/60
Model trained in 1.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.666
  Epoch 37/60
Model trained in 1.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.051
  Epoch 38/60
Model trained in 1.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.238
  Epoch 39/60
Model trained in 1.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.577
  Epoch 40/60
Model trained in 1.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.016
  Epoch 41/60
Model trained in 1.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.488
  Epoch 42/60
Model trained in 1.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.826
  Epoch 43/60
Model trained in 1.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.104
  Epoch 44/60
Model trained in 1.59s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.016
  Epoch 45/60
Model trained in 1.59s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.419
  Epoch 46/60
Model trained in 1.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.449
  Epoch 47/60
Model trained in 1.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.485
  Epoch 48/60
Model trained in 1.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.747
  Epoch 49/60
Model trained in 1.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.693
  Epoch 50/60
Model trained in 1.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.463
  Epoch 51/60
Model trained in 1.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 94.499
  Epoch 52/60
Model trained in 1.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 94.765
  Epoch 53/60
Model trained in 1.68s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 96.167
  Early stopping triggered.

  best_val_SMAPE=80.634

Combination 964/1152: {'encoder_hidden_size': 48, 'encoder_layers': 2, 'encoder_dropout': 0.0, 'decoder_hidden_size': 28, 'decoder_layers': 1, 'decoder_dropout': 0.0, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 20, 'batch_size': 64, 'sequence_length': 168}
Time: 238.31 minutes - estimated total time: 284.79 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 1.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 180.623
  Epoch 2/60
Model trained in 1.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 171.595
  Epoch 3/60
Model trained in 1.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 164.032
  Epoch 4/60
Model trained in 1.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 157.389
  Epoch 5/60
Model trained in 1.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 151.498
  Epoch 6/60
Model trained in 1.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 146.130
  Epoch 7/60
Model trained in 1.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 141.138
  Epoch 8/60
Model trained in 1.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 136.515
  Epoch 9/60
Model trained in 1.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 132.286
  Epoch 10/60
Model trained in 1.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 128.278
  Epoch 11/60
Model trained in 1.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 124.185
  Epoch 12/60
Model trained in 1.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 120.448
  Epoch 13/60
Model trained in 1.97s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 116.914
  Epoch 14/60
Model trained in 2.18s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 113.667
  Epoch 15/60
Model trained in 1.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 110.289
  Epoch 16/60
Model trained in 1.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 107.167
  Epoch 17/60
Model trained in 1.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 104.413
  Epoch 18/60
Model trained in 2.05s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 103.343
  Epoch 19/60
Model trained in 1.95s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 101.948
  Epoch 20/60
Model trained in 1.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 98.101
  Epoch 21/60
Model trained in 1.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 98.893
  Epoch 22/60
Model trained in 1.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 97.085
  Epoch 23/60
Model trained in 1.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.673
  Epoch 24/60
Model trained in 2.09s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.693
  Epoch 25/60
Model trained in 1.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.495
  Epoch 26/60
Model trained in 2.01s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.200
  Epoch 27/60
Model trained in 1.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.711
  Epoch 28/60
Model trained in 1.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.549
  Epoch 29/60
Model trained in 1.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.696
  Epoch 30/60
Model trained in 1.95s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.210
  Epoch 31/60
Model trained in 1.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.447
  Epoch 32/60
Model trained in 1.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.520
  Epoch 33/60
Model trained in 1.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.228
  Epoch 34/60
Model trained in 1.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.434
  Epoch 35/60
Model trained in 1.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.134
  Epoch 36/60
Model trained in 1.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.776
  Epoch 37/60
Model trained in 1.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.041
  Epoch 38/60
Model trained in 1.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.565
  Epoch 39/60
Model trained in 1.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.789
  Epoch 40/60
Model trained in 1.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.234
  Epoch 41/60
Model trained in 1.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.334
  Epoch 42/60
Model trained in 1.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.918
  Epoch 43/60
Model trained in 1.98s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.894
  Epoch 44/60
Model trained in 1.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.695
  Epoch 45/60
Model trained in 1.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.248
  Epoch 46/60
Model trained in 1.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.978
  Epoch 47/60
Model trained in 1.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.189
  Epoch 48/60
Model trained in 2.01s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.418
  Epoch 49/60
Model trained in 1.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.995
  Epoch 50/60
Model trained in 1.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.929
  Epoch 51/60
Model trained in 1.98s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.915
  Epoch 52/60
Model trained in 1.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.669
  Epoch 53/60
Model trained in 1.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.516
  Epoch 54/60
Model trained in 2.02s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 96.890
  Epoch 55/60
Model trained in 1.95s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.677
  Epoch 56/60
Model trained in 1.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.355
  Epoch 57/60
Model trained in 1.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.526
  Epoch 58/60
Model trained in 1.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.316
  Epoch 59/60
Model trained in 1.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.254
  Early stopping triggered.

  best_val_SMAPE=82.789

Combination 965/1152: {'encoder_hidden_size': 48, 'encoder_layers': 2, 'encoder_dropout': 0.0, 'decoder_hidden_size': 28, 'decoder_layers': 1, 'decoder_dropout': 0.0, 'learning_rate': 0.0005, 'max_epochs': 60, 'patience': 20, 'batch_size': 32, 'sequence_length': 24}
Time: 240.67 minutes - estimated total time: 287.31 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 2.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 180.583
  Epoch 2/60
Model trained in 2.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 171.713
  Epoch 3/60
Model trained in 3.00s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 164.206
  Epoch 4/60
Model trained in 2.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 157.622
  Epoch 5/60
Model trained in 2.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 151.696
  Epoch 6/60
Model trained in 2.98s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 146.294
  Epoch 7/60
Model trained in 2.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 141.318
  Epoch 8/60
Model trained in 2.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 136.693
  Epoch 9/60
Model trained in 2.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 132.247
  Epoch 10/60
Model trained in 2.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 128.108
  Epoch 11/60
Model trained in 2.68s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 124.073
  Epoch 12/60
Model trained in 2.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 120.310
  Epoch 13/60
Model trained in 3.05s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 116.785
  Epoch 14/60
Model trained in 3.03s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 113.415
  Epoch 15/60
Model trained in 3.05s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 110.189
  Epoch 16/60
Model trained in 3.05s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 107.063
  Epoch 17/60
Model trained in 3.00s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 104.174
  Epoch 18/60
Model trained in 2.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 101.482
  Epoch 19/60
Model trained in 3.09s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 99.135
  Epoch 20/60
Model trained in 3.07s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 96.598
  Epoch 21/60
Model trained in 2.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 94.606
  Epoch 22/60
Model trained in 2.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.152
  Epoch 23/60
Model trained in 2.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.169
  Epoch 24/60
Model trained in 2.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.201
  Epoch 25/60
Model trained in 2.55s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.288
  Epoch 26/60
Model trained in 2.58s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.518
  Epoch 27/60
Model trained in 2.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.978
  Epoch 28/60
Model trained in 2.63s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.874
  Epoch 29/60
Model trained in 2.56s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.945
  Epoch 30/60
Model trained in 2.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.877
  Epoch 31/60
Model trained in 2.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.024
  Epoch 32/60
Model trained in 2.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.575
  Epoch 33/60
Model trained in 2.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.238
  Epoch 34/60
Model trained in 2.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.543
  Epoch 35/60
Model trained in 2.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.835
  Epoch 36/60
Model trained in 2.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.262
  Epoch 37/60
Model trained in 2.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.690
  Epoch 38/60
Model trained in 2.62s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.300
  Epoch 39/60
Model trained in 2.63s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.151
  Epoch 40/60
Model trained in 2.67s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.977
  Epoch 41/60
Model trained in 2.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.135
  Epoch 42/60
Model trained in 2.68s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.931
  Epoch 43/60
Model trained in 2.65s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.909
  Epoch 44/60
Model trained in 2.57s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.615
  Epoch 45/60
Model trained in 2.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.979
  Epoch 46/60
Model trained in 2.63s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.466
  Epoch 47/60
Model trained in 2.63s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.794
  Epoch 48/60
Model trained in 2.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.495
  Epoch 49/60
Model trained in 2.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.701
  Epoch 50/60
Model trained in 2.65s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.569
  Epoch 51/60
Model trained in 2.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.094
  Epoch 52/60
Model trained in 2.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.932
  Epoch 53/60
Model trained in 2.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.269
  Epoch 54/60
Model trained in 2.63s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.047
  Epoch 55/60
Model trained in 2.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.898
  Epoch 56/60
Model trained in 2.63s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.854
  Epoch 57/60
Model trained in 2.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 94.775
  Epoch 58/60
Model trained in 2.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 96.026
  Epoch 59/60
Model trained in 2.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 95.247
  Epoch 60/60
Model trained in 2.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 95.526

  best_val_SMAPE=74.794

Combination 966/1152: {'encoder_hidden_size': 48, 'encoder_layers': 2, 'encoder_dropout': 0.0, 'decoder_hidden_size': 28, 'decoder_layers': 1, 'decoder_dropout': 0.0, 'learning_rate': 0.0005, 'max_epochs': 60, 'patience': 20, 'batch_size': 32, 'sequence_length': 168}
Time: 243.92 minutes - estimated total time: 290.89 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 2.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 180.694
  Epoch 2/60
Model trained in 2.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 171.833
  Epoch 3/60
Model trained in 2.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 164.339
  Epoch 4/60
Model trained in 3.19s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 157.755
  Epoch 5/60
Model trained in 3.12s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 151.862
  Epoch 6/60
Model trained in 3.08s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 146.466
  Epoch 7/60
Model trained in 3.10s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 141.527
  Epoch 8/60
Model trained in 2.99s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 136.892
  Epoch 9/60
Model trained in 3.14s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 132.455
  Epoch 10/60
Model trained in 2.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 128.284
  Epoch 11/60
Model trained in 2.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 124.600
  Epoch 12/60
Model trained in 2.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 120.434
  Epoch 13/60
Model trained in 2.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 116.958
  Epoch 14/60
Model trained in 3.13s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 113.761
  Epoch 15/60
Model trained in 2.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 110.940
  Epoch 16/60
Model trained in 2.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 108.148
  Epoch 17/60
Model trained in 2.67s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 104.793
  Epoch 18/60
Model trained in 2.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 102.534
  Epoch 19/60
Model trained in 2.98s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 99.168
  Epoch 20/60
Model trained in 2.95s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 97.014
  Epoch 21/60
Model trained in 2.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 95.449
  Epoch 22/60
Model trained in 2.99s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.773
  Epoch 23/60
Model trained in 3.04s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.592
  Epoch 24/60
Model trained in 2.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.939
  Epoch 25/60
Model trained in 2.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.005
  Epoch 26/60
Model trained in 2.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 98.294
  Epoch 27/60
Model trained in 2.98s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.374
  Epoch 28/60
Model trained in 2.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.645
  Epoch 29/60
Model trained in 3.01s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.311
  Epoch 30/60
Model trained in 2.95s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.435
  Epoch 31/60
Model trained in 3.23s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.148
  Epoch 32/60
Model trained in 3.05s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.630
  Epoch 33/60
Model trained in 3.10s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.247
  Epoch 34/60
Model trained in 3.07s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.799
  Epoch 35/60
Model trained in 3.09s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.821
  Epoch 36/60
Model trained in 3.09s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.713
  Epoch 37/60
Model trained in 3.04s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.394
  Epoch 38/60
Model trained in 3.04s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.551
  Epoch 39/60
Model trained in 3.05s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.812
  Epoch 40/60
Model trained in 3.08s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.652
  Epoch 41/60
Model trained in 3.08s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.979
  Epoch 42/60
Model trained in 3.09s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.197
  Epoch 43/60
Model trained in 3.03s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.771
  Epoch 44/60
Model trained in 2.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.038
  Epoch 45/60
Model trained in 2.99s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.045
  Epoch 46/60
Model trained in 2.97s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.631
  Epoch 47/60
Model trained in 3.00s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.088
  Epoch 48/60
Model trained in 3.06s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.897
  Epoch 49/60
Model trained in 3.06s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.374
  Epoch 50/60
Model trained in 3.14s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.533
  Epoch 51/60
Model trained in 3.05s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.676
  Epoch 52/60
Model trained in 3.09s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.466
  Epoch 53/60
Model trained in 3.11s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.326
  Epoch 54/60
Model trained in 2.99s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.901
  Epoch 55/60
Model trained in 2.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.885
  Epoch 56/60
Model trained in 3.10s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.362
  Epoch 57/60
Model trained in 2.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.573
  Epoch 58/60
Model trained in 2.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.630
  Epoch 59/60
Model trained in 2.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.866
  Epoch 60/60
Model trained in 3.01s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.227

  best_val_SMAPE=76.676

Combination 967/1152: {'encoder_hidden_size': 48, 'encoder_layers': 2, 'encoder_dropout': 0.0, 'decoder_hidden_size': 28, 'decoder_layers': 1, 'decoder_dropout': 0.0, 'learning_rate': 0.0005, 'max_epochs': 60, 'patience': 20, 'batch_size': 64, 'sequence_length': 24}
Time: 247.39 minutes - estimated total time: 294.72 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 1.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 186.689
  Epoch 2/60
Model trained in 1.68s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 180.533
  Epoch 3/60
Model trained in 1.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 175.840
  Epoch 4/60
Model trained in 1.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 171.622
  Epoch 5/60
Model trained in 1.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 167.725
  Epoch 6/60
Model trained in 1.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 164.089
  Epoch 7/60
Model trained in 1.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 160.663
  Epoch 8/60
Model trained in 1.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 157.461
  Epoch 9/60
Model trained in 1.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 154.389
  Epoch 10/60
Model trained in 1.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 151.485
  Epoch 11/60
Model trained in 1.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 148.703
  Epoch 12/60
Model trained in 1.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 146.025
  Epoch 13/60
Model trained in 1.68s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 143.452
  Epoch 14/60
Model trained in 1.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 140.999
  Epoch 15/60
Model trained in 1.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 138.616
  Epoch 16/60
Model trained in 1.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 136.343
  Epoch 17/60
Model trained in 1.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 134.106
  Epoch 18/60
Model trained in 1.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 131.946
  Epoch 19/60
Model trained in 1.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 129.843
  Epoch 20/60
Model trained in 1.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 127.833
  Epoch 21/60
Model trained in 1.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 125.909
  Epoch 22/60
Model trained in 1.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 123.988
  Epoch 23/60
Model trained in 1.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 122.130
  Epoch 24/60
Model trained in 1.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 120.358
  Epoch 25/60
Model trained in 1.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 118.631
  Epoch 26/60
Model trained in 1.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 116.896
  Epoch 27/60
Model trained in 2.08s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 115.198
  Epoch 28/60
Model trained in 1.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 113.506
  Epoch 29/60
Model trained in 1.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 112.079
  Epoch 30/60
Model trained in 1.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 110.566
  Epoch 31/60
Model trained in 1.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 109.112
  Epoch 32/60
Model trained in 1.65s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 107.756
  Epoch 33/60
Model trained in 1.56s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 106.392
  Epoch 34/60
Model trained in 1.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 105.032
  Epoch 35/60
Model trained in 1.58s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 103.759
  Epoch 36/60
Model trained in 1.58s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 102.475
  Epoch 37/60
Model trained in 1.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 101.026
  Epoch 38/60
Model trained in 1.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 99.910
  Epoch 39/60
Model trained in 1.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 98.500
  Epoch 40/60
Model trained in 1.67s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 97.072
  Epoch 41/60
Model trained in 1.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 95.789
  Epoch 42/60
Model trained in 1.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 94.369
  Epoch 43/60
Model trained in 1.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.978
  Epoch 44/60
Model trained in 1.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.873
  Epoch 45/60
Model trained in 1.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.786
  Epoch 46/60
Model trained in 1.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.468
  Epoch 47/60
Model trained in 1.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.309
  Epoch 48/60
Model trained in 1.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.218
  Epoch 49/60
Model trained in 1.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.222
  Epoch 50/60
Model trained in 1.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.301
  Epoch 51/60
Model trained in 1.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.497
  Epoch 52/60
Model trained in 1.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.688
  Epoch 53/60
Model trained in 1.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.000
  Epoch 54/60
Model trained in 1.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.198
  Epoch 55/60
Model trained in 1.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.492
  Epoch 56/60
Model trained in 1.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.785
  Epoch 57/60
Model trained in 1.67s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.175
  Epoch 58/60
Model trained in 1.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.438
  Epoch 59/60
Model trained in 1.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.359
  Epoch 60/60
Model trained in 1.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.931

  best_val_SMAPE=78.931

Combination 968/1152: {'encoder_hidden_size': 48, 'encoder_layers': 2, 'encoder_dropout': 0.0, 'decoder_hidden_size': 28, 'decoder_layers': 1, 'decoder_dropout': 0.0, 'learning_rate': 0.0005, 'max_epochs': 60, 'patience': 20, 'batch_size': 64, 'sequence_length': 168}
Time: 249.62 minutes - estimated total time: 297.07 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 2.14s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 186.744
  Epoch 2/60
Model trained in 2.18s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 180.589
  Epoch 3/60
Model trained in 2.13s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 175.919
  Epoch 4/60
Model trained in 2.04s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 171.709
  Epoch 5/60
Model trained in 2.05s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 167.830
  Epoch 6/60
Model trained in 2.04s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 164.213
  Epoch 7/60
Model trained in 2.04s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 160.825
  Epoch 8/60
Model trained in 2.05s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 157.630
  Epoch 9/60
Model trained in 2.00s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 154.572
  Epoch 10/60
Model trained in 1.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 151.695
  Epoch 11/60
Model trained in 1.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 148.945
  Epoch 12/60
Model trained in 1.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 146.311
  Epoch 13/60
Model trained in 1.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 143.785
  Epoch 14/60
Model trained in 2.01s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 141.376
  Epoch 15/60
Model trained in 1.95s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 139.099
  Epoch 16/60
Model trained in 1.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 136.696
  Epoch 17/60
Model trained in 1.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 134.447
  Epoch 18/60
Model trained in 1.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 132.179
  Epoch 19/60
Model trained in 1.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 130.029
  Epoch 20/60
Model trained in 1.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 127.941
  Epoch 21/60
Model trained in 1.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 125.914
  Epoch 22/60
Model trained in 1.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 124.016
  Epoch 23/60
Model trained in 1.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 122.099
  Epoch 24/60
Model trained in 1.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 120.296
  Epoch 25/60
Model trained in 1.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 118.690
  Epoch 26/60
Model trained in 1.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 116.804
  Epoch 27/60
Model trained in 1.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 115.081
  Epoch 28/60
Model trained in 1.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 113.228
  Epoch 29/60
Model trained in 1.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 111.731
  Epoch 30/60
Model trained in 1.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 110.125
  Epoch 31/60
Model trained in 1.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 108.618
  Epoch 32/60
Model trained in 1.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 107.006
  Epoch 33/60
Model trained in 1.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 105.442
  Epoch 34/60
Model trained in 1.97s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 104.053
  Epoch 35/60
Model trained in 1.95s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 102.640
  Epoch 36/60
Model trained in 1.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 101.334
  Epoch 37/60
Model trained in 1.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 100.074
  Epoch 38/60
Model trained in 1.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 98.786
  Epoch 39/60
Model trained in 1.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 97.624
  Epoch 40/60
Model trained in 1.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 96.381
  Epoch 41/60
Model trained in 1.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 95.174
  Epoch 42/60
Model trained in 2.08s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.996
  Epoch 43/60
Model trained in 1.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.367
  Epoch 44/60
Model trained in 1.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.796
  Epoch 45/60
Model trained in 1.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.804
  Epoch 46/60
Model trained in 2.07s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.878
  Epoch 47/60
Model trained in 1.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.008
  Epoch 48/60
Model trained in 1.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.137
  Epoch 49/60
Model trained in 2.02s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.232
  Epoch 50/60
Model trained in 1.98s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.331
  Epoch 51/60
Model trained in 1.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.663
  Epoch 52/60
Model trained in 1.98s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.537
  Epoch 53/60
Model trained in 1.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.976
  Epoch 54/60
Model trained in 1.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.050
  Epoch 55/60
Model trained in 1.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.582
  Epoch 56/60
Model trained in 2.12s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.434
  Epoch 57/60
Model trained in 2.02s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.725
  Epoch 58/60
Model trained in 1.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.158
  Epoch 59/60
Model trained in 1.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.522
  Epoch 60/60
Model trained in 1.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.181

  best_val_SMAPE=79.181

Combination 977/1152: {'encoder_hidden_size': 48, 'encoder_layers': 2, 'encoder_dropout': 0.0, 'decoder_hidden_size': 28, 'decoder_layers': 2, 'decoder_dropout': 0.0, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 20, 'batch_size': 32, 'sequence_length': 24}
Time: 252.03 minutes - estimated total time: 297.17 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 3.09s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 171.957
  Epoch 2/60
Model trained in 3.10s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 157.735
  Epoch 3/60
Model trained in 3.22s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 146.307
  Epoch 4/60
Model trained in 3.21s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 136.494
  Epoch 5/60
Model trained in 3.37s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 127.861
  Epoch 6/60
Model trained in 3.20s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 122.293
  Epoch 7/60
Model trained in 2.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 115.740
  Epoch 8/60
Model trained in 2.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 109.090
  Epoch 9/60
Model trained in 2.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 104.186
  Epoch 10/60
Model trained in 2.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 100.062
  Epoch 11/60
Model trained in 3.16s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 95.933
  Epoch 12/60
Model trained in 3.12s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.728
  Epoch 13/60
Model trained in 3.07s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.893
  Epoch 14/60
Model trained in 3.14s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.393
  Epoch 15/60
Model trained in 3.26s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.951
  Epoch 16/60
Model trained in 3.02s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.939
  Epoch 17/60
Model trained in 3.06s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.875
  Epoch 18/60
Model trained in 2.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.667
  Epoch 19/60
Model trained in 3.08s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.031
  Epoch 20/60
Model trained in 3.11s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.070
  Epoch 21/60
Model trained in 3.06s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.552
  Epoch 22/60
Model trained in 3.10s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.381
  Epoch 23/60
Model trained in 3.23s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.185
  Epoch 24/60
Model trained in 3.20s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.303
  Epoch 25/60
Model trained in 3.08s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.864
  Epoch 26/60
Model trained in 3.02s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.977
  Epoch 27/60
Model trained in 3.02s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.548
  Epoch 28/60
Model trained in 3.18s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.604
  Epoch 29/60
Model trained in 3.06s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.770
  Epoch 30/60
Model trained in 3.13s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.758
  Epoch 31/60
Model trained in 3.03s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.432
  Epoch 32/60
Model trained in 3.21s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.458
  Epoch 33/60
Model trained in 3.25s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.523
  Epoch 34/60
Model trained in 3.13s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.386
  Epoch 35/60
Model trained in 2.97s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.689
  Epoch 36/60
Model trained in 3.17s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.111
  Epoch 37/60
Model trained in 3.14s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.578
  Epoch 38/60
Model trained in 3.06s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.422
  Epoch 39/60
Model trained in 3.08s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.972
  Epoch 40/60
Model trained in 2.98s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.262
  Epoch 41/60
Model trained in 3.10s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.587
  Epoch 42/60
Model trained in 3.19s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.061
  Epoch 43/60
Model trained in 3.12s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.946
  Epoch 44/60
Model trained in 3.01s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.213
  Epoch 45/60
Model trained in 3.09s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.820
  Epoch 46/60
Model trained in 3.08s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.581
  Epoch 47/60
Model trained in 3.17s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.455
  Epoch 48/60
Model trained in 3.01s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.190
  Epoch 49/60
Model trained in 3.15s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.613
  Epoch 50/60
Model trained in 3.15s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.926
  Epoch 51/60
Model trained in 3.22s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.230
  Epoch 52/60
Model trained in 3.10s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.691
  Epoch 53/60
Model trained in 3.05s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.663
  Epoch 54/60
Model trained in 3.17s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.237
  Epoch 55/60
Model trained in 3.16s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.468
  Epoch 56/60
Model trained in 3.13s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.837
  Epoch 57/60
Model trained in 2.95s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.798
  Epoch 58/60
Model trained in 3.08s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.794
  Epoch 59/60
Model trained in 3.15s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.143
  Epoch 60/60
Model trained in 3.30s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.890

  best_val_SMAPE=78.890

Combination 978/1152: {'encoder_hidden_size': 48, 'encoder_layers': 2, 'encoder_dropout': 0.0, 'decoder_hidden_size': 28, 'decoder_layers': 2, 'decoder_dropout': 0.0, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 20, 'batch_size': 32, 'sequence_length': 168}
Time: 255.62 minutes - estimated total time: 301.09 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 3.12s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 172.057
  Epoch 2/60
Model trained in 3.04s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 157.870
  Epoch 3/60
Model trained in 3.22s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 146.483
  Epoch 4/60
Model trained in 3.18s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 136.701
  Epoch 5/60
Model trained in 3.15s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 127.835
  Epoch 6/60
Model trained in 3.08s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 119.667
  Epoch 7/60
Model trained in 3.27s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 114.592
  Epoch 8/60
Model trained in 3.33s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 109.667
  Epoch 9/60
Model trained in 3.27s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 103.481
  Epoch 10/60
Model trained in 2.97s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 98.157
  Epoch 11/60
Model trained in 2.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 95.072
  Epoch 12/60
Model trained in 3.01s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.383
  Epoch 13/60
Model trained in 3.13s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.903
  Epoch 14/60
Model trained in 3.13s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.861
  Epoch 15/60
Model trained in 3.11s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.486
  Epoch 16/60
Model trained in 3.25s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.766
  Epoch 17/60
Model trained in 3.12s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.403
  Epoch 18/60
Model trained in 3.14s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.755
  Epoch 19/60
Model trained in 2.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.725
  Epoch 20/60
Model trained in 3.09s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.166
  Epoch 21/60
Model trained in 3.19s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.474
  Epoch 22/60
Model trained in 3.23s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.240
  Epoch 23/60
Model trained in 3.04s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.898
  Epoch 24/60
Model trained in 3.06s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.756
  Epoch 25/60
Model trained in 2.95s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.097
  Epoch 26/60
Model trained in 2.99s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.396
  Epoch 27/60
Model trained in 3.03s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.133
  Epoch 28/60
Model trained in 3.05s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.835
  Epoch 29/60
Model trained in 3.02s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.051
  Epoch 30/60
Model trained in 3.08s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.315
  Epoch 31/60
Model trained in 3.05s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.142
  Epoch 32/60
Model trained in 2.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.529
  Epoch 33/60
Model trained in 2.98s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.976
  Epoch 34/60
Model trained in 3.01s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.785
  Epoch 35/60
Model trained in 3.14s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.446
  Epoch 36/60
Model trained in 3.09s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.088
  Epoch 37/60
Model trained in 3.04s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 94.893
  Epoch 38/60
Model trained in 3.02s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.491
  Epoch 39/60
Model trained in 3.20s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.636
  Epoch 40/60
Model trained in 3.10s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.388
  Epoch 41/60
Model trained in 2.99s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 94.967
  Early stopping triggered.

  best_val_SMAPE=83.474

Combination 979/1152: {'encoder_hidden_size': 48, 'encoder_layers': 2, 'encoder_dropout': 0.0, 'decoder_hidden_size': 28, 'decoder_layers': 2, 'decoder_dropout': 0.0, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 20, 'batch_size': 64, 'sequence_length': 24}
Time: 258.07 minutes - estimated total time: 303.67 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 1.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 180.857
  Epoch 2/60
Model trained in 1.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 171.865
  Epoch 3/60
Model trained in 1.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 164.274
  Epoch 4/60
Model trained in 1.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 157.586
  Epoch 5/60
Model trained in 1.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 151.588
  Epoch 6/60
Model trained in 1.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 146.115
  Epoch 7/60
Model trained in 1.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 141.025
  Epoch 8/60
Model trained in 1.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 136.268
  Epoch 9/60
Model trained in 1.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 131.720
  Epoch 10/60
Model trained in 1.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 127.772
  Epoch 11/60
Model trained in 1.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 125.365
  Epoch 12/60
Model trained in 1.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 122.195
  Epoch 13/60
Model trained in 1.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 118.145
  Epoch 14/60
Model trained in 1.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 114.578
  Epoch 15/60
Model trained in 1.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 111.438
  Epoch 16/60
Model trained in 1.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 107.741
  Epoch 17/60
Model trained in 1.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 105.048
  Epoch 18/60
Model trained in 1.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 102.545
  Epoch 19/60
Model trained in 1.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 99.677
  Epoch 20/60
Model trained in 1.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 97.514
  Epoch 21/60
Model trained in 1.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 95.114
  Epoch 22/60
Model trained in 1.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.288
  Epoch 23/60
Model trained in 1.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.297
  Epoch 24/60
Model trained in 1.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.732
  Epoch 25/60
Model trained in 1.68s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.428
  Epoch 26/60
Model trained in 1.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.940
  Epoch 27/60
Model trained in 1.68s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.833
  Epoch 28/60
Model trained in 1.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.910
  Epoch 29/60
Model trained in 1.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.171
  Epoch 30/60
Model trained in 1.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.216
  Epoch 31/60
Model trained in 1.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.402
  Epoch 32/60
Model trained in 1.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.053
  Epoch 33/60
Model trained in 1.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.880
  Epoch 34/60
Model trained in 1.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.581
  Epoch 35/60
Model trained in 1.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.573
  Epoch 36/60
Model trained in 1.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.054
  Epoch 37/60
Model trained in 1.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.073
  Epoch 38/60
Model trained in 1.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.201
  Epoch 39/60
Model trained in 1.99s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.773
  Epoch 40/60
Model trained in 1.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.001
  Epoch 41/60
Model trained in 1.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.135
  Epoch 42/60
Model trained in 1.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.936
  Epoch 43/60
Model trained in 1.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.913
  Epoch 44/60
Model trained in 1.63s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.243
  Epoch 45/60
Model trained in 1.62s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.701
  Epoch 46/60
Model trained in 1.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.137
  Epoch 47/60
Model trained in 1.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.621
  Epoch 48/60
Model trained in 1.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.335
  Epoch 49/60
Model trained in 1.63s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.540
  Epoch 50/60
Model trained in 1.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.405
  Epoch 51/60
Model trained in 1.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.083
  Epoch 52/60
Model trained in 1.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.983
  Epoch 53/60
Model trained in 1.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.355
  Epoch 54/60
Model trained in 1.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.317
  Epoch 55/60
Model trained in 1.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.371
  Epoch 56/60
Model trained in 1.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.762
  Epoch 57/60
Model trained in 1.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.218
  Epoch 58/60
Model trained in 1.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.871
  Epoch 59/60
Model trained in 1.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.279
  Early stopping triggered.

  best_val_SMAPE=73.773

Combination 980/1152: {'encoder_hidden_size': 48, 'encoder_layers': 2, 'encoder_dropout': 0.0, 'decoder_hidden_size': 28, 'decoder_layers': 2, 'decoder_dropout': 0.0, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 20, 'batch_size': 64, 'sequence_length': 168}
Time: 260.28 minutes - estimated total time: 305.96 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 1.95s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 180.944
  Epoch 2/60
Model trained in 2.01s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 171.971
  Epoch 3/60
Model trained in 1.97s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 164.417
  Epoch 4/60
Model trained in 2.04s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 157.754
  Epoch 5/60
Model trained in 2.00s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 151.781
  Epoch 6/60
Model trained in 1.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 146.330
  Epoch 7/60
Model trained in 1.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 141.256
  Epoch 8/60
Model trained in 1.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 136.517
  Epoch 9/60
Model trained in 1.99s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 131.991
  Epoch 10/60
Model trained in 1.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 127.617
  Epoch 11/60
Model trained in 1.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 123.430
  Epoch 12/60
Model trained in 1.95s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 119.425
  Epoch 13/60
Model trained in 1.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 115.666
  Epoch 14/60
Model trained in 1.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 112.083
  Epoch 15/60
Model trained in 1.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 108.649
  Epoch 16/60
Model trained in 1.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 105.379
  Epoch 17/60
Model trained in 1.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 104.967
  Epoch 18/60
Model trained in 1.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 103.339
  Epoch 19/60
Model trained in 2.02s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 100.842
  Epoch 20/60
Model trained in 1.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 98.155
  Epoch 21/60
Model trained in 1.97s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 95.541
  Epoch 22/60
Model trained in 1.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.000
  Epoch 23/60
Model trained in 1.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.023
  Epoch 24/60
Model trained in 1.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.767
  Epoch 25/60
Model trained in 2.09s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.501
  Epoch 26/60
Model trained in 1.99s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.634
  Epoch 27/60
Model trained in 1.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.919
  Epoch 28/60
Model trained in 1.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.101
  Epoch 29/60
Model trained in 1.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.978
  Epoch 30/60
Model trained in 1.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.576
  Epoch 31/60
Model trained in 1.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.276
  Epoch 32/60
Model trained in 1.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.042
  Epoch 33/60
Model trained in 1.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.587
  Epoch 34/60
Model trained in 1.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.289
  Epoch 35/60
Model trained in 1.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.133
  Epoch 36/60
Model trained in 1.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.326
  Epoch 37/60
Model trained in 1.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.062
  Epoch 38/60
Model trained in 1.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.819
  Epoch 39/60
Model trained in 1.97s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.737
  Epoch 40/60
Model trained in 1.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.990
  Epoch 41/60
Model trained in 2.17s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.891
  Epoch 42/60
Model trained in 1.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.878
  Epoch 43/60
Model trained in 1.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.034
  Epoch 44/60
Model trained in 1.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.997
  Epoch 45/60
Model trained in 1.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.012
  Epoch 46/60
Model trained in 1.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.756
  Epoch 47/60
Model trained in 1.99s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.121
  Epoch 48/60
Model trained in 1.98s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.631
  Epoch 49/60
Model trained in 1.99s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.056
  Epoch 50/60
Model trained in 1.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.322
  Epoch 51/60
Model trained in 1.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.639
  Epoch 52/60
Model trained in 1.97s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.005
  Epoch 53/60
Model trained in 1.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.096
  Epoch 54/60
Model trained in 1.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.423
  Epoch 55/60
Model trained in 1.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.252
  Epoch 56/60
Model trained in 1.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.965
  Epoch 57/60
Model trained in 1.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.962
  Epoch 58/60
Model trained in 1.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.951
  Epoch 59/60
Model trained in 2.08s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.267
  Epoch 60/60
Model trained in 2.04s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.556

  best_val_SMAPE=76.631

Combination 981/1152: {'encoder_hidden_size': 48, 'encoder_layers': 2, 'encoder_dropout': 0.0, 'decoder_hidden_size': 28, 'decoder_layers': 2, 'decoder_dropout': 0.0, 'learning_rate': 0.0005, 'max_epochs': 60, 'patience': 20, 'batch_size': 32, 'sequence_length': 24}
Time: 262.68 minutes - estimated total time: 308.47 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 3.13s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 180.843
  Epoch 2/60
Model trained in 3.11s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 172.002
  Epoch 3/60
Model trained in 3.22s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 164.494
  Epoch 4/60
Model trained in 3.36s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 157.842
  Epoch 5/60
Model trained in 3.16s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 151.861
  Epoch 6/60
Model trained in 2.95s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 146.390
  Epoch 7/60
Model trained in 2.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 141.285
  Epoch 8/60
Model trained in 2.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 136.511
  Epoch 9/60
Model trained in 2.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 132.187
  Epoch 10/60
Model trained in 2.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 128.963
  Epoch 11/60
Model trained in 2.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 124.592
  Epoch 12/60
Model trained in 2.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 120.657
  Epoch 13/60
Model trained in 2.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 117.193
  Epoch 14/60
Model trained in 2.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 113.809
  Epoch 15/60
Model trained in 2.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 110.598
  Epoch 16/60
Model trained in 2.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 107.056
  Epoch 17/60
Model trained in 3.07s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 103.899
  Epoch 18/60
Model trained in 2.97s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 100.831
  Epoch 19/60
Model trained in 2.99s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 98.495
  Epoch 20/60
Model trained in 2.95s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 95.542
  Epoch 21/60
Model trained in 3.18s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.535
  Epoch 22/60
Model trained in 3.12s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.070
  Epoch 23/60
Model trained in 3.10s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.942
  Epoch 24/60
Model trained in 3.09s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.073
  Epoch 25/60
Model trained in 3.05s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.683
  Epoch 26/60
Model trained in 3.20s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.459
  Epoch 27/60
Model trained in 3.11s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.113
  Epoch 28/60
Model trained in 3.11s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.711
  Epoch 29/60
Model trained in 2.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.231
  Epoch 30/60
Model trained in 2.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.112
  Epoch 31/60
Model trained in 2.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.890
  Epoch 32/60
Model trained in 2.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.309
  Epoch 33/60
Model trained in 2.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 72.754
  Epoch 34/60
Model trained in 3.16s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 72.569
  Epoch 35/60
Model trained in 3.20s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 72.157
  Epoch 36/60
Model trained in 3.05s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 71.799
  Epoch 37/60
Model trained in 2.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 72.115
  Epoch 38/60
Model trained in 2.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 71.368
  Epoch 39/60
Model trained in 3.24s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 71.799
  Epoch 40/60
Model trained in 3.21s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.761
  Epoch 41/60
Model trained in 3.14s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.567
  Epoch 42/60
Model trained in 2.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.160
  Epoch 43/60
Model trained in 2.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.472
  Epoch 44/60
Model trained in 2.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.438
  Epoch 45/60
Model trained in 2.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.208
  Epoch 46/60
Model trained in 2.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.730
  Epoch 47/60
Model trained in 3.21s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.238
  Epoch 48/60
Model trained in 3.19s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.291
  Epoch 49/60
Model trained in 3.21s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.592
  Epoch 50/60
Model trained in 3.17s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.948
  Epoch 51/60
Model trained in 3.19s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.787
  Epoch 52/60
Model trained in 3.15s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.693
  Epoch 53/60
Model trained in 3.19s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.964
  Epoch 54/60
Model trained in 3.24s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.342
  Epoch 55/60
Model trained in 3.16s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.298
  Epoch 56/60
Model trained in 3.20s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.094
  Epoch 57/60
Model trained in 3.19s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.208
  Epoch 58/60
Model trained in 3.13s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.859
  Early stopping triggered.

  best_val_SMAPE=71.368

Combination 982/1152: {'encoder_hidden_size': 48, 'encoder_layers': 2, 'encoder_dropout': 0.0, 'decoder_hidden_size': 28, 'decoder_layers': 2, 'decoder_dropout': 0.0, 'learning_rate': 0.0005, 'max_epochs': 60, 'patience': 20, 'batch_size': 32, 'sequence_length': 168}
Time: 266.09 minutes - estimated total time: 312.16 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 2.95s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 180.925
  Epoch 2/60
Model trained in 2.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 172.102
  Epoch 3/60
Model trained in 3.12s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 164.622
  Epoch 4/60
Model trained in 2.95s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 157.991
  Epoch 5/60
Model trained in 2.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 152.030
  Epoch 6/60
Model trained in 2.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 146.577
  Epoch 7/60
Model trained in 2.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 141.485
  Epoch 8/60
Model trained in 3.03s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 136.727
  Epoch 9/60
Model trained in 3.20s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 132.179
  Epoch 10/60
Model trained in 3.26s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 127.777
  Epoch 11/60
Model trained in 3.28s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 124.578
  Epoch 12/60
Model trained in 2.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 122.187
  Epoch 13/60
Model trained in 2.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 119.185
  Epoch 14/60
Model trained in 3.13s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 116.440
  Epoch 15/60
Model trained in 3.27s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 112.420
  Epoch 16/60
Model trained in 3.27s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 109.212
  Epoch 17/60
Model trained in 3.26s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 106.724
  Epoch 18/60
Model trained in 3.26s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 104.229
  Epoch 19/60
Model trained in 3.27s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 102.531
  Epoch 20/60
Model trained in 3.25s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 100.416
  Epoch 21/60
Model trained in 3.23s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 98.694
  Epoch 22/60
Model trained in 3.26s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 95.835
  Epoch 23/60
Model trained in 3.25s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 94.359
  Epoch 24/60
Model trained in 3.26s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.609
  Epoch 25/60
Model trained in 3.24s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.832
  Epoch 26/60
Model trained in 3.26s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.534
  Epoch 27/60
Model trained in 3.25s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.334
  Epoch 28/60
Model trained in 3.27s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.804
  Epoch 29/60
Model trained in 2.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.003
  Epoch 30/60
Model trained in 2.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.532
  Epoch 31/60
Model trained in 3.00s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.695
  Epoch 32/60
Model trained in 2.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.002
  Epoch 33/60
Model trained in 2.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.370
  Epoch 34/60
Model trained in 2.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.608
  Epoch 35/60
Model trained in 2.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.763
  Epoch 36/60
Model trained in 3.29s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.273
  Epoch 37/60
Model trained in 3.24s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.716
  Epoch 38/60
Model trained in 2.97s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.233
  Epoch 39/60
Model trained in 2.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.542
  Epoch 40/60
Model trained in 3.13s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.085
  Epoch 41/60
Model trained in 3.26s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.422
  Epoch 42/60
Model trained in 3.27s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.814
  Epoch 43/60
Model trained in 3.23s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.663
  Epoch 44/60
Model trained in 3.26s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.312
  Epoch 45/60
Model trained in 3.24s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.006
  Epoch 46/60
Model trained in 3.28s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.994
  Epoch 47/60
Model trained in 3.26s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.700
  Epoch 48/60
Model trained in 3.18s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.215
  Epoch 49/60
Model trained in 3.25s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.323
  Epoch 50/60
Model trained in 3.26s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.698
  Epoch 51/60
Model trained in 3.25s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.855
  Epoch 52/60
Model trained in 3.25s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.074
  Epoch 53/60
Model trained in 3.26s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.634
  Epoch 54/60
Model trained in 3.26s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.992
  Epoch 55/60
Model trained in 3.28s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.504
  Epoch 56/60
Model trained in 3.25s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.385
  Epoch 57/60
Model trained in 3.30s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.406
  Epoch 58/60
Model trained in 3.25s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.970
  Epoch 59/60
Model trained in 3.27s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.538
  Epoch 60/60
Model trained in 2.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.184

  best_val_SMAPE=74.663

Combination 983/1152: {'encoder_hidden_size': 48, 'encoder_layers': 2, 'encoder_dropout': 0.0, 'decoder_hidden_size': 28, 'decoder_layers': 2, 'decoder_dropout': 0.0, 'learning_rate': 0.0005, 'max_epochs': 60, 'patience': 20, 'batch_size': 64, 'sequence_length': 24}
Time: 269.71 minutes - estimated total time: 316.08 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 1.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 186.769
  Epoch 2/60
Model trained in 1.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 180.796
  Epoch 3/60
Model trained in 1.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 176.131
  Epoch 4/60
Model trained in 1.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 171.919
  Epoch 5/60
Model trained in 1.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 168.025
  Epoch 6/60
Model trained in 1.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 164.377
  Epoch 7/60
Model trained in 1.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 160.922
  Epoch 8/60
Model trained in 1.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 157.701
  Epoch 9/60
Model trained in 1.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 154.614
  Epoch 10/60
Model trained in 1.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 151.695
  Epoch 11/60
Model trained in 1.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 148.900
  Epoch 12/60
Model trained in 1.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 146.201
  Epoch 13/60
Model trained in 1.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 143.584
  Epoch 14/60
Model trained in 1.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 141.078
  Epoch 15/60
Model trained in 1.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 138.643
  Epoch 16/60
Model trained in 1.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 136.284
  Epoch 17/60
Model trained in 1.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 133.972
  Epoch 18/60
Model trained in 1.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 131.694
  Epoch 19/60
Model trained in 1.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 129.454
  Epoch 20/60
Model trained in 1.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 127.894
  Epoch 21/60
Model trained in 1.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 126.269
  Epoch 22/60
Model trained in 1.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 124.625
  Epoch 23/60
Model trained in 1.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 122.807
  Epoch 24/60
Model trained in 1.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 120.903
  Epoch 25/60
Model trained in 1.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 118.680
  Epoch 26/60
Model trained in 1.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 116.971
  Epoch 27/60
Model trained in 1.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 115.074
  Epoch 28/60
Model trained in 1.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 113.407
  Epoch 29/60
Model trained in 1.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 111.540
  Epoch 30/60
Model trained in 1.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 109.904
  Epoch 31/60
Model trained in 1.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 108.313
  Epoch 32/60
Model trained in 1.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 106.761
  Epoch 33/60
Model trained in 1.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 105.025
  Epoch 34/60
Model trained in 1.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 103.298
  Epoch 35/60
Model trained in 1.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 101.642
  Epoch 36/60
Model trained in 1.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 99.965
  Epoch 37/60
Model trained in 1.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 98.285
  Epoch 38/60
Model trained in 1.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 96.738
  Epoch 39/60
Model trained in 1.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 95.794
  Epoch 40/60
Model trained in 1.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 94.391
  Epoch 41/60
Model trained in 1.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.120
  Epoch 42/60
Model trained in 1.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.010
  Epoch 43/60
Model trained in 1.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.845
  Epoch 44/60
Model trained in 1.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.760
  Epoch 45/60
Model trained in 1.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.636
  Epoch 46/60
Model trained in 1.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.476
  Epoch 47/60
Model trained in 1.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.658
  Epoch 48/60
Model trained in 1.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.250
  Epoch 49/60
Model trained in 1.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.062
  Epoch 50/60
Model trained in 1.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.758
  Epoch 51/60
Model trained in 1.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.761
  Epoch 52/60
Model trained in 1.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.933
  Epoch 53/60
Model trained in 1.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.656
  Epoch 54/60
Model trained in 1.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.135
  Epoch 55/60
Model trained in 1.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.767
  Epoch 56/60
Model trained in 1.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.533
  Epoch 57/60
Model trained in 1.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.775
  Epoch 58/60
Model trained in 1.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.876
  Epoch 59/60
Model trained in 1.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.834
  Epoch 60/60
Model trained in 1.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.060

  best_val_SMAPE=77.060

Combination 984/1152: {'encoder_hidden_size': 48, 'encoder_layers': 2, 'encoder_dropout': 0.0, 'decoder_hidden_size': 28, 'decoder_layers': 2, 'decoder_dropout': 0.0, 'learning_rate': 0.0005, 'max_epochs': 60, 'patience': 20, 'batch_size': 64, 'sequence_length': 168}
Time: 272.01 minutes - estimated total time: 318.45 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 1.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 186.812
  Epoch 2/60
Model trained in 1.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 180.859
  Epoch 3/60
Model trained in 1.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 176.214
  Epoch 4/60
Model trained in 1.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 172.020
  Epoch 5/60
Model trained in 1.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 168.148
  Epoch 6/60
Model trained in 1.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 164.514
  Epoch 7/60
Model trained in 1.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 161.076
  Epoch 8/60
Model trained in 1.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 157.863
  Epoch 9/60
Model trained in 1.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 154.792
  Epoch 10/60
Model trained in 1.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 151.882
  Epoch 11/60
Model trained in 1.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 149.098
  Epoch 12/60
Model trained in 1.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 146.411
  Epoch 13/60
Model trained in 1.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 143.803
  Epoch 14/60
Model trained in 1.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 141.305
  Epoch 15/60
Model trained in 1.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 138.880
  Epoch 16/60
Model trained in 1.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 136.530
  Epoch 17/60
Model trained in 1.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 134.229
  Epoch 18/60
Model trained in 1.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 131.963
  Epoch 19/60
Model trained in 1.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 129.732
  Epoch 20/60
Model trained in 1.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 127.545
  Epoch 21/60
Model trained in 1.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 125.411
  Epoch 22/60
Model trained in 1.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 125.916
  Epoch 23/60
Model trained in 1.95s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 123.421
  Epoch 24/60
Model trained in 1.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 121.151
  Epoch 25/60
Model trained in 1.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 119.111
  Epoch 26/60
Model trained in 1.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 117.107
  Epoch 27/60
Model trained in 1.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 115.336
  Epoch 28/60
Model trained in 1.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 113.472
  Epoch 29/60
Model trained in 1.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 111.677
  Epoch 30/60
Model trained in 1.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 109.852
  Epoch 31/60
Model trained in 1.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 108.079
  Epoch 32/60
Model trained in 1.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 106.610
  Epoch 33/60
Model trained in 1.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 105.182
  Epoch 34/60
Model trained in 1.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 103.765
  Epoch 35/60
Model trained in 1.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 101.928
  Epoch 36/60
Model trained in 1.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 100.289
  Epoch 37/60
Model trained in 1.95s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 98.888
  Epoch 38/60
Model trained in 1.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 97.409
  Epoch 39/60
Model trained in 1.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 95.840
  Epoch 40/60
Model trained in 1.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 94.468
  Epoch 41/60
Model trained in 1.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.236
  Epoch 42/60
Model trained in 1.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.890
  Epoch 43/60
Model trained in 1.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.588
  Epoch 44/60
Model trained in 1.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.104
  Epoch 45/60
Model trained in 1.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.842
  Epoch 46/60
Model trained in 1.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.740
  Epoch 47/60
Model trained in 1.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.511
  Epoch 48/60
Model trained in 1.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.368
  Epoch 49/60
Model trained in 1.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.526
  Epoch 50/60
Model trained in 1.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.172
  Epoch 51/60
Model trained in 1.97s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.531
  Epoch 52/60
Model trained in 1.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.552
  Epoch 53/60
Model trained in 1.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.819
  Epoch 54/60
Model trained in 1.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.383
  Epoch 55/60
Model trained in 1.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.627
  Epoch 56/60
Model trained in 1.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.110
  Epoch 57/60
Model trained in 1.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.611
  Epoch 58/60
Model trained in 1.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.977
  Epoch 59/60
Model trained in 1.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.012
  Epoch 60/60
Model trained in 1.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.787

  best_val_SMAPE=76.787

Combination 985/1152: {'encoder_hidden_size': 48, 'encoder_layers': 2, 'encoder_dropout': 0.0, 'decoder_hidden_size': 28, 'decoder_layers': 2, 'decoder_dropout': 0.2, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 20, 'batch_size': 32, 'sequence_length': 24}
Time: 274.38 minutes - estimated total time: 320.90 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 2.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 171.949
  Epoch 2/60
Model trained in 2.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 157.728
  Epoch 3/60
Model trained in 2.97s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 146.301
  Epoch 4/60
Model trained in 2.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 136.489
  Epoch 5/60
Model trained in 2.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 127.581
  Epoch 6/60
Model trained in 2.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 121.130
  Epoch 7/60
Model trained in 2.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 114.873
  Epoch 8/60
Model trained in 2.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 109.816
  Epoch 9/60
Model trained in 2.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 104.811
  Epoch 10/60
Model trained in 2.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 101.545
  Epoch 11/60
Model trained in 2.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 96.199
  Epoch 12/60
Model trained in 3.21s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.691
  Epoch 13/60
Model trained in 2.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.641
  Epoch 14/60
Model trained in 2.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.621
  Epoch 15/60
Model trained in 3.03s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.259
  Epoch 16/60
Model trained in 3.14s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.095
  Epoch 17/60
Model trained in 3.13s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.715
  Epoch 18/60
Model trained in 3.12s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.264
  Epoch 19/60
Model trained in 2.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.497
  Epoch 20/60
Model trained in 2.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.888
  Epoch 21/60
Model trained in 2.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.190
  Epoch 22/60
Model trained in 2.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.509
  Epoch 23/60
Model trained in 2.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.348
  Epoch 24/60
Model trained in 3.04s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.029
  Epoch 25/60
Model trained in 3.15s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.142
  Epoch 26/60
Model trained in 3.16s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.777
  Epoch 27/60
Model trained in 3.22s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.849
  Epoch 28/60
Model trained in 3.02s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.701
  Epoch 29/60
Model trained in 3.20s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.257
  Epoch 30/60
Model trained in 3.11s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.382
  Epoch 31/60
Model trained in 3.21s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.446
  Epoch 32/60
Model trained in 3.06s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.947
  Epoch 33/60
Model trained in 2.97s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.763
  Epoch 34/60
Model trained in 2.99s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.712
  Epoch 35/60

C:\Users\n_and\AppData\Local\Temp\ipykernel_4700\3103432539.py:17: RuntimeWarning: invalid value encountered in divide
  vals = np.where(denom == 0, 0.0, 200.0 * np.abs(y_pred - y_true) / denom)

Model trained in 2.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 95.269
  Epoch 36/60
Model trained in 2.98s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 95.547
  Epoch 37/60
Model trained in 2.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 95.126
  Early stopping triggered.

  best_val_SMAPE=82.715

Combination 986/1152: {'encoder_hidden_size': 48, 'encoder_layers': 2, 'encoder_dropout': 0.0, 'decoder_hidden_size': 28, 'decoder_layers': 2, 'decoder_dropout': 0.2, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 20, 'batch_size': 32, 'sequence_length': 168}
Time: 276.52 minutes - estimated total time: 323.08 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 3.07s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 172.049
  Epoch 2/60
Model trained in 3.29s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 157.864
  Epoch 3/60
Model trained in 3.12s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 146.477
  Epoch 4/60
Model trained in 3.08s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 136.695
  Epoch 5/60
Model trained in 3.11s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 127.830
  Epoch 6/60
Model trained in 3.12s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 119.662
  Epoch 7/60
Model trained in 3.07s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 112.341
  Epoch 8/60
Model trained in 3.01s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 108.698
  Epoch 9/60
Model trained in 3.07s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 103.821
  Epoch 10/60
Model trained in 3.16s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 99.459
  Epoch 11/60
Model trained in 3.19s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 95.636
  Epoch 12/60
Model trained in 3.13s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.867
  Epoch 13/60
Model trained in 3.09s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.350
  Epoch 14/60
Model trained in 3.17s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.884
  Epoch 15/60
Model trained in 3.10s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.198
  Epoch 16/60
Model trained in 3.13s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.900
  Epoch 17/60
Model trained in 3.07s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.103
  Epoch 18/60
Model trained in 3.15s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.761
  Epoch 19/60
Model trained in 3.14s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.277
  Epoch 20/60
Model trained in 3.08s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.772
  Epoch 21/60
Model trained in 3.10s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.354
  Epoch 22/60
Model trained in 3.10s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.344
  Epoch 23/60
Model trained in 3.04s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.424
  Epoch 24/60
Model trained in 3.00s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.962
  Epoch 25/60
Model trained in 3.18s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.367
  Epoch 26/60
Model trained in 3.08s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.347
  Epoch 27/60
Model trained in 3.12s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.562
  Epoch 28/60
Model trained in 3.14s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.217
  Epoch 29/60
Model trained in 2.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.119
  Epoch 30/60
Model trained in 3.05s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.655
  Epoch 31/60
Model trained in 3.07s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.486
  Epoch 32/60
Model trained in 3.05s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.966
  Epoch 33/60
Model trained in 3.17s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.315
  Epoch 34/60
Model trained in 3.17s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.667
  Epoch 35/60
Model trained in 3.06s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.505
  Epoch 36/60
Model trained in 3.02s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.028
  Epoch 37/60
Model trained in 3.15s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.974
  Epoch 38/60
Model trained in 3.04s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.197
  Epoch 39/60
Model trained in 3.11s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.655
  Epoch 40/60
Model trained in 3.13s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.365
  Epoch 41/60
Model trained in 3.05s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.871
  Epoch 42/60
Model trained in 3.14s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.478
  Epoch 43/60
Model trained in 3.10s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.063
  Epoch 44/60
Model trained in 3.06s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.746
  Epoch 45/60
Model trained in 3.16s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.906
  Epoch 46/60
Model trained in 3.03s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.891
  Epoch 47/60
Model trained in 3.07s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.448
  Epoch 48/60
Model trained in 3.08s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.649
  Epoch 49/60
Model trained in 3.06s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.965
  Epoch 50/60
Model trained in 3.09s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.721
  Epoch 51/60
Model trained in 3.08s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.970
  Epoch 52/60
Model trained in 3.09s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.730
  Epoch 53/60
Model trained in 3.05s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.150
  Epoch 54/60
Model trained in 3.14s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.654
  Epoch 55/60
Model trained in 3.12s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.101
  Epoch 56/60
Model trained in 3.06s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.926
  Epoch 57/60
Model trained in 3.07s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.018
  Epoch 58/60
Model trained in 3.07s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.351
  Epoch 59/60
Model trained in 3.01s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.180
  Epoch 60/60
Model trained in 3.13s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.933

  best_val_SMAPE=80.063

Combination 987/1152: {'encoder_hidden_size': 48, 'encoder_layers': 2, 'encoder_dropout': 0.0, 'decoder_hidden_size': 28, 'decoder_layers': 2, 'decoder_dropout': 0.2, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 20, 'batch_size': 64, 'sequence_length': 24}
Time: 280.10 minutes - estimated total time: 326.92 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 1.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 180.848
  Epoch 2/60
Model trained in 1.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 171.856
  Epoch 3/60
Model trained in 1.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 164.266
  Epoch 4/60
Model trained in 1.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 157.579
  Epoch 5/60
Model trained in 1.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 151.582
  Epoch 6/60
Model trained in 1.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 146.109
  Epoch 7/60
Model trained in 1.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 141.020
  Epoch 8/60
Model trained in 1.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 136.263
  Epoch 9/60
Model trained in 1.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 132.496
  Epoch 10/60
Model trained in 1.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 128.495
  Epoch 11/60
Model trained in 1.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 125.162
  Epoch 12/60
Model trained in 1.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 121.724
  Epoch 13/60
Model trained in 1.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 118.177
  Epoch 14/60
Model trained in 1.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 114.912
  Epoch 15/60
Model trained in 1.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 111.644
  Epoch 16/60
Model trained in 1.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 108.781
  Epoch 17/60
Model trained in 1.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 105.669
  Epoch 18/60
Model trained in 1.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 102.468
  Epoch 19/60
Model trained in 1.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 100.994
  Epoch 20/60
Model trained in 1.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 98.874
  Epoch 21/60
Model trained in 1.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 96.285
  Epoch 22/60
Model trained in 1.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 95.097
  Epoch 23/60
Model trained in 1.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.578
  Epoch 24/60
Model trained in 1.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.163
  Epoch 25/60
Model trained in 1.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.305
  Epoch 26/60
Model trained in 1.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.520
  Epoch 27/60
Model trained in 1.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.745
  Epoch 28/60
Model trained in 1.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.236
  Epoch 29/60
Model trained in 1.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.656
  Epoch 30/60
Model trained in 1.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.183
  Epoch 31/60
Model trained in 1.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.531
  Epoch 32/60
Model trained in 1.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.272
  Epoch 33/60
Model trained in 1.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.359
  Epoch 34/60
Model trained in 1.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.400
  Epoch 35/60
Model trained in 1.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.542
  Epoch 36/60
Model trained in 1.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.114
  Epoch 37/60
Model trained in 1.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.966
  Epoch 38/60
Model trained in 1.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.334
  Epoch 39/60
Model trained in 1.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.943
  Epoch 40/60
Model trained in 1.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.610
  Epoch 41/60
Model trained in 1.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.568
  Epoch 42/60
Model trained in 1.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.894
  Epoch 43/60
Model trained in 1.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.276
  Epoch 44/60
Model trained in 1.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.104
  Epoch 45/60
Model trained in 1.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.308
  Epoch 46/60
Model trained in 1.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.879
  Epoch 47/60
Model trained in 1.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.043
  Epoch 48/60
Model trained in 1.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.913
  Epoch 49/60
Model trained in 1.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.769
  Epoch 50/60
Model trained in 1.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.778
  Early stopping triggered.

  best_val_SMAPE=82.183

Combination 988/1152: {'encoder_hidden_size': 48, 'encoder_layers': 2, 'encoder_dropout': 0.0, 'decoder_hidden_size': 28, 'decoder_layers': 2, 'decoder_dropout': 0.2, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 20, 'batch_size': 64, 'sequence_length': 168}
Time: 282.01 minutes - estimated total time: 328.82 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 2.03s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 180.934
  Epoch 2/60
Model trained in 1.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 171.963
  Epoch 3/60
Model trained in 1.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 164.409
  Epoch 4/60
Model trained in 1.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 157.747
  Epoch 5/60
Model trained in 1.97s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 151.774
  Epoch 6/60
Model trained in 1.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 146.323
  Epoch 7/60
Model trained in 1.97s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 141.250
  Epoch 8/60
Model trained in 1.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 136.512
  Epoch 9/60
Model trained in 1.95s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 131.986
  Epoch 10/60
Model trained in 1.99s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 127.612
  Epoch 11/60
Model trained in 1.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 123.425
  Epoch 12/60
Model trained in 1.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 119.420
  Epoch 13/60
Model trained in 2.00s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 115.671
  Epoch 14/60
Model trained in 1.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 116.169
  Epoch 15/60
Model trained in 1.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 112.676
  Epoch 16/60
Model trained in 1.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 110.438
  Epoch 17/60
Model trained in 1.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 108.300
  Epoch 18/60
Model trained in 1.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 106.375
  Epoch 19/60
Model trained in 1.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 103.366
  Epoch 20/60
Model trained in 1.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 100.783
  Epoch 21/60
Model trained in 1.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 100.775
  Epoch 22/60
Model trained in 1.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 99.184
  Epoch 23/60
Model trained in 1.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 95.652
  Epoch 24/60
Model trained in 1.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.825
  Epoch 25/60
Model trained in 1.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.952
  Epoch 26/60
Model trained in 2.00s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.526
  Epoch 27/60
Model trained in 1.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.438
  Epoch 28/60
Model trained in 1.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.307
  Epoch 29/60
Model trained in 1.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.369
  Epoch 30/60
Model trained in 1.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.410
  Epoch 31/60
Model trained in 1.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.808
  Epoch 32/60
Model trained in 1.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.482
  Epoch 33/60
Model trained in 1.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.908
  Epoch 34/60
Model trained in 1.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.704
  Epoch 35/60
Model trained in 1.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.010
  Epoch 36/60
Model trained in 1.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.093
  Epoch 37/60
Model trained in 1.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.975
  Epoch 38/60
Model trained in 1.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.857
  Epoch 39/60
Model trained in 1.95s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.356
  Epoch 40/60
Model trained in 1.99s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.017
  Epoch 41/60
Model trained in 1.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.477
  Epoch 42/60
Model trained in 1.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.293
  Epoch 43/60
Model trained in 1.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.886
  Epoch 44/60
Model trained in 1.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.449
  Epoch 45/60
Model trained in 1.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.450
  Epoch 46/60
Model trained in 1.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.818
  Epoch 47/60
Model trained in 1.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.918
  Epoch 48/60
Model trained in 1.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.272
  Epoch 49/60
Model trained in 1.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.772
  Epoch 50/60
Model trained in 1.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.808
  Epoch 51/60
Model trained in 1.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.461
  Epoch 52/60
Model trained in 1.95s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.093
  Epoch 53/60
Model trained in 1.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.320
  Epoch 54/60
Model trained in 1.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.616
  Epoch 55/60
Model trained in 1.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.334
  Epoch 56/60
Model trained in 1.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.002
  Epoch 57/60
Model trained in 1.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.790
  Epoch 58/60
Model trained in 1.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.588
  Epoch 59/60
Model trained in 1.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.988
  Epoch 60/60
Model trained in 1.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.534

  best_val_SMAPE=76.790

Combination 989/1152: {'encoder_hidden_size': 48, 'encoder_layers': 2, 'encoder_dropout': 0.0, 'decoder_hidden_size': 28, 'decoder_layers': 2, 'decoder_dropout': 0.2, 'learning_rate': 0.0005, 'max_epochs': 60, 'patience': 20, 'batch_size': 32, 'sequence_length': 24}
Time: 284.40 minutes - estimated total time: 331.28 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 3.00s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 180.833
  Epoch 2/60
Model trained in 2.99s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 171.994
  Epoch 3/60
Model trained in 3.04s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 164.486
  Epoch 4/60
Model trained in 3.01s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 157.836
  Epoch 5/60
Model trained in 3.08s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 151.855
  Epoch 6/60
Model trained in 3.03s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 146.384
  Epoch 7/60
Model trained in 2.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 141.279
  Epoch 8/60
Model trained in 3.06s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 136.505
  Epoch 9/60
Model trained in 2.97s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 131.960
  Epoch 10/60
Model trained in 3.04s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 130.747
  Epoch 11/60
Model trained in 3.03s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 127.041
  Epoch 12/60
Model trained in 3.10s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 123.639
  Epoch 13/60
Model trained in 3.07s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 120.000
  Epoch 14/60
Model trained in 3.07s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 116.961
  Epoch 15/60
Model trained in 3.11s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 114.021
  Epoch 16/60
Model trained in 3.07s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 116.556
  Epoch 17/60
Model trained in 3.03s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 112.464
  Epoch 18/60
Model trained in 3.01s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 104.308
  Epoch 19/60
Model trained in 3.02s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 109.757
  Epoch 20/60
Model trained in 2.98s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 109.059
  Epoch 21/60
Model trained in 2.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 106.910
  Epoch 22/60
Model trained in 3.03s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 104.796
  Epoch 23/60
Model trained in 3.05s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 103.832
  Epoch 24/60
Model trained in 3.00s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 101.409
  Epoch 25/60
Model trained in 3.09s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 100.198
  Epoch 26/60
Model trained in 3.03s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 99.814
  Epoch 27/60
Model trained in 3.15s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 97.960
  Epoch 28/60
Model trained in 3.04s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 96.560
  Epoch 29/60
Model trained in 2.99s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.309
  Epoch 30/60
Model trained in 2.97s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.358
  Epoch 31/60
Model trained in 2.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.291
  Epoch 32/60
Model trained in 3.07s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.948
  Epoch 33/60
Model trained in 3.03s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.451
  Epoch 34/60
Model trained in 3.10s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.405
  Epoch 35/60
Model trained in 3.07s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.250
  Epoch 36/60
Model trained in 3.09s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.893
  Epoch 37/60
Model trained in 3.12s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.019
  Epoch 38/60
Model trained in 2.99s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.751
  Epoch 39/60
Model trained in 2.99s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.636
  Epoch 40/60
Model trained in 3.00s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.280
  Epoch 41/60
Model trained in 3.05s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.494
  Epoch 42/60
Model trained in 3.05s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.303
  Epoch 43/60
Model trained in 3.02s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.282
  Epoch 44/60
Model trained in 3.08s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.327
  Epoch 45/60
Model trained in 3.06s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.216
  Epoch 46/60
Model trained in 3.12s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.248
  Epoch 47/60
Model trained in 2.98s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.115
  Epoch 48/60
Model trained in 2.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.002
  Epoch 49/60
Model trained in 3.04s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.747
  Epoch 50/60
Model trained in 3.03s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.135
  Epoch 51/60
Model trained in 3.10s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.918
  Epoch 52/60
Model trained in 3.05s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.355
  Epoch 53/60
Model trained in 3.08s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.797
  Epoch 54/60
Model trained in 3.04s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.041
  Epoch 55/60
Model trained in 3.22s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.479
  Epoch 56/60
Model trained in 3.10s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.171
  Epoch 57/60
Model trained in 2.98s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.268
  Epoch 58/60
Model trained in 2.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.576
  Epoch 59/60
Model trained in 2.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.428
  Epoch 60/60
Model trained in 3.15s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.200

  best_val_SMAPE=75.171

Combination 990/1152: {'encoder_hidden_size': 48, 'encoder_layers': 2, 'encoder_dropout': 0.0, 'decoder_hidden_size': 28, 'decoder_layers': 2, 'decoder_dropout': 0.2, 'learning_rate': 0.0005, 'max_epochs': 60, 'patience': 20, 'batch_size': 32, 'sequence_length': 168}
Time: 287.93 minutes - estimated total time: 335.05 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 3.16s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 180.916
  Epoch 2/60
Model trained in 3.07s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 172.094
  Epoch 3/60
Model trained in 3.18s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 164.614
  Epoch 4/60
Model trained in 3.10s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 157.984
  Epoch 5/60
Model trained in 3.12s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 152.024
  Epoch 6/60
Model trained in 3.12s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 146.571
  Epoch 7/60
Model trained in 3.03s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 141.480
  Epoch 8/60
Model trained in 2.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 136.722
  Epoch 9/60
Model trained in 3.19s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 132.174
  Epoch 10/60
Model trained in 3.13s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 127.772
  Epoch 11/60
Model trained in 3.18s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 124.664
  Epoch 12/60
Model trained in 2.95s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 120.973
  Epoch 13/60
Model trained in 2.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 116.739
  Epoch 14/60
Model trained in 2.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 112.924
  Epoch 15/60
Model trained in 2.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 109.345
  Epoch 16/60
Model trained in 3.04s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 106.258
  Epoch 17/60
Model trained in 3.09s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 103.506
  Epoch 18/60
Model trained in 3.04s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 100.328
  Epoch 19/60
Model trained in 3.03s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 97.892
  Epoch 20/60
Model trained in 3.09s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 95.015
  Epoch 21/60
Model trained in 3.12s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.407
  Epoch 22/60
Model trained in 3.08s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.856
  Epoch 23/60
Model trained in 3.13s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.570
  Epoch 24/60
Model trained in 3.09s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.593
  Epoch 25/60
Model trained in 3.29s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.926
  Epoch 26/60
Model trained in 3.36s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.529
  Epoch 27/60
Model trained in 3.07s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.278
  Epoch 28/60
Model trained in 3.10s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.778
  Epoch 29/60
Model trained in 3.16s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.643
  Epoch 30/60
Model trained in 3.18s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.005
  Epoch 31/60
Model trained in 3.19s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.771
  Epoch 32/60
Model trained in 3.20s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.906
  Epoch 33/60
Model trained in 3.21s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.785
  Epoch 34/60
Model trained in 3.15s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.658
  Epoch 35/60
Model trained in 3.03s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.473
  Epoch 36/60
Model trained in 3.09s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.833
  Epoch 37/60
Model trained in 3.23s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.483
  Epoch 38/60
Model trained in 3.10s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.824
  Epoch 39/60
Model trained in 3.12s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.737
  Epoch 40/60
Model trained in 3.20s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.566
  Epoch 41/60
Model trained in 3.07s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.073
  Epoch 42/60
Model trained in 3.10s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.154
  Epoch 43/60
Model trained in 3.09s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.288
  Epoch 44/60
Model trained in 3.03s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.859
  Epoch 45/60
Model trained in 3.10s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.866
  Epoch 46/60
Model trained in 3.09s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.320
  Epoch 47/60
Model trained in 3.09s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.487
  Epoch 48/60
Model trained in 3.14s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.109
  Epoch 49/60
Model trained in 3.14s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.817
  Epoch 50/60
Model trained in 3.04s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.190
  Epoch 51/60
Model trained in 3.28s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.742
  Epoch 52/60
Model trained in 2.97s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.512
  Epoch 53/60
Model trained in 3.07s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.524
  Epoch 54/60
Model trained in 3.05s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.067
  Epoch 55/60
Model trained in 2.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.136
  Epoch 56/60
Model trained in 2.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.712
  Epoch 57/60
Model trained in 2.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.158
  Epoch 58/60
Model trained in 3.16s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.856
  Epoch 59/60
Model trained in 3.25s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.688
  Epoch 60/60
Model trained in 3.12s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.707
  Early stopping triggered.

  best_val_SMAPE=78.566

Combination 991/1152: {'encoder_hidden_size': 48, 'encoder_layers': 2, 'encoder_dropout': 0.0, 'decoder_hidden_size': 28, 'decoder_layers': 2, 'decoder_dropout': 0.2, 'learning_rate': 0.0005, 'max_epochs': 60, 'patience': 20, 'batch_size': 64, 'sequence_length': 24}
Time: 291.51 minutes - estimated total time: 338.87 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 1.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 186.761
  Epoch 2/60
Model trained in 1.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 180.788
  Epoch 3/60
Model trained in 1.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 176.124
  Epoch 4/60
Model trained in 1.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 171.912
  Epoch 5/60
Model trained in 1.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 168.019
  Epoch 6/60
Model trained in 1.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 164.371
  Epoch 7/60
Model trained in 1.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 160.916
  Epoch 8/60
Model trained in 1.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 157.695
  Epoch 9/60
Model trained in 1.99s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 154.608
  Epoch 10/60
Model trained in 1.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 151.690
  Epoch 11/60
Model trained in 1.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 148.895
  Epoch 12/60
Model trained in 1.97s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 146.196
  Epoch 13/60
Model trained in 1.99s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 143.580
  Epoch 14/60
Model trained in 1.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 141.074
  Epoch 15/60
Model trained in 1.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 138.638
  Epoch 16/60
Model trained in 1.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 136.558
  Epoch 17/60
Model trained in 1.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 133.992
  Epoch 18/60
Model trained in 1.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 133.065
  Epoch 19/60
Model trained in 1.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 130.349
  Epoch 20/60
Model trained in 1.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 128.389
  Epoch 21/60
Model trained in 1.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 126.592
  Epoch 22/60
Model trained in 1.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 124.541
  Epoch 23/60
Model trained in 1.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 122.703
  Epoch 24/60
Model trained in 1.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 120.855
  Epoch 25/60
Model trained in 1.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 119.039
  Epoch 26/60
Model trained in 1.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 118.074
  Epoch 27/60
Model trained in 1.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 116.253
  Epoch 28/60
Model trained in 1.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 114.102
  Epoch 29/60
Model trained in 1.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 112.222
  Epoch 30/60
Model trained in 1.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 111.040
  Epoch 31/60
Model trained in 1.68s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 109.192
  Epoch 32/60
Model trained in 1.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 107.478
  Epoch 33/60
Model trained in 1.68s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 105.637
  Epoch 34/60
Model trained in 1.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 104.220
  Epoch 35/60
Model trained in 1.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 102.796
  Epoch 36/60
Model trained in 1.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 101.667
  Epoch 37/60
Model trained in 1.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 100.538
  Epoch 38/60
Model trained in 1.68s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 99.411
  Epoch 39/60
Model trained in 1.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 98.255
  Epoch 40/60
Model trained in 1.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 96.971
  Epoch 41/60
Model trained in 1.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 96.307
  Epoch 42/60
Model trained in 1.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 95.520
  Epoch 43/60
Model trained in 1.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 94.700
  Epoch 44/60
Model trained in 1.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.677
  Epoch 45/60
Model trained in 1.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.651
  Epoch 46/60
Model trained in 1.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.834
  Epoch 47/60
Model trained in 1.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.149
  Epoch 48/60
Model trained in 1.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.344
  Epoch 49/60
Model trained in 1.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.183
  Epoch 50/60
Model trained in 1.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.421
  Epoch 51/60
Model trained in 1.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.849
  Epoch 52/60
Model trained in 1.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.710
  Epoch 53/60
Model trained in 1.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.322
  Epoch 54/60
Model trained in 1.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.620
  Epoch 55/60
Model trained in 1.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.076
  Epoch 56/60
Model trained in 1.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.484
  Epoch 57/60
Model trained in 1.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.063
  Epoch 58/60
Model trained in 1.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.308
  Epoch 59/60
Model trained in 1.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.604
  Epoch 60/60
Model trained in 1.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.270

  best_val_SMAPE=83.270

Combination 992/1152: {'encoder_hidden_size': 48, 'encoder_layers': 2, 'encoder_dropout': 0.0, 'decoder_hidden_size': 28, 'decoder_layers': 2, 'decoder_dropout': 0.2, 'learning_rate': 0.0005, 'max_epochs': 60, 'patience': 20, 'batch_size': 64, 'sequence_length': 168}
Time: 293.83 minutes - estimated total time: 341.22 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 2.05s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 186.802
  Epoch 2/60
Model trained in 2.05s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 180.849
  Epoch 3/60
Model trained in 1.95s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 176.205
  Epoch 4/60
Model trained in 1.98s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 172.012
  Epoch 5/60
Model trained in 2.01s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 168.139
  Epoch 6/60
Model trained in 1.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 164.506
  Epoch 7/60
Model trained in 2.02s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 161.068
  Epoch 8/60
Model trained in 1.95s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 157.856
  Epoch 9/60
Model trained in 1.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 154.785
  Epoch 10/60
Model trained in 1.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 151.876
  Epoch 11/60
Model trained in 2.10s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 149.092
  Epoch 12/60
Model trained in 2.04s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 146.404
  Epoch 13/60
Model trained in 1.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 143.797
  Epoch 14/60
Model trained in 1.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 141.299
  Epoch 15/60
Model trained in 1.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 138.875
  Epoch 16/60
Model trained in 1.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 136.525
  Epoch 17/60
Model trained in 1.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 134.224
  Epoch 18/60
Model trained in 2.06s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 131.958
  Epoch 19/60
Model trained in 2.00s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 129.727
  Epoch 20/60
Model trained in 2.03s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 127.540
  Epoch 21/60
Model trained in 2.03s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 126.634
  Epoch 22/60
Model trained in 1.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 125.564
  Epoch 23/60
Model trained in 1.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 123.298
  Epoch 24/60
Model trained in 1.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 121.205
  Epoch 25/60
Model trained in 1.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 119.329
  Epoch 26/60
Model trained in 1.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 117.589
  Epoch 27/60
Model trained in 2.17s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 115.613
  Epoch 28/60
Model trained in 1.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 113.870
  Epoch 29/60
Model trained in 1.98s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 112.164
  Epoch 30/60
Model trained in 2.16s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 110.412
  Epoch 31/60
Model trained in 2.14s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 108.516
  Epoch 32/60
Model trained in 2.23s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 106.705
  Epoch 33/60
Model trained in 2.19s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 105.041
  Epoch 34/60
Model trained in 1.98s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 103.499
  Epoch 35/60
Model trained in 2.02s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 101.966
  Epoch 36/60
Model trained in 2.08s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 100.021
  Epoch 37/60
Model trained in 2.23s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 98.487
  Epoch 38/60
Model trained in 1.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 97.420
  Epoch 39/60
Model trained in 2.09s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 96.234
  Epoch 40/60
Model trained in 2.01s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 94.888
  Epoch 41/60
Model trained in 2.06s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.843
  Epoch 42/60
Model trained in 2.10s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.053
  Epoch 43/60
Model trained in 2.19s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.993
  Epoch 44/60
Model trained in 1.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.243
  Epoch 45/60
Model trained in 2.16s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.469
  Epoch 46/60
Model trained in 2.14s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.647
  Epoch 47/60
Model trained in 2.03s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.778
  Epoch 48/60
Model trained in 1.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.712
  Epoch 49/60
Model trained in 1.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.211
  Epoch 50/60
Model trained in 1.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.511
  Epoch 51/60
Model trained in 1.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.293
  Epoch 52/60
Model trained in 2.00s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.370
  Epoch 53/60
Model trained in 1.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.911
  Epoch 54/60
Model trained in 1.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.278
  Epoch 55/60
Model trained in 1.98s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.809
  Epoch 56/60
Model trained in 1.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.292
  Epoch 57/60
Model trained in 1.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.151
  Epoch 58/60
Model trained in 1.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.882
  Epoch 59/60
Model trained in 1.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.761
  Epoch 60/60
Model trained in 1.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.588

  best_val_SMAPE=83.588

Combination 993/1152: {'encoder_hidden_size': 48, 'encoder_layers': 2, 'encoder_dropout': 0.0, 'decoder_hidden_size': 33, 'decoder_layers': 1, 'decoder_dropout': 0.0, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 20, 'batch_size': 32, 'sequence_length': 24}
Time: 296.30 minutes - estimated total time: 343.74 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 2.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 168.311
  Epoch 2/60
Model trained in 3.20s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 152.788
  Epoch 3/60
Model trained in 3.09s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 140.660
  Epoch 4/60
Model trained in 3.01s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 130.330
  Epoch 5/60
Model trained in 3.43s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 120.992
  Epoch 6/60
Model trained in 2.99s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 112.770
  Epoch 7/60
Model trained in 3.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 105.879
  Epoch 8/60
Model trained in 3.31s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 99.448
  Epoch 9/60
Model trained in 3.29s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 94.150
  Epoch 10/60
Model trained in 3.44s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.788
  Epoch 11/60
Model trained in 3.09s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.828
  Epoch 12/60
Model trained in 3.48s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.724
  Epoch 13/60
Model trained in 2.97s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.337
  Epoch 14/60
Model trained in 3.06s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.453
  Epoch 15/60
Model trained in 3.19s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.251
  Epoch 16/60
Model trained in 3.15s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.944
  Epoch 17/60
Model trained in 3.30s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.984
  Epoch 18/60
Model trained in 3.21s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.260
  Epoch 19/60
Model trained in 3.11s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.070
  Epoch 20/60
Model trained in 3.06s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.595
  Epoch 21/60
Model trained in 3.25s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.866
  Epoch 22/60
Model trained in 3.15s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 94.930
  Epoch 23/60
Model trained in 3.06s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 103.036
  Epoch 24/60
Model trained in 3.18s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 104.949
  Epoch 25/60
Model trained in 3.18s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 106.616
  Epoch 26/60
Model trained in 3.21s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 106.388
  Epoch 27/60
Model trained in 3.18s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 104.148
  Epoch 28/60
Model trained in 3.13s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 102.262
  Epoch 29/60
Model trained in 3.10s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 101.107
  Epoch 30/60
Model trained in 3.20s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 99.127
  Epoch 31/60
Model trained in 3.30s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.786
  Epoch 32/60
Model trained in 3.08s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 100.486
  Epoch 33/60
Model trained in 3.23s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.591
  Epoch 34/60
Model trained in 3.23s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.065
  Epoch 35/60
Model trained in 3.18s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.030
  Epoch 36/60
Model trained in 3.26s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.760
  Epoch 37/60
Model trained in 3.11s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.404
  Early stopping triggered.

  best_val_SMAPE=83.984

Combination 994/1152: {'encoder_hidden_size': 48, 'encoder_layers': 2, 'encoder_dropout': 0.0, 'decoder_hidden_size': 33, 'decoder_layers': 1, 'decoder_dropout': 0.0, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 20, 'batch_size': 32, 'sequence_length': 168}
Time: 298.64 minutes - estimated total time: 346.11 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 3.41s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 168.404
  Epoch 2/60
Model trained in 3.49s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 152.928
  Epoch 3/60
Model trained in 3.32s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 140.749
  Epoch 4/60
Model trained in 3.26s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 130.580
  Epoch 5/60
Model trained in 3.25s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 121.457
  Epoch 6/60
Model trained in 3.36s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 114.009
  Epoch 7/60
Model trained in 3.53s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 107.063
  Epoch 8/60
Model trained in 3.43s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 100.533
  Epoch 9/60
Model trained in 3.33s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 95.811
  Epoch 10/60
Model trained in 3.16s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.049
  Epoch 11/60
Model trained in 3.33s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.692
  Epoch 12/60
Model trained in 3.23s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.594
  Epoch 13/60
Model trained in 3.09s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.192
  Epoch 14/60
Model trained in 3.14s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.032
  Epoch 15/60
Model trained in 3.09s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.459
  Epoch 16/60
Model trained in 3.29s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.205
  Epoch 17/60
Model trained in 3.19s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.792
  Epoch 18/60
Model trained in 3.12s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.659
  Epoch 19/60
Model trained in 3.15s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.232
  Epoch 20/60
Model trained in 3.32s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.373
  Epoch 21/60
Model trained in 3.27s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.001
  Epoch 22/60
Model trained in 3.22s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.842
  Epoch 23/60
Model trained in 3.23s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.689
  Epoch 24/60
Model trained in 3.19s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.733
  Epoch 25/60
Model trained in 3.39s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.269
  Epoch 26/60
Model trained in 3.25s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.318
  Epoch 27/60
Model trained in 3.16s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.908
  Epoch 28/60
Model trained in 3.22s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.520
  Epoch 29/60
Model trained in 3.30s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.395
  Epoch 30/60
Model trained in 3.24s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.937
  Epoch 31/60
Model trained in 3.24s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.866
  Epoch 32/60
Model trained in 3.17s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.966
  Epoch 33/60
Model trained in 3.13s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 94.341
  Epoch 34/60
Model trained in 3.21s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 94.209
  Epoch 35/60
Model trained in 3.15s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 95.691
  Early stopping triggered.

  best_val_SMAPE=74.459

Combination 995/1152: {'encoder_hidden_size': 48, 'encoder_layers': 2, 'encoder_dropout': 0.0, 'decoder_hidden_size': 33, 'decoder_layers': 1, 'decoder_dropout': 0.0, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 20, 'batch_size': 64, 'sequence_length': 24}
Time: 300.89 minutes - estimated total time: 348.37 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 1.95s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 178.210
  Epoch 2/60
Model trained in 2.03s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 168.153
  Epoch 3/60
Model trained in 1.95s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 159.767
  Epoch 4/60
Model trained in 2.06s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 152.584
  Epoch 5/60
Model trained in 2.04s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 146.234
  Epoch 6/60
Model trained in 2.00s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 140.465
  Epoch 7/60
Model trained in 1.97s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 135.211
  Epoch 8/60
Model trained in 1.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 130.162
  Epoch 9/60
Model trained in 1.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 125.291
  Epoch 10/60
Model trained in 2.01s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 120.915
  Epoch 11/60
Model trained in 2.05s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 116.661
  Epoch 12/60
Model trained in 1.99s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 112.855
  Epoch 13/60
Model trained in 1.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 109.079
  Epoch 14/60
Model trained in 1.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 105.482
  Epoch 15/60
Model trained in 1.95s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 102.220
  Epoch 16/60
Model trained in 1.97s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 99.752
  Epoch 17/60
Model trained in 1.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 97.397
  Epoch 18/60
Model trained in 2.01s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 95.258
  Epoch 19/60
Model trained in 2.00s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.532
  Epoch 20/60
Model trained in 1.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.230
  Epoch 21/60
Model trained in 1.97s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.949
  Epoch 22/60
Model trained in 1.98s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.321
  Epoch 23/60
Model trained in 1.97s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.735
  Epoch 24/60
Model trained in 1.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.129
  Epoch 25/60
Model trained in 1.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.027
  Epoch 26/60
Model trained in 2.01s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.950
  Epoch 27/60
Model trained in 1.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.674
  Epoch 28/60
Model trained in 1.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.069
  Epoch 29/60
Model trained in 1.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.885
  Epoch 30/60
Model trained in 1.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.585
  Epoch 31/60
Model trained in 1.95s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.327
  Epoch 32/60
Model trained in 2.14s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.411
  Epoch 33/60
Model trained in 2.02s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.957
  Epoch 34/60
Model trained in 1.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.629
  Epoch 35/60
Model trained in 1.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.293
  Epoch 36/60
Model trained in 2.01s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.805
  Epoch 37/60
Model trained in 1.97s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.054
  Epoch 38/60
Model trained in 1.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.241
  Epoch 39/60
Model trained in 1.97s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.900
  Epoch 40/60
Model trained in 2.09s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.986
  Epoch 41/60
Model trained in 1.95s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.165
  Epoch 42/60
Model trained in 1.98s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.178
  Epoch 43/60
Model trained in 1.95s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.710
  Epoch 44/60
Model trained in 1.97s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.777
  Epoch 45/60
Model trained in 1.98s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.318
  Epoch 46/60
Model trained in 2.16s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.533
  Epoch 47/60
Model trained in 2.02s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.000
  Epoch 48/60
Model trained in 1.95s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.019
  Epoch 49/60
Model trained in 2.04s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.476
  Epoch 50/60
Model trained in 1.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.196
  Early stopping triggered.

  best_val_SMAPE=79.585

Combination 996/1152: {'encoder_hidden_size': 48, 'encoder_layers': 2, 'encoder_dropout': 0.0, 'decoder_hidden_size': 33, 'decoder_layers': 1, 'decoder_dropout': 0.0, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 20, 'batch_size': 64, 'sequence_length': 168}
Time: 303.02 minutes - estimated total time: 350.48 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 2.22s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 178.297
  Epoch 2/60
Model trained in 2.36s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 168.287
  Epoch 3/60
Model trained in 2.14s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 159.938
  Epoch 4/60
Model trained in 2.09s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 152.789
  Epoch 5/60
Model trained in 2.09s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 146.444
  Epoch 6/60
Model trained in 2.19s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 140.539
  Epoch 7/60
Model trained in 2.11s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 135.524
  Epoch 8/60
Model trained in 2.18s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 130.500
  Epoch 9/60
Model trained in 2.20s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 125.825
  Epoch 10/60
Model trained in 2.12s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 121.422
  Epoch 11/60
Model trained in 2.06s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 117.191
  Epoch 12/60
Model trained in 2.12s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 113.511
  Epoch 13/60
Model trained in 2.08s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 109.889
  Epoch 14/60
Model trained in 2.14s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 106.603
  Epoch 15/60
Model trained in 2.25s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 103.352
  Epoch 16/60
Model trained in 2.16s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 99.953
  Epoch 17/60
Model trained in 2.13s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 97.787
  Epoch 18/60
Model trained in 2.14s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 94.121
  Epoch 19/60
Model trained in 2.08s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.100
  Epoch 20/60
Model trained in 2.15s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.148
  Epoch 21/60
Model trained in 2.11s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.222
  Epoch 22/60
Model trained in 2.18s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.527
  Epoch 23/60
Model trained in 2.04s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.126
  Epoch 24/60
Model trained in 1.99s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.085
  Epoch 25/60
Model trained in 2.00s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.996
  Epoch 26/60
Model trained in 2.00s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.048
  Epoch 27/60
Model trained in 2.04s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.576
  Epoch 28/60
Model trained in 2.12s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.102
  Epoch 29/60
Model trained in 2.13s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.521
  Epoch 30/60
Model trained in 2.02s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.822
  Epoch 31/60
Model trained in 2.03s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.999
  Epoch 32/60
Model trained in 2.02s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.745
  Epoch 33/60
Model trained in 2.04s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.009
  Epoch 34/60
Model trained in 2.17s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.933
  Epoch 35/60
Model trained in 2.30s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.538
  Epoch 36/60
Model trained in 2.12s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.523
  Epoch 37/60
Model trained in 2.10s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.516
  Epoch 38/60
Model trained in 2.11s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.665
  Epoch 39/60
Model trained in 2.19s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.559
  Epoch 40/60
Model trained in 2.16s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.972
  Epoch 41/60
Model trained in 2.07s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.892
  Epoch 42/60
Model trained in 2.22s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.415
  Epoch 43/60
Model trained in 2.17s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.229
  Epoch 44/60
Model trained in 2.08s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.269
  Epoch 45/60
Model trained in 2.06s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.419
  Epoch 46/60
Model trained in 2.14s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.782
  Epoch 47/60
Model trained in 2.19s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.234
  Epoch 48/60
Model trained in 2.09s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.298
  Epoch 49/60
Model trained in 2.15s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.557
  Epoch 50/60
Model trained in 2.16s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.557
  Epoch 51/60
Model trained in 2.18s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.157
  Epoch 52/60
Model trained in 2.06s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.534
  Epoch 53/60
Model trained in 2.12s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.916
  Epoch 54/60
Model trained in 2.11s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.334
  Epoch 55/60
Model trained in 2.18s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.407
  Epoch 56/60
Model trained in 2.05s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.130
  Early stopping triggered.

  best_val_SMAPE=75.523

Combination 997/1152: {'encoder_hidden_size': 48, 'encoder_layers': 2, 'encoder_dropout': 0.0, 'decoder_hidden_size': 33, 'decoder_layers': 1, 'decoder_dropout': 0.0, 'learning_rate': 0.0005, 'max_epochs': 60, 'patience': 20, 'batch_size': 32, 'sequence_length': 24}
Time: 305.53 minutes - estimated total time: 353.03 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 3.09s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 178.265
  Epoch 2/60
Model trained in 3.12s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 168.448
  Epoch 3/60
Model trained in 3.16s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 160.111
  Epoch 4/60
Model trained in 3.10s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 152.937
  Epoch 5/60
Model trained in 3.13s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 146.587
  Epoch 6/60
Model trained in 3.07s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 140.808
  Epoch 7/60
Model trained in 3.06s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 135.422
  Epoch 8/60
Model trained in 3.28s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 130.236
  Epoch 9/60
Model trained in 3.08s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 125.399
  Epoch 10/60
Model trained in 3.07s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 120.837
  Epoch 11/60
Model trained in 3.16s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 117.136
  Epoch 12/60
Model trained in 3.10s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 113.568
  Epoch 13/60
Model trained in 3.18s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 109.166
  Epoch 14/60
Model trained in 3.08s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 105.537
  Epoch 15/60
Model trained in 3.10s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 102.632
  Epoch 16/60
Model trained in 3.12s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 99.762
  Epoch 17/60
Model trained in 3.11s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 96.882
  Epoch 18/60
Model trained in 3.18s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 94.425
  Epoch 19/60
Model trained in 3.06s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.956
  Epoch 20/60
Model trained in 3.04s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.524
  Epoch 21/60
Model trained in 3.04s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.854
  Epoch 22/60
Model trained in 3.11s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.000
  Epoch 23/60
Model trained in 3.08s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.028
  Epoch 24/60
Model trained in 3.12s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.386
  Epoch 25/60
Model trained in 2.99s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.649
  Epoch 26/60
Model trained in 3.00s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.195
  Epoch 27/60
Model trained in 3.35s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.024
  Epoch 28/60
Model trained in 3.03s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.132
  Epoch 29/60
Model trained in 3.08s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.806
  Epoch 30/60
Model trained in 3.06s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.316
  Epoch 31/60
Model trained in 3.05s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.134
  Epoch 32/60
Model trained in 3.21s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.740
  Epoch 33/60
Model trained in 3.06s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.970
  Epoch 34/60
Model trained in 3.02s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.617
  Epoch 35/60
Model trained in 2.99s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.054
  Epoch 36/60
Model trained in 3.18s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.472
  Epoch 37/60
Model trained in 3.13s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.887
  Epoch 38/60
Model trained in 3.14s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.884
  Epoch 39/60
Model trained in 3.12s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.387
  Epoch 40/60
Model trained in 3.08s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.113
  Epoch 41/60
Model trained in 3.28s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.625
  Epoch 42/60
Model trained in 3.08s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.042
  Epoch 43/60
Model trained in 3.08s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.309
  Epoch 44/60
Model trained in 3.03s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.009
  Epoch 45/60
Model trained in 3.06s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.228
  Epoch 46/60
Model trained in 3.23s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.809
  Epoch 47/60
Model trained in 3.10s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.719
  Epoch 48/60
Model trained in 3.03s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.023
  Epoch 49/60
Model trained in 3.07s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.697
  Epoch 50/60
Model trained in 3.12s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.213
  Epoch 51/60
Model trained in 3.04s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.168
  Epoch 52/60
Model trained in 2.99s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.711
  Epoch 53/60
Model trained in 3.03s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.319
  Epoch 54/60
Model trained in 3.00s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.986
  Epoch 55/60
Model trained in 3.14s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.606
  Epoch 56/60
Model trained in 3.01s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.834
  Epoch 57/60
Model trained in 2.98s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.399
  Epoch 58/60
Model trained in 3.04s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.703
  Epoch 59/60
Model trained in 3.06s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.527
  Epoch 60/60
Model trained in 3.22s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.778

  best_val_SMAPE=76.042

Combination 998/1152: {'encoder_hidden_size': 48, 'encoder_layers': 2, 'encoder_dropout': 0.0, 'decoder_hidden_size': 33, 'decoder_layers': 1, 'decoder_dropout': 0.0, 'learning_rate': 0.0005, 'max_epochs': 60, 'patience': 20, 'batch_size': 32, 'sequence_length': 168}
Time: 309.20 minutes - estimated total time: 356.91 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 3.26s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 178.345
  Epoch 2/60
Model trained in 3.21s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 168.528
  Epoch 3/60
Model trained in 3.31s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 160.265
  Epoch 4/60
Model trained in 3.44s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 153.100
  Epoch 5/60
Model trained in 3.18s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 146.684
  Epoch 6/60
Model trained in 3.29s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 140.964
  Epoch 7/60
Model trained in 3.14s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 135.682
  Epoch 8/60
Model trained in 3.30s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 130.589
  Epoch 9/60
Model trained in 3.44s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 125.720
  Epoch 10/60
Model trained in 3.20s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 121.162
  Epoch 11/60
Model trained in 3.18s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 117.031
  Epoch 12/60
Model trained in 3.18s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 113.046
  Epoch 13/60
Model trained in 3.29s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 110.137
  Epoch 14/60
Model trained in 3.18s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 106.192
  Epoch 15/60
Model trained in 3.19s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 102.971
  Epoch 16/60
Model trained in 3.15s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 99.993
  Epoch 17/60
Model trained in 3.07s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 97.302
  Epoch 18/60
Model trained in 3.24s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 94.821
  Epoch 19/60
Model trained in 3.09s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.563
  Epoch 20/60
Model trained in 3.14s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.791
  Epoch 21/60
Model trained in 3.15s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.602
  Epoch 22/60
Model trained in 3.18s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.497
  Epoch 23/60
Model trained in 3.14s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.707
  Epoch 24/60
Model trained in 3.14s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.788
  Epoch 25/60
Model trained in 3.21s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.556
  Epoch 26/60
Model trained in 3.18s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.858
  Epoch 27/60
Model trained in 3.43s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.770
  Epoch 28/60
Model trained in 3.20s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.809
  Epoch 29/60
Model trained in 3.20s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.421
  Epoch 30/60
Model trained in 3.18s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.174
  Epoch 31/60
Model trained in 3.11s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.089
  Epoch 32/60
Model trained in 3.59s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.304
  Epoch 33/60
Model trained in 3.21s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.243
  Epoch 34/60
Model trained in 3.29s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.449
  Epoch 35/60
Model trained in 3.42s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.550
  Epoch 36/60
Model trained in 3.51s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.843
  Epoch 37/60
Model trained in 3.30s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.301
  Epoch 38/60
Model trained in 3.39s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.166
  Epoch 39/60
Model trained in 3.28s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.753
  Epoch 40/60
Model trained in 3.25s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.763
  Epoch 41/60
Model trained in 3.28s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.063
  Epoch 42/60
Model trained in 3.09s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.318
  Epoch 43/60
Model trained in 3.14s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.787
  Epoch 44/60
Model trained in 3.21s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.814
  Epoch 45/60
Model trained in 3.41s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.384
  Epoch 46/60
Model trained in 3.19s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.956
  Epoch 47/60
Model trained in 3.11s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.281
  Epoch 48/60
Model trained in 3.16s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.539
  Epoch 49/60
Model trained in 3.22s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.451
  Epoch 50/60
Model trained in 3.39s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.186
  Epoch 51/60
Model trained in 3.25s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.871
  Epoch 52/60
Model trained in 3.37s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.735
  Epoch 53/60
Model trained in 3.28s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.823
  Epoch 54/60
Model trained in 3.36s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.291
  Epoch 55/60
Model trained in 3.29s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 94.769
  Epoch 56/60
Model trained in 3.20s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 104.528
  Epoch 57/60
Model trained in 3.23s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 96.498
  Epoch 58/60
Model trained in 3.31s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.310
  Epoch 59/60
Model trained in 3.27s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 98.281
  Epoch 60/60
Model trained in 3.23s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 107.053

  best_val_SMAPE=79.814

Combination 999/1152: {'encoder_hidden_size': 48, 'encoder_layers': 2, 'encoder_dropout': 0.0, 'decoder_hidden_size': 33, 'decoder_layers': 1, 'decoder_dropout': 0.0, 'learning_rate': 0.0005, 'max_epochs': 60, 'patience': 20, 'batch_size': 64, 'sequence_length': 24}
Time: 313.01 minutes - estimated total time: 360.95 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 1.97s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 184.824
  Epoch 2/60
Model trained in 1.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 178.166
  Epoch 3/60
Model trained in 1.95s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 172.937
  Epoch 4/60
Model trained in 2.13s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 168.324
  Epoch 5/60
Model trained in 2.14s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 163.983
  Epoch 6/60
Model trained in 1.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 159.949
  Epoch 7/60
Model trained in 1.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 156.252
  Epoch 8/60
Model trained in 1.99s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 152.756
  Epoch 9/60
Model trained in 1.98s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 149.490
  Epoch 10/60
Model trained in 1.97s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 146.385
  Epoch 11/60
Model trained in 2.03s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 143.413
  Epoch 12/60
Model trained in 1.95s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 140.651
  Epoch 13/60
Model trained in 2.00s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 137.936
  Epoch 14/60
Model trained in 2.26s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 135.162
  Epoch 15/60
Model trained in 2.05s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 132.515
  Epoch 16/60
Model trained in 1.98s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 130.003
  Epoch 17/60
Model trained in 1.98s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 127.509
  Epoch 18/60
Model trained in 2.04s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 125.351
  Epoch 19/60
Model trained in 1.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 123.009
  Epoch 20/60
Model trained in 1.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 120.713
  Epoch 21/60
Model trained in 1.95s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 118.648
  Epoch 22/60
Model trained in 1.95s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 116.854
  Epoch 23/60
Model trained in 1.95s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 115.046
  Epoch 24/60
Model trained in 2.01s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 113.112
  Epoch 25/60
Model trained in 2.05s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 111.405
  Epoch 26/60
Model trained in 2.05s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 110.352
  Epoch 27/60
Model trained in 1.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 108.588
  Epoch 28/60
Model trained in 1.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 105.839
  Epoch 29/60
Model trained in 1.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 104.344
  Epoch 30/60
Model trained in 2.00s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 102.727
  Epoch 31/60
Model trained in 2.01s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 101.028
  Epoch 32/60
Model trained in 2.01s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 99.455
  Epoch 33/60
Model trained in 2.00s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 97.960
  Epoch 34/60
Model trained in 2.00s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 96.506
  Epoch 35/60
Model trained in 1.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 95.070
  Epoch 36/60
Model trained in 1.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.677
  Epoch 37/60
Model trained in 1.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.689
  Epoch 38/60
Model trained in 1.99s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.484
  Epoch 39/60
Model trained in 2.00s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.538
  Epoch 40/60
Model trained in 1.95s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.827
  Epoch 41/60
Model trained in 1.97s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 97.673
  Epoch 42/60
Model trained in 1.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 97.317
  Epoch 43/60
Model trained in 1.98s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 94.786
  Epoch 44/60
Model trained in 1.99s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.156
  Epoch 45/60
Model trained in 1.98s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.674
  Epoch 46/60
Model trained in 2.08s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.072
  Epoch 47/60
Model trained in 2.03s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.527
  Epoch 48/60
Model trained in 1.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.664
  Epoch 49/60
Model trained in 1.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.974
  Epoch 50/60
Model trained in 1.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.430
  Epoch 51/60
Model trained in 1.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.709
  Epoch 52/60
Model trained in 1.97s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.059
  Epoch 53/60
Model trained in 2.05s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.369
  Epoch 54/60
Model trained in 1.95s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.015
  Epoch 55/60
Model trained in 1.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.469
  Epoch 56/60
Model trained in 2.03s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.173
  Epoch 57/60
Model trained in 1.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.487
  Epoch 58/60
Model trained in 1.97s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.832
  Epoch 59/60
Model trained in 1.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.527
  Epoch 60/60
Model trained in 2.10s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.347

  best_val_SMAPE=76.347

Combination 1000/1152: {'encoder_hidden_size': 48, 'encoder_layers': 2, 'encoder_dropout': 0.0, 'decoder_hidden_size': 33, 'decoder_layers': 1, 'decoder_dropout': 0.0, 'learning_rate': 0.0005, 'max_epochs': 60, 'patience': 20, 'batch_size': 64, 'sequence_length': 168}
Time: 315.57 minutes - estimated total time: 363.54 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 2.09s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 184.878
  Epoch 2/60
Model trained in 2.10s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 178.237
  Epoch 3/60
Model trained in 2.14s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 173.031
  Epoch 4/60
Model trained in 2.10s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 168.393
  Epoch 5/60
Model trained in 2.24s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 164.121
  Epoch 6/60
Model trained in 2.19s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 160.111
  Epoch 7/60
Model trained in 2.16s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 156.422
  Epoch 8/60
Model trained in 2.16s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 152.973
  Epoch 9/60
Model trained in 2.07s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 149.653
  Epoch 10/60
Model trained in 2.08s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 146.706
  Epoch 11/60
Model trained in 2.10s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 144.591
  Epoch 12/60
Model trained in 2.26s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 143.175
  Epoch 13/60
Model trained in 2.06s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 139.656
  Epoch 14/60
Model trained in 2.08s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 135.552
  Epoch 15/60
Model trained in 2.06s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 132.931
  Epoch 16/60
Model trained in 2.14s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 130.348
  Epoch 17/60
Model trained in 2.11s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 127.924
  Epoch 18/60
Model trained in 2.13s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 125.571
  Epoch 19/60
Model trained in 2.19s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 123.228
  Epoch 20/60
Model trained in 2.08s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 120.962
  Epoch 21/60
Model trained in 2.09s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 118.848
  Epoch 22/60
Model trained in 2.05s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 116.726
  Epoch 23/60
Model trained in 2.03s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 114.674
  Epoch 24/60
Model trained in 2.03s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 112.853
  Epoch 25/60
Model trained in 2.15s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 111.568
  Epoch 26/60
Model trained in 2.04s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 109.328
  Epoch 27/60
Model trained in 2.05s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 107.580
  Epoch 28/60
Model trained in 2.18s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 106.404
  Epoch 29/60
Model trained in 2.09s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 104.460
  Epoch 30/60
Model trained in 2.05s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 103.081
  Epoch 31/60
Model trained in 2.08s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 109.472
  Epoch 32/60
Model trained in 2.27s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 108.083
  Epoch 33/60
Model trained in 2.23s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 106.192
  Epoch 34/60
Model trained in 2.13s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 105.962
  Epoch 35/60
Model trained in 2.08s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 105.230
  Epoch 36/60
Model trained in 2.15s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 95.983
  Epoch 37/60
Model trained in 2.12s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 95.015
  Epoch 38/60
Model trained in 2.14s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 94.034
  Epoch 39/60
Model trained in 2.21s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.708
  Epoch 40/60
Model trained in 2.15s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.125
  Epoch 41/60
Model trained in 2.14s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.777
  Epoch 42/60
Model trained in 2.07s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.612
  Epoch 43/60
Model trained in 2.09s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.774
  Epoch 44/60
Model trained in 2.17s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.007
  Epoch 45/60
Model trained in 2.34s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.224
  Epoch 46/60
Model trained in 2.17s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.439
  Epoch 47/60
Model trained in 2.08s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.964
  Epoch 48/60
Model trained in 2.19s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.617
  Epoch 49/60
Model trained in 2.09s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.252
  Epoch 50/60
Model trained in 2.07s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.869
  Epoch 51/60
Model trained in 2.10s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.322
  Epoch 52/60
Model trained in 2.13s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.215
  Epoch 53/60
Model trained in 2.08s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.207
  Epoch 54/60
Model trained in 2.11s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.316
  Epoch 55/60
Model trained in 2.10s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.806
  Epoch 56/60
Model trained in 2.16s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.751
  Epoch 57/60
Model trained in 2.02s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.127
  Epoch 58/60
Model trained in 2.06s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.609
  Epoch 59/60
Model trained in 2.19s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.759
  Epoch 60/60
Model trained in 2.13s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.312

  best_val_SMAPE=80.609

Combination 1009/1152: {'encoder_hidden_size': 48, 'encoder_layers': 2, 'encoder_dropout': 0.0, 'decoder_hidden_size': 33, 'decoder_layers': 2, 'decoder_dropout': 0.0, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 20, 'batch_size': 32, 'sequence_length': 24}
Time: 318.26 minutes - estimated total time: 363.36 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 3.25s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 169.040
  Epoch 2/60
Model trained in 3.22s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 153.337
  Epoch 3/60
Model trained in 3.44s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 140.882
  Epoch 4/60
Model trained in 3.21s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 130.134
  Epoch 5/60
Model trained in 3.28s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 123.428
  Epoch 6/60
Model trained in 3.23s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 115.966
  Epoch 7/60
Model trained in 3.34s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 108.445
  Epoch 8/60
Model trained in 3.44s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 103.153
  Epoch 9/60
Model trained in 3.18s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 103.209
  Epoch 10/60
Model trained in 3.21s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 98.330
  Epoch 11/60
Model trained in 3.33s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 95.282
  Epoch 12/60
Model trained in 3.42s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.175
  Epoch 13/60
Model trained in 3.23s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.826
  Epoch 14/60
Model trained in 3.28s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.464
  Epoch 15/60
Model trained in 3.35s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.086
  Epoch 16/60
Model trained in 3.29s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.441
  Epoch 17/60
Model trained in 3.27s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.965
  Epoch 18/60
Model trained in 3.26s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.196
  Epoch 19/60
Model trained in 3.25s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.366
  Epoch 20/60
Model trained in 3.25s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.335
  Epoch 21/60
Model trained in 3.20s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.074
  Epoch 22/60
Model trained in 3.03s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.137
  Epoch 23/60
Model trained in 2.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.852
  Epoch 24/60
Model trained in 2.97s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.748
  Epoch 25/60
Model trained in 3.03s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.963
  Epoch 26/60
Model trained in 3.03s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.955
  Epoch 27/60
Model trained in 2.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.054
  Epoch 28/60
Model trained in 3.01s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.077
  Epoch 29/60
Model trained in 3.02s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.292
  Epoch 30/60
Model trained in 2.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.444
  Epoch 31/60
Model trained in 2.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.961
  Epoch 32/60
Model trained in 2.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.168
  Epoch 33/60
Model trained in 2.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.744
  Epoch 34/60
Model trained in 2.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.726
  Epoch 35/60
Model trained in 2.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.700
  Epoch 36/60
Model trained in 2.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.724
  Epoch 37/60
Model trained in 2.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.549
  Epoch 38/60
Model trained in 3.00s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.904
  Epoch 39/60
Model trained in 2.98s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.028
  Epoch 40/60
Model trained in 3.04s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.612
  Epoch 41/60
Model trained in 3.04s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.517
  Epoch 42/60
Model trained in 2.95s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.840
  Epoch 43/60
Model trained in 2.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.387
  Epoch 44/60
Model trained in 2.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.082
  Epoch 45/60
Model trained in 2.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.040
  Epoch 46/60
Model trained in 3.00s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.172
  Epoch 47/60
Model trained in 2.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.579
  Epoch 48/60
Model trained in 3.01s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.461
  Epoch 49/60
Model trained in 2.99s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.199
  Epoch 50/60
Model trained in 2.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.037
  Epoch 51/60
Model trained in 2.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.910
  Epoch 52/60
Model trained in 2.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.104
  Epoch 53/60
Model trained in 2.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.123
  Epoch 54/60
Model trained in 2.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.027
  Epoch 55/60
Model trained in 3.07s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 72.613
  Epoch 56/60
Model trained in 2.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 72.365
  Epoch 57/60
Model trained in 3.05s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 71.214
  Epoch 58/60
Model trained in 2.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 70.611
  Epoch 59/60
Model trained in 2.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 71.038
  Epoch 60/60
Model trained in 2.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 70.229

  best_val_SMAPE=70.229

Combination 1010/1152: {'encoder_hidden_size': 48, 'encoder_layers': 2, 'encoder_dropout': 0.0, 'decoder_hidden_size': 33, 'decoder_layers': 2, 'decoder_dropout': 0.0, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 20, 'batch_size': 32, 'sequence_length': 168}
Time: 321.83 minutes - estimated total time: 367.08 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 3.03s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 169.031
  Epoch 2/60
Model trained in 2.97s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 153.425
  Epoch 3/60
Model trained in 3.19s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 141.033
  Epoch 4/60
Model trained in 3.02s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 130.333
  Epoch 5/60
Model trained in 3.08s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 120.602
  Epoch 6/60
Model trained in 3.01s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 114.310
  Epoch 7/60
Model trained in 2.98s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 107.837
  Epoch 8/60
Model trained in 3.01s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 101.712
  Epoch 9/60
Model trained in 3.09s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 96.540
  Epoch 10/60
Model trained in 3.03s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.668
  Epoch 11/60
Model trained in 3.08s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.915
  Epoch 12/60
Model trained in 3.11s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.768
  Epoch 13/60
Model trained in 3.15s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.335
  Epoch 14/60
Model trained in 3.09s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.151
  Epoch 15/60
Model trained in 2.98s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.352
  Epoch 16/60
Model trained in 2.95s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.655
  Epoch 17/60
Model trained in 3.08s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.092
  Epoch 18/60
Model trained in 3.09s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.245
  Epoch 19/60
Model trained in 3.19s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.781
  Epoch 20/60
Model trained in 3.09s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.904
  Epoch 21/60
Model trained in 2.95s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.879
  Epoch 22/60
Model trained in 3.00s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.505
  Epoch 23/60
Model trained in 3.03s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.851
  Epoch 24/60
Model trained in 2.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.538
  Epoch 25/60
Model trained in 3.19s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.858
  Epoch 26/60
Model trained in 3.28s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.654
  Epoch 27/60
Model trained in 3.12s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.425
  Epoch 28/60
Model trained in 3.16s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.768
  Epoch 29/60
Model trained in 3.06s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.974
  Epoch 30/60
Model trained in 3.00s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.259
  Epoch 31/60
Model trained in 3.21s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.522
  Epoch 32/60
Model trained in 3.30s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.369
  Epoch 33/60
Model trained in 3.05s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.332
  Epoch 34/60
Model trained in 3.19s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.388
  Early stopping triggered.

  best_val_SMAPE=80.151

Combination 1011/1152: {'encoder_hidden_size': 48, 'encoder_layers': 2, 'encoder_dropout': 0.0, 'decoder_hidden_size': 33, 'decoder_layers': 2, 'decoder_dropout': 0.0, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 20, 'batch_size': 64, 'sequence_length': 24}
Time: 323.87 minutes - estimated total time: 369.04 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 2.08s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 178.840
  Epoch 2/60
Model trained in 1.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 168.840
  Epoch 3/60
Model trained in 1.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 160.404
  Epoch 4/60
Model trained in 1.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 153.120
  Epoch 5/60
Model trained in 1.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 146.606
  Epoch 6/60
Model trained in 1.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 140.636
  Epoch 7/60
Model trained in 1.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 135.112
  Epoch 8/60
Model trained in 1.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 129.846
  Epoch 9/60
Model trained in 1.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 125.052
  Epoch 10/60
Model trained in 1.95s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 121.842
  Epoch 11/60
Model trained in 1.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 117.860
  Epoch 12/60
Model trained in 1.95s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 113.364
  Epoch 13/60
Model trained in 1.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 109.465
  Epoch 14/60
Model trained in 1.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 105.702
  Epoch 15/60
Model trained in 1.95s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 102.438
  Epoch 16/60
Model trained in 2.09s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 99.144
  Epoch 17/60
Model trained in 1.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 96.111
  Epoch 18/60
Model trained in 1.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.409
  Epoch 19/60
Model trained in 1.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.877
  Epoch 20/60
Model trained in 1.98s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.517
  Epoch 21/60
Model trained in 1.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.752
  Epoch 22/60
Model trained in 1.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.523
  Epoch 23/60
Model trained in 1.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.694
  Epoch 24/60
Model trained in 1.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.254
  Epoch 25/60
Model trained in 2.24s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.924
  Epoch 26/60
Model trained in 1.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.777
  Epoch 27/60
Model trained in 1.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.824
  Epoch 28/60
Model trained in 1.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.174
  Epoch 29/60
Model trained in 1.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.112
  Epoch 30/60
Model trained in 1.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.279
  Epoch 31/60
Model trained in 1.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.408
  Epoch 32/60
Model trained in 1.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.107
  Epoch 33/60
Model trained in 1.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.372
  Epoch 34/60
Model trained in 1.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.158
  Epoch 35/60
Model trained in 1.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.211
  Epoch 36/60
Model trained in 1.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.976
  Epoch 37/60
Model trained in 1.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.638
  Epoch 38/60
Model trained in 1.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.916
  Epoch 39/60
Model trained in 1.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.992
  Epoch 40/60
Model trained in 1.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.036
  Epoch 41/60
Model trained in 1.99s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.302
  Epoch 42/60
Model trained in 1.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.576
  Epoch 43/60
Model trained in 1.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.810
  Epoch 44/60
Model trained in 2.03s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.657
  Epoch 45/60
Model trained in 1.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.688
  Epoch 46/60
Model trained in 1.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.288
  Epoch 47/60
Model trained in 1.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.917
  Epoch 48/60
Model trained in 2.00s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.120
  Epoch 49/60
Model trained in 2.25s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.336
  Epoch 50/60
Model trained in 2.01s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.305
  Epoch 51/60
Model trained in 1.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.721
  Epoch 52/60
Model trained in 1.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.449
  Epoch 53/60
Model trained in 2.10s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.184
  Epoch 54/60
Model trained in 1.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.959
  Epoch 55/60
Model trained in 2.02s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.080
  Epoch 56/60
Model trained in 2.00s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.729
  Epoch 57/60
Model trained in 2.50s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.670
  Epoch 58/60
Model trained in 2.22s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.132
  Epoch 59/60
Model trained in 2.32s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.626
  Epoch 60/60
Model trained in 2.25s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.570

  best_val_SMAPE=76.576

Combination 1012/1152: {'encoder_hidden_size': 48, 'encoder_layers': 2, 'encoder_dropout': 0.0, 'decoder_hidden_size': 33, 'decoder_layers': 2, 'decoder_dropout': 0.0, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 20, 'batch_size': 64, 'sequence_length': 168}
Time: 326.29 minutes - estimated total time: 371.43 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 2.59s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 178.887
  Epoch 2/60
Model trained in 2.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 168.949
  Epoch 3/60
Model trained in 2.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 160.565
  Epoch 4/60
Model trained in 2.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 153.311
  Epoch 5/60
Model trained in 2.68s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 146.827
  Epoch 6/60
Model trained in 2.68s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 140.878
  Epoch 7/60
Model trained in 2.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 135.377
  Epoch 8/60
Model trained in 2.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 130.137
  Epoch 9/60
Model trained in 2.68s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 125.136
  Epoch 10/60
Model trained in 2.55s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 121.873
  Epoch 11/60
Model trained in 2.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 117.657
  Epoch 12/60
Model trained in 2.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 114.088
  Epoch 13/60
Model trained in 2.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 110.462
  Epoch 14/60
Model trained in 2.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 106.689
  Epoch 15/60
Model trained in 3.08s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 104.226
  Epoch 16/60
Model trained in 2.68s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 101.398
  Epoch 17/60
Model trained in 2.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 98.518
  Epoch 18/60
Model trained in 2.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 95.486
  Epoch 19/60
Model trained in 3.02s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.752
  Epoch 20/60
Model trained in 2.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.927
  Epoch 21/60
Model trained in 3.08s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.704
  Epoch 22/60
Model trained in 3.09s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.351
  Epoch 23/60
Model trained in 3.32s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.578
  Epoch 24/60
Model trained in 2.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.273
  Epoch 25/60
Model trained in 2.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.648
  Epoch 26/60
Model trained in 2.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.313
  Epoch 27/60
Model trained in 3.34s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.839
  Epoch 28/60
Model trained in 3.01s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.832
  Epoch 29/60
Model trained in 2.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.739
  Epoch 30/60
Model trained in 2.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.199
  Epoch 31/60
Model trained in 2.19s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.945
  Epoch 32/60
Model trained in 2.48s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.834
  Epoch 33/60
Model trained in 2.15s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.759
  Epoch 34/60
Model trained in 2.47s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.901
  Epoch 35/60
Model trained in 2.53s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.018
  Epoch 36/60
Model trained in 2.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.379
  Epoch 37/60
Model trained in 2.32s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.677
  Epoch 38/60
Model trained in 2.28s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.378
  Epoch 39/60
Model trained in 2.09s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.471
  Epoch 40/60
Model trained in 2.20s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.311
  Epoch 41/60
Model trained in 2.19s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.239
  Epoch 42/60
Model trained in 2.23s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.189
  Epoch 43/60
Model trained in 2.18s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.949
  Epoch 44/60
Model trained in 2.12s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.183
  Epoch 45/60
Model trained in 2.05s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.088
  Epoch 46/60
Model trained in 2.11s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.886
  Epoch 47/60
Model trained in 2.18s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.467
  Epoch 48/60
Model trained in 2.10s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.901
  Epoch 49/60
Model trained in 2.09s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.085
  Epoch 50/60
Model trained in 2.07s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.025
  Epoch 51/60
Model trained in 2.03s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.754
  Epoch 52/60
Model trained in 2.10s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.353
  Epoch 53/60
Model trained in 2.10s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.625
  Epoch 54/60
Model trained in 2.09s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.564
  Epoch 55/60
Model trained in 2.16s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.988
  Epoch 56/60
Model trained in 2.11s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.926
  Epoch 57/60
Model trained in 2.11s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.626
  Epoch 58/60
Model trained in 2.16s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.123
  Epoch 59/60
Model trained in 2.23s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.696
  Epoch 60/60
Model trained in 2.09s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.948

  best_val_SMAPE=77.467

Combination 1013/1152: {'encoder_hidden_size': 48, 'encoder_layers': 2, 'encoder_dropout': 0.0, 'decoder_hidden_size': 33, 'decoder_layers': 2, 'decoder_dropout': 0.0, 'learning_rate': 0.0005, 'max_epochs': 60, 'patience': 20, 'batch_size': 32, 'sequence_length': 24}
Time: 329.38 minutes - estimated total time: 374.57 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 3.31s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 178.861
  Epoch 2/60
Model trained in 3.26s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 169.015
  Epoch 3/60
Model trained in 3.24s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 160.657
  Epoch 4/60
Model trained in 3.28s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 153.401
  Epoch 5/60
Model trained in 3.24s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 146.898
  Epoch 6/60
Model trained in 3.25s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 140.917
  Epoch 7/60
Model trained in 3.25s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 135.376
  Epoch 8/60
Model trained in 3.31s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 130.046
  Epoch 9/60
Model trained in 3.33s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 124.956
  Epoch 10/60
Model trained in 3.38s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 120.211
  Epoch 11/60
Model trained in 3.24s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 118.744
  Epoch 12/60
Model trained in 3.26s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 112.952
  Epoch 13/60
Model trained in 3.31s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 111.416
  Epoch 14/60
Model trained in 3.28s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 108.551
  Epoch 15/60
Model trained in 3.25s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 105.598
  Epoch 16/60
Model trained in 3.21s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 102.479
  Epoch 17/60
Model trained in 3.29s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 100.012
  Epoch 18/60
Model trained in 3.25s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 97.838
  Epoch 19/60
Model trained in 3.23s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 95.038
  Epoch 20/60
Model trained in 3.16s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.632
  Epoch 21/60
Model trained in 3.34s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.850
  Epoch 22/60
Model trained in 3.29s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.316
  Epoch 23/60
Model trained in 3.28s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.721
  Epoch 24/60
Model trained in 3.26s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.775
  Epoch 25/60
Model trained in 3.26s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.803
  Epoch 26/60
Model trained in 3.23s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.977
  Epoch 27/60
Model trained in 3.22s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.054
  Epoch 28/60
Model trained in 3.20s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.811
  Epoch 29/60
Model trained in 3.20s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.586
  Epoch 30/60
Model trained in 3.32s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.998
  Epoch 31/60
Model trained in 3.30s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.768
  Epoch 32/60
Model trained in 3.24s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.871
  Epoch 33/60
Model trained in 3.23s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.066
  Epoch 34/60
Model trained in 3.47s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.373
  Epoch 35/60
Model trained in 3.26s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.649
  Epoch 36/60
Model trained in 3.26s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.754
  Epoch 37/60
Model trained in 3.23s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.103
  Epoch 38/60
Model trained in 3.30s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.925
  Epoch 39/60
Model trained in 3.31s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.643
  Epoch 40/60
Model trained in 3.32s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.504
  Epoch 41/60
Model trained in 3.26s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.959
  Epoch 42/60
Model trained in 2.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.280
  Epoch 43/60
Model trained in 2.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.396
  Epoch 44/60
Model trained in 3.04s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.970
  Epoch 45/60
Model trained in 3.37s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.221
  Epoch 46/60
Model trained in 3.04s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.194
  Epoch 47/60
Model trained in 2.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.576
  Epoch 48/60
Model trained in 2.99s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.631
  Epoch 49/60
Model trained in 3.01s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.493
  Epoch 50/60
Model trained in 3.18s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.385
  Epoch 51/60
Model trained in 3.16s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.741
  Early stopping triggered.

  best_val_SMAPE=75.768

Combination 1014/1152: {'encoder_hidden_size': 48, 'encoder_layers': 2, 'encoder_dropout': 0.0, 'decoder_hidden_size': 33, 'decoder_layers': 2, 'decoder_dropout': 0.0, 'learning_rate': 0.0005, 'max_epochs': 60, 'patience': 20, 'batch_size': 32, 'sequence_length': 168}
Time: 332.54 minutes - estimated total time: 377.79 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 3.13s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 178.889
  Epoch 2/60
Model trained in 3.18s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 169.107
  Epoch 3/60
Model trained in 3.18s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 160.792
  Epoch 4/60
Model trained in 3.08s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 153.561
  Epoch 5/60
Model trained in 3.05s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 147.082
  Epoch 6/60
Model trained in 3.17s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 141.119
  Epoch 7/60
Model trained in 3.08s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 136.630
  Epoch 8/60
Model trained in 3.17s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 131.628
  Epoch 9/60
Model trained in 3.35s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 126.349
  Epoch 10/60
Model trained in 3.30s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 121.377
  Epoch 11/60
Model trained in 3.12s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 117.036
  Epoch 12/60
Model trained in 3.27s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 113.081
  Epoch 13/60
Model trained in 3.10s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 109.442
  Epoch 14/60
Model trained in 3.14s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 106.206
  Epoch 15/60
Model trained in 3.10s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 103.212
  Epoch 16/60
Model trained in 3.10s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 100.288
  Epoch 17/60
Model trained in 3.09s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 98.076
  Epoch 18/60
Model trained in 3.06s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 95.436
  Epoch 19/60
Model trained in 3.05s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.724
  Epoch 20/60
Model trained in 3.00s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.394
  Epoch 21/60
Model trained in 3.04s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.662
  Epoch 22/60
Model trained in 3.07s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.556
  Epoch 23/60
Model trained in 3.13s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.509
  Epoch 24/60
Model trained in 3.08s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.540
  Epoch 25/60
Model trained in 3.08s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.794
  Epoch 26/60
Model trained in 3.02s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.229
  Epoch 27/60
Model trained in 3.09s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.071
  Epoch 28/60
Model trained in 3.05s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.531
  Epoch 29/60
Model trained in 3.04s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.142
  Epoch 30/60
Model trained in 3.08s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.915
  Epoch 31/60
Model trained in 3.11s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.051
  Epoch 32/60
Model trained in 3.16s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.242
  Epoch 33/60
Model trained in 3.12s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.459
  Epoch 34/60
Model trained in 3.10s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.499
  Epoch 35/60
Model trained in 3.03s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.629
  Epoch 36/60
Model trained in 3.12s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.609
  Epoch 37/60
Model trained in 3.22s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.801
  Epoch 38/60
Model trained in 3.27s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.327
  Epoch 39/60
Model trained in 3.08s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.868
  Epoch 40/60
Model trained in 2.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.067
  Epoch 41/60
Model trained in 2.98s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.125
  Epoch 42/60
Model trained in 3.03s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.211
  Epoch 43/60
Model trained in 2.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.072
  Epoch 44/60
Model trained in 2.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.160
  Epoch 45/60
Model trained in 3.02s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.787
  Epoch 46/60
Model trained in 3.08s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.048
  Epoch 47/60
Model trained in 2.98s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.317
  Epoch 48/60
Model trained in 2.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.569
  Epoch 49/60
Model trained in 2.95s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.375
  Epoch 50/60
Model trained in 2.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.072
  Early stopping triggered.

  best_val_SMAPE=79.915

Combination 1015/1152: {'encoder_hidden_size': 48, 'encoder_layers': 2, 'encoder_dropout': 0.0, 'decoder_hidden_size': 33, 'decoder_layers': 2, 'decoder_dropout': 0.0, 'learning_rate': 0.0005, 'max_epochs': 60, 'patience': 20, 'batch_size': 64, 'sequence_length': 24}
Time: 335.52 minutes - estimated total time: 380.81 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 1.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 185.275
  Epoch 2/60
Model trained in 1.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 178.755
  Epoch 3/60
Model trained in 1.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 173.554
  Epoch 4/60
Model trained in 1.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 168.887
  Epoch 5/60
Model trained in 1.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 164.552
  Epoch 6/60
Model trained in 1.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 160.503
  Epoch 7/60
Model trained in 1.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 156.775
  Epoch 8/60
Model trained in 1.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 153.227
  Epoch 9/60
Model trained in 1.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 149.891
  Epoch 10/60
Model trained in 1.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 146.699
  Epoch 11/60
Model trained in 1.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 143.624
  Epoch 12/60
Model trained in 1.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 140.698
  Epoch 13/60
Model trained in 1.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 137.865
  Epoch 14/60
Model trained in 1.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 135.134
  Epoch 15/60
Model trained in 1.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 132.452
  Epoch 16/60
Model trained in 1.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 129.819
  Epoch 17/60
Model trained in 1.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 127.249
  Epoch 18/60
Model trained in 1.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 124.745
  Epoch 19/60
Model trained in 1.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 122.290
  Epoch 20/60
Model trained in 1.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 119.912
  Epoch 21/60
Model trained in 1.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 118.244
  Epoch 22/60
Model trained in 1.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 117.924
  Epoch 23/60
Model trained in 1.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 118.545
  Epoch 24/60
Model trained in 1.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 117.530
  Epoch 25/60
Model trained in 1.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 116.172
  Epoch 26/60
Model trained in 1.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 113.625
  Epoch 27/60
Model trained in 1.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 111.902
  Epoch 28/60
Model trained in 1.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 109.945
  Epoch 29/60
Model trained in 1.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 108.482
  Epoch 30/60
Model trained in 1.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 106.915
  Epoch 31/60
Model trained in 1.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 105.330
  Epoch 32/60
Model trained in 1.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 103.683
  Epoch 33/60
Model trained in 1.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 102.849
  Epoch 34/60
Model trained in 1.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 102.336
  Epoch 35/60
Model trained in 1.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 101.585
  Epoch 36/60
Model trained in 1.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 100.799
  Epoch 37/60
Model trained in 1.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 99.582
  Epoch 38/60
Model trained in 1.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 98.602
  Epoch 39/60
Model trained in 1.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 97.209
  Epoch 40/60
Model trained in 1.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 96.191
  Epoch 41/60
Model trained in 1.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 94.358
  Epoch 42/60
Model trained in 1.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.482
  Epoch 43/60
Model trained in 1.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.434
  Epoch 44/60
Model trained in 1.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.934
  Epoch 45/60
Model trained in 1.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.811
  Epoch 46/60
Model trained in 1.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.340
  Epoch 47/60
Model trained in 1.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.042
  Epoch 48/60
Model trained in 1.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.621
  Epoch 49/60
Model trained in 1.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.954
  Epoch 50/60
Model trained in 1.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.270
  Epoch 51/60
Model trained in 1.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.755
  Epoch 52/60
Model trained in 1.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.949
  Epoch 53/60
Model trained in 1.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.861
  Epoch 54/60
Model trained in 1.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.953
  Epoch 55/60
Model trained in 1.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.438
  Epoch 56/60
Model trained in 1.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.082
  Epoch 57/60
Model trained in 1.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.574
  Epoch 58/60
Model trained in 1.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.094
  Epoch 59/60
Model trained in 1.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.173
  Epoch 60/60
Model trained in 1.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.020

  best_val_SMAPE=85.574

Combination 1016/1152: {'encoder_hidden_size': 48, 'encoder_layers': 2, 'encoder_dropout': 0.0, 'decoder_hidden_size': 33, 'decoder_layers': 2, 'decoder_dropout': 0.0, 'learning_rate': 0.0005, 'max_epochs': 60, 'patience': 20, 'batch_size': 64, 'sequence_length': 168}
Time: 337.81 minutes - estimated total time: 383.03 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 1.99s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 185.326
  Epoch 2/60
Model trained in 1.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 178.840
  Epoch 3/60
Model trained in 1.95s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 173.673
  Epoch 4/60
Model trained in 1.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 169.034
  Epoch 5/60
Model trained in 2.00s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 164.717
  Epoch 6/60
Model trained in 1.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 160.688
  Epoch 7/60
Model trained in 2.18s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 156.971
  Epoch 8/60
Model trained in 1.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 153.434
  Epoch 9/60
Model trained in 1.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 150.111
  Epoch 10/60
Model trained in 1.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 146.933
  Epoch 11/60
Model trained in 1.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 143.868
  Epoch 12/60
Model trained in 1.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 140.950
  Epoch 13/60
Model trained in 1.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 138.128
  Epoch 14/60
Model trained in 1.99s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 136.798
  Epoch 15/60
Model trained in 1.99s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 134.292
  Epoch 16/60
Model trained in 1.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 132.290
  Epoch 17/60
Model trained in 1.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 129.981
  Epoch 18/60
Model trained in 1.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 127.602
  Epoch 19/60
Model trained in 1.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 125.270
  Epoch 20/60
Model trained in 1.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 123.476
  Epoch 21/60
Model trained in 1.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 121.394
  Epoch 22/60
Model trained in 1.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 119.384
  Epoch 23/60
Model trained in 1.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 117.630
  Epoch 24/60
Model trained in 1.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 116.443
  Epoch 25/60
Model trained in 1.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 114.499
  Epoch 26/60
Model trained in 1.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 112.911
  Epoch 27/60
Model trained in 1.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 112.200
  Epoch 28/60
Model trained in 1.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 110.574
  Epoch 29/60
Model trained in 1.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 108.857
  Epoch 30/60
Model trained in 1.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 106.825
  Epoch 31/60
Model trained in 1.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 105.608
  Epoch 32/60
Model trained in 1.97s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 104.195
  Epoch 33/60
Model trained in 1.98s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 102.690
  Epoch 34/60
Model trained in 1.95s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 101.545
  Epoch 35/60
Model trained in 1.95s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 100.244
  Epoch 36/60
Model trained in 1.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 98.989
  Epoch 37/60
Model trained in 1.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 98.547
  Epoch 38/60
Model trained in 1.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 98.517
  Epoch 39/60
Model trained in 1.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 96.954
  Epoch 40/60
Model trained in 1.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 96.052
  Epoch 41/60
Model trained in 1.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 95.544
  Epoch 42/60
Model trained in 1.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 94.387
  Epoch 43/60
Model trained in 1.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.296
  Epoch 44/60
Model trained in 1.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.758
  Epoch 45/60
Model trained in 1.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.780
  Epoch 46/60
Model trained in 1.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.707
  Epoch 47/60
Model trained in 1.95s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.599
  Epoch 48/60
Model trained in 1.98s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.500
  Epoch 49/60
Model trained in 1.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.896
  Epoch 50/60
Model trained in 1.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.037
  Epoch 51/60
Model trained in 1.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.829
  Epoch 52/60
Model trained in 1.95s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.549
  Epoch 53/60
Model trained in 1.97s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.078
  Epoch 54/60
Model trained in 1.98s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.203
  Epoch 55/60
Model trained in 1.95s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.337
  Epoch 56/60
Model trained in 2.07s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.922
  Epoch 57/60
Model trained in 1.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.636
  Epoch 58/60
Model trained in 1.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.108
  Epoch 59/60
Model trained in 1.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.565
  Epoch 60/60
Model trained in 1.98s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.826

  best_val_SMAPE=88.636

Combination 1017/1152: {'encoder_hidden_size': 48, 'encoder_layers': 2, 'encoder_dropout': 0.0, 'decoder_hidden_size': 33, 'decoder_layers': 2, 'decoder_dropout': 0.2, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 20, 'batch_size': 32, 'sequence_length': 24}
Time: 340.25 minutes - estimated total time: 385.41 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 3.00s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 169.032
  Epoch 2/60
Model trained in 2.97s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 153.328
  Epoch 3/60
Model trained in 2.97s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 140.875
  Epoch 4/60
Model trained in 2.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 130.127
  Epoch 5/60
Model trained in 2.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 120.360
  Epoch 6/60
Model trained in 2.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 111.743
  Epoch 7/60
Model trained in 2.97s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 104.020
  Epoch 8/60
Model trained in 3.00s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 97.038
  Epoch 9/60
Model trained in 2.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.686
  Epoch 10/60
Model trained in 3.03s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.388
  Epoch 11/60
Model trained in 2.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.198
  Epoch 12/60
Model trained in 2.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.701
  Epoch 13/60
Model trained in 2.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.001
  Epoch 14/60
Model trained in 2.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.236
  Epoch 15/60
Model trained in 2.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.045
  Epoch 16/60
Model trained in 2.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.425
  Epoch 17/60
Model trained in 2.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.987
  Epoch 18/60
Model trained in 2.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.702
  Epoch 19/60
Model trained in 2.95s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.371
  Epoch 20/60
Model trained in 2.98s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.350
  Epoch 21/60
Model trained in 3.12s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.103
  Epoch 22/60
Model trained in 3.29s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.818
  Epoch 23/60
Model trained in 3.22s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.628
  Epoch 24/60
Model trained in 3.26s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.222
  Epoch 25/60
Model trained in 3.18s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.415
  Epoch 26/60
Model trained in 3.08s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.761
  Epoch 27/60
Model trained in 3.03s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.163
  Epoch 28/60
Model trained in 3.04s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.390
  Epoch 29/60
Model trained in 3.03s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.802
  Epoch 30/60
Model trained in 3.01s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.916
  Epoch 31/60
Model trained in 3.22s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.174
  Epoch 32/60
Model trained in 3.16s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.553
  Epoch 33/60
Model trained in 3.08s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.757
  Epoch 34/60
Model trained in 2.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.328
  Epoch 35/60
Model trained in 3.01s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.501
  Epoch 36/60
Model trained in 3.11s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.708
  Epoch 37/60
Model trained in 3.06s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.755
  Epoch 38/60
Model trained in 2.99s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.471
  Epoch 39/60
Model trained in 3.01s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.783
  Epoch 40/60
Model trained in 3.04s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.960
  Epoch 41/60
Model trained in 3.26s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.459
  Epoch 42/60
Model trained in 3.09s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.424
  Early stopping triggered.

  best_val_SMAPE=81.818

Combination 1018/1152: {'encoder_hidden_size': 48, 'encoder_layers': 2, 'encoder_dropout': 0.0, 'decoder_hidden_size': 33, 'decoder_layers': 2, 'decoder_dropout': 0.2, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 20, 'batch_size': 32, 'sequence_length': 168}
Time: 342.73 minutes - estimated total time: 387.85 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 3.34s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 169.022
  Epoch 2/60
Model trained in 3.31s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 153.417
  Epoch 3/60
Model trained in 3.50s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 141.026
  Epoch 4/60
Model trained in 3.25s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 130.327
  Epoch 5/60
Model trained in 3.24s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 120.596
  Epoch 6/60
Model trained in 3.27s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 114.671
  Epoch 7/60
Model trained in 3.30s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 107.007
  Epoch 8/60
Model trained in 3.03s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 100.722
  Epoch 9/60
Model trained in 3.11s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 94.478
  Epoch 10/60
Model trained in 3.25s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.717
  Epoch 11/60
Model trained in 3.15s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.763
  Epoch 12/60
Model trained in 3.18s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.971
  Epoch 13/60
Model trained in 3.15s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.193
  Epoch 14/60
Model trained in 3.23s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.882
  Epoch 15/60
Model trained in 3.25s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.061
  Epoch 16/60
Model trained in 3.25s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.548
  Epoch 17/60
Model trained in 2.99s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.440
  Epoch 18/60
Model trained in 3.00s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.925
  Epoch 19/60
Model trained in 3.00s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.984
  Epoch 20/60
Model trained in 3.08s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.053
  Epoch 21/60
Model trained in 3.07s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.108
  Epoch 22/60
Model trained in 3.19s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.497
  Epoch 23/60
Model trained in 2.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.923
  Epoch 24/60
Model trained in 2.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.916
  Epoch 25/60
Model trained in 3.05s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.240
  Epoch 26/60
Model trained in 3.35s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.025
  Epoch 27/60
Model trained in 3.16s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.729
  Epoch 28/60
Model trained in 3.15s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.292
  Epoch 29/60
Model trained in 3.27s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.458
  Epoch 30/60
Model trained in 3.18s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.230
  Epoch 31/60
Model trained in 3.07s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.987
  Epoch 32/60
Model trained in 3.16s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.921
  Epoch 33/60
Model trained in 3.62s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.513
  Epoch 34/60
Model trained in 3.33s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.309
  Epoch 35/60
Model trained in 3.03s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.643
  Epoch 36/60
Model trained in 3.06s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.634
  Epoch 37/60
Model trained in 3.14s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.365
  Epoch 38/60
Model trained in 3.15s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.763
  Epoch 39/60
Model trained in 2.99s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.067
  Epoch 40/60
Model trained in 2.97s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.151
  Epoch 41/60
Model trained in 2.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.543
  Epoch 42/60
Model trained in 2.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.554
  Epoch 43/60
Model trained in 3.15s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.104
  Epoch 44/60
Model trained in 3.06s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.778
  Epoch 45/60
Model trained in 3.02s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.352
  Epoch 46/60
Model trained in 3.12s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.040
  Epoch 47/60
Model trained in 3.05s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.755
  Epoch 48/60
Model trained in 3.13s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.667
  Early stopping triggered.

  best_val_SMAPE=75.292

Combination 1019/1152: {'encoder_hidden_size': 48, 'encoder_layers': 2, 'encoder_dropout': 0.0, 'decoder_hidden_size': 33, 'decoder_layers': 2, 'decoder_dropout': 0.2, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 20, 'batch_size': 64, 'sequence_length': 24}
Time: 345.65 minutes - estimated total time: 390.76 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 1.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 178.834
  Epoch 2/60
Model trained in 1.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 168.833
  Epoch 3/60
Model trained in 1.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 160.396
  Epoch 4/60
Model trained in 1.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 153.113
  Epoch 5/60
Model trained in 1.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 146.600
  Epoch 6/60
Model trained in 1.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 140.630
  Epoch 7/60
Model trained in 1.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 135.106
  Epoch 8/60
Model trained in 2.05s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 129.840
  Epoch 9/60
Model trained in 2.19s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 126.675
  Epoch 10/60
Model trained in 1.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 122.353
  Epoch 11/60
Model trained in 1.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 118.765
  Epoch 12/60
Model trained in 1.95s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 114.460
  Epoch 13/60
Model trained in 1.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 110.606
  Epoch 14/60
Model trained in 1.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 107.257
  Epoch 15/60
Model trained in 1.95s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 104.041
  Epoch 16/60
Model trained in 1.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 101.470
  Epoch 17/60
Model trained in 1.98s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 98.060
  Epoch 18/60
Model trained in 2.02s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 95.423
  Epoch 19/60
Model trained in 1.98s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.919
  Epoch 20/60
Model trained in 2.02s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.424
  Epoch 21/60
Model trained in 2.11s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.298
  Epoch 22/60
Model trained in 2.10s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.362
  Epoch 23/60
Model trained in 1.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.870
  Epoch 24/60
Model trained in 1.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.949
  Epoch 25/60
Model trained in 2.06s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.819
  Epoch 26/60
Model trained in 2.08s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.968
  Epoch 27/60
Model trained in 2.09s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.673
  Epoch 28/60
Model trained in 1.97s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.439
  Epoch 29/60
Model trained in 1.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.607
  Epoch 30/60
Model trained in 2.00s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.270
  Epoch 31/60
Model trained in 2.18s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.640
  Epoch 32/60
Model trained in 2.04s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.338
  Epoch 33/60
Model trained in 2.01s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.364
  Epoch 34/60
Model trained in 2.01s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.621
  Epoch 35/60
Model trained in 2.00s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.002
  Epoch 36/60
Model trained in 1.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.066
  Epoch 37/60
Model trained in 2.00s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.292
  Epoch 38/60
Model trained in 1.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.907
  Epoch 39/60
Model trained in 1.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.904
  Epoch 40/60
Model trained in 1.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.038
  Epoch 41/60
Model trained in 1.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.825
  Epoch 42/60
Model trained in 1.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.756
  Epoch 43/60
Model trained in 1.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.468
  Epoch 44/60
Model trained in 1.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.703
  Epoch 45/60
Model trained in 1.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.617
  Epoch 46/60
Model trained in 1.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.262
  Epoch 47/60
Model trained in 1.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.581
  Epoch 48/60
Model trained in 1.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.016
  Epoch 49/60
Model trained in 1.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.897
  Epoch 50/60
Model trained in 1.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.480
  Epoch 51/60
Model trained in 1.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.847
  Epoch 52/60
Model trained in 1.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.399
  Epoch 53/60
Model trained in 1.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.742
  Epoch 54/60
Model trained in 1.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.927
  Epoch 55/60
Model trained in 1.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.703
  Epoch 56/60
Model trained in 1.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.415
  Epoch 57/60
Model trained in 1.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.480
  Epoch 58/60
Model trained in 1.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.419
  Epoch 59/60
Model trained in 1.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.126
  Epoch 60/60
Model trained in 1.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.341

  best_val_SMAPE=79.468

Combination 1020/1152: {'encoder_hidden_size': 48, 'encoder_layers': 2, 'encoder_dropout': 0.0, 'decoder_hidden_size': 33, 'decoder_layers': 2, 'decoder_dropout': 0.2, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 20, 'batch_size': 64, 'sequence_length': 168}
Time: 348.05 minutes - estimated total time: 393.09 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 1.98s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 178.882
  Epoch 2/60
Model trained in 1.97s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 168.943
  Epoch 3/60
Model trained in 2.00s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 160.559
  Epoch 4/60
Model trained in 2.10s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 153.306
  Epoch 5/60
Model trained in 1.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 146.822
  Epoch 6/60
Model trained in 1.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 140.873
  Epoch 7/60
Model trained in 1.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 135.373
  Epoch 8/60
Model trained in 2.00s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 130.132
  Epoch 9/60
Model trained in 1.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 125.131
  Epoch 10/60
Model trained in 1.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 120.367
  Epoch 11/60
Model trained in 1.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 115.933
  Epoch 12/60
Model trained in 1.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 114.848
  Epoch 13/60
Model trained in 1.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 111.100
  Epoch 14/60
Model trained in 1.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 107.715
  Epoch 15/60
Model trained in 1.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 105.149
  Epoch 16/60
Model trained in 1.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 102.971
  Epoch 17/60
Model trained in 1.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 100.730
  Epoch 18/60
Model trained in 1.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 99.218
  Epoch 19/60
Model trained in 1.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 96.072
  Epoch 20/60
Model trained in 1.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.513
  Epoch 21/60
Model trained in 1.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.386
  Epoch 22/60
Model trained in 1.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.729
  Epoch 23/60
Model trained in 1.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.134
  Epoch 24/60
Model trained in 1.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.008
  Epoch 25/60
Model trained in 1.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.754
  Epoch 26/60
Model trained in 1.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.336
  Epoch 27/60
Model trained in 1.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.855
  Epoch 28/60
Model trained in 1.95s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.745
  Epoch 29/60
Model trained in 2.04s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.574
  Epoch 30/60
Model trained in 1.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.313
  Epoch 31/60
Model trained in 1.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.125
  Epoch 32/60
Model trained in 1.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.517
  Epoch 33/60
Model trained in 1.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.137
  Epoch 34/60
Model trained in 1.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.113
  Epoch 35/60
Model trained in 1.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.633
  Epoch 36/60
Model trained in 1.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.896
  Epoch 37/60
Model trained in 1.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.705
  Epoch 38/60
Model trained in 1.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.265
  Epoch 39/60
Model trained in 1.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.167
  Epoch 40/60
Model trained in 1.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.770
  Epoch 41/60
Model trained in 1.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.853
  Epoch 42/60
Model trained in 1.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.516
  Epoch 43/60
Model trained in 1.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.404
  Epoch 44/60
Model trained in 1.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.160
  Epoch 45/60
Model trained in 1.99s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.209
  Epoch 46/60
Model trained in 1.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.137
  Epoch 47/60
Model trained in 1.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.318
  Epoch 48/60
Model trained in 1.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.018
  Epoch 49/60
Model trained in 1.95s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.357
  Epoch 50/60
Model trained in 1.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.261
  Epoch 51/60
Model trained in 1.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.291
  Early stopping triggered.

  best_val_SMAPE=80.125

Combination 1021/1152: {'encoder_hidden_size': 48, 'encoder_layers': 2, 'encoder_dropout': 0.0, 'decoder_hidden_size': 33, 'decoder_layers': 2, 'decoder_dropout': 0.2, 'learning_rate': 0.0005, 'max_epochs': 60, 'patience': 20, 'batch_size': 32, 'sequence_length': 24}
Time: 350.06 minutes - estimated total time: 394.97 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 3.06s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 178.854
  Epoch 2/60
Model trained in 2.99s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 169.007
  Epoch 3/60
Model trained in 2.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 160.650
  Epoch 4/60
Model trained in 3.03s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 153.394
  Epoch 5/60
Model trained in 3.13s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 146.892
  Epoch 6/60
Model trained in 2.98s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 140.912
  Epoch 7/60
Model trained in 2.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 135.371
  Epoch 8/60
Model trained in 2.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 129.483
  Epoch 9/60
Model trained in 3.03s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 127.281
  Epoch 10/60
Model trained in 3.03s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 122.813
  Epoch 11/60
Model trained in 3.18s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 119.267
  Epoch 12/60
Model trained in 3.13s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 115.383
  Epoch 13/60
Model trained in 3.44s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 112.351
  Epoch 14/60
Model trained in 3.34s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 109.393
  Epoch 15/60
Model trained in 3.11s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 106.492
  Epoch 16/60
Model trained in 2.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 103.042
  Epoch 17/60
Model trained in 3.15s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 99.183
  Epoch 18/60
Model trained in 3.37s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 96.327
  Epoch 19/60
Model trained in 2.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.830
  Epoch 20/60
Model trained in 2.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.509
  Epoch 21/60
Model trained in 2.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.357
  Epoch 22/60
Model trained in 3.00s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.739
  Epoch 23/60
Model trained in 2.98s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.255
  Epoch 24/60
Model trained in 2.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.495
  Epoch 25/60
Model trained in 2.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.783
  Epoch 26/60
Model trained in 2.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.923
  Epoch 27/60
Model trained in 2.98s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.948
  Epoch 28/60
Model trained in 3.05s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.655
  Epoch 29/60
Model trained in 3.06s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.089
  Epoch 30/60
Model trained in 3.03s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.786
  Epoch 31/60
Model trained in 2.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.000
  Epoch 32/60
Model trained in 2.98s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.798
  Epoch 33/60
Model trained in 3.02s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.807
  Epoch 34/60
Model trained in 3.08s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.101
  Epoch 35/60
Model trained in 2.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.300
  Epoch 36/60
Model trained in 3.15s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.571
  Epoch 37/60
Model trained in 3.04s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.616
  Epoch 38/60
Model trained in 2.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.781
  Epoch 39/60
Model trained in 3.07s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.931
  Epoch 40/60
Model trained in 2.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.115
  Epoch 41/60
Model trained in 3.00s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.153
  Epoch 42/60
Model trained in 3.20s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.092
  Epoch 43/60
Model trained in 3.06s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.232
  Epoch 44/60
Model trained in 3.11s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.279
  Epoch 45/60
Model trained in 2.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.934
  Epoch 46/60
Model trained in 2.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.437
  Epoch 47/60
Model trained in 2.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.402
  Epoch 48/60
Model trained in 3.33s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.404
  Epoch 49/60
Model trained in 2.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.484
  Early stopping triggered.

  best_val_SMAPE=79.089

Combination 1022/1152: {'encoder_hidden_size': 48, 'encoder_layers': 2, 'encoder_dropout': 0.0, 'decoder_hidden_size': 33, 'decoder_layers': 2, 'decoder_dropout': 0.2, 'learning_rate': 0.0005, 'max_epochs': 60, 'patience': 20, 'batch_size': 32, 'sequence_length': 168}
Time: 352.93 minutes - estimated total time: 397.83 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 3.00s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 178.881
  Epoch 2/60
Model trained in 2.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 169.099
  Epoch 3/60
Model trained in 3.55s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 160.785
  Epoch 4/60
Model trained in 3.63s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 153.554
  Epoch 5/60
Model trained in 3.50s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 147.076
  Epoch 6/60
Model trained in 3.12s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 141.113
  Epoch 7/60
Model trained in 3.21s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 135.592
  Epoch 8/60
Model trained in 3.05s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 130.325
  Epoch 9/60
Model trained in 3.01s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 127.045
  Epoch 10/60
Model trained in 3.08s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 121.666
  Epoch 11/60
Model trained in 3.02s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 117.188
  Epoch 12/60
Model trained in 3.26s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 113.118
  Epoch 13/60
Model trained in 3.16s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 109.241
  Epoch 14/60
Model trained in 3.06s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 105.916
  Epoch 15/60
Model trained in 2.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 103.208
  Epoch 16/60
Model trained in 3.01s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 100.140
  Epoch 17/60
Model trained in 3.01s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 97.422
  Epoch 18/60
Model trained in 2.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 96.887
  Epoch 19/60
Model trained in 3.05s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 95.031
  Epoch 20/60
Model trained in 2.97s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.182
  Epoch 21/60
Model trained in 2.95s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.843
  Epoch 22/60
Model trained in 2.97s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.780
  Epoch 23/60
Model trained in 2.98s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.074
  Epoch 24/60
Model trained in 2.98s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.641
  Epoch 25/60
Model trained in 3.04s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.185
  Epoch 26/60
Model trained in 3.03s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.384
  Epoch 27/60
Model trained in 2.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.434
  Epoch 28/60
Model trained in 3.12s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.122
  Epoch 29/60
Model trained in 3.14s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.029
  Epoch 30/60
Model trained in 3.15s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.647
  Epoch 31/60
Model trained in 3.11s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.580
  Epoch 32/60
Model trained in 3.17s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.676
  Epoch 33/60
Model trained in 3.24s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.485
  Epoch 34/60
Model trained in 3.39s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.958
  Epoch 35/60
Model trained in 3.29s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.819
  Epoch 36/60
Model trained in 3.25s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.099
  Epoch 37/60
Model trained in 3.05s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.080
  Epoch 38/60
Model trained in 3.13s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.418
  Epoch 39/60
Model trained in 3.17s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.666
  Epoch 40/60
Model trained in 2.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.420
  Epoch 41/60
Model trained in 2.98s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.965
  Epoch 42/60
Model trained in 2.95s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.118
  Epoch 43/60
Model trained in 2.98s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.870
  Epoch 44/60
Model trained in 3.01s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.058
  Epoch 45/60
Model trained in 3.01s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.924
  Epoch 46/60
Model trained in 3.11s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.029
  Epoch 47/60
Model trained in 3.06s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.791
  Epoch 48/60
Model trained in 2.98s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.223
  Epoch 49/60
Model trained in 2.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.326
  Epoch 50/60
Model trained in 2.95s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.229
  Epoch 51/60
Model trained in 3.00s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.904
  Epoch 52/60
Model trained in 3.03s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.629
  Epoch 53/60
Model trained in 3.01s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.160
  Epoch 54/60
Model trained in 3.16s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.610
  Epoch 55/60
Model trained in 3.01s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.793
  Epoch 56/60
Model trained in 3.02s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.491
  Epoch 57/60
Model trained in 2.95s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.137
  Early stopping triggered.

  best_val_SMAPE=79.080

Combination 1023/1152: {'encoder_hidden_size': 48, 'encoder_layers': 2, 'encoder_dropout': 0.0, 'decoder_hidden_size': 33, 'decoder_layers': 2, 'decoder_dropout': 0.2, 'learning_rate': 0.0005, 'max_epochs': 60, 'patience': 20, 'batch_size': 64, 'sequence_length': 24}
Time: 356.32 minutes - estimated total time: 401.25 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 1.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 185.270
  Epoch 2/60
Model trained in 1.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 178.749
  Epoch 3/60
Model trained in 1.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 173.547
  Epoch 4/60
Model trained in 1.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 168.880
  Epoch 5/60
Model trained in 1.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 164.546
  Epoch 6/60
Model trained in 1.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 160.497
  Epoch 7/60
Model trained in 1.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 156.769
  Epoch 8/60
Model trained in 1.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 153.221
  Epoch 9/60
Model trained in 1.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 149.885
  Epoch 10/60
Model trained in 1.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 146.694
  Epoch 11/60
Model trained in 1.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 143.620
  Epoch 12/60
Model trained in 1.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 140.694
  Epoch 13/60
Model trained in 1.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 137.861
  Epoch 14/60
Model trained in 1.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 135.130
  Epoch 15/60
Model trained in 1.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 132.448
  Epoch 16/60
Model trained in 1.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 129.815
  Epoch 17/60
Model trained in 1.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 127.245
  Epoch 18/60
Model trained in 1.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 124.742
  Epoch 19/60
Model trained in 1.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 122.288
  Epoch 20/60
Model trained in 1.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 121.123
  Epoch 21/60
Model trained in 1.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 121.709
  Epoch 22/60
Model trained in 1.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 120.164
  Epoch 23/60
Model trained in 1.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 118.479
  Epoch 24/60
Model trained in 1.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 116.428
  Epoch 25/60
Model trained in 1.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 114.579
  Epoch 26/60
Model trained in 1.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 112.774
  Epoch 27/60
Model trained in 1.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 110.958
  Epoch 28/60
Model trained in 1.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 108.993
  Epoch 29/60
Model trained in 1.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 107.242
  Epoch 30/60
Model trained in 1.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 105.160
  Epoch 31/60
Model trained in 1.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 103.760
  Epoch 32/60
Model trained in 1.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 102.430
  Epoch 33/60
Model trained in 1.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 101.853
  Epoch 34/60
Model trained in 1.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 100.584
  Epoch 35/60
Model trained in 1.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 98.943
  Epoch 36/60
Model trained in 1.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 97.677
  Epoch 37/60
Model trained in 1.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 96.711
  Epoch 38/60
Model trained in 1.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 95.449
  Epoch 39/60
Model trained in 1.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.450
  Epoch 40/60
Model trained in 1.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.878
  Epoch 41/60
Model trained in 1.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.593
  Epoch 42/60
Model trained in 1.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.506
  Epoch 43/60
Model trained in 1.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.287
  Epoch 44/60
Model trained in 1.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.189
  Epoch 45/60
Model trained in 1.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.346
  Epoch 46/60
Model trained in 1.97s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.558
  Epoch 47/60
Model trained in 2.00s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.894
  Epoch 48/60
Model trained in 2.01s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.591
  Epoch 49/60
Model trained in 1.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.553
  Epoch 50/60
Model trained in 1.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.798
  Epoch 51/60
Model trained in 1.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.427
  Epoch 52/60
Model trained in 1.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.981
  Epoch 53/60
Model trained in 1.97s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.541
  Epoch 54/60
Model trained in 1.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.930
  Epoch 55/60
Model trained in 1.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.344
  Epoch 56/60
Model trained in 1.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.019
  Epoch 57/60
Model trained in 1.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.864
  Epoch 58/60
Model trained in 1.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.198
  Epoch 59/60
Model trained in 2.12s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.590
  Epoch 60/60
Model trained in 1.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.423

  best_val_SMAPE=77.423

Combination 1024/1152: {'encoder_hidden_size': 48, 'encoder_layers': 2, 'encoder_dropout': 0.0, 'decoder_hidden_size': 33, 'decoder_layers': 2, 'decoder_dropout': 0.2, 'learning_rate': 0.0005, 'max_epochs': 60, 'patience': 20, 'batch_size': 64, 'sequence_length': 168}
Time: 358.64 minutes - estimated total time: 403.47 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 1.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 185.320
  Epoch 2/60
Model trained in 1.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 178.833
  Epoch 3/60
Model trained in 2.29s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 173.666
  Epoch 4/60
Model trained in 2.18s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 169.027
  Epoch 5/60
Model trained in 2.41s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 164.711
  Epoch 6/60
Model trained in 2.13s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 160.681
  Epoch 7/60
Model trained in 2.12s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 156.965
  Epoch 8/60
Model trained in 2.01s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 153.428
  Epoch 9/60
Model trained in 2.06s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 150.105
  Epoch 10/60
Model trained in 2.01s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 146.927
  Epoch 11/60
Model trained in 2.07s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 143.863
  Epoch 12/60
Model trained in 2.15s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 140.946
  Epoch 13/60
Model trained in 2.23s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 138.123
  Epoch 14/60
Model trained in 2.04s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 135.404
  Epoch 15/60
Model trained in 2.04s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 132.735
  Epoch 16/60
Model trained in 2.03s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 130.114
  Epoch 17/60
Model trained in 1.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 127.552
  Epoch 18/60
Model trained in 1.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 127.554
  Epoch 19/60
Model trained in 1.98s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 124.369
  Epoch 20/60
Model trained in 2.06s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 121.959
  Epoch 21/60
Model trained in 1.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 120.158
  Epoch 22/60
Model trained in 1.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 118.740
  Epoch 23/60
Model trained in 1.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 116.790
  Epoch 24/60
Model trained in 1.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 114.397
  Epoch 25/60
Model trained in 2.04s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 112.742
  Epoch 26/60
Model trained in 1.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 112.195
  Epoch 27/60
Model trained in 2.10s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 110.136
  Epoch 28/60
Model trained in 1.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 108.776
  Epoch 29/60
Model trained in 1.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 106.755
  Epoch 30/60
Model trained in 1.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 104.817
  Epoch 31/60
Model trained in 1.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 103.548
  Epoch 32/60
Model trained in 1.98s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 101.702
  Epoch 33/60
Model trained in 1.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 100.326
  Epoch 34/60
Model trained in 2.33s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 98.864
  Epoch 35/60
Model trained in 2.01s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 97.517
  Epoch 36/60
Model trained in 1.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 95.922
  Epoch 37/60
Model trained in 1.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 94.224
  Epoch 38/60
Model trained in 1.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.781
  Epoch 39/60
Model trained in 1.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.029
  Epoch 40/60
Model trained in 1.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.015
  Epoch 41/60
Model trained in 2.06s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.342
  Epoch 42/60
Model trained in 1.95s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.263
  Epoch 43/60
Model trained in 1.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.096
  Epoch 44/60
Model trained in 1.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.043
  Epoch 45/60
Model trained in 1.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.204
  Epoch 46/60
Model trained in 1.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.774
  Epoch 47/60
Model trained in 1.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.684
  Epoch 48/60
Model trained in 2.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.799
  Epoch 49/60
Model trained in 2.99s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.766
  Epoch 50/60
Model trained in 2.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.847
  Epoch 51/60
Model trained in 3.02s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.198
  Epoch 52/60
Model trained in 3.00s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.012
  Epoch 53/60
Model trained in 3.02s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.970
  Epoch 54/60
Model trained in 2.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.439
  Epoch 55/60
Model trained in 2.97s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.889
  Epoch 56/60
Model trained in 2.48s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.965
  Epoch 57/60
Model trained in 2.08s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.963
  Epoch 58/60
Model trained in 1.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.611
  Epoch 59/60
Model trained in 1.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.270
  Epoch 60/60
Model trained in 1.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.247

  best_val_SMAPE=75.247

Combination 1025/1152: {'encoder_hidden_size': 48, 'encoder_layers': 2, 'encoder_dropout': 0.0, 'decoder_hidden_size': 48, 'decoder_layers': 1, 'decoder_dropout': 0.0, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 20, 'batch_size': 32, 'sequence_length': 24}
Time: 361.28 minutes - estimated total time: 406.04 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 2.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 160.794
  Epoch 2/60
Model trained in 2.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 141.702
  Epoch 3/60
Model trained in 2.58s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 127.062
  Epoch 4/60
Model trained in 2.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 114.635
  Epoch 5/60
Model trained in 2.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 104.989
  Epoch 6/60
Model trained in 3.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 96.016
  Epoch 7/60
Model trained in 3.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.744
  Epoch 8/60
Model trained in 3.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.128
  Epoch 9/60
Model trained in 3.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.446
  Epoch 10/60
Model trained in 3.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.181
  Epoch 11/60
Model trained in 3.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.538
  Epoch 12/60
Model trained in 3.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.314
  Epoch 13/60
Model trained in 3.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.699
  Epoch 14/60
Model trained in 3.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.024
  Epoch 15/60
Model trained in 3.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.411
  Epoch 16/60
Model trained in 3.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.223
  Epoch 17/60
Model trained in 3.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.767
  Epoch 18/60
Model trained in 3.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.110
  Epoch 19/60
Model trained in 3.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.070
  Epoch 20/60
Model trained in 3.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.790
  Epoch 21/60
Model trained in 3.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.946
  Epoch 22/60
Model trained in 3.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.573
  Epoch 23/60
Model trained in 3.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.624
  Epoch 24/60
Model trained in 3.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 95.269
  Epoch 25/60
Model trained in 3.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.985
  Epoch 26/60
Model trained in 3.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.671
  Epoch 27/60
Model trained in 3.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.927
  Epoch 28/60
Model trained in 3.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.399
  Epoch 29/60
Model trained in 3.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.550
  Epoch 30/60
Model trained in 3.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.575
  Early stopping triggered.

  best_val_SMAPE=77.181

Combination 1026/1152: {'encoder_hidden_size': 48, 'encoder_layers': 2, 'encoder_dropout': 0.0, 'decoder_hidden_size': 48, 'decoder_layers': 1, 'decoder_dropout': 0.0, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 20, 'batch_size': 32, 'sequence_length': 168}
Time: 363.43 minutes - estimated total time: 408.07 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 3.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 160.867
  Epoch 2/60
Model trained in 4.04s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 141.842
  Epoch 3/60
Model trained in 4.07s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 127.230
  Epoch 4/60
Model trained in 4.03s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 115.084
  Epoch 5/60
Model trained in 3.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 104.577
  Epoch 6/60
Model trained in 4.11s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 96.077
  Epoch 7/60
Model trained in 3.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.135
  Epoch 8/60
Model trained in 3.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.753
  Epoch 9/60
Model trained in 3.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.988
  Epoch 10/60
Model trained in 3.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.188
  Epoch 11/60
Model trained in 4.02s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.444
  Epoch 12/60
Model trained in 3.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.724
  Epoch 13/60
Model trained in 3.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.862
  Epoch 14/60
Model trained in 3.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.711
  Epoch 15/60
Model trained in 3.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.760
  Epoch 16/60
Model trained in 4.04s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.421
  Epoch 17/60
Model trained in 3.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 97.229
  Epoch 18/60
Model trained in 3.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 98.197
  Epoch 19/60
Model trained in 3.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 104.012
  Epoch 20/60
Model trained in 3.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 98.975
  Epoch 21/60
Model trained in 3.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 100.909
  Epoch 22/60
Model trained in 4.05s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 103.279
  Epoch 23/60
Model trained in 4.08s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 104.164
  Epoch 24/60
Model trained in 4.04s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 98.073
  Epoch 25/60
Model trained in 4.04s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 99.152
  Epoch 26/60
Model trained in 4.11s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 98.523
  Epoch 27/60
Model trained in 4.02s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 96.026
  Epoch 28/60
Model trained in 3.59s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 102.249
  Epoch 29/60
Model trained in 3.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 100.904
  Epoch 30/60
Model trained in 4.00s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 103.495
  Early stopping triggered.

  best_val_SMAPE=80.188

Combination 1027/1152: {'encoder_hidden_size': 48, 'encoder_layers': 2, 'encoder_dropout': 0.0, 'decoder_hidden_size': 48, 'decoder_layers': 1, 'decoder_dropout': 0.0, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 20, 'batch_size': 64, 'sequence_length': 24}
Time: 365.77 minutes - estimated total time: 410.28 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 2.51s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 173.319
  Epoch 2/60
Model trained in 2.48s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 160.497
  Epoch 3/60
Model trained in 2.48s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 150.231
  Epoch 4/60
Model trained in 2.40s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 141.424
  Epoch 5/60
Model trained in 2.45s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 133.722
  Epoch 6/60
Model trained in 2.44s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 126.553
  Epoch 7/60
Model trained in 2.45s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 119.921
  Epoch 8/60
Model trained in 2.48s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 114.283
  Epoch 9/60
Model trained in 2.44s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 109.050
  Epoch 10/60
Model trained in 2.27s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 104.314
  Epoch 11/60
Model trained in 2.38s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 99.973
  Epoch 12/60
Model trained in 2.44s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 96.090
  Epoch 13/60
Model trained in 2.35s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.912
  Epoch 14/60
Model trained in 2.48s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.205
  Epoch 15/60
Model trained in 2.40s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.325
  Epoch 16/60
Model trained in 2.38s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.202
  Epoch 17/60
Model trained in 2.31s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.425
  Epoch 18/60
Model trained in 2.29s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.867
  Epoch 19/60
Model trained in 2.32s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.754
  Epoch 20/60
Model trained in 2.40s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.262
  Epoch 21/60
Model trained in 2.40s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.081
  Epoch 22/60
Model trained in 2.35s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.242
  Epoch 23/60
Model trained in 2.39s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.250
  Epoch 24/60
Model trained in 2.31s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.117
  Epoch 25/60
Model trained in 2.46s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.034
  Epoch 26/60
Model trained in 2.41s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.835
  Epoch 27/60
Model trained in 2.50s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.765
  Epoch 28/60
Model trained in 2.41s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.628
  Epoch 29/60
Model trained in 2.44s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.260
  Epoch 30/60
Model trained in 2.48s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.188
  Epoch 31/60
Model trained in 2.46s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.015
  Epoch 32/60
Model trained in 2.27s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.890
  Epoch 33/60
Model trained in 2.35s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.817
  Epoch 34/60
Model trained in 2.32s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.176
  Epoch 35/60
Model trained in 2.39s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.996
  Epoch 36/60
Model trained in 2.43s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.752
  Epoch 37/60
Model trained in 2.53s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.185
  Epoch 38/60
Model trained in 2.46s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.384
  Epoch 39/60
Model trained in 2.46s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.903
  Epoch 40/60
Model trained in 2.45s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.282
  Epoch 41/60
Model trained in 2.38s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.408
  Epoch 42/60
Model trained in 2.27s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.651
  Epoch 43/60
Model trained in 2.41s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.154
  Epoch 44/60
Model trained in 2.46s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.541
  Epoch 45/60
Model trained in 2.51s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.230
  Early stopping triggered.

  best_val_SMAPE=77.034

Combination 1028/1152: {'encoder_hidden_size': 48, 'encoder_layers': 2, 'encoder_dropout': 0.0, 'decoder_hidden_size': 48, 'decoder_layers': 1, 'decoder_dropout': 0.0, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 20, 'batch_size': 64, 'sequence_length': 168}
Time: 368.10 minutes - estimated total time: 412.50 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 2.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 173.419
  Epoch 2/60
Model trained in 2.63s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 160.667
  Epoch 3/60
Model trained in 2.61s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 150.434
  Epoch 4/60
Model trained in 2.60s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 141.671
  Epoch 5/60
Model trained in 2.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 133.904
  Epoch 6/60
Model trained in 2.65s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 126.944
  Epoch 7/60
Model trained in 2.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 120.448
  Epoch 8/60
Model trained in 2.62s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 115.023
  Epoch 9/60
Model trained in 2.60s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 109.792
  Epoch 10/60
Model trained in 2.60s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 105.285
  Epoch 11/60
Model trained in 2.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 100.671
  Epoch 12/60
Model trained in 2.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 96.551
  Epoch 13/60
Model trained in 2.68s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.038
  Epoch 14/60
Model trained in 2.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.113
  Epoch 15/60
Model trained in 2.60s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.568
  Epoch 16/60
Model trained in 2.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.229
  Epoch 17/60
Model trained in 2.68s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.210
  Epoch 18/60
Model trained in 2.52s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.129
  Epoch 19/60
Model trained in 2.57s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.773
  Epoch 20/60
Model trained in 2.56s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.218
  Epoch 21/60
Model trained in 2.57s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 72.700
  Epoch 22/60
Model trained in 2.55s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 72.409
  Epoch 23/60
Model trained in 2.57s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 71.908
  Epoch 24/60
Model trained in 2.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.053
  Epoch 25/60
Model trained in 2.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.149
  Epoch 26/60
Model trained in 2.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.711
  Epoch 27/60
Model trained in 2.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.086
  Epoch 28/60
Model trained in 2.59s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.873
  Epoch 29/60
Model trained in 2.53s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.751
  Epoch 30/60
Model trained in 2.61s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.680
  Epoch 31/60
Model trained in 2.49s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.221
  Epoch 32/60
Model trained in 2.63s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.035
  Epoch 33/60
Model trained in 2.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.728
  Epoch 34/60
Model trained in 2.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.607
  Epoch 35/60
Model trained in 2.62s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.223
  Epoch 36/60
Model trained in 2.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.636
  Epoch 37/60
Model trained in 2.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.646
  Epoch 38/60
Model trained in 2.51s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.257
  Epoch 39/60
Model trained in 2.57s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.087
  Epoch 40/60
Model trained in 2.65s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.664
  Epoch 41/60
Model trained in 2.59s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.393
  Epoch 42/60
Model trained in 2.67s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.690
  Epoch 43/60
Model trained in 2.63s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.550
  Early stopping triggered.

  best_val_SMAPE=71.908

Combination 1029/1152: {'encoder_hidden_size': 48, 'encoder_layers': 2, 'encoder_dropout': 0.0, 'decoder_hidden_size': 48, 'decoder_layers': 1, 'decoder_dropout': 0.0, 'learning_rate': 0.0005, 'max_epochs': 60, 'patience': 20, 'batch_size': 32, 'sequence_length': 24}
Time: 370.47 minutes - estimated total time: 414.75 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 3.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 173.404
  Epoch 2/60
Model trained in 3.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 160.767
  Epoch 3/60
Model trained in 3.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 150.531
  Epoch 4/60
Model trained in 3.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 142.017
  Epoch 5/60
Model trained in 3.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 134.743
  Epoch 6/60
Model trained in 3.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 127.135
  Epoch 7/60
Model trained in 3.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 120.628
  Epoch 8/60
Model trained in 3.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 114.788
  Epoch 9/60
Model trained in 3.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 109.577
  Epoch 10/60
Model trained in 3.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 104.520
  Epoch 11/60
Model trained in 3.67s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 100.664
  Epoch 12/60
Model trained in 3.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 97.167
  Epoch 13/60
Model trained in 3.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 94.002
  Epoch 14/60
Model trained in 3.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.357
  Epoch 15/60
Model trained in 3.50s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.257
  Epoch 16/60
Model trained in 3.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.269
  Epoch 17/60
Model trained in 3.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.859
  Epoch 18/60
Model trained in 3.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.612
  Epoch 19/60
Model trained in 3.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.619
  Epoch 20/60
Model trained in 3.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.167
  Epoch 21/60
Model trained in 3.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.284
  Epoch 22/60
Model trained in 3.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.613
  Epoch 23/60
Model trained in 3.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.149
  Epoch 24/60
Model trained in 3.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.500
  Epoch 25/60
Model trained in 3.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 94.394
  Epoch 26/60
Model trained in 3.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 96.477
  Epoch 27/60
Model trained in 3.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 95.524
  Epoch 28/60
Model trained in 3.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 96.803
  Epoch 29/60
Model trained in 3.62s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 99.858
  Epoch 30/60
Model trained in 3.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 94.679
  Epoch 31/60
Model trained in 3.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 98.745
  Epoch 32/60
Model trained in 3.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.134
  Epoch 33/60
Model trained in 3.60s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.578
  Epoch 34/60
Model trained in 3.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.531
  Epoch 35/60
Model trained in 3.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.933
  Epoch 36/60
Model trained in 3.55s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.161
  Epoch 37/60
Model trained in 3.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.472
  Epoch 38/60
Model trained in 3.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.138
  Epoch 39/60
Model trained in 3.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.471
  Epoch 40/60
Model trained in 3.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.003
  Epoch 41/60
Model trained in 3.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 96.153
  Epoch 42/60
Model trained in 3.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 94.179
  Epoch 43/60
Model trained in 3.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 105.419
  Epoch 44/60
Model trained in 3.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 115.390
  Epoch 45/60
Model trained in 3.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 113.568
  Epoch 46/60
Model trained in 3.67s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 94.830
  Epoch 47/60
Model trained in 3.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 100.413
  Epoch 48/60
Model trained in 3.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 106.527
  Epoch 49/60
Model trained in 3.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.358
  Epoch 50/60
Model trained in 3.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 105.776
  Epoch 51/60
Model trained in 3.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 101.899
  Epoch 52/60
Model trained in 3.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 98.178
  Epoch 53/60
Model trained in 3.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 98.689
  Epoch 54/60
Model trained in 3.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 95.777
  Epoch 55/60
Model trained in 3.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 101.872
  Epoch 56/60
Model trained in 3.67s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 103.706
  Epoch 57/60
Model trained in 3.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 107.083
  Early stopping triggered.

  best_val_SMAPE=85.472

Combination 1030/1152: {'encoder_hidden_size': 48, 'encoder_layers': 2, 'encoder_dropout': 0.0, 'decoder_hidden_size': 48, 'decoder_layers': 1, 'decoder_dropout': 0.0, 'learning_rate': 0.0005, 'max_epochs': 60, 'patience': 20, 'batch_size': 32, 'sequence_length': 168}
Time: 374.69 minutes - estimated total time: 419.07 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 4.12s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 173.480
  Epoch 2/60
Model trained in 4.01s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 160.902
  Epoch 3/60
Model trained in 4.07s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 150.692
  Epoch 4/60
Model trained in 3.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 141.877
  Epoch 5/60
Model trained in 3.98s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 134.280
  Epoch 6/60
Model trained in 3.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 127.372
  Epoch 7/60
Model trained in 3.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 120.746
  Epoch 8/60
Model trained in 4.06s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 115.087
  Epoch 9/60
Model trained in 4.12s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 109.930
  Epoch 10/60
Model trained in 3.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 105.290
  Epoch 11/60
Model trained in 3.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 103.678
  Epoch 12/60
Model trained in 3.51s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 96.919
  Epoch 13/60
Model trained in 3.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.641
  Epoch 14/60
Model trained in 3.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.110
  Epoch 15/60
Model trained in 3.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.937
  Epoch 16/60
Model trained in 3.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.208
  Epoch 17/60
Model trained in 3.99s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.271
  Epoch 18/60
Model trained in 4.02s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.111
  Epoch 19/60
Model trained in 3.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.064
  Epoch 20/60
Model trained in 4.14s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.775
  Epoch 21/60
Model trained in 3.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.030
  Epoch 22/60
Model trained in 4.14s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.811
  Epoch 23/60
Model trained in 4.09s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.846
  Epoch 24/60
Model trained in 4.09s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.824
  Epoch 25/60
Model trained in 4.05s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.539
  Epoch 26/60
Model trained in 4.09s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.294
  Epoch 27/60
Model trained in 3.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.399
  Epoch 28/60
Model trained in 3.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 94.178
  Epoch 29/60
Model trained in 3.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 95.140
  Epoch 30/60
Model trained in 4.05s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 95.346
  Epoch 31/60
Model trained in 3.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 96.354
  Epoch 32/60
Model trained in 3.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 95.893
  Epoch 33/60
Model trained in 3.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.156
  Epoch 34/60
Model trained in 3.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 94.877
  Epoch 35/60
Model trained in 3.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 99.867
  Epoch 36/60
Model trained in 3.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 96.552
  Epoch 37/60
Model trained in 3.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 101.116
  Epoch 38/60
Model trained in 3.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 98.635
  Epoch 39/60
Model trained in 4.09s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 98.990
  Epoch 40/60
Model trained in 4.05s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 100.789
  Early stopping triggered.

  best_val_SMAPE=80.775

Combination 1031/1152: {'encoder_hidden_size': 48, 'encoder_layers': 2, 'encoder_dropout': 0.0, 'decoder_hidden_size': 48, 'decoder_layers': 1, 'decoder_dropout': 0.0, 'learning_rate': 0.0005, 'max_epochs': 60, 'patience': 20, 'batch_size': 64, 'sequence_length': 24}
Time: 377.77 minutes - estimated total time: 422.11 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 2.58s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 181.280
  Epoch 2/60
Model trained in 2.41s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 173.255
  Epoch 3/60
Model trained in 2.45s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 166.560
  Epoch 4/60
Model trained in 2.47s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 160.604
  Epoch 5/60
Model trained in 2.48s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 155.256
  Epoch 6/60
Model trained in 2.40s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 150.390
  Epoch 7/60
Model trained in 2.38s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 145.831
  Epoch 8/60
Model trained in 2.41s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 141.569
  Epoch 9/60
Model trained in 2.46s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 137.612
  Epoch 10/60
Model trained in 2.47s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 133.831
  Epoch 11/60
Model trained in 2.41s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 130.302
  Epoch 12/60
Model trained in 2.38s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 126.738
  Epoch 13/60
Model trained in 2.50s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 123.434
  Epoch 14/60
Model trained in 2.34s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 120.283
  Epoch 15/60
Model trained in 2.38s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 117.350
  Epoch 16/60
Model trained in 2.43s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 114.248
  Epoch 17/60
Model trained in 2.44s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 111.912
  Epoch 18/60
Model trained in 2.41s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 109.239
  Epoch 19/60
Model trained in 2.36s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 107.134
  Epoch 20/60
Model trained in 2.37s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 104.527
  Epoch 21/60
Model trained in 2.35s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 103.535
  Epoch 22/60
Model trained in 2.36s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 102.180
  Epoch 23/60
Model trained in 2.34s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 98.198
  Epoch 24/60
Model trained in 2.44s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 95.848
  Epoch 25/60
Model trained in 2.37s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.750
  Epoch 26/60
Model trained in 2.36s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.083
  Epoch 27/60
Model trained in 2.35s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.560
  Epoch 28/60
Model trained in 2.30s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.336
  Epoch 29/60
Model trained in 2.35s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.674
  Epoch 30/60
Model trained in 2.33s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.863
  Epoch 31/60
Model trained in 2.36s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.416
  Epoch 32/60
Model trained in 2.40s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.412
  Epoch 33/60
Model trained in 2.50s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.577
  Epoch 34/60
Model trained in 2.38s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.031
  Epoch 35/60
Model trained in 2.41s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.825
  Epoch 36/60
Model trained in 2.42s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.145
  Epoch 37/60
Model trained in 2.40s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.984
  Epoch 38/60
Model trained in 2.46s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.943
  Epoch 39/60
Model trained in 2.44s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.223
  Epoch 40/60
Model trained in 2.47s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.248
  Epoch 41/60
Model trained in 2.47s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.082
  Epoch 42/60
Model trained in 2.42s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.557
  Epoch 43/60
Model trained in 2.50s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.014
  Epoch 44/60
Model trained in 2.41s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.978
  Epoch 45/60
Model trained in 2.40s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.880
  Epoch 46/60
Model trained in 2.34s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.493
  Epoch 47/60
Model trained in 2.42s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.077
  Epoch 48/60
Model trained in 2.49s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.790
  Epoch 49/60
Model trained in 2.44s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.885
  Epoch 50/60
Model trained in 2.39s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.252
  Epoch 51/60
Model trained in 2.39s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.490
  Epoch 52/60
Model trained in 2.34s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.042
  Epoch 53/60
Model trained in 2.33s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.608
  Epoch 54/60
Model trained in 2.35s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.154
  Epoch 55/60
Model trained in 2.36s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.630
  Epoch 56/60
Model trained in 2.36s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.044
  Epoch 57/60
Model trained in 2.39s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.788
  Epoch 58/60
Model trained in 2.34s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.944
  Epoch 59/60
Model trained in 2.31s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.979
  Epoch 60/60
Model trained in 2.34s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.596

  best_val_SMAPE=80.880

Combination 1032/1152: {'encoder_hidden_size': 48, 'encoder_layers': 2, 'encoder_dropout': 0.0, 'decoder_hidden_size': 48, 'decoder_layers': 1, 'decoder_dropout': 0.0, 'learning_rate': 0.0005, 'max_epochs': 60, 'patience': 20, 'batch_size': 64, 'sequence_length': 168}
Time: 380.84 minutes - estimated total time: 425.12 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 2.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 181.362
  Epoch 2/60
Model trained in 2.67s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 173.366
  Epoch 3/60
Model trained in 2.68s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 166.706
  Epoch 4/60
Model trained in 2.65s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 160.773
  Epoch 5/60
Model trained in 2.54s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 155.490
  Epoch 6/60
Model trained in 2.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 150.716
  Epoch 7/60
Model trained in 2.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 146.032
  Epoch 8/60
Model trained in 2.63s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 141.848
  Epoch 9/60
Model trained in 2.58s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 137.964
  Epoch 10/60
Model trained in 2.62s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 134.259
  Epoch 11/60
Model trained in 2.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 130.591
  Epoch 12/60
Model trained in 2.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 127.189
  Epoch 13/60
Model trained in 2.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 123.808
  Epoch 14/60
Model trained in 2.63s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 120.704
  Epoch 15/60
Model trained in 2.61s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 117.656
  Epoch 16/60
Model trained in 2.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 114.960
  Epoch 17/60
Model trained in 2.56s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 111.933
  Epoch 18/60
Model trained in 2.57s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 109.522
  Epoch 19/60
Model trained in 2.50s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 107.128
  Epoch 20/60
Model trained in 2.53s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 104.747
  Epoch 21/60
Model trained in 2.55s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 102.514
  Epoch 22/60
Model trained in 2.54s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 100.344
  Epoch 23/60
Model trained in 2.59s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 98.195
  Epoch 24/60
Model trained in 2.49s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 96.214
  Epoch 25/60
Model trained in 2.55s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 94.243
  Epoch 26/60
Model trained in 2.61s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.715
  Epoch 27/60
Model trained in 2.52s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.233
  Epoch 28/60
Model trained in 2.59s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.743
  Epoch 29/60
Model trained in 2.56s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.251
  Epoch 30/60
Model trained in 2.56s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.696
  Epoch 31/60
Model trained in 2.55s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.830
  Epoch 32/60
Model trained in 2.53s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.039
  Epoch 33/60
Model trained in 2.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.360
  Epoch 34/60
Model trained in 2.67s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.619
  Epoch 35/60
Model trained in 2.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.140
  Epoch 36/60
Model trained in 2.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.085
  Epoch 37/60
Model trained in 2.68s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.475
  Epoch 38/60
Model trained in 2.60s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.503
  Epoch 39/60
Model trained in 2.62s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.870
  Epoch 40/60
Model trained in 2.55s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.558
  Epoch 41/60
Model trained in 2.62s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.271
  Epoch 42/60
Model trained in 2.60s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.313
  Epoch 43/60
Model trained in 2.63s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.652
  Epoch 44/60
Model trained in 2.50s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.363
  Epoch 45/60
Model trained in 2.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.517
  Epoch 46/60
Model trained in 2.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.964
  Epoch 47/60
Model trained in 2.67s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.786
  Epoch 48/60
Model trained in 2.58s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.156
  Epoch 49/60
Model trained in 2.54s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.700
  Epoch 50/60
Model trained in 2.50s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.551
  Epoch 51/60
Model trained in 2.56s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.347
  Epoch 52/60
Model trained in 2.61s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.636
  Epoch 53/60
Model trained in 2.56s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.858
  Epoch 54/60
Model trained in 2.65s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.383
  Epoch 55/60
Model trained in 2.57s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.508
  Epoch 56/60
Model trained in 2.54s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.659
  Epoch 57/60
Model trained in 2.53s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.689
  Epoch 58/60
Model trained in 2.49s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.060
  Epoch 59/60
Model trained in 2.57s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.659
  Epoch 60/60
Model trained in 2.54s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.896

  best_val_SMAPE=80.271

Combination 1041/1152: {'encoder_hidden_size': 48, 'encoder_layers': 2, 'encoder_dropout': 0.0, 'decoder_hidden_size': 48, 'decoder_layers': 2, 'decoder_dropout': 0.0, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 20, 'batch_size': 32, 'sequence_length': 24}
Time: 384.10 minutes - estimated total time: 425.05 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 4.11s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 161.254
  Epoch 2/60
Model trained in 4.09s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 141.885
  Epoch 3/60
Model trained in 4.02s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 126.584
  Epoch 4/60
Model trained in 4.24s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 116.827
  Epoch 5/60
Model trained in 4.08s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 106.071
  Epoch 6/60
Model trained in 4.09s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 99.189
  Epoch 7/60
Model trained in 4.11s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.456
  Epoch 8/60
Model trained in 3.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.669
  Epoch 9/60
Model trained in 4.00s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.265
  Epoch 10/60
Model trained in 4.10s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.834
  Epoch 11/60
Model trained in 4.03s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.280
  Epoch 12/60
Model trained in 3.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.293
  Epoch 13/60
Model trained in 3.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.387
  Epoch 14/60
Model trained in 3.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.922
  Epoch 15/60
Model trained in 3.63s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.788
  Epoch 16/60
Model trained in 3.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.217
  Epoch 17/60
Model trained in 4.03s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.102
  Epoch 18/60
Model trained in 3.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.383
  Epoch 19/60
Model trained in 3.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.586
  Epoch 20/60
Model trained in 3.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.722
  Epoch 21/60
Model trained in 3.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.169
  Epoch 22/60
Model trained in 3.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.627
  Epoch 23/60
Model trained in 4.05s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.939
  Epoch 24/60
Model trained in 4.12s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.131
  Epoch 25/60
Model trained in 4.06s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.887
  Epoch 26/60
Model trained in 4.04s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.117
  Epoch 27/60
Model trained in 4.09s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.509
  Epoch 28/60
Model trained in 3.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.942
  Epoch 29/60
Model trained in 3.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.036
  Epoch 30/60
Model trained in 3.99s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.766
  Epoch 31/60
Model trained in 4.11s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.688
  Epoch 32/60
Model trained in 4.05s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.430
  Epoch 33/60
Model trained in 3.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.641
  Epoch 34/60
Model trained in 3.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.978
  Epoch 35/60
Model trained in 4.00s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.084
  Epoch 36/60
Model trained in 3.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.935
  Early stopping triggered.

  best_val_SMAPE=78.217

Combination 1042/1152: {'encoder_hidden_size': 48, 'encoder_layers': 2, 'encoder_dropout': 0.0, 'decoder_hidden_size': 48, 'decoder_layers': 2, 'decoder_dropout': 0.0, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 20, 'batch_size': 32, 'sequence_length': 168}
Time: 386.90 minutes - estimated total time: 427.74 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 4.35s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 161.415
  Epoch 2/60
Model trained in 4.37s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 142.116
  Epoch 3/60
Model trained in 4.15s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 126.858
  Epoch 4/60
Model trained in 4.27s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 117.403
  Epoch 5/60
Model trained in 4.25s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 108.475
  Epoch 6/60
Model trained in 4.10s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 102.086
  Epoch 7/60
Model trained in 4.13s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 95.757
  Epoch 8/60
Model trained in 4.23s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.577
  Epoch 9/60
Model trained in 4.31s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.429
  Epoch 10/60
Model trained in 4.16s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.030
  Epoch 11/60
Model trained in 4.29s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.609
  Epoch 12/60
Model trained in 4.22s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.769
  Epoch 13/60
Model trained in 4.25s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.853
  Epoch 14/60
Model trained in 4.30s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.828
  Epoch 15/60
Model trained in 4.07s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.998
  Epoch 16/60
Model trained in 3.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.744
  Epoch 17/60
Model trained in 3.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.983
  Epoch 18/60
Model trained in 4.03s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.674
  Epoch 19/60
Model trained in 4.13s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.697
  Epoch 20/60
Model trained in 4.12s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.391
  Epoch 21/60
Model trained in 4.09s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.149
  Epoch 22/60
Model trained in 4.23s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.394
  Epoch 23/60
Model trained in 4.03s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.617
  Epoch 24/60
Model trained in 4.28s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.375
  Epoch 25/60
Model trained in 4.20s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.480
  Epoch 26/60
Model trained in 4.16s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.914
  Epoch 27/60
Model trained in 4.02s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.512
  Epoch 28/60
Model trained in 4.30s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.704
  Epoch 29/60
Model trained in 4.29s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.052
  Epoch 30/60
Model trained in 4.12s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.870
  Epoch 31/60
Model trained in 4.20s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.120
  Epoch 32/60
Model trained in 4.31s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.285
  Epoch 33/60
Model trained in 4.22s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.988
  Epoch 34/60
Model trained in 4.31s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.743
  Epoch 35/60
Model trained in 4.18s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.543
  Epoch 36/60
Model trained in 4.14s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.528
  Epoch 37/60
Model trained in 4.08s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.525
  Epoch 38/60
Model trained in 4.10s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.779
  Epoch 39/60
Model trained in 4.13s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.463
  Epoch 40/60
Model trained in 4.00s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.357
  Epoch 41/60
Model trained in 4.08s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.053
  Epoch 42/60
Model trained in 4.10s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.107
  Early stopping triggered.

  best_val_SMAPE=80.394

Combination 1043/1152: {'encoder_hidden_size': 48, 'encoder_layers': 2, 'encoder_dropout': 0.0, 'decoder_hidden_size': 48, 'decoder_layers': 2, 'decoder_dropout': 0.0, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 20, 'batch_size': 64, 'sequence_length': 24}
Time: 390.28 minutes - estimated total time: 431.06 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 2.52s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 174.097
  Epoch 2/60
Model trained in 2.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 161.011
  Epoch 3/60
Model trained in 2.53s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 150.601
  Epoch 4/60
Model trained in 2.54s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 141.663
  Epoch 5/60
Model trained in 2.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 133.714
  Epoch 6/60
Model trained in 2.60s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 127.274
  Epoch 7/60
Model trained in 2.54s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 122.479
  Epoch 8/60
Model trained in 2.52s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 116.824
  Epoch 9/60
Model trained in 2.48s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 110.985
  Epoch 10/60
Model trained in 2.47s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 106.526
  Epoch 11/60
Model trained in 2.52s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 102.893
  Epoch 12/60
Model trained in 2.52s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 98.160
  Epoch 13/60
Model trained in 2.54s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 94.646
  Epoch 14/60
Model trained in 2.47s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.789
  Epoch 15/60
Model trained in 2.46s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.963
  Epoch 16/60
Model trained in 2.45s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.626
  Epoch 17/60
Model trained in 2.50s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.014
  Epoch 18/60
Model trained in 2.45s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.053
  Epoch 19/60
Model trained in 2.46s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.026
  Epoch 20/60
Model trained in 2.47s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.405
  Epoch 21/60
Model trained in 2.51s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.486
  Epoch 22/60
Model trained in 2.50s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.054
  Epoch 23/60
Model trained in 2.43s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.234
  Epoch 24/60
Model trained in 2.48s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.633
  Epoch 25/60
Model trained in 2.50s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.162
  Epoch 26/60
Model trained in 2.52s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.769
  Epoch 27/60
Model trained in 2.47s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.479
  Epoch 28/60
Model trained in 2.47s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.714
  Epoch 29/60
Model trained in 2.51s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.384
  Epoch 30/60
Model trained in 2.46s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.150
  Epoch 31/60
Model trained in 2.47s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.302
  Epoch 32/60
Model trained in 2.46s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.331
  Epoch 33/60
Model trained in 2.44s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.521
  Epoch 34/60
Model trained in 2.54s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.859
  Epoch 35/60
Model trained in 2.58s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.618
  Epoch 36/60
Model trained in 2.62s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.902
  Epoch 37/60
Model trained in 2.42s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.776
  Epoch 38/60
Model trained in 2.56s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.225
  Epoch 39/60
Model trained in 2.59s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.606
  Epoch 40/60
Model trained in 2.48s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.220
  Epoch 41/60
Model trained in 2.55s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.075
  Epoch 42/60
Model trained in 2.48s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.456
  Epoch 43/60
Model trained in 2.40s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.195
  Epoch 44/60
Model trained in 2.56s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.825
  Epoch 45/60
Model trained in 2.53s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.365
  Epoch 46/60
Model trained in 2.46s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.499
  Epoch 47/60
Model trained in 2.49s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.679
  Epoch 48/60
Model trained in 2.53s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.777
  Epoch 49/60
Model trained in 2.42s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.063
  Epoch 50/60
Model trained in 2.49s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.177
  Epoch 51/60
Model trained in 2.50s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.093
  Epoch 52/60
Model trained in 2.49s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.472
  Epoch 53/60
Model trained in 2.52s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.817
  Epoch 54/60
Model trained in 2.31s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.701
  Epoch 55/60
Model trained in 2.36s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.713
  Epoch 56/60
Model trained in 2.50s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.687
  Epoch 57/60
Model trained in 2.44s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.935
  Early stopping triggered.

  best_val_SMAPE=81.776

Combination 1044/1152: {'encoder_hidden_size': 48, 'encoder_layers': 2, 'encoder_dropout': 0.0, 'decoder_hidden_size': 48, 'decoder_layers': 2, 'decoder_dropout': 0.0, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 20, 'batch_size': 64, 'sequence_length': 168}
Time: 393.28 minutes - estimated total time: 433.96 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 2.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 174.229
  Epoch 2/60
Model trained in 2.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 161.675
  Epoch 3/60
Model trained in 2.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 151.021
  Epoch 4/60
Model trained in 2.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 142.043
  Epoch 5/60
Model trained in 2.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 134.095
  Epoch 6/60
Model trained in 2.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 126.704
  Epoch 7/60
Model trained in 2.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 120.608
  Epoch 8/60
Model trained in 2.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 118.562
  Epoch 9/60
Model trained in 2.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 113.210
  Epoch 10/60
Model trained in 2.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 108.558
  Epoch 11/60
Model trained in 2.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 104.167
  Epoch 12/60
Model trained in 2.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 99.488
  Epoch 13/60
Model trained in 2.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 96.222
  Epoch 14/60
Model trained in 2.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.035
  Epoch 15/60
Model trained in 2.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.657
  Epoch 16/60
Model trained in 2.65s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.857
  Epoch 17/60
Model trained in 2.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.830
  Epoch 18/60
Model trained in 2.61s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.339
  Epoch 19/60
Model trained in 2.62s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.706
  Epoch 20/60
Model trained in 2.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.690
  Epoch 21/60
Model trained in 2.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.760
  Epoch 22/60
Model trained in 2.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.789
  Epoch 23/60
Model trained in 2.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.309
  Epoch 24/60
Model trained in 2.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.666
  Epoch 25/60
Model trained in 2.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.219
  Epoch 26/60
Model trained in 2.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.543
  Epoch 27/60
Model trained in 2.67s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.591
  Epoch 28/60
Model trained in 2.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.487
  Epoch 29/60
Model trained in 2.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.879
  Epoch 30/60
Model trained in 2.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.433
  Epoch 31/60
Model trained in 2.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.108
  Epoch 32/60
Model trained in 2.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.634
  Epoch 33/60
Model trained in 2.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.816
  Epoch 34/60
Model trained in 2.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.551
  Epoch 35/60
Model trained in 2.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.812
  Epoch 36/60
Model trained in 2.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.960
  Epoch 37/60
Model trained in 2.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.857
  Epoch 38/60
Model trained in 2.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.882
  Epoch 39/60
Model trained in 2.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.658
  Epoch 40/60
Model trained in 2.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.837
  Epoch 41/60
Model trained in 2.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.867
  Epoch 42/60
Model trained in 2.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.141
  Epoch 43/60
Model trained in 2.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.912
  Epoch 44/60
Model trained in 2.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.120
  Epoch 45/60
Model trained in 2.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.933
  Epoch 46/60
Model trained in 2.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.159
  Epoch 47/60
Model trained in 2.67s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.350
  Epoch 48/60
Model trained in 2.65s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.860
  Epoch 49/60
Model trained in 2.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.004
  Epoch 50/60
Model trained in 2.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.538
  Epoch 51/60
Model trained in 2.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.805
  Early stopping triggered.

  best_val_SMAPE=78.108

Combination 1045/1152: {'encoder_hidden_size': 48, 'encoder_layers': 2, 'encoder_dropout': 0.0, 'decoder_hidden_size': 48, 'decoder_layers': 2, 'decoder_dropout': 0.0, 'learning_rate': 0.0005, 'max_epochs': 60, 'patience': 20, 'batch_size': 32, 'sequence_length': 24}
Time: 396.19 minutes - estimated total time: 436.75 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 4.17s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 174.440
  Epoch 2/60
Model trained in 4.11s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 161.765
  Epoch 3/60
Model trained in 4.10s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 151.520
  Epoch 4/60
Model trained in 4.14s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 142.706
  Epoch 5/60
Model trained in 3.98s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 134.846
  Epoch 6/60
Model trained in 3.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 128.132
  Epoch 7/60
Model trained in 3.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 123.229
  Epoch 8/60
Model trained in 4.08s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 118.283
  Epoch 9/60
Model trained in 4.05s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 113.418
  Epoch 10/60
Model trained in 4.07s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 108.162
  Epoch 11/60
Model trained in 4.13s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 103.423
  Epoch 12/60
Model trained in 4.04s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 102.858
  Epoch 13/60
Model trained in 4.04s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 99.268
  Epoch 14/60
Model trained in 3.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 95.717
  Epoch 15/60
Model trained in 3.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.368
  Epoch 16/60
Model trained in 4.02s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.190
  Epoch 17/60
Model trained in 3.99s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.366
  Epoch 18/60
Model trained in 3.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.090
  Epoch 19/60
Model trained in 3.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.298
  Epoch 20/60
Model trained in 3.97s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.107
  Epoch 21/60
Model trained in 3.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.749
  Epoch 22/60
Model trained in 3.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.963
  Epoch 23/60
Model trained in 4.05s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.017
  Epoch 24/60
Model trained in 4.06s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.663
  Epoch 25/60
Model trained in 4.32s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.897
  Epoch 26/60
Model trained in 4.13s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.508
  Epoch 27/60
Model trained in 4.01s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.473
  Epoch 28/60
Model trained in 4.04s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.673
  Epoch 29/60
Model trained in 4.10s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.244
  Epoch 30/60
Model trained in 4.07s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.764
  Epoch 31/60
Model trained in 4.07s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.987
  Epoch 32/60
Model trained in 4.11s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.929
  Epoch 33/60
Model trained in 3.97s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.785
  Epoch 34/60
Model trained in 3.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.650
  Epoch 35/60
Model trained in 3.98s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.986
  Epoch 36/60
Model trained in 3.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.236
  Epoch 37/60
Model trained in 3.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.358
  Epoch 38/60
Model trained in 3.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.013
  Epoch 39/60
Model trained in 3.98s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.896
  Epoch 40/60
Model trained in 3.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.273
  Epoch 41/60
Model trained in 3.98s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.134
  Epoch 42/60
Model trained in 4.02s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.773
  Epoch 43/60
Model trained in 3.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.968
  Epoch 44/60
Model trained in 3.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.485
  Epoch 45/60
Model trained in 3.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.664
  Epoch 46/60
Model trained in 3.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.135
  Epoch 47/60
Model trained in 4.11s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.946
  Epoch 48/60
Model trained in 4.05s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.338
  Epoch 49/60
Model trained in 3.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.602
  Epoch 50/60
Model trained in 3.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.459
  Epoch 51/60
Model trained in 4.07s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.995
  Epoch 52/60
Model trained in 4.00s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.181
  Epoch 53/60
Model trained in 3.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.358
  Epoch 54/60
Model trained in 3.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.598
  Epoch 55/60
Model trained in 3.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.623
  Early stopping triggered.

  best_val_SMAPE=79.986

Combination 1046/1152: {'encoder_hidden_size': 48, 'encoder_layers': 2, 'encoder_dropout': 0.0, 'decoder_hidden_size': 48, 'decoder_layers': 2, 'decoder_dropout': 0.0, 'learning_rate': 0.0005, 'max_epochs': 60, 'patience': 20, 'batch_size': 32, 'sequence_length': 168}
Time: 400.45 minutes - estimated total time: 441.03 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 4.22s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 174.529
  Epoch 2/60
Model trained in 4.29s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 162.332
  Epoch 3/60
Model trained in 4.29s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 151.927
  Epoch 4/60
Model trained in 4.35s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 142.708
  Epoch 5/60
Model trained in 4.15s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 134.683
  Epoch 6/60
Model trained in 3.99s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 127.230
  Epoch 7/60
Model trained in 4.06s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 120.317
  Epoch 8/60
Model trained in 4.25s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 116.591
  Epoch 9/60
Model trained in 4.27s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 113.005
  Epoch 10/60
Model trained in 4.06s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 108.884
  Epoch 11/60
Model trained in 4.09s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 103.995
  Epoch 12/60
Model trained in 4.13s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 100.769
  Epoch 13/60
Model trained in 4.37s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 97.440
  Epoch 14/60
Model trained in 4.36s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.960
  Epoch 15/60
Model trained in 4.24s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.690
  Epoch 16/60
Model trained in 4.16s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.901
  Epoch 17/60
Model trained in 4.14s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.932
  Epoch 18/60
Model trained in 3.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.623
  Epoch 19/60
Model trained in 4.13s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.640
  Epoch 20/60
Model trained in 4.11s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.710
  Epoch 21/60
Model trained in 4.10s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.524
  Epoch 22/60
Model trained in 4.15s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.240
  Epoch 23/60
Model trained in 4.17s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.620
  Epoch 24/60
Model trained in 4.32s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.211
  Epoch 25/60
Model trained in 4.23s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.388
  Epoch 26/60
Model trained in 4.14s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.194
  Epoch 27/60
Model trained in 4.15s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.511
  Epoch 28/60
Model trained in 4.04s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.175
  Epoch 29/60
Model trained in 4.20s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.602
  Epoch 30/60
Model trained in 4.22s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.945
  Epoch 31/60
Model trained in 4.12s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.638
  Epoch 32/60
Model trained in 4.22s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.613
  Epoch 33/60
Model trained in 4.28s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.159
  Epoch 34/60
Model trained in 4.03s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.165
  Epoch 35/60
Model trained in 4.36s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.408
  Epoch 36/60
Model trained in 4.16s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.310
  Epoch 37/60
Model trained in 4.19s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.227
  Epoch 38/60
Model trained in 4.13s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.135
  Epoch 39/60
Model trained in 4.13s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.483
  Epoch 40/60
Model trained in 4.14s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.909
  Epoch 41/60
Model trained in 3.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.853
  Epoch 42/60
Model trained in 4.07s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.441
  Epoch 43/60
Model trained in 4.08s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.188
  Epoch 44/60
Model trained in 4.05s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.262
  Epoch 45/60
Model trained in 4.18s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.179
  Epoch 46/60
Model trained in 4.37s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.527
  Epoch 47/60
Model trained in 4.15s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.199
  Epoch 48/60
Model trained in 4.21s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.048
  Epoch 49/60
Model trained in 4.33s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.304
  Epoch 50/60
Model trained in 4.20s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.427
  Epoch 51/60
Model trained in 4.06s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.997
  Epoch 52/60
Model trained in 4.12s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.017
  Epoch 53/60
Model trained in 4.14s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.323
  Epoch 54/60
Model trained in 4.14s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.628
  Epoch 55/60
Model trained in 4.03s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.181
  Epoch 56/60
Model trained in 4.09s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.856
  Epoch 57/60
Model trained in 4.06s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.575
  Epoch 58/60
Model trained in 4.08s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.658
  Epoch 59/60
Model trained in 4.05s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.290
  Epoch 60/60
Model trained in 3.99s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.403

  best_val_SMAPE=78.997

Combination 1047/1152: {'encoder_hidden_size': 48, 'encoder_layers': 2, 'encoder_dropout': 0.0, 'decoder_hidden_size': 48, 'decoder_layers': 2, 'decoder_dropout': 0.0, 'learning_rate': 0.0005, 'max_epochs': 60, 'patience': 20, 'batch_size': 64, 'sequence_length': 24}
Time: 405.27 minutes - estimated total time: 445.91 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 2.52s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 182.108
  Epoch 2/60
Model trained in 2.57s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 174.263
  Epoch 3/60
Model trained in 2.56s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 167.516
  Epoch 4/60
Model trained in 2.43s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 161.576
  Epoch 5/60
Model trained in 2.61s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 156.236
  Epoch 6/60
Model trained in 2.55s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 151.324
  Epoch 7/60
Model trained in 2.60s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 146.779
  Epoch 8/60
Model trained in 2.63s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 142.485
  Epoch 9/60
Model trained in 2.52s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 138.444
  Epoch 10/60
Model trained in 2.54s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 134.597
  Epoch 11/60
Model trained in 2.50s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 130.856
  Epoch 12/60
Model trained in 2.53s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 126.838
  Epoch 13/60
Model trained in 2.45s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 126.087
  Epoch 14/60
Model trained in 2.40s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 123.384
  Epoch 15/60
Model trained in 2.56s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 120.168
  Epoch 16/60
Model trained in 2.55s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 117.455
  Epoch 17/60
Model trained in 2.47s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 115.068
  Epoch 18/60
Model trained in 2.53s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 112.543
  Epoch 19/60
Model trained in 2.47s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 109.787
  Epoch 20/60
Model trained in 2.50s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 107.614
  Epoch 21/60
Model trained in 2.48s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 105.234
  Epoch 22/60
Model trained in 2.42s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 103.153
  Epoch 23/60
Model trained in 2.36s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 101.320
  Epoch 24/60
Model trained in 2.48s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 99.253
  Epoch 25/60
Model trained in 2.50s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 97.609
  Epoch 26/60
Model trained in 2.53s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 95.719
  Epoch 27/60
Model trained in 2.51s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.972
  Epoch 28/60
Model trained in 2.42s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.562
  Epoch 29/60
Model trained in 2.52s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.573
  Epoch 30/60
Model trained in 2.43s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.812
  Epoch 31/60
Model trained in 2.50s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.666
  Epoch 32/60
Model trained in 2.45s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.267
  Epoch 33/60
Model trained in 2.49s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.418
  Epoch 34/60
Model trained in 2.63s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.830
  Epoch 35/60
Model trained in 2.58s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.832
  Epoch 36/60
Model trained in 2.55s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.971
  Epoch 37/60
Model trained in 2.65s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.910
  Epoch 38/60
Model trained in 2.54s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.178
  Epoch 39/60
Model trained in 2.62s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.636
  Epoch 40/60
Model trained in 2.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.878
  Epoch 41/60
Model trained in 2.67s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.090
  Epoch 42/60
Model trained in 2.57s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.125
  Epoch 43/60
Model trained in 2.49s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.425
  Epoch 44/60
Model trained in 2.52s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.717
  Epoch 45/60
Model trained in 2.59s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.355
  Epoch 46/60
Model trained in 2.53s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.592
  Epoch 47/60
Model trained in 2.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.315
  Epoch 48/60
Model trained in 2.48s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.157
  Epoch 49/60
Model trained in 2.47s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.929
  Epoch 50/60
Model trained in 2.51s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.234
  Epoch 51/60
Model trained in 2.47s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.456
  Epoch 52/60
Model trained in 2.45s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.983
  Epoch 53/60
Model trained in 2.45s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.993
  Epoch 54/60
Model trained in 2.52s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.523
  Epoch 55/60
Model trained in 2.48s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.338
  Epoch 56/60
Model trained in 2.44s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.144
  Epoch 57/60
Model trained in 2.44s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.157
  Epoch 58/60
Model trained in 2.50s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.900
  Epoch 59/60
Model trained in 2.48s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.570
  Epoch 60/60
Model trained in 2.52s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.251

  best_val_SMAPE=75.157

Combination 1048/1152: {'encoder_hidden_size': 48, 'encoder_layers': 2, 'encoder_dropout': 0.0, 'decoder_hidden_size': 48, 'decoder_layers': 2, 'decoder_dropout': 0.0, 'learning_rate': 0.0005, 'max_epochs': 60, 'patience': 20, 'batch_size': 64, 'sequence_length': 168}
Time: 408.44 minutes - estimated total time: 448.98 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 2.98s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 182.193
  Epoch 2/60
Model trained in 2.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 174.479
  Epoch 3/60
Model trained in 2.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 168.027
  Epoch 4/60
Model trained in 2.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 161.968
  Epoch 5/60
Model trained in 2.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 156.572
  Epoch 6/60
Model trained in 2.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 151.648
  Epoch 7/60
Model trained in 2.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 147.101
  Epoch 8/60
Model trained in 2.55s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 142.812
  Epoch 9/60
Model trained in 2.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 138.780
  Epoch 10/60
Model trained in 2.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 134.941
  Epoch 11/60
Model trained in 2.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 131.214
  Epoch 12/60
Model trained in 2.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 127.630
  Epoch 13/60
Model trained in 2.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 125.767
  Epoch 14/60
Model trained in 2.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 122.774
  Epoch 15/60
Model trained in 2.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 119.850
  Epoch 16/60
Model trained in 2.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 117.332
  Epoch 17/60
Model trained in 2.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 114.907
  Epoch 18/60
Model trained in 2.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 112.521
  Epoch 19/60
Model trained in 2.67s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 110.003
  Epoch 20/60
Model trained in 2.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 107.912
  Epoch 21/60
Model trained in 2.65s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 105.503
  Epoch 22/60
Model trained in 2.65s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 103.556
  Epoch 23/60
Model trained in 2.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 101.120
  Epoch 24/60
Model trained in 2.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 99.233
  Epoch 25/60
Model trained in 2.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 97.341
  Epoch 26/60
Model trained in 2.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 95.991
  Epoch 27/60
Model trained in 2.67s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 95.191
  Epoch 28/60
Model trained in 2.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 94.054
  Epoch 29/60
Model trained in 2.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.712
  Epoch 30/60
Model trained in 2.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.858
  Epoch 31/60
Model trained in 2.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.263
  Epoch 32/60
Model trained in 2.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.241
  Epoch 33/60
Model trained in 2.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.077
  Epoch 34/60
Model trained in 2.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.612
  Epoch 35/60
Model trained in 2.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.066
  Epoch 36/60
Model trained in 2.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.029
  Epoch 37/60
Model trained in 2.67s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.271
  Epoch 38/60
Model trained in 2.62s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.512
  Epoch 39/60
Model trained in 2.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.279
  Epoch 40/60
Model trained in 2.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.650
  Epoch 41/60
Model trained in 2.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.312
  Epoch 42/60
Model trained in 2.68s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.002
  Epoch 43/60
Model trained in 2.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.117
  Epoch 44/60
Model trained in 2.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.735
  Epoch 45/60
Model trained in 2.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.276
  Epoch 46/60
Model trained in 2.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.989
  Epoch 47/60
Model trained in 2.62s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.149
  Epoch 48/60
Model trained in 2.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.060
  Epoch 49/60
Model trained in 2.56s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.429
  Epoch 50/60
Model trained in 2.67s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.770
  Epoch 51/60
Model trained in 2.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.516
  Epoch 52/60
Model trained in 2.62s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.835
  Epoch 53/60
Model trained in 2.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.515
  Epoch 54/60
Model trained in 2.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.879
  Epoch 55/60
Model trained in 2.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.648
  Epoch 56/60
Model trained in 2.68s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.888
  Epoch 57/60
Model trained in 2.56s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.437
  Epoch 58/60
Model trained in 2.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.144
  Epoch 59/60
Model trained in 2.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.721
  Epoch 60/60
Model trained in 2.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.952

  best_val_SMAPE=83.429

Combination 1049/1152: {'encoder_hidden_size': 48, 'encoder_layers': 2, 'encoder_dropout': 0.0, 'decoder_hidden_size': 48, 'decoder_layers': 2, 'decoder_dropout': 0.2, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 20, 'batch_size': 32, 'sequence_length': 24}
Time: 411.84 minutes - estimated total time: 452.28 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 4.01s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 161.212
  Epoch 2/60
Model trained in 4.13s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 141.870
  Epoch 3/60
Model trained in 4.04s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 126.573
  Epoch 4/60
Model trained in 4.16s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 116.375
  Epoch 5/60
Model trained in 4.12s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 107.542
  Epoch 6/60
Model trained in 4.02s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 99.826
  Epoch 7/60
Model trained in 4.01s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.098
  Epoch 8/60
Model trained in 4.03s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.520
  Epoch 9/60
Model trained in 4.09s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.467
  Epoch 10/60
Model trained in 4.11s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.739
  Epoch 11/60
Model trained in 4.03s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.583
  Epoch 12/60
Model trained in 4.01s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.129
  Epoch 13/60
Model trained in 3.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.911
  Epoch 14/60
Model trained in 4.02s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.791
  Epoch 15/60
Model trained in 4.13s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.561
  Epoch 16/60
Model trained in 3.95s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.254
  Epoch 17/60
Model trained in 3.98s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.526
  Epoch 18/60
Model trained in 3.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.883
  Epoch 19/60
Model trained in 3.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.293
  Epoch 20/60
Model trained in 3.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.650
  Epoch 21/60
Model trained in 3.97s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.438
  Epoch 22/60
Model trained in 3.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.146
  Epoch 23/60
Model trained in 4.12s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.392
  Epoch 24/60
Model trained in 4.11s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.828
  Epoch 25/60
Model trained in 4.08s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.896
  Epoch 26/60
Model trained in 3.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.888
  Epoch 27/60
Model trained in 4.04s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.251
  Epoch 28/60
Model trained in 3.97s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.107
  Epoch 29/60
Model trained in 4.10s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.657
  Epoch 30/60
Model trained in 4.11s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.323
  Epoch 31/60
Model trained in 3.98s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.768
  Epoch 32/60
Model trained in 3.99s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.310
  Epoch 33/60
Model trained in 4.03s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.541
  Epoch 34/60
Model trained in 4.07s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.008
  Epoch 35/60
Model trained in 3.98s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.977
  Epoch 36/60
Model trained in 3.99s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.267
  Epoch 37/60
Model trained in 4.01s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.416
  Epoch 38/60
Model trained in 4.01s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.518
  Epoch 39/60
Model trained in 3.99s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.924
  Epoch 40/60
Model trained in 3.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.911
  Epoch 41/60
Model trained in 3.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.235
  Epoch 42/60
Model trained in 3.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.741
  Epoch 43/60
Model trained in 4.03s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.831
  Epoch 44/60
Model trained in 4.02s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.798
  Epoch 45/60
Model trained in 4.00s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.713
  Epoch 46/60
Model trained in 4.07s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.750
  Epoch 47/60
Model trained in 4.09s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.071
  Epoch 48/60
Model trained in 3.98s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.922
  Epoch 49/60
Model trained in 3.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.969
  Epoch 50/60
Model trained in 3.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.526
  Epoch 51/60
Model trained in 4.06s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.328
  Epoch 52/60
Model trained in 4.06s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.758
  Epoch 53/60
Model trained in 4.00s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.359
  Epoch 54/60
Model trained in 3.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.308
  Epoch 55/60
Model trained in 3.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.803
  Epoch 56/60
Model trained in 3.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.658
  Epoch 57/60
Model trained in 4.00s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.933
  Epoch 58/60
Model trained in 4.02s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.131
  Epoch 59/60
Model trained in 3.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.826
  Epoch 60/60
Model trained in 4.08s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.385

  best_val_SMAPE=75.385

Combination 1050/1152: {'encoder_hidden_size': 48, 'encoder_layers': 2, 'encoder_dropout': 0.0, 'decoder_hidden_size': 48, 'decoder_layers': 2, 'decoder_dropout': 0.2, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 20, 'batch_size': 32, 'sequence_length': 168}
Time: 416.50 minutes - estimated total time: 456.96 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 4.41s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 161.370
  Epoch 2/60
Model trained in 4.30s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 142.099
  Epoch 3/60
Model trained in 4.32s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 126.820
  Epoch 4/60
Model trained in 4.24s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 115.971
  Epoch 5/60
Model trained in 4.16s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 107.708
  Epoch 6/60
Model trained in 4.26s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 97.924
  Epoch 7/60
Model trained in 4.32s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.607
  Epoch 8/60
Model trained in 4.26s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.933
  Epoch 9/60
Model trained in 4.25s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.957
  Epoch 10/60
Model trained in 4.31s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.764
  Epoch 11/60
Model trained in 4.04s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.233
  Epoch 12/60
Model trained in 4.04s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.022
  Epoch 13/60
Model trained in 4.10s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.626
  Epoch 14/60
Model trained in 4.14s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.498
  Epoch 15/60
Model trained in 4.17s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.522
  Epoch 16/60
Model trained in 4.14s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.786
  Epoch 17/60
Model trained in 4.09s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.898
  Epoch 18/60
Model trained in 3.97s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.597
  Epoch 19/60
Model trained in 4.15s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.393
  Epoch 20/60
Model trained in 4.11s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.979
  Epoch 21/60
Model trained in 4.12s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.617
  Epoch 22/60
Model trained in 4.36s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.742
  Epoch 23/60
Model trained in 4.33s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.396
  Epoch 24/60
Model trained in 4.38s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.836
  Epoch 25/60
Model trained in 4.16s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.132
  Epoch 26/60
Model trained in 4.11s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.826
  Epoch 27/60
Model trained in 4.29s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.671
  Epoch 28/60
Model trained in 4.33s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.239
  Epoch 29/60
Model trained in 4.29s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.064
  Epoch 30/60
Model trained in 4.36s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.316
  Epoch 31/60
Model trained in 4.08s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.052
  Epoch 32/60
Model trained in 4.07s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.666
  Epoch 33/60
Model trained in 4.16s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.900
  Epoch 34/60
Model trained in 4.12s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.238
  Epoch 35/60
Model trained in 4.09s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.379
  Epoch 36/60
Model trained in 4.16s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.248
  Epoch 37/60
Model trained in 4.19s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.571
  Epoch 38/60
Model trained in 4.13s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.151
  Early stopping triggered.

  best_val_SMAPE=76.597

Combination 1051/1152: {'encoder_hidden_size': 48, 'encoder_layers': 2, 'encoder_dropout': 0.0, 'decoder_hidden_size': 48, 'decoder_layers': 2, 'decoder_dropout': 0.2, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 20, 'batch_size': 64, 'sequence_length': 24}
Time: 419.59 minutes - estimated total time: 459.91 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 2.59s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 174.017
  Epoch 2/60
Model trained in 2.56s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 160.993
  Epoch 3/60
Model trained in 2.63s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 150.591
  Epoch 4/60
Model trained in 2.55s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 141.655
  Epoch 5/60
Model trained in 2.54s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 133.709
  Epoch 6/60
Model trained in 2.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 126.997
  Epoch 7/60
Model trained in 2.57s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 122.375
  Epoch 8/60
Model trained in 2.58s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 117.100
  Epoch 9/60
Model trained in 2.63s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 111.895
  Epoch 10/60
Model trained in 2.59s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 107.250
  Epoch 11/60
Model trained in 2.58s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 102.451
  Epoch 12/60
Model trained in 2.50s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 98.405
  Epoch 13/60
Model trained in 2.58s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 95.062
  Epoch 14/60
Model trained in 2.59s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.727
  Epoch 15/60
Model trained in 2.59s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.222
  Epoch 16/60
Model trained in 2.63s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.828
  Epoch 17/60
Model trained in 2.36s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.431
  Epoch 18/60
Model trained in 2.47s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.970
  Epoch 19/60
Model trained in 2.45s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.561
  Epoch 20/60
Model trained in 2.40s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.740
  Epoch 21/60
Model trained in 2.58s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.871
  Epoch 22/60
Model trained in 2.45s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.019
  Epoch 23/60
Model trained in 2.45s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.483
  Epoch 24/60
Model trained in 2.52s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.822
  Epoch 25/60
Model trained in 2.43s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.125
  Epoch 26/60
Model trained in 2.46s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.854
  Epoch 27/60
Model trained in 2.31s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.254
  Epoch 28/60
Model trained in 2.45s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.695
  Epoch 29/60
Model trained in 2.44s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.590
  Epoch 30/60
Model trained in 2.46s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.875
  Epoch 31/60
Model trained in 2.49s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.095
  Epoch 32/60
Model trained in 2.50s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.565
  Epoch 33/60
Model trained in 2.56s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.379
  Epoch 34/60
Model trained in 2.61s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.316
  Epoch 35/60
Model trained in 2.61s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.728
  Epoch 36/60
Model trained in 2.60s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.882
  Epoch 37/60
Model trained in 2.47s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.623
  Epoch 38/60
Model trained in 2.57s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.015
  Epoch 39/60
Model trained in 2.56s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.205
  Epoch 40/60
Model trained in 2.57s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.040
  Epoch 41/60
Model trained in 2.60s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.411
  Epoch 42/60
Model trained in 2.47s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.050
  Epoch 43/60
Model trained in 2.55s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.797
  Epoch 44/60
Model trained in 2.38s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.717
  Epoch 45/60
Model trained in 2.65s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.475
  Epoch 46/60
Model trained in 2.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.020
  Epoch 47/60
Model trained in 2.60s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.321
  Epoch 48/60
Model trained in 2.53s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.578
  Epoch 49/60
Model trained in 2.45s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.667
  Epoch 50/60
Model trained in 2.52s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.612
  Epoch 51/60
Model trained in 2.51s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.643
  Epoch 52/60
Model trained in 2.49s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.823
  Epoch 53/60
Model trained in 2.48s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.471
  Epoch 54/60
Model trained in 2.42s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.021
  Epoch 55/60
Model trained in 2.37s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.164
  Epoch 56/60
Model trained in 2.47s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.175
  Epoch 57/60
Model trained in 2.46s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.541
  Epoch 58/60
Model trained in 2.54s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.797
  Epoch 59/60
Model trained in 2.51s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.329
  Epoch 60/60
Model trained in 2.50s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.990

  best_val_SMAPE=76.578

Combination 1052/1152: {'encoder_hidden_size': 48, 'encoder_layers': 2, 'encoder_dropout': 0.0, 'decoder_hidden_size': 48, 'decoder_layers': 2, 'decoder_dropout': 0.2, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 20, 'batch_size': 64, 'sequence_length': 168}
Time: 422.77 minutes - estimated total time: 462.96 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 2.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 174.214
  Epoch 2/60
Model trained in 2.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 161.517
  Epoch 3/60
Model trained in 2.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 150.942
  Epoch 4/60
Model trained in 2.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 141.993
  Epoch 5/60
Model trained in 2.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 134.055
  Epoch 6/60
Model trained in 2.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 126.665
  Epoch 7/60
Model trained in 2.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 120.316
  Epoch 8/60
Model trained in 2.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 114.604
  Epoch 9/60
Model trained in 2.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 109.326
  Epoch 10/60
Model trained in 2.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 104.771
  Epoch 11/60
Model trained in 2.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 100.607
  Epoch 12/60
Model trained in 2.68s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 96.766
  Epoch 13/60
Model trained in 2.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.973
  Epoch 14/60
Model trained in 2.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.546
  Epoch 15/60
Model trained in 2.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.573
  Epoch 16/60
Model trained in 2.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.178
  Epoch 17/60
Model trained in 2.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.273
  Epoch 18/60
Model trained in 2.67s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.780
  Epoch 19/60
Model trained in 2.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.755
  Epoch 20/60
Model trained in 2.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.230
  Epoch 21/60
Model trained in 2.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.832
  Epoch 22/60
Model trained in 2.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.686
  Epoch 23/60
Model trained in 2.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.274
  Epoch 24/60
Model trained in 2.68s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.688
  Epoch 25/60
Model trained in 2.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.738
  Epoch 26/60
Model trained in 2.68s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.910
  Epoch 27/60
Model trained in 2.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.913
  Epoch 28/60
Model trained in 2.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.533
  Epoch 29/60
Model trained in 2.68s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.183
  Epoch 30/60
Model trained in 2.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.335
  Epoch 31/60
Model trained in 2.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.960
  Epoch 32/60
Model trained in 2.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.185
  Epoch 33/60
Model trained in 2.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.189
  Epoch 34/60
Model trained in 2.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.475
  Epoch 35/60
Model trained in 2.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.683
  Epoch 36/60
Model trained in 2.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.119
  Epoch 37/60
Model trained in 2.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.496
  Epoch 38/60
Model trained in 2.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.321
  Epoch 39/60
Model trained in 2.67s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.457
  Epoch 40/60
Model trained in 2.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.188
  Epoch 41/60
Model trained in 2.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.660
  Early stopping triggered.

  best_val_SMAPE=76.832

Combination 1053/1152: {'encoder_hidden_size': 48, 'encoder_layers': 2, 'encoder_dropout': 0.0, 'decoder_hidden_size': 48, 'decoder_layers': 2, 'decoder_dropout': 0.2, 'learning_rate': 0.0005, 'max_epochs': 60, 'patience': 20, 'batch_size': 32, 'sequence_length': 24}
Time: 425.12 minutes - estimated total time: 465.09 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 4.11s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 174.433
  Epoch 2/60
Model trained in 4.05s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 161.706
  Epoch 3/60
Model trained in 4.09s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 151.485
  Epoch 4/60
Model trained in 4.11s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 142.678
  Epoch 5/60
Model trained in 4.10s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 134.491
  Epoch 6/60
Model trained in 4.01s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 126.986
  Epoch 7/60
Model trained in 3.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 121.639
  Epoch 8/60
Model trained in 3.67s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 114.935
  Epoch 9/60
Model trained in 4.09s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 109.177
  Epoch 10/60
Model trained in 4.14s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 104.141
  Epoch 11/60
Model trained in 4.00s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 99.345
  Epoch 12/60
Model trained in 3.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 94.798
  Epoch 13/60
Model trained in 3.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.166
  Epoch 14/60
Model trained in 3.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.725
  Epoch 15/60
Model trained in 3.97s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.070
  Epoch 16/60
Model trained in 4.05s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.849
  Epoch 17/60
Model trained in 4.20s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.817
  Epoch 18/60
Model trained in 4.11s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.885
  Epoch 19/60
Model trained in 4.15s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.663
  Epoch 20/60
Model trained in 4.09s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.265
  Epoch 21/60
Model trained in 4.00s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.274
  Epoch 22/60
Model trained in 3.98s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.271
  Epoch 23/60
Model trained in 4.11s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.103
  Epoch 24/60
Model trained in 4.09s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.323
  Epoch 25/60
Model trained in 4.08s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.091
  Epoch 26/60
Model trained in 4.15s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.817
  Epoch 27/60
Model trained in 3.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.692
  Epoch 28/60
Model trained in 3.95s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.698
  Epoch 29/60
Model trained in 4.10s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.887
  Epoch 30/60
Model trained in 4.13s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.035
  Epoch 31/60
Model trained in 3.98s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.308
  Epoch 32/60
Model trained in 3.98s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.601
  Epoch 33/60
Model trained in 3.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.581
  Epoch 34/60
Model trained in 3.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.549
  Epoch 35/60
Model trained in 3.99s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.637
  Epoch 36/60
Model trained in 3.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.300
  Epoch 37/60
Model trained in 3.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.666
  Epoch 38/60
Model trained in 4.04s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.469
  Epoch 39/60
Model trained in 3.98s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.105
  Epoch 40/60
Model trained in 4.08s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.900
  Early stopping triggered.

  best_val_SMAPE=73.265

Combination 1054/1152: {'encoder_hidden_size': 48, 'encoder_layers': 2, 'encoder_dropout': 0.0, 'decoder_hidden_size': 48, 'decoder_layers': 2, 'decoder_dropout': 0.2, 'learning_rate': 0.0005, 'max_epochs': 60, 'patience': 20, 'batch_size': 32, 'sequence_length': 168}
Time: 428.25 minutes - estimated total time: 468.07 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 4.38s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 174.521
  Epoch 2/60
Model trained in 4.18s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 162.091
  Epoch 3/60
Model trained in 4.21s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 151.498
  Epoch 4/60
Model trained in 4.26s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 142.485
  Epoch 5/60
Model trained in 4.19s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 134.509
  Epoch 6/60
Model trained in 4.31s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 127.939
  Epoch 7/60
Model trained in 4.26s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 121.688
  Epoch 8/60
Model trained in 4.11s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 116.279
  Epoch 9/60
Model trained in 4.14s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 111.071
  Epoch 10/60
Model trained in 4.33s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 106.733
  Epoch 11/60
Model trained in 4.34s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 102.103
  Epoch 12/60
Model trained in 4.10s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 98.926
  Epoch 13/60
Model trained in 4.14s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 96.337
  Epoch 14/60
Model trained in 4.05s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.047
  Epoch 15/60
Model trained in 4.05s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.869
  Epoch 16/60
Model trained in 4.08s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.000
  Epoch 17/60
Model trained in 4.11s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.557
  Epoch 18/60
Model trained in 4.13s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.256
  Epoch 19/60
Model trained in 4.18s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.327
  Epoch 20/60
Model trained in 4.16s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.727
  Epoch 21/60
Model trained in 4.06s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.615
  Epoch 22/60
Model trained in 4.24s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.601
  Epoch 23/60
Model trained in 4.24s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.800
  Epoch 24/60
Model trained in 4.23s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.456
  Epoch 25/60
Model trained in 4.30s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.742
  Epoch 26/60
Model trained in 4.25s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.584
  Epoch 27/60
Model trained in 4.28s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.262
  Epoch 28/60
Model trained in 4.15s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.345
  Epoch 29/60
Model trained in 3.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.714
  Epoch 30/60
Model trained in 4.32s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.383
  Epoch 31/60
Model trained in 4.30s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.023
  Epoch 32/60
Model trained in 4.08s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.959
  Epoch 33/60
Model trained in 4.07s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.874
  Epoch 34/60
Model trained in 4.10s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.134
  Epoch 35/60
Model trained in 4.07s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.327
  Epoch 36/60
Model trained in 4.05s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.167
  Epoch 37/60
Model trained in 4.09s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.376
  Epoch 38/60
Model trained in 4.18s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.427
  Epoch 39/60
Model trained in 4.10s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.375
  Epoch 40/60
Model trained in 4.14s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.078
  Epoch 41/60
Model trained in 4.07s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.425
  Epoch 42/60
Model trained in 4.08s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.467
  Epoch 43/60
Model trained in 4.09s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.755
  Epoch 44/60
Model trained in 4.08s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.593
  Epoch 45/60
Model trained in 4.06s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.030
  Epoch 46/60
Model trained in 4.14s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.425
  Epoch 47/60
Model trained in 4.36s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.327
  Epoch 48/60
Model trained in 4.32s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.999
  Epoch 49/60
Model trained in 3.98s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.707
  Epoch 50/60
Model trained in 4.06s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.589
  Epoch 51/60
Model trained in 4.13s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.034
  Epoch 52/60
Model trained in 4.31s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 72.443
  Epoch 53/60
Model trained in 4.31s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 71.518
  Epoch 54/60
Model trained in 4.08s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 70.007
  Epoch 55/60
Model trained in 3.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 69.439
  Epoch 56/60
Model trained in 4.08s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 69.507
  Epoch 57/60
Model trained in 4.07s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 69.125
  Epoch 58/60
Model trained in 4.11s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 68.858
  Epoch 59/60
Model trained in 4.09s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 69.156
  Epoch 60/60
Model trained in 4.09s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 69.142

  best_val_SMAPE=68.858

Combination 1055/1152: {'encoder_hidden_size': 48, 'encoder_layers': 2, 'encoder_dropout': 0.0, 'decoder_hidden_size': 48, 'decoder_layers': 2, 'decoder_dropout': 0.2, 'learning_rate': 0.0005, 'max_epochs': 60, 'patience': 20, 'batch_size': 64, 'sequence_length': 24}
Time: 433.07 minutes - estimated total time: 472.88 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 2.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 182.099
  Epoch 2/60
Model trained in 2.61s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 174.134
  Epoch 3/60
Model trained in 2.52s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 167.471
  Epoch 4/60
Model trained in 2.59s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 161.544
  Epoch 5/60
Model trained in 2.53s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 156.210
  Epoch 6/60
Model trained in 2.59s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 151.303
  Epoch 7/60
Model trained in 2.67s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 146.760
  Epoch 8/60
Model trained in 2.50s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 142.468
  Epoch 9/60
Model trained in 2.42s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 138.430
  Epoch 10/60
Model trained in 2.59s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 134.710
  Epoch 11/60
Model trained in 2.58s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 132.572
  Epoch 12/60
Model trained in 2.57s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 129.609
  Epoch 13/60
Model trained in 2.49s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 126.639
  Epoch 14/60
Model trained in 2.59s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 123.416
  Epoch 15/60
Model trained in 2.59s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 120.160
  Epoch 16/60
Model trained in 2.52s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 117.100
  Epoch 17/60
Model trained in 2.42s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 114.335
  Epoch 18/60
Model trained in 2.45s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 111.776
  Epoch 19/60
Model trained in 2.51s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 109.276
  Epoch 20/60
Model trained in 2.44s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 106.446
  Epoch 21/60
Model trained in 2.51s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 103.158
  Epoch 22/60
Model trained in 2.47s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 101.360
  Epoch 23/60
Model trained in 2.51s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 98.994
  Epoch 24/60
Model trained in 2.57s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 95.970
  Epoch 25/60
Model trained in 2.49s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.639
  Epoch 26/60
Model trained in 2.55s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.419
  Epoch 27/60
Model trained in 2.42s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.416
  Epoch 28/60
Model trained in 2.48s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.311
  Epoch 29/60
Model trained in 2.53s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.887
  Epoch 30/60
Model trained in 2.46s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.986
  Epoch 31/60
Model trained in 2.55s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.238
  Epoch 32/60
Model trained in 2.49s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.254
  Epoch 33/60
Model trained in 2.53s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.624
  Epoch 34/60
Model trained in 2.62s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.806
  Epoch 35/60
Model trained in 2.54s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.189
  Epoch 36/60
Model trained in 2.55s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.059
  Epoch 37/60
Model trained in 2.58s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.164
  Epoch 38/60
Model trained in 2.57s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.928
  Epoch 39/60
Model trained in 2.52s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.663
  Epoch 40/60
Model trained in 2.42s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.148
  Epoch 41/60
Model trained in 2.59s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.388
  Epoch 42/60
Model trained in 2.61s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.335
  Epoch 43/60
Model trained in 2.63s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.424
  Epoch 44/60
Model trained in 2.57s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.870
  Epoch 45/60
Model trained in 2.68s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.308
  Epoch 46/60
Model trained in 2.58s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.498
  Epoch 47/60
Model trained in 2.59s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.302
  Epoch 48/60
Model trained in 2.57s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.011
  Epoch 49/60
Model trained in 2.58s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.974
  Epoch 50/60
Model trained in 2.52s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.103
  Epoch 51/60
Model trained in 2.53s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.253
  Epoch 52/60
Model trained in 2.50s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.107
  Epoch 53/60
Model trained in 2.51s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.393
  Epoch 54/60
Model trained in 2.52s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.087
  Epoch 55/60
Model trained in 2.46s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.159
  Epoch 56/60
Model trained in 2.46s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.483
  Epoch 57/60
Model trained in 2.41s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.025
  Epoch 58/60
Model trained in 2.49s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.667
  Epoch 59/60
Model trained in 2.48s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.073
  Epoch 60/60
Model trained in 2.49s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.200

  best_val_SMAPE=77.335

Combination 1056/1152: {'encoder_hidden_size': 48, 'encoder_layers': 2, 'encoder_dropout': 0.0, 'decoder_hidden_size': 48, 'decoder_layers': 2, 'decoder_dropout': 0.2, 'learning_rate': 0.0005, 'max_epochs': 60, 'patience': 20, 'batch_size': 64, 'sequence_length': 168}
Time: 436.25 minutes - estimated total time: 475.91 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 2.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 182.184
  Epoch 2/60
Model trained in 2.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 174.471
  Epoch 3/60
Model trained in 2.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 167.831
  Epoch 4/60
Model trained in 2.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 161.838
  Epoch 5/60
Model trained in 2.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 156.490
  Epoch 6/60
Model trained in 2.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 151.583
  Epoch 7/60
Model trained in 2.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 147.046
  Epoch 8/60
Model trained in 2.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 142.763
  Epoch 9/60
Model trained in 2.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 138.735
  Epoch 10/60
Model trained in 2.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 134.899
  Epoch 11/60
Model trained in 2.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 131.174
  Epoch 12/60
Model trained in 2.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 127.470
  Epoch 13/60
Model trained in 2.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 124.854
  Epoch 14/60
Model trained in 2.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 121.566
  Epoch 15/60
Model trained in 2.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 118.212
  Epoch 16/60
Model trained in 2.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 115.239
  Epoch 17/60
Model trained in 2.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 112.295
  Epoch 18/60
Model trained in 2.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 109.195
  Epoch 19/60
Model trained in 2.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 106.570
  Epoch 20/60
Model trained in 2.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 104.661
  Epoch 21/60
Model trained in 2.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 101.504
  Epoch 22/60
Model trained in 2.68s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 100.284
  Epoch 23/60
Model trained in 2.65s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 98.426
  Epoch 24/60
Model trained in 2.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 96.343
  Epoch 25/60
Model trained in 2.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 94.799
  Epoch 26/60
Model trained in 2.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.940
  Epoch 27/60
Model trained in 2.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.356
  Epoch 28/60
Model trained in 2.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.128
  Epoch 29/60
Model trained in 2.65s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.629
  Epoch 30/60
Model trained in 2.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.129
  Epoch 31/60
Model trained in 2.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.379
  Epoch 32/60
Model trained in 2.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.092
  Epoch 33/60
Model trained in 2.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.412
  Epoch 34/60
Model trained in 2.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.675
  Epoch 35/60
Model trained in 2.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.547
  Epoch 36/60
Model trained in 2.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.629
  Epoch 37/60
Model trained in 2.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.760
  Epoch 38/60
Model trained in 2.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.692
  Epoch 39/60
Model trained in 2.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.930
  Epoch 40/60
Model trained in 2.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.582
  Epoch 41/60
Model trained in 2.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.308
  Epoch 42/60
Model trained in 2.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.670
  Epoch 43/60
Model trained in 2.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.789
  Epoch 44/60
Model trained in 2.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.140
  Epoch 45/60
Model trained in 2.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.923
  Epoch 46/60
Model trained in 2.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.342
  Epoch 47/60
Model trained in 2.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.402
  Epoch 48/60
Model trained in 2.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.105
  Epoch 49/60
Model trained in 2.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 94.417
  Epoch 50/60
Model trained in 2.63s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.691
  Epoch 51/60
Model trained in 2.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 94.684
  Epoch 52/60
Model trained in 2.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 94.321
  Epoch 53/60
Model trained in 2.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 94.981
  Epoch 54/60
Model trained in 2.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 94.499
  Epoch 55/60
Model trained in 2.67s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.238
  Early stopping triggered.

  best_val_SMAPE=83.547

Combination 1057/1152: {'encoder_hidden_size': 48, 'encoder_layers': 2, 'encoder_dropout': 0.2, 'decoder_hidden_size': 28, 'decoder_layers': 1, 'decoder_dropout': 0.0, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 20, 'batch_size': 32, 'sequence_length': 24}
Time: 439.39 minutes - estimated total time: 478.88 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 4.62s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 171.518
  Epoch 2/60
Model trained in 4.27s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 157.333
  Epoch 3/60
Model trained in 4.26s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 146.047
  Epoch 4/60
Model trained in 4.29s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 136.386
  Epoch 5/60
Model trained in 4.27s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 128.002
  Epoch 6/60
Model trained in 4.18s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 120.409
  Epoch 7/60
Model trained in 4.25s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 113.400
  Epoch 8/60
Model trained in 4.30s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 107.181
  Epoch 9/60
Model trained in 4.22s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 101.894
  Epoch 10/60
Model trained in 4.33s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 97.053
  Epoch 11/60
Model trained in 4.19s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.141
  Epoch 12/60
Model trained in 4.18s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.153
  Epoch 13/60
Model trained in 4.24s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.871
  Epoch 14/60
Model trained in 4.10s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.846
  Epoch 15/60
Model trained in 4.14s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.815
  Epoch 16/60
Model trained in 4.16s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.574
  Epoch 17/60
Model trained in 4.16s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.740
  Epoch 18/60
Model trained in 4.12s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.148
  Epoch 19/60
Model trained in 4.17s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.623
  Epoch 20/60
Model trained in 4.06s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.661
  Epoch 21/60
Model trained in 3.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.857
  Epoch 22/60
Model trained in 4.35s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.684
  Epoch 23/60
Model trained in 4.35s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.536
  Epoch 24/60
Model trained in 4.42s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.754
  Epoch 25/60
Model trained in 4.20s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.191
  Epoch 26/60
Model trained in 4.20s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.657
  Epoch 27/60
Model trained in 4.10s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.282
  Epoch 28/60
Model trained in 3.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.088
  Epoch 29/60
Model trained in 4.39s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.364
  Epoch 30/60
Model trained in 4.12s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.422
  Epoch 31/60
Model trained in 4.16s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 94.370
  Epoch 32/60
Model trained in 4.09s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 94.733
  Epoch 33/60
Model trained in 4.17s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.702
  Epoch 34/60
Model trained in 4.20s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.316
  Epoch 35/60
Model trained in 4.19s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.716
  Epoch 36/60
Model trained in 4.21s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.894
  Epoch 37/60
Model trained in 4.19s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.321
  Epoch 38/60
Model trained in 4.27s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.159
  Epoch 39/60
Model trained in 4.03s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.775
  Epoch 40/60
Model trained in 4.11s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.361
  Early stopping triggered.

  best_val_SMAPE=75.661

Combination 1058/1152: {'encoder_hidden_size': 48, 'encoder_layers': 2, 'encoder_dropout': 0.2, 'decoder_hidden_size': 28, 'decoder_layers': 1, 'decoder_dropout': 0.0, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 20, 'batch_size': 32, 'sequence_length': 168}
Time: 442.64 minutes - estimated total time: 481.96 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 4.68s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 171.749
  Epoch 2/60
Model trained in 4.57s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 157.573
  Epoch 3/60
Model trained in 4.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 146.207
  Epoch 4/60
Model trained in 4.61s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 136.671
  Epoch 5/60
Model trained in 4.58s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 128.344
  Epoch 6/60
Model trained in 4.56s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 120.763
  Epoch 7/60
Model trained in 4.40s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 113.790
  Epoch 8/60
Model trained in 4.38s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 107.458
  Epoch 9/60
Model trained in 4.23s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 102.263
  Epoch 10/60
Model trained in 4.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 98.186
  Epoch 11/60
Model trained in 4.38s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 94.316
  Epoch 12/60
Model trained in 4.42s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.067
  Epoch 13/60
Model trained in 4.40s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.821
  Epoch 14/60
Model trained in 4.36s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.308
  Epoch 15/60
Model trained in 4.31s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.937
  Epoch 16/60
Model trained in 4.35s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.926
  Epoch 17/60
Model trained in 4.39s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.110
  Epoch 18/60
Model trained in 4.29s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.192
  Epoch 19/60
Model trained in 4.34s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.603
  Epoch 20/60
Model trained in 4.38s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.124
  Epoch 21/60
Model trained in 4.48s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.418
  Epoch 22/60
Model trained in 4.54s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.685
  Epoch 23/60
Model trained in 4.60s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.402
  Epoch 24/60
Model trained in 4.59s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.565
  Epoch 25/60
Model trained in 4.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.129
  Epoch 26/60
Model trained in 4.43s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.491
  Epoch 27/60
Model trained in 4.45s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.857
  Epoch 28/60
Model trained in 4.54s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.821
  Epoch 29/60
Model trained in 4.49s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.529
  Epoch 30/60
Model trained in 4.27s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.896
  Epoch 31/60
Model trained in 4.27s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.075
  Epoch 32/60
Model trained in 4.36s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.160
  Epoch 33/60
Model trained in 4.26s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.084
  Epoch 34/60
Model trained in 4.23s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.323
  Epoch 35/60
Model trained in 4.26s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.170
  Epoch 36/60
Model trained in 4.32s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.282
  Epoch 37/60
Model trained in 4.35s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.426
  Epoch 38/60
Model trained in 4.29s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.542
  Epoch 39/60
Model trained in 4.36s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.302
  Epoch 40/60
Model trained in 4.29s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.682
  Early stopping triggered.

  best_val_SMAPE=76.124

Combination 1059/1152: {'encoder_hidden_size': 48, 'encoder_layers': 2, 'encoder_dropout': 0.2, 'decoder_hidden_size': 28, 'decoder_layers': 1, 'decoder_dropout': 0.0, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 20, 'batch_size': 64, 'sequence_length': 24}
Time: 446.03 minutes - estimated total time: 485.20 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 2.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 180.510
  Epoch 2/60
Model trained in 2.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 171.482
  Epoch 3/60
Model trained in 2.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 163.896
  Epoch 4/60
Model trained in 2.60s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 157.233
  Epoch 5/60
Model trained in 2.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 151.254
  Epoch 6/60
Model trained in 2.65s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 145.798
  Epoch 7/60
Model trained in 2.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 140.728
  Epoch 8/60
Model trained in 2.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 135.983
  Epoch 9/60
Model trained in 2.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 131.476
  Epoch 10/60
Model trained in 2.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 127.500
  Epoch 11/60
Model trained in 2.63s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 123.574
  Epoch 12/60
Model trained in 2.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 120.178
  Epoch 13/60
Model trained in 2.62s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 116.796
  Epoch 14/60
Model trained in 2.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 113.414
  Epoch 15/60
Model trained in 2.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 110.239
  Epoch 16/60
Model trained in 2.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 107.183
  Epoch 17/60
Model trained in 2.67s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 104.235
  Epoch 18/60
Model trained in 2.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 101.812
  Epoch 19/60
Model trained in 2.62s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 99.902
  Epoch 20/60
Model trained in 2.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 97.976
  Epoch 21/60
Model trained in 2.65s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 96.080
  Epoch 22/60
Model trained in 2.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 94.469
  Epoch 23/60
Model trained in 2.61s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.990
  Epoch 24/60
Model trained in 2.61s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.203
  Epoch 25/60
Model trained in 2.61s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.195
  Epoch 26/60
Model trained in 2.67s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.965
  Epoch 27/60
Model trained in 2.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.937
  Epoch 28/60
Model trained in 2.68s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.652
  Epoch 29/60
Model trained in 2.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.170
  Epoch 30/60
Model trained in 2.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.250
  Epoch 31/60
Model trained in 2.59s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.938
  Epoch 32/60
Model trained in 2.65s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.443
  Epoch 33/60
Model trained in 2.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.571
  Epoch 34/60
Model trained in 2.61s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.190
  Epoch 35/60
Model trained in 2.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.187
  Epoch 36/60
Model trained in 2.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.328
  Epoch 37/60
Model trained in 2.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.973
  Epoch 38/60
Model trained in 2.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.399
  Epoch 39/60
Model trained in 2.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.735
  Epoch 40/60
Model trained in 2.67s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.559
  Epoch 41/60
Model trained in 2.50s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 94.501
  Epoch 42/60
Model trained in 2.58s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.539
  Epoch 43/60
Model trained in 2.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.312
  Epoch 44/60
Model trained in 2.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 95.346
  Epoch 45/60
Model trained in 2.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 94.261
  Epoch 46/60
Model trained in 2.61s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 95.807
  Epoch 47/60
Model trained in 2.67s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 97.543
  Epoch 48/60
Model trained in 2.61s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 97.337
  Epoch 49/60
Model trained in 2.51s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 94.194
  Epoch 50/60
Model trained in 2.62s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 96.634
  Epoch 51/60
Model trained in 2.62s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 96.624
  Epoch 52/60
Model trained in 2.60s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 96.213
  Epoch 53/60
Model trained in 2.60s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 94.897
  Epoch 54/60
Model trained in 2.57s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.094
  Epoch 55/60
Model trained in 2.59s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.708
  Early stopping triggered.

  best_val_SMAPE=87.187

Combination 1060/1152: {'encoder_hidden_size': 48, 'encoder_layers': 2, 'encoder_dropout': 0.2, 'decoder_hidden_size': 28, 'decoder_layers': 1, 'decoder_dropout': 0.0, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 20, 'batch_size': 64, 'sequence_length': 168}
Time: 449.08 minutes - estimated total time: 488.06 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 2.98s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 180.622
  Epoch 2/60
Model trained in 3.00s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 171.594
  Epoch 3/60
Model trained in 2.99s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 164.032
  Epoch 4/60
Model trained in 2.95s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 157.389
  Epoch 5/60
Model trained in 2.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 151.447
  Epoch 6/60
Model trained in 2.95s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 146.113
  Epoch 7/60
Model trained in 2.98s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 141.160
  Epoch 8/60
Model trained in 2.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 136.525
  Epoch 9/60
Model trained in 2.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 132.201
  Epoch 10/60
Model trained in 3.01s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 128.163
  Epoch 11/60
Model trained in 2.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 124.303
  Epoch 12/60
Model trained in 2.98s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 120.542
  Epoch 13/60
Model trained in 2.95s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 116.971
  Epoch 14/60
Model trained in 2.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 113.546
  Epoch 15/60
Model trained in 2.99s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 110.340
  Epoch 16/60
Model trained in 3.02s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 107.417
  Epoch 17/60
Model trained in 2.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 104.785
  Epoch 18/60
Model trained in 2.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 102.427
  Epoch 19/60
Model trained in 2.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 100.370
  Epoch 20/60
Model trained in 2.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 98.319
  Epoch 21/60
Model trained in 2.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 96.503
  Epoch 22/60
Model trained in 2.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 94.758
  Epoch 23/60
Model trained in 2.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.400
  Epoch 24/60
Model trained in 2.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.123
  Epoch 25/60
Model trained in 2.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.231
  Epoch 26/60
Model trained in 2.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.985
  Epoch 27/60
Model trained in 2.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.441
  Epoch 28/60
Model trained in 2.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.958
  Epoch 29/60
Model trained in 2.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.277
  Epoch 30/60
Model trained in 2.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.964
  Epoch 31/60
Model trained in 2.97s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.837
  Epoch 32/60
Model trained in 2.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.363
  Epoch 33/60
Model trained in 2.98s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.978
  Epoch 34/60
Model trained in 2.98s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.141
  Epoch 35/60
Model trained in 2.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.592
  Epoch 36/60
Model trained in 3.00s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.967
  Epoch 37/60
Model trained in 2.95s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.807
  Epoch 38/60
Model trained in 2.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.125
  Epoch 39/60
Model trained in 2.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.663
  Epoch 40/60
Model trained in 3.01s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.549
  Epoch 41/60
Model trained in 2.98s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.712
  Epoch 42/60
Model trained in 2.98s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.014
  Epoch 43/60
Model trained in 2.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 98.595
  Epoch 44/60
Model trained in 2.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 98.501
  Epoch 45/60
Model trained in 2.68s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 102.776
  Epoch 46/60
Model trained in 2.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 103.818
  Epoch 47/60
Model trained in 2.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 100.541
  Epoch 48/60
Model trained in 2.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 100.914
  Epoch 49/60
Model trained in 2.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 101.299
  Epoch 50/60
Model trained in 2.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 100.564
  Epoch 51/60
Model trained in 2.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 99.853
  Epoch 52/60
Model trained in 2.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 103.585
  Epoch 53/60
Model trained in 2.63s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 101.044
  Epoch 54/60
Model trained in 2.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 100.734
  Early stopping triggered.

  best_val_SMAPE=82.141

Combination 1061/1152: {'encoder_hidden_size': 48, 'encoder_layers': 2, 'encoder_dropout': 0.2, 'decoder_hidden_size': 28, 'decoder_layers': 1, 'decoder_dropout': 0.0, 'learning_rate': 0.0005, 'max_epochs': 60, 'patience': 20, 'batch_size': 32, 'sequence_length': 24}
Time: 452.34 minutes - estimated total time: 491.14 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 4.38s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 180.583
  Epoch 2/60
Model trained in 4.31s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 171.713
  Epoch 3/60
Model trained in 4.35s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 164.205
  Epoch 4/60
Model trained in 4.32s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 157.626
  Epoch 5/60
Model trained in 4.28s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 151.701
  Epoch 6/60
Model trained in 4.18s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 146.305
  Epoch 7/60
Model trained in 4.17s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 141.370
  Epoch 8/60
Model trained in 4.28s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 136.724
  Epoch 9/60
Model trained in 4.33s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 132.294
  Epoch 10/60
Model trained in 4.13s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 128.075
  Epoch 11/60
Model trained in 3.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 124.068
  Epoch 12/60
Model trained in 4.20s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 120.298
  Epoch 13/60
Model trained in 4.09s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 116.666
  Epoch 14/60
Model trained in 4.26s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 113.385
  Epoch 15/60
Model trained in 4.09s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 110.412
  Epoch 16/60
Model trained in 3.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 107.351
  Epoch 17/60
Model trained in 4.14s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 106.587
  Epoch 18/60
Model trained in 4.13s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 109.386
  Epoch 19/60
Model trained in 4.20s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 108.331
  Epoch 20/60
Model trained in 4.18s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 106.018
  Epoch 21/60
Model trained in 4.22s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 102.956
  Epoch 22/60
Model trained in 4.38s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 101.002
  Epoch 23/60
Model trained in 4.44s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.346
  Epoch 24/60
Model trained in 4.40s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.798
  Epoch 25/60
Model trained in 4.27s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.751
  Epoch 26/60
Model trained in 4.39s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.212
  Epoch 27/60
Model trained in 4.21s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 95.723
  Epoch 28/60
Model trained in 4.12s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 98.007
  Epoch 29/60
Model trained in 4.28s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 94.364
  Epoch 30/60
Model trained in 4.41s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.922
  Epoch 31/60
Model trained in 4.25s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 94.776
  Epoch 32/60
Model trained in 4.14s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 94.426
  Epoch 33/60
Model trained in 4.25s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 94.427
  Epoch 34/60
Model trained in 4.17s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 94.310
  Epoch 35/60
Model trained in 4.18s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.911
  Epoch 36/60
Model trained in 4.17s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.116
  Epoch 37/60
Model trained in 4.15s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.495
  Epoch 38/60
Model trained in 4.04s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.580
  Epoch 39/60
Model trained in 4.17s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.473
  Epoch 40/60
Model trained in 3.99s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.352
  Epoch 41/60
Model trained in 4.22s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.058
  Epoch 42/60
Model trained in 4.00s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.798
  Epoch 43/60
Model trained in 4.09s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.962
  Epoch 44/60
Model trained in 4.26s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.973
  Epoch 45/60
Model trained in 4.37s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.742
  Epoch 46/60
Model trained in 3.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.960
  Early stopping triggered.

  best_val_SMAPE=85.212

Combination 1062/1152: {'encoder_hidden_size': 48, 'encoder_layers': 2, 'encoder_dropout': 0.2, 'decoder_hidden_size': 28, 'decoder_layers': 1, 'decoder_dropout': 0.0, 'learning_rate': 0.0005, 'max_epochs': 60, 'patience': 20, 'batch_size': 32, 'sequence_length': 168}
Time: 456.07 minutes - estimated total time: 494.72 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 4.68s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 180.693
  Epoch 2/60
Model trained in 4.54s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 171.832
  Epoch 3/60
Model trained in 4.53s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 164.338
  Epoch 4/60
Model trained in 4.37s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 157.754
  Epoch 5/60
Model trained in 4.56s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 151.860
  Epoch 6/60
Model trained in 4.31s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 146.462
  Epoch 7/60
Model trained in 4.46s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 141.449
  Epoch 8/60
Model trained in 4.55s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 136.815
  Epoch 9/60
Model trained in 4.51s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 132.398
  Epoch 10/60
Model trained in 3.97s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 128.179
  Epoch 11/60
Model trained in 4.37s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 124.325
  Epoch 12/60
Model trained in 4.37s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 120.557
  Epoch 13/60
Model trained in 4.36s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 116.993
  Epoch 14/60
Model trained in 4.33s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 113.676
  Epoch 15/60
Model trained in 4.45s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 110.615
  Epoch 16/60
Model trained in 4.01s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 107.713
  Epoch 17/60
Model trained in 4.40s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 104.870
  Epoch 18/60
Model trained in 4.62s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 102.001
  Epoch 19/60
Model trained in 4.59s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 99.580
  Epoch 20/60
Model trained in 4.60s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 97.146
  Epoch 21/60
Model trained in 4.60s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 95.625
  Epoch 22/60
Model trained in 4.52s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.877
  Epoch 23/60
Model trained in 4.56s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.799
  Epoch 24/60
Model trained in 4.59s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.191
  Epoch 25/60
Model trained in 4.43s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.885
  Epoch 26/60
Model trained in 4.34s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.106
  Epoch 27/60
Model trained in 4.28s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.692
  Epoch 28/60
Model trained in 4.58s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.590
  Epoch 29/60
Model trained in 4.42s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.285
  Epoch 30/60
Model trained in 4.43s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.598
  Epoch 31/60
Model trained in 4.36s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.230
  Epoch 32/60
Model trained in 4.45s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.506
  Epoch 33/60
Model trained in 4.32s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.825
  Epoch 34/60
Model trained in 4.47s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.281
  Epoch 35/60
Model trained in 4.34s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.976
  Epoch 36/60
Model trained in 4.29s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.543
  Epoch 37/60
Model trained in 4.10s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.970
  Epoch 38/60
Model trained in 4.33s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.310
  Epoch 39/60
Model trained in 4.38s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.943
  Epoch 40/60
Model trained in 4.45s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.507
  Epoch 41/60
Model trained in 4.37s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.245
  Epoch 42/60
Model trained in 4.40s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.070
  Epoch 43/60
Model trained in 4.67s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.161
  Epoch 44/60
Model trained in 4.59s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.417
  Epoch 45/60
Model trained in 4.40s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.452
  Epoch 46/60
Model trained in 4.36s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.109
  Epoch 47/60
Model trained in 4.49s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.717
  Epoch 48/60
Model trained in 4.40s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.896
  Epoch 49/60
Model trained in 4.33s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.677
  Epoch 50/60
Model trained in 4.10s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.730
  Epoch 51/60
Model trained in 4.37s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.449
  Epoch 52/60
Model trained in 4.38s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.001
  Epoch 53/60
Model trained in 4.37s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.481
  Epoch 54/60
Model trained in 4.25s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.324
  Epoch 55/60
Model trained in 4.01s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.431
  Epoch 56/60
Model trained in 4.10s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 96.490
  Epoch 57/60
Model trained in 4.29s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 98.671
  Epoch 58/60
Model trained in 4.34s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 98.443
  Epoch 59/60
Model trained in 4.32s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.135
  Epoch 60/60
Model trained in 4.20s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.918

  best_val_SMAPE=74.070

Combination 1063/1152: {'encoder_hidden_size': 48, 'encoder_layers': 2, 'encoder_dropout': 0.2, 'decoder_hidden_size': 28, 'decoder_layers': 1, 'decoder_dropout': 0.0, 'learning_rate': 0.0005, 'max_epochs': 60, 'patience': 20, 'batch_size': 64, 'sequence_length': 24}
Time: 461.11 minutes - estimated total time: 499.72 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 2.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 186.689
  Epoch 2/60
Model trained in 2.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 180.532
  Epoch 3/60
Model trained in 2.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 175.840
  Epoch 4/60
Model trained in 2.63s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 171.622
  Epoch 5/60
Model trained in 2.61s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 167.725
  Epoch 6/60
Model trained in 2.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 164.088
  Epoch 7/60
Model trained in 2.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 160.663
  Epoch 8/60
Model trained in 2.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 157.465
  Epoch 9/60
Model trained in 2.62s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 154.394
  Epoch 10/60
Model trained in 2.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 151.506
  Epoch 11/60
Model trained in 2.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 148.742
  Epoch 12/60
Model trained in 2.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 146.078
  Epoch 13/60
Model trained in 2.65s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 143.510
  Epoch 14/60
Model trained in 2.60s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 141.079
  Epoch 15/60
Model trained in 2.67s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 138.709
  Epoch 16/60
Model trained in 2.61s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 136.443
  Epoch 17/60
Model trained in 2.59s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 134.231
  Epoch 18/60
Model trained in 2.59s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 132.061
  Epoch 19/60
Model trained in 2.63s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 129.905
  Epoch 20/60
Model trained in 2.54s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 127.808
  Epoch 21/60
Model trained in 2.56s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 125.777
  Epoch 22/60
Model trained in 2.62s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 123.833
  Epoch 23/60
Model trained in 2.55s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 121.976
  Epoch 24/60
Model trained in 2.55s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 120.222
  Epoch 25/60
Model trained in 2.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 118.582
  Epoch 26/60
Model trained in 2.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 116.903
  Epoch 27/60
Model trained in 2.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 115.365
  Epoch 28/60
Model trained in 2.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 115.201
  Epoch 29/60
Model trained in 2.68s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 114.277
  Epoch 30/60
Model trained in 2.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 113.533
  Epoch 31/60
Model trained in 2.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 112.927
  Epoch 32/60
Model trained in 2.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 111.590
  Epoch 33/60
Model trained in 2.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 110.695
  Epoch 34/60
Model trained in 2.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 106.805
  Epoch 35/60
Model trained in 2.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 108.197
  Epoch 36/60
Model trained in 2.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 107.210
  Epoch 37/60
Model trained in 2.68s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 105.928
  Epoch 38/60
Model trained in 2.67s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 102.540
  Epoch 39/60
Model trained in 2.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 101.037
  Epoch 40/60
Model trained in 2.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 99.948
  Epoch 41/60
Model trained in 2.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 99.022
  Epoch 42/60
Model trained in 2.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 98.028
  Epoch 43/60
Model trained in 2.50s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 97.159
  Epoch 44/60
Model trained in 2.55s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 96.194
  Epoch 45/60
Model trained in 2.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 95.640
  Epoch 46/60
Model trained in 2.68s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 94.958
  Epoch 47/60
Model trained in 2.61s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.516
  Epoch 48/60
Model trained in 2.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.442
  Epoch 49/60
Model trained in 2.56s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.584
  Epoch 50/60
Model trained in 2.57s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.135
  Epoch 51/60
Model trained in 2.67s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.852
  Epoch 52/60
Model trained in 2.67s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.201
  Epoch 53/60
Model trained in 2.57s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.821
  Epoch 54/60
Model trained in 2.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.720
  Epoch 55/60
Model trained in 2.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.475
  Epoch 56/60
Model trained in 2.65s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.548
  Epoch 57/60
Model trained in 2.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.719
  Epoch 58/60
Model trained in 2.62s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.761
  Epoch 59/60
Model trained in 2.65s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.545
  Epoch 60/60
Model trained in 2.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.937

  best_val_SMAPE=85.761

Combination 1064/1152: {'encoder_hidden_size': 48, 'encoder_layers': 2, 'encoder_dropout': 0.2, 'decoder_hidden_size': 28, 'decoder_layers': 1, 'decoder_dropout': 0.0, 'learning_rate': 0.0005, 'max_epochs': 60, 'patience': 20, 'batch_size': 64, 'sequence_length': 168}
Time: 464.43 minutes - estimated total time: 502.84 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 3.10s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 186.744
  Epoch 2/60
Model trained in 2.97s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 180.589
  Epoch 3/60
Model trained in 2.95s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 175.918
  Epoch 4/60
Model trained in 2.99s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 171.709
  Epoch 5/60
Model trained in 2.95s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 167.829
  Epoch 6/60
Model trained in 2.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 164.212
  Epoch 7/60
Model trained in 2.97s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 160.826
  Epoch 8/60
Model trained in 2.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 157.636
  Epoch 9/60
Model trained in 2.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 154.575
  Epoch 10/60
Model trained in 2.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 151.700
  Epoch 11/60
Model trained in 2.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 148.942
  Epoch 12/60
Model trained in 2.99s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 146.286
  Epoch 13/60
Model trained in 2.98s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 143.741
  Epoch 14/60
Model trained in 2.97s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 141.320
  Epoch 15/60
Model trained in 2.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 140.872
  Epoch 16/60
Model trained in 2.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 137.233
  Epoch 17/60
Model trained in 2.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 134.359
  Epoch 18/60
Model trained in 2.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 135.453
  Epoch 19/60
Model trained in 2.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 132.872
  Epoch 20/60
Model trained in 2.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 133.550
  Epoch 21/60
Model trained in 2.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 126.236
  Epoch 22/60
Model trained in 2.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 125.280
  Epoch 23/60
Model trained in 2.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 122.226
  Epoch 24/60
Model trained in 2.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 120.905
  Epoch 25/60
Model trained in 2.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 119.233
  Epoch 26/60
Model trained in 2.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 117.572
  Epoch 27/60
Model trained in 2.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 115.268
  Epoch 28/60
Model trained in 2.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 113.506
  Epoch 29/60
Model trained in 2.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 111.932
  Epoch 30/60
Model trained in 2.99s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 110.365
  Epoch 31/60
Model trained in 2.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 108.824
  Epoch 32/60
Model trained in 2.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 107.577
  Epoch 33/60
Model trained in 3.04s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 106.248
  Epoch 34/60
Model trained in 2.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 104.419
  Epoch 35/60
Model trained in 2.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 103.054
  Epoch 36/60
Model trained in 2.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 101.702
  Epoch 37/60
Model trained in 2.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 100.486
  Epoch 38/60
Model trained in 2.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 99.270
  Epoch 39/60
Model trained in 2.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 98.138
  Epoch 40/60
Model trained in 2.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 97.022
  Epoch 41/60
Model trained in 2.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 95.745
  Epoch 42/60
Model trained in 2.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 94.681
  Epoch 43/60
Model trained in 2.99s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.744
  Epoch 44/60
Model trained in 2.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.776
  Epoch 45/60
Model trained in 2.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.569
  Epoch 46/60
Model trained in 2.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.762
  Epoch 47/60
Model trained in 2.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.603
  Epoch 48/60
Model trained in 2.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.352
  Epoch 49/60
Model trained in 2.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.939
  Epoch 50/60
Model trained in 2.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.395
  Epoch 51/60
Model trained in 2.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.346
  Epoch 52/60
Model trained in 2.63s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.636
  Epoch 53/60
Model trained in 2.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.936
  Epoch 54/60
Model trained in 2.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.470
  Epoch 55/60
Model trained in 2.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.909
  Epoch 56/60
Model trained in 2.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.234
  Epoch 57/60
Model trained in 2.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.848
  Epoch 58/60
Model trained in 2.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.276
  Epoch 59/60
Model trained in 2.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.181
  Epoch 60/60
Model trained in 2.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.882

  best_val_SMAPE=82.882

Combination 1073/1152: {'encoder_hidden_size': 48, 'encoder_layers': 2, 'encoder_dropout': 0.2, 'decoder_hidden_size': 28, 'decoder_layers': 2, 'decoder_dropout': 0.0, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 20, 'batch_size': 32, 'sequence_length': 24}
Time: 467.96 minutes - estimated total time: 502.42 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 4.57s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 171.957
  Epoch 2/60
Model trained in 4.49s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 157.735
  Epoch 3/60
Model trained in 4.60s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 146.307
  Epoch 4/60
Model trained in 4.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 136.494
  Epoch 5/60
Model trained in 4.51s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 128.419
  Epoch 6/60
Model trained in 4.41s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 120.795
  Epoch 7/60
Model trained in 4.43s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 113.317
  Epoch 8/60
Model trained in 4.53s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 106.807
  Epoch 9/60
Model trained in 4.53s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 101.955
  Epoch 10/60
Model trained in 4.43s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 97.487
  Epoch 11/60
Model trained in 4.45s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.194
  Epoch 12/60
Model trained in 4.41s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.252
  Epoch 13/60
Model trained in 4.39s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.924
  Epoch 14/60
Model trained in 4.41s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.870
  Epoch 15/60
Model trained in 4.45s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.806
  Epoch 16/60
Model trained in 4.20s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.218
  Epoch 17/60
Model trained in 4.41s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.338
  Epoch 18/60
Model trained in 4.51s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.374
  Epoch 19/60
Model trained in 4.40s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.354
  Epoch 20/60
Model trained in 4.43s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.317
  Epoch 21/60
Model trained in 4.67s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.659
  Epoch 22/60
Model trained in 4.63s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.887
  Epoch 23/60
Model trained in 4.67s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.665
  Epoch 24/60
Model trained in 4.46s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.401
  Epoch 25/60
Model trained in 4.37s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.318
  Epoch 26/60
Model trained in 4.48s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.977
  Epoch 27/60
Model trained in 4.58s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.882
  Epoch 28/60
Model trained in 4.63s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.268
  Epoch 29/60
Model trained in 4.48s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.005
  Epoch 30/60
Model trained in 4.50s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.711
  Epoch 31/60
Model trained in 4.45s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.845
  Epoch 32/60
Model trained in 4.37s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.611
  Epoch 33/60
Model trained in 4.41s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.976
  Epoch 34/60
Model trained in 4.41s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.505
  Epoch 35/60
Model trained in 4.37s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.798
  Epoch 36/60
Model trained in 4.44s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.326
  Epoch 37/60
Model trained in 4.42s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.721
  Epoch 38/60
Model trained in 4.44s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.662
  Epoch 39/60
Model trained in 4.48s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.369
  Epoch 40/60
Model trained in 4.46s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.026
  Epoch 41/60
Model trained in 4.48s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.841
  Epoch 42/60
Model trained in 4.61s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.534
  Epoch 43/60
Model trained in 4.67s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.415
  Epoch 44/60
Model trained in 4.38s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.149
  Epoch 45/60
Model trained in 4.40s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.238
  Epoch 46/60
Model trained in 4.62s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.917
  Epoch 47/60
Model trained in 4.63s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.611
  Epoch 48/60
Model trained in 4.40s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.611
  Epoch 49/60
Model trained in 4.34s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.974
  Epoch 50/60
Model trained in 4.46s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.418
  Epoch 51/60
Model trained in 4.47s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.759
  Epoch 52/60
Model trained in 4.35s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.390
  Epoch 53/60
Model trained in 4.56s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.682
  Epoch 54/60
Model trained in 4.14s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.094
  Epoch 55/60
Model trained in 4.03s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.002
  Early stopping triggered.

  best_val_SMAPE=73.798

Combination 1074/1152: {'encoder_hidden_size': 48, 'encoder_layers': 2, 'encoder_dropout': 0.2, 'decoder_hidden_size': 28, 'decoder_layers': 2, 'decoder_dropout': 0.0, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 20, 'batch_size': 32, 'sequence_length': 168}
Time: 472.66 minutes - estimated total time: 506.99 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 4.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 172.056
  Epoch 2/60
Model trained in 4.68s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 157.870
  Epoch 3/60
Model trained in 4.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 146.483
  Epoch 4/60
Model trained in 4.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 136.700
  Epoch 5/60
Model trained in 4.57s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 127.834
  Epoch 6/60
Model trained in 4.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 119.667
  Epoch 7/60
Model trained in 4.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 112.345
  Epoch 8/60
Model trained in 4.58s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 105.674
  Epoch 9/60
Model trained in 4.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 104.995
  Epoch 10/60
Model trained in 4.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 100.732
  Epoch 11/60
Model trained in 4.61s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 97.136
  Epoch 12/60
Model trained in 4.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.395
  Epoch 13/60
Model trained in 4.58s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.327
  Epoch 14/60
Model trained in 4.60s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.149
  Epoch 15/60
Model trained in 4.61s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.078
  Epoch 16/60
Model trained in 4.60s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.054
  Epoch 17/60
Model trained in 4.58s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.574
  Epoch 18/60
Model trained in 4.60s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.252
  Epoch 19/60
Model trained in 4.62s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.933
  Epoch 20/60
Model trained in 4.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.054
  Epoch 21/60
Model trained in 4.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.696
  Epoch 22/60
Model trained in 4.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.724
  Epoch 23/60
Model trained in 4.68s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.532
  Epoch 24/60
Model trained in 4.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.032
  Epoch 25/60
Model trained in 4.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.879
  Epoch 26/60
Model trained in 4.62s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.402
  Epoch 27/60
Model trained in 4.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.402
  Epoch 28/60
Model trained in 4.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.194
  Epoch 29/60
Model trained in 4.67s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.618
  Epoch 30/60
Model trained in 4.63s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.890
  Epoch 31/60
Model trained in 4.65s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.916
  Epoch 32/60
Model trained in 4.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.621
  Epoch 33/60
Model trained in 4.55s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.921
  Epoch 34/60
Model trained in 4.63s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.691
  Epoch 35/60
Model trained in 4.52s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.806
  Epoch 36/60
Model trained in 4.59s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.377
  Epoch 37/60
Model trained in 4.63s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.582
  Epoch 38/60
Model trained in 4.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.014
  Epoch 39/60
Model trained in 4.61s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.186
  Epoch 40/60
Model trained in 4.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.667
  Epoch 41/60
Model trained in 4.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.669
  Early stopping triggered.

  best_val_SMAPE=81.696

Combination 1075/1152: {'encoder_hidden_size': 48, 'encoder_layers': 2, 'encoder_dropout': 0.2, 'decoder_hidden_size': 28, 'decoder_layers': 2, 'decoder_dropout': 0.0, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 20, 'batch_size': 64, 'sequence_length': 24}
Time: 476.32 minutes - estimated total time: 510.44 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 2.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 180.857
  Epoch 2/60
Model trained in 2.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 171.864
  Epoch 3/60
Model trained in 2.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 164.273
  Epoch 4/60
Model trained in 2.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 157.586
  Epoch 5/60
Model trained in 2.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 151.588
  Epoch 6/60
Model trained in 2.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 146.115
  Epoch 7/60
Model trained in 2.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 141.025
  Epoch 8/60
Model trained in 2.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 136.268
  Epoch 9/60
Model trained in 2.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 131.720
  Epoch 10/60
Model trained in 2.68s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 127.329
  Epoch 11/60
Model trained in 2.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 123.123
  Epoch 12/60
Model trained in 2.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 120.048
  Epoch 13/60
Model trained in 2.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 117.923
  Epoch 14/60
Model trained in 2.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 114.298
  Epoch 15/60
Model trained in 2.58s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 111.442
  Epoch 16/60
Model trained in 2.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 108.208
  Epoch 17/60
Model trained in 2.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 105.202
  Epoch 18/60
Model trained in 2.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 102.923
  Epoch 19/60
Model trained in 2.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 100.544
  Epoch 20/60
Model trained in 2.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 97.310
  Epoch 21/60
Model trained in 2.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 94.896
  Epoch 22/60
Model trained in 2.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.522
  Epoch 23/60
Model trained in 2.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.249
  Epoch 24/60
Model trained in 2.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.513
  Epoch 25/60
Model trained in 2.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.424
  Epoch 26/60
Model trained in 2.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.409
  Epoch 27/60
Model trained in 2.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.538
  Epoch 28/60
Model trained in 2.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.566
  Epoch 29/60
Model trained in 2.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.275
  Epoch 30/60
Model trained in 2.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.026
  Epoch 31/60
Model trained in 2.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.889
  Epoch 32/60
Model trained in 2.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.069
  Epoch 33/60
Model trained in 2.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.804
  Epoch 34/60
Model trained in 2.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.357
  Epoch 35/60
Model trained in 2.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.298
  Epoch 36/60
Model trained in 2.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.760
  Epoch 37/60
Model trained in 2.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.159
  Epoch 38/60
Model trained in 2.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.954
  Epoch 39/60
Model trained in 2.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.621
  Epoch 40/60
Model trained in 2.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.034
  Epoch 41/60
Model trained in 2.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.863
  Epoch 42/60
Model trained in 2.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.063
  Epoch 43/60
Model trained in 2.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.423
  Epoch 44/60
Model trained in 2.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.432
  Epoch 45/60
Model trained in 2.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.174
  Epoch 46/60
Model trained in 2.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.831
  Epoch 47/60
Model trained in 2.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.455
  Epoch 48/60
Model trained in 2.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.132
  Epoch 49/60
Model trained in 2.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.034
  Epoch 50/60
Model trained in 2.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.044
  Epoch 51/60
Model trained in 2.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.578
  Epoch 52/60
Model trained in 2.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.808
  Epoch 53/60
Model trained in 2.67s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.565
  Epoch 54/60
Model trained in 2.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.110
  Epoch 55/60
Model trained in 2.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.290
  Early stopping triggered.

  best_val_SMAPE=76.298

Combination 1076/1152: {'encoder_hidden_size': 48, 'encoder_layers': 2, 'encoder_dropout': 0.2, 'decoder_hidden_size': 28, 'decoder_layers': 2, 'decoder_dropout': 0.0, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 20, 'batch_size': 64, 'sequence_length': 168}
Time: 479.51 minutes - estimated total time: 513.38 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 3.12s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 180.943
  Epoch 2/60
Model trained in 3.01s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 171.971
  Epoch 3/60
Model trained in 2.97s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 164.416
  Epoch 4/60
Model trained in 3.05s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 157.754
  Epoch 5/60
Model trained in 3.05s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 151.780
  Epoch 6/60
Model trained in 3.02s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 146.330
  Epoch 7/60
Model trained in 3.04s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 141.255
  Epoch 8/60
Model trained in 3.06s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 136.517
  Epoch 9/60
Model trained in 3.02s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 131.991
  Epoch 10/60
Model trained in 2.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 127.617
  Epoch 11/60
Model trained in 2.98s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 123.430
  Epoch 12/60
Model trained in 3.07s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 119.425
  Epoch 13/60
Model trained in 3.11s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 115.665
  Epoch 14/60
Model trained in 3.08s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 112.083
  Epoch 15/60
Model trained in 2.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 109.954
  Epoch 16/60
Model trained in 2.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 108.852
  Epoch 17/60
Model trained in 2.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 106.053
  Epoch 18/60
Model trained in 2.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 103.224
  Epoch 19/60
Model trained in 2.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 101.925
  Epoch 20/60
Model trained in 3.00s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 99.895
  Epoch 21/60
Model trained in 2.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 97.655
  Epoch 22/60
Model trained in 2.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 95.233
  Epoch 23/60
Model trained in 2.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.968
  Epoch 24/60
Model trained in 2.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.682
  Epoch 25/60
Model trained in 2.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.778
  Epoch 26/60
Model trained in 2.97s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.442
  Epoch 27/60
Model trained in 2.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.328
  Epoch 28/60
Model trained in 2.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.794
  Epoch 29/60
Model trained in 3.00s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.024
  Epoch 30/60
Model trained in 3.11s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.197
  Epoch 31/60
Model trained in 3.05s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.200
  Epoch 32/60
Model trained in 3.10s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.944
  Epoch 33/60
Model trained in 3.10s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.418
  Epoch 34/60
Model trained in 2.98s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.501
  Epoch 35/60
Model trained in 2.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.927
  Epoch 36/60
Model trained in 3.00s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.477
  Epoch 37/60
Model trained in 3.02s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.485
  Epoch 38/60
Model trained in 3.05s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.378
  Epoch 39/60
Model trained in 3.06s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.593
  Epoch 40/60
Model trained in 3.00s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.582
  Epoch 41/60
Model trained in 2.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.618
  Epoch 42/60
Model trained in 2.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.102
  Epoch 43/60
Model trained in 3.04s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.696
  Epoch 44/60
Model trained in 2.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.528
  Epoch 45/60
Model trained in 2.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.113
  Epoch 46/60
Model trained in 2.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.613
  Epoch 47/60
Model trained in 2.95s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.383
  Epoch 48/60
Model trained in 2.95s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.126
  Epoch 49/60
Model trained in 2.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.271
  Epoch 50/60
Model trained in 2.98s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.028
  Epoch 51/60
Model trained in 2.97s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.719
  Epoch 52/60
Model trained in 2.97s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.060
  Epoch 53/60
Model trained in 2.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.959
  Epoch 54/60
Model trained in 2.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.194
  Early stopping triggered.

  best_val_SMAPE=78.501

Combination 1077/1152: {'encoder_hidden_size': 48, 'encoder_layers': 2, 'encoder_dropout': 0.2, 'decoder_hidden_size': 28, 'decoder_layers': 2, 'decoder_dropout': 0.0, 'learning_rate': 0.0005, 'max_epochs': 60, 'patience': 20, 'batch_size': 32, 'sequence_length': 24}
Time: 482.81 minutes - estimated total time: 516.43 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 4.61s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 180.843
  Epoch 2/60
Model trained in 4.65s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 172.002
  Epoch 3/60
Model trained in 4.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 164.493
  Epoch 4/60
Model trained in 4.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 157.842
  Epoch 5/60
Model trained in 4.47s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 151.861
  Epoch 6/60
Model trained in 4.50s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 146.390
  Epoch 7/60
Model trained in 4.39s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 141.285
  Epoch 8/60
Model trained in 4.43s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 136.511
  Epoch 9/60
Model trained in 4.57s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 131.944
  Epoch 10/60
Model trained in 4.42s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 127.527
  Epoch 11/60
Model trained in 4.47s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 124.352
  Epoch 12/60
Model trained in 4.44s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 121.209
  Epoch 13/60
Model trained in 4.52s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 117.860
  Epoch 14/60
Model trained in 4.39s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 114.155
  Epoch 15/60
Model trained in 4.44s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 110.730
  Epoch 16/60
Model trained in 4.38s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 107.775
  Epoch 17/60
Model trained in 4.42s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 105.255
  Epoch 18/60
Model trained in 4.43s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 103.494
  Epoch 19/60
Model trained in 4.46s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 100.329
  Epoch 20/60
Model trained in 4.52s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 96.884
  Epoch 21/60
Model trained in 4.59s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 94.281
  Epoch 22/60
Model trained in 4.55s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.059
  Epoch 23/60
Model trained in 4.49s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.798
  Epoch 24/60
Model trained in 4.61s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.664
  Epoch 25/60
Model trained in 4.60s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.552
  Epoch 26/60
Model trained in 4.39s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.986
  Epoch 27/60
Model trained in 4.41s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.496
  Epoch 28/60
Model trained in 4.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.206
  Epoch 29/60
Model trained in 4.58s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.415
  Epoch 30/60
Model trained in 4.40s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.561
  Epoch 31/60
Model trained in 4.40s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.250
  Epoch 32/60
Model trained in 4.42s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.443
  Epoch 33/60
Model trained in 4.49s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.467
  Epoch 34/60
Model trained in 4.45s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.688
  Epoch 35/60
Model trained in 4.44s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.428
  Epoch 36/60
Model trained in 4.20s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.397
  Epoch 37/60
Model trained in 4.52s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.400
  Epoch 38/60
Model trained in 4.35s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.003
  Epoch 39/60
Model trained in 4.17s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.789
  Epoch 40/60
Model trained in 4.34s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.748
  Epoch 41/60
Model trained in 4.17s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.412
  Epoch 42/60
Model trained in 4.33s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.495
  Epoch 43/60
Model trained in 4.45s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.519
  Epoch 44/60
Model trained in 4.54s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.390
  Epoch 45/60
Model trained in 4.44s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.169
  Epoch 46/60
Model trained in 4.39s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.342
  Epoch 47/60
Model trained in 4.49s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.249
  Epoch 48/60
Model trained in 4.58s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.188
  Epoch 49/60
Model trained in 4.31s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.984
  Epoch 50/60
Model trained in 4.46s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.545
  Epoch 51/60
Model trained in 4.46s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.613
  Epoch 52/60
Model trained in 4.26s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.012
  Epoch 53/60
Model trained in 4.02s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.481
  Epoch 54/60
Model trained in 4.41s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.512
  Epoch 55/60
Model trained in 4.39s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.838
  Epoch 56/60
Model trained in 4.46s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.019
  Epoch 57/60
Model trained in 4.43s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.744
  Epoch 58/60
Model trained in 4.36s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.540
  Epoch 59/60
Model trained in 4.33s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.625
  Early stopping triggered.

  best_val_SMAPE=74.789

Combination 1078/1152: {'encoder_hidden_size': 48, 'encoder_layers': 2, 'encoder_dropout': 0.2, 'decoder_hidden_size': 28, 'decoder_layers': 2, 'decoder_dropout': 0.0, 'learning_rate': 0.0005, 'max_epochs': 60, 'patience': 20, 'batch_size': 32, 'sequence_length': 168}
Time: 487.84 minutes - estimated total time: 521.32 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 4.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 180.925
  Epoch 2/60
Model trained in 4.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 172.101
  Epoch 3/60
Model trained in 4.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 164.622
  Epoch 4/60
Model trained in 4.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 157.991
  Epoch 5/60
Model trained in 4.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 152.030
  Epoch 6/60
Model trained in 4.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 146.577
  Epoch 7/60
Model trained in 4.54s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 141.485
  Epoch 8/60
Model trained in 4.52s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 136.727
  Epoch 9/60
Model trained in 4.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 132.179
  Epoch 10/60
Model trained in 4.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 127.777
  Epoch 11/60
Model trained in 4.44s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 124.559
  Epoch 12/60
Model trained in 4.59s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 120.901
  Epoch 13/60
Model trained in 4.60s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 117.551
  Epoch 14/60
Model trained in 4.41s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 113.827
  Epoch 15/60
Model trained in 4.44s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 110.366
  Epoch 16/60
Model trained in 4.51s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 107.369
  Epoch 17/60
Model trained in 4.53s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 105.051
  Epoch 18/60
Model trained in 4.62s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 102.591
  Epoch 19/60
Model trained in 4.59s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 100.057
  Epoch 20/60
Model trained in 4.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 97.810
  Epoch 21/60
Model trained in 4.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 95.533
  Epoch 22/60
Model trained in 4.60s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.341
  Epoch 23/60
Model trained in 3.40s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.347
  Epoch 24/60
Model trained in 3.12s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.251
  Epoch 25/60
Model trained in 3.10s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.326
  Epoch 26/60
Model trained in 3.00s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.117
  Epoch 27/60
Model trained in 2.97s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.061
  Epoch 28/60
Model trained in 3.14s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.529
  Epoch 29/60
Model trained in 3.19s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.906
  Epoch 30/60
Model trained in 2.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.441
  Epoch 31/60
Model trained in 2.97s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.620
  Epoch 32/60
Model trained in 3.10s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.560
  Epoch 33/60
Model trained in 2.97s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.127
  Epoch 34/60
Model trained in 2.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.995
  Epoch 35/60
Model trained in 3.03s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.930
  Epoch 36/60
Model trained in 2.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.348
  Epoch 37/60
Model trained in 3.02s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.137
  Epoch 38/60
Model trained in 3.07s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.478
  Epoch 39/60
Model trained in 2.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.151
  Epoch 40/60
Model trained in 2.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.045
  Epoch 41/60
Model trained in 3.01s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.979
  Epoch 42/60
Model trained in 3.02s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.119
  Epoch 43/60
Model trained in 3.10s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.610
  Epoch 44/60
Model trained in 3.01s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.485
  Epoch 45/60
Model trained in 3.03s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.695
  Epoch 46/60
Model trained in 2.97s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.261
  Epoch 47/60
Model trained in 3.02s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.750
  Epoch 48/60
Model trained in 3.01s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.819
  Epoch 49/60
Model trained in 2.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.013
  Epoch 50/60
Model trained in 3.05s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.295
  Epoch 51/60
Model trained in 3.11s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.465
  Epoch 52/60
Model trained in 3.07s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.833
  Epoch 53/60
Model trained in 2.99s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.054
  Epoch 54/60
Model trained in 3.05s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.683
  Epoch 55/60
Model trained in 3.08s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.748
  Epoch 56/60
Model trained in 3.13s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.824
  Early stopping triggered.

  best_val_SMAPE=76.348

Combination 1079/1152: {'encoder_hidden_size': 48, 'encoder_layers': 2, 'encoder_dropout': 0.2, 'decoder_hidden_size': 28, 'decoder_layers': 2, 'decoder_dropout': 0.0, 'learning_rate': 0.0005, 'max_epochs': 60, 'patience': 20, 'batch_size': 64, 'sequence_length': 24}
Time: 491.77 minutes - estimated total time: 525.04 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 1.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 186.769
  Epoch 2/60
Model trained in 1.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 180.796
  Epoch 3/60
Model trained in 1.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 176.131
  Epoch 4/60
Model trained in 1.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 171.918
  Epoch 5/60
Model trained in 1.95s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 168.025
  Epoch 6/60
Model trained in 1.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 164.377
  Epoch 7/60
Model trained in 1.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 160.922
  Epoch 8/60
Model trained in 1.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 157.701
  Epoch 9/60
Model trained in 1.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 154.614
  Epoch 10/60
Model trained in 1.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 151.695
  Epoch 11/60
Model trained in 1.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 148.900
  Epoch 12/60
Model trained in 1.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 146.201
  Epoch 13/60
Model trained in 1.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 143.584
  Epoch 14/60
Model trained in 1.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 141.078
  Epoch 15/60
Model trained in 1.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 138.642
  Epoch 16/60
Model trained in 1.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 136.284
  Epoch 17/60
Model trained in 1.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 133.970
  Epoch 18/60
Model trained in 1.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 131.693
  Epoch 19/60
Model trained in 1.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 129.458
  Epoch 20/60
Model trained in 1.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 127.375
  Epoch 21/60
Model trained in 1.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 125.561
  Epoch 22/60
Model trained in 1.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 123.859
  Epoch 23/60
Model trained in 1.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 121.900
  Epoch 24/60
Model trained in 1.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 120.104
  Epoch 25/60
Model trained in 1.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 118.455
  Epoch 26/60
Model trained in 1.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 116.617
  Epoch 27/60
Model trained in 1.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 115.094
  Epoch 28/60
Model trained in 1.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 113.750
  Epoch 29/60
Model trained in 1.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 112.085
  Epoch 30/60
Model trained in 1.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 110.503
  Epoch 31/60
Model trained in 1.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 108.679
  Epoch 32/60
Model trained in 1.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 107.389
  Epoch 33/60
Model trained in 1.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 106.120
  Epoch 34/60
Model trained in 1.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 104.984
  Epoch 35/60
Model trained in 1.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 103.478
  Epoch 36/60
Model trained in 1.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 102.122
  Epoch 37/60
Model trained in 1.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 100.966
  Epoch 38/60
Model trained in 1.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 99.642
  Epoch 39/60
Model trained in 1.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 98.686
  Epoch 40/60
Model trained in 1.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 97.395
  Epoch 41/60
Model trained in 1.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 96.220
  Epoch 42/60
Model trained in 1.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 95.273
  Epoch 43/60
Model trained in 1.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 94.155
  Epoch 44/60
Model trained in 1.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.761
  Epoch 45/60
Model trained in 1.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.751
  Epoch 46/60
Model trained in 1.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.685
  Epoch 47/60
Model trained in 1.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.475
  Epoch 48/60
Model trained in 1.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.183
  Epoch 49/60
Model trained in 1.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.038
  Epoch 50/60
Model trained in 1.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.756
  Epoch 51/60
Model trained in 1.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.759
  Epoch 52/60
Model trained in 1.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.007
  Epoch 53/60
Model trained in 1.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.138
  Epoch 54/60
Model trained in 1.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.157
  Epoch 55/60
Model trained in 1.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.787
  Epoch 56/60
Model trained in 1.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.833
  Epoch 57/60
Model trained in 1.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.051
  Epoch 58/60
Model trained in 1.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.211
  Epoch 59/60
Model trained in 1.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.184
  Epoch 60/60
Model trained in 1.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.493

  best_val_SMAPE=78.493

Combination 1080/1152: {'encoder_hidden_size': 48, 'encoder_layers': 2, 'encoder_dropout': 0.2, 'decoder_hidden_size': 28, 'decoder_layers': 2, 'decoder_dropout': 0.0, 'learning_rate': 0.0005, 'max_epochs': 60, 'patience': 20, 'batch_size': 64, 'sequence_length': 168}
Time: 494.03 minutes - estimated total time: 526.96 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 2.08s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 186.812
  Epoch 2/60
Model trained in 1.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 180.859
  Epoch 3/60
Model trained in 1.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 176.214
  Epoch 4/60
Model trained in 1.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 172.020
  Epoch 5/60
Model trained in 1.98s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 168.148
  Epoch 6/60
Model trained in 1.97s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 164.514
  Epoch 7/60
Model trained in 1.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 161.076
  Epoch 8/60
Model trained in 1.98s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 157.863
  Epoch 9/60
Model trained in 1.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 154.791
  Epoch 10/60
Model trained in 1.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 151.882
  Epoch 11/60
Model trained in 1.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 149.098
  Epoch 12/60
Model trained in 1.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 146.410
  Epoch 13/60
Model trained in 1.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 143.803
  Epoch 14/60
Model trained in 1.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 141.305
  Epoch 15/60
Model trained in 1.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 138.880
  Epoch 16/60
Model trained in 1.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 136.530
  Epoch 17/60
Model trained in 1.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 134.229
  Epoch 18/60
Model trained in 1.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 131.963
  Epoch 19/60
Model trained in 1.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 129.732
  Epoch 20/60
Model trained in 1.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 127.545
  Epoch 21/60
Model trained in 1.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 125.412
  Epoch 22/60
Model trained in 1.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 123.311
  Epoch 23/60
Model trained in 1.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 121.258
  Epoch 24/60
Model trained in 1.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 121.577
  Epoch 25/60
Model trained in 1.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 120.094
  Epoch 26/60
Model trained in 1.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 118.614
  Epoch 27/60
Model trained in 1.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 116.797
  Epoch 28/60
Model trained in 1.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 115.479
  Epoch 29/60
Model trained in 1.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 114.148
  Epoch 30/60
Model trained in 1.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 112.955
  Epoch 31/60
Model trained in 2.07s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 111.890
  Epoch 32/60
Model trained in 1.95s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 110.388
  Epoch 33/60
Model trained in 1.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 109.623
  Epoch 34/60
Model trained in 1.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 108.084
  Epoch 35/60
Model trained in 1.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 107.230
  Epoch 36/60
Model trained in 1.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 105.564
  Epoch 37/60
Model trained in 1.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 104.246
  Epoch 38/60
Model trained in 1.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 102.912
  Epoch 39/60
Model trained in 1.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 101.854
  Epoch 40/60
Model trained in 1.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 101.271
  Epoch 41/60
Model trained in 1.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 100.348
  Epoch 42/60
Model trained in 1.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 99.279
  Epoch 43/60
Model trained in 1.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 98.314
  Epoch 44/60
Model trained in 1.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 97.824
  Epoch 45/60
Model trained in 1.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 95.282
  Epoch 46/60
Model trained in 1.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 95.302
  Epoch 47/60
Model trained in 1.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 94.689
  Epoch 48/60
Model trained in 1.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.791
  Epoch 49/60
Model trained in 1.95s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.925
  Epoch 50/60
Model trained in 1.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.975
  Epoch 51/60
Model trained in 1.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.297
  Epoch 52/60
Model trained in 1.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.399
  Epoch 53/60
Model trained in 1.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.504
  Epoch 54/60
Model trained in 1.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.664
  Epoch 55/60
Model trained in 1.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.723
  Epoch 56/60
Model trained in 1.95s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.059
  Epoch 57/60
Model trained in 1.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.844
  Epoch 58/60
Model trained in 1.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.908
  Epoch 59/60
Model trained in 1.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.566
  Epoch 60/60
Model trained in 1.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.509

  best_val_SMAPE=85.509

Combination 1081/1152: {'encoder_hidden_size': 48, 'encoder_layers': 2, 'encoder_dropout': 0.2, 'decoder_hidden_size': 28, 'decoder_layers': 2, 'decoder_dropout': 0.2, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 20, 'batch_size': 32, 'sequence_length': 24}
Time: 496.38 minutes - estimated total time: 528.98 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 2.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 171.949
  Epoch 2/60
Model trained in 3.04s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 157.728
  Epoch 3/60
Model trained in 2.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 146.300
  Epoch 4/60
Model trained in 3.03s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 136.489
  Epoch 5/60
Model trained in 3.01s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 127.590
  Epoch 6/60
Model trained in 3.02s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 122.024
  Epoch 7/60
Model trained in 3.04s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 114.778
  Epoch 8/60
Model trained in 3.04s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 108.355
  Epoch 9/60
Model trained in 2.99s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 102.656
  Epoch 10/60
Model trained in 2.97s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 97.796
  Epoch 11/60
Model trained in 2.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.455
  Epoch 12/60
Model trained in 2.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.065
  Epoch 13/60
Model trained in 3.02s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.658
  Epoch 14/60
Model trained in 3.01s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.644
  Epoch 15/60
Model trained in 2.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.310
  Epoch 16/60
Model trained in 2.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.237
  Epoch 17/60
Model trained in 2.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.885
  Epoch 18/60
Model trained in 2.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.393
  Epoch 19/60
Model trained in 2.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.155
  Epoch 20/60
Model trained in 2.99s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.487
  Epoch 21/60
Model trained in 3.03s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.276
  Epoch 22/60
Model trained in 3.05s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.505
  Epoch 23/60
Model trained in 2.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.962
  Epoch 24/60
Model trained in 2.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.947
  Epoch 25/60
Model trained in 2.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.545
  Epoch 26/60
Model trained in 2.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.469
  Epoch 27/60
Model trained in 2.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.424
  Epoch 28/60
Model trained in 2.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.614
  Epoch 29/60
Model trained in 2.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.309
  Epoch 30/60
Model trained in 2.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.979
  Epoch 31/60
Model trained in 3.10s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.375
  Epoch 32/60
Model trained in 3.04s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.040
  Epoch 33/60
Model trained in 2.97s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.618
  Epoch 34/60
Model trained in 3.10s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.051
  Epoch 35/60
Model trained in 2.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.568
  Epoch 36/60
Model trained in 2.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.058
  Epoch 37/60
Model trained in 2.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.637
  Epoch 38/60
Model trained in 3.11s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.834
  Epoch 39/60
Model trained in 2.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.733
  Epoch 40/60
Model trained in 2.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.925
  Epoch 41/60
Model trained in 2.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.307
  Epoch 42/60
Model trained in 2.97s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.279
  Epoch 43/60
Model trained in 2.99s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.772
  Epoch 44/60
Model trained in 2.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.311
  Epoch 45/60
Model trained in 2.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.799
  Epoch 46/60
Model trained in 2.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.962
  Epoch 47/60
Model trained in 3.08s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.328
  Epoch 48/60
Model trained in 3.01s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.207
  Epoch 49/60
Model trained in 3.00s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.374
  Epoch 50/60
Model trained in 3.02s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.465
  Epoch 51/60
Model trained in 2.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.073
  Epoch 52/60
Model trained in 2.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.386
  Epoch 53/60
Model trained in 2.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.723
  Epoch 54/60
Model trained in 2.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.826
  Epoch 55/60
Model trained in 2.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.507
  Epoch 56/60
Model trained in 2.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.126
  Epoch 57/60
Model trained in 2.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.938
  Epoch 58/60
Model trained in 2.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.009
  Epoch 59/60
Model trained in 2.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.040
  Epoch 60/60
Model trained in 2.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.162

  best_val_SMAPE=79.938

Combination 1082/1152: {'encoder_hidden_size': 48, 'encoder_layers': 2, 'encoder_dropout': 0.2, 'decoder_hidden_size': 28, 'decoder_layers': 2, 'decoder_dropout': 0.2, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 20, 'batch_size': 32, 'sequence_length': 168}
Time: 499.78 minutes - estimated total time: 532.11 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 3.12s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 172.048
  Epoch 2/60
Model trained in 3.11s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 157.863
  Epoch 3/60
Model trained in 3.15s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 146.477
  Epoch 4/60
Model trained in 3.12s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 136.695
  Epoch 5/60
Model trained in 3.06s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 127.829
  Epoch 6/60
Model trained in 3.14s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 119.662
  Epoch 7/60
Model trained in 3.11s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 112.341
  Epoch 8/60
Model trained in 3.11s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 107.922
  Epoch 9/60
Model trained in 3.03s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 104.649
  Epoch 10/60
Model trained in 3.01s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 99.258
  Epoch 11/60
Model trained in 3.15s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 94.228
  Epoch 12/60
Model trained in 3.20s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.908
  Epoch 13/60
Model trained in 3.01s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.578
  Epoch 14/60
Model trained in 2.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.661
  Epoch 15/60
Model trained in 3.02s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.299
  Epoch 16/60
Model trained in 3.03s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.690
  Epoch 17/60
Model trained in 2.97s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.306
  Epoch 18/60
Model trained in 3.01s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.878
  Epoch 19/60
Model trained in 2.98s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.213
  Epoch 20/60
Model trained in 2.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.888
  Epoch 21/60
Model trained in 3.17s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.936
  Epoch 22/60
Model trained in 2.95s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.020
  Epoch 23/60
Model trained in 2.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.465
  Epoch 24/60
Model trained in 3.01s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.433
  Epoch 25/60
Model trained in 2.99s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.849
  Epoch 26/60
Model trained in 2.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.740
  Epoch 27/60
Model trained in 3.04s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.503
  Epoch 28/60
Model trained in 2.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.656
  Epoch 29/60
Model trained in 2.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.573
  Epoch 30/60
Model trained in 3.16s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.162
  Epoch 31/60
Model trained in 3.13s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.077
  Epoch 32/60
Model trained in 3.08s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.987
  Epoch 33/60
Model trained in 3.10s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.838
  Epoch 34/60
Model trained in 3.15s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.479
  Epoch 35/60
Model trained in 3.00s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.711
  Epoch 36/60
Model trained in 3.02s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.479
  Epoch 37/60
Model trained in 3.03s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.415
  Epoch 38/60
Model trained in 3.14s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.754
  Epoch 39/60
Model trained in 3.18s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.733
  Epoch 40/60
Model trained in 2.99s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.641
  Epoch 41/60
Model trained in 2.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.005
  Epoch 42/60
Model trained in 3.06s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.624
  Epoch 43/60
Model trained in 3.09s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.027
  Epoch 44/60
Model trained in 2.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.777
  Epoch 45/60
Model trained in 2.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.724
  Epoch 46/60
Model trained in 2.98s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.105
  Epoch 47/60
Model trained in 2.97s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.231
  Epoch 48/60
Model trained in 3.03s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.553
  Epoch 49/60
Model trained in 3.01s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.323
  Epoch 50/60
Model trained in 2.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.890
  Epoch 51/60
Model trained in 3.00s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.505
  Epoch 52/60
Model trained in 3.05s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.533
  Epoch 53/60
Model trained in 2.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.667
  Epoch 54/60
Model trained in 2.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.388
  Epoch 55/60
Model trained in 3.01s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.788
  Epoch 56/60
Model trained in 3.03s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.355
  Epoch 57/60
Model trained in 2.98s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.506
  Epoch 58/60
Model trained in 2.99s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.621
  Epoch 59/60
Model trained in 2.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.516
  Early stopping triggered.

  best_val_SMAPE=73.733

Combination 1083/1152: {'encoder_hidden_size': 48, 'encoder_layers': 2, 'encoder_dropout': 0.2, 'decoder_hidden_size': 28, 'decoder_layers': 2, 'decoder_dropout': 0.2, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 20, 'batch_size': 64, 'sequence_length': 24}
Time: 503.21 minutes - estimated total time: 535.28 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 1.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 180.848
  Epoch 2/60
Model trained in 1.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 171.855
  Epoch 3/60
Model trained in 1.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 164.265
  Epoch 4/60
Model trained in 1.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 157.578
  Epoch 5/60
Model trained in 1.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 151.581
  Epoch 6/60
Model trained in 1.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 146.108
  Epoch 7/60
Model trained in 1.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 141.019
  Epoch 8/60
Model trained in 1.95s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 136.262
  Epoch 9/60
Model trained in 1.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 131.714
  Epoch 10/60
Model trained in 1.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 127.323
  Epoch 11/60
Model trained in 1.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 124.722
  Epoch 12/60
Model trained in 1.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 121.021
  Epoch 13/60
Model trained in 1.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 116.858
  Epoch 14/60
Model trained in 1.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 113.256
  Epoch 15/60
Model trained in 1.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 109.720
  Epoch 16/60
Model trained in 1.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 106.553
  Epoch 17/60
Model trained in 1.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 103.389
  Epoch 18/60
Model trained in 1.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 100.768
  Epoch 19/60
Model trained in 1.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 97.817
  Epoch 20/60
Model trained in 1.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 95.070
  Epoch 21/60
Model trained in 1.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.190
  Epoch 22/60
Model trained in 1.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.823
  Epoch 23/60
Model trained in 1.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.480
  Epoch 24/60
Model trained in 1.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.689
  Epoch 25/60
Model trained in 1.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.717
  Epoch 26/60
Model trained in 1.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.849
  Epoch 27/60
Model trained in 1.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.759
  Epoch 28/60
Model trained in 1.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.162
  Epoch 29/60
Model trained in 1.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.801
  Epoch 30/60
Model trained in 1.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.113
  Epoch 31/60
Model trained in 1.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.131
  Epoch 32/60
Model trained in 1.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.662
  Epoch 33/60
Model trained in 1.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.955
  Epoch 34/60
Model trained in 1.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.316
  Epoch 35/60
Model trained in 1.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 72.756
  Epoch 36/60
Model trained in 1.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 72.305
  Epoch 37/60
Model trained in 1.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 72.573
  Epoch 38/60
Model trained in 1.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 72.686
  Epoch 39/60
Model trained in 1.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.335
  Epoch 40/60
Model trained in 1.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.515
  Epoch 41/60
Model trained in 1.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.998
  Epoch 42/60
Model trained in 1.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.931
  Epoch 43/60
Model trained in 1.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.832
  Epoch 44/60
Model trained in 1.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.019
  Epoch 45/60
Model trained in 1.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.251
  Epoch 46/60
Model trained in 1.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.121
  Epoch 47/60
Model trained in 1.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.821
  Epoch 48/60
Model trained in 1.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.584
  Epoch 49/60
Model trained in 1.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.254
  Epoch 50/60
Model trained in 1.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.237
  Epoch 51/60
Model trained in 1.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.900
  Epoch 52/60
Model trained in 1.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.925
  Epoch 53/60
Model trained in 1.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.632
  Epoch 54/60
Model trained in 1.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.788
  Epoch 55/60
Model trained in 1.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.617
  Epoch 56/60
Model trained in 1.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.681
  Early stopping triggered.

  best_val_SMAPE=72.305

Combination 1084/1152: {'encoder_hidden_size': 48, 'encoder_layers': 2, 'encoder_dropout': 0.2, 'decoder_hidden_size': 28, 'decoder_layers': 2, 'decoder_dropout': 0.2, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 20, 'batch_size': 64, 'sequence_length': 168}
Time: 505.34 minutes - estimated total time: 537.04 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 2.08s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 180.934
  Epoch 2/60
Model trained in 1.97s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 171.963
  Epoch 3/60
Model trained in 1.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 164.409
  Epoch 4/60
Model trained in 1.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 157.747
  Epoch 5/60
Model trained in 1.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 151.774
  Epoch 6/60
Model trained in 1.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 146.323
  Epoch 7/60
Model trained in 1.97s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 141.250
  Epoch 8/60
Model trained in 1.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 136.512
  Epoch 9/60
Model trained in 1.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 131.986
  Epoch 10/60
Model trained in 1.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 127.612
  Epoch 11/60
Model trained in 1.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 123.425
  Epoch 12/60
Model trained in 1.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 119.420
  Epoch 13/60
Model trained in 1.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 117.924
  Epoch 14/60
Model trained in 1.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 114.333
  Epoch 15/60
Model trained in 1.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 111.107
  Epoch 16/60
Model trained in 1.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 108.349
  Epoch 17/60
Model trained in 1.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 105.430
  Epoch 18/60
Model trained in 1.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 102.637
  Epoch 19/60
Model trained in 1.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 100.219
  Epoch 20/60
Model trained in 1.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 97.954
  Epoch 21/60
Model trained in 1.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 95.916
  Epoch 22/60
Model trained in 1.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.495
  Epoch 23/60
Model trained in 1.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.369
  Epoch 24/60
Model trained in 1.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.386
  Epoch 25/60
Model trained in 1.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.359
  Epoch 26/60
Model trained in 1.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.305
  Epoch 27/60
Model trained in 1.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.570
  Epoch 28/60
Model trained in 1.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.286
  Epoch 29/60
Model trained in 1.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.828
  Epoch 30/60
Model trained in 1.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.147
  Epoch 31/60
Model trained in 1.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.186
  Epoch 32/60
Model trained in 1.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.177
  Epoch 33/60
Model trained in 1.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.927
  Epoch 34/60
Model trained in 1.98s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.230
  Epoch 35/60
Model trained in 1.99s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.517
  Epoch 36/60
Model trained in 1.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.460
  Epoch 37/60
Model trained in 1.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.279
  Epoch 38/60
Model trained in 1.98s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.113
  Epoch 39/60
Model trained in 1.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.856
  Epoch 40/60
Model trained in 1.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.627
  Epoch 41/60
Model trained in 1.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.880
  Epoch 42/60
Model trained in 1.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.314
  Epoch 43/60
Model trained in 2.02s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.335
  Epoch 44/60
Model trained in 1.97s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.211
  Epoch 45/60
Model trained in 1.99s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.462
  Epoch 46/60
Model trained in 1.97s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.846
  Epoch 47/60
Model trained in 1.95s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.057
  Epoch 48/60
Model trained in 1.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.825
  Epoch 49/60
Model trained in 1.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.525
  Epoch 50/60
Model trained in 1.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.629
  Epoch 51/60
Model trained in 1.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.357
  Epoch 52/60
Model trained in 1.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.383
  Epoch 53/60
Model trained in 1.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.278
  Epoch 54/60
Model trained in 2.02s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.012
  Epoch 55/60
Model trained in 1.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.479
  Epoch 56/60
Model trained in 1.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.674
  Epoch 57/60
Model trained in 1.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.437
  Epoch 58/60
Model trained in 1.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.406
  Epoch 59/60
Model trained in 1.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.124
  Epoch 60/60
Model trained in 1.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.091
  Early stopping triggered.

  best_val_SMAPE=73.627

Combination 1085/1152: {'encoder_hidden_size': 48, 'encoder_layers': 2, 'encoder_dropout': 0.2, 'decoder_hidden_size': 28, 'decoder_layers': 2, 'decoder_dropout': 0.2, 'learning_rate': 0.0005, 'max_epochs': 60, 'patience': 20, 'batch_size': 32, 'sequence_length': 24}
Time: 507.71 minutes - estimated total time: 539.06 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 3.08s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 180.834
  Epoch 2/60
Model trained in 3.10s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 171.995
  Epoch 3/60
Model trained in 3.01s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 164.487
  Epoch 4/60
Model trained in 3.06s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 157.836
  Epoch 5/60
Model trained in 3.08s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 151.856
  Epoch 6/60
Model trained in 2.99s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 146.384
  Epoch 7/60
Model trained in 2.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 141.280
  Epoch 8/60
Model trained in 3.01s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 136.506
  Epoch 9/60
Model trained in 3.15s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 131.939
  Epoch 10/60
Model trained in 3.06s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 127.529
  Epoch 11/60
Model trained in 3.04s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 123.299
  Epoch 12/60
Model trained in 3.13s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 120.010
  Epoch 13/60
Model trained in 3.03s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 116.478
  Epoch 14/60
Model trained in 3.13s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 113.461
  Epoch 15/60
Model trained in 2.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 109.419
  Epoch 16/60
Model trained in 2.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 106.574
  Epoch 17/60
Model trained in 2.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 104.350
  Epoch 18/60
Model trained in 2.95s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 101.853
  Epoch 19/60
Model trained in 3.05s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 100.065
  Epoch 20/60
Model trained in 3.10s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 97.543
  Epoch 21/60
Model trained in 3.07s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 94.990
  Epoch 22/60
Model trained in 3.08s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.848
  Epoch 23/60
Model trained in 2.97s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.224
  Epoch 24/60
Model trained in 3.02s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.902
  Epoch 25/60
Model trained in 2.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.813
  Epoch 26/60
Model trained in 2.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.540
  Epoch 27/60
Model trained in 2.95s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.063
  Epoch 28/60
Model trained in 2.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.267
  Epoch 29/60
Model trained in 2.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.693
  Epoch 30/60
Model trained in 3.03s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.341
  Epoch 31/60
Model trained in 3.08s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.697
  Epoch 32/60
Model trained in 3.07s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.594
  Epoch 33/60
Model trained in 3.01s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.751
  Epoch 34/60
Model trained in 2.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.180
  Epoch 35/60
Model trained in 2.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 71.871
  Epoch 36/60
Model trained in 2.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 71.309
  Epoch 37/60
Model trained in 3.00s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 70.296
  Epoch 38/60
Model trained in 2.98s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 69.729
  Epoch 39/60
Model trained in 2.99s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 69.737
  Epoch 40/60
Model trained in 2.98s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 69.349
  Epoch 41/60
Model trained in 2.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 69.440
  Epoch 42/60
Model trained in 2.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 70.095
  Epoch 43/60
Model trained in 2.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 70.668
  Epoch 44/60
Model trained in 3.00s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 71.135
  Epoch 45/60
Model trained in 2.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 71.453
  Epoch 46/60
Model trained in 3.13s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 72.599
  Epoch 47/60
Model trained in 3.01s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 72.987
  Epoch 48/60
Model trained in 2.95s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 72.617
  Epoch 49/60
Model trained in 3.07s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 72.046
  Epoch 50/60
Model trained in 2.99s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 72.122
  Epoch 51/60
Model trained in 2.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 71.704
  Epoch 52/60
Model trained in 2.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 71.504
  Epoch 53/60
Model trained in 2.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 71.268
  Epoch 54/60
Model trained in 2.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 71.338
  Epoch 55/60
Model trained in 2.99s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 71.652
  Epoch 56/60
Model trained in 2.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 71.759
  Epoch 57/60
Model trained in 2.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 72.035
  Epoch 58/60
Model trained in 2.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 71.561
  Epoch 59/60
Model trained in 3.16s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 71.770
  Epoch 60/60
Model trained in 2.99s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 72.242
  Early stopping triggered.

  best_val_SMAPE=69.349

Combination 1086/1152: {'encoder_hidden_size': 48, 'encoder_layers': 2, 'encoder_dropout': 0.2, 'decoder_hidden_size': 28, 'decoder_layers': 2, 'decoder_dropout': 0.2, 'learning_rate': 0.0005, 'max_epochs': 60, 'patience': 20, 'batch_size': 32, 'sequence_length': 168}
Time: 511.15 minutes - estimated total time: 542.22 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 3.16s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 180.916
  Epoch 2/60
Model trained in 3.14s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 172.094
  Epoch 3/60
Model trained in 3.06s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 164.615
  Epoch 4/60
Model trained in 3.11s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 157.985
  Epoch 5/60
Model trained in 3.11s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 152.024
  Epoch 6/60
Model trained in 3.10s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 146.571
  Epoch 7/60
Model trained in 3.06s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 141.480
  Epoch 8/60
Model trained in 3.09s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 136.722
  Epoch 9/60
Model trained in 3.03s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 132.175
  Epoch 10/60
Model trained in 3.16s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 127.773
  Epoch 11/60
Model trained in 3.17s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 123.556
  Epoch 12/60
Model trained in 2.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 121.302
  Epoch 13/60
Model trained in 2.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 117.716
  Epoch 14/60
Model trained in 3.06s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 114.823
  Epoch 15/60
Model trained in 2.95s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 111.881
  Epoch 16/60
Model trained in 3.04s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 108.999
  Epoch 17/60
Model trained in 3.08s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 106.226
  Epoch 18/60
Model trained in 2.98s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 103.104
  Epoch 19/60
Model trained in 2.98s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 100.424
  Epoch 20/60
Model trained in 3.03s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 97.778
  Epoch 21/60
Model trained in 3.00s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 95.503
  Epoch 22/60
Model trained in 3.03s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.572
  Epoch 23/60
Model trained in 3.04s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.651
  Epoch 24/60
Model trained in 3.04s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.947
  Epoch 25/60
Model trained in 2.95s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.076
  Epoch 26/60
Model trained in 3.05s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.762
  Epoch 27/60
Model trained in 3.00s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.745
  Epoch 28/60
Model trained in 3.10s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.754
  Epoch 29/60
Model trained in 3.16s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.565
  Epoch 30/60
Model trained in 3.10s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.711
  Epoch 31/60
Model trained in 3.08s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.207
  Epoch 32/60
Model trained in 3.21s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.535
  Epoch 33/60
Model trained in 3.14s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.785
  Epoch 34/60
Model trained in 2.98s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.262
  Epoch 35/60
Model trained in 3.11s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.958
  Epoch 36/60
Model trained in 3.04s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.742
  Epoch 37/60
Model trained in 3.02s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.842
  Epoch 38/60
Model trained in 3.13s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.020
  Epoch 39/60
Model trained in 3.02s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.295
  Epoch 40/60
Model trained in 2.99s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.211
  Epoch 41/60
Model trained in 3.11s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.242
  Epoch 42/60
Model trained in 2.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.344
  Epoch 43/60
Model trained in 2.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.470
  Epoch 44/60
Model trained in 3.11s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.522
  Epoch 45/60
Model trained in 3.03s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.813
  Epoch 46/60
Model trained in 2.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.125
  Epoch 47/60
Model trained in 2.97s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.696
  Epoch 48/60
Model trained in 3.03s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.964
  Epoch 49/60
Model trained in 2.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.377
  Epoch 50/60
Model trained in 3.03s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.743
  Epoch 51/60
Model trained in 2.99s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.629
  Epoch 52/60
Model trained in 2.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.471
  Epoch 53/60
Model trained in 3.06s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.891
  Epoch 54/60
Model trained in 3.02s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.773
  Early stopping triggered.

  best_val_SMAPE=81.262

Combination 1087/1152: {'encoder_hidden_size': 48, 'encoder_layers': 2, 'encoder_dropout': 0.2, 'decoder_hidden_size': 28, 'decoder_layers': 2, 'decoder_dropout': 0.2, 'learning_rate': 0.0005, 'max_epochs': 60, 'patience': 20, 'batch_size': 64, 'sequence_length': 24}
Time: 514.32 minutes - estimated total time: 545.07 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 1.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 186.761
  Epoch 2/60
Model trained in 1.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 180.788
  Epoch 3/60
Model trained in 1.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 176.123
  Epoch 4/60
Model trained in 1.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 171.911
  Epoch 5/60
Model trained in 1.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 168.018
  Epoch 6/60
Model trained in 1.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 164.371
  Epoch 7/60
Model trained in 1.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 160.915
  Epoch 8/60
Model trained in 1.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 157.695
  Epoch 9/60
Model trained in 1.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 154.608
  Epoch 10/60
Model trained in 1.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 151.690
  Epoch 11/60
Model trained in 1.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 148.895
  Epoch 12/60
Model trained in 1.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 146.196
  Epoch 13/60
Model trained in 1.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 143.579
  Epoch 14/60
Model trained in 1.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 141.074
  Epoch 15/60
Model trained in 1.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 138.638
  Epoch 16/60
Model trained in 1.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 136.280
  Epoch 17/60
Model trained in 1.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 133.969
  Epoch 18/60
Model trained in 1.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 131.736
  Epoch 19/60
Model trained in 1.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 129.610
  Epoch 20/60
Model trained in 1.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 128.893
  Epoch 21/60
Model trained in 1.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 127.036
  Epoch 22/60
Model trained in 1.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 124.319
  Epoch 23/60
Model trained in 1.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 121.916
  Epoch 24/60
Model trained in 1.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 120.061
  Epoch 25/60
Model trained in 1.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 117.912
  Epoch 26/60
Model trained in 1.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 116.179
  Epoch 27/60
Model trained in 1.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 114.456
  Epoch 28/60
Model trained in 1.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 112.748
  Epoch 29/60
Model trained in 1.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 111.526
  Epoch 30/60
Model trained in 1.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 109.954
  Epoch 31/60
Model trained in 1.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 108.191
  Epoch 32/60
Model trained in 1.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 106.806
  Epoch 33/60
Model trained in 1.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 104.868
  Epoch 34/60
Model trained in 1.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 103.278
  Epoch 35/60
Model trained in 1.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 102.260
  Epoch 36/60
Model trained in 1.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 101.700
  Epoch 37/60
Model trained in 1.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 100.420
  Epoch 38/60
Model trained in 1.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 99.453
  Epoch 39/60
Model trained in 1.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 97.347
  Epoch 40/60
Model trained in 1.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 95.717
  Epoch 41/60
Model trained in 1.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 96.040
  Epoch 42/60
Model trained in 1.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.525
  Epoch 43/60
Model trained in 1.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.597
  Epoch 44/60
Model trained in 1.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.372
  Epoch 45/60
Model trained in 1.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.596
  Epoch 46/60
Model trained in 1.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.586
  Epoch 47/60
Model trained in 1.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.357
  Epoch 48/60
Model trained in 1.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.243
  Epoch 49/60
Model trained in 1.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.184
  Epoch 50/60
Model trained in 1.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.337
  Epoch 51/60
Model trained in 1.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.047
  Epoch 52/60
Model trained in 1.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.771
  Epoch 53/60
Model trained in 1.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.426
  Epoch 54/60
Model trained in 1.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.610
  Epoch 55/60
Model trained in 1.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.930
  Epoch 56/60
Model trained in 1.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.207
  Epoch 57/60
Model trained in 1.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.780
  Epoch 58/60
Model trained in 1.68s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.871
  Epoch 59/60
Model trained in 1.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.176
  Epoch 60/60
Model trained in 1.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.609

  best_val_SMAPE=82.609

Combination 1088/1152: {'encoder_hidden_size': 48, 'encoder_layers': 2, 'encoder_dropout': 0.2, 'decoder_hidden_size': 28, 'decoder_layers': 2, 'decoder_dropout': 0.2, 'learning_rate': 0.0005, 'max_epochs': 60, 'patience': 20, 'batch_size': 64, 'sequence_length': 168}
Time: 516.57 minutes - estimated total time: 546.96 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 1.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 186.805
  Epoch 2/60
Model trained in 1.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 180.851
  Epoch 3/60
Model trained in 1.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 176.206
  Epoch 4/60
Model trained in 1.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 172.013
  Epoch 5/60
Model trained in 1.98s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 168.141
  Epoch 6/60
Model trained in 1.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 164.508
  Epoch 7/60
Model trained in 1.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 161.070
  Epoch 8/60
Model trained in 1.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 157.858
  Epoch 9/60
Model trained in 1.98s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 154.786
  Epoch 10/60
Model trained in 1.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 151.877
  Epoch 11/60
Model trained in 1.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 149.093
  Epoch 12/60
Model trained in 1.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 146.405
  Epoch 13/60
Model trained in 1.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 143.798
  Epoch 14/60
Model trained in 1.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 141.300
  Epoch 15/60
Model trained in 2.05s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 138.875
  Epoch 16/60
Model trained in 1.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 136.526
  Epoch 17/60
Model trained in 1.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 134.225
  Epoch 18/60
Model trained in 1.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 131.959
  Epoch 19/60
Model trained in 1.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 129.727
  Epoch 20/60
Model trained in 1.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 127.541
  Epoch 21/60
Model trained in 1.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 125.408
  Epoch 22/60
Model trained in 1.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 123.307
  Epoch 23/60
Model trained in 1.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 124.329
  Epoch 24/60
Model trained in 1.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 122.589
  Epoch 25/60
Model trained in 1.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 121.199
  Epoch 26/60
Model trained in 1.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 118.972
  Epoch 27/60
Model trained in 1.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 117.261
  Epoch 28/60
Model trained in 1.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 115.700
  Epoch 29/60
Model trained in 1.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 113.881
  Epoch 30/60
Model trained in 1.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 111.383
  Epoch 31/60
Model trained in 1.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 109.743
  Epoch 32/60
Model trained in 1.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 108.529
  Epoch 33/60
Model trained in 1.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 107.467
  Epoch 34/60
Model trained in 1.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 106.545
  Epoch 35/60
Model trained in 1.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 105.572
  Epoch 36/60
Model trained in 1.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 104.927
  Epoch 37/60
Model trained in 1.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 104.633
  Epoch 38/60
Model trained in 1.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 103.167
  Epoch 39/60
Model trained in 1.95s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 102.818
  Epoch 40/60
Model trained in 1.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 102.387
  Epoch 41/60
Model trained in 2.01s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 102.787
  Epoch 42/60
Model trained in 1.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 102.056
  Epoch 43/60
Model trained in 1.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 101.362
  Epoch 44/60
Model trained in 1.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 100.458
  Epoch 45/60
Model trained in 1.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 98.949
  Epoch 46/60
Model trained in 1.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 97.687
  Epoch 47/60
Model trained in 1.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 96.712
  Epoch 48/60
Model trained in 1.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 95.621
  Epoch 49/60
Model trained in 1.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 95.647
  Epoch 50/60
Model trained in 1.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 96.013
  Epoch 51/60
Model trained in 1.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 95.655
  Epoch 52/60
Model trained in 1.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 94.924
  Epoch 53/60
Model trained in 1.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 94.297
  Epoch 54/60
Model trained in 1.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.797
  Epoch 55/60
Model trained in 1.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.017
  Epoch 56/60
Model trained in 1.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.048
  Epoch 57/60
Model trained in 1.99s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.198
  Epoch 58/60
Model trained in 1.97s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.596
  Epoch 59/60
Model trained in 1.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.623
  Epoch 60/60
Model trained in 1.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.675

  best_val_SMAPE=88.675

Combination 1089/1152: {'encoder_hidden_size': 48, 'encoder_layers': 2, 'encoder_dropout': 0.2, 'decoder_hidden_size': 33, 'decoder_layers': 1, 'decoder_dropout': 0.0, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 20, 'batch_size': 32, 'sequence_length': 24}
Time: 518.95 minutes - estimated total time: 548.97 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 2.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 168.310
  Epoch 2/60
Model trained in 2.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 152.792
  Epoch 3/60
Model trained in 2.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 140.680
  Epoch 4/60
Model trained in 2.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 130.633
  Epoch 5/60
Model trained in 2.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 121.423
  Epoch 6/60
Model trained in 2.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 113.581
  Epoch 7/60
Model trained in 2.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 106.240
  Epoch 8/60
Model trained in 2.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 99.377
  Epoch 9/60
Model trained in 2.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 95.364
  Epoch 10/60
Model trained in 2.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.185
  Epoch 11/60
Model trained in 2.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.057
  Epoch 12/60
Model trained in 2.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.268
  Epoch 13/60
Model trained in 2.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.198
  Epoch 14/60
Model trained in 2.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.876
  Epoch 15/60
Model trained in 2.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.129
  Epoch 16/60
Model trained in 2.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.805
  Epoch 17/60
Model trained in 2.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.498
  Epoch 18/60
Model trained in 2.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.964
  Epoch 19/60
Model trained in 2.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.230
  Epoch 20/60
Model trained in 2.65s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.955
  Epoch 21/60
Model trained in 2.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.755
  Epoch 22/60
Model trained in 2.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 99.479
  Epoch 23/60
Model trained in 2.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.627
  Epoch 24/60
Model trained in 2.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.857
  Epoch 25/60
Model trained in 2.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.835
  Epoch 26/60
Model trained in 2.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.839
  Epoch 27/60
Model trained in 2.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.378
  Epoch 28/60
Model trained in 2.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.074
  Epoch 29/60
Model trained in 2.67s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.318
  Epoch 30/60
Model trained in 2.67s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.478
  Epoch 31/60
Model trained in 2.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.413
  Epoch 32/60
Model trained in 2.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.195
  Epoch 33/60
Model trained in 2.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.511
  Epoch 34/60
Model trained in 2.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.231
  Epoch 35/60
Model trained in 2.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.921
  Epoch 36/60
Model trained in 2.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.475
  Epoch 37/60
Model trained in 2.65s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.960
  Epoch 38/60
Model trained in 2.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.507
  Epoch 39/60
Model trained in 2.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.887
  Epoch 40/60
Model trained in 2.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.917
  Epoch 41/60
Model trained in 2.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.419
  Epoch 42/60
Model trained in 2.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.659
  Epoch 43/60
Model trained in 2.68s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.134
  Epoch 44/60
Model trained in 2.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.831
  Epoch 45/60
Model trained in 2.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.992
  Epoch 46/60
Model trained in 2.68s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.879
  Epoch 47/60
Model trained in 2.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.334
  Epoch 48/60
Model trained in 2.68s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.754
  Epoch 49/60
Model trained in 2.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.616
  Epoch 50/60
Model trained in 2.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.355
  Epoch 51/60
Model trained in 2.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.543
  Epoch 52/60
Model trained in 3.00s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.329
  Epoch 53/60
Model trained in 2.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.700
  Epoch 54/60
Model trained in 2.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.552
  Epoch 55/60
Model trained in 2.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.163
  Epoch 56/60
Model trained in 2.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.448
  Epoch 57/60
Model trained in 2.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.820
  Epoch 58/60
Model trained in 2.68s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.801
  Epoch 59/60
Model trained in 2.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 95.304
  Early stopping triggered.

  best_val_SMAPE=83.887

Combination 1090/1152: {'encoder_hidden_size': 48, 'encoder_layers': 2, 'encoder_dropout': 0.2, 'decoder_hidden_size': 33, 'decoder_layers': 1, 'decoder_dropout': 0.0, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 20, 'batch_size': 32, 'sequence_length': 168}
Time: 522.14 minutes - estimated total time: 551.84 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 2.95s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 168.403
  Epoch 2/60
Model trained in 3.05s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 152.931
  Epoch 3/60
Model trained in 2.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 140.751
  Epoch 4/60
Model trained in 2.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 130.771
  Epoch 5/60
Model trained in 2.99s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 121.398
  Epoch 6/60
Model trained in 2.99s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 113.344
  Epoch 7/60
Model trained in 2.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 106.487
  Epoch 8/60
Model trained in 2.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 100.320
  Epoch 9/60
Model trained in 2.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 95.541
  Epoch 10/60
Model trained in 2.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.993
  Epoch 11/60
Model trained in 2.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.536
  Epoch 12/60
Model trained in 2.98s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.880
  Epoch 13/60
Model trained in 2.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.944
  Epoch 14/60
Model trained in 2.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.995
  Epoch 15/60
Model trained in 2.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.227
  Epoch 16/60
Model trained in 2.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.610
  Epoch 17/60
Model trained in 2.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.635
  Epoch 18/60
Model trained in 2.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.898
  Epoch 19/60
Model trained in 2.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.378
  Epoch 20/60
Model trained in 2.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.473
  Epoch 21/60
Model trained in 2.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.339
  Epoch 22/60
Model trained in 2.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.426
  Epoch 23/60
Model trained in 2.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.156
  Epoch 24/60
Model trained in 2.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 107.716
  Epoch 25/60
Model trained in 2.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.484
  Epoch 26/60
Model trained in 2.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.185
  Epoch 27/60
Model trained in 2.67s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.352
  Epoch 28/60
Model trained in 2.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.503
  Epoch 29/60
Model trained in 2.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.848
  Epoch 30/60
Model trained in 2.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 102.664
  Epoch 31/60
Model trained in 2.95s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 101.028
  Epoch 32/60
Model trained in 2.99s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 101.766
  Epoch 33/60
Model trained in 2.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.516
  Epoch 34/60
Model trained in 2.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 102.750
  Epoch 35/60
Model trained in 3.01s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 102.807
  Early stopping triggered.

  best_val_SMAPE=79.227

Combination 1091/1152: {'encoder_hidden_size': 48, 'encoder_layers': 2, 'encoder_dropout': 0.2, 'decoder_hidden_size': 33, 'decoder_layers': 1, 'decoder_dropout': 0.0, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 20, 'batch_size': 64, 'sequence_length': 24}
Time: 524.10 minutes - estimated total time: 553.40 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 1.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 178.210
  Epoch 2/60
Model trained in 1.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 168.153
  Epoch 3/60
Model trained in 1.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 159.768
  Epoch 4/60
Model trained in 1.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 152.589
  Epoch 5/60
Model trained in 1.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 146.236
  Epoch 6/60
Model trained in 1.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 140.445
  Epoch 7/60
Model trained in 1.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 135.087
  Epoch 8/60
Model trained in 1.62s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 130.128
  Epoch 9/60
Model trained in 1.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 125.032
  Epoch 10/60
Model trained in 1.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 120.371
  Epoch 11/60
Model trained in 1.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 116.938
  Epoch 12/60
Model trained in 1.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 114.896
  Epoch 13/60
Model trained in 1.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 111.090
  Epoch 14/60
Model trained in 1.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 108.724
  Epoch 15/60
Model trained in 1.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 105.976
  Epoch 16/60
Model trained in 1.68s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 103.656
  Epoch 17/60
Model trained in 1.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 101.968
  Epoch 18/60
Model trained in 1.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 100.927
  Epoch 19/60
Model trained in 1.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 94.914
  Epoch 20/60
Model trained in 1.68s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 94.826
  Epoch 21/60
Model trained in 1.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.317
  Epoch 22/60
Model trained in 1.63s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.121
  Epoch 23/60
Model trained in 1.63s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.358
  Epoch 24/60
Model trained in 1.67s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.957
  Epoch 25/60
Model trained in 1.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.715
  Epoch 26/60
Model trained in 1.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.372
  Epoch 27/60
Model trained in 1.67s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.195
  Epoch 28/60
Model trained in 1.65s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.434
  Epoch 29/60
Model trained in 1.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.766
  Epoch 30/60
Model trained in 1.65s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.975
  Epoch 31/60
Model trained in 1.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.111
  Epoch 32/60
Model trained in 1.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.173
  Epoch 33/60
Model trained in 1.63s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.545
  Epoch 34/60
Model trained in 1.65s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.351
  Epoch 35/60
Model trained in 1.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.020
  Epoch 36/60
Model trained in 1.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.887
  Epoch 37/60
Model trained in 1.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.990
  Epoch 38/60
Model trained in 1.63s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.215
  Epoch 39/60
Model trained in 1.65s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.454
  Epoch 40/60
Model trained in 1.62s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.308
  Epoch 41/60
Model trained in 1.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.799
  Epoch 42/60
Model trained in 1.61s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.470
  Epoch 43/60
Model trained in 1.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.408
  Epoch 44/60
Model trained in 1.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.966
  Epoch 45/60
Model trained in 1.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.258
  Epoch 46/60
Model trained in 1.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.217
  Epoch 47/60
Model trained in 1.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.132
  Epoch 48/60
Model trained in 1.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.509
  Epoch 49/60
Model trained in 1.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.212
  Epoch 50/60
Model trained in 1.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.075
  Epoch 51/60
Model trained in 1.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.207
  Epoch 52/60
Model trained in 1.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.815
  Epoch 53/60
Model trained in 1.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.259
  Epoch 54/60
Model trained in 1.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.546
  Early stopping triggered.

  best_val_SMAPE=75.351

Combination 1092/1152: {'encoder_hidden_size': 48, 'encoder_layers': 2, 'encoder_dropout': 0.2, 'decoder_hidden_size': 33, 'decoder_layers': 1, 'decoder_dropout': 0.0, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 20, 'batch_size': 64, 'sequence_length': 168}
Time: 526.05 minutes - estimated total time: 554.95 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 1.99s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 178.297
  Epoch 2/60
Model trained in 1.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 168.286
  Epoch 3/60
Model trained in 1.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 159.939
  Epoch 4/60
Model trained in 1.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 152.795
  Epoch 5/60
Model trained in 1.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 146.426
  Epoch 6/60
Model trained in 1.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 140.589
  Epoch 7/60
Model trained in 1.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 135.292
  Epoch 8/60
Model trained in 1.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 130.328
  Epoch 9/60
Model trained in 1.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 125.584
  Epoch 10/60
Model trained in 1.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 121.561
  Epoch 11/60
Model trained in 1.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 116.795
  Epoch 12/60
Model trained in 1.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 112.816
  Epoch 13/60
Model trained in 1.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 108.902
  Epoch 14/60
Model trained in 1.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 105.532
  Epoch 15/60
Model trained in 1.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 102.194
  Epoch 16/60
Model trained in 1.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 99.595
  Epoch 17/60
Model trained in 1.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 97.156
  Epoch 18/60
Model trained in 1.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 94.253
  Epoch 19/60
Model trained in 1.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.365
  Epoch 20/60
Model trained in 1.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.496
  Epoch 21/60
Model trained in 1.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.976
  Epoch 22/60
Model trained in 1.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.480
  Epoch 23/60
Model trained in 1.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.747
  Epoch 24/60
Model trained in 1.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.158
  Epoch 25/60
Model trained in 1.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.752
  Epoch 26/60
Model trained in 1.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.124
  Epoch 27/60
Model trained in 1.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.923
  Epoch 28/60
Model trained in 1.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.298
  Epoch 29/60
Model trained in 1.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.734
  Epoch 30/60
Model trained in 1.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.539
  Epoch 31/60
Model trained in 1.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.176
  Epoch 32/60
Model trained in 1.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.323
  Epoch 33/60
Model trained in 1.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.956
  Epoch 34/60
Model trained in 1.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.633
  Epoch 35/60
Model trained in 1.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.533
  Epoch 36/60
Model trained in 1.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.768
  Epoch 37/60
Model trained in 1.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.251
  Epoch 38/60
Model trained in 1.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.763
  Epoch 39/60
Model trained in 1.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.836
  Epoch 40/60
Model trained in 1.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.514
  Epoch 41/60
Model trained in 1.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.907
  Epoch 42/60
Model trained in 1.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.419
  Epoch 43/60
Model trained in 1.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.806
  Epoch 44/60
Model trained in 1.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.713
  Epoch 45/60
Model trained in 1.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.583
  Epoch 46/60
Model trained in 1.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.853
  Epoch 47/60
Model trained in 1.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.299
  Epoch 48/60
Model trained in 1.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.905
  Epoch 49/60
Model trained in 1.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.957
  Early stopping triggered.

  best_val_SMAPE=78.734

Combination 1093/1152: {'encoder_hidden_size': 48, 'encoder_layers': 2, 'encoder_dropout': 0.2, 'decoder_hidden_size': 33, 'decoder_layers': 1, 'decoder_dropout': 0.0, 'learning_rate': 0.0005, 'max_epochs': 60, 'patience': 20, 'batch_size': 32, 'sequence_length': 24}
Time: 527.90 minutes - estimated total time: 556.39 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 2.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 178.265
  Epoch 2/60
Model trained in 2.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 168.448
  Epoch 3/60
Model trained in 2.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 160.109
  Epoch 4/60
Model trained in 2.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 152.932
  Epoch 5/60
Model trained in 2.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 146.589
  Epoch 6/60
Model trained in 2.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 140.802
  Epoch 7/60
Model trained in 2.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 135.449
  Epoch 8/60
Model trained in 2.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 130.370
  Epoch 9/60
Model trained in 2.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 125.577
  Epoch 10/60
Model trained in 2.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 121.164
  Epoch 11/60
Model trained in 2.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 116.963
  Epoch 12/60
Model trained in 2.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 112.962
  Epoch 13/60
Model trained in 2.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 110.104
  Epoch 14/60
Model trained in 2.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 105.754
  Epoch 15/60
Model trained in 2.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 102.466
  Epoch 16/60
Model trained in 2.68s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 99.548
  Epoch 17/60
Model trained in 2.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 97.221
  Epoch 18/60
Model trained in 2.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 95.276
  Epoch 19/60
Model trained in 2.67s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.308
  Epoch 20/60
Model trained in 2.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.316
  Epoch 21/60
Model trained in 2.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.350
  Epoch 22/60
Model trained in 2.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.798
  Epoch 23/60
Model trained in 2.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.332
  Epoch 24/60
Model trained in 2.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.365
  Epoch 25/60
Model trained in 2.68s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.209
  Epoch 26/60
Model trained in 2.65s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.075
  Epoch 27/60
Model trained in 2.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.720
  Epoch 28/60
Model trained in 2.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.793
  Epoch 29/60
Model trained in 2.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.121
  Epoch 30/60
Model trained in 2.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.236
  Epoch 31/60
Model trained in 2.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.990
  Epoch 32/60
Model trained in 2.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.752
  Epoch 33/60
Model trained in 2.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.161
  Epoch 34/60
Model trained in 2.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.464
  Epoch 35/60
Model trained in 2.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.503
  Epoch 36/60
Model trained in 2.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.301
  Epoch 37/60
Model trained in 2.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.161
  Epoch 38/60
Model trained in 2.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.307
  Epoch 39/60
Model trained in 2.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.498
  Epoch 40/60
Model trained in 2.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.417
  Epoch 41/60
Model trained in 2.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.809
  Epoch 42/60
Model trained in 2.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.316
  Epoch 43/60
Model trained in 2.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.477
  Epoch 44/60
Model trained in 2.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.463
  Epoch 45/60
Model trained in 2.63s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.807
  Epoch 46/60
Model trained in 2.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.259
  Epoch 47/60
Model trained in 2.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.172
  Epoch 48/60
Model trained in 2.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.341
  Epoch 49/60
Model trained in 2.63s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.592
  Epoch 50/60
Model trained in 2.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.953
  Epoch 51/60
Model trained in 2.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 96.640
  Epoch 52/60
Model trained in 2.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 103.172
  Early stopping triggered.

  best_val_SMAPE=78.752

Combination 1094/1152: {'encoder_hidden_size': 48, 'encoder_layers': 2, 'encoder_dropout': 0.2, 'decoder_hidden_size': 33, 'decoder_layers': 1, 'decoder_dropout': 0.0, 'learning_rate': 0.0005, 'max_epochs': 60, 'patience': 20, 'batch_size': 32, 'sequence_length': 168}
Time: 530.70 minutes - estimated total time: 558.83 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 2.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 178.344
  Epoch 2/60
Model trained in 2.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 168.528
  Epoch 3/60
Model trained in 2.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 160.269
  Epoch 4/60
Model trained in 2.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 153.101
  Epoch 5/60
Model trained in 2.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 146.757
  Epoch 6/60
Model trained in 3.02s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 140.965
  Epoch 7/60
Model trained in 2.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 135.684
  Epoch 8/60
Model trained in 2.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 130.532
  Epoch 9/60
Model trained in 2.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 126.083
  Epoch 10/60
Model trained in 2.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 121.289
  Epoch 11/60
Model trained in 2.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 117.270
  Epoch 12/60
Model trained in 2.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 113.121
  Epoch 13/60
Model trained in 2.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 109.958
  Epoch 14/60
Model trained in 2.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 106.791
  Epoch 15/60
Model trained in 2.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 103.922
  Epoch 16/60
Model trained in 3.01s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 101.277
  Epoch 17/60
Model trained in 2.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 97.943
  Epoch 18/60
Model trained in 2.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 97.487
  Epoch 19/60
Model trained in 2.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 95.618
  Epoch 20/60
Model trained in 2.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.901
  Epoch 21/60
Model trained in 2.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.620
  Epoch 22/60
Model trained in 2.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.476
  Epoch 23/60
Model trained in 2.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.880
  Epoch 24/60
Model trained in 2.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.061
  Epoch 25/60
Model trained in 2.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.323
  Epoch 26/60
Model trained in 2.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.159
  Epoch 27/60
Model trained in 2.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.216
  Epoch 28/60
Model trained in 2.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.556
  Epoch 29/60
Model trained in 2.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.024
  Epoch 30/60
Model trained in 2.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.215
  Epoch 31/60
Model trained in 3.05s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.547
  Epoch 32/60
Model trained in 2.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.948
  Epoch 33/60
Model trained in 2.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.028
  Epoch 34/60
Model trained in 3.01s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.710
  Epoch 35/60
Model trained in 2.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.499
  Epoch 36/60
Model trained in 2.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.373
  Epoch 37/60
Model trained in 2.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.495
  Epoch 38/60
Model trained in 2.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.995
  Epoch 39/60
Model trained in 2.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.792
  Epoch 40/60
Model trained in 2.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.762
  Epoch 41/60
Model trained in 2.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.269
  Epoch 42/60
Model trained in 2.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.402
  Epoch 43/60
Model trained in 2.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.823
  Epoch 44/60
Model trained in 2.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.787
  Epoch 45/60
Model trained in 2.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.575
  Epoch 46/60
Model trained in 2.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.244
  Epoch 47/60
Model trained in 2.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.652
  Epoch 48/60
Model trained in 2.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.187
  Epoch 49/60
Model trained in 2.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.069
  Epoch 50/60
Model trained in 2.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.175
  Epoch 51/60
Model trained in 2.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.468
  Epoch 52/60
Model trained in 2.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.097
  Epoch 53/60
Model trained in 2.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.080
  Epoch 54/60
Model trained in 2.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.107
  Early stopping triggered.

  best_val_SMAPE=75.710

Combination 1095/1152: {'encoder_hidden_size': 48, 'encoder_layers': 2, 'encoder_dropout': 0.2, 'decoder_hidden_size': 33, 'decoder_layers': 1, 'decoder_dropout': 0.0, 'learning_rate': 0.0005, 'max_epochs': 60, 'patience': 20, 'batch_size': 64, 'sequence_length': 24}
Time: 533.68 minutes - estimated total time: 561.46 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 1.67s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 184.824
  Epoch 2/60
Model trained in 1.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 178.166
  Epoch 3/60
Model trained in 1.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 172.937
  Epoch 4/60
Model trained in 1.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 168.324
  Epoch 5/60
Model trained in 1.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 163.985
  Epoch 6/60
Model trained in 1.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 159.949
  Epoch 7/60
Model trained in 1.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 156.249
  Epoch 8/60
Model trained in 1.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 152.749
  Epoch 9/60
Model trained in 1.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 149.475
  Epoch 10/60
Model trained in 1.68s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 146.364
  Epoch 11/60
Model trained in 1.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 143.409
  Epoch 12/60
Model trained in 1.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 140.588
  Epoch 13/60
Model trained in 1.68s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 137.862
  Epoch 14/60
Model trained in 1.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 135.223
  Epoch 15/60
Model trained in 1.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 132.621
  Epoch 16/60
Model trained in 1.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 129.973
  Epoch 17/60
Model trained in 1.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 127.504
  Epoch 18/60
Model trained in 1.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 125.122
  Epoch 19/60
Model trained in 1.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 122.808
  Epoch 20/60
Model trained in 1.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 120.682
  Epoch 21/60
Model trained in 1.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 118.447
  Epoch 22/60
Model trained in 1.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 116.397
  Epoch 23/60
Model trained in 1.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 114.578
  Epoch 24/60
Model trained in 1.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 112.674
  Epoch 25/60
Model trained in 1.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 110.720
  Epoch 26/60
Model trained in 1.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 109.039
  Epoch 27/60
Model trained in 1.65s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 107.421
  Epoch 28/60
Model trained in 1.59s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 105.776
  Epoch 29/60
Model trained in 1.65s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 104.477
  Epoch 30/60
Model trained in 1.67s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 102.686
  Epoch 31/60
Model trained in 1.67s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 101.179
  Epoch 32/60
Model trained in 1.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 99.644
  Epoch 33/60
Model trained in 1.63s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 98.117
  Epoch 34/60
Model trained in 1.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 96.296
  Epoch 35/60
Model trained in 1.62s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 95.262
  Epoch 36/60
Model trained in 1.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 94.008
  Epoch 37/60
Model trained in 1.65s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.827
  Epoch 38/60
Model trained in 1.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.673
  Epoch 39/60
Model trained in 1.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.583
  Epoch 40/60
Model trained in 1.61s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.478
  Epoch 41/60
Model trained in 1.68s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.290
  Epoch 42/60
Model trained in 1.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.288
  Epoch 43/60
Model trained in 1.67s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.390
  Epoch 44/60
Model trained in 1.65s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.817
  Epoch 45/60
Model trained in 1.59s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.777
  Epoch 46/60
Model trained in 1.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.026
  Epoch 47/60
Model trained in 1.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.341
  Epoch 48/60
Model trained in 1.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.178
  Epoch 49/60
Model trained in 1.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.549
  Epoch 50/60
Model trained in 1.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.003
  Epoch 51/60
Model trained in 1.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.571
  Epoch 52/60
Model trained in 1.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.003
  Epoch 53/60
Model trained in 1.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.902
  Epoch 54/60
Model trained in 1.68s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.857
  Epoch 55/60
Model trained in 1.62s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.537
  Epoch 56/60
Model trained in 1.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.870
  Epoch 57/60
Model trained in 1.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.727
  Epoch 58/60
Model trained in 1.67s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.725
  Epoch 59/60
Model trained in 1.68s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.087
  Epoch 60/60
Model trained in 1.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.186

  best_val_SMAPE=78.087

Combination 1096/1152: {'encoder_hidden_size': 48, 'encoder_layers': 2, 'encoder_dropout': 0.2, 'decoder_hidden_size': 33, 'decoder_layers': 1, 'decoder_dropout': 0.0, 'learning_rate': 0.0005, 'max_epochs': 60, 'patience': 20, 'batch_size': 64, 'sequence_length': 168}
Time: 535.84 minutes - estimated total time: 563.22 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 1.98s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 184.878
  Epoch 2/60
Model trained in 1.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 178.237
  Epoch 3/60
Model trained in 1.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 173.031
  Epoch 4/60
Model trained in 1.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 168.392
  Epoch 5/60
Model trained in 1.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 164.120
  Epoch 6/60
Model trained in 1.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 160.114
  Epoch 7/60
Model trained in 1.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 156.423
  Epoch 8/60
Model trained in 1.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 152.931
  Epoch 9/60
Model trained in 1.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 149.630
  Epoch 10/60
Model trained in 1.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 146.539
  Epoch 11/60
Model trained in 1.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 143.558
  Epoch 12/60
Model trained in 1.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 140.764
  Epoch 13/60
Model trained in 1.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 138.059
  Epoch 14/60
Model trained in 1.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 135.427
  Epoch 15/60
Model trained in 1.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 132.846
  Epoch 16/60
Model trained in 1.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 130.237
  Epoch 17/60
Model trained in 1.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 127.862
  Epoch 18/60
Model trained in 1.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 125.412
  Epoch 19/60
Model trained in 1.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 123.106
  Epoch 20/60
Model trained in 1.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 120.951
  Epoch 21/60
Model trained in 1.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 118.812
  Epoch 22/60
Model trained in 1.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 116.761
  Epoch 23/60
Model trained in 1.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 114.757
  Epoch 24/60
Model trained in 1.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 112.831
  Epoch 25/60
Model trained in 1.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 111.024
  Epoch 26/60
Model trained in 1.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 109.357
  Epoch 27/60
Model trained in 1.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 107.927
  Epoch 28/60
Model trained in 1.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 106.547
  Epoch 29/60
Model trained in 1.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 104.909
  Epoch 30/60
Model trained in 1.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 103.544
  Epoch 31/60
Model trained in 1.68s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 102.019
  Epoch 32/60
Model trained in 1.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 100.588
  Epoch 33/60
Model trained in 1.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 100.060
  Epoch 34/60
Model trained in 1.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 98.799
  Epoch 35/60
Model trained in 1.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 98.537
  Epoch 36/60
Model trained in 1.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 96.552
  Epoch 37/60
Model trained in 1.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 95.591
  Epoch 38/60
Model trained in 1.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 94.674
  Epoch 39/60
Model trained in 1.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.794
  Epoch 40/60
Model trained in 1.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.771
  Epoch 41/60
Model trained in 1.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.820
  Epoch 42/60
Model trained in 1.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.469
  Epoch 43/60
Model trained in 1.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.401
  Epoch 44/60
Model trained in 1.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.952
  Epoch 45/60
Model trained in 1.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.314
  Epoch 46/60
Model trained in 1.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.734
  Epoch 47/60
Model trained in 1.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.809
  Epoch 48/60
Model trained in 1.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.294
  Epoch 49/60
Model trained in 1.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.378
  Epoch 50/60
Model trained in 1.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.038
  Epoch 51/60
Model trained in 1.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.693
  Epoch 52/60
Model trained in 1.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.182
  Epoch 53/60
Model trained in 1.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.889
  Epoch 54/60
Model trained in 1.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.998
  Epoch 55/60
Model trained in 1.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.037
  Epoch 56/60
Model trained in 1.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.531
  Epoch 57/60
Model trained in 1.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.384
  Epoch 58/60
Model trained in 1.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.507
  Epoch 59/60
Model trained in 1.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.100
  Epoch 60/60
Model trained in 1.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.242

  best_val_SMAPE=82.100

Combination 1105/1152: {'encoder_hidden_size': 48, 'encoder_layers': 2, 'encoder_dropout': 0.2, 'decoder_hidden_size': 33, 'decoder_layers': 2, 'decoder_dropout': 0.0, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 20, 'batch_size': 32, 'sequence_length': 24}
Time: 538.11 minutes - estimated total time: 561.00 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 3.05s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 169.040
  Epoch 2/60
Model trained in 2.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 153.337
  Epoch 3/60
Model trained in 2.95s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 140.882
  Epoch 4/60
Model trained in 2.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 130.134
  Epoch 5/60
Model trained in 3.03s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 120.367
  Epoch 6/60
Model trained in 2.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 114.235
  Epoch 7/60
Model trained in 2.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 108.806
  Epoch 8/60
Model trained in 2.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 101.735
  Epoch 9/60
Model trained in 3.03s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 96.875
  Epoch 10/60
Model trained in 3.02s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.912
  Epoch 11/60
Model trained in 2.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.106
  Epoch 12/60
Model trained in 3.01s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.739
  Epoch 13/60
Model trained in 2.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.692
  Epoch 14/60
Model trained in 3.04s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.301
  Epoch 15/60
Model trained in 3.05s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.629
  Epoch 16/60
Model trained in 3.01s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.706
  Epoch 17/60
Model trained in 2.98s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.608
  Epoch 18/60
Model trained in 2.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.512
  Epoch 19/60
Model trained in 2.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.349
  Epoch 20/60
Model trained in 2.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.575
  Epoch 21/60
Model trained in 2.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.958
  Epoch 22/60
Model trained in 3.01s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.431
  Epoch 23/60
Model trained in 2.99s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.821
  Epoch 24/60
Model trained in 3.02s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.514
  Epoch 25/60
Model trained in 3.11s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.111
  Epoch 26/60
Model trained in 2.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.674
  Epoch 27/60
Model trained in 2.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.634
  Epoch 28/60
Model trained in 2.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.788
  Epoch 29/60
Model trained in 2.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.352
  Epoch 30/60
Model trained in 2.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.614
  Epoch 31/60
Model trained in 3.12s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.786
  Epoch 32/60
Model trained in 2.99s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.683
  Epoch 33/60
Model trained in 3.09s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.861
  Epoch 34/60
Model trained in 3.08s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.731
  Epoch 35/60
Model trained in 3.06s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.175
  Epoch 36/60
Model trained in 2.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.941
  Epoch 37/60
Model trained in 2.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.111
  Epoch 38/60
Model trained in 2.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.204
  Epoch 39/60
Model trained in 3.04s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.720
  Epoch 40/60
Model trained in 3.05s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.764
  Early stopping triggered.

  best_val_SMAPE=78.575

Combination 1106/1152: {'encoder_hidden_size': 48, 'encoder_layers': 2, 'encoder_dropout': 0.2, 'decoder_hidden_size': 33, 'decoder_layers': 2, 'decoder_dropout': 0.0, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 20, 'batch_size': 32, 'sequence_length': 168}
Time: 540.41 minutes - estimated total time: 562.89 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 3.07s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 169.029
  Epoch 2/60
Model trained in 3.10s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 153.423
  Epoch 3/60
Model trained in 3.05s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 141.031
  Epoch 4/60
Model trained in 3.09s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 130.332
  Epoch 5/60
Model trained in 3.01s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 120.600
  Epoch 6/60
Model trained in 3.03s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 114.767
  Epoch 7/60
Model trained in 2.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 107.183
  Epoch 8/60
Model trained in 2.99s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 99.296
  Epoch 9/60
Model trained in 3.06s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.645
  Epoch 10/60
Model trained in 3.21s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.450
  Epoch 11/60
Model trained in 3.04s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.781
  Epoch 12/60
Model trained in 3.11s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.090
  Epoch 13/60
Model trained in 3.06s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.199
  Epoch 14/60
Model trained in 2.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.206
  Epoch 15/60
Model trained in 2.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.464
  Epoch 16/60
Model trained in 2.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.852
  Epoch 17/60
Model trained in 2.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.367
  Epoch 18/60
Model trained in 2.97s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.754
  Epoch 19/60
Model trained in 2.99s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.271
  Epoch 20/60
Model trained in 3.01s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.482
  Epoch 21/60
Model trained in 2.95s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.184
  Epoch 22/60
Model trained in 3.08s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.857
  Epoch 23/60
Model trained in 3.05s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.310
  Epoch 24/60
Model trained in 3.09s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.530
  Epoch 25/60
Model trained in 3.05s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.868
  Epoch 26/60
Model trained in 2.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.963
  Epoch 27/60
Model trained in 3.05s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.587
  Epoch 28/60
Model trained in 2.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.064
  Epoch 29/60
Model trained in 3.00s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.086
  Epoch 30/60
Model trained in 3.12s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.131
  Epoch 31/60
Model trained in 3.10s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.778
  Epoch 32/60
Model trained in 3.02s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.838
  Epoch 33/60
Model trained in 3.07s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.329
  Epoch 34/60
Model trained in 3.02s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.931
  Epoch 35/60
Model trained in 2.95s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.772
  Epoch 36/60
Model trained in 2.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.365
  Epoch 37/60
Model trained in 3.17s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.432
  Early stopping triggered.

  best_val_SMAPE=76.367

Combination 1107/1152: {'encoder_hidden_size': 48, 'encoder_layers': 2, 'encoder_dropout': 0.2, 'decoder_hidden_size': 33, 'decoder_layers': 2, 'decoder_dropout': 0.0, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 20, 'batch_size': 64, 'sequence_length': 24}
Time: 542.59 minutes - estimated total time: 564.65 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 1.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 178.840
  Epoch 2/60
Model trained in 1.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 168.840
  Epoch 3/60
Model trained in 1.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 160.403
  Epoch 4/60
Model trained in 1.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 153.120
  Epoch 5/60
Model trained in 1.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 146.606
  Epoch 6/60
Model trained in 1.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 140.636
  Epoch 7/60
Model trained in 1.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 135.112
  Epoch 8/60
Model trained in 1.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 129.846
  Epoch 9/60
Model trained in 1.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 124.825
  Epoch 10/60
Model trained in 1.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 121.166
  Epoch 11/60
Model trained in 1.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 118.291
  Epoch 12/60
Model trained in 1.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 114.271
  Epoch 13/60
Model trained in 1.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 110.089
  Epoch 14/60
Model trained in 1.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 106.291
  Epoch 15/60
Model trained in 1.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 103.240
  Epoch 16/60
Model trained in 1.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 99.746
  Epoch 17/60
Model trained in 1.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 96.648
  Epoch 18/60
Model trained in 1.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 94.151
  Epoch 19/60
Model trained in 1.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.817
  Epoch 20/60
Model trained in 1.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.467
  Epoch 21/60
Model trained in 1.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.034
  Epoch 22/60
Model trained in 1.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.521
  Epoch 23/60
Model trained in 1.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.863
  Epoch 24/60
Model trained in 1.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.021
  Epoch 25/60
Model trained in 1.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.363
  Epoch 26/60
Model trained in 1.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.836
  Epoch 27/60
Model trained in 1.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.416
  Epoch 28/60
Model trained in 1.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.795
  Epoch 29/60
Model trained in 1.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.226
  Epoch 30/60
Model trained in 1.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.104
  Epoch 31/60
Model trained in 1.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.818
  Epoch 32/60
Model trained in 1.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.155
  Epoch 33/60
Model trained in 1.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.940
  Epoch 34/60
Model trained in 1.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.666
  Epoch 35/60
Model trained in 1.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.078
  Epoch 36/60
Model trained in 1.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.520
  Epoch 37/60
Model trained in 1.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.219
  Epoch 38/60
Model trained in 1.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.415
  Epoch 39/60
Model trained in 1.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.821
  Epoch 40/60
Model trained in 1.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.352
  Epoch 41/60
Model trained in 1.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.526
  Epoch 42/60
Model trained in 1.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.818
  Epoch 43/60
Model trained in 1.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.154
  Epoch 44/60
Model trained in 1.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.589
  Epoch 45/60
Model trained in 1.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.565
  Epoch 46/60
Model trained in 1.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.433
  Epoch 47/60
Model trained in 1.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.654
  Epoch 48/60
Model trained in 1.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.371
  Epoch 49/60
Model trained in 1.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.698
  Epoch 50/60
Model trained in 1.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.563
  Epoch 51/60
Model trained in 1.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.056
  Epoch 52/60
Model trained in 1.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.181
  Epoch 53/60
Model trained in 1.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.779
  Epoch 54/60
Model trained in 1.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.849
  Early stopping triggered.

  best_val_SMAPE=73.666

Combination 1108/1152: {'encoder_hidden_size': 48, 'encoder_layers': 2, 'encoder_dropout': 0.2, 'decoder_hidden_size': 33, 'decoder_layers': 2, 'decoder_dropout': 0.0, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 20, 'batch_size': 64, 'sequence_length': 168}
Time: 544.64 minutes - estimated total time: 566.27 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 1.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 178.887
  Epoch 2/60
Model trained in 1.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 168.949
  Epoch 3/60
Model trained in 1.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 160.564
  Epoch 4/60
Model trained in 1.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 153.311
  Epoch 5/60
Model trained in 1.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 146.827
  Epoch 6/60
Model trained in 1.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 140.878
  Epoch 7/60
Model trained in 1.95s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 135.377
  Epoch 8/60
Model trained in 1.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 130.137
  Epoch 9/60
Model trained in 1.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 125.136
  Epoch 10/60
Model trained in 1.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 120.377
  Epoch 11/60
Model trained in 1.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 118.264
  Epoch 12/60
Model trained in 1.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 114.090
  Epoch 13/60
Model trained in 1.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 110.432
  Epoch 14/60
Model trained in 2.00s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 107.125
  Epoch 15/60
Model trained in 1.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 103.939
  Epoch 16/60
Model trained in 1.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 99.737
  Epoch 17/60
Model trained in 1.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 96.233
  Epoch 18/60
Model trained in 1.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.197
  Epoch 19/60
Model trained in 1.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.230
  Epoch 20/60
Model trained in 1.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.385
  Epoch 21/60
Model trained in 1.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.730
  Epoch 22/60
Model trained in 1.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.982
  Epoch 23/60
Model trained in 1.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.605
  Epoch 24/60
Model trained in 1.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.064
  Epoch 25/60
Model trained in 1.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.670
  Epoch 26/60
Model trained in 1.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.297
  Epoch 27/60
Model trained in 1.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.728
  Epoch 28/60
Model trained in 1.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.373
  Epoch 29/60
Model trained in 1.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.378
  Epoch 30/60
Model trained in 1.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.115
  Epoch 31/60
Model trained in 1.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.050
  Epoch 32/60
Model trained in 1.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.656
  Epoch 33/60
Model trained in 1.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.716
  Epoch 34/60
Model trained in 1.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.473
  Epoch 35/60
Model trained in 2.05s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.908
  Epoch 36/60
Model trained in 1.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.648
  Epoch 37/60
Model trained in 1.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.024
  Epoch 38/60
Model trained in 1.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.144
  Epoch 39/60
Model trained in 1.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.884
  Epoch 40/60
Model trained in 1.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.008
  Epoch 41/60
Model trained in 1.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.020
  Epoch 42/60
Model trained in 1.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.113
  Epoch 43/60
Model trained in 1.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.562
  Epoch 44/60
Model trained in 1.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.898
  Epoch 45/60
Model trained in 1.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.009
  Epoch 46/60
Model trained in 1.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.092
  Epoch 47/60
Model trained in 1.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.456
  Epoch 48/60
Model trained in 1.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.359
  Epoch 49/60
Model trained in 1.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.514
  Epoch 50/60
Model trained in 1.95s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.197
  Epoch 51/60
Model trained in 1.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.009
  Epoch 52/60
Model trained in 1.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.804
  Epoch 53/60
Model trained in 1.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.466
  Epoch 54/60
Model trained in 1.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.518
  Epoch 55/60
Model trained in 1.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.354
  Epoch 56/60
Model trained in 1.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.505
  Epoch 57/60
Model trained in 1.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.816
  Epoch 58/60
Model trained in 1.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.679
  Epoch 59/60
Model trained in 1.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.404
  Epoch 60/60
Model trained in 1.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.687

  best_val_SMAPE=78.113

Combination 1109/1152: {'encoder_hidden_size': 48, 'encoder_layers': 2, 'encoder_dropout': 0.2, 'decoder_hidden_size': 33, 'decoder_layers': 2, 'decoder_dropout': 0.0, 'learning_rate': 0.0005, 'max_epochs': 60, 'patience': 20, 'batch_size': 32, 'sequence_length': 24}
Time: 546.99 minutes - estimated total time: 568.20 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 2.99s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 178.861
  Epoch 2/60
Model trained in 3.03s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 169.014
  Epoch 3/60
Model trained in 3.03s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 160.657
  Epoch 4/60
Model trained in 2.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 153.401
  Epoch 5/60
Model trained in 2.98s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 146.898
  Epoch 6/60
Model trained in 2.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 140.917
  Epoch 7/60
Model trained in 2.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 135.376
  Epoch 8/60
Model trained in 2.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 130.088
  Epoch 9/60
Model trained in 3.06s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 125.035
  Epoch 10/60
Model trained in 2.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 122.593
  Epoch 11/60
Model trained in 2.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 119.454
  Epoch 12/60
Model trained in 2.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 115.650
  Epoch 13/60
Model trained in 2.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 112.611
  Epoch 14/60
Model trained in 2.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 109.654
  Epoch 15/60
Model trained in 2.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 106.312
  Epoch 16/60
Model trained in 2.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 103.352
  Epoch 17/60
Model trained in 2.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 99.665
  Epoch 18/60
Model trained in 2.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 96.939
  Epoch 19/60
Model trained in 3.00s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 95.358
  Epoch 20/60
Model trained in 2.98s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.541
  Epoch 21/60
Model trained in 3.00s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.840
  Epoch 22/60
Model trained in 3.01s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.666
  Epoch 23/60
Model trained in 2.97s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.640
  Epoch 24/60
Model trained in 2.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.444
  Epoch 25/60
Model trained in 2.97s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.112
  Epoch 26/60
Model trained in 2.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.674
  Epoch 27/60
Model trained in 2.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.573
  Epoch 28/60
Model trained in 3.02s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.726
  Epoch 29/60
Model trained in 2.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.869
  Epoch 30/60
Model trained in 2.97s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.574
  Epoch 31/60
Model trained in 3.04s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.467
  Epoch 32/60
Model trained in 2.99s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.713
  Epoch 33/60
Model trained in 3.00s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.180
  Epoch 34/60
Model trained in 2.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.029
  Epoch 35/60
Model trained in 2.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.744
  Epoch 36/60
Model trained in 2.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.235
  Epoch 37/60
Model trained in 3.01s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.948
  Epoch 38/60
Model trained in 3.04s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.090
  Epoch 39/60
Model trained in 2.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.961
  Epoch 40/60
Model trained in 2.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.906
  Epoch 41/60
Model trained in 2.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.766
  Epoch 42/60
Model trained in 2.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.252
  Epoch 43/60
Model trained in 2.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.631
  Epoch 44/60
Model trained in 2.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.628
  Epoch 45/60
Model trained in 2.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.516
  Epoch 46/60
Model trained in 2.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.198
  Epoch 47/60
Model trained in 2.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.861
  Epoch 48/60
Model trained in 2.98s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.575
  Epoch 49/60
Model trained in 2.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.483
  Epoch 50/60
Model trained in 3.04s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.951
  Epoch 51/60
Model trained in 2.99s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.981
  Epoch 52/60
Model trained in 2.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.527
  Epoch 53/60
Model trained in 2.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.439
  Epoch 54/60
Model trained in 2.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.897
  Epoch 55/60
Model trained in 2.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.000
  Epoch 56/60
Model trained in 2.98s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.746
  Epoch 57/60
Model trained in 2.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.110
  Epoch 58/60
Model trained in 2.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.455
  Epoch 59/60
Model trained in 2.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.717
  Epoch 60/60
Model trained in 2.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.948

  best_val_SMAPE=74.951

Combination 1110/1152: {'encoder_hidden_size': 48, 'encoder_layers': 2, 'encoder_dropout': 0.2, 'decoder_hidden_size': 33, 'decoder_layers': 2, 'decoder_dropout': 0.0, 'learning_rate': 0.0005, 'max_epochs': 60, 'patience': 20, 'batch_size': 32, 'sequence_length': 168}
Time: 550.39 minutes - estimated total time: 571.22 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 3.16s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 178.889
  Epoch 2/60
Model trained in 3.12s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 169.107
  Epoch 3/60
Model trained in 3.14s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 160.792
  Epoch 4/60
Model trained in 3.04s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 153.560
  Epoch 5/60
Model trained in 3.29s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 147.082
  Epoch 6/60
Model trained in 3.07s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 141.119
  Epoch 7/60
Model trained in 2.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 135.597
  Epoch 8/60
Model trained in 2.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 131.497
  Epoch 9/60
Model trained in 3.27s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 126.480
  Epoch 10/60
Model trained in 3.34s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 121.574
  Epoch 11/60
Model trained in 3.05s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 116.662
  Epoch 12/60
Model trained in 2.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 112.393
  Epoch 13/60
Model trained in 3.02s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 108.346
  Epoch 14/60
Model trained in 2.97s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 104.998
  Epoch 15/60
Model trained in 2.97s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 101.764
  Epoch 16/60
Model trained in 2.99s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 98.609
  Epoch 17/60
Model trained in 3.05s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 95.953
  Epoch 18/60
Model trained in 3.13s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.503
  Epoch 19/60
Model trained in 3.28s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.425
  Epoch 20/60
Model trained in 3.32s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.712
  Epoch 21/60
Model trained in 3.27s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.596
  Epoch 22/60
Model trained in 3.22s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.094
  Epoch 23/60
Model trained in 3.25s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.272
  Epoch 24/60
Model trained in 2.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.031
  Epoch 25/60
Model trained in 2.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.535
  Epoch 26/60
Model trained in 3.22s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.054
  Epoch 27/60
Model trained in 3.31s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.073
  Epoch 28/60
Model trained in 3.04s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.143
  Epoch 29/60
Model trained in 3.11s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.695
  Epoch 30/60
Model trained in 3.06s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.163
  Epoch 31/60
Model trained in 3.07s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.253
  Epoch 32/60
Model trained in 3.04s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.574
  Epoch 33/60
Model trained in 3.20s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.064
  Epoch 34/60
Model trained in 3.05s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 72.753
  Epoch 35/60
Model trained in 3.03s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 72.209
  Epoch 36/60
Model trained in 3.03s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 71.795
  Epoch 37/60
Model trained in 3.11s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 71.778
  Epoch 38/60
Model trained in 3.05s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 71.483
  Epoch 39/60
Model trained in 3.09s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 71.004
  Epoch 40/60
Model trained in 3.06s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 70.386
  Epoch 41/60
Model trained in 3.10s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 70.299
  Epoch 42/60
Model trained in 3.35s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 70.728
  Epoch 43/60
Model trained in 3.28s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 70.664
  Epoch 44/60
Model trained in 3.36s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 70.440
  Epoch 45/60
Model trained in 3.19s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 70.145
  Epoch 46/60
Model trained in 3.03s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 70.238
  Epoch 47/60
Model trained in 3.03s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 69.581
  Epoch 48/60
Model trained in 2.99s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 70.089
  Epoch 49/60
Model trained in 3.16s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 69.632
  Epoch 50/60
Model trained in 2.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 69.528
  Epoch 51/60
Model trained in 3.02s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 70.284
  Epoch 52/60
Model trained in 3.25s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 70.496
  Epoch 53/60
Model trained in 3.19s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 70.701
  Epoch 54/60
Model trained in 3.24s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 71.123
  Epoch 55/60
Model trained in 3.15s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 71.516
  Epoch 56/60
Model trained in 3.23s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 71.368
  Epoch 57/60
Model trained in 3.20s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 70.989
  Epoch 58/60
Model trained in 2.99s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 70.477
  Epoch 59/60
Model trained in 2.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 70.548
  Epoch 60/60
Model trained in 3.02s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 69.456

  best_val_SMAPE=69.456

Combination 1111/1152: {'encoder_hidden_size': 48, 'encoder_layers': 2, 'encoder_dropout': 0.2, 'decoder_hidden_size': 33, 'decoder_layers': 2, 'decoder_dropout': 0.0, 'learning_rate': 0.0005, 'max_epochs': 60, 'patience': 20, 'batch_size': 64, 'sequence_length': 24}
Time: 553.99 minutes - estimated total time: 574.43 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 1.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 185.275
  Epoch 2/60
Model trained in 1.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 178.755
  Epoch 3/60
Model trained in 1.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 173.553
  Epoch 4/60
Model trained in 1.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 168.887
  Epoch 5/60
Model trained in 1.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 164.552
  Epoch 6/60
Model trained in 1.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 160.503
  Epoch 7/60
Model trained in 1.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 156.775
  Epoch 8/60
Model trained in 1.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 153.227
  Epoch 9/60
Model trained in 1.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 149.891
  Epoch 10/60
Model trained in 1.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 146.699
  Epoch 11/60
Model trained in 1.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 143.624
  Epoch 12/60
Model trained in 1.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 140.698
  Epoch 13/60
Model trained in 1.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 137.865
  Epoch 14/60
Model trained in 1.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 135.133
  Epoch 15/60
Model trained in 1.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 132.451
  Epoch 16/60
Model trained in 1.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 128.547
  Epoch 17/60
Model trained in 1.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 126.017
  Epoch 18/60
Model trained in 1.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 125.810
  Epoch 19/60
Model trained in 1.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 123.425
  Epoch 20/60
Model trained in 1.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 122.801
  Epoch 21/60
Model trained in 1.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 123.654
  Epoch 22/60
Model trained in 1.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 122.372
  Epoch 23/60
Model trained in 1.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 119.385
  Epoch 24/60
Model trained in 1.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 117.741
  Epoch 25/60
Model trained in 1.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 115.373
  Epoch 26/60
Model trained in 1.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 112.907
  Epoch 27/60
Model trained in 1.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 110.536
  Epoch 28/60
Model trained in 1.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 108.718
  Epoch 29/60
Model trained in 1.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 106.417
  Epoch 30/60
Model trained in 1.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 104.867
  Epoch 31/60
Model trained in 1.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 103.056
  Epoch 32/60
Model trained in 1.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 100.619
  Epoch 33/60
Model trained in 1.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 99.415
  Epoch 34/60
Model trained in 1.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 97.765
  Epoch 35/60
Model trained in 1.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 96.341
  Epoch 36/60
Model trained in 1.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 95.436
  Epoch 37/60
Model trained in 1.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 95.013
  Epoch 38/60
Model trained in 1.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 94.023
  Epoch 39/60
Model trained in 1.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.888
  Epoch 40/60
Model trained in 1.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.962
  Epoch 41/60
Model trained in 1.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.883
  Epoch 42/60
Model trained in 1.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.693
  Epoch 43/60
Model trained in 1.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.188
  Epoch 44/60
Model trained in 1.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.075
  Epoch 45/60
Model trained in 1.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.277
  Epoch 46/60
Model trained in 1.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.521
  Epoch 47/60
Model trained in 1.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.336
  Epoch 48/60
Model trained in 1.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.035
  Epoch 49/60
Model trained in 1.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.444
  Epoch 50/60
Model trained in 1.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.623
  Epoch 51/60
Model trained in 1.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.334
  Epoch 52/60
Model trained in 1.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.262
  Epoch 53/60
Model trained in 1.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.962
  Epoch 54/60
Model trained in 1.95s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.531
  Epoch 55/60
Model trained in 1.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.183
  Epoch 56/60
Model trained in 1.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.946
  Epoch 57/60
Model trained in 1.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.537
  Epoch 58/60
Model trained in 1.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.084
  Epoch 59/60
Model trained in 1.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.735
  Epoch 60/60
Model trained in 1.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.663

  best_val_SMAPE=79.735

Combination 1112/1152: {'encoder_hidden_size': 48, 'encoder_layers': 2, 'encoder_dropout': 0.2, 'decoder_hidden_size': 33, 'decoder_layers': 2, 'decoder_dropout': 0.0, 'learning_rate': 0.0005, 'max_epochs': 60, 'patience': 20, 'batch_size': 64, 'sequence_length': 168}
Time: 556.26 minutes - estimated total time: 576.27 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 2.15s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 185.326
  Epoch 2/60
Model trained in 1.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 178.840
  Epoch 3/60
Model trained in 1.97s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 173.673
  Epoch 4/60
Model trained in 1.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 169.034
  Epoch 5/60
Model trained in 2.20s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 164.717
  Epoch 6/60
Model trained in 1.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 160.688
  Epoch 7/60
Model trained in 2.05s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 156.971
  Epoch 8/60
Model trained in 1.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 153.434
  Epoch 9/60
Model trained in 1.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 150.111
  Epoch 10/60
Model trained in 1.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 146.933
  Epoch 11/60
Model trained in 1.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 143.868
  Epoch 12/60
Model trained in 2.09s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 140.951
  Epoch 13/60
Model trained in 1.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 138.128
  Epoch 14/60
Model trained in 1.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 135.409
  Epoch 15/60
Model trained in 1.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 132.740
  Epoch 16/60
Model trained in 1.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 130.119
  Epoch 17/60
Model trained in 1.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 127.612
  Epoch 18/60
Model trained in 1.98s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 126.053
  Epoch 19/60
Model trained in 1.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 123.798
  Epoch 20/60
Model trained in 1.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 121.622
  Epoch 21/60
Model trained in 1.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 119.026
  Epoch 22/60
Model trained in 1.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 116.640
  Epoch 23/60
Model trained in 1.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 114.480
  Epoch 24/60
Model trained in 1.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 112.232
  Epoch 25/60
Model trained in 1.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 110.190
  Epoch 26/60
Model trained in 1.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 108.173
  Epoch 27/60
Model trained in 1.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 106.506
  Epoch 28/60
Model trained in 1.99s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 104.871
  Epoch 29/60
Model trained in 2.05s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 103.277
  Epoch 30/60
Model trained in 1.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 101.471
  Epoch 31/60
Model trained in 2.01s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 99.422
  Epoch 32/60
Model trained in 1.98s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 97.845
  Epoch 33/60
Model trained in 1.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 96.274
  Epoch 34/60
Model trained in 2.11s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 94.899
  Epoch 35/60
Model trained in 2.04s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.691
  Epoch 36/60
Model trained in 1.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.334
  Epoch 37/60
Model trained in 1.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.195
  Epoch 38/60
Model trained in 1.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.804
  Epoch 39/60
Model trained in 1.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.291
  Epoch 40/60
Model trained in 1.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.017
  Epoch 41/60
Model trained in 1.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.913
  Epoch 42/60
Model trained in 1.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.392
  Epoch 43/60
Model trained in 1.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.349
  Epoch 44/60
Model trained in 2.00s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.369
  Epoch 45/60
Model trained in 2.02s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.568
  Epoch 46/60
Model trained in 2.11s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.968
  Epoch 47/60
Model trained in 1.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.764
  Epoch 48/60
Model trained in 1.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.932
  Epoch 49/60
Model trained in 1.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.367
  Epoch 50/60
Model trained in 1.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.955
  Epoch 51/60
Model trained in 1.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.772
  Epoch 52/60
Model trained in 1.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.316
  Epoch 53/60
Model trained in 1.95s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.802
  Epoch 54/60
Model trained in 1.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.973
  Epoch 55/60
Model trained in 1.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.876
  Epoch 56/60
Model trained in 1.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.315
  Epoch 57/60
Model trained in 1.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.251
  Epoch 58/60
Model trained in 2.03s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.492
  Epoch 59/60
Model trained in 1.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.159
  Epoch 60/60
Model trained in 1.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.175

  best_val_SMAPE=75.159

Combination 1113/1152: {'encoder_hidden_size': 48, 'encoder_layers': 2, 'encoder_dropout': 0.2, 'decoder_hidden_size': 33, 'decoder_layers': 2, 'decoder_dropout': 0.2, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 20, 'batch_size': 32, 'sequence_length': 24}
Time: 558.67 minutes - estimated total time: 578.24 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 3.27s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 169.033
  Epoch 2/60
Model trained in 3.29s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 153.330
  Epoch 3/60
Model trained in 3.20s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 140.876
  Epoch 4/60
Model trained in 3.15s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 130.128
  Epoch 5/60
Model trained in 3.24s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 123.136
  Epoch 6/60
Model trained in 3.06s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 115.566
  Epoch 7/60
Model trained in 3.26s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 108.625
  Epoch 8/60
Model trained in 3.35s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 102.772
  Epoch 9/60
Model trained in 3.09s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 95.460
  Epoch 10/60
Model trained in 3.29s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.779
  Epoch 11/60
Model trained in 3.18s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.382
  Epoch 12/60
Model trained in 3.23s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.793
  Epoch 13/60
Model trained in 2.97s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.030
  Epoch 14/60
Model trained in 3.19s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.601
  Epoch 15/60
Model trained in 2.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.506
  Epoch 16/60
Model trained in 3.05s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.681
  Epoch 17/60
Model trained in 3.08s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.993
  Epoch 18/60
Model trained in 3.02s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.726
  Epoch 19/60
Model trained in 3.26s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.406
  Epoch 20/60
Model trained in 3.28s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.219
  Epoch 21/60
Model trained in 3.16s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.838
  Epoch 22/60
Model trained in 3.10s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.274
  Epoch 23/60
Model trained in 2.99s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.995
  Epoch 24/60
Model trained in 2.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.228
  Epoch 25/60
Model trained in 2.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.875
  Epoch 26/60
Model trained in 3.07s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.402
  Epoch 27/60
Model trained in 2.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.099
  Epoch 28/60
Model trained in 3.28s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.137
  Epoch 29/60
Model trained in 3.24s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.411
  Epoch 30/60
Model trained in 3.15s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.614
  Epoch 31/60
Model trained in 3.13s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.342
  Epoch 32/60
Model trained in 3.09s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.204
  Epoch 33/60
Model trained in 3.01s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.526
  Epoch 34/60
Model trained in 3.14s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.287
  Epoch 35/60
Model trained in 3.11s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.599
  Epoch 36/60
Model trained in 3.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.771
  Epoch 37/60
Model trained in 4.39s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.748
  Epoch 38/60
Model trained in 4.49s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.204
  Epoch 39/60
Model trained in 4.41s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.963
  Epoch 40/60
Model trained in 4.25s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.802
  Epoch 41/60
Model trained in 4.25s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.748
  Epoch 42/60
Model trained in 4.16s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.458
  Epoch 43/60
Model trained in 4.26s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.181
  Epoch 44/60
Model trained in 3.21s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.282
  Epoch 45/60
Model trained in 2.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.213
  Epoch 46/60
Model trained in 2.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.217
  Epoch 47/60
Model trained in 2.99s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.818
  Epoch 48/60
Model trained in 2.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.277
  Epoch 49/60
Model trained in 3.04s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.340
  Epoch 50/60
Model trained in 2.98s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.101
  Epoch 51/60
Model trained in 2.98s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.615
  Epoch 52/60
Model trained in 2.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.597
  Epoch 53/60
Model trained in 3.20s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.564
  Epoch 54/60
Model trained in 2.97s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.163
  Epoch 55/60
Model trained in 3.11s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.297
  Epoch 56/60
Model trained in 3.09s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.316
  Epoch 57/60
Model trained in 2.95s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.467
  Epoch 58/60
Model trained in 2.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.761
  Epoch 59/60
Model trained in 3.04s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.449
  Epoch 60/60
Model trained in 3.07s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.243

  best_val_SMAPE=74.615

Combination 1114/1152: {'encoder_hidden_size': 48, 'encoder_layers': 2, 'encoder_dropout': 0.2, 'decoder_hidden_size': 33, 'decoder_layers': 2, 'decoder_dropout': 0.2, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 20, 'batch_size': 32, 'sequence_length': 168}
Time: 562.41 minutes - estimated total time: 581.60 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 4.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 169.022
  Epoch 2/60
Model trained in 4.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 153.417
  Epoch 3/60
Model trained in 4.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 141.026
  Epoch 4/60
Model trained in 4.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 130.327
  Epoch 5/60
Model trained in 4.67s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 120.596
  Epoch 6/60
Model trained in 4.68s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 111.998
  Epoch 7/60
Model trained in 4.63s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 104.290
  Epoch 8/60
Model trained in 4.53s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 97.320
  Epoch 9/60
Model trained in 4.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 97.165
  Epoch 10/60
Model trained in 4.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.301
  Epoch 11/60
Model trained in 4.58s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.107
  Epoch 12/60
Model trained in 4.52s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.308
  Epoch 13/60
Model trained in 4.51s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.722
  Epoch 14/60
Model trained in 4.54s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.143
  Epoch 15/60
Model trained in 4.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.966
  Epoch 16/60
Model trained in 4.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.657
  Epoch 17/60
Model trained in 4.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.109
  Epoch 18/60
Model trained in 4.67s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.113
  Epoch 19/60
Model trained in 4.34s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.855
  Epoch 20/60
Model trained in 4.40s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.775
  Epoch 21/60
Model trained in 4.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.063
  Epoch 22/60
Model trained in 4.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.411
  Epoch 23/60
Model trained in 4.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.444
  Epoch 24/60
Model trained in 4.62s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.469
  Epoch 25/60
Model trained in 4.47s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.320
  Epoch 26/60
Model trained in 4.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.867
  Epoch 27/60
Model trained in 4.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.021
  Epoch 28/60
Model trained in 4.65s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.270
  Epoch 29/60
Model trained in 4.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.559
  Epoch 30/60
Model trained in 4.49s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.514
  Epoch 31/60
Model trained in 4.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.345
  Epoch 32/60
Model trained in 4.55s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.089
  Epoch 33/60
Model trained in 4.54s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.344
  Epoch 34/60
Model trained in 4.26s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.979
  Epoch 35/60
Model trained in 4.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.731
  Epoch 36/60
Model trained in 4.68s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.599
  Early stopping triggered.

  best_val_SMAPE=79.657

Combination 1115/1152: {'encoder_hidden_size': 48, 'encoder_layers': 2, 'encoder_dropout': 0.2, 'decoder_hidden_size': 33, 'decoder_layers': 2, 'decoder_dropout': 0.2, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 20, 'batch_size': 64, 'sequence_length': 24}
Time: 565.61 minutes - estimated total time: 584.38 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 2.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 178.834
  Epoch 2/60
Model trained in 2.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 168.832
  Epoch 3/60
Model trained in 2.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 160.396
  Epoch 4/60
Model trained in 3.04s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 153.113
  Epoch 5/60
Model trained in 2.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 146.599
  Epoch 6/60
Model trained in 2.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 140.629
  Epoch 7/60
Model trained in 2.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 135.106
  Epoch 8/60
Model trained in 2.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 129.839
  Epoch 9/60
Model trained in 2.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 124.942
  Epoch 10/60
Model trained in 2.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 122.361
  Epoch 11/60
Model trained in 2.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 119.758
  Epoch 12/60
Model trained in 2.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 115.231
  Epoch 13/60
Model trained in 2.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 110.972
  Epoch 14/60
Model trained in 2.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 107.703
  Epoch 15/60
Model trained in 2.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 105.140
  Epoch 16/60
Model trained in 2.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 102.538
  Epoch 17/60
Model trained in 2.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 99.210
  Epoch 18/60
Model trained in 2.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 96.633
  Epoch 19/60
Model trained in 2.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 94.344
  Epoch 20/60
Model trained in 2.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.058
  Epoch 21/60
Model trained in 2.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.883
  Epoch 22/60
Model trained in 2.43s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.138
  Epoch 23/60
Model trained in 1.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.889
  Epoch 24/60
Model trained in 1.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.305
  Epoch 25/60
Model trained in 1.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.172
  Epoch 26/60
Model trained in 1.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.306
  Epoch 27/60
Model trained in 1.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.393
  Epoch 28/60
Model trained in 1.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.672
  Epoch 29/60
Model trained in 1.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.220
  Epoch 30/60
Model trained in 1.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.920
  Epoch 31/60
Model trained in 1.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.420
  Epoch 32/60
Model trained in 1.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.278
  Epoch 33/60
Model trained in 1.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.518
  Epoch 34/60
Model trained in 1.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.932
  Epoch 35/60
Model trained in 1.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.259
  Epoch 36/60
Model trained in 1.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.750
  Epoch 37/60
Model trained in 1.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.915
  Epoch 38/60
Model trained in 1.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.693
  Epoch 39/60
Model trained in 1.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.676
  Epoch 40/60
Model trained in 1.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.815
  Epoch 41/60
Model trained in 1.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.730
  Epoch 42/60
Model trained in 1.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.717
  Epoch 43/60
Model trained in 1.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.814
  Epoch 44/60
Model trained in 1.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.720
  Epoch 45/60
Model trained in 1.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.000
  Epoch 46/60
Model trained in 1.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.844
  Epoch 47/60
Model trained in 1.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.547
  Epoch 48/60
Model trained in 1.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.400
  Early stopping triggered.

  best_val_SMAPE=84.672

Combination 1116/1152: {'encoder_hidden_size': 48, 'encoder_layers': 2, 'encoder_dropout': 0.2, 'decoder_hidden_size': 33, 'decoder_layers': 2, 'decoder_dropout': 0.2, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 20, 'batch_size': 64, 'sequence_length': 168}
Time: 567.88 minutes - estimated total time: 586.20 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 2.06s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 178.880
  Epoch 2/60
Model trained in 1.95s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 168.941
  Epoch 3/60
Model trained in 1.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 160.556
  Epoch 4/60
Model trained in 2.01s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 153.304
  Epoch 5/60
Model trained in 1.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 146.820
  Epoch 6/60
Model trained in 1.98s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 140.871
  Epoch 7/60
Model trained in 1.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 135.371
  Epoch 8/60
Model trained in 1.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 130.130
  Epoch 9/60
Model trained in 1.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 125.130
  Epoch 10/60
Model trained in 1.95s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 120.366
  Epoch 11/60
Model trained in 1.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 115.957
  Epoch 12/60
Model trained in 1.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 114.920
  Epoch 13/60
Model trained in 1.98s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 111.696
  Epoch 14/60
Model trained in 1.95s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 109.022
  Epoch 15/60
Model trained in 2.00s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 105.243
  Epoch 16/60
Model trained in 1.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 102.584
  Epoch 17/60
Model trained in 1.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 99.979
  Epoch 18/60
Model trained in 1.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 97.234
  Epoch 19/60
Model trained in 1.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 94.363
  Epoch 20/60
Model trained in 1.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.036
  Epoch 21/60
Model trained in 1.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.134
  Epoch 22/60
Model trained in 1.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.858
  Epoch 23/60
Model trained in 1.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.004
  Epoch 24/60
Model trained in 1.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.270
  Epoch 25/60
Model trained in 1.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.945
  Epoch 26/60
Model trained in 1.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.846
  Epoch 27/60
Model trained in 1.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.238
  Epoch 28/60

C:\Users\n_and\AppData\Local\Temp\ipykernel_4700\3103432539.py:17: RuntimeWarning: invalid value encountered in divide
  vals = np.where(denom == 0, 0.0, 200.0 * np.abs(y_pred - y_true) / denom)

Model trained in 1.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.038
  Epoch 29/60
Model trained in 1.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.006
  Epoch 30/60
Model trained in 1.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.224
  Epoch 31/60
Model trained in 1.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.371
  Epoch 32/60
Model trained in 1.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.089
  Epoch 33/60
Model trained in 1.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.952
  Epoch 34/60
Model trained in 1.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.951
  Epoch 35/60
Model trained in 1.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.849
  Epoch 36/60
Model trained in 2.00s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.767
  Epoch 37/60
Model trained in 1.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.551
  Epoch 38/60
Model trained in 1.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.548
  Epoch 39/60
Model trained in 2.00s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.590
  Epoch 40/60
Model trained in 1.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.818
  Epoch 41/60
Model trained in 1.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.055
  Epoch 42/60
Model trained in 1.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.300
  Epoch 43/60
Model trained in 1.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.538
  Epoch 44/60
Model trained in 1.97s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.605
  Epoch 45/60
Model trained in 1.97s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.428
  Epoch 46/60
Model trained in 1.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.784
  Epoch 47/60
Model trained in 1.98s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.056
  Epoch 48/60
Model trained in 1.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.380
  Epoch 49/60
Model trained in 1.98s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.048
  Epoch 50/60
Model trained in 1.98s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.206
  Epoch 51/60
Model trained in 1.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.428
  Epoch 52/60
Model trained in 1.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.679
  Epoch 53/60
Model trained in 1.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.634
  Epoch 54/60
Model trained in 1.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.228
  Epoch 55/60
Model trained in 1.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.770
  Epoch 56/60
Model trained in 2.00s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.022
  Epoch 57/60
Model trained in 1.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.098
  Epoch 58/60
Model trained in 1.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.899
  Epoch 59/60
Model trained in 1.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.373
  Epoch 60/60
Model trained in 1.99s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.947

  best_val_SMAPE=78.055

Combination 1117/1152: {'encoder_hidden_size': 48, 'encoder_layers': 2, 'encoder_dropout': 0.2, 'decoder_hidden_size': 33, 'decoder_layers': 2, 'decoder_dropout': 0.2, 'learning_rate': 0.0005, 'max_epochs': 60, 'patience': 20, 'batch_size': 32, 'sequence_length': 24}
Time: 570.27 minutes - estimated total time: 588.14 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 3.06s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 178.854
  Epoch 2/60
Model trained in 3.05s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 169.007
  Epoch 3/60
Model trained in 2.95s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 160.650
  Epoch 4/60
Model trained in 2.99s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 153.395
  Epoch 5/60
Model trained in 3.05s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 146.892
  Epoch 6/60
Model trained in 2.98s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 140.912
  Epoch 7/60
Model trained in 2.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 135.372
  Epoch 8/60
Model trained in 2.98s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 130.083
  Epoch 9/60
Model trained in 2.97s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 125.030
  Epoch 10/60
Model trained in 2.99s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 120.213
  Epoch 11/60
Model trained in 3.04s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 115.725
  Epoch 12/60
Model trained in 3.00s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 116.837
  Epoch 13/60
Model trained in 3.06s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 111.875
  Epoch 14/60
Model trained in 3.13s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 107.787
  Epoch 15/60
Model trained in 2.99s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 104.720
  Epoch 16/60
Model trained in 2.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 101.645
  Epoch 17/60
Model trained in 2.97s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 98.747
  Epoch 18/60
Model trained in 2.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 96.429
  Epoch 19/60
Model trained in 2.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.985
  Epoch 20/60
Model trained in 3.02s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.541
  Epoch 21/60
Model trained in 3.01s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.427
  Epoch 22/60
Model trained in 3.05s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.722
  Epoch 23/60
Model trained in 3.03s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.736
  Epoch 24/60
Model trained in 2.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.573
  Epoch 25/60
Model trained in 2.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.107
  Epoch 26/60
Model trained in 2.97s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.629
  Epoch 27/60
Model trained in 2.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.353
  Epoch 28/60
Model trained in 2.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.337
  Epoch 29/60
Model trained in 2.95s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.631
  Epoch 30/60
Model trained in 3.10s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.052
  Epoch 31/60
Model trained in 2.97s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.386
  Epoch 32/60
Model trained in 3.05s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.219
  Epoch 33/60
Model trained in 3.07s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.696
  Epoch 34/60
Model trained in 2.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.807
  Epoch 35/60
Model trained in 2.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.628
  Epoch 36/60
Model trained in 3.03s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.223
  Epoch 37/60
Model trained in 2.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.499
  Epoch 38/60
Model trained in 2.99s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.186
  Epoch 39/60
Model trained in 2.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.104
  Epoch 40/60
Model trained in 2.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.471
  Epoch 41/60
Model trained in 2.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.422
  Epoch 42/60
Model trained in 2.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.222
  Epoch 43/60
Model trained in 2.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.089
  Epoch 44/60
Model trained in 2.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.822
  Epoch 45/60
Model trained in 2.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.532
  Epoch 46/60
Model trained in 2.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.642
  Epoch 47/60
Model trained in 2.97s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.372
  Epoch 48/60
Model trained in 3.04s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.428
  Epoch 49/60
Model trained in 3.18s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.687
  Epoch 50/60
Model trained in 3.02s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.011
  Epoch 51/60
Model trained in 2.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.775
  Epoch 52/60
Model trained in 2.97s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.797
  Epoch 53/60
Model trained in 2.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.026
  Epoch 54/60
Model trained in 2.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.181
  Early stopping triggered.

  best_val_SMAPE=76.807

Combination 1118/1152: {'encoder_hidden_size': 48, 'encoder_layers': 2, 'encoder_dropout': 0.2, 'decoder_hidden_size': 33, 'decoder_layers': 2, 'decoder_dropout': 0.2, 'learning_rate': 0.0005, 'max_epochs': 60, 'patience': 20, 'batch_size': 32, 'sequence_length': 168}
Time: 573.37 minutes - estimated total time: 590.81 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 3.15s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 178.881
  Epoch 2/60
Model trained in 3.10s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 169.099
  Epoch 3/60
Model trained in 3.07s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 160.784
  Epoch 4/60
Model trained in 3.13s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 153.554
  Epoch 5/60
Model trained in 2.98s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 147.075
  Epoch 6/60
Model trained in 3.12s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 141.113
  Epoch 7/60
Model trained in 3.16s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 135.592
  Epoch 8/60
Model trained in 3.04s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 130.325
  Epoch 9/60
Model trained in 2.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 125.288
  Epoch 10/60
Model trained in 2.98s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 122.715
  Epoch 11/60
Model trained in 3.11s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 118.654
  Epoch 12/60
Model trained in 3.06s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 114.292
  Epoch 13/60
Model trained in 3.01s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 110.433
  Epoch 14/60
Model trained in 2.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 106.292
  Epoch 15/60
Model trained in 2.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 102.447
  Epoch 16/60
Model trained in 3.01s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 99.188
  Epoch 17/60
Model trained in 3.00s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 96.872
  Epoch 18/60
Model trained in 2.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 94.956
  Epoch 19/60
Model trained in 2.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.060
  Epoch 20/60
Model trained in 2.99s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.955
  Epoch 21/60
Model trained in 2.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.455
  Epoch 22/60
Model trained in 3.02s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.413
  Epoch 23/60
Model trained in 2.97s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.307
  Epoch 24/60
Model trained in 2.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.014
  Epoch 25/60
Model trained in 2.97s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.068
  Epoch 26/60
Model trained in 3.04s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.401
  Epoch 27/60
Model trained in 2.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.621
  Epoch 28/60
Model trained in 2.95s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.980
  Epoch 29/60
Model trained in 3.02s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.640
  Epoch 30/60
Model trained in 3.05s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.063
  Epoch 31/60
Model trained in 3.09s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.083
  Epoch 32/60
Model trained in 3.07s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 72.894
  Epoch 33/60
Model trained in 3.11s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.149
  Epoch 34/60
Model trained in 3.15s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.988
  Epoch 35/60
Model trained in 3.12s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.918
  Epoch 36/60
Model trained in 2.95s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.876
  Epoch 37/60
Model trained in 2.98s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.782
  Epoch 38/60
Model trained in 3.05s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.301
  Epoch 39/60
Model trained in 3.11s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.892
  Epoch 40/60
Model trained in 3.11s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.271
  Epoch 41/60
Model trained in 2.98s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.088
  Epoch 42/60
Model trained in 2.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.606
  Epoch 43/60
Model trained in 2.98s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.586
  Epoch 44/60
Model trained in 3.01s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.524
  Epoch 45/60
Model trained in 2.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.313
  Epoch 46/60
Model trained in 2.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.818
  Epoch 47/60
Model trained in 3.02s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.354
  Epoch 48/60
Model trained in 3.05s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.301
  Epoch 49/60
Model trained in 2.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.040
  Epoch 50/60
Model trained in 2.98s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.096
  Epoch 51/60
Model trained in 2.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.150
  Epoch 52/60
Model trained in 2.95s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.822
  Early stopping triggered.

  best_val_SMAPE=72.894

Combination 1119/1152: {'encoder_hidden_size': 48, 'encoder_layers': 2, 'encoder_dropout': 0.2, 'decoder_hidden_size': 33, 'decoder_layers': 2, 'decoder_dropout': 0.2, 'learning_rate': 0.0005, 'max_epochs': 60, 'patience': 20, 'batch_size': 64, 'sequence_length': 24}
Time: 576.40 minutes - estimated total time: 593.40 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 1.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 185.270
  Epoch 2/60
Model trained in 1.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 178.749
  Epoch 3/60
Model trained in 1.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 173.547
  Epoch 4/60
Model trained in 1.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 168.880
  Epoch 5/60
Model trained in 1.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 164.545
  Epoch 6/60
Model trained in 1.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 160.497
  Epoch 7/60
Model trained in 1.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 156.769
  Epoch 8/60
Model trained in 1.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 153.221
  Epoch 9/60
Model trained in 1.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 149.885
  Epoch 10/60
Model trained in 1.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 146.694
  Epoch 11/60
Model trained in 1.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 143.619
  Epoch 12/60
Model trained in 1.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 140.693
  Epoch 13/60
Model trained in 1.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 137.860
  Epoch 14/60
Model trained in 1.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 135.129
  Epoch 15/60
Model trained in 1.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 132.599
  Epoch 16/60
Model trained in 1.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 130.616
  Epoch 17/60
Model trained in 1.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 129.083
  Epoch 18/60
Model trained in 1.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 126.850
  Epoch 19/60
Model trained in 1.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 124.400
  Epoch 20/60
Model trained in 1.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 122.072
  Epoch 21/60
Model trained in 1.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 119.558
  Epoch 22/60
Model trained in 1.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 117.166
  Epoch 23/60
Model trained in 1.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 114.948
  Epoch 24/60
Model trained in 1.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 112.832
  Epoch 25/60
Model trained in 1.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 110.660
  Epoch 26/60
Model trained in 1.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 108.796
  Epoch 27/60
Model trained in 1.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 107.420
  Epoch 28/60
Model trained in 1.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 106.042
  Epoch 29/60
Model trained in 1.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 104.018
  Epoch 30/60
Model trained in 1.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 102.259
  Epoch 31/60
Model trained in 1.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 100.733
  Epoch 32/60
Model trained in 1.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 99.357
  Epoch 33/60
Model trained in 1.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 97.887
  Epoch 34/60
Model trained in 1.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 96.667
  Epoch 35/60
Model trained in 1.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 95.043
  Epoch 36/60
Model trained in 1.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.721
  Epoch 37/60
Model trained in 1.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.248
  Epoch 38/60
Model trained in 1.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.126
  Epoch 39/60
Model trained in 1.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.790
  Epoch 40/60
Model trained in 1.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.433
  Epoch 41/60
Model trained in 1.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.015
  Epoch 42/60
Model trained in 1.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.045
  Epoch 43/60
Model trained in 1.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.982
  Epoch 44/60
Model trained in 1.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.091
  Epoch 45/60
Model trained in 1.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.356
  Epoch 46/60
Model trained in 1.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.505
  Epoch 47/60
Model trained in 1.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.703
  Epoch 48/60
Model trained in 1.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.854
  Epoch 49/60
Model trained in 1.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.823
  Epoch 50/60
Model trained in 1.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.018
  Epoch 51/60
Model trained in 1.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.337
  Epoch 52/60
Model trained in 1.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.933
  Epoch 53/60
Model trained in 1.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.532
  Epoch 54/60
Model trained in 1.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.097
  Epoch 55/60
Model trained in 1.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.670
  Epoch 56/60
Model trained in 1.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.196
  Epoch 57/60
Model trained in 1.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.737
  Epoch 58/60
Model trained in 1.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.452
  Epoch 59/60
Model trained in 1.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.864
  Epoch 60/60
Model trained in 1.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.610

  best_val_SMAPE=74.610

Combination 1120/1152: {'encoder_hidden_size': 48, 'encoder_layers': 2, 'encoder_dropout': 0.2, 'decoder_hidden_size': 33, 'decoder_layers': 2, 'decoder_dropout': 0.2, 'learning_rate': 0.0005, 'max_epochs': 60, 'patience': 20, 'batch_size': 64, 'sequence_length': 168}
Time: 578.66 minutes - estimated total time: 595.20 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 1.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 185.320
  Epoch 2/60
Model trained in 1.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 178.833
  Epoch 3/60
Model trained in 1.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 173.666
  Epoch 4/60
Model trained in 1.97s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 169.026
  Epoch 5/60
Model trained in 2.00s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 164.710
  Epoch 6/60
Model trained in 1.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 160.681
  Epoch 7/60
Model trained in 1.98s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 156.965
  Epoch 8/60
Model trained in 1.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 153.428
  Epoch 9/60
Model trained in 1.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 150.105
  Epoch 10/60
Model trained in 1.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 146.927
  Epoch 11/60
Model trained in 1.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 143.863
  Epoch 12/60
Model trained in 2.03s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 140.946
  Epoch 13/60
Model trained in 1.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 138.123
  Epoch 14/60
Model trained in 1.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 135.876
  Epoch 15/60
Model trained in 1.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 134.189
  Epoch 16/60
Model trained in 1.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 131.598
  Epoch 17/60
Model trained in 1.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 129.010
  Epoch 18/60
Model trained in 1.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 126.532
  Epoch 19/60
Model trained in 1.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 124.122
  Epoch 20/60
Model trained in 1.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 122.041
  Epoch 21/60
Model trained in 1.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 119.870
  Epoch 22/60
Model trained in 1.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 117.527
  Epoch 23/60
Model trained in 1.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 115.290
  Epoch 24/60
Model trained in 1.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 113.299
  Epoch 25/60
Model trained in 1.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 111.321
  Epoch 26/60
Model trained in 1.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 109.391
  Epoch 27/60
Model trained in 1.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 107.508
  Epoch 28/60
Model trained in 1.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 105.373
  Epoch 29/60
Model trained in 1.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 103.826
  Epoch 30/60
Model trained in 1.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 101.899
  Epoch 31/60
Model trained in 1.95s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 100.354
  Epoch 32/60
Model trained in 1.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 98.576
  Epoch 33/60
Model trained in 1.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 97.377
  Epoch 34/60
Model trained in 1.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 95.688
  Epoch 35/60
Model trained in 1.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 94.443
  Epoch 36/60
Model trained in 1.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.951
  Epoch 37/60
Model trained in 1.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.481
  Epoch 38/60
Model trained in 1.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.120
  Epoch 39/60
Model trained in 1.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.215
  Epoch 40/60
Model trained in 2.02s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.116
  Epoch 41/60
Model trained in 1.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.257
  Epoch 42/60
Model trained in 1.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.604
  Epoch 43/60
Model trained in 2.00s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.940
  Epoch 44/60
Model trained in 1.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.374
  Epoch 45/60
Model trained in 1.95s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.549
  Epoch 46/60
Model trained in 1.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.570
  Epoch 47/60
Model trained in 1.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.830
  Epoch 48/60
Model trained in 1.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.296
  Epoch 49/60
Model trained in 1.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.212
  Epoch 50/60
Model trained in 1.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.422
  Epoch 51/60
Model trained in 1.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.669
  Epoch 52/60
Model trained in 1.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.480
  Epoch 53/60
Model trained in 1.95s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.347
  Epoch 54/60
Model trained in 1.97s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.524
  Epoch 55/60
Model trained in 1.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.133
  Epoch 56/60
Model trained in 1.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.981
  Epoch 57/60
Model trained in 1.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.054
  Epoch 58/60
Model trained in 1.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.680
  Epoch 59/60
Model trained in 1.95s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.152
  Epoch 60/60
Model trained in 1.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.109

  best_val_SMAPE=78.981

Combination 1121/1152: {'encoder_hidden_size': 48, 'encoder_layers': 2, 'encoder_dropout': 0.2, 'decoder_hidden_size': 48, 'decoder_layers': 1, 'decoder_dropout': 0.0, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 20, 'batch_size': 32, 'sequence_length': 24}
Time: 581.02 minutes - estimated total time: 597.09 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 2.56s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 160.793
  Epoch 2/60
Model trained in 2.55s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 141.688
  Epoch 3/60
Model trained in 2.49s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 127.073
  Epoch 4/60
Model trained in 2.62s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 114.746
  Epoch 5/60
Model trained in 2.55s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 104.564
  Epoch 6/60
Model trained in 2.55s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 96.084
  Epoch 7/60
Model trained in 2.55s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.441
  Epoch 8/60
Model trained in 2.51s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.022
  Epoch 9/60
Model trained in 2.57s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.534
  Epoch 10/60
Model trained in 2.54s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.795
  Epoch 11/60
Model trained in 2.56s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.718
  Epoch 12/60
Model trained in 2.39s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.163
  Epoch 13/60
Model trained in 2.54s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.780
  Epoch 14/60
Model trained in 2.65s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.524
  Epoch 15/60
Model trained in 2.53s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.041
  Epoch 16/60
Model trained in 2.41s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.596
  Epoch 17/60
Model trained in 2.35s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.684
  Epoch 18/60
Model trained in 2.50s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.124
  Epoch 19/60
Model trained in 2.46s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 94.929
  Epoch 20/60
Model trained in 2.43s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 97.220
  Epoch 21/60
Model trained in 2.46s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 95.136
  Epoch 22/60
Model trained in 2.55s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 95.798
  Epoch 23/60
Model trained in 2.58s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 96.320
  Epoch 24/60
Model trained in 2.53s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 101.860
  Epoch 25/60
Model trained in 2.63s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 101.554
  Epoch 26/60
Model trained in 2.54s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 95.712
  Epoch 27/60
Model trained in 2.41s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.500
  Epoch 28/60
Model trained in 2.40s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.243
  Epoch 29/60
Model trained in 2.47s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 94.186
  Epoch 30/60
Model trained in 2.49s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.882
  Epoch 31/60
Model trained in 2.42s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 94.164
  Epoch 32/60
Model trained in 2.33s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.215
  Early stopping triggered.

  best_val_SMAPE=78.163

Combination 1122/1152: {'encoder_hidden_size': 48, 'encoder_layers': 2, 'encoder_dropout': 0.2, 'decoder_hidden_size': 48, 'decoder_layers': 1, 'decoder_dropout': 0.0, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 20, 'batch_size': 32, 'sequence_length': 168}
Time: 582.62 minutes - estimated total time: 598.20 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 2.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 160.866
  Epoch 2/60
Model trained in 2.56s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 141.823
  Epoch 3/60
Model trained in 2.57s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 127.474
  Epoch 4/60
Model trained in 2.67s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 115.252
  Epoch 5/60
Model trained in 2.67s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 104.922
  Epoch 6/60
Model trained in 2.53s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 96.522
  Epoch 7/60
Model trained in 2.63s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.651
  Epoch 8/60
Model trained in 2.65s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.635
  Epoch 9/60
Model trained in 2.52s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.872
  Epoch 10/60
Model trained in 2.53s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.212
  Epoch 11/60
Model trained in 2.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.743
  Epoch 12/60
Model trained in 2.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.879
  Epoch 13/60
Model trained in 2.61s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.289
  Epoch 14/60
Model trained in 2.55s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.237
  Epoch 15/60
Model trained in 2.57s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.695
  Epoch 16/60
Model trained in 2.56s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 100.793
  Epoch 17/60
Model trained in 2.49s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 104.567
  Epoch 18/60
Model trained in 2.49s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 107.640
  Epoch 19/60
Model trained in 2.59s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 105.459
  Epoch 20/60
Model trained in 2.60s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 108.829
  Epoch 21/60
Model trained in 2.59s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 106.869
  Epoch 22/60
Model trained in 2.65s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 107.008
  Epoch 23/60
Model trained in 2.62s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 106.402
  Epoch 24/60
Model trained in 2.59s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 105.172
  Epoch 25/60
Model trained in 2.46s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 101.703
  Epoch 26/60
Model trained in 2.61s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 101.214
  Epoch 27/60
Model trained in 2.47s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 97.623
  Epoch 28/60
Model trained in 2.45s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.955
  Epoch 29/60
Model trained in 2.52s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 96.242
  Epoch 30/60
Model trained in 2.47s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 95.927
  Epoch 31/60
Model trained in 2.57s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 94.661
  Early stopping triggered.

  best_val_SMAPE=76.743

Combination 1123/1152: {'encoder_hidden_size': 48, 'encoder_layers': 2, 'encoder_dropout': 0.2, 'decoder_hidden_size': 48, 'decoder_layers': 1, 'decoder_dropout': 0.0, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 20, 'batch_size': 64, 'sequence_length': 24}
Time: 584.21 minutes - estimated total time: 599.30 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 1.52s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 173.319
  Epoch 2/60
Model trained in 1.61s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 160.500
  Epoch 3/60
Model trained in 1.59s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 150.239
  Epoch 4/60
Model trained in 1.61s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 141.408
  Epoch 5/60
Model trained in 1.56s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 133.667
  Epoch 6/60
Model trained in 1.58s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 126.665
  Epoch 7/60
Model trained in 1.61s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 119.923
  Epoch 8/60
Model trained in 1.59s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 114.865
  Epoch 9/60
Model trained in 1.60s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 108.718
  Epoch 10/60
Model trained in 1.59s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 104.402
  Epoch 11/60
Model trained in 1.56s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 99.962
  Epoch 12/60
Model trained in 1.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 96.290
  Epoch 13/60
Model trained in 1.62s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.465
  Epoch 14/60
Model trained in 1.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.901
  Epoch 15/60
Model trained in 1.62s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.948
  Epoch 16/60
Model trained in 1.53s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.342
  Epoch 17/60
Model trained in 1.53s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.879
  Epoch 18/60
Model trained in 1.48s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.710
  Epoch 19/60
Model trained in 1.54s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.909
  Epoch 20/60
Model trained in 1.55s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.667
  Epoch 21/60
Model trained in 1.57s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.913
  Epoch 22/60
Model trained in 1.56s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.563
  Epoch 23/60
Model trained in 1.57s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.110
  Epoch 24/60
Model trained in 1.58s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.604
  Epoch 25/60
Model trained in 1.58s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.474
  Epoch 26/60
Model trained in 1.52s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.297
  Epoch 27/60
Model trained in 1.52s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.166
  Epoch 28/60
Model trained in 1.49s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.153
  Epoch 29/60
Model trained in 1.46s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.491
  Epoch 30/60
Model trained in 1.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.670
  Epoch 31/60
Model trained in 1.59s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.366
  Epoch 32/60
Model trained in 1.50s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.551
  Epoch 33/60
Model trained in 1.56s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.093
  Epoch 34/60
Model trained in 1.49s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.624
  Epoch 35/60
Model trained in 1.49s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.445
  Epoch 36/60
Model trained in 1.55s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.421
  Epoch 37/60
Model trained in 1.49s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.651
  Epoch 38/60
Model trained in 1.56s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.951
  Epoch 39/60
Model trained in 1.50s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.834
  Epoch 40/60
Model trained in 1.49s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.951
  Epoch 41/60
Model trained in 1.54s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.427
  Epoch 42/60
Model trained in 1.53s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.719
  Early stopping triggered.

  best_val_SMAPE=74.563

Combination 1124/1152: {'encoder_hidden_size': 48, 'encoder_layers': 2, 'encoder_dropout': 0.2, 'decoder_hidden_size': 48, 'decoder_layers': 1, 'decoder_dropout': 0.0, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 20, 'batch_size': 64, 'sequence_length': 168}
Time: 585.64 minutes - estimated total time: 600.23 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 1.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 173.419
  Epoch 2/60
Model trained in 1.67s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 160.667
  Epoch 3/60
Model trained in 1.67s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 150.434
  Epoch 4/60
Model trained in 1.63s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 141.668
  Epoch 5/60
Model trained in 1.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 133.970
  Epoch 6/60
Model trained in 1.65s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 126.887
  Epoch 7/60
Model trained in 1.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 120.623
  Epoch 8/60
Model trained in 1.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 114.863
  Epoch 9/60
Model trained in 1.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 109.830
  Epoch 10/60
Model trained in 1.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 104.889
  Epoch 11/60
Model trained in 1.68s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 100.320
  Epoch 12/60
Model trained in 1.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 96.217
  Epoch 13/60
Model trained in 1.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.524
  Epoch 14/60
Model trained in 1.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.660
  Epoch 15/60
Model trained in 1.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.761
  Epoch 16/60
Model trained in 1.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.687
  Epoch 17/60
Model trained in 1.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.357
  Epoch 18/60
Model trained in 1.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.565
  Epoch 19/60
Model trained in 1.68s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.799
  Epoch 20/60
Model trained in 1.67s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.967
  Epoch 21/60
Model trained in 1.59s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.265
  Epoch 22/60
Model trained in 1.62s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.370
  Epoch 23/60
Model trained in 1.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.934
  Epoch 24/60
Model trained in 1.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.695
  Epoch 25/60
Model trained in 1.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.643
  Epoch 26/60
Model trained in 1.57s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.177
  Epoch 27/60
Model trained in 1.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.076
  Epoch 28/60
Model trained in 1.62s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.273
  Epoch 29/60
Model trained in 1.65s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.207
  Epoch 30/60
Model trained in 1.62s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.685
  Epoch 31/60
Model trained in 1.58s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.337
  Epoch 32/60
Model trained in 1.61s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.635
  Epoch 33/60
Model trained in 1.67s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.188
  Epoch 34/60
Model trained in 1.65s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 95.331
  Epoch 35/60
Model trained in 1.63s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 96.878
  Epoch 36/60
Model trained in 1.55s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 95.624
  Epoch 37/60
Model trained in 1.63s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 100.502
  Epoch 38/60
Model trained in 1.62s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 101.222
  Epoch 39/60
Model trained in 1.68s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 101.978
  Early stopping triggered.

  best_val_SMAPE=79.799

Combination 1125/1152: {'encoder_hidden_size': 48, 'encoder_layers': 2, 'encoder_dropout': 0.2, 'decoder_hidden_size': 48, 'decoder_layers': 1, 'decoder_dropout': 0.0, 'learning_rate': 0.0005, 'max_epochs': 60, 'patience': 20, 'batch_size': 32, 'sequence_length': 24}
Time: 587.04 minutes - estimated total time: 601.13 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 2.59s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 173.403
  Epoch 2/60
Model trained in 2.48s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 160.769
  Epoch 3/60
Model trained in 2.42s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 150.537
  Epoch 4/60
Model trained in 2.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 141.766
  Epoch 5/60
Model trained in 2.56s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 134.568
  Epoch 6/60
Model trained in 2.56s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 127.245
  Epoch 7/60
Model trained in 2.57s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 120.792
  Epoch 8/60
Model trained in 2.53s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 115.197
  Epoch 9/60
Model trained in 2.55s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 110.148
  Epoch 10/60
Model trained in 2.47s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 105.414
  Epoch 11/60
Model trained in 2.54s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 101.102
  Epoch 12/60
Model trained in 2.41s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 97.003
  Epoch 13/60
Model trained in 2.40s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.796
  Epoch 14/60
Model trained in 2.54s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.692
  Epoch 15/60
Model trained in 2.65s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.129
  Epoch 16/60
Model trained in 2.59s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.410
  Epoch 17/60
Model trained in 2.50s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.312
  Epoch 18/60
Model trained in 2.62s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.209
  Epoch 19/60
Model trained in 2.54s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.134
  Epoch 20/60
Model trained in 2.51s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.998
  Epoch 21/60
Model trained in 2.39s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.841
  Epoch 22/60
Model trained in 2.40s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.733
  Epoch 23/60
Model trained in 2.42s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.483
  Epoch 24/60
Model trained in 2.35s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.931
  Epoch 25/60
Model trained in 2.54s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.871
  Epoch 26/60
Model trained in 2.43s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.365
  Epoch 27/60
Model trained in 2.41s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.730
  Epoch 28/60
Model trained in 2.39s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.302
  Epoch 29/60
Model trained in 2.42s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.034
  Epoch 30/60
Model trained in 2.53s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.590
  Epoch 31/60
Model trained in 2.43s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.412
  Epoch 32/60
Model trained in 2.45s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.709
  Epoch 33/60
Model trained in 2.36s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.406
  Epoch 34/60
Model trained in 2.49s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.022
  Epoch 35/60
Model trained in 2.54s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.618
  Epoch 36/60
Model trained in 2.59s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.323
  Epoch 37/60
Model trained in 2.60s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 101.658
  Epoch 38/60
Model trained in 2.55s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 101.304
  Epoch 39/60
Model trained in 2.44s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 110.914
  Epoch 40/60
Model trained in 2.44s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 115.602
  Early stopping triggered.

  best_val_SMAPE=76.998

Combination 1126/1152: {'encoder_hidden_size': 48, 'encoder_layers': 2, 'encoder_dropout': 0.2, 'decoder_hidden_size': 48, 'decoder_layers': 1, 'decoder_dropout': 0.0, 'learning_rate': 0.0005, 'max_epochs': 60, 'patience': 20, 'batch_size': 32, 'sequence_length': 168}
Time: 589.03 minutes - estimated total time: 602.63 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 2.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 173.479
  Epoch 2/60
Model trained in 2.60s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 160.901
  Epoch 3/60
Model trained in 2.51s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 150.698
  Epoch 4/60
Model trained in 2.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 141.950
  Epoch 5/60
Model trained in 2.65s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 134.338
  Epoch 6/60
Model trained in 2.62s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 127.328
  Epoch 7/60
Model trained in 2.51s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 120.971
  Epoch 8/60
Model trained in 2.52s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 115.496
  Epoch 9/60
Model trained in 2.65s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 109.912
  Epoch 10/60
Model trained in 2.56s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 105.926
  Epoch 11/60
Model trained in 2.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 101.080
  Epoch 12/60
Model trained in 2.45s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 97.259
  Epoch 13/60
Model trained in 2.47s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.303
  Epoch 14/60
Model trained in 2.46s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.643
  Epoch 15/60
Model trained in 2.53s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.851
  Epoch 16/60
Model trained in 2.55s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.596
  Epoch 17/60
Model trained in 2.44s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.860
  Epoch 18/60
Model trained in 2.50s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.329
  Epoch 19/60
Model trained in 2.56s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.686
  Epoch 20/60
Model trained in 2.52s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.165
  Epoch 21/60
Model trained in 2.46s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.297
  Epoch 22/60
Model trained in 2.55s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.879
  Epoch 23/60
Model trained in 2.57s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.380
  Epoch 24/60
Model trained in 2.45s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.604
  Epoch 25/60
Model trained in 2.60s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.456
  Epoch 26/60
Model trained in 2.59s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.377
  Epoch 27/60
Model trained in 2.49s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.302
  Epoch 28/60
Model trained in 2.47s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.924
  Epoch 29/60
Model trained in 2.54s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.958
  Epoch 30/60
Model trained in 2.56s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.655
  Epoch 31/60
Model trained in 2.43s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 95.163
  Epoch 32/60
Model trained in 2.48s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 98.811
  Epoch 33/60
Model trained in 2.53s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 94.875
  Epoch 34/60
Model trained in 2.58s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.771
  Epoch 35/60
Model trained in 2.53s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.360
  Epoch 36/60
Model trained in 2.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 99.581
  Epoch 37/60
Model trained in 2.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 99.810
  Epoch 38/60
Model trained in 2.56s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 102.380
  Epoch 39/60
Model trained in 2.51s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 103.150
  Early stopping triggered.

  best_val_SMAPE=81.686

Combination 1127/1152: {'encoder_hidden_size': 48, 'encoder_layers': 2, 'encoder_dropout': 0.2, 'decoder_hidden_size': 48, 'decoder_layers': 1, 'decoder_dropout': 0.0, 'learning_rate': 0.0005, 'max_epochs': 60, 'patience': 20, 'batch_size': 64, 'sequence_length': 24}
Time: 591.01 minutes - estimated total time: 604.12 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 1.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 181.279
  Epoch 2/60
Model trained in 1.59s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 173.253
  Epoch 3/60
Model trained in 1.61s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 166.559
  Epoch 4/60
Model trained in 1.52s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 160.600
  Epoch 5/60
Model trained in 1.53s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 155.255
  Epoch 6/60
Model trained in 1.60s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 150.345
  Epoch 7/60
Model trained in 1.65s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 145.790
  Epoch 8/60
Model trained in 1.62s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 141.585
  Epoch 9/60
Model trained in 1.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 137.703
  Epoch 10/60
Model trained in 1.51s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 136.053
  Epoch 11/60
Model trained in 1.50s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 130.232
  Epoch 12/60
Model trained in 1.58s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 126.895
  Epoch 13/60
Model trained in 1.60s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 123.618
  Epoch 14/60
Model trained in 1.62s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 120.255
  Epoch 15/60
Model trained in 1.58s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 117.118
  Epoch 16/60
Model trained in 1.56s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 114.319
  Epoch 17/60
Model trained in 1.53s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 111.963
  Epoch 18/60
Model trained in 1.56s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 109.287
  Epoch 19/60
Model trained in 1.55s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 106.885
  Epoch 20/60
Model trained in 1.58s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 104.410
  Epoch 21/60
Model trained in 1.50s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 102.127
  Epoch 22/60
Model trained in 1.48s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 100.047
  Epoch 23/60
Model trained in 1.48s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 97.913
  Epoch 24/60
Model trained in 1.46s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 96.056
  Epoch 25/60
Model trained in 1.58s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 94.312
  Epoch 26/60
Model trained in 1.54s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.791
  Epoch 27/60
Model trained in 1.48s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.548
  Epoch 28/60
Model trained in 1.52s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.721
  Epoch 29/60
Model trained in 1.50s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.280
  Epoch 30/60
Model trained in 1.49s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.897
  Epoch 31/60
Model trained in 1.53s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.055
  Epoch 32/60
Model trained in 1.58s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.751
  Epoch 33/60
Model trained in 1.55s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.325
  Epoch 34/60
Model trained in 1.48s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.087
  Epoch 35/60
Model trained in 1.47s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.547
  Epoch 36/60
Model trained in 1.56s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.674
  Epoch 37/60
Model trained in 1.51s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.231
  Epoch 38/60
Model trained in 1.50s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.730
  Epoch 39/60
Model trained in 1.56s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.597
  Epoch 40/60
Model trained in 1.61s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.064
  Epoch 41/60
Model trained in 1.54s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.254
  Epoch 42/60
Model trained in 1.51s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.863
  Epoch 43/60
Model trained in 1.56s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.084
  Epoch 44/60
Model trained in 1.65s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.310
  Epoch 45/60
Model trained in 1.53s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.026
  Epoch 46/60
Model trained in 1.60s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.342
  Epoch 47/60
Model trained in 1.56s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.719
  Epoch 48/60
Model trained in 1.56s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.438
  Epoch 49/60
Model trained in 1.63s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.958
  Epoch 50/60
Model trained in 1.55s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.705
  Epoch 51/60
Model trained in 1.55s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.286
  Epoch 52/60
Model trained in 1.54s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.729
  Epoch 53/60
Model trained in 1.53s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.655
  Epoch 54/60
Model trained in 1.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.118
  Epoch 55/60
Model trained in 1.54s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.016
  Epoch 56/60
Model trained in 1.53s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.005
  Epoch 57/60
Model trained in 1.56s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.897
  Epoch 58/60
Model trained in 1.55s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.491
  Early stopping triggered.

  best_val_SMAPE=83.730

Combination 1128/1152: {'encoder_hidden_size': 48, 'encoder_layers': 2, 'encoder_dropout': 0.2, 'decoder_hidden_size': 48, 'decoder_layers': 1, 'decoder_dropout': 0.0, 'learning_rate': 0.0005, 'max_epochs': 60, 'patience': 20, 'batch_size': 64, 'sequence_length': 168}
Time: 592.97 minutes - estimated total time: 605.58 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 1.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 181.358
  Epoch 2/60
Model trained in 1.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 173.362
  Epoch 3/60
Model trained in 1.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 166.700
  Epoch 4/60
Model trained in 1.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 160.762
  Epoch 5/60
Model trained in 1.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 155.462
  Epoch 6/60
Model trained in 1.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 150.540
  Epoch 7/60
Model trained in 1.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 145.992
  Epoch 8/60
Model trained in 1.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 141.728
  Epoch 9/60
Model trained in 1.65s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 137.780
  Epoch 10/60
Model trained in 1.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 133.989
  Epoch 11/60
Model trained in 1.63s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 130.387
  Epoch 12/60
Model trained in 1.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 126.988
  Epoch 13/60
Model trained in 1.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 123.579
  Epoch 14/60
Model trained in 1.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 120.331
  Epoch 15/60
Model trained in 1.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 117.316
  Epoch 16/60
Model trained in 1.65s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 114.418
  Epoch 17/60
Model trained in 1.61s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 111.723
  Epoch 18/60
Model trained in 1.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 109.253
  Epoch 19/60
Model trained in 1.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 106.934
  Epoch 20/60
Model trained in 1.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 104.658
  Epoch 21/60
Model trained in 1.59s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 102.448
  Epoch 22/60
Model trained in 1.60s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 100.215
  Epoch 23/60
Model trained in 1.68s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 98.312
  Epoch 24/60
Model trained in 1.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 96.385
  Epoch 25/60
Model trained in 1.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 94.435
  Epoch 26/60
Model trained in 1.60s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.580
  Epoch 27/60
Model trained in 1.61s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.309
  Epoch 28/60
Model trained in 1.63s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.614
  Epoch 29/60
Model trained in 1.67s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.087
  Epoch 30/60
Model trained in 1.68s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.302
  Epoch 31/60
Model trained in 1.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.929
  Epoch 32/60
Model trained in 1.61s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.479
  Epoch 33/60
Model trained in 1.62s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.603
  Epoch 34/60
Model trained in 1.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.388
  Epoch 35/60
Model trained in 1.68s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.450
  Epoch 36/60
Model trained in 1.61s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.625
  Epoch 37/60
Model trained in 1.62s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.248
  Epoch 38/60
Model trained in 1.65s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.127
  Epoch 39/60
Model trained in 1.61s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.275
  Epoch 40/60
Model trained in 1.67s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.743
  Epoch 41/60
Model trained in 1.61s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.899
  Epoch 42/60
Model trained in 1.61s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.162
  Epoch 43/60
Model trained in 1.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.766
  Epoch 44/60
Model trained in 1.62s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.601
  Epoch 45/60
Model trained in 1.65s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.981
  Epoch 46/60
Model trained in 1.60s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.484
  Epoch 47/60
Model trained in 1.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.980
  Epoch 48/60
Model trained in 1.59s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.261
  Epoch 49/60
Model trained in 1.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.624
  Epoch 50/60
Model trained in 1.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.699
  Epoch 51/60
Model trained in 1.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.361
  Epoch 52/60
Model trained in 1.60s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.243
  Epoch 53/60
Model trained in 1.65s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.049
  Epoch 54/60
Model trained in 1.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.891
  Early stopping triggered.

  best_val_SMAPE=83.388

Combination 1137/1152: {'encoder_hidden_size': 48, 'encoder_layers': 2, 'encoder_dropout': 0.2, 'decoder_hidden_size': 48, 'decoder_layers': 2, 'decoder_dropout': 0.0, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 20, 'batch_size': 32, 'sequence_length': 24}
Time: 594.88 minutes - estimated total time: 602.73 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 2.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 161.253
  Epoch 2/60
Model trained in 2.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 141.885
  Epoch 3/60
Model trained in 2.62s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 126.582
  Epoch 4/60
Model trained in 2.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 115.915
  Epoch 5/60
Model trained in 2.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 104.952
  Epoch 6/60
Model trained in 2.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 95.989
  Epoch 7/60
Model trained in 2.62s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.450
  Epoch 8/60
Model trained in 2.65s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.775
  Epoch 9/60
Model trained in 2.67s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.663
  Epoch 10/60
Model trained in 2.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.108
  Epoch 11/60
Model trained in 2.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.546
  Epoch 12/60
Model trained in 2.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.725
  Epoch 13/60
Model trained in 2.56s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.906
  Epoch 14/60
Model trained in 2.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.982
  Epoch 15/60
Model trained in 2.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.272
  Epoch 16/60
Model trained in 2.63s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.552
  Epoch 17/60
Model trained in 2.62s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.221
  Epoch 18/60
Model trained in 2.61s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.828
  Epoch 19/60
Model trained in 2.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.646
  Epoch 20/60
Model trained in 2.58s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.540
  Epoch 21/60
Model trained in 2.65s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.623
  Epoch 22/60
Model trained in 2.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.106
  Epoch 23/60
Model trained in 2.60s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.848
  Epoch 24/60
Model trained in 2.63s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.059
  Epoch 25/60
Model trained in 2.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.140
  Epoch 26/60
Model trained in 2.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.760
  Epoch 27/60
Model trained in 2.58s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.651
  Epoch 28/60
Model trained in 2.60s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.616
  Epoch 29/60
Model trained in 2.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.016
  Epoch 30/60
Model trained in 2.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.669
  Epoch 31/60
Model trained in 2.60s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.327
  Epoch 32/60
Model trained in 2.65s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.826
  Epoch 33/60
Model trained in 2.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.512
  Epoch 34/60
Model trained in 2.68s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.835
  Epoch 35/60
Model trained in 2.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.858
  Epoch 36/60
Model trained in 2.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.982
  Epoch 37/60
Model trained in 2.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.197
  Epoch 38/60
Model trained in 2.59s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.845
  Early stopping triggered.

  best_val_SMAPE=73.828

Combination 1138/1152: {'encoder_hidden_size': 48, 'encoder_layers': 2, 'encoder_dropout': 0.2, 'decoder_hidden_size': 48, 'decoder_layers': 2, 'decoder_dropout': 0.0, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 20, 'batch_size': 32, 'sequence_length': 168}
Time: 596.88 minutes - estimated total time: 604.22 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 2.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 161.414
  Epoch 2/60
Model trained in 2.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 142.115
  Epoch 3/60
Model trained in 2.68s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 126.868
  Epoch 4/60
Model trained in 2.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 116.545
  Epoch 5/60
Model trained in 2.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 108.240
  Epoch 6/60
Model trained in 2.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 100.326
  Epoch 7/60
Model trained in 2.68s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.242
  Epoch 8/60
Model trained in 2.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.838
  Epoch 9/60
Model trained in 2.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.400
  Epoch 10/60
Model trained in 2.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.499
  Epoch 11/60
Model trained in 2.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.825
  Epoch 12/60
Model trained in 2.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.989
  Epoch 13/60
Model trained in 2.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.971
  Epoch 14/60
Model trained in 2.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.688
  Epoch 15/60
Model trained in 2.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.446
  Epoch 16/60
Model trained in 2.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.714
  Epoch 17/60
Model trained in 2.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.277
  Epoch 18/60
Model trained in 2.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.001
  Epoch 19/60
Model trained in 2.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.451
  Epoch 20/60
Model trained in 2.60s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.104
  Epoch 21/60
Model trained in 2.67s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.486
  Epoch 22/60
Model trained in 2.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.035
  Epoch 23/60
Model trained in 2.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.082
  Epoch 24/60
Model trained in 2.63s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.590
  Epoch 25/60
Model trained in 2.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.891
  Epoch 26/60
Model trained in 2.65s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.225
  Epoch 27/60
Model trained in 2.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.868
  Epoch 28/60
Model trained in 2.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.209
  Epoch 29/60
Model trained in 2.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.372
  Epoch 30/60
Model trained in 2.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.074
  Epoch 31/60
Model trained in 2.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.046
  Epoch 32/60
Model trained in 2.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.150
  Epoch 33/60
Model trained in 2.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.599
  Epoch 34/60
Model trained in 2.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.670
  Epoch 35/60
Model trained in 2.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.473
  Epoch 36/60
Model trained in 2.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.151
  Epoch 37/60
Model trained in 2.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.951
  Epoch 38/60
Model trained in 2.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.496
  Epoch 39/60
Model trained in 2.67s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.415
  Epoch 40/60
Model trained in 2.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.580
  Epoch 41/60
Model trained in 2.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.368
  Epoch 42/60
Model trained in 2.67s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.543
  Epoch 43/60
Model trained in 2.60s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.817
  Epoch 44/60
Model trained in 2.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.216
  Epoch 45/60
Model trained in 2.67s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.141
  Epoch 46/60
Model trained in 2.67s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.120
  Epoch 47/60
Model trained in 2.63s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.633
  Epoch 48/60
Model trained in 2.58s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.358
  Epoch 49/60
Model trained in 2.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.382
  Epoch 50/60
Model trained in 2.65s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.782
  Epoch 51/60
Model trained in 2.68s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.756
  Epoch 52/60
Model trained in 2.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.671
  Epoch 53/60
Model trained in 2.59s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.474
  Epoch 54/60
Model trained in 2.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.469
  Epoch 55/60
Model trained in 2.68s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.122
  Epoch 56/60
Model trained in 2.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.755
  Epoch 57/60
Model trained in 2.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.708
  Epoch 58/60
Model trained in 2.62s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.739
  Epoch 59/60
Model trained in 2.67s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.766
  Epoch 60/60
Model trained in 2.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.867

  best_val_SMAPE=74.122

Combination 1139/1152: {'encoder_hidden_size': 48, 'encoder_layers': 2, 'encoder_dropout': 0.2, 'decoder_hidden_size': 48, 'decoder_layers': 2, 'decoder_dropout': 0.0, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 20, 'batch_size': 64, 'sequence_length': 24}
Time: 600.06 minutes - estimated total time: 606.91 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 1.58s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 174.094
  Epoch 2/60
Model trained in 1.67s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 161.011
  Epoch 3/60
Model trained in 1.61s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 150.601
  Epoch 4/60
Model trained in 1.68s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 141.663
  Epoch 5/60
Model trained in 1.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 133.711
  Epoch 6/60
Model trained in 1.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 126.284
  Epoch 7/60
Model trained in 1.68s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 121.441
  Epoch 8/60
Model trained in 1.63s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 115.697
  Epoch 9/60
Model trained in 1.68s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 111.067
  Epoch 10/60
Model trained in 1.67s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 105.936
  Epoch 11/60
Model trained in 1.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 100.631
  Epoch 12/60
Model trained in 1.67s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 96.282
  Epoch 13/60
Model trained in 1.62s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.662
  Epoch 14/60
Model trained in 1.61s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.264
  Epoch 15/60
Model trained in 1.62s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.687
  Epoch 16/60
Model trained in 1.61s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.050
  Epoch 17/60
Model trained in 1.68s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.478
  Epoch 18/60
Model trained in 1.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.727
  Epoch 19/60
Model trained in 1.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.936
  Epoch 20/60
Model trained in 1.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.463
  Epoch 21/60
Model trained in 1.59s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.166
  Epoch 22/60
Model trained in 1.59s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.379
  Epoch 23/60
Model trained in 1.54s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.713
  Epoch 24/60
Model trained in 1.60s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.692
  Epoch 25/60
Model trained in 1.61s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.279
  Epoch 26/60
Model trained in 1.60s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.496
  Epoch 27/60
Model trained in 1.63s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.950
  Epoch 28/60
Model trained in 1.65s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.535
  Epoch 29/60
Model trained in 1.57s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.611
  Epoch 30/60
Model trained in 1.63s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.489
  Epoch 31/60
Model trained in 1.63s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.822
  Epoch 32/60
Model trained in 1.65s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.566
  Epoch 33/60
Model trained in 1.59s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.556
  Epoch 34/60
Model trained in 1.59s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.018
  Epoch 35/60
Model trained in 1.67s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.057
  Epoch 36/60
Model trained in 1.55s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.855
  Epoch 37/60
Model trained in 1.65s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.473
  Epoch 38/60
Model trained in 1.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.470
  Epoch 39/60
Model trained in 1.59s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.860
  Epoch 40/60
Model trained in 1.60s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.574
  Epoch 41/60
Model trained in 1.59s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.367
  Epoch 42/60
Model trained in 1.61s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.893
  Epoch 43/60
Model trained in 1.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.415
  Epoch 44/60
Model trained in 1.61s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.947
  Epoch 45/60
Model trained in 1.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.601
  Epoch 46/60
Model trained in 1.54s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.758
  Epoch 47/60
Model trained in 1.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.412
  Epoch 48/60
Model trained in 1.61s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.141
  Epoch 49/60
Model trained in 1.67s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.958
  Epoch 50/60
Model trained in 1.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.556
  Epoch 51/60
Model trained in 1.68s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.570
  Epoch 52/60
Model trained in 1.63s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.617
  Epoch 53/60
Model trained in 1.63s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.381
  Epoch 54/60
Model trained in 1.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.160
  Early stopping triggered.

  best_val_SMAPE=74.018

Combination 1140/1152: {'encoder_hidden_size': 48, 'encoder_layers': 2, 'encoder_dropout': 0.2, 'decoder_hidden_size': 48, 'decoder_layers': 2, 'decoder_dropout': 0.0, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 20, 'batch_size': 64, 'sequence_length': 168}
Time: 601.95 minutes - estimated total time: 608.29 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 1.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 174.229
  Epoch 2/60
Model trained in 1.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 161.675
  Epoch 3/60
Model trained in 1.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 151.023
  Epoch 4/60
Model trained in 1.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 142.043
  Epoch 5/60
Model trained in 1.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 134.095
  Epoch 6/60
Model trained in 1.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 126.703
  Epoch 7/60
Model trained in 1.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 119.848
  Epoch 8/60
Model trained in 1.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 115.407
  Epoch 9/60
Model trained in 1.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 110.612
  Epoch 10/60
Model trained in 1.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 105.406
  Epoch 11/60
Model trained in 1.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 101.510
  Epoch 12/60
Model trained in 1.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 97.545
  Epoch 13/60
Model trained in 1.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.417
  Epoch 14/60
Model trained in 1.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.979
  Epoch 15/60
Model trained in 1.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.924
  Epoch 16/60
Model trained in 1.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.462
  Epoch 17/60
Model trained in 1.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.078
  Epoch 18/60
Model trained in 1.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.294
  Epoch 19/60
Model trained in 1.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.978
  Epoch 20/60
Model trained in 1.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.889
  Epoch 21/60
Model trained in 1.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.494
  Epoch 22/60
Model trained in 1.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.913
  Epoch 23/60
Model trained in 1.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.959
  Epoch 24/60
Model trained in 1.67s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.111
  Epoch 25/60
Model trained in 1.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.815
  Epoch 26/60
Model trained in 1.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.346
  Epoch 27/60
Model trained in 1.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.261
  Epoch 28/60
Model trained in 1.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.186
  Epoch 29/60
Model trained in 1.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.570
  Epoch 30/60
Model trained in 1.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.495
  Epoch 31/60
Model trained in 1.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.645
  Epoch 32/60
Model trained in 1.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.748
  Epoch 33/60
Model trained in 1.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.579
  Epoch 34/60
Model trained in 1.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.669
  Epoch 35/60
Model trained in 1.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.777
  Epoch 36/60
Model trained in 1.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.652
  Epoch 37/60
Model trained in 1.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.369
  Epoch 38/60
Model trained in 1.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.523
  Epoch 39/60
Model trained in 1.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.521
  Epoch 40/60
Model trained in 1.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.000
  Epoch 41/60
Model trained in 1.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.904
  Epoch 42/60
Model trained in 1.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.951
  Epoch 43/60
Model trained in 1.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.557
  Epoch 44/60
Model trained in 1.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.777
  Epoch 45/60
Model trained in 1.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.313
  Epoch 46/60
Model trained in 1.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.510
  Epoch 47/60
Model trained in 1.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.193
  Epoch 48/60
Model trained in 1.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.033
  Epoch 49/60
Model trained in 1.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.929
  Epoch 50/60
Model trained in 1.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.466
  Epoch 51/60
Model trained in 1.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.100
  Epoch 52/60
Model trained in 1.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.593
  Epoch 53/60
Model trained in 1.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.493
  Epoch 54/60
Model trained in 1.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.311
  Early stopping triggered.

  best_val_SMAPE=75.669

Combination 1141/1152: {'encoder_hidden_size': 48, 'encoder_layers': 2, 'encoder_dropout': 0.2, 'decoder_hidden_size': 48, 'decoder_layers': 2, 'decoder_dropout': 0.0, 'learning_rate': 0.0005, 'max_epochs': 60, 'patience': 20, 'batch_size': 32, 'sequence_length': 24}
Time: 603.99 minutes - estimated total time: 609.81 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 2.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 174.440
  Epoch 2/60
Model trained in 2.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 161.764
  Epoch 3/60
Model trained in 2.68s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 151.520
  Epoch 4/60
Model trained in 2.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 142.705
  Epoch 5/60
Model trained in 2.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 134.800
  Epoch 6/60
Model trained in 2.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 127.142
  Epoch 7/60
Model trained in 2.65s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 120.144
  Epoch 8/60
Model trained in 2.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 116.663
  Epoch 9/60
Model trained in 2.65s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 111.517
  Epoch 10/60
Model trained in 2.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 105.621
  Epoch 11/60
Model trained in 3.23s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 101.602
  Epoch 12/60
Model trained in 2.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 97.862
  Epoch 13/60
Model trained in 2.97s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 95.035
  Epoch 14/60
Model trained in 3.02s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.774
  Epoch 15/60
Model trained in 2.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.690
  Epoch 16/60
Model trained in 3.02s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.392
  Epoch 17/60
Model trained in 3.05s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.463
  Epoch 18/60
Model trained in 2.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.233
  Epoch 19/60
Model trained in 2.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.756
  Epoch 20/60
Model trained in 2.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.842
  Epoch 21/60
Model trained in 2.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.470
  Epoch 22/60
Model trained in 2.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.555
  Epoch 23/60
Model trained in 2.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.004
  Epoch 24/60
Model trained in 2.68s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.274
  Epoch 25/60
Model trained in 2.65s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.350
  Epoch 26/60
Model trained in 2.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.910
  Epoch 27/60
Model trained in 2.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.722
  Epoch 28/60
Model trained in 2.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.624
  Epoch 29/60
Model trained in 2.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.917
  Epoch 30/60
Model trained in 2.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.747
  Epoch 31/60
Model trained in 2.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.182
  Epoch 32/60
Model trained in 2.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.952
  Epoch 33/60
Model trained in 2.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.113
  Epoch 34/60
Model trained in 2.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.706
  Epoch 35/60
Model trained in 2.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.502
  Epoch 36/60
Model trained in 2.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.992
  Epoch 37/60
Model trained in 2.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.056
  Epoch 38/60
Model trained in 2.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.752
  Epoch 39/60
Model trained in 2.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.185
  Epoch 40/60
Model trained in 2.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.758
  Epoch 41/60
Model trained in 2.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.437
  Epoch 42/60
Model trained in 2.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.965
  Epoch 43/60
Model trained in 2.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.477
  Epoch 44/60
Model trained in 2.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.527
  Epoch 45/60
Model trained in 2.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.408
  Epoch 46/60
Model trained in 2.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.424
  Epoch 47/60
Model trained in 2.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.798
  Epoch 48/60
Model trained in 2.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.640
  Epoch 49/60
Model trained in 2.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.591
  Epoch 50/60
Model trained in 2.62s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.611
  Epoch 51/60
Model trained in 2.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.891
  Epoch 52/60
Model trained in 2.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.979
  Epoch 53/60
Model trained in 2.60s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.475
  Epoch 54/60
Model trained in 2.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.506
  Epoch 55/60
Model trained in 2.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.282
  Early stopping triggered.

  best_val_SMAPE=77.502

Combination 1142/1152: {'encoder_hidden_size': 48, 'encoder_layers': 2, 'encoder_dropout': 0.2, 'decoder_hidden_size': 48, 'decoder_layers': 2, 'decoder_dropout': 0.0, 'learning_rate': 0.0005, 'max_epochs': 60, 'patience': 20, 'batch_size': 32, 'sequence_length': 168}
Time: 607.00 minutes - estimated total time: 612.31 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 2.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 174.528
  Epoch 2/60
Model trained in 2.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 162.332
  Epoch 3/60
Model trained in 2.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 151.929
  Epoch 4/60
Model trained in 2.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 142.706
  Epoch 5/60
Model trained in 2.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 134.681
  Epoch 6/60
Model trained in 2.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 127.228
  Epoch 7/60
Model trained in 2.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 122.185
  Epoch 8/60
Model trained in 2.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 117.921
  Epoch 9/60
Model trained in 2.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 111.841
  Epoch 10/60
Model trained in 2.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 106.360
  Epoch 11/60
Model trained in 2.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 102.506
  Epoch 12/60
Model trained in 2.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 98.403
  Epoch 13/60
Model trained in 2.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 95.312
  Epoch 14/60
Model trained in 2.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.271
  Epoch 15/60
Model trained in 2.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.915
  Epoch 16/60
Model trained in 2.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.438
  Epoch 17/60
Model trained in 2.67s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.460
  Epoch 18/60
Model trained in 2.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.419
  Epoch 19/60
Model trained in 2.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.667
  Epoch 20/60
Model trained in 2.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.628
  Epoch 21/60
Model trained in 2.65s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.148
  Epoch 22/60
Model trained in 2.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.316
  Epoch 23/60
Model trained in 2.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.460
  Epoch 24/60
Model trained in 2.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.974
  Epoch 25/60
Model trained in 2.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.283
  Epoch 26/60
Model trained in 2.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.904
  Epoch 27/60
Model trained in 2.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.986
  Epoch 28/60
Model trained in 2.67s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.691
  Epoch 29/60
Model trained in 2.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.093
  Epoch 30/60
Model trained in 2.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.313
  Epoch 31/60
Model trained in 2.58s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.351
  Epoch 32/60
Model trained in 2.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.842
  Epoch 33/60
Model trained in 2.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.890
  Epoch 34/60
Model trained in 2.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.930
  Epoch 35/60
Model trained in 2.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.824
  Epoch 36/60
Model trained in 2.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.497
  Epoch 37/60
Model trained in 2.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.526
  Epoch 38/60
Model trained in 2.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.195
  Epoch 39/60
Model trained in 2.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.452
  Epoch 40/60
Model trained in 2.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.763
  Epoch 41/60
Model trained in 2.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.048
  Epoch 42/60
Model trained in 2.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.427
  Epoch 43/60
Model trained in 2.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.508
  Epoch 44/60
Model trained in 2.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.458
  Epoch 45/60
Model trained in 2.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.550
  Epoch 46/60
Model trained in 2.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.830
  Early stopping triggered.

  best_val_SMAPE=82.904

Combination 1143/1152: {'encoder_hidden_size': 48, 'encoder_layers': 2, 'encoder_dropout': 0.2, 'decoder_hidden_size': 48, 'decoder_layers': 2, 'decoder_dropout': 0.0, 'learning_rate': 0.0005, 'max_epochs': 60, 'patience': 20, 'batch_size': 64, 'sequence_length': 24}
Time: 609.49 minutes - estimated total time: 614.29 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 1.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 182.108
  Epoch 2/60
Model trained in 1.67s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 174.263
  Epoch 3/60
Model trained in 1.67s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 167.516
  Epoch 4/60
Model trained in 1.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 161.576
  Epoch 5/60
Model trained in 1.65s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 156.236
  Epoch 6/60
Model trained in 1.65s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 151.324
  Epoch 7/60
Model trained in 1.68s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 146.779
  Epoch 8/60
Model trained in 1.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 142.486
  Epoch 9/60
Model trained in 1.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 138.446
  Epoch 10/60
Model trained in 1.61s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 134.597
  Epoch 11/60
Model trained in 1.62s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 130.856
  Epoch 12/60
Model trained in 1.63s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 127.227
  Epoch 13/60
Model trained in 1.62s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 123.727
  Epoch 14/60
Model trained in 1.65s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 120.345
  Epoch 15/60
Model trained in 1.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 117.181
  Epoch 16/60
Model trained in 1.68s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 116.557
  Epoch 17/60
Model trained in 1.57s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 114.438
  Epoch 18/60
Model trained in 1.63s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 111.300
  Epoch 19/60
Model trained in 1.62s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 108.139
  Epoch 20/60
Model trained in 1.59s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 104.993
  Epoch 21/60
Model trained in 1.65s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 102.640
  Epoch 22/60
Model trained in 1.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 100.479
  Epoch 23/60
Model trained in 1.63s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 98.067
  Epoch 24/60
Model trained in 1.59s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 95.706
  Epoch 25/60
Model trained in 1.58s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.120
  Epoch 26/60
Model trained in 1.60s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.564
  Epoch 27/60
Model trained in 1.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.715
  Epoch 28/60
Model trained in 1.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.918
  Epoch 29/60
Model trained in 1.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.622
  Epoch 30/60
Model trained in 1.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.435
  Epoch 31/60
Model trained in 1.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.897
  Epoch 32/60
Model trained in 1.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.686
  Epoch 33/60
Model trained in 1.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.435
  Epoch 34/60
Model trained in 1.60s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.454
  Epoch 35/60
Model trained in 1.60s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.210
  Epoch 36/60
Model trained in 1.60s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.933
  Epoch 37/60
Model trained in 1.59s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.929
  Epoch 38/60
Model trained in 1.63s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.852
  Epoch 39/60
Model trained in 1.61s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.289
  Epoch 40/60
Model trained in 1.62s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.856
  Epoch 41/60
Model trained in 1.62s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.131
  Epoch 42/60
Model trained in 1.65s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.860
  Epoch 43/60
Model trained in 1.67s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.734
  Epoch 44/60
Model trained in 1.65s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.487
  Epoch 45/60
Model trained in 1.60s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.800
  Epoch 46/60
Model trained in 1.63s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.335
  Epoch 47/60
Model trained in 1.61s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.721
  Epoch 48/60
Model trained in 1.59s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.786
  Epoch 49/60
Model trained in 1.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.384
  Epoch 50/60
Model trained in 1.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.973
  Epoch 51/60
Model trained in 1.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.305
  Epoch 52/60
Model trained in 1.63s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.106
  Epoch 53/60
Model trained in 1.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.637
  Epoch 54/60
Model trained in 1.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.211
  Epoch 55/60
Model trained in 1.67s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.350
  Epoch 56/60
Model trained in 1.62s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.789
  Epoch 57/60
Model trained in 1.63s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.717
  Epoch 58/60
Model trained in 1.59s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.520
  Epoch 59/60
Model trained in 1.62s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.309
  Epoch 60/60
Model trained in 1.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.310

  best_val_SMAPE=76.721

Combination 1144/1152: {'encoder_hidden_size': 48, 'encoder_layers': 2, 'encoder_dropout': 0.2, 'decoder_hidden_size': 48, 'decoder_layers': 2, 'decoder_dropout': 0.0, 'learning_rate': 0.0005, 'max_epochs': 60, 'patience': 20, 'batch_size': 64, 'sequence_length': 168}
Time: 611.60 minutes - estimated total time: 615.88 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 1.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 182.193
  Epoch 2/60
Model trained in 1.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 174.479
  Epoch 3/60
Model trained in 1.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 168.027
  Epoch 4/60
Model trained in 1.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 161.966
  Epoch 5/60
Model trained in 1.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 156.572
  Epoch 6/60
Model trained in 1.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 151.647
  Epoch 7/60
Model trained in 1.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 147.101
  Epoch 8/60
Model trained in 1.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 142.812
  Epoch 9/60
Model trained in 1.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 138.778
  Epoch 10/60
Model trained in 1.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 134.940
  Epoch 11/60
Model trained in 1.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 131.930
  Epoch 12/60
Model trained in 1.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 128.375
  Epoch 13/60
Model trained in 1.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 125.626
  Epoch 14/60
Model trained in 1.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 122.792
  Epoch 15/60
Model trained in 1.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 119.494
  Epoch 16/60
Model trained in 1.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 116.299
  Epoch 17/60
Model trained in 1.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 113.439
  Epoch 18/60
Model trained in 1.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 110.761
  Epoch 19/60
Model trained in 1.65s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 108.174
  Epoch 20/60
Model trained in 1.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 106.597
  Epoch 21/60
Model trained in 1.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 104.429
  Epoch 22/60
Model trained in 1.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 102.723
  Epoch 23/60
Model trained in 1.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 100.941
  Epoch 24/60
Model trained in 1.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 99.616
  Epoch 25/60
Model trained in 1.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 97.678
  Epoch 26/60
Model trained in 1.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 95.800
  Epoch 27/60
Model trained in 1.65s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 94.138
  Epoch 28/60
Model trained in 1.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.758
  Epoch 29/60
Model trained in 1.68s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.721
  Epoch 30/60
Model trained in 1.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.522
  Epoch 31/60
Model trained in 1.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.109
  Epoch 32/60
Model trained in 1.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.635
  Epoch 33/60
Model trained in 1.68s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.747
  Epoch 34/60
Model trained in 1.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.793
  Epoch 35/60
Model trained in 1.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.612
  Epoch 36/60
Model trained in 1.67s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.696
  Epoch 37/60
Model trained in 1.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.611
  Epoch 38/60
Model trained in 1.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.899
  Epoch 39/60
Model trained in 1.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.848
  Epoch 40/60
Model trained in 1.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.348
  Epoch 41/60
Model trained in 1.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.639
  Epoch 42/60
Model trained in 1.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.831
  Epoch 43/60
Model trained in 1.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.936
  Epoch 44/60
Model trained in 1.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.336
  Epoch 45/60
Model trained in 1.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.300
  Epoch 46/60
Model trained in 1.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.085
  Epoch 47/60
Model trained in 1.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.733
  Epoch 48/60
Model trained in 1.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.783
  Epoch 49/60
Model trained in 1.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.389
  Epoch 50/60
Model trained in 1.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.561
  Epoch 51/60
Model trained in 1.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.060
  Epoch 52/60
Model trained in 1.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.808
  Epoch 53/60
Model trained in 1.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.194
  Epoch 54/60
Model trained in 1.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.347
  Epoch 55/60
Model trained in 1.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.103
  Epoch 56/60
Model trained in 1.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.762
  Epoch 57/60
Model trained in 1.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.727
  Epoch 58/60
Model trained in 1.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.632
  Epoch 59/60
Model trained in 1.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.278
  Epoch 60/60
Model trained in 1.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.329

  best_val_SMAPE=79.336

Combination 1145/1152: {'encoder_hidden_size': 48, 'encoder_layers': 2, 'encoder_dropout': 0.2, 'decoder_hidden_size': 48, 'decoder_layers': 2, 'decoder_dropout': 0.2, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 20, 'batch_size': 32, 'sequence_length': 24}
Time: 613.82 minutes - estimated total time: 617.57 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 2.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 161.208
  Epoch 2/60
Model trained in 2.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 141.869
  Epoch 3/60
Model trained in 2.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 126.535
  Epoch 4/60
Model trained in 2.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 115.668
  Epoch 5/60
Model trained in 2.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 105.899
  Epoch 6/60
Model trained in 2.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 98.300
  Epoch 7/60
Model trained in 2.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.240
  Epoch 8/60
Model trained in 2.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.851
  Epoch 9/60
Model trained in 2.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.493
  Epoch 10/60
Model trained in 2.61s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.437
  Epoch 11/60
Model trained in 2.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.306
  Epoch 12/60
Model trained in 2.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.563
  Epoch 13/60
Model trained in 2.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.117
  Epoch 14/60
Model trained in 2.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 72.797
  Epoch 15/60
Model trained in 2.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 71.650
  Epoch 16/60
Model trained in 2.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 71.576
  Epoch 17/60
Model trained in 2.62s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 70.781
  Epoch 18/60
Model trained in 2.67s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 70.686
  Epoch 19/60
Model trained in 2.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 70.745
  Epoch 20/60
Model trained in 2.65s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 71.066
  Epoch 21/60
Model trained in 2.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 71.304
  Epoch 22/60
Model trained in 2.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 71.111
  Epoch 23/60
Model trained in 2.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 71.388
  Epoch 24/60
Model trained in 2.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 72.007
  Epoch 25/60
Model trained in 2.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 72.366
  Epoch 26/60
Model trained in 2.68s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 72.618
  Epoch 27/60
Model trained in 2.60s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 71.982
  Epoch 28/60
Model trained in 2.63s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 71.358
  Epoch 29/60
Model trained in 2.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 71.526
  Epoch 30/60
Model trained in 2.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 71.649
  Epoch 31/60
Model trained in 2.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 72.735
  Epoch 32/60
Model trained in 2.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.451
  Epoch 33/60
Model trained in 2.95s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.035
  Epoch 34/60
Model trained in 3.05s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.133
  Epoch 35/60
Model trained in 2.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.590
  Epoch 36/60
Model trained in 2.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.602
  Epoch 37/60
Model trained in 3.03s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.100
  Epoch 38/60
Model trained in 2.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.888
  Early stopping triggered.

  best_val_SMAPE=70.686

Combination 1146/1152: {'encoder_hidden_size': 48, 'encoder_layers': 2, 'encoder_dropout': 0.2, 'decoder_hidden_size': 48, 'decoder_layers': 2, 'decoder_dropout': 0.2, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 20, 'batch_size': 32, 'sequence_length': 168}
Time: 615.87 minutes - estimated total time: 619.10 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 3.02s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 161.351
  Epoch 2/60
Model trained in 3.05s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 142.095
  Epoch 3/60
Model trained in 2.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 126.848
  Epoch 4/60
Model trained in 2.97s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 116.867
  Epoch 5/60
Model trained in 2.99s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 106.860
  Epoch 6/60
Model trained in 2.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 98.986
  Epoch 7/60
Model trained in 2.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.728
  Epoch 8/60
Model trained in 2.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.101
  Epoch 9/60
Model trained in 2.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.615
  Epoch 10/60
Model trained in 3.02s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.234
  Epoch 11/60
Model trained in 3.24s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.156
  Epoch 12/60
Model trained in 2.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.035
  Epoch 13/60
Model trained in 2.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.222
  Epoch 14/60
Model trained in 2.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.584
  Epoch 15/60
Model trained in 2.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.039
  Epoch 16/60
Model trained in 2.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.318
  Epoch 17/60
Model trained in 2.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.456
  Epoch 18/60
Model trained in 2.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.609
  Epoch 19/60
Model trained in 2.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.181
  Epoch 20/60
Model trained in 2.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.489
  Epoch 21/60
Model trained in 2.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.156
  Epoch 22/60
Model trained in 3.05s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.559
  Epoch 23/60
Model trained in 2.96s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.438
  Epoch 24/60
Model trained in 2.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.815
  Epoch 25/60
Model trained in 2.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.203
  Epoch 26/60
Model trained in 2.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.613
  Epoch 27/60
Model trained in 3.03s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.084
  Epoch 28/60
Model trained in 2.95s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.201
  Epoch 29/60
Model trained in 2.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.602
  Epoch 30/60
Model trained in 2.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.821
  Epoch 31/60
Model trained in 2.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.052
  Epoch 32/60
Model trained in 3.02s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.546
  Epoch 33/60
Model trained in 2.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.646
  Epoch 34/60
Model trained in 2.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.573
  Epoch 35/60
Model trained in 2.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.980
  Epoch 36/60
Model trained in 2.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.579
  Epoch 37/60
Model trained in 3.06s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.722
  Epoch 38/60
Model trained in 3.04s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.506
  Epoch 39/60
Model trained in 2.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.148
  Epoch 40/60
Model trained in 2.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.758
  Epoch 41/60
Model trained in 2.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.760
  Epoch 42/60
Model trained in 2.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.276
  Epoch 43/60
Model trained in 2.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.438
  Epoch 44/60
Model trained in 2.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.299
  Epoch 45/60
Model trained in 2.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.486
  Epoch 46/60
Model trained in 3.07s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.843
  Epoch 47/60
Model trained in 2.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.864
  Epoch 48/60
Model trained in 2.68s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.673
  Epoch 49/60
Model trained in 2.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.491
  Epoch 50/60
Model trained in 2.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.671
  Epoch 51/60
Model trained in 2.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.968
  Epoch 52/60
Model trained in 2.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.015
  Epoch 53/60
Model trained in 2.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.548
  Epoch 54/60
Model trained in 2.65s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.135
  Epoch 55/60
Model trained in 2.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.196
  Epoch 56/60
Model trained in 2.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.995
  Epoch 57/60
Model trained in 2.65s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.674
  Epoch 58/60
Model trained in 2.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.097
  Epoch 59/60
Model trained in 2.67s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.157
  Epoch 60/60
Model trained in 2.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.946

  best_val_SMAPE=78.946

Combination 1147/1152: {'encoder_hidden_size': 48, 'encoder_layers': 2, 'encoder_dropout': 0.2, 'decoder_hidden_size': 48, 'decoder_layers': 2, 'decoder_dropout': 0.2, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 20, 'batch_size': 64, 'sequence_length': 24}
Time: 619.19 minutes - estimated total time: 621.89 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 1.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 173.984
  Epoch 2/60
Model trained in 1.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 160.989
  Epoch 3/60
Model trained in 1.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 150.590
  Epoch 4/60
Model trained in 1.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 141.655
  Epoch 5/60
Model trained in 1.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 133.707
  Epoch 6/60
Model trained in 1.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 126.308
  Epoch 7/60
Model trained in 1.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 121.628
  Epoch 8/60
Model trained in 1.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 116.146
  Epoch 9/60
Model trained in 1.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 110.950
  Epoch 10/60
Model trained in 1.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 106.431
  Epoch 11/60
Model trained in 1.63s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 102.274
  Epoch 12/60
Model trained in 1.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 99.519
  Epoch 13/60
Model trained in 1.62s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 95.022
  Epoch 14/60
Model trained in 1.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.749
  Epoch 15/60
Model trained in 1.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.858
  Epoch 16/60
Model trained in 1.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.971
  Epoch 17/60
Model trained in 1.60s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.673
  Epoch 18/60
Model trained in 1.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.955
  Epoch 19/60
Model trained in 1.59s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.196
  Epoch 20/60
Model trained in 1.63s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.169
  Epoch 21/60
Model trained in 1.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.199
  Epoch 22/60
Model trained in 1.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.589
  Epoch 23/60
Model trained in 1.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.424
  Epoch 24/60
Model trained in 1.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.010
  Epoch 25/60
Model trained in 1.65s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.217
  Epoch 26/60
Model trained in 1.67s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.410
  Epoch 27/60
Model trained in 1.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.418
  Epoch 28/60
Model trained in 1.63s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.211
  Epoch 29/60
Model trained in 1.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.974
  Epoch 30/60
Model trained in 1.67s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.054
  Epoch 31/60
Model trained in 1.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.234
  Epoch 32/60
Model trained in 1.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.183
  Epoch 33/60
Model trained in 1.60s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.615
  Epoch 34/60
Model trained in 1.61s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.696
  Epoch 35/60
Model trained in 1.62s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.085
  Epoch 36/60
Model trained in 1.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.820
  Epoch 37/60
Model trained in 1.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.294
  Epoch 38/60
Model trained in 1.58s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.332
  Epoch 39/60
Model trained in 1.63s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.969
  Epoch 40/60
Model trained in 1.60s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.502
  Epoch 41/60
Model trained in 1.68s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.613
  Early stopping triggered.

  best_val_SMAPE=79.199

Combination 1148/1152: {'encoder_hidden_size': 48, 'encoder_layers': 2, 'encoder_dropout': 0.2, 'decoder_hidden_size': 48, 'decoder_layers': 2, 'decoder_dropout': 0.2, 'learning_rate': 0.001, 'max_epochs': 60, 'patience': 20, 'batch_size': 64, 'sequence_length': 168}
Time: 620.67 minutes - estimated total time: 622.83 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 1.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 174.216
  Epoch 2/60
Model trained in 1.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 161.472
  Epoch 3/60
Model trained in 1.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 150.931
  Epoch 4/60
Model trained in 1.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 141.987
  Epoch 5/60
Model trained in 1.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 134.051
  Epoch 6/60
Model trained in 1.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 126.644
  Epoch 7/60
Model trained in 1.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 121.754
  Epoch 8/60
Model trained in 1.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 116.453
  Epoch 9/60
Model trained in 1.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 110.944
  Epoch 10/60
Model trained in 1.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 106.450
  Epoch 11/60
Model trained in 1.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 101.057
  Epoch 12/60
Model trained in 1.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 97.010
  Epoch 13/60
Model trained in 1.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.374
  Epoch 14/60
Model trained in 1.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.355
  Epoch 15/60
Model trained in 1.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.583
  Epoch 16/60
Model trained in 1.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.698
  Epoch 17/60
Model trained in 1.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.754
  Epoch 18/60
Model trained in 1.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.283
  Epoch 19/60
Model trained in 1.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.161
  Epoch 20/60
Model trained in 1.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.486
  Epoch 21/60
Model trained in 1.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.818
  Epoch 22/60
Model trained in 1.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.774
  Epoch 23/60
Model trained in 1.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.190
  Epoch 24/60
Model trained in 1.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.390
  Epoch 25/60
Model trained in 1.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.287
  Epoch 26/60
Model trained in 1.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.644
  Epoch 27/60
Model trained in 1.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.641
  Epoch 28/60
Model trained in 1.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.050
  Epoch 29/60
Model trained in 1.68s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.253
  Epoch 30/60
Model trained in 1.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.609
  Epoch 31/60
Model trained in 1.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.921
  Epoch 32/60

C:\Users\n_and\AppData\Local\Temp\ipykernel_4700\3103432539.py:17: RuntimeWarning: invalid value encountered in divide
  vals = np.where(denom == 0, 0.0, 200.0 * np.abs(y_pred - y_true) / denom)

Model trained in 1.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.870
  Epoch 33/60
Model trained in 1.67s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.277
  Epoch 34/60
Model trained in 1.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.510
  Epoch 35/60
Model trained in 1.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.779
  Epoch 36/60
Model trained in 1.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.301
  Epoch 37/60
Model trained in 1.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.687
  Epoch 38/60
Model trained in 1.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.318
  Epoch 39/60
Model trained in 1.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.908
  Epoch 40/60
Model trained in 1.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.330
  Epoch 41/60
Model trained in 1.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.378
  Epoch 42/60
Model trained in 1.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.843
  Epoch 43/60
Model trained in 1.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.214
  Epoch 44/60
Model trained in 1.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.296
  Epoch 45/60
Model trained in 1.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.464
  Epoch 46/60
Model trained in 1.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.950
  Epoch 47/60
Model trained in 1.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.791
  Epoch 48/60
Model trained in 1.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.470
  Epoch 49/60
Model trained in 1.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.711
  Epoch 50/60
Model trained in 1.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.198
  Epoch 51/60
Model trained in 1.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.139
  Epoch 52/60
Model trained in 1.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.041
  Epoch 53/60
Model trained in 1.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.104
  Epoch 54/60
Model trained in 1.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.900
  Epoch 55/60
Model trained in 1.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.078
  Epoch 56/60
Model trained in 1.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.281
  Epoch 57/60
Model trained in 1.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.052
  Epoch 58/60
Model trained in 1.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.019
  Epoch 59/60
Model trained in 1.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.996
  Early stopping triggered.

  best_val_SMAPE=73.908

Combination 1149/1152: {'encoder_hidden_size': 48, 'encoder_layers': 2, 'encoder_dropout': 0.2, 'decoder_hidden_size': 48, 'decoder_layers': 2, 'decoder_dropout': 0.2, 'learning_rate': 0.0005, 'max_epochs': 60, 'patience': 20, 'batch_size': 32, 'sequence_length': 24}
Time: 622.88 minutes - estimated total time: 624.50 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 2.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 174.360
  Epoch 2/60
Model trained in 2.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 161.693
  Epoch 3/60
Model trained in 2.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 151.476
  Epoch 4/60
Model trained in 2.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 142.573
  Epoch 5/60
Model trained in 2.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 134.424
  Epoch 6/60
Model trained in 2.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 126.936
  Epoch 7/60
Model trained in 2.63s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 119.978
  Epoch 8/60
Model trained in 2.63s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 115.916
  Epoch 9/60
Model trained in 2.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 110.366
  Epoch 10/60
Model trained in 2.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 105.436
  Epoch 11/60
Model trained in 2.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 100.450
  Epoch 12/60
Model trained in 2.67s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 95.649
  Epoch 13/60
Model trained in 2.67s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 91.343
  Epoch 14/60
Model trained in 2.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.388
  Epoch 15/60
Model trained in 2.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.471
  Epoch 16/60
Model trained in 2.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.224
  Epoch 17/60
Model trained in 2.67s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.948
  Epoch 18/60
Model trained in 2.62s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.043
  Epoch 19/60
Model trained in 2.67s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.296
  Epoch 20/60
Model trained in 2.63s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.241
  Epoch 21/60
Model trained in 2.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.036
  Epoch 22/60
Model trained in 2.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.720
  Epoch 23/60
Model trained in 2.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.057
  Epoch 24/60
Model trained in 2.60s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.191
  Epoch 25/60
Model trained in 2.62s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.065
  Epoch 26/60
Model trained in 2.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.605
  Epoch 27/60
Model trained in 2.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.046
  Epoch 28/60
Model trained in 2.57s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.609
  Epoch 29/60
Model trained in 2.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.612
  Epoch 30/60
Model trained in 2.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.003
  Epoch 31/60
Model trained in 2.62s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.359
  Epoch 32/60
Model trained in 2.65s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.672
  Epoch 33/60
Model trained in 2.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.716
  Epoch 34/60
Model trained in 2.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.513
  Epoch 35/60
Model trained in 2.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.479
  Epoch 36/60
Model trained in 2.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.234
  Epoch 37/60
Model trained in 2.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.020
  Epoch 38/60
Model trained in 2.61s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.054
  Epoch 39/60
Model trained in 2.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.168
  Epoch 40/60
Model trained in 2.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.260
  Epoch 41/60
Model trained in 2.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.417
  Epoch 42/60
Model trained in 2.67s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.069
  Epoch 43/60
Model trained in 2.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.842
  Epoch 44/60
Model trained in 2.63s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.611
  Epoch 45/60
Model trained in 2.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.505
  Epoch 46/60
Model trained in 2.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.782
  Epoch 47/60
Model trained in 2.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.919
  Epoch 48/60
Model trained in 2.68s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.632
  Epoch 49/60
Model trained in 2.58s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.599
  Epoch 50/60
Model trained in 2.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.772
  Epoch 51/60
Model trained in 2.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.911
  Epoch 52/60
Model trained in 2.58s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.116
  Epoch 53/60
Model trained in 2.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.614
  Epoch 54/60
Model trained in 2.58s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.708
  Epoch 55/60
Model trained in 2.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.949
  Epoch 56/60
Model trained in 2.61s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.932
  Epoch 57/60
Model trained in 2.63s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.968
  Epoch 58/60
Model trained in 2.63s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.926
  Epoch 59/60
Model trained in 2.61s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.849
  Epoch 60/60
Model trained in 2.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.513

  best_val_SMAPE=74.505

Combination 1150/1152: {'encoder_hidden_size': 48, 'encoder_layers': 2, 'encoder_dropout': 0.2, 'decoder_hidden_size': 48, 'decoder_layers': 2, 'decoder_dropout': 0.2, 'learning_rate': 0.0005, 'max_epochs': 60, 'patience': 20, 'batch_size': 32, 'sequence_length': 168}
Time: 626.03 minutes - estimated total time: 627.12 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 2.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 174.520
  Epoch 2/60
Model trained in 2.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 162.079
  Epoch 3/60
Model trained in 2.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 151.416
  Epoch 4/60
Model trained in 2.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 142.435
  Epoch 5/60
Model trained in 2.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 134.468
  Epoch 6/60
Model trained in 2.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 128.949
  Epoch 7/60
Model trained in 2.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 123.595
  Epoch 8/60
Model trained in 2.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 118.077
  Epoch 9/60
Model trained in 2.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 113.934
  Epoch 10/60
Model trained in 2.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 109.282
  Epoch 11/60
Model trained in 2.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 104.651
  Epoch 12/60
Model trained in 2.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 100.972
  Epoch 13/60
Model trained in 2.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 97.830
  Epoch 14/60
Model trained in 2.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.946
  Epoch 15/60
Model trained in 2.73s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.262
  Epoch 16/60
Model trained in 2.59s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.806
  Epoch 17/60
Model trained in 2.67s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.186
  Epoch 18/60
Model trained in 2.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.439
  Epoch 19/60
Model trained in 2.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.052
  Epoch 20/60
Model trained in 2.65s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.191
  Epoch 21/60
Model trained in 2.57s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.739
  Epoch 22/60
Model trained in 2.62s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.605
  Epoch 23/60
Model trained in 2.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.331
  Epoch 24/60
Model trained in 2.74s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.159
  Epoch 25/60
Model trained in 2.65s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.394
  Epoch 26/60
Model trained in 2.61s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.886
  Epoch 27/60
Model trained in 2.67s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.859
  Epoch 28/60
Model trained in 2.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.291
  Epoch 29/60
Model trained in 2.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.487
  Epoch 30/60
Model trained in 2.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.520
  Epoch 31/60
Model trained in 2.63s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.097
  Epoch 32/60
Model trained in 2.67s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.344
  Epoch 33/60
Model trained in 2.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.516
  Epoch 34/60
Model trained in 2.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 72.952
  Epoch 35/60
Model trained in 2.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.268
  Epoch 36/60
Model trained in 2.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.357
  Epoch 37/60
Model trained in 2.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.994
  Epoch 38/60
Model trained in 2.95s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.491
  Epoch 39/60
Model trained in 2.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.875
  Epoch 40/60
Model trained in 2.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.787
  Epoch 41/60
Model trained in 2.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.734
  Epoch 42/60
Model trained in 2.68s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.929
  Epoch 43/60
Model trained in 2.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.662
  Epoch 44/60
Model trained in 2.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.262
  Epoch 45/60
Model trained in 2.68s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.746
  Epoch 46/60
Model trained in 2.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.181
  Epoch 47/60
Model trained in 2.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.701
  Epoch 48/60
Model trained in 2.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.359
  Epoch 49/60
Model trained in 2.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.297
  Epoch 50/60
Model trained in 2.56s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.373
  Epoch 51/60
Model trained in 2.68s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.391
  Epoch 52/60
Model trained in 2.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.016
  Epoch 53/60
Model trained in 2.65s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.364
  Epoch 54/60
Model trained in 2.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.492
  Early stopping triggered.

  best_val_SMAPE=72.952

Combination 1151/1152: {'encoder_hidden_size': 48, 'encoder_layers': 2, 'encoder_dropout': 0.2, 'decoder_hidden_size': 48, 'decoder_layers': 2, 'decoder_dropout': 0.2, 'learning_rate': 0.0005, 'max_epochs': 60, 'patience': 20, 'batch_size': 64, 'sequence_length': 24}
Time: 628.92 minutes - estimated total time: 629.47 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 1.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 182.099
  Epoch 2/60
Model trained in 1.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 174.118
  Epoch 3/60
Model trained in 1.59s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 167.464
  Epoch 4/60
Model trained in 1.65s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 161.540
  Epoch 5/60
Model trained in 1.63s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 156.208
  Epoch 6/60
Model trained in 1.72s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 151.301
  Epoch 7/60
Model trained in 1.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 146.758
  Epoch 8/60
Model trained in 1.65s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 142.467
  Epoch 9/60
Model trained in 1.63s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 138.429
  Epoch 10/60
Model trained in 1.60s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 134.582
  Epoch 11/60
Model trained in 1.68s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 130.841
  Epoch 12/60
Model trained in 1.59s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 127.213
  Epoch 13/60
Model trained in 1.58s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 123.713
  Epoch 14/60
Model trained in 1.65s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 122.494
  Epoch 15/60
Model trained in 1.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 120.674
  Epoch 16/60
Model trained in 1.68s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 117.914
  Epoch 17/60
Model trained in 1.68s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 115.402
  Epoch 18/60
Model trained in 1.59s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 113.395
  Epoch 19/60
Model trained in 1.60s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 111.151
  Epoch 20/60
Model trained in 1.63s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 109.485
  Epoch 21/60
Model trained in 1.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 107.652
  Epoch 22/60
Model trained in 1.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 106.059
  Epoch 23/60
Model trained in 1.65s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 104.752
  Epoch 24/60
Model trained in 1.67s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 102.122
  Epoch 25/60
Model trained in 1.65s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 100.276
  Epoch 26/60
Model trained in 1.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 98.092
  Epoch 27/60
Model trained in 1.68s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 96.209
  Epoch 28/60
Model trained in 1.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 94.481
  Epoch 29/60
Model trained in 1.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.325
  Epoch 30/60
Model trained in 1.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.055
  Epoch 31/60
Model trained in 1.60s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.392
  Epoch 32/60
Model trained in 1.55s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.929
  Epoch 33/60
Model trained in 1.61s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.150
  Epoch 34/60
Model trained in 1.56s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.918
  Epoch 35/60
Model trained in 1.63s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.171
  Epoch 36/60
Model trained in 1.56s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.642
  Epoch 37/60
Model trained in 1.62s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.492
  Epoch 38/60
Model trained in 1.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.456
  Epoch 39/60
Model trained in 1.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.749
  Epoch 40/60
Model trained in 1.65s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.211
  Epoch 41/60
Model trained in 1.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.319
  Epoch 42/60
Model trained in 1.69s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.705
  Epoch 43/60
Model trained in 1.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.695
  Epoch 44/60
Model trained in 1.67s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.017
  Epoch 45/60
Model trained in 1.64s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.527
  Epoch 46/60
Model trained in 1.65s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.506
  Epoch 47/60
Model trained in 1.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.994
  Epoch 48/60
Model trained in 1.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.054
  Epoch 49/60
Model trained in 1.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.267
  Epoch 50/60
Model trained in 1.70s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.049
  Epoch 51/60
Model trained in 2.01s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.882
  Epoch 52/60
Model trained in 1.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.707
  Epoch 53/60
Model trained in 1.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.035
  Epoch 54/60
Model trained in 1.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.319
  Epoch 55/60
Model trained in 1.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.195
  Epoch 56/60
Model trained in 1.66s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.935
  Epoch 57/60
Model trained in 1.68s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 88.153
  Epoch 58/60
Model trained in 1.71s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.577
  Epoch 59/60
Model trained in 1.67s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 86.761
  Epoch 60/60
Model trained in 1.78s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.238
  Early stopping triggered.

  best_val_SMAPE=80.211

Combination 1152/1152: {'encoder_hidden_size': 48, 'encoder_layers': 2, 'encoder_dropout': 0.2, 'decoder_hidden_size': 48, 'decoder_layers': 2, 'decoder_dropout': 0.2, 'learning_rate': 0.0005, 'max_epochs': 60, 'patience': 20, 'batch_size': 64, 'sequence_length': 168}
Time: 631.09 minutes - estimated total time: 631.09 minutes

INCLUDE_REMAINING_2024_DURING_TRAINING: True
Number of input features (decoder): 33
All input columns: ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
  Epoch 1/60
Model trained in 1.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 182.184
  Epoch 2/60
Model trained in 1.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 174.472
  Epoch 3/60
Model trained in 1.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 167.826
  Epoch 4/60
Model trained in 1.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 161.836
  Epoch 5/60
Model trained in 1.95s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 156.488
  Epoch 6/60
Model trained in 1.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 151.582
  Epoch 7/60
Model trained in 1.97s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 147.046
  Epoch 8/60
Model trained in 1.95s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 142.762
  Epoch 9/60
Model trained in 1.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 138.734
  Epoch 10/60
Model trained in 1.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 134.899
  Epoch 11/60
Model trained in 1.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 131.174
  Epoch 12/60
Model trained in 1.75s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 127.557
  Epoch 13/60
Model trained in 1.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 123.835
  Epoch 14/60
Model trained in 1.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 120.385
  Epoch 15/60
Model trained in 1.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 117.691
  Epoch 16/60
Model trained in 1.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 115.903
  Epoch 17/60
Model trained in 1.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 114.957
  Epoch 18/60
Model trained in 1.94s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 112.701
  Epoch 19/60
Model trained in 1.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 111.314
  Epoch 20/60
Model trained in 1.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 109.186
  Epoch 21/60
Model trained in 1.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 107.035
  Epoch 22/60
Model trained in 1.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 104.651
  Epoch 23/60
Model trained in 1.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 101.606
  Epoch 24/60
Model trained in 1.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 99.276
  Epoch 25/60
Model trained in 1.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 96.376
  Epoch 26/60
Model trained in 1.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 93.932
  Epoch 27/60
Model trained in 1.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.064
  Epoch 28/60
Model trained in 1.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.364
  Epoch 29/60
Model trained in 1.77s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.158
  Epoch 30/60
Model trained in 1.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.338
  Epoch 31/60
Model trained in 1.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.871
  Epoch 32/60
Model trained in 1.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.318
  Epoch 33/60
Model trained in 1.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 84.111
  Epoch 34/60
Model trained in 1.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.899
  Epoch 35/60
Model trained in 1.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.906
  Epoch 36/60
Model trained in 1.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.768
  Epoch 37/60
Model trained in 1.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.695
  Epoch 38/60
Model trained in 1.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.936
  Epoch 39/60
Model trained in 1.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.778
  Epoch 40/60
Model trained in 1.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.464
  Epoch 41/60
Model trained in 1.76s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.025
  Epoch 42/60
Model trained in 1.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.658
  Epoch 43/60
Model trained in 1.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.032
  Epoch 44/60
Model trained in 1.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.005
  Epoch 45/60
Model trained in 1.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.303
  Epoch 46/60
Model trained in 1.99s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.513
  Epoch 47/60
Model trained in 1.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.760
  Epoch 48/60
Model trained in 1.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.629
  Epoch 49/60
Model trained in 1.92s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.881
  Epoch 50/60
Model trained in 1.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 80.104
  Epoch 51/60
Model trained in 1.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.405
  Epoch 52/60
Model trained in 1.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.737
  Epoch 53/60
Model trained in 1.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.675
  Epoch 54/60
Model trained in 1.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.375
  Epoch 55/60
Model trained in 1.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.154
  Epoch 56/60
Model trained in 1.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.614
  Epoch 57/60
Model trained in 1.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.892
  Epoch 58/60
Model trained in 1.93s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.843
  Epoch 59/60
Model trained in 1.80s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.979
  Epoch 60/60
Model trained in 1.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.647

  best_val_SMAPE=74.892

Results saved to: c:\Users\n_and\OneDrive\Delt skrivebord\Data Science\Speciale\Energinet\Delte scripts\Speciale_Kode\Deep learners\LSTM Autoencoder\DK1_lstm_ae_search_results_8.csv

,fe_latent_dim,fe_dense_layers,enc_hidden_size,enc_layers,dec_hidden_size,dec_layers,encoder_dropout,decoder_dropout,encoder_hidden_size,encoder_layers,...,avg_daily_rmse,avg_daily_mae,avg_daily_smape,avg_smape_day_1,avg_smape_day_2,avg_smape_day_3,avg_smape_day_4,avg_smape_day_5,avg_smape_day_6,avg_smape_day_7
63,33,1,48,1,33,2,0.0,0.2,48,1,...,233.993728,205.044191,68.837841,60.941239,48.434844,36.794525,55.528344,76.803061,94.376470,108.986405
160,33,1,48,2,48,2,0.0,0.2,48,2,...,232.750534,204.864227,68.857719,55.601017,51.144896,49.799734,60.918437,71.880909,87.859838,104.799201
183,33,1,48,2,28,2,0.2,0.2,48,2,...,243.989411,213.365855,69.349300,56.190351,46.909008,49.307671,61.950576,74.195430,95.298367,101.593696
200,33,1,48,2,33,2,0.2,0.0,48,2,...,230.872715,202.487436,69.456301,56.500368,47.154438,50.243984,62.226476,73.290539,93.433437,103.344866
27,33,1,48,1,28,2,0.0,0.0,48,1,...,233.503149,205.256079,69.601700,54.060409,49.170008,54.803715,64.591077,76.594323,93.783776,94.208591
14,33,1,33,2,48,2,0.2,0.2,33,2,...,219.511079,194.114962,69.935172,53.120496,58.482611,48.412412,64.922072,70.125448,91.987151,102.496017
123,33,1,48,2,33,2,0.0,0.0,48,2,...,232.608019,206.064398,70.228660,57.545835,48.470854,59.061968,62.554593,78.536894,91.030972,94.399502
227,33,1,48,2,48,2,0.2,0.2,48,2,...,234.172441,208.993245,70.685973,53.637871,47.696541,58.375840,68.357064,79.078838,90.395635,97.260020
66,33,1,48,1,33,2,0.0,0.2,48,1,...,243.703785,212.709159,71.145868,56.025862,50.841592,59.833862,68.256074,74.034276,94.293297,94.736115
103,33,1,48,2,28,2,0.0,0.0,48,2,...,246.966030,217.995827,71.368108,54.924754,48.925204,54.054278,63.880876,75.286934,94.647425,107.857283

## Train final model

In [7]:

import copy
import numpy as np
import pandas as pd
from pathlib import Path
import wandb
import tempfile
import joblib
from sklearn.preprocessing import StandardScaler
from Modules.Validation3_AE import run_cross_validation

# =====================================================================================
# Stage 3 – Train final LSTM Autoencoder
#
# Parameters are taken from the best Stage 2 row (results_df).
# The pretrained feature encoder from Stage 1 is loaded UNFROZEN so all weights
# can fine-tune together end-to-end.
# =====================================================================================

# ---------------------------------------------------------------------------
# Load Stage 1 checkpoint from disk if not already in memory
# (allows resuming Stage 2 after a kernel restart)
# ---------------------------------------------------------------------------
_stage1_ckpt_path = Path(project_root) / "Deep learners" / "LSTM Autoencoder" / f"{PRICE_ZONE}_best_stage1_checkpoint.pt"

if not ("best_stage1_encoder_state_dict" in globals() and best_stage1_encoder_state_dict is not None):
    if _stage1_ckpt_path.exists():
        _ckpt = torch.load(_stage1_ckpt_path, map_location="cpu")
        best_stage1_encoder_state_dict = _ckpt["encoder_state_dict"]
        best_stage1_params             = _ckpt["params"]
        best_stage1_val_smape          = _ckpt["val_smape"]
        print(f"Loaded Stage 1 checkpoint from disk: {_stage1_ckpt_path}")
        print(f"  best_stage1_params   : {best_stage1_params}")
        print(f"  best_stage1_val_smape: {best_stage1_val_smape:.4f}")
    else:
        print(f"WARNING: No Stage 1 checkpoint found at {_stage1_ckpt_path}. Run Stage 1 first.")
else:
    print(f"Stage 1 results already in memory (val SMAPE={best_stage1_val_smape:.4f}). Skipping disk load.")


# ---------------------------------------------------------------------------
# Validate prerequisites
# ---------------------------------------------------------------------------
required_globals = [
    "dataset_train", "dataset_train_input", "dataset_validation",
    "dataset_context", "INCLUDE_REMAINING_2024_DURING_TRAINING",
    "INCLUDE_LAGS", "USE_FORECASTED_HISTORY",
    # "results_df",                          # Stage 2 search results
    "best_stage1_encoder_state_dict",      # pretrained encoder weights from Stage 1
    "best_stage1_params",                  # Stage 1 best latent_dim / dense_layers
]
missing_globals = [name for name in required_globals if name not in globals()]
if missing_globals:
    raise ValueError(
        f"Missing prerequisites – run Stage 1 and Stage 2 first. "
        f"Missing: {missing_globals}"
    )

if dataset_train.empty:
    raise ValueError("Prepared dataset_train is empty; cannot train final model.")
if dataset_validation.empty:
    raise ValueError("dataset_validation is empty; cannot run final training with early stopping.")
if best_stage1_encoder_state_dict is None:
    raise ValueError("best_stage1_encoder_state_dict is None. Re-run Stage 1.")

# ---------------------------------------------------------------------------
# Derive parameters from the best Stage 2 row
# ---------------------------------------------------------------------------
# best_stage2_row = results_df.iloc[0]

params = {
    # Feature encoder shape – fixed from Stage 1
    "latent_dim":            int(best_stage1_params["latent_dim"]),
    "dense_layers":          int(best_stage1_params["dense_layers"]),
    # LSTM / training – from Stage 2 best
    "encoder_hidden_size":  28, # int(best_stage2_row["encoder_hidden_size"]),
    "decoder_hidden_size":  48, # int(best_stage2_row["decoder_hidden_size"]),
    "encoder_layers":       2, # int(best_stage2_row["encoder_layers"] if "encoder_layers" in best_stage2_row else best_stage2_row["layers"]),
    "decoder_layers":       2, # int(best_stage2_row["decoder_layers"] if "decoder_layers" in best_stage2_row else best_stage2_row["layers"]),
    "learning_rate":        0.0005, # float(best_stage2_row["learning_rate"]),
    "batch_size":           64, # int(best_stage2_row["batch_size"]),
    "sequence_length":      24, # int(best_stage2_row["sequence_length"]),
    "encoder_dropout":      0.0, # float(best_stage2_row["encoder_dropout"] if "encoder_dropout" in best_stage2_row else best_stage2_row["dropout"]),
    "decoder_dropout":      0.2, # float(best_stage2_row["decoder_dropout"] if "decoder_dropout" in best_stage2_row else best_stage2_row["dropout"]),
}

print("=== Stage 3 parameters (derived from Stage 1 + Stage 2 best) ===")
for k, v in params.items():
    print(f"  {k}: {v}")
# print(f"  (Stage 2 best avg_smape: {float(best_stage2_row['avg_smape']):.4f})")

# ---------------------------------------------------------------------------
# Config
# ---------------------------------------------------------------------------
PREDICT_PERIOD = 4 * 168
MAX_EPOCHS = 80
PATIENCE = 30
MIN_DELTA = 0.0
WANDB_PROJECT = "LSTM_AE_final"
WANDB_RUN_NAME = (
    f"{PRICE_ZONE}_LSTM_AE_{TRAIN_WINDOW//8760}y_"
    f"2024{'incl' if INCLUDE_REMAINING_2024_DURING_TRAINING else 'excl'}"
    f"_Lag1{'_incl' if INCLUDE_PRICE_LAG1_AS_INPUT else '_excl'}"
    f"_lags{'_incl' if INCLUDE_LAGS else '_excl'}"
    f"_{PREDICT_PERIOD//168}val"
    f"FE_lays1_FE_LatDim33_EnHid28_DeHid48_EnDeLays2"
)
save_model_to_wandb = True
save_model_to_disk = False

feature_columns = [c for c in dataset_train_input.columns if c not in ["Time", "DKPrice"]]
if not feature_columns:
    raise ValueError("No feature columns found in dataset_train_input.")

output_root = Path(project_root) / "Deep learners" / "LSTM Autoencoder"
output_root.mkdir(parents=True, exist_ok=True)

# ---------------------------------------------------------------------------
# W&B run
# ---------------------------------------------------------------------------
run = wandb.init(
    project=WANDB_PROJECT,
    name=WANDB_RUN_NAME,
    config={
        "price_zone": PRICE_ZONE,
        "train_window": int(TRAIN_WINDOW),
        "training_rows": int(len(dataset_train)),
        "validation_rows": int(len(dataset_validation)),
        "train_start_time": str(dataset_train["Time"].min()),
        "train_end_time": str(dataset_train["Time"].max()),
        "val_start": VAL_START,
        "val_window": int(VAL_WINDOW),
        "predict_period": int(PREDICT_PERIOD),
        "stride": int(STRIDE),
        "include_remaining_2024_in_prepared_train_data": bool(INCLUDE_REMAINING_2024_DURING_TRAINING),
        "include_lags": bool(INCLUDE_LAGS),
        "use_forecasted_history": bool(USE_FORECASTED_HISTORY),
        "max_epochs": MAX_EPOCHS,
        "patience": PATIENCE,
        "min_delta": MIN_DELTA,
        "save_model_to_wandb": bool(save_model_to_wandb),
        "decoder_horizon": 168,
        "stage1_recon_smape": float(best_stage1_val_smape),
        "stage2_best_val_smape": 67.02, # float(best_stage2_row["avg_smape"]),
        "encoder_pretrained": True,
        "encoder_frozen": False,
        **params,
    },
    tags=["lstm-ae", "final-model", "early-stopping", "pretrained-encoder", "unfrozen-encoder"],
    reinit=True,
    settings=wandb.Settings(start_method="thread"),
)

print(f"\nTraining rows: {len(dataset_train)}")
print(f"Training window: {dataset_train['Time'].min()} -> {dataset_train['Time'].max()}")
print(f"Validation rows: {len(dataset_validation)}")
print(f"Include remainder_2024_for_train: {INCLUDE_REMAINING_2024_DURING_TRAINING}")
print(f"Include lag features: {INCLUDE_LAGS}")
print(f"Use forecasted history: {USE_FORECASTED_HISTORY}")
print(f"Feature columns (decoder, {len(feature_columns)}): {feature_columns}")

# ---------------------------------------------------------------------------
# Build model – load pretrained encoder UNFROZEN (freeze=False) so all weights
# fine-tune end-to-end during Stage 3.
# ---------------------------------------------------------------------------
model = TorchLSTMAERegressor(
    latent_dim=params["latent_dim"],
    encoder_hidden_size=params["encoder_hidden_size"],
    decoder_hidden_size=params["decoder_hidden_size"],
    encoder_layers=params["encoder_layers"],
    decoder_layers=params["decoder_layers"],
    dense_layers=params["dense_layers"],
    learning_rate=params["learning_rate"],
    epochs=1,
    batch_size=params["batch_size"],
    sequence_length=params["sequence_length"],
    encoder_dropout=params["encoder_dropout"],
    decoder_dropout=params["decoder_dropout"],
    dropout=0.0,
    random_state=42,
    log_epoch_metrics=True,
    log_prefix="final_",
    warm_start=True,
)

# Load pretrained encoder weights but keep them trainable (freeze=False)
model.set_pretrained_encoder(best_stage1_encoder_state_dict, freeze=False)

# ---------------------------------------------------------------------------
# Training loop with early stopping
# ---------------------------------------------------------------------------
best_val_smape = float("inf")
best_epoch = 0
patience_counter = 0
best_model = None
epoch_history = []

for epoch in range(1, MAX_EPOCHS + 1):
    print(f"\nEpoch {epoch}/{MAX_EPOCHS}")

    epoch_results = run_cross_validation(
        model=model,
        dataset_train=dataset_train,
        dataset_validation=dataset_validation,
        dataset_context=dataset_context,
        feature_columns=feature_columns,
        include_remaining_2024=INCLUDE_REMAINING_2024_DURING_TRAINING,
        dk_zone=PRICE_ZONE,
        split_setup=2,
        train_window=TRAIN_WINDOW,
        val_window=VAL_WINDOW,
        val_start=VAL_START,
        predict_period=PREDICT_PERIOD,
        stride=STRIDE,
        use_scaler=True,
        print_fold_results=False,
        plot=False,
        rf_models=rf_models,
        use_precomputed_feature_values=use_precomputed_feature_values,
        precomputed_feature_predictions=feature_predictions,
        use_forecasted_history=USE_FORECASTED_HISTORY,
    )

    train_mse = float(model.epoch_losses_[-1]) if hasattr(model, "epoch_losses_") else float("nan")
    train_smape = float(model.epoch_smapes_[-1]) if hasattr(model, "epoch_smapes_") else float("nan")
    val_smape = float(epoch_results["overall_avg_weekly_smape"])

    improved = val_smape < (best_val_smape - MIN_DELTA)
    if improved:
        best_val_smape = val_smape
        best_epoch = epoch
        patience_counter = 0
        best_model = copy.deepcopy(model)
        print(f"  Validation SMAPE improved: {val_smape:.4f} (best so far)")
    else:
        patience_counter += 1
        print(f"  Validation SMAPE: {val_smape:.4f} (patience {patience_counter}/{PATIENCE})")

    epoch_row = {
        "epoch": epoch,
        "train_MSE": train_mse,
        "train_SMAPE": train_smape,
        "val_SMAPE": val_smape,
        "best_val_SMAPE": best_val_smape,
        "patience_counter": int(patience_counter),
    }
    epoch_history.append(epoch_row)
    wandb.log(epoch_row)

    if patience_counter >= PATIENCE:
        print(f"\nEarly stopping triggered at epoch {epoch}. Best epoch: {best_epoch}.")
        break

if best_epoch == 0:
    raise RuntimeError("No valid epoch found during final training with early stopping.")

print(f"\n=== Stage 3 Training Complete ===")
print(f"Best epoch: {best_epoch}")
print(f"Best validation SMAPE: {best_val_smape:.4f}")

final_model = best_model

epoch_metrics_df = pd.DataFrame(epoch_history)
wandb.log({"final_epoch_metrics": wandb.Table(dataframe=epoch_metrics_df)})
wandb.log({
    "best_epoch": int(best_epoch),
    "best_val_smape": float(best_val_smape),
})
run.summary.update({
    "best_epoch": int(best_epoch),
    "best_val_smape": float(best_val_smape),
    "epochs_trained": int(epoch),
})

if save_model_to_wandb:
    model_artifact = wandb.Artifact(name=f"{WANDB_RUN_NAME}_model", type="model")
    with tempfile.TemporaryDirectory() as tmpdir:
        model_path = Path(tmpdir) / f"{WANDB_RUN_NAME}_model.joblib"
        joblib.dump(final_model, model_path, compress=3)
        model_artifact.add_file(str(model_path), name="model.joblib")
        run.log_artifact(model_artifact)
    print("Model stored in W&B artifact.")
else:
    print("Model not saved to W&B. Set save_model_to_wandb = True to upload it.")

print(f"Trained final LSTM AE on the prepared {PRICE_ZONE} train set (best epoch: {best_epoch}).")

wandb.finish()

wandb: WARNING `start_method` is deprecated and will be removed in a future version of wandb. This setting is currently non-functional and safely ignored.

Stage 1 results already in memory (val SMAPE=16.8601). Skipping disk load.
=== Stage 3 parameters (derived from Stage 1 + Stage 2 best) ===
  latent_dim: 33
  dense_layers: 1
  encoder_hidden_size: 28
  decoder_hidden_size: 48
  encoder_layers: 2
  decoder_layers: 2
  learning_rate: 0.0005
  batch_size: 64
  sequence_length: 24
  encoder_dropout: 0.0
  decoder_dropout: 0.2

wandb: Currently logged in as: nande24 (Energinet_speciale) to https://api.wandb.ai. Use `wandb login --relogin` to force relogin
wandb: WARNING Using a boolean value for 'reinit' is deprecated. Use 'return_previous' or 'finish_previous' instead.

Training rows: 22944
Training window: 2022-01-01 00:00:00 -> 2024-12-31 23:00:00
Validation rows: 2688
Include remainder_2024_for_train: True
Include lag features: False
Use forecasted history: True
Feature columns (decoder, 33): ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']

Epoch 1/80
Model trained in 3.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 184.179
  Validation SMAPE improved: 184.1790 (best so far)

Epoch 2/80
Model trained in 1.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 176.868
  Validation SMAPE improved: 176.8680 (best so far)

Epoch 3/80
Model trained in 1.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 170.427
  Validation SMAPE improved: 170.4270 (best so far)

Epoch 4/80
Model trained in 1.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 164.592
  Validation SMAPE improved: 164.5917 (best so far)

Epoch 5/80
Model trained in 1.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 159.268
  Validation SMAPE improved: 159.2676 (best so far)

Epoch 6/80
Model trained in 1.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 154.267
  Validation SMAPE improved: 154.2666 (best so far)

Epoch 7/80
Model trained in 2.10s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 149.489
  Validation SMAPE improved: 149.4895 (best so far)

Epoch 8/80
Model trained in 2.07s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 145.020
  Validation SMAPE improved: 145.0204 (best so far)

Epoch 9/80
Model trained in 2.07s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 140.831
  Validation SMAPE improved: 140.8309 (best so far)

Epoch 10/80
Model trained in 1.91s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 136.776
  Validation SMAPE improved: 136.7765 (best so far)

Epoch 11/80
Model trained in 2.05s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 132.824
  Validation SMAPE improved: 132.8237 (best so far)

Epoch 12/80
Model trained in 1.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 129.118
  Validation SMAPE improved: 129.1184 (best so far)

Epoch 13/80
Model trained in 1.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 125.443
  Validation SMAPE improved: 125.4433 (best so far)

Epoch 14/80
Model trained in 2.01s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 122.229
  Validation SMAPE improved: 122.2287 (best so far)

Epoch 15/80
Model trained in 1.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 119.611
  Validation SMAPE improved: 119.6105 (best so far)

Epoch 16/80
Model trained in 1.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 116.697
  Validation SMAPE improved: 116.6969 (best so far)

Epoch 17/80
Model trained in 1.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 114.187
  Validation SMAPE improved: 114.1868 (best so far)

Epoch 18/80
Model trained in 1.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 111.490
  Validation SMAPE improved: 111.4904 (best so far)

Epoch 19/80
Model trained in 1.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 108.853
  Validation SMAPE improved: 108.8534 (best so far)

Epoch 20/80
Model trained in 1.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 106.637
  Validation SMAPE improved: 106.6373 (best so far)

Epoch 21/80
Model trained in 1.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 104.925
  Validation SMAPE improved: 104.9251 (best so far)

Epoch 22/80
Model trained in 1.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 102.546
  Validation SMAPE improved: 102.5460 (best so far)

Epoch 23/80
Model trained in 1.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 100.061
  Validation SMAPE improved: 100.0606 (best so far)

Epoch 24/80
Model trained in 1.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 97.823
  Validation SMAPE improved: 97.8228 (best so far)

Epoch 25/80
Model trained in 1.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 95.193
  Validation SMAPE improved: 95.1929 (best so far)

Epoch 26/80
Model trained in 1.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 92.870
  Validation SMAPE improved: 92.8702 (best so far)

Epoch 27/80
Model trained in 1.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 90.733
  Validation SMAPE improved: 90.7327 (best so far)

Epoch 28/80
Model trained in 1.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 89.146
  Validation SMAPE improved: 89.1465 (best so far)

Epoch 29/80
Model trained in 1.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 87.436
  Validation SMAPE improved: 87.4361 (best so far)

Epoch 30/80
Model trained in 1.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 85.801
  Validation SMAPE improved: 85.8008 (best so far)

Epoch 31/80
Model trained in 1.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 83.883
  Validation SMAPE improved: 83.8832 (best so far)

Epoch 32/80
Model trained in 1.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 82.543
  Validation SMAPE improved: 82.5431 (best so far)

Epoch 33/80
Model trained in 1.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 81.433
  Validation SMAPE improved: 81.4327 (best so far)

Epoch 34/80
Model trained in 1.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 79.901
  Validation SMAPE improved: 79.9010 (best so far)

Epoch 35/80
Model trained in 1.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 78.503
  Validation SMAPE improved: 78.5032 (best so far)

Epoch 36/80
Model trained in 1.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 77.569
  Validation SMAPE improved: 77.5692 (best so far)

Epoch 37/80
Model trained in 1.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 76.297
  Validation SMAPE improved: 76.2971 (best so far)

Epoch 38/80
Model trained in 1.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 75.201
  Validation SMAPE improved: 75.2011 (best so far)

Epoch 39/80
Model trained in 1.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 74.216
  Validation SMAPE improved: 74.2157 (best so far)

Epoch 40/80
Model trained in 1.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 73.203
  Validation SMAPE improved: 73.2034 (best so far)

Epoch 41/80
Model trained in 1.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 72.307
  Validation SMAPE improved: 72.3072 (best so far)

Epoch 42/80
Model trained in 1.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 71.360
  Validation SMAPE improved: 71.3603 (best so far)

Epoch 43/80
Model trained in 1.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 70.696
  Validation SMAPE improved: 70.6963 (best so far)

Epoch 44/80
Model trained in 1.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 70.235
  Validation SMAPE improved: 70.2351 (best so far)

Epoch 45/80
Model trained in 1.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 69.503
  Validation SMAPE improved: 69.5026 (best so far)

Epoch 46/80
Model trained in 1.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 68.689
  Validation SMAPE improved: 68.6886 (best so far)

Epoch 47/80
Model trained in 1.81s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 68.461
  Validation SMAPE improved: 68.4611 (best so far)

Epoch 48/80
Model trained in 1.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 68.142
  Validation SMAPE improved: 68.1424 (best so far)

Epoch 49/80
Model trained in 1.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 67.907
  Validation SMAPE improved: 67.9071 (best so far)

Epoch 50/80
Model trained in 1.82s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 67.657
  Validation SMAPE improved: 67.6570 (best so far)

Epoch 51/80
Model trained in 1.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 67.239
  Validation SMAPE improved: 67.2393 (best so far)

Epoch 52/80
Model trained in 1.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 66.937
  Validation SMAPE improved: 66.9368 (best so far)

Epoch 53/80
Model trained in 1.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 67.052
  Validation SMAPE: 67.0520 (patience 1/30)

Epoch 54/80
Model trained in 1.79s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 67.510
  Validation SMAPE: 67.5098 (patience 2/30)

Epoch 55/80
Model trained in 1.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 67.733
  Validation SMAPE: 67.7330 (patience 3/30)

Epoch 56/80
Model trained in 1.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 67.909
  Validation SMAPE: 67.9086 (patience 4/30)

Epoch 57/80
Model trained in 1.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 68.021
  Validation SMAPE: 68.0214 (patience 5/30)

Epoch 58/80
Model trained in 1.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 68.464
  Validation SMAPE: 68.4635 (patience 6/30)

Epoch 59/80
Model trained in 1.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 68.656
  Validation SMAPE: 68.6560 (patience 7/30)

Epoch 60/80
Model trained in 1.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 69.366
  Validation SMAPE: 69.3665 (patience 8/30)

Epoch 61/80
Model trained in 2.02s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 69.884
  Validation SMAPE: 69.8836 (patience 9/30)

Epoch 62/80
Model trained in 1.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 70.266
  Validation SMAPE: 70.2661 (patience 10/30)

Epoch 63/80
Model trained in 2.01s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 70.329
  Validation SMAPE: 70.3289 (patience 11/30)

Epoch 64/80
Model trained in 1.84s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 70.683
  Validation SMAPE: 70.6834 (patience 12/30)

Epoch 65/80
Model trained in 1.98s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 70.406
  Validation SMAPE: 70.4061 (patience 13/30)

Epoch 66/80
Model trained in 1.99s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 70.187
  Validation SMAPE: 70.1870 (patience 14/30)

Epoch 67/80
Model trained in 2.06s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 70.530
  Validation SMAPE: 70.5298 (patience 15/30)

Epoch 68/80
Model trained in 1.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 70.746
  Validation SMAPE: 70.7456 (patience 16/30)

Epoch 69/80
Model trained in 1.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 71.164
  Validation SMAPE: 71.1639 (patience 17/30)

Epoch 70/80
Model trained in 1.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 71.642
  Validation SMAPE: 71.6419 (patience 18/30)

Epoch 71/80
Model trained in 1.95s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 71.810
  Validation SMAPE: 71.8099 (patience 19/30)

Epoch 72/80
Model trained in 1.87s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 72.097
  Validation SMAPE: 72.0970 (patience 20/30)

Epoch 73/80
Model trained in 1.89s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 72.096
  Validation SMAPE: 72.0957 (patience 21/30)

Epoch 74/80
Model trained in 1.83s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 72.095
  Validation SMAPE: 72.0949 (patience 22/30)

Epoch 75/80

C:\Users\n_and\AppData\Local\Temp\ipykernel_25872\3103432539.py:17: RuntimeWarning: invalid value encountered in divide
  vals = np.where(denom == 0, 0.0, 200.0 * np.abs(y_pred - y_true) / denom)

Model trained in 1.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 72.221
  Validation SMAPE: 72.2205 (patience 23/30)

Epoch 76/80
Model trained in 1.90s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 72.379
  Validation SMAPE: 72.3789 (patience 24/30)

Epoch 77/80
Model trained in 1.88s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 72.410
  Validation SMAPE: 72.4098 (patience 25/30)

Epoch 78/80
Model trained in 1.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 72.495
  Validation SMAPE: 72.4951 (patience 26/30)

Epoch 79/80
Model trained in 1.85s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 72.745
  Validation SMAPE: 72.7450 (patience 27/30)

Epoch 80/80
Model trained in 1.86s. Now validating on 4 folds...

Average SMAPE across all weeks in all folds: 72.398
  Validation SMAPE: 72.3982 (patience 28/30)

=== Stage 3 Training Complete ===
Best epoch: 52
Best validation SMAPE: 66.9368
Model stored in W&B artifact.
Trained final LSTM AE on the prepared DK1 train set (best epoch: 52).

Test Final Model

In [8]:

import numpy as np
import pandas as pd
from pathlib import Path
import wandb
import joblib
from sklearn.preprocessing import StandardScaler
from Modules.Validation3_AE import _build_validation_folds
from Modules.week_predictions2_AE import get_predictions

# =====================================================================================
# Test final LSTM Autoencoder on 2025 only, week-by-week (168h blocks)
# =====================================================================================
WANDB_PROJECT = "LSTM_AE_final"
WANDB_RUN_NAME = WANDB_RUN_NAME  # Must match final training run name
WANDB_TEST_RUN_NAME = f"{WANDB_RUN_NAME}_test"
WANDB_ARTIFACT_NAME = f"{WANDB_RUN_NAME}_model"

FORECAST_HORIZON = 168  # 1 week
PREDICT_PERIOD = 8760    # one week per validation fold
STRIDE = 168            # next fold starts next week
TEST_START = pd.Timestamp("2025-01-01 00:00:00")
TEST_WINDOW = 8760
TEST_END = TEST_START + pd.Timedelta(hours=TEST_WINDOW - 1)

# Retrieve zone data
if PRICE_ZONE == "DK1":
    test_source = DK1_test.copy() if "DK1_test" in globals() else None
    history_source = DK1_train.copy() if "DK1_train" in globals() else None
elif PRICE_ZONE == "DK2":
    test_source = DK2_test.copy() if "DK2_test" in globals() else None
    history_source = DK2_train.copy() if "DK2_train" in globals() else None
else:
    raise ValueError("PRICE_ZONE must be 'DK1' or 'DK2'.")

if test_source is None or history_source is None:
    raise ValueError(f"Missing train/test source data for {PRICE_ZONE}. Run data loading first.")

test_source = test_source.sort_values("Time").reset_index(drop=True)
history_source = history_source.sort_values("Time").reset_index(drop=True)

# Test only on 2025 window
test_set = test_source.loc[
    (test_source["Time"] >= TEST_START) & (test_source["Time"] <= TEST_END)
].copy().sort_values("Time").reset_index(drop=True)

if len(test_set) != TEST_WINDOW:
    raise ValueError(
        f"Expected exactly TEST_WINDOW={TEST_WINDOW} rows from {TEST_START} to {TEST_END}, got {len(test_set)}."
    )

# Feature columns: all columns except Time and DKPrice.
# DKPrice is fed directly into the encoder; it is not a feature column.
feature_columns = [c for c in dataset_train_input.columns if c not in ["Time", "DKPrice"]]
if not feature_columns:
    raise ValueError("No feature columns found in dataset_train_input. Run the load data cell first.")

# Build full eval dataset: include end-of-2024 history so the encoder can look back
# seq_len hours before the first 2025 prediction block.
full_eval_dataset = (
    pd.concat([history_source, test_set], ignore_index=True)
    .sort_values("Time")
    .drop_duplicates(subset=["Time"], keep="last")
    .reset_index(drop=True)
)

# DKPrice_lag1 is derived from Price_lag1 during training (INCLUDE_PRICE_LAG1_AS_INPUT).
# The raw source DataFrames store it as Price_lag1, so map it here if needed.
if INCLUDE_PRICE_LAG1_AS_INPUT and "DKPrice_lag1" not in full_eval_dataset.columns:
    if "Price_lag1" in full_eval_dataset.columns:
        full_eval_dataset["DKPrice_lag1"] = full_eval_dataset["Price_lag1"]
    else:
        full_eval_dataset["DKPrice_lag1"] = full_eval_dataset["DKPrice"].shift(1)

missing_in_eval = [c for c in feature_columns if c not in full_eval_dataset.columns]
if missing_in_eval:
    raise ValueError(f"full_eval_dataset is missing feature columns from dataset_train_input: {missing_in_eval}")

# DKPrice must be the first column so get_predictions treats it as the target
full_eval_dataset = full_eval_dataset[["DKPrice", "Time"] + feature_columns].copy()

# Initialize W&B run
try:
    wandb.finish()
except Exception:
    pass
test_run = wandb.init(
    project=WANDB_PROJECT,
    name=WANDB_TEST_RUN_NAME,
    job_type="evaluation",
    config={
        "price_zone": PRICE_ZONE,
        "test_start": str(TEST_START),
        "test_end": str(TEST_END),
        "test_window": int(TEST_WINDOW),
        "test_rows": int(len(test_set)),
        "model_artifact": WANDB_ARTIFACT_NAME,
        "forecast_horizon": int(FORECAST_HORIZON),
        "predict_period": int(PREDICT_PERIOD),
        "stride": int(STRIDE),
        "prediction_method": "weekly_168h_seq2seq",
    },
    tags=["lstm-ae", "final-model", "test", "evaluation", "weekly-metrics"],
    reinit=True,
    settings=wandb.Settings(start_method="thread"),
)

# Load trained model
model_artifact = test_run.use_artifact(f"{WANDB_ARTIFACT_NAME}:latest")
artifact_dir = Path(model_artifact.download())
model_path = artifact_dir / "model.joblib"
if not model_path.exists():
    raise ValueError(f"Could not find model.joblib in downloaded artifact: {artifact_dir}")

model = joblib.load(model_path)
print(f"Loaded model artifact: {WANDB_ARTIFACT_NAME}:latest")
print(f"Test window: {TEST_START} -> {TEST_END} ({len(test_set)} rows)")
print(f"Feature columns (decoder, {len(feature_columns)}): {feature_columns}")

# Fit scaler on the same training tail used during training.
train_for_scaler = history_source.sort_values("Time").copy()
train_for_scaler = train_for_scaler.tail(TRAIN_WINDOW).reset_index(drop=True)
# DKPrice_lag1 is stored as Price_lag1 in raw source DataFrames; rename to match feature_columns.
if "DKPrice_lag1" not in train_for_scaler.columns and "Price_lag1" in train_for_scaler.columns:
    train_for_scaler["DKPrice_lag1"] = train_for_scaler["Price_lag1"]
X_scaler = train_for_scaler[feature_columns].astype(np.float32)
scaler = StandardScaler()
scaler.fit(X_scaler)

# Build 2025 weekly folds
folds = _build_validation_folds(
    data=full_eval_dataset,
    val_window=TEST_WINDOW,
    val_start=str(TEST_START),
    predict_period=PREDICT_PERIOD,
    stride=STRIDE,
    validation_reference=test_set,
)
print(f"Generated {len(folds)} weekly folds with predict_period={PREDICT_PERIOD}, stride={STRIDE}.")

# Metric helper
def smape_mean(y_true: np.ndarray, y_pred: np.ndarray) -> float:
    denom = np.abs(y_true) + np.abs(y_pred)
    vals = np.where(denom == 0, 0.0, 200.0 * np.abs(y_pred - y_true) / denom)
    return float(np.mean(vals))

# Evaluate fold-by-fold (week-by-week)
all_week_evals = []
day_smapes_per_week = {}  # (fold_no, week_no) -> {day_num -> smape}

for fold in folds:
    fold_no = int(fold["fold"])
    fold_val_data = test_set.loc[
        (test_set["Time"] >= fold["val_start"]) & (test_set["Time"] <= fold["val_end"])
    ].copy()

    preds_by_week = get_predictions(
        model=model,
        dataset=full_eval_dataset,
        val_start=fold["val_start"],
        val_end=fold["val_end"],
        forecast_horizon=FORECAST_HORIZON,
        fitted_scaler=scaler,
        dk_zone=PRICE_ZONE,
        rf_models=rf_models if "rf_models" in globals() else None,
        use_precomputed_feature_values=use_precomputed_feature_values if "use_precomputed_feature_values" in globals() else False,
        precomputed_feature_predictions=feature_predictions if "feature_predictions" in globals() else None,
        use_forecasted_history=USE_FORECASTED_HISTORY,
    )

    for week_no, week_pred_df in preds_by_week.items():
        week_eval = week_pred_df.merge(
            fold_val_data[["Time", "DKPrice"]],
            on="Time",
            how="left",
        )
        week_eval = week_eval.dropna(subset=["DKPrice"]).copy()
        if week_eval.empty:
            continue

        week_eval["fold"] = fold_no
        week_eval["week_in_fold"] = int(week_no)
        all_week_evals.append(week_eval)

        week_key = (fold_no, int(week_no))
        day_smapes_per_week[week_key] = {}
        week_eval_sorted = week_eval.sort_values("Time").reset_index(drop=True)

        for day_num in range(1, 8):
            start_hour = (day_num - 1) * 24
            end_hour = day_num * 24
            day_data = week_eval_sorted.iloc[start_hour:end_hour]
            if len(day_data) > 0:
                day_smapes_per_week[week_key][day_num] = smape_mean(
                    day_data["DKPrice"].values,
                    day_data["Prediction"].values,
                )

if not all_week_evals:
    raise RuntimeError("No aligned predictions produced for 2025 weekly folds.")

results_df = pd.concat(all_week_evals, ignore_index=True).sort_values("Time").reset_index(drop=True)
results_df = results_df.rename(columns={"DKPrice": "Actual"})
results_df["Error"] = results_df["Actual"] - results_df["Prediction"]
results_df["Abs_Error"] = np.abs(results_df["Error"])

y_actual = results_df["Actual"].values
y_pred = results_df["Prediction"].values

# Overall metrics
overall_mse = float(np.mean((y_actual - y_pred) ** 2))
overall_smape = smape_mean(y_actual, y_pred)
overall_mae = float(np.mean(np.abs(y_actual - y_pred)))
overall_rmse = float(np.sqrt(overall_mse))

print("\n=== Overall Test Results ===")
print(f"MSE Loss:  {overall_mse:.6f}")
print(f"SMAPE:     {overall_smape:.6f}")
print(f"MAE:       {overall_mae:.6f}")
print(f"RMSE:      {overall_rmse:.6f}")

# Weekly metrics (calendar week)
print("\n=== Weekly Metrics ===")
results_df["Week"] = results_df["Time"].dt.isocalendar().week
weekly_results = []
for week, group in results_df.groupby("Week"):
    week_actual = group["Actual"].values
    week_pred = group["Prediction"].values
    week_rmse = float(np.sqrt(np.mean((week_actual - week_pred) ** 2)))
    week_mae = float(np.mean(np.abs(week_actual - week_pred)))
    week_smape = smape_mean(week_actual, week_pred)
    weekly_results.append({
        "week": int(week),
        "rmse": week_rmse,
        "mae": week_mae,
        "smape": week_smape,
        "n_samples": len(group),
    })
    print(f"Week {week:02d}: RMSE={week_rmse:.4f}, MAE={week_mae:.4f}, SMAPE={week_smape:.4f}")

# Daily metrics
print("\n=== Daily Metrics (by Date) ===")
results_df["Date"] = results_df["Time"].dt.date
daily_results = []
for date, group in results_df.groupby("Date"):
    day_actual = group["Actual"].values
    day_pred = group["Prediction"].values
    day_rmse = float(np.sqrt(np.mean((day_actual - day_pred) ** 2)))
    day_mae = float(np.mean(np.abs(day_actual - day_pred)))
    day_smape = smape_mean(day_actual, day_pred)
    daily_results.append({
        "date": str(date),
        "rmse": day_rmse,
        "mae": day_mae,
        "smape": day_smape,
        "n_samples": len(group),
    })
    print(f"{date}: RMSE={day_rmse:.4f}, MAE={day_mae:.4f}, SMAPE={day_smape:.4f}")

# Day-of-forecast metrics (Day 1..7 inside each predicted week)
print("\n=== Day-of-Forecast Metrics (within each 168-hour period) ===")
day_of_forecast_smapes = {}
for day_num in range(1, 8):
    smapes = [
        day_smapes_per_week[w].get(day_num)
        for w in day_smapes_per_week
        if day_num in day_smapes_per_week[w]
    ]
    smapes = [s for s in smapes if s is not None and not np.isnan(s)]
    day_of_forecast_smapes[day_num] = float(np.mean(smapes)) if smapes else float("nan")
    print(f"Day {day_num} (hours {(day_num-1)*24}-{day_num*24-1}): avg SMAPE={day_of_forecast_smapes[day_num]:.4f}")

# Average weekly/daily metrics
avg_weekly_rmse = float(np.mean([r["rmse"] for r in weekly_results]))
avg_weekly_mae = float(np.mean([r["mae"] for r in weekly_results]))
avg_weekly_smape = float(np.mean([r["smape"] for r in weekly_results]))

avg_daily_rmse = float(np.mean([r["rmse"] for r in daily_results]))
avg_daily_mae = float(np.mean([r["mae"] for r in daily_results]))
avg_daily_smape = float(np.mean([r["smape"] for r in daily_results]))

print("\n=== Average Weekly Metrics ===")
print(f"Avg Weekly RMSE: {avg_weekly_rmse:.6f}")
print(f"Avg Weekly MAE:  {avg_weekly_mae:.6f}")
print(f"Avg Weekly SMAPE: {avg_weekly_smape:.6f}")

print("\n=== Average Daily Metrics ===")
print(f"Avg Daily RMSE: {avg_daily_rmse:.6f}")
print(f"Avg Daily MAE:  {avg_daily_mae:.6f}")
print(f"Avg Daily SMAPE: {avg_daily_smape:.6f}")

# Save all hourly predictions to CSV
output_root = Path(project_root) / "Deep learners" / "LSTM Autoencoder"
output_root.mkdir(parents=True, exist_ok=True)
predictions_csv_path = output_root / f"{WANDB_RUN_NAME}_test_predictions.csv"
results_df.to_csv(predictions_csv_path, index=False, sep=";", decimal=".")
print(f"\nHourly predictions saved to: {predictions_csv_path}")

# Log metrics
test_run.log({
    "test_overall_MSE_loss": overall_mse,
    "test_overall_SMAPE": overall_smape,
    "test_overall_MAE": overall_mae,
    "test_overall_RMSE": overall_rmse,
    "test_avg_weekly_RMSE": avg_weekly_rmse,
    "test_avg_weekly_MAE": avg_weekly_mae,
    "test_avg_weekly_SMAPE": avg_weekly_smape,
    "test_avg_daily_RMSE": avg_daily_rmse,
    "test_avg_daily_MAE": avg_daily_mae,
    "test_avg_daily_SMAPE": avg_daily_smape,
    "test_avg_smape_day_1": day_of_forecast_smapes.get(1, float("nan")),
    "test_avg_smape_day_2": day_of_forecast_smapes.get(2, float("nan")),
    "test_avg_smape_day_3": day_of_forecast_smapes.get(3, float("nan")),
    "test_avg_smape_day_4": day_of_forecast_smapes.get(4, float("nan")),
    "test_avg_smape_day_5": day_of_forecast_smapes.get(5, float("nan")),
    "test_avg_smape_day_6": day_of_forecast_smapes.get(6, float("nan")),
    "test_avg_smape_day_7": day_of_forecast_smapes.get(7, float("nan")),
})

weekly_df = pd.DataFrame(weekly_results)
daily_df = pd.DataFrame(daily_results)
test_run.log({
    "test_weekly_metrics": wandb.Table(dataframe=weekly_df),
    "test_daily_metrics": wandb.Table(dataframe=daily_df),
    "test_predictions_sample": wandb.Table(dataframe=results_df.head(100)),
})

test_run.summary.update({
    "test_overall_MSE_loss": overall_mse,
    "test_overall_SMAPE": overall_smape,
    "test_overall_MAE": overall_mae,
    "test_overall_RMSE": overall_rmse,
    "test_avg_weekly_RMSE": avg_weekly_rmse,
    "test_avg_weekly_MAE": avg_weekly_mae,
    "test_avg_weekly_SMAPE": avg_weekly_smape,
    "test_avg_daily_RMSE": avg_daily_rmse,
    "test_avg_daily_MAE": avg_daily_mae,
    "test_avg_daily_SMAPE": avg_daily_smape,
    "test_samples": int(len(results_df)),
    "test_period_start": str(TEST_START),
    "test_period_end": str(TEST_END),
    "n_weeks": len(weekly_results),
    "n_days": len(daily_results),
})

print(f"\nTest predictions and metrics logged to W&B run: {WANDB_TEST_RUN_NAME}")
wandb.finish()

wandb:   1 of 1 files downloaded.
c:\Users\n_and\OneDrive\Delt skrivebord\Data Science\Speciale\Energinet\py_3.10_blackwell\lib\site-packages\torch\nn\modules\rnn.py:1141: UserWarning: RNN module weights are not part of single contiguous chunk of memory. This means they need to be compacted at every call, possibly greatly increasing memory usage. To compact weights again call flatten_parameters(). (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\cudnn\RNN.cpp:1480.)
  result = _VF.lstm(
c:\Users\n_and\OneDrive\Delt skrivebord\Data Science\Speciale\Energinet\py_3.10_blackwell\lib\site-packages\torch\nn\modules\rnn.py:1141: UserWarning: RNN module weights are not part of single contiguous chunk of memory. This means they need to be compacted at every call, possibly greatly increasing memory usage. To compact weights again call flatten_parameters(). (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\cudnn\RNN.cpp:1480.)
  result = _VF.lstm(

Loaded model artifact: DK1_LSTM_AE_2y_2024incl_Lag1_incl_lags_excl_4valFE_lays1_FE_LatDim33_EnHid28_DeHid48_EnDeLays2_model:latest
Test window: 2025-01-01 00:00:00 -> 2025-12-31 23:00:00 (8760 rows)
Feature columns (decoder, 33): ['OffshoreWindPower', 'OnshoreWindPower', 'HydroPower', 'SolarPower', 'Biomass', 'Biogas', 'Waste', 'FossilGas', 'FossilOil', 'FossilHardCoal', 'ExchangeGreatBelt', 'ExchangeGermany', 'ExchangeSweden', 'ExchangeNorway', 'ExchangeNetherlands', 'WindSpeed', 'Radiation', 'DEPrice', 'NO2Price', 'SE3Price', 'SE4Price', 'NLPrice', 'GrossCon', 'TotalProduction', 'Year', 'Month', 'Day', 'WeekDay', 'Hour', 'OffshoreWindCapacity', 'OnshoreWindCapacity', 'SolarPowerCapacity', 'DKPrice_lag1']
Generated 1 weekly folds with predict_period=8760, stride=168.

c:\Users\n_and\OneDrive\Delt skrivebord\Data Science\Speciale\Energinet\py_3.10_blackwell\lib\site-packages\torch\nn\modules\rnn.py:1141: UserWarning: RNN module weights are not part of single contiguous chunk of memory. This means they need to be compacted at every call, possibly greatly increasing memory usage. To compact weights again call flatten_parameters(). (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\cudnn\RNN.cpp:1480.)
  result = _VF.lstm(
c:\Users\n_and\OneDrive\Delt skrivebord\Data Science\Speciale\Energinet\py_3.10_blackwell\lib\site-packages\torch\nn\modules\rnn.py:1141: UserWarning: RNN module weights are not part of single contiguous chunk of memory. This means they need to be compacted at every call, possibly greatly increasing memory usage. To compact weights again call flatten_parameters(). (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\cudnn\RNN.cpp:1480.)
  result = _VF.lstm(
c:\Users\n_and\OneDrive\Delt skrivebord\Data Science\Speciale\Energinet\py_3.10_blackwell\lib\site-packages\torch\nn\modules\rnn.py:1141: UserWarning: RNN module weights are not part of single contiguous chunk of memory. This means they need to be compacted at every call, possibly greatly increasing memory usage. To compact weights again call flatten_parameters(). (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\cudnn\RNN.cpp:1480.)
  result = _VF.lstm(
c:\Users\n_and\OneDrive\Delt skrivebord\Data Science\Speciale\Energinet\py_3.10_blackwell\lib\site-packages\torch\nn\modules\rnn.py:1141: UserWarning: RNN module weights are not part of single contiguous chunk of memory. This means they need to be compacted at every call, possibly greatly increasing memory usage. To compact weights again call flatten_parameters(). (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\cudnn\RNN.cpp:1480.)
  result = _VF.lstm(
c:\Users\n_and\OneDrive\Delt skrivebord\Data Science\Speciale\Energinet\py_3.10_blackwell\lib\site-packages\torch\nn\modules\rnn.py:1141: UserWarning: RNN module weights are not part of single contiguous chunk of memory. This means they need to be compacted at every call, possibly greatly increasing memory usage. To compact weights again call flatten_parameters(). (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\cudnn\RNN.cpp:1480.)
  result = _VF.lstm(
c:\Users\n_and\OneDrive\Delt skrivebord\Data Science\Speciale\Energinet\py_3.10_blackwell\lib\site-packages\torch\nn\modules\rnn.py:1141: UserWarning: RNN module weights are not part of single contiguous chunk of memory. This means they need to be compacted at every call, possibly greatly increasing memory usage. To compact weights again call flatten_parameters(). (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\cudnn\RNN.cpp:1480.)
  result = _VF.lstm(
c:\Users\n_and\OneDrive\Delt skrivebord\Data Science\Speciale\Energinet\py_3.10_blackwell\lib\site-packages\torch\nn\modules\rnn.py:1141: UserWarning: RNN module weights are not part of single contiguous chunk of memory. This means they need to be compacted at every call, possibly greatly increasing memory usage. To compact weights again call flatten_parameters(). (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\cudnn\RNN.cpp:1480.)
  result = _VF.lstm(
c:\Users\n_and\OneDrive\Delt skrivebord\Data Science\Speciale\Energinet\py_3.10_blackwell\lib\site-packages\torch\nn\modules\rnn.py:1141: UserWarning: RNN module weights are not part of single contiguous chunk of memory. This means they need to be compacted at every call, possibly greatly increasing memory usage. To compact weights again call flatten_parameters(). (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\cudnn\RNN.cpp:1480.)
  result = _VF.lstm(
c:\Users\n_and\OneDrive\Delt skrivebord\Data Science\Speciale\Energinet\py_3.10_blackwell\lib\site-packages\torch\nn\modules\rnn.py:1141: UserWarning: RNN module weights are not part of single contiguous chunk of memory. This means they need to be compacted at every call, possibly greatly increasing memory usage. To compact weights again call flatten_parameters(). (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\cudnn\RNN.cpp:1480.)
  result = _VF.lstm(
c:\Users\n_and\OneDrive\Delt skrivebord\Data Science\Speciale\Energinet\py_3.10_blackwell\lib\site-packages\torch\nn\modules\rnn.py:1141: UserWarning: RNN module weights are not part of single contiguous chunk of memory. This means they need to be compacted at every call, possibly greatly increasing memory usage. To compact weights again call flatten_parameters(). (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\cudnn\RNN.cpp:1480.)
  result = _VF.lstm(
c:\Users\n_and\OneDrive\Delt skrivebord\Data Science\Speciale\Energinet\py_3.10_blackwell\lib\site-packages\torch\nn\modules\rnn.py:1141: UserWarning: RNN module weights are not part of single contiguous chunk of memory. This means they need to be compacted at every call, possibly greatly increasing memory usage. To compact weights again call flatten_parameters(). (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\cudnn\RNN.cpp:1480.)
  result = _VF.lstm(
c:\Users\n_and\OneDrive\Delt skrivebord\Data Science\Speciale\Energinet\py_3.10_blackwell\lib\site-packages\torch\nn\modules\rnn.py:1141: UserWarning: RNN module weights are not part of single contiguous chunk of memory. This means they need to be compacted at every call, possibly greatly increasing memory usage. To compact weights again call flatten_parameters(). (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\cudnn\RNN.cpp:1480.)
  result = _VF.lstm(
c:\Users\n_and\OneDrive\Delt skrivebord\Data Science\Speciale\Energinet\py_3.10_blackwell\lib\site-packages\torch\nn\modules\rnn.py:1141: UserWarning: RNN module weights are not part of single contiguous chunk of memory. This means they need to be compacted at every call, possibly greatly increasing memory usage. To compact weights again call flatten_parameters(). (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\cudnn\RNN.cpp:1480.)
  result = _VF.lstm(
c:\Users\n_and\OneDrive\Delt skrivebord\Data Science\Speciale\Energinet\py_3.10_blackwell\lib\site-packages\torch\nn\modules\rnn.py:1141: UserWarning: RNN module weights are not part of single contiguous chunk of memory. This means they need to be compacted at every call, possibly greatly increasing memory usage. To compact weights again call flatten_parameters(). (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\cudnn\RNN.cpp:1480.)
  result = _VF.lstm(
c:\Users\n_and\OneDrive\Delt skrivebord\Data Science\Speciale\Energinet\py_3.10_blackwell\lib\site-packages\torch\nn\modules\rnn.py:1141: UserWarning: RNN module weights are not part of single contiguous chunk of memory. This means they need to be compacted at every call, possibly greatly increasing memory usage. To compact weights again call flatten_parameters(). (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\cudnn\RNN.cpp:1480.)
  result = _VF.lstm(
c:\Users\n_and\OneDrive\Delt skrivebord\Data Science\Speciale\Energinet\py_3.10_blackwell\lib\site-packages\torch\nn\modules\rnn.py:1141: UserWarning: RNN module weights are not part of single contiguous chunk of memory. This means they need to be compacted at every call, possibly greatly increasing memory usage. To compact weights again call flatten_parameters(). (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\cudnn\RNN.cpp:1480.)
  result = _VF.lstm(
c:\Users\n_and\OneDrive\Delt skrivebord\Data Science\Speciale\Energinet\py_3.10_blackwell\lib\site-packages\torch\nn\modules\rnn.py:1141: UserWarning: RNN module weights are not part of single contiguous chunk of memory. This means they need to be compacted at every call, possibly greatly increasing memory usage. To compact weights again call flatten_parameters(). (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\cudnn\RNN.cpp:1480.)
  result = _VF.lstm(
c:\Users\n_and\OneDrive\Delt skrivebord\Data Science\Speciale\Energinet\py_3.10_blackwell\lib\site-packages\torch\nn\modules\rnn.py:1141: UserWarning: RNN module weights are not part of single contiguous chunk of memory. This means they need to be compacted at every call, possibly greatly increasing memory usage. To compact weights again call flatten_parameters(). (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\cudnn\RNN.cpp:1480.)
  result = _VF.lstm(
c:\Users\n_and\OneDrive\Delt skrivebord\Data Science\Speciale\Energinet\py_3.10_blackwell\lib\site-packages\torch\nn\modules\rnn.py:1141: UserWarning: RNN module weights are not part of single contiguous chunk of memory. This means they need to be compacted at every call, possibly greatly increasing memory usage. To compact weights again call flatten_parameters(). (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\cudnn\RNN.cpp:1480.)
  result = _VF.lstm(
c:\Users\n_and\OneDrive\Delt skrivebord\Data Science\Speciale\Energinet\py_3.10_blackwell\lib\site-packages\torch\nn\modules\rnn.py:1141: UserWarning: RNN module weights are not part of single contiguous chunk of memory. This means they need to be compacted at every call, possibly greatly increasing memory usage. To compact weights again call flatten_parameters(). (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\cudnn\RNN.cpp:1480.)
  result = _VF.lstm(
c:\Users\n_and\OneDrive\Delt skrivebord\Data Science\Speciale\Energinet\py_3.10_blackwell\lib\site-packages\torch\nn\modules\rnn.py:1141: UserWarning: RNN module weights are not part of single contiguous chunk of memory. This means they need to be compacted at every call, possibly greatly increasing memory usage. To compact weights again call flatten_parameters(). (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\cudnn\RNN.cpp:1480.)
  result = _VF.lstm(
c:\Users\n_and\OneDrive\Delt skrivebord\Data Science\Speciale\Energinet\py_3.10_blackwell\lib\site-packages\torch\nn\modules\rnn.py:1141: UserWarning: RNN module weights are not part of single contiguous chunk of memory. This means they need to be compacted at every call, possibly greatly increasing memory usage. To compact weights again call flatten_parameters(). (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\cudnn\RNN.cpp:1480.)
  result = _VF.lstm(
c:\Users\n_and\OneDrive\Delt skrivebord\Data Science\Speciale\Energinet\py_3.10_blackwell\lib\site-packages\torch\nn\modules\rnn.py:1141: UserWarning: RNN module weights are not part of single contiguous chunk of memory. This means they need to be compacted at every call, possibly greatly increasing memory usage. To compact weights again call flatten_parameters(). (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\cudnn\RNN.cpp:1480.)
  result = _VF.lstm(
c:\Users\n_and\OneDrive\Delt skrivebord\Data Science\Speciale\Energinet\py_3.10_blackwell\lib\site-packages\torch\nn\modules\rnn.py:1141: UserWarning: RNN module weights are not part of single contiguous chunk of memory. This means they need to be compacted at every call, possibly greatly increasing memory usage. To compact weights again call flatten_parameters(). (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\cudnn\RNN.cpp:1480.)
  result = _VF.lstm(
c:\Users\n_and\OneDrive\Delt skrivebord\Data Science\Speciale\Energinet\py_3.10_blackwell\lib\site-packages\torch\nn\modules\rnn.py:1141: UserWarning: RNN module weights are not part of single contiguous chunk of memory. This means they need to be compacted at every call, possibly greatly increasing memory usage. To compact weights again call flatten_parameters(). (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\cudnn\RNN.cpp:1480.)
  result = _VF.lstm(
c:\Users\n_and\OneDrive\Delt skrivebord\Data Science\Speciale\Energinet\py_3.10_blackwell\lib\site-packages\torch\nn\modules\rnn.py:1141: UserWarning: RNN module weights are not part of single contiguous chunk of memory. This means they need to be compacted at every call, possibly greatly increasing memory usage. To compact weights again call flatten_parameters(). (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\cudnn\RNN.cpp:1480.)
  result = _VF.lstm(
c:\Users\n_and\OneDrive\Delt skrivebord\Data Science\Speciale\Energinet\py_3.10_blackwell\lib\site-packages\torch\nn\modules\rnn.py:1141: UserWarning: RNN module weights are not part of single contiguous chunk of memory. This means they need to be compacted at every call, possibly greatly increasing memory usage. To compact weights again call flatten_parameters(). (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\cudnn\RNN.cpp:1480.)
  result = _VF.lstm(
c:\Users\n_and\OneDrive\Delt skrivebord\Data Science\Speciale\Energinet\py_3.10_blackwell\lib\site-packages\torch\nn\modules\rnn.py:1141: UserWarning: RNN module weights are not part of single contiguous chunk of memory. This means they need to be compacted at every call, possibly greatly increasing memory usage. To compact weights again call flatten_parameters(). (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\cudnn\RNN.cpp:1480.)
  result = _VF.lstm(
c:\Users\n_and\OneDrive\Delt skrivebord\Data Science\Speciale\Energinet\py_3.10_blackwell\lib\site-packages\torch\nn\modules\rnn.py:1141: UserWarning: RNN module weights are not part of single contiguous chunk of memory. This means they need to be compacted at every call, possibly greatly increasing memory usage. To compact weights again call flatten_parameters(). (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\cudnn\RNN.cpp:1480.)
  result = _VF.lstm(
c:\Users\n_and\OneDrive\Delt skrivebord\Data Science\Speciale\Energinet\py_3.10_blackwell\lib\site-packages\torch\nn\modules\rnn.py:1141: UserWarning: RNN module weights are not part of single contiguous chunk of memory. This means they need to be compacted at every call, possibly greatly increasing memory usage. To compact weights again call flatten_parameters(). (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\cudnn\RNN.cpp:1480.)
  result = _VF.lstm(
c:\Users\n_and\OneDrive\Delt skrivebord\Data Science\Speciale\Energinet\py_3.10_blackwell\lib\site-packages\torch\nn\modules\rnn.py:1141: UserWarning: RNN module weights are not part of single contiguous chunk of memory. This means they need to be compacted at every call, possibly greatly increasing memory usage. To compact weights again call flatten_parameters(). (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\cudnn\RNN.cpp:1480.)
  result = _VF.lstm(
c:\Users\n_and\OneDrive\Delt skrivebord\Data Science\Speciale\Energinet\py_3.10_blackwell\lib\site-packages\torch\nn\modules\rnn.py:1141: UserWarning: RNN module weights are not part of single contiguous chunk of memory. This means they need to be compacted at every call, possibly greatly increasing memory usage. To compact weights again call flatten_parameters(). (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\cudnn\RNN.cpp:1480.)
  result = _VF.lstm(
c:\Users\n_and\OneDrive\Delt skrivebord\Data Science\Speciale\Energinet\py_3.10_blackwell\lib\site-packages\torch\nn\modules\rnn.py:1141: UserWarning: RNN module weights are not part of single contiguous chunk of memory. This means they need to be compacted at every call, possibly greatly increasing memory usage. To compact weights again call flatten_parameters(). (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\cudnn\RNN.cpp:1480.)
  result = _VF.lstm(
c:\Users\n_and\OneDrive\Delt skrivebord\Data Science\Speciale\Energinet\py_3.10_blackwell\lib\site-packages\torch\nn\modules\rnn.py:1141: UserWarning: RNN module weights are not part of single contiguous chunk of memory. This means they need to be compacted at every call, possibly greatly increasing memory usage. To compact weights again call flatten_parameters(). (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\cudnn\RNN.cpp:1480.)
  result = _VF.lstm(
c:\Users\n_and\OneDrive\Delt skrivebord\Data Science\Speciale\Energinet\py_3.10_blackwell\lib\site-packages\torch\nn\modules\rnn.py:1141: UserWarning: RNN module weights are not part of single contiguous chunk of memory. This means they need to be compacted at every call, possibly greatly increasing memory usage. To compact weights again call flatten_parameters(). (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\cudnn\RNN.cpp:1480.)
  result = _VF.lstm(
c:\Users\n_and\OneDrive\Delt skrivebord\Data Science\Speciale\Energinet\py_3.10_blackwell\lib\site-packages\torch\nn\modules\rnn.py:1141: UserWarning: RNN module weights are not part of single contiguous chunk of memory. This means they need to be compacted at every call, possibly greatly increasing memory usage. To compact weights again call flatten_parameters(). (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\cudnn\RNN.cpp:1480.)
  result = _VF.lstm(
c:\Users\n_and\OneDrive\Delt skrivebord\Data Science\Speciale\Energinet\py_3.10_blackwell\lib\site-packages\torch\nn\modules\rnn.py:1141: UserWarning: RNN module weights are not part of single contiguous chunk of memory. This means they need to be compacted at every call, possibly greatly increasing memory usage. To compact weights again call flatten_parameters(). (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\cudnn\RNN.cpp:1480.)
  result = _VF.lstm(
c:\Users\n_and\OneDrive\Delt skrivebord\Data Science\Speciale\Energinet\py_3.10_blackwell\lib\site-packages\torch\nn\modules\rnn.py:1141: UserWarning: RNN module weights are not part of single contiguous chunk of memory. This means they need to be compacted at every call, possibly greatly increasing memory usage. To compact weights again call flatten_parameters(). (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\cudnn\RNN.cpp:1480.)
  result = _VF.lstm(
c:\Users\n_and\OneDrive\Delt skrivebord\Data Science\Speciale\Energinet\py_3.10_blackwell\lib\site-packages\torch\nn\modules\rnn.py:1141: UserWarning: RNN module weights are not part of single contiguous chunk of memory. This means they need to be compacted at every call, possibly greatly increasing memory usage. To compact weights again call flatten_parameters(). (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\cudnn\RNN.cpp:1480.)
  result = _VF.lstm(

=== Overall Test Results ===
MSE Loss:  171150.294934
SMAPE:     75.434783
MAE:       320.054265
RMSE:      413.703148

=== Weekly Metrics ===
Week 01: RMSE=391.9626, MAE=321.4013, SMAPE=85.2168
Week 02: RMSE=466.2252, MAE=374.7931, SMAPE=86.9953
Week 03: RMSE=629.6268, MAE=454.3112, SMAPE=63.7096
Week 04: RMSE=805.3067, MAE=578.7203, SMAPE=77.8416
Week 05: RMSE=470.7260, MAE=413.1984, SMAPE=62.0991
Week 06: RMSE=462.6406, MAE=383.7299, SMAPE=55.8456
Week 07: RMSE=605.8966, MAE=506.1109, SMAPE=65.3438
Week 08: RMSE=411.2956, MAE=302.0893, SMAPE=45.4229
Week 09: RMSE=475.9622, MAE=427.2452, SMAPE=66.5691
Week 10: RMSE=345.1180, MAE=295.3871, SMAPE=73.0593
Week 11: RMSE=426.0159, MAE=372.5708, SMAPE=58.9383
Week 12: RMSE=432.2153, MAE=364.1975, SMAPE=86.1776
Week 13: RMSE=386.1687, MAE=323.7721, SMAPE=75.9667
Week 14: RMSE=384.3240, MAE=323.1810, SMAPE=82.4777
Week 15: RMSE=357.0843, MAE=285.8602, SMAPE=76.9533
Week 16: RMSE=341.3995, MAE=279.8264, SMAPE=76.1730
Week 17: RMSE=360.6473, MAE=301.7109, SMAPE=67.6928
Week 18: RMSE=322.1406, MAE=271.7772, SMAPE=91.0939
Week 19: RMSE=330.2860, MAE=288.5439, SMAPE=73.6377
Week 20: RMSE=355.0811, MAE=307.4877, SMAPE=87.1995
Week 21: RMSE=286.1997, MAE=225.7347, SMAPE=87.5520
Week 22: RMSE=283.7318, MAE=224.1042, SMAPE=84.6037
Week 23: RMSE=261.3077, MAE=197.6946, SMAPE=83.9199
Week 24: RMSE=289.8232, MAE=222.3950, SMAPE=92.6827
Week 25: RMSE=356.7595, MAE=293.6894, SMAPE=93.5245
Week 26: RMSE=273.3858, MAE=191.8625, SMAPE=87.7359
Week 27: RMSE=538.6162, MAE=368.3490, SMAPE=102.4505
Week 28: RMSE=374.2155, MAE=347.9962, SMAPE=96.3547
Week 29: RMSE=342.3948, MAE=313.8055, SMAPE=74.9029
Week 30: RMSE=323.9964, MAE=301.9573, SMAPE=65.9654
Week 31: RMSE=255.3012, MAE=227.3302, SMAPE=64.6032
Week 32: RMSE=297.3593, MAE=266.9967, SMAPE=103.0368
Week 33: RMSE=380.7135, MAE=306.7199, SMAPE=81.6505
Week 34: RMSE=306.5045, MAE=268.7567, SMAPE=73.8170
Week 35: RMSE=403.2515, MAE=336.8017, SMAPE=78.6143
Week 36: RMSE=439.9303, MAE=327.5956, SMAPE=73.5591
Week 37: RMSE=525.1486, MAE=368.6851, SMAPE=78.1515
Week 38: RMSE=329.9731, MAE=292.5744, SMAPE=125.0425
Week 39: RMSE=342.2359, MAE=297.4360, SMAPE=80.1385
Week 40: RMSE=548.7922, MAE=389.5933, SMAPE=108.5120
Week 41: RMSE=549.6495, MAE=486.8182, SMAPE=119.2290
Week 42: RMSE=592.9039, MAE=473.5671, SMAPE=76.2774
Week 43: RMSE=263.7160, MAE=159.5258, SMAPE=59.5450
Week 44: RMSE=264.1871, MAE=222.1076, SMAPE=56.1979
Week 45: RMSE=347.1556, MAE=293.8274, SMAPE=56.3259
Week 46: RMSE=341.6959, MAE=305.2029, SMAPE=64.9105
Week 47: RMSE=443.0422, MAE=363.6011, SMAPE=58.8960
Week 48: RMSE=667.5553, MAE=415.0046, SMAPE=51.4956
Week 49: RMSE=446.3368, MAE=349.9875, SMAPE=54.4693
Week 50: RMSE=245.2408, MAE=189.5337, SMAPE=42.1100
Week 51: RMSE=306.9209, MAE=255.0884, SMAPE=51.1136
Week 52: RMSE=210.2798, MAE=182.3727, SMAPE=35.4102

=== Daily Metrics (by Date) ===
2025-01-01: RMSE=328.7851, MAE=317.4817, SMAPE=161.7322
2025-01-02: RMSE=367.1159, MAE=318.7086, SMAPE=67.6437
2025-01-03: RMSE=189.5112, MAE=135.7977, SMAPE=27.5697
2025-01-04: RMSE=757.3118, MAE=729.7002, SMAPE=135.9510
2025-01-05: RMSE=486.2524, MAE=463.4058, SMAPE=170.1958
2025-01-06: RMSE=83.1222, MAE=69.8589, SMAPE=73.4946
2025-01-07: RMSE=95.1139, MAE=72.0687, SMAPE=55.7097
2025-01-08: RMSE=602.8237, MAE=507.1306, SMAPE=132.0824
2025-01-09: RMSE=693.2147, MAE=656.7325, SMAPE=121.0038
2025-01-10: RMSE=460.7331, MAE=437.2845, SMAPE=69.0620
2025-01-11: RMSE=341.4082, MAE=331.8593, SMAPE=58.3667
2025-01-12: RMSE=576.9124, MAE=548.6174, SMAPE=99.2481
2025-01-13: RMSE=354.4896, MAE=268.5903, SMAPE=60.7671
2025-01-14: RMSE=121.4024, MAE=101.8651, SMAPE=30.4666
2025-01-15: RMSE=1317.2025, MAE=1151.4004, SMAPE=114.4749
2025-01-16: RMSE=392.8201, MAE=309.0484, SMAPE=51.0028
2025-01-17: RMSE=399.0961, MAE=291.9964, SMAPE=41.9961
2025-01-18: RMSE=560.3851, MAE=545.1411, SMAPE=74.8964
2025-01-19: RMSE=521.5059, MAE=512.1368, SMAPE=72.3633
2025-01-20: RMSE=1601.1278, MAE=1324.2556, SMAPE=115.4063
2025-01-21: RMSE=991.2297, MAE=952.5124, SMAPE=134.2081
2025-01-22: RMSE=769.8915, MAE=707.8520, SMAPE=84.4171
2025-01-23: RMSE=350.6596, MAE=285.9991, SMAPE=46.3350
2025-01-24: RMSE=222.0923, MAE=201.4731, SMAPE=64.0373
2025-01-25: RMSE=348.1050, MAE=276.7199, SMAPE=49.2050
2025-01-26: RMSE=327.5487, MAE=302.2300, SMAPE=51.2823
2025-01-27: RMSE=165.8514, MAE=147.7936, SMAPE=44.9821
2025-01-28: RMSE=329.1047, MAE=282.4441, SMAPE=47.3348
2025-01-29: RMSE=387.6567, MAE=340.7918, SMAPE=52.1949
2025-01-30: RMSE=493.7954, MAE=452.8541, SMAPE=64.3693
2025-01-31: RMSE=609.8042, MAE=561.5578, SMAPE=74.1420
2025-02-01: RMSE=564.3272, MAE=546.8575, SMAPE=75.4516
2025-02-02: RMSE=575.1750, MAE=560.0903, SMAPE=76.2187
2025-02-03: RMSE=732.7878, MAE=672.7315, SMAPE=82.3471
2025-02-04: RMSE=384.3981, MAE=300.7330, SMAPE=45.2885
2025-02-05: RMSE=310.2511, MAE=251.7046, SMAPE=40.0639
2025-02-06: RMSE=617.4697, MAE=585.2576, SMAPE=77.3133
2025-02-07: RMSE=354.4343, MAE=301.9511, SMAPE=47.6006
2025-02-08: RMSE=278.6754, MAE=233.0093, SMAPE=44.7494
2025-02-09: RMSE=364.2891, MAE=340.7218, SMAPE=53.5562
2025-02-10: RMSE=210.8279, MAE=157.8077, SMAPE=27.4410
2025-02-11: RMSE=157.2083, MAE=132.0919, SMAPE=24.6986
2025-02-12: RMSE=604.3107, MAE=541.1579, SMAPE=70.7536
2025-02-13: RMSE=772.6133, MAE=740.6006, SMAPE=88.8359
2025-02-14: RMSE=962.7771, MAE=887.6694, SMAPE=95.9400
2025-02-15: RMSE=554.9174, MAE=541.8981, SMAPE=74.7619
2025-02-16: RMSE=551.0141, MAE=541.5506, SMAPE=74.9755
2025-02-17: RMSE=763.2457, MAE=696.1186, SMAPE=83.8857
2025-02-18: RMSE=571.8220, MAE=531.6641, SMAPE=72.1399
2025-02-19: RMSE=392.1195, MAE=348.8820, SMAPE=53.4480
2025-02-20: RMSE=116.6240, MAE=79.0727, SMAPE=16.2695
2025-02-21: RMSE=190.3422, MAE=140.5438, SMAPE=26.9428
2025-02-22: RMSE=186.8260, MAE=155.4383, SMAPE=31.1892
2025-02-23: RMSE=190.0822, MAE=162.9055, SMAPE=34.0853
2025-02-24: RMSE=243.2884, MAE=205.0293, SMAPE=59.0638
2025-02-25: RMSE=614.7573, MAE=565.6675, SMAPE=74.3930
2025-02-26: RMSE=570.7291, MAE=548.9167, SMAPE=74.7934
2025-02-27: RMSE=521.5529, MAE=492.7481, SMAPE=69.2871
2025-02-28: RMSE=505.5617, MAE=481.5299, SMAPE=68.4864
2025-03-01: RMSE=462.9747, MAE=447.2280, SMAPE=65.6999
2025-03-02: RMSE=284.5646, MAE=249.5970, SMAPE=54.2603
2025-03-03: RMSE=276.6122, MAE=225.9226, SMAPE=61.1774
2025-03-04: RMSE=215.4869, MAE=168.4705, SMAPE=56.0372
2025-03-05: RMSE=293.9589, MAE=254.7306, SMAPE=94.5474
2025-03-06: RMSE=345.9554, MAE=298.8335, SMAPE=68.3638
2025-03-07: RMSE=431.5496, MAE=376.1217, SMAPE=64.2665
2025-03-08: RMSE=425.1421, MAE=392.9328, SMAPE=82.9186
2025-03-09: RMSE=371.1043, MAE=350.6982, SMAPE=84.1043
2025-03-10: RMSE=416.1542, MAE=368.1791, SMAPE=55.3040
2025-03-11: RMSE=489.9597, MAE=453.9407, SMAPE=65.2067
2025-03-12: RMSE=508.0902, MAE=469.0891, SMAPE=66.5203
2025-03-13: RMSE=517.0927, MAE=487.7795, SMAPE=68.8030
2025-03-14: RMSE=476.6270, MAE=456.0040, SMAPE=66.3468
2025-03-15: RMSE=289.3134, MAE=250.4851, SMAPE=41.5672
2025-03-16: RMSE=144.1050, MAE=122.5178, SMAPE=48.8200
2025-03-17: RMSE=405.4329, MAE=332.9866, SMAPE=52.3851
2025-03-18: RMSE=409.6005, MAE=373.6995, SMAPE=78.9623
2025-03-19: RMSE=554.6374, MAE=478.6411, SMAPE=88.5162
2025-03-20: RMSE=572.1896, MAE=476.3204, SMAPE=83.1093
2025-03-21: RMSE=336.5264, MAE=302.8908, SMAPE=77.4252
2025-03-22: RMSE=360.0815, MAE=340.3971, SMAPE=134.7598
2025-03-23: RMSE=312.3941, MAE=244.4469, SMAPE=88.0852
2025-03-24: RMSE=586.5782, MAE=548.9899, SMAPE=80.6837
2025-03-25: RMSE=340.2134, MAE=305.1501, SMAPE=54.8815
2025-03-26: RMSE=424.2851, MAE=369.8293, SMAPE=67.7138
2025-03-27: RMSE=336.0477, MAE=294.1175, SMAPE=52.9933
2025-03-28: RMSE=349.1999, MAE=279.8929, SMAPE=66.2317
2025-03-29: RMSE=364.2068, MAE=324.2125, SMAPE=93.8479
2025-03-30: RMSE=191.1322, MAE=144.2128, SMAPE=115.4147
2025-03-31: RMSE=438.5068, MAE=354.1775, SMAPE=51.1005
2025-04-01: RMSE=395.3458, MAE=322.9189, SMAPE=56.3968
2025-04-02: RMSE=345.4435, MAE=291.8203, SMAPE=81.4124
2025-04-03: RMSE=438.5122, MAE=384.5648, SMAPE=86.5673
2025-04-04: RMSE=404.8327, MAE=371.2899, SMAPE=84.6480
2025-04-05: RMSE=276.3589, MAE=237.0325, SMAPE=100.0371
2025-04-06: RMSE=365.3220, MAE=300.4633, SMAPE=117.1818
2025-04-07: RMSE=439.1561, MAE=373.5783, SMAPE=67.7581
2025-04-08: RMSE=440.0276, MAE=362.0201, SMAPE=58.1192
2025-04-09: RMSE=367.2899, MAE=306.9637, SMAPE=55.6383
2025-04-10: RMSE=327.8210, MAE=270.5213, SMAPE=85.8566
2025-04-11: RMSE=316.2491, MAE=272.4783, SMAPE=110.5648
2025-04-12: RMSE=323.6579, MAE=246.8170, SMAPE=77.6256
2025-04-13: RMSE=242.7869, MAE=168.6426, SMAPE=83.1104
2025-04-14: RMSE=351.8434, MAE=269.7363, SMAPE=41.4398
2025-04-15: RMSE=233.5373, MAE=191.4847, SMAPE=76.3534
2025-04-16: RMSE=297.1180, MAE=235.0671, SMAPE=39.8032
2025-04-17: RMSE=375.3658, MAE=344.9307, SMAPE=71.5694
2025-04-18: RMSE=345.8396, MAE=313.7898, SMAPE=85.6189
2025-04-19: RMSE=244.1800, MAE=200.8178, SMAPE=77.7226
2025-04-20: RMSE=478.6798, MAE=402.9588, SMAPE=140.7039
2025-04-21: RMSE=326.9051, MAE=301.4999, SMAPE=63.0931
2025-04-22: RMSE=541.2065, MAE=456.0649, SMAPE=74.4201
2025-04-23: RMSE=464.5836, MAE=437.6728, SMAPE=80.1784
2025-04-24: RMSE=355.3527, MAE=337.6407, SMAPE=66.8911
2025-04-25: RMSE=316.5358, MAE=305.4902, SMAPE=70.1683
2025-04-26: RMSE=176.6325, MAE=142.3382, SMAPE=65.3959
2025-04-27: RMSE=192.8376, MAE=131.2696, SMAPE=53.7024
2025-04-28: RMSE=399.0639, MAE=340.2895, SMAPE=92.1923
2025-04-29: RMSE=365.4626, MAE=326.9520, SMAPE=87.4557
2025-04-30: RMSE=375.2765, MAE=343.3323, SMAPE=89.5717
2025-05-01: RMSE=379.7424, MAE=335.6769, SMAPE=95.6195
2025-05-02: RMSE=247.0373, MAE=210.6224, SMAPE=81.5658
2025-05-03: RMSE=169.4077, MAE=141.8903, SMAPE=79.1416
2025-05-04: RMSE=242.5776, MAE=203.6768, SMAPE=112.1107
2025-05-05: RMSE=284.7675, MAE=263.1209, SMAPE=63.4012
2025-05-06: RMSE=339.7869, MAE=303.4023, SMAPE=60.8339
2025-05-07: RMSE=367.6388, MAE=340.8007, SMAPE=60.6509
2025-05-08: RMSE=397.1727, MAE=353.9576, SMAPE=57.4536
2025-05-09: RMSE=339.5434, MAE=299.4194, SMAPE=85.1096
2025-05-10: RMSE=304.0576, MAE=242.3023, SMAPE=82.0471
2025-05-11: RMSE=257.7380, MAE=216.8042, SMAPE=105.9672
2025-05-12: RMSE=351.8204, MAE=289.7829, SMAPE=70.9027
2025-05-13: RMSE=441.5491, MAE=390.6937, SMAPE=94.6346
2025-05-14: RMSE=397.3704, MAE=370.9045, SMAPE=96.3101
2025-05-15: RMSE=357.9260, MAE=331.8796, SMAPE=94.9305
2025-05-16: RMSE=348.9160, MAE=318.9008, SMAPE=90.3368
2025-05-17: RMSE=266.8342, MAE=213.1380, SMAPE=81.8111
2025-05-18: RMSE=291.3374, MAE=237.1142, SMAPE=81.4704
2025-05-19: RMSE=398.4030, MAE=323.3056, SMAPE=57.3293
2025-05-20: RMSE=340.7488, MAE=273.0791, SMAPE=69.8924
2025-05-21: RMSE=183.6197, MAE=141.1214, SMAPE=77.1881
2025-05-22: RMSE=301.4154, MAE=262.3777, SMAPE=124.8356
2025-05-23: RMSE=274.2817, MAE=232.8773, SMAPE=56.1277
2025-05-24: RMSE=235.5873, MAE=195.2764, SMAPE=101.3960
2025-05-25: RMSE=207.9368, MAE=152.1052, SMAPE=126.0945
2025-05-26: RMSE=298.5550, MAE=251.7993, SMAPE=97.2908
2025-05-27: RMSE=283.2243, MAE=230.9991, SMAPE=100.8632
2025-05-28: RMSE=306.8212, MAE=272.8158, SMAPE=60.1541
2025-05-29: RMSE=194.7854, MAE=168.7162, SMAPE=78.1053
2025-05-30: RMSE=298.2898, MAE=244.2865, SMAPE=101.2812
2025-05-31: RMSE=396.1351, MAE=298.5472, SMAPE=89.8210
2025-06-01: RMSE=127.2584, MAE=101.5651, SMAPE=64.7104
2025-06-02: RMSE=395.3178, MAE=288.5443, SMAPE=76.5668
2025-06-03: RMSE=198.5648, MAE=162.4121, SMAPE=78.1885
2025-06-04: RMSE=274.0396, MAE=222.5150, SMAPE=63.5415
2025-06-05: RMSE=320.8401, MAE=279.5616, SMAPE=93.1102
2025-06-06: RMSE=216.7963, MAE=151.3280, SMAPE=74.4859
2025-06-07: RMSE=216.7779, MAE=198.3883, SMAPE=91.7353
2025-06-08: RMSE=101.1847, MAE=81.1128, SMAPE=109.8111
2025-06-09: RMSE=287.5867, MAE=227.0825, SMAPE=109.8489
2025-06-10: RMSE=208.0289, MAE=186.4378, SMAPE=77.6466
2025-06-11: RMSE=383.1735, MAE=293.0758, SMAPE=85.2196
2025-06-12: RMSE=250.9331, MAE=204.5719, SMAPE=85.1451
2025-06-13: RMSE=160.1765, MAE=130.9886, SMAPE=75.2865
2025-06-14: RMSE=226.1009, MAE=173.6952, SMAPE=83.3468
2025-06-15: RMSE=418.8471, MAE=340.9132, SMAPE=132.2853
2025-06-16: RMSE=389.5126, MAE=345.0197, SMAPE=120.3277
2025-06-17: RMSE=389.1390, MAE=319.2838, SMAPE=80.4443
2025-06-18: RMSE=299.7704, MAE=276.6024, SMAPE=86.4702
2025-06-19: RMSE=328.0947, MAE=272.6855, SMAPE=104.1585
2025-06-20: RMSE=448.1696, MAE=366.2038, SMAPE=98.3152
2025-06-21: RMSE=372.1370, MAE=310.5319, SMAPE=92.6242
2025-06-22: RMSE=225.7025, MAE=165.4988, SMAPE=72.3317
2025-06-23: RMSE=178.6437, MAE=129.0027, SMAPE=78.9050
2025-06-24: RMSE=151.0987, MAE=132.7941, SMAPE=105.5203
2025-06-25: RMSE=451.4459, MAE=268.3596, SMAPE=68.0787
2025-06-26: RMSE=353.4557, MAE=331.0570, SMAPE=83.6311
2025-06-27: RMSE=198.3624, MAE=143.4674, SMAPE=86.3307
2025-06-28: RMSE=144.7608, MAE=115.0987, SMAPE=92.7098
2025-06-29: RMSE=281.7738, MAE=223.2579, SMAPE=98.9758
2025-06-30: RMSE=623.8636, MAE=519.0168, SMAPE=122.5842
2025-07-01: RMSE=1030.9897, MAE=715.8421, SMAPE=107.6495
2025-07-02: RMSE=500.7879, MAE=420.0471, SMAPE=86.3059
2025-07-03: RMSE=338.6595, MAE=273.8951, SMAPE=130.2332
2025-07-04: RMSE=215.8558, MAE=182.5381, SMAPE=72.0055
2025-07-05: RMSE=201.2755, MAE=151.8880, SMAPE=89.3665
2025-07-06: RMSE=354.9959, MAE=315.2156, SMAPE=109.0087
2025-07-07: RMSE=423.8833, MAE=400.8896, SMAPE=93.3586
2025-07-08: RMSE=383.3186, MAE=367.6705, SMAPE=93.1229
2025-07-09: RMSE=365.6135, MAE=345.6075, SMAPE=81.1652
2025-07-10: RMSE=351.3635, MAE=339.5600, SMAPE=80.1731
2025-07-11: RMSE=333.1286, MAE=325.6830, SMAPE=82.3067
2025-07-12: RMSE=363.3957, MAE=309.7819, SMAPE=119.2847
2025-07-13: RMSE=391.7779, MAE=346.7811, SMAPE=125.0715
2025-07-14: RMSE=373.9182, MAE=353.3397, SMAPE=64.9860
2025-07-15: RMSE=329.8933, MAE=306.8861, SMAPE=61.4672
2025-07-16: RMSE=325.1405, MAE=308.2961, SMAPE=55.5085
2025-07-17: RMSE=295.9353, MAE=271.9912, SMAPE=48.2090
2025-07-18: RMSE=409.9227, MAE=392.8770, SMAPE=78.0899
2025-07-19: RMSE=310.4031, MAE=267.4907, SMAPE=105.4361
2025-07-20: RMSE=338.1040, MAE=295.7573, SMAPE=110.6236
2025-07-21: RMSE=317.2582, MAE=306.9979, SMAPE=53.1269
2025-07-22: RMSE=265.9371, MAE=242.2228, SMAPE=53.5180
2025-07-23: RMSE=239.6543, MAE=209.4027, SMAPE=40.3955
2025-07-24: RMSE=343.5026, MAE=319.3811, SMAPE=51.9420
2025-07-25: RMSE=323.4913, MAE=315.9150, SMAPE=58.7456
2025-07-26: RMSE=416.6460, MAE=404.1061, SMAPE=106.2902
2025-07-27: RMSE=331.3179, MAE=315.6755, SMAPE=97.7392
2025-07-28: RMSE=276.6477, MAE=257.8805, SMAPE=61.9629
2025-07-29: RMSE=275.9427, MAE=253.2549, SMAPE=91.4506
2025-07-30: RMSE=231.8643, MAE=211.8792, SMAPE=46.4557
2025-07-31: RMSE=261.3269, MAE=224.4819, SMAPE=38.9059
2025-08-01: RMSE=287.9117, MAE=263.0425, SMAPE=44.1024
2025-08-02: RMSE=235.8116, MAE=213.7336, SMAPE=71.7340
2025-08-03: RMSE=207.4118, MAE=167.0386, SMAPE=97.6109
2025-08-04: RMSE=282.7777, MAE=255.9268, SMAPE=96.5565
2025-08-05: RMSE=242.3178, MAE=217.4881, SMAPE=165.3760
2025-08-06: RMSE=349.3587, MAE=337.9953, SMAPE=149.1229
2025-08-07: RMSE=321.7666, MAE=305.9115, SMAPE=84.4825
2025-08-08: RMSE=365.2237, MAE=333.4594, SMAPE=81.9102
2025-08-09: RMSE=254.4597, MAE=221.1662, SMAPE=78.6747
2025-08-10: RMSE=237.8099, MAE=197.0293, SMAPE=65.1350
2025-08-11: RMSE=415.7898, MAE=356.0282, SMAPE=87.9408
2025-08-12: RMSE=408.9436, MAE=371.7207, SMAPE=103.2817
2025-08-13: RMSE=479.9395, MAE=411.6501, SMAPE=88.1599
2025-08-14: RMSE=517.9706, MAE=356.3457, SMAPE=48.8731
2025-08-15: RMSE=287.4418, MAE=272.4389, SMAPE=74.5737
2025-08-16: RMSE=186.5821, MAE=165.8775, SMAPE=74.7893
2025-08-17: RMSE=241.6863, MAE=212.9784, SMAPE=93.9354
2025-08-18: RMSE=393.7067, MAE=319.6727, SMAPE=55.0435
2025-08-19: RMSE=334.9426, MAE=315.4801, SMAPE=86.9161
2025-08-20: RMSE=314.8386, MAE=299.2469, SMAPE=66.5378
2025-08-21: RMSE=299.4406, MAE=289.5526, SMAPE=58.7721
2025-08-22: RMSE=225.0012, MAE=193.4645, SMAPE=70.4559
2025-08-23: RMSE=261.2344, MAE=218.9635, SMAPE=74.4186
2025-08-24: RMSE=287.6920, MAE=244.9168, SMAPE=104.5748
2025-08-25: RMSE=433.8784, MAE=358.9808, SMAPE=92.4753
2025-08-26: RMSE=467.9787, MAE=428.6653, SMAPE=93.1930
2025-08-27: RMSE=477.4736, MAE=399.6258, SMAPE=70.5833
2025-08-28: RMSE=482.3317, MAE=431.6925, SMAPE=64.4084
2025-08-29: RMSE=387.0838, MAE=361.7887, SMAPE=80.8623
2025-08-30: RMSE=246.0203, MAE=210.3609, SMAPE=72.8413
2025-08-31: RMSE=245.0374, MAE=166.4977, SMAPE=75.9362
2025-09-01: RMSE=482.2623, MAE=369.5222, SMAPE=63.9047
2025-09-02: RMSE=631.3869, MAE=482.7305, SMAPE=65.3817
2025-09-03: RMSE=278.9192, MAE=251.9194, SMAPE=78.5749
2025-09-04: RMSE=609.8249, MAE=419.7700, SMAPE=77.0205
2025-09-05: RMSE=367.7280, MAE=338.6966, SMAPE=57.5340
2025-09-06: RMSE=315.9532, MAE=262.2304, SMAPE=83.3225
2025-09-07: RMSE=197.0058, MAE=168.3001, SMAPE=89.1756
2025-09-08: RMSE=755.3325, MAE=479.0407, SMAPE=60.2512
2025-09-09: RMSE=804.5582, MAE=601.4035, SMAPE=70.1219
2025-09-10: RMSE=581.2831, MAE=465.7561, SMAPE=63.2767
2025-09-11: RMSE=294.4641, MAE=248.0724, SMAPE=71.8403
2025-09-12: RMSE=333.8891, MAE=296.5163, SMAPE=99.7079
2025-09-13: RMSE=234.4305, MAE=192.2228, SMAPE=70.6547
2025-09-14: RMSE=348.6938, MAE=297.7839, SMAPE=111.2077
2025-09-15: RMSE=413.8285, MAE=409.7313, SMAPE=187.0998
2025-09-16: RMSE=417.2094, MAE=414.9917, SMAPE=176.3531
2025-09-17: RMSE=321.8304, MAE=287.9704, SMAPE=106.0469
2025-09-18: RMSE=304.5122, MAE=281.7634, SMAPE=111.1983
2025-09-19: RMSE=323.1380, MAE=285.9566, SMAPE=81.5003
2025-09-20: RMSE=231.6709, MAE=181.1724, SMAPE=72.6495
2025-09-21: RMSE=249.9316, MAE=186.4354, SMAPE=140.4495
2025-09-22: RMSE=308.4627, MAE=241.7921, SMAPE=102.7385
2025-09-23: RMSE=410.1299, MAE=368.8801, SMAPE=61.9352
2025-09-24: RMSE=261.4582, MAE=228.2321, SMAPE=48.4358
2025-09-25: RMSE=326.7074, MAE=305.0553, SMAPE=82.3989
2025-09-26: RMSE=227.4312, MAE=197.1141, SMAPE=54.6081
2025-09-27: RMSE=356.1071, MAE=317.7852, SMAPE=93.0282
2025-09-28: RMSE=450.4296, MAE=423.1931, SMAPE=117.8249
2025-09-29: RMSE=842.6090, MAE=667.7544, SMAPE=102.7959
2025-09-30: RMSE=817.3213, MAE=663.2790, SMAPE=93.0787
2025-10-01: RMSE=625.5064, MAE=429.9784, SMAPE=55.6175
2025-10-02: RMSE=414.8023, MAE=365.8354, SMAPE=74.9447
2025-10-03: RMSE=251.1802, MAE=222.9306, SMAPE=97.2584
2025-10-04: RMSE=281.4953, MAE=239.3735, SMAPE=190.4543
2025-10-05: RMSE=156.7034, MAE=138.0016, SMAPE=145.4348
2025-10-06: RMSE=615.4918, MAE=592.0866, SMAPE=164.9041
2025-10-07: RMSE=840.0611, MAE=786.9373, SMAPE=134.5217
2025-10-08: RMSE=507.4272, MAE=458.6981, SMAPE=68.7463
2025-10-09: RMSE=318.9415, MAE=258.8178, SMAPE=53.2460
2025-10-10: RMSE=256.2494, MAE=230.0887, SMAPE=77.2770
2025-10-11: RMSE=513.0190, MAE=501.2518, SMAPE=157.2680
2025-10-12: RMSE=584.9881, MAE=579.8471, SMAPE=178.6398
2025-10-13: RMSE=746.9166, MAE=622.6034, SMAPE=80.9787
2025-10-14: RMSE=956.6644, MAE=724.6512, SMAPE=78.9339
2025-10-15: RMSE=652.4701, MAE=554.9336, SMAPE=70.8084
2025-10-16: RMSE=295.4487, MAE=258.0239, SMAPE=42.9400
2025-10-17: RMSE=425.8547, MAE=416.9709, SMAPE=76.5492
2025-10-18: RMSE=435.9016, MAE=430.6350, SMAPE=88.1473
2025-10-19: RMSE=321.3790, MAE=307.1516, SMAPE=95.5846
2025-10-20: RMSE=144.5840, MAE=125.3443, SMAPE=30.1657
2025-10-21: RMSE=134.4500, MAE=108.1878, SMAPE=26.8818
2025-10-22: RMSE=607.7543, MAE=405.7209, SMAPE=50.4445
2025-10-23: RMSE=175.9882, MAE=154.8699, SMAPE=34.4059
2025-10-24: RMSE=148.8710, MAE=125.0414, SMAPE=61.9956
2025-10-25: RMSE=123.4245, MAE=110.2860, SMAPE=101.1492
2025-10-26: RMSE=100.5407, MAE=87.2304, SMAPE=111.7721
2025-10-27: RMSE=291.4966, MAE=240.3659, SMAPE=70.4537
2025-10-28: RMSE=203.4399, MAE=180.9405, SMAPE=43.8386
2025-10-29: RMSE=243.5392, MAE=202.3693, SMAPE=34.6556
2025-10-30: RMSE=212.0679, MAE=162.2523, SMAPE=37.1675
2025-10-31: RMSE=327.0155, MAE=312.2576, SMAPE=78.2033
2025-11-01: RMSE=152.6265, MAE=107.2672, SMAPE=40.6205
2025-11-02: RMSE=357.3342, MAE=349.3002, SMAPE=88.4465
2025-11-03: RMSE=174.2478, MAE=146.5019, SMAPE=34.6662
2025-11-04: RMSE=136.3465, MAE=107.0482, SMAPE=41.2808
2025-11-05: RMSE=213.4496, MAE=163.6856, SMAPE=28.4029
2025-11-06: RMSE=380.7802, MAE=347.2051, SMAPE=55.9064

Shap analysis

In [9]:

import gc
from pathlib import Path

import joblib
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import psutil
import shap
import wandb

# ==========================
# SHAP configuration (LSTM AE)
# Note: predict() uses a constant-feature decoder with zero encoder baseline.
# SHAP values reflect sensitivity of the mean predicted price to each decoder
# feature value held constant across the 168-hour horizon.
# ==========================
quick_mode = False
eval_size = 300            # evaluation sample size
bg_size = 150              # background sample size for KernelExplainer
chunk_size = 25            # lower if memory/runtime is high
nsamples = 100             # SHAP Monte Carlo samples per explained point
include_beeswarm = True
include_waterfall = True

PRICE_ZONE = globals().get("PRICE_ZONE", "DK1")
WANDB_PROJECT = globals().get("WANDB_PROJECT", "LSTM_AE")
# WANDB_RUN_NAME = WANDB_RUN_NAME  # Must match the final training run name from Stage 3
WANDB_RUN_NAME = WANDB_RUN_NAME
WANDB_ARTIFACT_NAME = f"{WANDB_RUN_NAME}_model"
WANDB_SHAP_RUN_NAME = f"{PRICE_ZONE}_lstm_ae_shap"


# Use dataset_train_input (feature columns only, no DKPrice) as the SHAP background/eval set.
if "dataset_train_input" not in globals() or dataset_train_input is None:
    raise ValueError("Missing dataset_train_input. Run the data loading cell first.")

feature_columns = [c for c in dataset_train_input.columns if c not in ["Time", "DKPrice"]]
if not feature_columns:
    raise ValueError("No feature columns found in dataset_train_input after removing ['Time', 'DKPrice'].")

X_train_shap = dataset_train_input.loc[:, feature_columns].copy()
if len(X_train_shap) == 0:
    raise ValueError("No rows found in dataset_train_input for SHAP analysis.")

X_train_shap = X_train_shap.astype(np.float32, copy=False)

# Start a dedicated W&B run for SHAP and load latest model artifact
wandb_run = wandb.init(
    project=WANDB_PROJECT,
    name=WANDB_SHAP_RUN_NAME,
    job_type="shap-analysis",
    config={
        "price_zone": PRICE_ZONE,
        "train_hours": int(TRAIN_WINDOW),
        "artifact_name": WANDB_ARTIFACT_NAME,
        "eval_size_requested": int(eval_size),
        "bg_size_requested": int(bg_size),
        "nsamples": int(nsamples),
    },
    reinit=True,
    settings=wandb.Settings(start_method="thread"),
)

model_artifact = wandb_run.use_artifact(f"{WANDB_ARTIFACT_NAME}:latest")
artifact_dir = Path(model_artifact.download())
model_path = artifact_dir / "model.joblib"
if not model_path.exists():
    raise ValueError(f"Could not find model.joblib in downloaded artifact: {artifact_dir}")

model = joblib.load(model_path)
print(f"Loaded LSTM AE model artifact: {WANDB_ARTIFACT_NAME}:latest")

mem = psutil.virtual_memory()
print(f"Available RAM before SHAP: {mem.available / (1024**3):.2f} GB")
print(f"Training set size for SHAP: {len(X_train_shap)} samples")
print(f"Number of features: {len(feature_columns)}")

if quick_mode:
    bg_size = min(30, len(X_train_shap))
    eval_size = min(60, len(X_train_shap))
    chunk_size = 10
    nsamples = 50
else:
    bg_size = min(bg_size, len(X_train_shap))
    eval_size = min(eval_size, len(X_train_shap))
    chunk_size = max(1, min(chunk_size, eval_size))

X_bg = shap.sample(X_train_shap, bg_size, random_state=42)
X_eval = shap.sample(X_train_shap, eval_size, random_state=42)

print(f"\nBackground sample size (X_bg): {len(X_bg)}")
print(f"Evaluation sample size (X_eval): {len(X_eval)}")
print(f"Chunk size: {chunk_size}")
print(f"Kernel SHAP nsamples: {nsamples}")

def predict_fn(x):
    x_df = pd.DataFrame(x, columns=feature_columns)
    preds = model.predict(x_df)
    return np.asarray(preds).reshape(-1)

explainer = shap.KernelExplainer(predict_fn, X_bg.values)

# Compute SHAP values in chunks and print progress
shap_chunks = []
n_chunks = (len(X_eval) + chunk_size - 1) // chunk_size
for idx, start in enumerate(range(0, len(X_eval), chunk_size), start=1):
    stop = min(start + chunk_size, len(X_eval))
    print(f"Computing SHAP chunk {idx}/{n_chunks} (rows {start}:{stop})...", flush=True)
    X_chunk = X_eval.iloc[start:stop]
    shap_chunk = explainer.shap_values(X_chunk.values, nsamples=nsamples)
    shap_chunks.append(np.asarray(shap_chunk))

shap_values = np.vstack(shap_chunks)
gc.collect()

print("\nSHAP analysis complete.")

# Global importance bar plot
plt.figure(figsize=(12, 6))
shap.summary_plot(shap_values, X_eval, plot_type="bar", show=False)
plt.tight_layout()
wandb_run.log({"shap_bar": wandb.Image(plt.gcf())})
plt.show()
plt.close()

# Beeswarm plot
if include_beeswarm:
    plt.figure(figsize=(12, 8))
    shap.summary_plot(shap_values, X_eval, show=False)
    plt.tight_layout()
    wandb_run.log({"shap_beeswarm": wandb.Image(plt.gcf())})
    plt.show()
    plt.close()

# Waterfall plot for first sample
if include_waterfall:
    i = 0
    base_value = float(np.mean(predict_fn(X_bg.values)))
    explanation = shap.Explanation(
        values=shap_values[i],
        base_values=base_value,
        data=X_eval.iloc[i].values,
        feature_names=X_eval.columns.tolist(),
    )
    plt.figure(figsize=(10, 4))
    shap.plots.waterfall(explanation, show=False)
    plt.tight_layout()
    wandb_run.log({"shap_waterfall": wandb.Image(plt.gcf())})
    plt.show()
    plt.close()

# Log mean absolute SHAP as a table
mean_abs_shap = np.abs(shap_values).mean(axis=0)
importance_df = pd.DataFrame({
    "feature": feature_columns,
    "mean_abs_shap": mean_abs_shap,
}).sort_values("mean_abs_shap", ascending=False)

wandb_run.log({"shap_importance_table": wandb.Table(dataframe=importance_df)})
wandb_run.summary.update({
    "shap_eval_size": int(len(X_eval)),
    "shap_bg_size": int(len(X_bg)),
    "top_feature": str(importance_df.iloc[0]["feature"]),
    "top_feature_mean_abs_shap": float(importance_df.iloc[0]["mean_abs_shap"]),
})

mem_after = psutil.virtual_memory()
print(f"Available RAM after SHAP cleanup: {mem_after.available / (1024**3):.2f} GB")

# Cleanup large objects explicitly
del X_bg, X_eval, X_train_shap, shap_chunks, shap_values
gc.collect()

wandb.finish()

wandb:   1 of 1 files downloaded.
c:\Users\n_and\OneDrive\Delt skrivebord\Data Science\Speciale\Energinet\py_3.10_blackwell\lib\site-packages\torch\nn\modules\rnn.py:1141: UserWarning: RNN module weights are not part of single contiguous chunk of memory. This means they need to be compacted at every call, possibly greatly increasing memory usage. To compact weights again call flatten_parameters(). (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\cudnn\RNN.cpp:1480.)
  result = _VF.lstm(

Loaded LSTM AE model artifact: DK1_LSTM_AE_2y_2024incl_Lag1_incl_lags_excl_4valFE_lays1_FE_LatDim33_EnHid28_DeHid48_EnDeLays2_model:latest
Available RAM before SHAP: 17.07 GB
Training set size for SHAP: 22944 samples
Number of features: 33

Background sample size (X_bg): 150
Evaluation sample size (X_eval): 300
Chunk size: 25
Kernel SHAP nsamples: 100

Using 150 background data samples could cause slower run times. Consider using shap.sample(data, K) or shap.kmeans(data, K) to summarize the background as K samples.

Computing SHAP chunk 1/12 (rows 0:25)...

100%|██████████| 25/25 [08:47<00:00, 21.10s/it]

Computing SHAP chunk 2/12 (rows 25:50)...

100%|██████████| 25/25 [08:28<00:00, 20.34s/it]

Computing SHAP chunk 3/12 (rows 50:75)...

100%|██████████| 25/25 [08:26<00:00, 20.28s/it]

Computing SHAP chunk 4/12 (rows 75:100)...

100%|██████████| 25/25 [08:31<00:00, 20.47s/it]

Computing SHAP chunk 5/12 (rows 100:125)...

100%|██████████| 25/25 [08:19<00:00, 19.99s/it]

Computing SHAP chunk 6/12 (rows 125:150)...

100%|██████████| 25/25 [08:07<00:00, 19.50s/it]

Computing SHAP chunk 7/12 (rows 150:175)...

 48%|████▊     | 12/25 [04:11<04:31, 20.92s/it]

KeyboardInterrupt: